### ISSUE TITLE
Update / expand / correct :help page in REPL for missing commands

### ISSUE THREAD

**Issue by LeifW** [idris-lang/Idris-dev#1027]
Some commands may be more intended for use from editors, though?

Documentation for the "proof search" command there would be nice. An example invocation of this is on http://www.idris-lang.org/idris-0-9-12-released/

Also, some of the abbreviated forms presented on there are ambiguous / don't seem to work.

`:m` runs ":metavars" (which should not say it has a <metavar> argument - that yields a confusing-looking error: `error: expected: end of input,` ...), so the `:m` abbreviation for `:module` should be removed from that help?

:addmissing might be nice to add to the doc, too.

**Comment by ahmadsalim** [comment]
As per discussion on the PR that tried to fix them, then this seems to be a won't fix.
