### ISSUE TITLE
Duplicate warnings

### ISSUE THREAD

**Issue by puffnfresh** [idris-lang/Idris-dev#1033]
Given `hello.idr`:

```haskell
z : Int -> Int
z 0 = 1
```

We get a duplicate warning when compiling with `--warnpartial`:

```
$ idris --check --warnpartial hello.idr
hello.idr:2:1:Warning - Main.z is not total as there are missing cases
hello.idr:2:1:Warning - Main.z is not total as there are missing cases
```

**Comment by jfdm** [comment]
Testing the above on `Idris 0.9.16-git:b32de5c` this issue appears to be resolved. @puffnfresh If you are happy, then can we close this issue?

**Comment by jfdm** [comment]
I am closing this issue as it is fixed.
