### ISSUE TITLE
QuickCheck library fails to load with "INTERNAL ERROR: Nothing to fill in."

### ISSUE THREAD

**Issue by carlohamalainen** [idris-lang/Idris-dev#1132]
I get this error with the latest copy of QuickCheck on github:

    $ idris QuickCheck.idr -i ../idris-tf-random/src/
         ____    __     _
        /  _/___/ /____(_)____
        / // __  / ___/ / ___/     Version 0.9.12-git:62705e4
      _/ // /_/ / /  / (__  )      http://www.idris-lang.org/
     /___/\__,_/_/  /_/____/       Type :? for help

    Type checking ./QuickCheck.idr
    QuickCheck.idr:112:13:When elaborating right hand side of QuickCheck.r, Integer instance of QuickCheck.Arbitrary, method arbitrary:
    INTERNAL ERROR: Nothing to fill in.
    This is probably a bug, or a missing error message.
    Please consider reporting at https://github.com/idris-lang/Idris-dev/issues
    QuickCheck.idr:122:13:When elaborating right hand side of QuickCheck.r, Nat instance of QuickCheck.Arbitrary, method arbitrary:
    INTERNAL ERROR: Nothing to fill in.
    This is probably a bug, or a missing error message.
    Please consider reporting at https://github.com/idris-lang/Idris-dev/issues
    Metavariables: r, Nat instance of QuickCheck.Arbitrary, r, Integer instance of QuickCheck.Arbitrary

**Comment by ahmadsalim** [comment]
I think Idris QuickCheck has bitrotted now, and it is hard to check whether this bug is fixed so I will close this.
