### ISSUE TITLE
Crash on old .ibc file

### ISSUE THREAD

**Issue by andreasabel** [idris-lang/Idris-dev#1151]
idris: Invalid / corrupted zip format on "/home/abel/play/idris/helloWorld.ibc": incorrect header check

Suggested fix: just rebuild stale .ibc files.

**Comment by melted** [comment]
Since this we have moved once more from zlib to zip. Closing.

**Comment by andreasabel** [comment]
Fine.  I have no clue whether this problem persists anyway.
