### ISSUE TITLE
Refining to subclasses

### ISSUE THREAD

**Issue by ejenk** [idris-lang/Idris-dev#1184]
This is closely related to a <a href="https://github.com/idris-lang/Idris-dev/issues/1141">previous issue</a>. When I try to prove the theorem there using `refine`s instead of `let`s, I eventually run into a goal of type `VerifiedMonoid a`:

```
----------              Other goals:              ----------
{r520},{__pi_arg7513},{hole4},{hole3},{hole2},{hole1},{hole0}
----------              Assumptions:              ----------
 a : Type
 constrarg : VerifiedGroup a
 x : a
 y : a
 p : x <+> y = neutral
----------                 Goal:                  ----------
{class519} : VerifiedMonoid a
```

 I would like to be able to do something like `refine constrarg`, but `constrarg` has type `VerifiedGroup a`. There should still be some way to do this, because `VerifiedGroup` is a subclass of `VerifiedMonoid`, but if there is syntax to do this, I can't find it.

**Comment by edwinb** [comment]
Sorry for taking ages to even notice this. We need to be more systematic (or even, at all systematic) about issue tracking!

The trouble is I don't have enough to even begin reproducing this and I'm wondering if it's even still relevant with the changes in type classes and unification over the last few months. So I'm going to close, and if it is still a problem please open a new issue with a reproducible test case, as far as is possible.
