### ISSUE TITLE
'Can't resolve type class Monoid B' for an instance of 'VerifiedGroup'

### ISSUE THREAD

**Issue by sebzim4500** [idris-lang/Idris-dev#1202]
It seems that whenever you try to make an instance of `VerifiedGroup` idris throws an error:

    module Bug

    data Test : Type where
	    test : Test

    instance Semigroup Test where
	    test <+> test = test

    instance Monoid Test where
    	neutral = test

    instance Group Test where
    	inverse test = test

    instance VerifiedSemigroup Test where
    	semigroupOpIsAssociative test test test = refl

    instance VerifiedMonoid Test where
    	monoidNeutralIsNeutralL test = refl
    	monoidNeutralIsNeutralR test = refl

    instance VerifiedGroup Test where
    	groupInverseIsInverseL test = refl
    	groupInverseIsInverseR test = refl

This is the error message thrown:

    Type checking ./bug.idr
    bug.idr:22:10:
    When elaborating type of Prelude.Algebra.Test instance of     Prelude.Algebra.VerifiedGroup, method groupInverseIsInverseL:
    Can't resolve type class Monoid B
    Metavariables: Test instance of Prelude.Algebra.VerifiedGroup

**Comment by ahmadsalim** [comment]
This seems to work on the latest version of Idris.
