### ISSUE TITLE
Private functions show up in autocomplete and work in :t

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#1209]
They should not.

**Comment by BartAdv** [comment]
How would one determine what's the current module? Been poking around the Idris state and I hadn't spotted anything.

**Comment by steshaw** [comment]
I'm taking a look at this issue (in addition to #1126).

On the completion side of things, I've tracked this down to `Idris.Completion`. We would appear to need a little bit of extra filtering in `names`. It looks like you ought to be able to access the Accessibility of the name and look for ones tagged `export`. However, I've noticed that everything seems to be tagged `public export`. For example, I have a simple example:

```idris
module Foo

foo_private : Nat -> Nat
foo_private n = n

export
foo_visible : Nat -> Nat
foo_visible n = n
```

```idris
module Bar

import Foo

bar_private : Nat -> Nat
bar_private n = n

export
bar_visible : Nat -> Nat
bar_visible n = n
```

I've hacked a special ":context" command that prints out the Context for anything starting with "foo" or "bar":

```sh-session
$ idris Bar.idr
*Bar> :context
fromList [
(bar_private,fromList [(Bar.bar_private,(Case: Prelude.Nat.Nat -> Prelude.Nat.Nat []
...
Inlinable,False,public export,Total,EmptyMI))]),
(bar_visible,fromList [(Bar.bar_visible,(Case: Prelude.Nat.Nat -> Prelude.Nat.Nat []
...
Inlinable,False,public export,Total,EmptyMI))]),
(foo_private,fromList [(Foo.foo_private,(Case: Prelude.Nat.Nat -> Prelude.Nat.Nat []
...
Inlinable,False,public export,Total,EmptyMI))]),
(foo_visible,fromList [(Foo.foo_visible,(Case: Prelude.Nat.Nat -> Prelude.Nat.Nat []
...
Inlinable,False,public export,Total,EmptyMI))])]
```

Note that each function is listed as `public export`. Perhaps this is intended in the REPL? I would appreciate any tips. Perhaps there's a bug in the module loading code?

**Comment by eraserhd** [comment]
@steshaw If you look at `Idris.IBC.processAccess`, you'll notice it sets all functions loaded to `Public` when the phase is `IBC_REPL True`.

**Comment by steshaw** [comment]
Thanks for the tip, @eraserhd. It's been a while but I'm taking a look. 😃

**Comment by steshaw** [comment]
It was a long journey but I've raised a pull request, #4062. Reviews and comments appreciated.

Thanks again, @eraserhd, your comment prompted me to continue looking into this!
