### ISSUE TITLE
Default instance can only find parent class, not ancestor.

### ISSUE THREAD

**Issue by sellout** [idris-lang/Idris-dev#1211]
``` idris
class Foo a where

class Foo a => Bar a where

class Bar a => Baz a where
  instance Foo a where
```

complains

```
line 6 col 12: Default instances must be for a superclass constraint on the containing class.
```

If I change `Baz` to

```
class (Foo a, Bar a) => Baz a where
  instance Foo a where
```

it works fine, but that Foo constraint should be implied.

**Comment by clayrat** [comment]
On 1.0 the error appears both with and without the additional `Foo a` constraint.

**Comment by ahmadsalim** [comment]
@clayrat Could you please elabaorate on what the error is?

**Comment by clayrat** [comment]
(Almost) the same one that is given in first comment:
`Default implementations must be for a super interface constraint on the containing interface.`
