### ISSUE TITLE
Inconsistent qualification rules ?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#123]
The following program type checks:

````
> module B

> import test_modules_A

> A.X = Nat
> A.Y x = Bool
> A.step x False = x
> A.step x True = S x

> reward : (x : A.X) -> A.Y x -> A.X -> Float
> reward x y x' = 0.0
```
with
````
> module A

> X : Set
> Y : X -> Set
> step : (x : X) -> Y x -> X
```
Replacing line 10 of module B with
````
> reward : (x : X) -> Y x -> X -> Float
```
also type checks but replacing line 5 with
````
> X = Nat
```
yields 
````
test_modules_B.lidr:5:No type declaration for B.X
```
Thus, it appears that names on the left-hand side of "assignments" have to be fully qualified while names on the right-hand side do not. Would it be possible to change the name resolution rules for
````
> module B

> import test_modules_A

> X = Nat
> Y x = Bool
> step x False = x
> step x True = S x

> reward : (x : X) -> Y x -> X -> Float
> reward x y x' = 0.0
``` 
to type check ? Is there anything that makes this program more ambiguous than
````
> module B

> import test_modules_A

> A.X = Nat
> A.Y x = Bool
> A.step x False = x
> A.step x True = S x

> reward : (x : X) -> Y x -> X -> Float
> reward x y x' = 0.0
``` 
? I do not think so.

**Comment by edwinb** [comment]
This has been open for ages, and I don't think there's any hope of anything changing without significant changes to the implementation. I think I still prefer requiring explicit qualification for names outside the current module anyway...

**Comment by nicolabotta** [comment]
Edwin, I think we can agree to disagree on preferences (about qualification rules) and I understand that this issue cannot be resolved on short time scales. Still, I believe that this is a very serious issue that will have to be addressed. I assume that we do agree that having to write something like
```
> module B

> import test_modules_A

> A.X = Nat
> A.Y x = Bool
> A.step x False = x
> A.step x True = S x

> reward : (x : A.X) -> A.Y x -> A.X -> Float
> reward x y x' = 0.0
```
instead of simply
```
> module B

> import test_modules_A

> X = Nat
> Y x = Bool
> step x False = x
> step x True = S x

> reward : (x : X) -> Y x -> X -> Float
> reward x y x' = 0.0
```
is not acceptable in any serious application. It makes programs hard to read and understand and gives a positive incentive to write spaghetti code by providing a very obvious reason for inlining (instead of importing) `test_modules_A` in module `B`.

Thus, the relevant question is whether such style can be avoided. At the moment, and for reasons that we cannot elaborate here in full but that we have meanwhile well understood, I believe, this does not appear to be the case. 

Therefore I think that the issue will have to be addressed in the long term, somehow.

**Comment by edwinb** [comment]
I think the real, underlying and complicated issue is that we don't have
a proper module system, and this has to be addressed. We'll get to that,
hopefully in the not too distant future.

Declaring things in one module and defining in another was never really
intended to work, and it would be much better if we avoided the need for
that.

**Comment by nicolabotta** [comment]
Thanks Edwin! Declaring things in one module and implementing them in another, seems (to me) a very natural way of separating specifications from implementations. Type classes already support this a little bit. But we really need a way of organizing and using different implementations of, for example
```
gcd : Nat -> Nat -> Nat
gcdSpec1 : (m : Nat) -> (n : Nat) -> gcd m n `Divisor` m
gcdSpec2 : (m : Nat) -> (n : Nat) -> gcd m n `Divisor` n
gcdSpec3 : (m : Nat) -> (n : Nat) -> (d : Nat) -> d `Divisor` m -> d `Divisor` n -> d `Divisor` gcd m n
```
in such a way that full qualification is only required if there are truly more than one candidates for dispatching. Also, we need to be able to build collections of proofs (of properties of `gcd`) that only rely on (something like) `gcdSpec1`, `gcdSpec3` and `gcdSpec3` and are therefore independent of any particular implementation of `gcd`.

I have been thinking a bit about "specification interfaces" lately and I will try to summarize my thoughts in a short note. Ciao, Nicola
