### ISSUE TITLE
Moving Contribs to separate project.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#1233]
From the meta discussion from the idris developer meeting it was decided that the `contribs` folder would be spun out into a separate project hosted on `idris-dev`.

**Comment by jfdm** [comment]
Giving this issue a bump. I suggest the following actions to address this issue:

1. Spin the Sublime Text 2 support [2] into its own repository under the Idris Hackers organisation.
2. Spin the libraries found in `contribs/lib` (SQLite3 and SimpleParser) into their own separate repositories under the Idris Hackers organisation.
3. Create an `idris-extras` repository in Idris-Dev containing the remaining articles in `contribs`.

If nobody has any objections to these actions, can you let me know by:

    Friday 3, April 2015

Otherwise, I shall carry out these actions for Monday 7, April 2015.

**Comment by LeifW** [comment]
I didn't know about the Sublime support in the contribs dir; there's a separate repo out there:
https://github.com/laughedelic/sublime-idris
My pull request has been sitting there open for a bit. Maybe it could be forked into the Idris Hackers org?

**Comment by jfdm** [comment]
> I didn't know about the Sublime support in the contribs dir;

@LeifW This is one of the reasons we (and by I mean I) was going to spin these out so that they can get appropriate recognition and more eyes on them.

**Comment by david-christiansen** [comment]
Shouldn't we just delete the SQLite and SimpleParser stuff? I think there's a better SQLite binding already, and Lightyear certainly beats the SimpleParser.

**Comment by jfdm** [comment]
As an alternative to deletion (I would rather archive than delete) an alternate suggestion would be to re-purpose these two packages (or just the SimpleParser) as the basis for tutorials in using Idris.

**Comment by david-christiansen** [comment]
I don't think we should purge them from the Git history or anything - they
are archived. But I don't want to maintain them. The Sqlite bit in
particular is fairly hairy and already superseded elsewhere.

**Comment by jfdm** [comment]
By deletion, I do not mean do a stalin and change history, just remove from index. I agree that the SQLite pkg should be deleted, but I think it might be useful to re-purpose the simple parser for a small tutorial. Regardless of any purposed re-purposing, both will be removed.

**Comment by david-christiansen** [comment]
I can get on board with that.
