### ISSUE TITLE
totality of Stream involving recursive references.

### ISSUE THREAD

**Issue by LeifW** [idris-lang/Idris-dev#1262]
Things like this are reported total:

``` haskell
a : Stream Nat
a = map S [1..]

b : Stream Nat
b = 0 :: b
```

But this gets reported as `c is possibly not total due to recursive path c`

``` haskell
c : Stream Nat
c = 0 :: map S c
```

It similarly complains about this version of the Fibonacci sequence:

``` haskell
fibs : Stream Nat
fibs = 0 :: 1 :: zipWith (+) fibs (tail fibs)
```

A scanl impl works, though - `fibs = scanl (+) 0 (1::fibs)`

**Comment by joom** [comment]
```idris
total
fibs : Stream Nat
fibs = 1 :: 1 :: r
  where r : Stream Nat
        r = zipWith (+) fibs (tail fibs)
```
is reported total though.

**Comment by ahmadsalim** [comment]
@joom Can you please report that as a new issue, when rereading this, I think your issue is an actual problematic case, whereas the original one was an inherent limitation of coinduction in Idris.

**Comment by joom** [comment]
Huh, but my definition of `fibs` *is* supposed to be total. (observed behavior is correct) I tried to abuse the recursive call in the `where` clause thing for lists, but couldn't produce a problematic case in which the totality checker says a non-total definition is total. Can you explain what is problematic about my case?

**Comment by ahmadsalim** [comment]
@joom Ah, sorry, I misunderstood.
