### ISSUE TITLE
A few things don’t work inside syntax

### ISSUE THREAD

**Issue by Melvar** [idris-lang/Idris-dev#1283]
Using a syntax rule with a do block on the RHS causes a crash because [`Idris.ParseExpr.extension where update where upd`](https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/ParseExpr.hs#L175-L185) is missing a case for `[]`. This is how I found this problem.

Additionally, [`Idris.ParseExpr.extension where update`](https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/ParseExpr.hs#L155-L187) does not have a case for `PDisamb`, so using a syntax rule that mentions a syntax-bound variable within a `with NS expr` expression causes a “no such variable” error, because the said variable isn’t being replaced when the syntax rule is applied. The same appears to be true of `PRefl`, `PEq`, `PRewrite`, `PIdiom`, `PProof` and `PTactics`. I could probably fix these, but there are a few more constructors I can’t identify immediately, so I decided to report first in case one of the rest also needed to be `update`d under.

**Comment by Melvar** [comment]
@david-christiansen ping.

Here follows a full table of handling of `PTerm` constructors in `update`. I would like to have complete information on which of the ones in question (:question:) should be handled. For some, the question is whether they occur in surface syntax and how (“unclear”). For others it’s a matter of opinion whether they should be allowed in syntax (“opinion”).

`PTerm` constructor | status/comment | mark
------------------- | -------------- | ----
`PQuote Raw` | not handled; unclear, seemingly only introduced in elaboration | :question:
`PRef FC [FC] Name` | handled | :white_check_mark:
`PInferRef FC [FC] Name` | not handled; unclear, seemingly only introduced in elaboration | :question:
`PPatvar FC Name` | not handled; unclear | :question:
`PLam FC Name FC PTerm PTerm` | handled | :white_check_mark:
`PPi  Plicity Name FC PTerm PTerm` | handled | :white_check_mark:
`PLet FC Name FC PTerm PTerm PTerm` | handled | :white_check_mark:
`PTyped PTerm PTerm` | not handled; unclear, seemingly can not occur at all | :question:
`PApp FC PTerm [PArg]` | handled | :white_check_mark:
`PAppImpl PTerm [ImplicitInfo]` | not handled; only introduced in elaboration | :white_check_mark:
`PAppBind FC PTerm [PArg]` | handled | :white_check_mark:
`PMatchApp FC Name` | not handled; should be | :negative_squared_cross_mark:
`PIfThenElse FC PTerm PTerm PTerm` | handled (good job David) | :white_check_mark:
`PCase FC PTerm [(PTerm, PTerm)]` | handled | :white_check_mark:
`PTrue FC PunInfo` | not handled; nothing to do | :white_check_mark:
`PResolveTC FC` | not handled; nothing to do | :white_check_mark:
`PRewrite FC PTerm PTerm (Maybe PTerm)` | not handled; should be | :negative_squared_cross_mark:
`PPair FC [FC] PunInfo PTerm PTerm` | handled | :white_check_mark:
`PDPair FC [FC] PunInfo PTerm PTerm PTerm` | handled | :white_check_mark:
`PAs FC Name PTerm` | not handled; should be | :negative_squared_cross_mark:
`PAlternative [(Name, Name)] PAltType [PTerm]` | handled | :white_check_mark:
`PHidden PTerm` | handled | :white_check_mark:
`PType FC` | not handled; nothing to do | :white_check_mark:
`PUniverse Universe` | not handled; nothing to do | :white_check_mark:
`PGoal FC PTerm Name PTerm` | handled | :white_check_mark:
`PConstant FC Const` | not handled; nothing to do | :white_check_mark:
`Placeholder` | not handled; nothing to do | :white_check_mark:
`PDoBlock [PDo]` | handled; has a fatal but easily fixed bug | :negative_squared_cross_mark:
`PIdiom FC PTerm` | not handled; should be | :negative_squared_cross_mark:
`PReturn FC` | not handled; nothing to do (undocumented, seemingly cannot occur) | :white_check_mark:
`PMetavar FC Name` | not handled; opinion, should or shouldn’t? | :question:
`PProof [PTactic]` | not handled; opinion, maybe should? | :question:
`PTactics [PTactic]` | not handled; should be same as `PProof` | :question:
`PElabError Err` | not handled; nothing to do | :white_check_mark:
`PImpossible` | not handled; nothing to do | :white_check_mark:
`PCoerced PTerm` | not handled; unclear, seemingly only introduced in elaboration | :question:
`PDisamb [[T.Text]] PTerm` | not handled; should be | :negative_squared_cross_mark:
`PUnifyLog PTerm` | not handled; should be | :negative_squared_cross_mark:
`PNoImplicits PTerm` | not handled; should be | :negative_squared_cross_mark:
`PQuasiquote PTerm (Maybe PTerm)` | not handled; opinion, probably should | :question:
`PUnquote PTerm` | not handled; should be same as `PQuasiquote` | :question:
`PQuoteName Name FC` | not handled; opinion, probably shouldn’t? | :question:
`PRunElab FC PTerm [String]` | not handled; opinion, maybe should? | :question:
`PConstSugar FC PTerm` | not handled; unclear, seemingly doesn’t need to be | :question:

`PEq` and `PRefl` mentioned in the original post have since been removed.

**Comment by david-christiansen** [comment]
* `PQuote` doesn't occur in the syntax.  I don't think they ever get built, actually - I vote just deleting it from `PTerm`. My understanding is that it's a relic of an earlier time, and `%runElab` should be enough to get the same effect anyway these days.
 * `PInferRef` is an intermediate elaboration product. It doesn't occur in surface syntax. Perhaps there should be a case there that fails, however, to make this assumption clear.
 * `PPatVar` might occur if the RHS of syntax has a case block in it. Prob. should handle it, or at least rule it out.
 * As far as I can tell, `PTyped` is obsolete. I'd delete it.
 * `PMetavar` should probably be handled. While I think it's ugly to have a syntax extension that introduces a new hole,  I think it's fair to accept it.
 * `PProof` and `PTactics` should *sigh* probably be handled, until we can get rid of them. They are valid expressions.
 *  I don't know about `PCoerced`. Ask @edwinb.
 * `PQuasiquote` and `PUnquote` should be handled.
 * `PQuoteName` should be handled, in case people want to write syntax that resolves a name to a name AST. This might be useful for wrapping a better syntax around `%runElab` calls, for instance.
 * `PRunElab` should also be handled, for the same reason.
 * `PConstSugar` is there to track source locations of things like integer literals for highlighting. I don't *think* that someone can cause a syntax variable to occur in them, but I wouldn't rule it out. Might as well handle it.

**Comment by Melvar** [comment]
To be absolutely clear, “handle” here means “substitute syntax arguments into”, not merely “allow to be present” (there’s a catchall identity case). Your comments on `PMetavar`, `PProof` and `PTactics` make me unsure if this was clear.

It occurs to me that this makes `{}` syntax args usable for other things than binding names: You can introduce a metavariable with one and use one to substitute a quoted name.

**Comment by david-christiansen** [comment]
Yes, that's how I interpreted "handle".

**Comment by Melvar** [comment]
Thank you for clearing that up.

It seems that `PQuote` is in fact introduced in `Idris.Reflection.reifyApp` and `Idris.Elab.Term.runTac`; as I don’t understand these, I can’t delete it.

**Comment by david-christiansen** [comment]
OK. Thanks for doing the searching! I think that we can rewrite `reifyApp` to avoid it, and hopefully `runTac` will disappear once `Elab` is ready to go.
