### ISSUE TITLE
ideslave: refinement by a complete expression

### ISSUE THREAD

**Issue by defanor** [idris-lang/Idris-dev#1307]
The way it is now, it's possible to refine by a function name or a type constructor, but not by some value. But being able to refine by a complete expression is much nicer for interactive editing: in particular, it will not require to remove a meta and replace it with some value manually.

Also being able to refine by a new expression with metavariables is handy too.

Shortly: it would be nice to make ideslave's refinement closer to the one supported by agda2-mode.

**Comment by ahmadsalim** [comment]
@defanor You are welcome to make a PR is you are still interested, but since no one has volunteered so far I will close the issue.
