### ISSUE TITLE
Rewriting goes from right to left, which may be confusing

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#1343]
See e.g. this reddit discussion: http://www.reddit.com/r/programming/comments/29c29t/video_demonstrations_of_programming_and_proving/cijvvq2

Changing this ordering would break essentially all Idris code, but it would be easy to fix with `sym`, and we haven't let that get in the way before (cf `Vect a n` -> `Vect n a`).

If we don't do this, then I think it would make sense to at least add to the FAQ why not.

**Comment by ahmadsalim** [comment]
This totally does not make sense still.

**Comment by ahmadsalim** [comment]
I believe it works now in the correct direction.
