### ISSUE TITLE
unexpected error: redefinition ... (VM* vm, VAL* oldbase) {

### ISSUE THREAD

**Issue by mpkh** [idris-lang/Idris-dev#1355]
``` idris
complete2 : (Nat, Nat, Nat, String) -> (Nat, Nat, Nat, String) -> (Nat, Nat, Nat, String)
complete2 (sc, oa, ca, a) (sb, ob, cb, b) = do
    if ca > 1
        then let step = if ca == 3 then ob - oa
                                   else if sc == 0 then 4
                                                   else sc
             in if cb == 1
                    then if ca == 3
                            then let strX = if debug then (a ++ "\n" ++ b)
                                                     else (a ++ "\n" ++ b)
```

ERROR: idris2652:23514:6: error: redefinition of '_idris_Top_46__123_complete20_125_'  void _idris_Top_46__123_complete20_125_(VM\* vm, VAL\* oldbase) {

C code:

``` c
void _idris_Top_46__123_complete20_125_(VM* vm, VAL* oldbase) {
    INITFRAME;
    RESERVE(1);
    ADDTOP(1);
    LOC(2) = MKSTR(vm, """\x0a""");
    LOC(2) = idris_concat(vm, LOC(2), LOC(1));
    RVAL = idris_concat(vm, LOC(0), LOC(2));
    TOPBASE(0);
    REBASE;
}

void _idris_Top_46__123_complete20_125_(VM* vm, VAL* oldbase) {
    INITFRAME;
    RESERVE(1);
    ADDTOP(1);
    LOC(2) = INTOP(==,LOC(0), LOC(1));
    RESERVE(1);
    TOP(0) = LOC(2);
    SLIDE(vm, 1);
    TOPBASE(1);
    TAILCALL(_idris_Prelude_46_Classes_46_intToBool);
}
```

> redefinition of 'Top.{complete20}'  void _idris_Top.{complete20}(VM\* vm, VAL*..."

``` idris
                            then let strX = (a ++ "\n" ++ b)
```

< - this works...

**Comment by ahmadsalim** [comment]
@ziman You never got around to submit a PR.
Would that be something you would consider still doing?

**Comment by ziman** [comment]
Well, I can fix it blindly, without testing effectiveness.

**Comment by ahmadsalim** [comment]
@ziman I see.
I am unsure how to reproduce it myself though, but it would be nice to have a fix.
Could one e.g. try to check this at a more theoretical level? Like taking the two MNs which we know are conflicting and see how their names are generated.

@edwinb What do you think?

**Comment by melted** [comment]
At some point the relevant code has been changed to `show (MN i s) = "{" ++ str s ++ "_" ++ show i ++ "}"`. As underscore is a valid part of a name it can probably still be fooled, but the example will likely not work anymore.

**Comment by ahmadsalim** [comment]
@melted I will close the issue then, and if it pops up again, we can try it then.
