### ISSUE TITLE
`REPL` commands.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#1407]
Following from the closed PR #1404 and #1027 the `REPL` commands need looking after, and the `REPL` help needs updating.

1. Several on the undocumented (in help) commands can be pruned and are no longer needed---see `:hnf`. Mostly these are internal debugging commands.
2. The `:di` command can possibly be re-purposed.

**Comment by ahmadsalim** [comment]
@jfdm 

It seems that `:hnf` does not longer exist on latest versions.

`:di` is still used for printing debug information, but I guess that shouldn't be documented anyway. Someone didn't bother repurpose it for almost 2 years, so I am closing this.
