### ISSUE TITLE
Optionally allow identical redeclaration

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#1412]
When writing Idris in the Potsdam style, one ends up with modules that do not have implementations of certain names, which other modules that import them then define.

Until we get a real module system, this is something that must be done.

I'd like to propose a (perhaps temporary) pragma `%allow_redeclaration` that allows redeclarations of global constants that have not yet been defined. Idris should then check that the new type is identical to the old one. This would allow what is presently in comments in our biggest code base to become machine-checked annotations, and therefore more useful.

**Comment by ahmadsalim** [comment]
I am closing this as 'won't fix', not because I don't think it might be useful, but since it has been a long time and no one did anything about it.
