### ISSUE TITLE
Implicit arguments that could not be solved sometimes give poor error messages

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#1415]
When an implicit cannot be solved, Idris is currently giving an error message like

```
No such variable t
```

Upon inspection, the application in question has a free implicit named `t`, and the occurrence of `t` in the error message is actually an `MN`. This likely means that the elaborator is leaving behind variables that could not be solved (which makes sense) yet not reporting "Incomplete term".

The error is fixed by adding the implicit argument on its own.

Test case on the way, if we can get something reduced small enough (sitting and hacking with Nicola)

**Comment by ahmadsalim** [comment]
@david-christiansen Can you remember what the test case was? Because the current issue description does not provide much help, unfortunately.

**Comment by ahmadsalim** [comment]
I will close the issue since no new information was provided.
