### ISSUE TITLE
typeclass duplication during proofs

### ISSUE THREAD

**Issue by enn** [idris-lang/Idris-dev#1463]
When trying to prove a fact about a typeclass method we have two instances of the same typeclass: (constraint : E a) -> (class : E a) ->

This seems to be a bug and it blocks me from completing a proof,  here is a test case that lets you reproduce this: https://gist.github.com/enn/ab9f55c6342cf1409714

**Comment by edwinb** [comment]
The cause of this (duplicate constraints) is fixed in master.
