### ISSUE TITLE
Prelude.(!!): index too large

### ISSUE THREAD

**Issue by projedi** [idris-lang/Idris-dev#1472]
Using current HEAD(42dbdbe) I get
`Prelude.(!!): index too large`
when typechecking
```idris
f : (x : ()) -> x = x -> ()
f x _ = x

g : ()
g = f x refl
 where x = ()
```
The problem goes away when `g` implementation is replaced with
```idris
g = f () refl
```

**Comment by melted** [comment]
It still fails to typecheck, but with an empty error message:
```
Type checking .\.\i1472.idr
.\.\i1472.idr:5:3:
Holes: Main.g
```
`refl`has become `Refl` since this report.

**Comment by ahmadsalim** [comment]
Seems to be fixed now.
