### ISSUE TITLE
Improvements to JavaScript binding which require deep thinking about FFI

### ISSUE THREAD

**Issue by IreneKnapp** [idris-lang/Idris-dev#148]
So, this came up in the context of JavaScript, but some of it applies in principle to the C ABI as well, only that function pointers are fairly rare there.

I'm probably going to do the work that I propose myself, but I wanted to create this issue as a central place for discussion, since we don't have the luxury of sitting down in a three-cornered conversation today.

In modern JavaScript libraries, since JS is a functional language, it is not at all uncommon to pass around objects containing functions, and even first-class functions.  In order to interact with these libraries, it is necessary for us to be able to both create and consume these.  The JavaScript functionality that raichoo recently added is almost sufficient, but there's no primitive datatype for representing a reference to foreign value, nor any primitive operation for calling it in the case where it's a function.

Just to give a few examples of things I'd like to be able to do:

The standard JavaScript way to detect whether one is running in a browser or elsewhere (for example, under node.js) is to check for the existence of a global variable "window".  If we could bind to this object at all, we could then compare it to JS's "undefined" value, if we could represent the undefined value...

One approach would be to create a primitive function, perhaps called mkForeignConstant, and a peer to LForeign / DForeign / SForeign, perhaps called LForeignConstant / DForeignConstant / SForeignConstant.  (I'm not sure what the term for these things is - AST nodes?)  The function and various constructors would take just type information and no parameters.  The backend could then do whatever was necessary to implement this.  Notice that it can't be implemented in terms of the existing stuff, because the backend needs to know that the value is not being invoked as a function.  This is because, of course, in most foreign languages there is a distinction between a value, and a function with no parameters.

As another example, the library jQuery allows one to issue an HTTP request and provide a callback function.  We should be able to wrap our Idris functions in foreign objects that allow them to be invoked by foreign code.

One approach here would be to create a primitive function wrapForeign, which takes an Idris function and JavaScript type information, and returns a JavaScript function.  But again we have a problem of how to pass this information through to the backend, and this time I have no suggestion.

As a final example, it is the custom in JavaScript, for portability's sake, to check for the existence of a property in an object prior to using that property's value.  So supposing we wish to call the function console.log (having verified that console exists, by whatever means was invented to resolve our first example), but only if it exists.  My proposal here is to create a "magic" foreign function.  Since punctuation characters are not legal JavaScript names, we can safely extend the backend's implementation to make the foreign function "." translate to the JavaScript dot operator.  It can take the JavaScript object foo provided as the first parameter, and a string bar, and return the result of foo[bar], which will return the "undefined" value if the property is not set.  (Annoyingly, there is a distinction in JavaScript between a property or variable being defined as the undefined value, and being actually undefined, but JS has no means to test this distinction!  But we can't change JS, so oh well.)  At any rate, once we have used the dot operator to access the property, we can go ahead and check it for undefined-ness by the same means as we did in the first example.

**Comment by melted** [comment]
The first two issues, comparing with undefined and wrapping idris functions are addressed in the "new" (it's pretty old now) FFI. As this is for the old FFI, it's best to file new issues based on the current status.
