### ISSUE TITLE
Bad error message when using `fill` tactic with terms instead of reflected terms

### ISSUE THREAD

**Issue by prophile** [idris-lang/Idris-dev#1480]
In the example:

```
foo : Type
foo = ?bar
```

The command:

```
:p bar
fill Nat
```

Fails, with the cryptic error message: `INTERNAL ERROR: Unknown reflection raw term: Prelude.Nat.Nat`.

**Comment by ahmadsalim** [comment]
The tactics system is deprecated now and so this is no longer relevant.
