### ISSUE TITLE
Non-covering function passes as total

### ISSUE THREAD

**Issue by ksf** [idris-lang/Idris-dev#1500]
total
    strBin : (s: Vect n Char) -> Maybe (Vect n Bool)
    strBin [] = Just []
    strBin ('0' :: xs) = Just $ False :: !(strBin xs)
    strBin ('1' :: xs) = Just $ True  :: !(strBin xs)

Note the missing catch-all case:

    strBin (_::_) = Nothing

When evaluating at the REPL:

    *idris> strBin ['1','2']
    Maybe instance of Prelude.Monad.Monad, method >>= (strBin ['2'])
                                                  (\_bindApp0 =>
                                                     Just (True ::
                                                           (_bindApp0))) : Maybe (Vect 2
                                                                                       Bool)

**Comment by david-christiansen** [comment]
Fixed in latest Idris. Thanks!
