### ISSUE TITLE
Confusing behavior with type classes at the type level

### ISSUE THREAD

**Issue by ocharles** [idris-lang/Idris-dev#1513]
I'm working with the following code:

```idris
data Unit : {group : Type} -> (g : group) -> Type where
  MkUnit : Float -> Unit gElem

class MyGroup g where
  identity : g
  gprod : g -> g -> g
  ginv : g -> g

(*) : MyGroup group => Unit g -> Unit g' -> Unit (gprod g g')
(MkUnit a) * (MkUnit b) = MkUnit (a * b)
```

This type checks just fine - but I'm confused about what's going on with `MyGroup group =>` - nothing in the actual function type mentions `group`. Further more, the following also type checks:

```idris
(*) : (MyGroup group, MyGroup nonsense) => Unit g -> Unit g' -> Unit (gprod g g')
(MkUnit a) * (MkUnit b) = MkUnit (a * b)
```

But the following doesn't:

```idris
(*) : Unit g -> Unit g' -> Unit (gprod g g')
(MkUnit a) * (MkUnit b) = MkUnit (a * b)
```

@edwinb said this looked a bit fishy, so here I am, reporting it :)

**Comment by edwinb** [comment]
This code no longer type checks (as it shouldn't) now that I've finally got around to fixing a long standing issue in type class resolution. Resolving classes used to happily solve metavariables in some cases, but the results would be no better than a guess... this is no longer allowed.

I guess mygroup would need to be parameterised over both g and its type here.
