### ISSUE TITLE
Provide a smart aliasing feature

### ISSUE THREAD

**Issue by ahmadsalim** [idris-lang/Idris-dev#1518]
Currently it is possible to some aliasing by simply declaring a function with result type ``Type``, like
```Idris
Pair : Type -> Type -> Type
Pair a b = HVect [a , b]
```
However, such declaration loses injectivity which is that if Pair a b = Pair a' b' then a = a' and b = b' are not necessarily true. It would therefore be desirable to be able to define an injective alias akin to

```Idris
alias 
Pair : Type -> Type -> Type
Pair a b = HVect [a , b]
```

A more advanced feature would be to provide constructor aliases, which can also be used for pattern matching.

```Idris
alias 
Singleton : a -> Vect 1 a
Singleton x = [x]        
```

Since overloading is usually possible in constructors, it would also be desirable to have overloading on aliases (and disambiguate by result type as usual), like overloading ``Singleton``:

```Idris
alias
Singleton : a -> List a
Singleton x = [x]
```

While there is a way to define new pattern syntax, it doesn't work well with pattern matching, e.g.

```Idris
extract : Vec 1 a -> a
extract (Singleton {a = a} x) = the a $ x
```
is not nice to do with pattern syntax, especially with multiple different possible implicit arguments. 

This request aims to make it easier to deprecate things by renaming, and provide ways to make more readable type signatures by simplifying complex types.

**Comment by edwinb** [comment]
Something like this would be very nice, but there hasn't been any proposal on exactly how to make this work or what the feature would look like, and there doesn't seem to be anyone enthusiastic about working on it.

I'm closing this, therefore, but any concrete proposals on this idea would still be welcome (perhaps better as a dragon egg)
