### ISSUE TITLE
Missing functions from libs / base / Data / SortedSet.idr

### ISSUE THREAD

**Issue by mlitchard** [idris-lang/Idris-dev#1554]
I am very new to idris and was looking for a straight forward way to contribute.
I noticed this comment in the above file
-- TODO: add intersection, union, difference

I would like to work this TODO, if it's not being done by anyone already.

**Comment by edwinb** [comment]
I'm closing this since it's not really a useful thing to be tracking in the issue tracker. Still happy to take contributions on this, of course.
