### ISSUE TITLE
Equality type inconsistencies

### ISSUE THREAD

**Issue by trillioneyes** [idris-lang/Idris-dev#1564]
The `(=)` type and its `refl` constructor don't quite behave as normal operators/functions that accept implicit arguments.

```
> :t refl
(input):0:0:Incomplete term refl
> :t fZ
Prelude.Fin.fZ : Fin (S k)
```
It would be nice if you could look at refl's type, so that you could (for example) see the name of its implicit argument if you need to explicitly pass it.

```
> :t (=)
(=) : A -> B -> Type
> :t (=) 'a'
Can't unify Char with Type
> :t (=) Nat
(=) : (B : Type) -> Nat -> B -> Type
```
`(=)`'s arguments are displayed as implicit in its type, but when you call it in prefix form, it expects its normally-implicit arguments to be given as if they were explicit arguments.

**Comment by david-christiansen** [comment]
This is fixed in the latest Idris.
