### ISSUE TITLE
Fix: Improvements to obtaining error location.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#1575]
The `parseProg` function of `src/Idris/Parser.hs`. Currently, when a program fails to parse an error is reported, and the location to. The issue is related to the means in which the location is found. This needs to be addressed.

**Comment by ahmadsalim** [comment]
If I understand correctly this has been solved by now, so I will close it.

**Comment by LeifW** [comment]
There's a FIXME in the source code referencing this issue; should this be removed now?
https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/Parser.hs#L1572
Also, there seems to be some work upstream that seems to be related (it breaks that line, at least)
https://github.com/ekmett/trifecta/commit/4b9f81d92932e1ff9491e500223d139cfcc567f9

**Comment by jfdm** [comment]
For all fixme/todo's that are closed, the corresponding link in the source too. The rationale behind the fixme/todo and source links was to make the source location identifiable by search.

**Comment by ahmadsalim** [comment]
@LeifW I think that we may need to improve the parser at some point.
I think I will reopen this, since I misunderstood the context.
