### ISSUE TITLE
javascript backend takes 9 minutes to translate .ibc file to .js

### ISSUE THREAD

**Issue by stepcut** [idris-lang/Idris-dev#1581]
Using Idris from head it takes over 9 minutes for `make install` to compile this project:

https://github.com/stepcut/stackulator

Further investigation shows that almost all this time can be attributed to the `.ibc -> .js` phase:

```
$ time idris-javascript HtmlView.ibc -o foo.js
539.227 secs
```

When I last compiled this project a couple months ago it definitely did not take that long.

Removing lines from the `main` function in `HtmlView.idr` seems to improve compile time significantly. But it was not easy to pin down any specific piece of the code that was causing the compile times to drag out so long.

I also feel like the generated .js files might be significantly larger than before -- though I don't have any data to support that. But, the output file is 6.6MB, and I seem to remember thinking that the idris javascript backend generated reasonably sized code.

Perhaps both these things can be attributed to the new inliner changes which I believe were added since I last tried compiling this project.

**Comment by rbarreiro** [comment]
Does this still happen with the new js backend?

**Comment by ahmadsalim** [comment]
I will close the issue, since there has been no information provided for some time.
