### ISSUE TITLE
File position as a span.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#1594]
The `getFC` function in `src/Idris/ParseHelpers.hs` returns the file position using the `FC` data structure. This needs to be updated so that a span defined structure is returned.

Of note the instance `TokenParsing` of `IdrisParser` declared on line 50 needs updateding.

**Comment by ahmadsalim** [comment]
This has been fixed

**Comment by LeifW** [comment]
This issue is mentioned multiple times in Idris/Parser/Helpers.hs; should those references be updated?

**Comment by ahmadsalim** [comment]
@LeifW Yeah, if you want to. I believe @david-christiansen fixed this.

**Comment by enolan** [comment]
I don't think this is fixed. `getFC` stills returns a zero length span and is called many times. Sometimes it's called twice and a new `FC` spanning the two locations is returned, but sometimes it's not.

@david-christiansen?

I'm also not sure what solution was intended to be. Something like `MonadParsing m => m a -> m (FC, a)`?

**Comment by ahmadsalim** [comment]
@enolan Thnaks, I have reopened the issue.
If you are interested, could you try to help up with this? It seems that you already have a good idea on what could be improved.

**Comment by ahmadsalim** [comment]
@eamsden I have unassigned you from the issue, since I haven't seen much activity on it for a while and thought that no one should be held back if they wanted to improve on it.
If you are still interested, I can reassign you however.
