### ISSUE TITLE
Unhelpful error message when failing to convert type class instances

### ISSUE THREAD

**Issue by djfarrar** [idris-lang/Idris-dev#1634]
I am not sure if this is a bug or not.  However, if the actual type error is not a bug, perhaps the error message can be refined to give a better clue as to what is wrong.  The following code:

> total maybeGTE : Ord a => a -> Maybe a -> Bool
> maybeGTE x (Just y) = (x >= y)
> maybeGTE x Nothing = True 

> data Sorted : Ord a => List a -> Type where
>       sortedElem : Ord a => (x : a) -> (l : List a) -> (Sorted l) -> 
>                    (So (maybeGTE x (head' l))) -> Sorted (x::l)
>       baseSorted : Ord a => Sorted Nil

> total headNotSorted: Ord a => (l1 : a) -> (l2 : a) -> (ls : List a) -> (prf : Sorted (l2 :: ls)) ->
>                 (contra2 : So (l1 >= l2) -> \_|\_) -> (impos : Sorted (l1 :: l2 :: ls)) -> \_|\_
> headNotSorted l1 l2 ls prf contra2 (sortedElem l1 (l2::ls) prf xact) = contra2 xact
> headNotSorted l1 l2 ls prf contra2 (baseSorted) impossible

Gives the following type check error:
cantconvert.lidr:12:15:Can't convert
        Main.Sorted {a = a}
                    {{constrarg}}
                    (Prelude.List.(::) {a = a}
                                       l1
                                       (Prelude.List.(::) {a = a} l2 ls))
with
        Main.Sorted {a = a}
                    {{constrarg}}
                    (Prelude.List.(::) {a = a}
                                       l1
                                       (Prelude.List.(::) {a = a} l2 ls))

Since both terms in the reported error appear identical, it is not clear what to do to fix it.

(Reproduced on 0.9.14.2-git:a57302c , using :set showimplicits).

Thank you!

**Comment by edwinb** [comment]
I now get different behaviour for this, for two reasons - firstly, changing type class resolution so it doesn't just guess, so you don't get odd results. Secondly, when it gets to 'headNotSorted' it reports an error due to the non-linear match. So I think this can be closed now.
