### ISSUE TITLE
Conditional compilation based on selected codegen.

### ISSUE THREAD

**Issue by MaxOw** [idris-lang/Idris-dev#1642]
I'm  writing a toy 2D game engine and I would like for the user to be able to compile both to binary and javascript without any changes to the code. For that I need conditional compilation based on the selected codegen i.e:

```
#ifdef CodegenJavascript
import Backend.WebGL
#else
import Backend.OpenGL
#endif
```

I couldn't find anything like that in the documentation.

**Comment by ahmadsalim** [comment]
I believe this is already possible because one could parametrise `IO'` with the ffi it is dependent on like `FFI_C` or `FFI_JS`.
