### ISSUE TITLE
Inconsistent error message

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#1643]
The following code
````
> namespace Functorial
>   F : Type -> Type
>   fmap : (alpha -> beta) -> F alpha -> F beta

> -- %hide fmap
> namespace Monadic
>   M : Type -> Type
>   fmap : (alpha -> beta) -> M alpha -> M beta
>   isIn        :  alpha -> M alpha -> Bool
>   tagElem      : (ma : M alpha) -> M (a : alpha ** So (a `isIn` ma))
>   tagElemSpec  : (ma : M alpha) -> fmap Sigma.getWitness (tagElem ma) = ma
```
does not type check. The error message is
````
- + Errors (1)
 `-- ./publications/2014.avoidability/code/test_tag.lidr line 11 col 71:
     When elaborating type of Main.Monadic.tagElemSpec:
     When elaborating argument x to type constructor =:
             Can't unify
                     M beta
             with
                     M alpha
             
             Specifically:
                     Can't unify
                             M beta
                     with
                             M alpha
```
But, as far as I understand, there is no unification problem here: uncommenting the hide directive brings back the expected behavior.

**Comment by ahmadsalim** [comment]
This seems to have been fixed, now giving:

```idris
Type checking ./test.idr
test.idr:12:17:When checking type of Main.Monadic.tagElemSpec:
Can't disambiguate name: Main.Functorial.fmap, Main.Monadic.fmap
```
