### ISSUE TITLE
Dependent pair syntax sugar parse failure

### ISSUE THREAD

**Issue by pelotom** [idris-lang/Idris-dev#1648]
This definition:
```idris
Magma : Type
Magma = (T : Type ** T -> T -> T)
```
fails to parse:
```
/Users/tom/code/tutorials/idris/abstraction.idr:7:1: error: unexpected
    EOF, expected: "->"
<EOF>
^
```
If I understand correctly, it should be precisely equivalent to this:
```idris
Magma : Type
Magma = Sigma Type (\T => T -> T -> T)
```
which both parses and compiles.

**Comment by david-christiansen** [comment]
Still an issue in 0.9.18.

**Comment by jfdm** [comment]
Sorry it has been over two years to address this.

But due to a recent improvement in parsing for dependent pairs.
This works in [v.011](https://github.com/idris-lang/Idris-dev/releases/tag/v0.11).

I am closing now.
