### ISSUE TITLE
Non-exhaustive patterns in function irts_c

### ISSUE THREAD

**Issue by MaxOw** [idris-lang/Idris-dev#1665]
This is the same issue as #1561 that was closed for different reasons. I got is when trying to pass idris function to c

```c
void glutDisplayFunc(void (*func)(void));
```
Then in idris I wrap it like this:
```idris
glutDisplayFunc : IO () -> IO ()
glutDisplayFunc f = 
    mkForeign (FFun "glutDisplayFunc" [FFunction FUnit (FAny (IO ()))] FUnit)
    (const f)
```

I was doing it the same way with javascript backend and it worked fine, so I don't know if I should be doing it differently with c or what. Either way it crushes so that's a problem.

**Comment by ahmadsalim** [comment]
I believe that this should no longer be an issue with @melted improvements to the C API. See [FFI Documentation](https://github.com/idris-lang/Idris-dev/blob/b3fdc3e2dc6256b9cb03e4cee89edb1dd97b081d/docs/reference/ffi.rst)
