### ISSUE TITLE
Productivity checker not recognizing non-productivity of mult on CoNats

### ISSUE THREAD

**Issue by tac-tics** [idris-lang/Idris-dev#167]
codata CoNat = cO | cS (CoNat)

cnplus : CoNat -> CoNat -> CoNat
cnplus    cO  y = y
cnplus (cS x) y = cS (cnplus x y)

-- If first argument is omega and second argument is zero,
-- cnmult omega cO ~> cnplus cO (cnmult omega cO)
-- ~> cnmult omega cO
-- which is a unguarded loop 
cnmult : CoNat -> CoNat -> CoNat
cnmult    cO  y = cO
cnmult (cS x) y = cnplus y (cnmult x y)

omega : CoNat
omega = cS omega

isSuc : CoNat -> Bool
isSuc cO = False
isSuc _ = True

oinf : CoNat
oinf = cnmult cO omega

info : CoNat
info = cnmult omega cO

-- Try taking isSuc oinf 
-- Then try   isSuc info

**Comment by ice1000** [comment]
With the help of guardedness on copatterns this is gonna be much easier.

**Comment by ice1000** [comment]
I've found the typechecker's reduction on coinductive definitions is utterly crashed. When I try to do something like a `cong`, the arguments' types reduce, meaning that their type changes if you apply them as arguments to other functions, which is absurd.
I'm not likely to provide a complete minimum reproducible example because the whole codebase is kinda big and I don't think I should waste time on this abandoned feature.

**Comment by ice1000** [comment]
Ah I feel like my previous comment is stupid, a code example should be made.

```idris
codata Conat : Type where
  Coz : Conat
  Cos : Conat -> Conat

codata Bisimulation : Conat -> Conat -> Type where
  Biz : Bisimulation Coz Coz
  Bis : {a : Conat} -> {b : Conat} ->
        (Bisimulation a b) ->
        (Bisimulation (Cos a) (Cos b))

MuGen : Conat
MuGen = Cos MuGen

MuGenSucc : Bisimulation (Cos MuGen) MuGen
MuGenSucc = Bis MuGenSucc

Add : Conat -> Conat -> Conat
Add Coz b = b
Add (Cos a) b = Cos $ Add b a

Trans : (b : Conat) -> Bisimulation a b -> Bisimulation b c -> Bisimulation a c
Trans Coz Biz Biz = Biz
Trans (Cos x) (Bis a) (Bis b) = Bis (Trans x a b)

AddN : (n : Conat) -> Bisimulation a b -> Bisimulation (Add a n) (Add b n)
AddN Coz Biz = Biz
AddN Coz (Bis x) = Bis x
AddN (Cos x) Biz = Bis (Reflx x)
AddN (Cos x) (Bis y) = Bis (Bis (AddN x y))

Lemma0 : Bisimulation (Add (Cos MuGen) MuGen) (Add MuGen MuGen)
Lemma0 = AddN MuGen MuGenSucc
```

Currently all these lemmas look so beautiful. Now let's try to prove something.
Mutually recursive definition:

```idris
MuGenAdd : Bisimulation MuGen (Add MuGen MuGen)
Lemma1 : Bisimulation MuGen (Add (Cos MuGen) MuGen)
```

For `Lemma1`, if we reduce the type signature of `Lemma1` **once on each side**, which means that `MuGen` reduces to `Cos MuGen` and `Add (Cos MuGen) MuGen` reduces to `Cos (Add MuGen MuGen)`, we're supposed to draw a conclusion like this:

```idris
Lemma1 : Bisimulation (Cos MuGen) (Cos (Add MuGen MuGen))
```

Which can be trivially proved by:

```idris
Lemma1 = Bis MuGenAdd
```

And when you load this in the REPL, you get error.
But now let's continue to `MuGenAdd`'s implementation: we don't need to reduce the type signature, but `Trans` can do the job: `Lemma1` is `Bisimulation MuGen (Add (Cos MuGen) MuGen)`, while `Lemma0` is `Bisimulation (Add (Cos MuGen) MuGen) (Add MuGen MuGen)`, we can `Trans` them into `Bisimulation MuGen (Add MuGen MuGen)`, which is exactly what we want. Have a try.

```idris
MuGenAdd = Trans Lemma1 Lemma0
```

Run the typecheck.

```text
     ____    __     _
    /  _/___/ /____(_)____
    / // __  / ___/ / ___/     Version 1.3.1-git:5188ef3c3
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/
 /___/\__,_/_/  /_/____/       Type :? for help

Idris is free software with ABSOLUTELY NO WARRANTY.
For details type :warranty.
Type checking ./BisiNat.idr
BisiNat.idr:62:10-21:
   |
62 | Lemma1 = Bis MuGenAdd
   |          ~~~~~~~~~~~~
Type mismatch between
        Bisimulation MuGen (Add (Cos (Delay MuGen)) MuGen)
and
        Bisimulation (Cos (Delay MuGen)) (Cos (Delay (Add (Cos (Delay MuGen)) MuGen)))

Specifically:
        Type mismatch between
                Bisimulation (Cos (Delay MuGen)) (Cos (Delay (Add (Cos (Delay MuGen)) (Cos (Delay MuGen)))))
        and
                Bisimulation (Cos (Delay MuGen)) (Cos (Delay (Add (Cos (Delay MuGen)) MuGen)))

BisiNat.idr:63:12-30:
   |
63 | MuGenAdd = Trans Lemma1 Lemma0
   |            ~~~~~~~~~~~~~~~~~~~
When checking right hand side of MuGenAdd with expected type
        Bisimulation MuGen (Add MuGen MuGen)

Type mismatch between
        Bisimulation b c -> Bisimulation a c (Type of Trans b _)
and
        Bisimulation (Cos (Delay MuGen)) (Cos (Delay (Add (Cos (Delay MuGen)) MuGen))) (Expected type)

Specifically:
        Type mismatch between
                Bisimulation a c
        and
                Cos (Delay (Add (Cos (Delay MuGen)) (Cos (Delay MuGen))))

Holes: BisiNat.MuGenAdd, BisiNat.Lemma1
```

![image](https://user-images.githubusercontent.com/16398479/54062073-fe2f6500-41d1-11e9-92cd-fdb9e1890460.png)

**Comment by ice1000** [comment]
Ah, I've just found a solution:

```idris
MuGenAdd : Bisimulation MuGen (Add MuGen MuGen)
MuGenAdd = Trans (Bis MuGenAdd) Lemma0
```

The above content is deleted because they're not related to this issue.
Apologize for bothering.
