### ISSUE TITLE
Indecipherable internal error parsing "../" in import

### ISSUE THREAD

**Issue by rolyp** [idris-lang/Idris-dev#1683]
Just started playing around with Idris. Experimenting with how modules work (I still don't know) lead me to the following internal error:

```idris
module Parser

import ../Lightyear.Core
import Lightyear.Combinators
import Lightyear.Strings
```

This causes:

```
- + Errors (1)
 `-- INTERNAL ERROR: [1m./Parser.idr[0m:[1m3[0m:[1m8[0m: [91merror[0m: expected: Idris
     import ../Lightyear.Core 
            [92m^[0m   
```

(I assume an `INTERNAL ERROR` is a bug by definition, but correct me if I'm wrong.)

**Comment by david-christiansen** [comment]
The parser error is now readable in the latest Idris. Thanks for the report!
