### ISSUE TITLE
Missing IO features

### ISSUE THREAD

**Issue by jech** [idris-lang/Idris-dev#1690]
While trying to use Idris for Real Work, I've found a few things missing in the Prelude:

1. ~~It doesn't seem to be possible to access the `argv` array without resorting to C code;~~

2. Related to the above, it doesn't seem possible to access a C global variable ;

3. ~~There doesn't seem to be an easy way to pass a NULL pointer to a foreign function.~~

I'm also not very happy with openFile and friends -- there's no easy way to push around large quantities of binary data.  Is anything planned, or should I roll my own?

**Comment by ahmadsalim** [comment]
I am closing this since it is now possible to access global variables, see [FFI Documentation](http://docs.idris-lang.org/en/latest/reference/ffi.html) and the rest seems to be mostly discussion.
