### ISSUE TITLE
Obvious search finds variables that are not in scope

### ISSUE THREAD

**Issue by LiamGoodacre** [idris-lang/Idris-dev#1691]
Searching for replacement of `?f_rhs` gives `(__pi_arg)`, this is not in scope

~~~idris
f : Int -> Int
f _ = ?f_rhs
~~~

Searching for replacement of `?g_rhs` gives `a`, this is not in scope

~~~idris
g : Int -> Int
g a with (())
  g _ | () = ?g_rhs
~~~

In these cases I would expect the search to fail.

Idris version: 0.9.15
Installed from cabal

**Comment by david-christiansen** [comment]
Fixed in latest Idris. Thanks!
