### ISSUE TITLE
Args out of range on :casesplit

### ISSUE THREAD

**Issue by rolyp** [idris-lang/Idris-dev#1700]
Case-splitting on the variable `tau` at the bottom of the attached code returns an empty string, which causes Emacs mode to report `Args out of range: "", 0, -1`. The line of code is deleted from the Emacs buffer.

    module Type'
    
       -- Contexts are snoc lists over some set.
       data Cxt c =
          empty |
          (::) (Cxt c) c
    
       -- Context membership (de Bruijn indices).
       data in' : c -> Cxt c -> Type where
          zero : in' c (gamma :: c)
          suc : in' c gamma -> in' c (gamma :: b)
    
       -- Abstract notion of term over a set.
       TermType : Type -> Type
       TermType c = Cxt c -> c -> Type
    
       -- Conor's "friendly fish" operator.
       infixl 4 <><
       (<><) : Cxt c -> List c -> Cxt c
       gamma <>< empty = gamma
       gamma <>< (a :: as) = (gamma :: a) <>< as
    
       -- Renaming over x.
       Ren : TermType c -> Cxt c -> Cxt c -> {a : c} -> Type
       Ren x gamma gamma' {a} = x gamma a -> x gamma' a
    
       -- Renaming which can be shifted under a list of additional binders, a la Conor.
       ShRen : TermType c -> Cxt c -> Cxt c -> {a : c} -> Type
       ShRen {c} x gamma gamma' {a} = (as : List c) -> Ren x (gamma <>< as) (gamma' <>< as) {a}
    
       -- Substitution over x.
       Sub : TermType c -> (TermType c -> TermType c) -> Cxt c -> Cxt c -> {a : c} -> Type
       Sub x y gamma gamma' {a} = x gamma a -> y x gamma' a
    
       -- Shiftable substitution.
       ShSub : TermType c -> (TermType c -> TermType c) -> Cxt c -> Cxt c -> {a : c} -> Type
       ShSub {c} x y gamma gamma' {a} = (as : List c) -> Sub x y (gamma <>< as) (gamma' <>< as) {a}
    
       infixr 10 **
    
       -- There is only one kind, hence type variables inhabit Cxt ().
       data Type' : (Cxt () -> () -> Type) -> Cxt () -> () -> Type where
          unit : Type' x delta ()
    
       infixl 10 ***
    
       (***) : ShSub x Type' delta delta' -> ShRen (Type' x) delta delta'
       (***) theta as tau = ?wib  -- case split on 'tau' doesn't work

**Comment by ahmadsalim** [comment]
I can't seem to reproduce this error on the latest version of Idris, even after smaller modifications, since it fails to type check now.
