### ISSUE TITLE
Missing error message

### ISSUE THREAD

**Issue by laMudri** [idris-lang/Idris-dev#1727]
I was fiddling in the REPL:

    λΠ> the (Vect _ _) [(4 ** the (Fin 4) 2),(7 ** the (Fin 7) 1)]
    INTERNAL ERROR: Nothing to fill in.
    This is probably a bug, or a missing error message.
    Please consider reporting at https://github.com/idris-lang/Idris-dev/issues
As is evident from that line of code, I don't quite get this stuff, so don't expect me to be of much help.

**Comment by david-christiansen** [comment]
It seems that something else has fixed this bug in the meantime. On the latest `master` it reports:
```
λΠ> the (Vect _ _) [(4 ** the (Fin 4) 2),(7 ** the (Fin 7) 1)]
Can't resolve type class Num a
```

which makes reasonable sense. I'll close this issue. Please re-open if I've misunderstood something.
