### ISSUE TITLE
Improvements to the `aiFn`.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#1740]
In the file `src/Idris/AbsSyntax.hs` the where-clauses for the function `aiFn` the function `insImpAcc` requires that for the pattern match:

```
insImpAcc _ expected [] imps
```

A report should be given together with a pruning of alternatives. The task is to implement this. Please liase with a current idris-dev.

**Comment by edwinb** [comment]
Closing this because I'm currently editing this code and I don't know what this TODO means even after looking at it! Either way, it'll be updated with the fix for #2279
