### ISSUE TITLE
Addition of 'eval' directive for evaluation of foreign int types.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#1742]
The addition of an `%eval` directive for the evaluation of at compile time of FInt types.

Please liase with an idrs-dev for more information.

The `TODO` was logged from the function `mkIty` in the where clauses of the `doForeign` function of `src/IRTS/Compiler.hs`

**Comment by ahmadsalim** [comment]
Seems to no longer be relevant
