### ISSUE TITLE
lcm unusually slow

### ISSUE THREAD

**Issue by identicalsnowflake** [idris-lang/Idris-dev#1759]
I was trying some of my Haskell code in Idris, and I came across this:

foldr1 lcm [1..20]

In ghci, this returns immediately, but Idris (at least the repl) hangs indefinitely. I tried reducing it to just [1..10], but it still doesn't return for me. ghci returns within 1 second for me, even for ranges up to [1..100000].

Using a fresh build (0.9.15.1) with libgmp.

**Comment by ahmadsalim** [comment]
This seems to work now correctly with the latest version of Idris:

Result:
```idris
 > ./test
232792560
```

Wolfram Alpha check:
http://www.wolframalpha.com/input/?i=least+common+multiple+of+%7B1,+2,+3,+4,+5,+6,+7,+8,+9,+10,+11,+12,+13,+14,+15,+16,+17,+18,+19,+20%7D
