### ISSUE TITLE
Improvements to Tactic Syntax

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#1766]
The description of 'tactics' for the repl completion engine requires attention. Specifically the syntax for `intro` and `let`. This will require more information from an `idris` developer for intended fixes.

The affected function is: `tacticArgs` in `src/Idris/Completion.hs`.

**Comment by ahmadsalim** [comment]
I am pretty sure this has been superseeded by Elaborator Reflection, so I will close this.
