### ISSUE TITLE
Out of memory typechecking list literals

### ISSUE THREAD

**Issue by projedi** [idris-lang/Idris-dev#1771]
When trying to typecheck this:
```idris
module Main

test : List () -> IO ()

main : IO ()
main = do
  test
    [ ()
    , ()
    , ()
    , ()
    , ()
    , ()
    , ()
    , ()
    , ()
    , ()
    , ()
    , ()
    , ()
    , ()
    , ()
    ]
  test
    [ ()
    , ()
    , ()
    , ()
    , ()
    ]
```
idris eats too much memory.

Profiling shows that all the allocations are coming from `Idris.AbsSyntax.mkUniqueNames`. `traceM`-powered debugging shows that allocation happens while evaluating `Idris.ElabTerm.build` in `Idris.Elab.Clause.elabClause`. And all the memory is used to store the AST which for a list of length
`n` is of size `3^n` because of overloaded `::` and `Nil` constructors.

I tried to understand who and why evaluates the entire AST before pruning the alternatives but got lost.

**Comment by ahmadsalim** [comment]
It doesn't seem to take that much memory on the latest version of Idris, so I will close it.
