### ISSUE TITLE
Install Failure: Mac Mavericks, cabal

### ISSUE THREAD

**Issue by mpettis** [idris-lang/Idris-dev#1801]
Issued `cabal install idris`, got following error:

```
[53 of 93] Compiling IRTS.CodegenC    ( src/IRTS/CodegenC.hs, dist/build/IRTS/CodegenC.o )
[54 of 93] Compiling IRTS.CodegenJavaScript ( src/IRTS/CodegenJavaScript.hs, dist/build/IRTS/CodegenJavaScript.o )
[55 of 93] Compiling Idris.Output     ( src/Idris/Output.hs, dist/build/Idris/Output.o )

src/Idris/Output.hs:18:1: Warning:
    Module ‘Control.Monad.Error’ is deprecated:
      Use Control.Monad.Except instead

<no location info>:
Failing due to -Werror.
Failed to install idris-0.9.15.1
cabal: Error: some packages failed to install:
idris-0.9.15.1 failed during the building phase. The exception was:
ExitFailure 1
```

Not sure how to diagnose this.  Do _not_ have ghc from brew, but from uninstalled it from brew and installed from here: https://www.haskell.org/platform/mac.html

The install from here: https://github.com/idris-lang/Idris-dev/wiki/Idris-on-OS-X-using-Homebrew did not work either.  I'll close this issue if there is something I should know from this link.

**Comment by yoeluk** [comment]
I came across this issue exactly as described here on my OSX machine. Switching to the Idris-dev version sorted me out. However, I just came across this issue, exactly, on my Manjaro machine also. Just saying that it is not exclusively of OSX systems. Perhaps it will be better to leave this issue open even if it is fixed on master for visibility purpose for those that come across it.

**Comment by NobbZ** [comment]
This has nothing to do with Mac OS X and happens on Linux and Windows also.

On my Ubuntu machine I solved this by giving cabal a constraint on mtl: `cabal install idris --force-reinstall --constraint=mtl==2.2.0.1`

This emits also some deprecation warnings in some modules due to some Monad-Transformers (ErrorT deprecated, please use ExceptT, or something), but this does not affect Idris.Output module, which forces -Werror for itself, so one can install idris using the above cabal command. **This is a workaround until next version of idris gets released on hackage**

**Comment by yoeluk** [comment]
@NobbZ thanks! I tried your flags on Manjaro and OSX and worked both times. Interestingly I didn't get any warnings in Manjaro while in OSX I got quite a bit while compiling Network.URI (non related to deprecations) and didn't worked the first time around. For OSX repeating the command with sudo proceeded successfully without warnings in my machine, so for OSX you may need to do: ```sudo cabal install idris --force-reinstall --constraint=mtl==2.2.0.1```

**Comment by NobbZ** [comment]
I imply that every user knows when to and when not to use sudo on his/her system, so I never ever even mention it.

Don't using `sudo` where you should does not harm your system, but using it where you shouldn't can be very dangerous.

**Comment by yoeluk** [comment]
Point well-made however, the error messages are not always a helpful indication that you need to use sudo and it is probably not wholly true that every user knows when sudo is required. For one, I have been surprise way too often. So, I like mentioning it.

Thanks for the tip.
