### ISSUE TITLE
Type checker won't accept type-correctness proof accepted by the prover

### ISSUE THREAD

**Issue by BlackBrane** [idris-lang/Idris-dev#1805]
I've encountered what appears to be a clear case of incorrect behavior on the part of the type checker. In constructing an example of a data type, I'm notified of a unification failure and so I attempt to use the prover to fill in the lemma as usual. The prover is satisfied by a simple `intros; trivial`. It indicates the proof is completed and I add it to the source file. However upon refreshing, Idris complains of a unification failure again. Specifically it says `can't unify x = x with [my data type example]`, and it points to the beginning of the proof in question, so I don't understand what that is about.

A secondary issue is that if all that's required for unification is `intros; trivial`, then shouldn't the code simply type check in the first place without resorting to the prover anyway? 

Here is [the minimal subset of the code](https://gist.githubusercontent.com/BlackBrane/a2c50ba86bc85e76cdb0/raw/fe7778a69d497500fbb71621059d2a9e00817d40/Marked_.idr) needed to reproduce this issue. It has been tested with the current github master.

```idris
module Marked

%default total

||| A set of sites that are either marked (X) or unmarked (O)
||| @ n number of sites
||| @ m number of marked sites
data Marks : (n : Nat) -> (m : Nat) -> Type where
  mZ : Marks Z Z
  mX : Marks n m -> Marks (S n) (S m)
  mO : Marks n m -> Marks (S n) m

||| Compatibility between marked sets such that they can be added without clashing
data Compat : Marks n m -> Marks n j -> Type where
  comZero : Compat mZ mZ
  comOO   : Compat y z -> Compat (mO y) (mO z)
  comOX   : Compat y z -> Compat (mO y) (mX z)
  comXO   : Compat y z -> Compat (mX y) (mO z)

||| Add two marked sets together 
markAdd : {q : Marks n m} -> {w : Marks n j} -> Compat q w -> Marks n (m + j)
markAdd comZero    = mZ
markAdd (comOO c)  = mO (markAdd c)
markAdd (comOX c) ?= mX (markAdd c)
markAdd (comXO c)  = mX (markAdd c)

data Partition : (x : Marks n m) -> Type where
  POne : (y : Marks n m) -> Partition y
  PNxt : (c : Compat y z) -> Partition z -> Partition (markAdd c)

test1 : Partition (mX $ mO mZ)
test1 = POne $ mX $ mO mZ

test2 : Partition (mX $ mX mZ)
test2 ?= {Troubled_lemma} PNxt (comOX $ comXO comZero) test1


---------- Proofs ----------

Troubled_lemma = proof
  intros
  trivial

markAdd_lemma_1 = proof
  intros
  rewrite plusSuccRightSucc m j
  trivial

{-
Type checking ./graph/Marked_.idr
./graph/Marked_.idr:40:16:
When elaborating right hand side of Marked.Troubled_lemma:
Can't unify
        x = x
with
        Partition (mX (mX mZ))
Metavariables: Marked.Troubled_lemma

Tested on HEAD, 0.9.15.1-git:d40cd6f

based on https://github.com/BlackBrane/quantum/blob/master/graph/Marked.idr
-}
```

By the way, Merry Christmas / happy holidays and thanks for all the great work on Idris!

**Comment by ahmadsalim** [comment]
I know this is waaay too late but thanks for reporting the bug!

Since we tactics are now replaced by Elaborator Reflection, I will close this as a won't fix.
