### ISSUE TITLE
At-use library naming

### ISSUE THREAD

**Issue by ghost** [idris-lang/Idris-dev#1810]
A feature suggestion.

In Idris command line after option "-i" give ability to user to specify 2 more parameters:
- A root namespace for the library. Everything in the library would be wrapped into this and would have to be specified as part of qualifying an item from the library. The idea is to invent the root namespace name at usage of the library and not when creating the library. Has 2 benefits: accidental name collision may not stop libraries from being usable simultaneously. It also makes it possible for library developers to avoid thinking about a long-and-hopefully-unique root namespace and repeating it in every source file of the library.
- A boolean parameter meaning if the compiler should create automatic module names for source files which do not have a module declaration at their top - mimicking the folder and file names. In most cases the module names correspond to the file names by convention, and is redundant work.

Perhaps the 2 options may be viewed as independent suggestions.

I do not know the package system, but I guess the principle of at-use name invention can be applied there too.

**Comment by ahmadsalim** [comment]
I will close this feature request since no one has volunteered to implement it and it has been some time. PRs are still welcome.
