### ISSUE TITLE
`infix` clause for backticked operators

### ISSUE THREAD

**Issue by zraffer** [idris-lang/Idris-dev#1811]
In Haskell or Agda we can declare fixity and associativity for named operators, via

```
infixl 5 `oper`   -- Haskell
infixl 5 _oper_   -- Agda
```

We have not such feature in Idris currently. Or I've missed something?

```
./TMP.idr:3:10: error: expected: space
infixl 5 `oper` 
         ^      
```

```
./TMP.idr:3:10: error: expected: space
infixl 5 oper 
         ^    
```

(tested versions: hackage 0.9.15.1 and current github HEAD)

**Comment by ahmadsalim** [comment]
As a I recall, this is indeed not supported in the current idris:
https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/ParseOps.hs.

**Comment by puffnfresh** [comment]
```idris
example : 1 `plus` 1 = 2
example = Refl
```

Looks like it works to me.

**Comment by zraffer** [comment]
@ahmadsalim , I see, thank you. 

Then this issue should be considered to be a feature request.
