### ISSUE TITLE
Setup.hs not compatible with cabal-install 1.22.0.0

### ISSUE THREAD

**Issue by mietek** [idris-lang/Idris-dev#1836]
Idris compiles and installs successfully using _cabal-install_ 1.22.0.0.  However, at runtime, there is a problem:
```
$ idris --libdir
/app/share/$abi/idris-0.9.15.1/
```

`$abi` looks like an unexpanded variable.  I would be expecting `x86_64-linux-ghc-7.8.4` in its place.

The problem does not occur when using _cabal-install_ 1.20.0.3.

**Comment by mietek** [comment]
Looking at `dist/build/autogen/Paths_idris.hs`, both `libdir` and `datadir` seem wrong:
```
libdir     = "/app/lib/$abi/idriskey"
datadir    = "/app/share/$abi/idris-0.9.15.1"
```

Thanks to @david-christiansen for suggesting this may be a Cabal issue.

**Comment by ahmadsalim** [comment]
This doesn't seem to be an issue with the latest `cabal-install` so I am closing this.
