### ISSUE TITLE
recent changes break build: Incompatible ibc version...

### ISSUE THREAD

**Issue by Heather** [idris-lang/Idris-dev#1842]
During `make relib`

``` shell
...
Type checking .\Data\So.idr
Type checking .\Control\Isomorphism.idr
Type checking .\Control\Isomorphism\Primitives.idr
Type checking .\Control\Monad\Identity.idr
Incompatible ibc version.
This library was built with an earlier version of Idris.
Please clean and rebuild.
make[2]: *** [build] Error 1
make[2]: Leaving directory `/c/H/P/Idris-dev/libs/base'
"make"[1]: *** [build] Error 2
"make"[1]: Leaving directory `/c/H/P/Idris-dev/libs'
Failed to install idris-0.9.16
cabal.exe: Error: some packages failed to install:
idris-0.9.16 failed during the building phase. The exception was:
```

**Comment by david-christiansen** [comment]
Did you try a "make relib"? What about a "find . -name *.ibc -delete"?

2015-01-11 19:32 GMT-08:00 Heather <notifications@github.com>:

**Comment by jfdm** [comment]
There is also the make file command: `make lib_clean`. This runs `idris --clean` on each of the packages within `libs`.

As the output from the transcript provided reports: Please *clean* and *rebuild*.

**Comment by Heather** [comment]
@david-christiansen it was `make relib` , `find` on windows works different iirc..

@jfdm thanks, I will try today evening
