### ISSUE TITLE
:x getChar doesn't work

### ISSUE THREAD

**Issue by TorosFanny** [idris-lang/Idris-dev#1845]
Here is what I got:
Idris> :x getChar
Symbol "getchar" not found
INTERNAL ERROR: Could not call foreign function "getchar" with args [EBind Pi {binderTy = World, binderKind = Type} <<fn>>,FFun ("getchar") (Prelude.List.Nil (FTy)) (FIntT (ITNative)),w]
This is probably a bug, or a missing error message.
Please consider reporting at https://github.com/idris-lang/Idris-dev/issues

But getLine, putChar, etc all worked fine

**Comment by david-christiansen** [comment]
The part of Idris that runs :x has to special-case some functions in the C RTS due to issues with 32-bit GHC and 64-bit Homebrew on OS X. I probably missed that one when implementing them.

**Comment by david-christiansen** [comment]
It's fixed in #1846. I'm going to sleep now, and I'll merge when Travis has run. If you need the fix before tomorrow, you can pull from #1846's branch.

Thanks for a useful and concise bug report!
