### ISSUE TITLE
Build failure when trying to install Idris 0.9.15.1

### ISSUE THREAD

**Issue by flexibeast** [idris-lang/Idris-dev#1848]
Using `cabal install idris` (`cabal-install` version 1.22.0.0) to install Idris on a 64-bit Debian Wheezy system, all Idris prerequisites build and install successfully, but Idris itself fails to build:

    ...
    [53 of 93] Compiling IRTS.CodegenC    ( src/IRTS/CodegenC.hs, dist/build/IRTS/CodegenC.o )
    [54 of 93] Compiling IRTS.CodegenJavaScript ( src/IRTS/CodegenJavaScript.hs, dist/build/IRTS/CodegenJavaScript.o )
    [55 of 93] Compiling Idris.Output     ( src/Idris/Output.hs, dist/build/Idris/Output.o )

    src/Idris/Output.hs:18:1: Warning:
        Module ‘Control.Monad.Error’ is deprecated:
          Use Control.Monad.Except instead

    <no location info>: 
    Failing due to -Werror.
    cabal: Error: some packages failed to install:
    idris-0.9.15.1 failed during the building phase. The exception was:
    ExitFailure 1

**Comment by LeifW** [comment]
Sorry, a new version of mtl got released that added some warnings, and we
had "fail on warnings" on in that release. You'll have to constrain mtl to
a lower version, or install from the git repo.

**Comment by flexibeast** [comment]
@LeifW:

Yeah, installing from the repo worked without issues. Thanks!

**Comment by david-christiansen** [comment]
Sorry for that! Hopefull we'll get a new release soon.
