### ISSUE TITLE
idris-0.9.16 depends on streaming-commons-0.1.9.1 which failed to install.

### ISSUE THREAD

**Issue by rosenk** [idris-lang/Idris-dev#1853]
cabal install -j8 idris
Resolving dependencies...
Notice: installing into a sandbox located at
/home/rosen/home/dev/idris/.cabal-sandbox
Configuring ansi-terminal-0.6.2.1...
Downloading auto-update-0.1.2.1...
Configuring base64-bytestring-1.0.0.1...
Configuring binary-0.7.2.3...
Downloading byteorder-1.0.4...
Configuring data-default-class-0.0.1...
Configuring dlist-0.7.1...
Configuring fingertree-0.1.0.0...
Configuring prelude-extras-0.4...
Configuring split-0.2.2...
Downloading bytestring-builder-0.10.4.0.1...
Downloading cereal-0.4.1.1...
Downloading easy-file-0.2.0...
Downloading parallel-3.2.0.6...
Building base64-bytestring-1.0.0.1...
Building dlist-0.7.1...
Building ansi-terminal-0.6.2.1...
Building prelude-extras-0.4...
Building data-default-class-0.0.1...
Building binary-0.7.2.3...
Building fingertree-0.1.0.0...
Building split-0.2.2...
Downloading random-1.1...
Downloading stm-2.4.4...
Configuring tagged-0.7.3...
Installed data-default-class-0.0.1
Downloading stringsearch-0.3.6.5...
Downloading syb-0.4.4...
Configuring primitive-0.5.4.0...
Installed dlist-0.7.1
Configuring terminfo-0.4.0.0...
Installed split-0.2.2
Building tagged-0.7.3...
Downloading text-1.2.0.4...
Downloading unix-compat-0.4.1.4...
Configuring utf8-string-0.3.8...
Installed prelude-extras-0.4
Building primitive-0.5.4.0...
Configuring network-2.6.0.2...
Installed base64-bytestring-1.0.0.1
Downloading word8-0.1.1...
Building utf8-string-0.3.8...
Configuring transformers-0.4.2.0...
Installed ansi-terminal-0.6.2.1
Configuring zlib-0.5.4.2...
Installed tagged-0.7.3
Building transformers-0.4.2.0...
Installed fingertree-0.1.0.0
Configuring auto-update-0.1.2.1...
Building zlib-0.5.4.2...
Configuring byteorder-1.0.4...
Installed primitive-0.5.4.0
Downloading vector-0.10.12.2...
Building auto-update-0.1.2.1...
Building byteorder-1.0.4...
Configuring bytestring-builder-0.10.4.0.1...
Installed auto-update-0.1.2.1
Configuring cereal-0.4.1.1...
Installed byteorder-1.0.4
Building terminfo-0.4.0.0...
Configuring parallel-3.2.0.6...
Installed utf8-string-0.3.8
Building cereal-0.4.1.1...
Configuring easy-file-0.2.0...
Installed zlib-0.5.4.2
Building parallel-3.2.0.6...
Building easy-file-0.2.0...
Building bytestring-builder-0.10.4.0.1...
Configuring data-default-instances-base-0.0.1...
Installed bytestring-builder-0.10.4.0.1
Configuring data-default-instances-containers-0.0.1...
Installed binary-0.7.2.3
Downloading unix-time-0.3.4...
Configuring data-default-instances-old-locale-0.0.1...
Installed terminfo-0.4.0.0
Configuring random-1.1...
Installed parallel-3.2.0.6
Building data-default-instances-base-0.0.1...
Configuring stm-2.4.4...
Installed easy-file-0.2.0
Building data-default-instances-containers-0.0.1...
Building network-2.6.0.2...
Building data-default-instances-old-locale-0.0.1...
Configuring data-default-instances-dlist-0.0.1...
Installed data-default-instances-base-0.0.1
Configuring stringsearch-0.3.6.5...
Installed data-default-instances-containers-0.0.1
Building random-1.1...
Building stm-2.4.4...
Configuring syb-0.4.4...
Installed data-default-instances-old-locale-0.0.1
Building data-default-instances-dlist-0.0.1...
Building stringsearch-0.3.6.5...
Building syb-0.4.4...
Configuring unix-compat-0.4.1.4...
Installed data-default-instances-dlist-0.0.1
Configuring text-1.2.0.4...
Installed stm-2.4.4
Building unix-compat-0.4.1.4...
Building text-1.2.0.4...
Configuring word8-0.1.1...
Installed unix-compat-0.4.1.4
Configuring ansi-wl-pprint-0.6.7.1...
Installed syb-0.4.4
Configuring reflection-1.5.1...
Installed transformers-0.4.2.0
Downloading mmorph-1.0.4...
Downloading transformers-base-0.4.3...
Building word8-0.1.1...
Building ansi-wl-pprint-0.6.7.1...
Downloading transformers-compat-0.3.3.4...
Building reflection-1.5.1...
Installed word8-0.1.1
Configuring vector-0.10.12.2...
Configuring unix-time-0.3.4...
Installed random-1.1
Configuring data-default-0.5.3...
Installed ansi-wl-pprint-0.6.7.1
Configuring haskeline-0.7.1.3...
Installed reflection-1.5.1
Building vector-0.10.12.2...
Configuring mtl-2.2.1...
Installed cereal-0.4.1.1
Building data-default-0.5.3...
Configuring transformers-base-0.4.3...
Installed data-default-0.5.3
Building mtl-2.2.1...
Building transformers-base-0.4.3...
Configuring mmorph-1.0.4...
Installed transformers-base-0.4.3
Downloading monad-control-1.0.0.1...
Building haskeline-0.7.1.3...
Building unix-time-0.3.4...
Building mmorph-1.0.4...
Configuring transformers-compat-0.3.3.4...
Installed network-2.6.0.2
Configuring monad-control-1.0.0.1...
Installed mtl-2.2.1
Configuring exceptions-0.6.1...
Installed stringsearch-0.3.6.5
Installed mmorph-1.0.4
Building transformers-compat-0.3.3.4...
Building monad-control-1.0.0.1...
Installed unix-time-0.3.4
Building exceptions-0.6.1...
Installed transformers-compat-0.3.3.4
Configuring distributive-0.4.4...
Configuring optparse-applicative-0.11.0.1...
Building optparse-applicative-0.11.0.1...
Installed monad-control-1.0.0.1
Downloading lifted-base-0.2.3.3...
Installed exceptions-0.6.1
Configuring lifted-base-0.2.3.3...
Building lifted-base-0.2.3.3...
Building distributive-0.4.4...
Installed distributive-0.4.4
Installed lifted-base-0.2.3.3
Downloading resourcet-1.1.3.3...
Configuring resourcet-1.1.3.3...
Building resourcet-1.1.3.3...
Installed optparse-applicative-0.11.0.1
Installed resourcet-1.1.3.3
Installed haskeline-0.7.1.3
Installed vector-0.10.12.2
Configuring vector-binary-instances-0.2.1.0...
Building vector-binary-instances-0.2.1.0...
Installed vector-binary-instances-0.2.1.0
Installed text-1.2.0.4
Configuring blaze-builder-0.3.3.4...
Downloading hashable-1.2.3.1...
Downloading parsec-3.1.8...
Configuring tagsoup-0.13.3...
Configuring xml-1.3.13...
Configuring hashable-1.2.3.1...
Building blaze-builder-0.3.3.4...
Configuring parsec-3.1.8...
Building xml-1.3.13...
Building tagsoup-0.13.3...
Building hashable-1.2.3.1...
Building parsec-3.1.8...
Installed hashable-1.2.3.1
Downloading case-insensitive-1.2.0.3...
Downloading nats-1...
Configuring unordered-containers-0.2.5.1...
Configuring case-insensitive-1.2.0.3...
Downloading scientific-0.3.3.5...
Configuring nats-1...
Building unordered-containers-0.2.5.1...
Configuring scientific-0.3.3.5...
Building case-insensitive-1.2.0.3...
Building nats-1...
Building scientific-0.3.3.5...
Installed xml-1.3.13
Installed nats-1
Installed blaze-builder-0.3.3.4
Downloading blaze-markup-0.6.2.0...
Downloading fast-logger-2.2.3...
Installed case-insensitive-1.2.0.3
Configuring fast-logger-2.2.3...
Downloading streaming-commons-0.1.9.1...
Configuring blaze-markup-0.6.2.0...
Downloading http-types-0.8.5...
Configuring streaming-commons-0.1.9.1...
Configuring http-types-0.8.5...
Building fast-logger-2.2.3...
Building blaze-markup-0.6.2.0...
Building streaming-commons-0.1.9.1...
Building http-types-0.8.5...
Failed to install streaming-commons-0.1.9.1
Build log ( /home/rosen/home/dev/idris/.cabal-sandbox/logs/streaming-commons-0.1.9.1.log ):
Configuring streaming-commons-0.1.9.1...
Building streaming-commons-0.1.9.1...
Preprocessing library streaming-commons-0.1.9.1...

Data/Streaming/ByteString/Builder.hs:12:8:
    Could not find module `Data.ByteString.Builder.Extra'
    Perhaps you meant
      Data.ByteString.Lazy.Builder.Extras (from bytestring-0.10.0.2)
    Use -v to see a list of the files searched for.
Installed parsec-3.1.8
Configuring network-uri-2.6.0.1...
Installed fast-logger-2.2.3
Building network-uri-2.6.0.1...
Installed scientific-0.3.3.5
Configuring attoparsec-0.12.1.2...
Building attoparsec-0.12.1.2...
Installed tagsoup-0.13.3
Installed http-types-0.8.5
Installed blaze-markup-0.6.2.0
Configuring blaze-html-0.7.0.3...
Installed unordered-containers-0.2.5.1
Downloading semigroups-0.16.0.1...
Configuring uniplate-1.6.12...
Downloading vault-0.3.0.4...
Building blaze-html-0.7.0.3...
Configuring semigroups-0.16.0.1...
Configuring vault-0.3.0.4...
Building uniplate-1.6.12...
Building semigroups-0.16.0.1...
Building vault-0.3.0.4...
Installed network-uri-2.6.0.1
Installed vault-0.3.0.4
Downloading wai-3.0.2.2...
Configuring wai-3.0.2.2...
Building wai-3.0.2.2...
Installed wai-3.0.2.2
Downloading wai-logger-2.2.3...
Configuring wai-logger-2.2.3...
Installed semigroups-0.16.0.1
Configuring charset-0.3.7...
Downloading void-0.7...
Building wai-logger-2.2.3...
Configuring void-0.7...
Building charset-0.3.7...
Installed uniplate-1.6.12
Building void-0.7...
Installed wai-logger-2.2.3
Installed void-0.7
Downloading contravariant-1.2.0.1...
Configuring contravariant-1.2.0.1...
Building contravariant-1.2.0.1...
Installed contravariant-1.2.0.1
Configuring comonad-4.2.2...
Installed blaze-html-0.7.0.3
Installed charset-0.3.7
Building comonad-4.2.2...
Installed comonad-4.2.2
Configuring semigroupoids-4.2...
Building semigroupoids-4.2...
Installed semigroupoids-4.2
Configuring bifunctors-4.2...
Configuring profunctors-4.3.2...
Building bifunctors-4.2...
Building profunctors-4.3.2...
Installed attoparsec-0.12.1.2
Downloading aeson-0.7.0.6...
Configuring css-text-0.1.2.1...
Configuring parsers-0.12.1.1...
Configuring aeson-0.7.0.6...
Building css-text-0.1.2.1...
Building aeson-0.7.0.6...
Building parsers-0.12.1.1...
Installed css-text-0.1.2.1
Configuring xss-sanitize-0.3.5.4...
Installed profunctors-4.3.2
Building xss-sanitize-0.3.5.4...
Installed bifunctors-4.2
Downloading free-4.10.0.1...
Configuring free-4.10.0.1...
Building free-4.10.0.1...
Installed xss-sanitize-0.3.5.4
Installed parsers-0.12.1.1
Installed free-4.10.0.1
Downloading adjunctions-4.2...
Configuring keys-3.10.1...
Downloading lens-4.7...
Building keys-3.10.1...
Configuring adjunctions-4.2...
Building adjunctions-4.2...
Configuring lens-4.7...
Building lens-4.7...
Installed keys-3.10.1
Installed adjunctions-4.2
Downloading kan-extensions-4.2.1...
Configuring kan-extensions-4.2.1...
Building kan-extensions-4.2.1...
Installed aeson-0.7.0.6
Installed kan-extensions-4.2.1
Downloading pointed-4.2...
Configuring pointed-4.2...
Building pointed-4.2...
Installed pointed-4.2
Configuring reducers-3.10.3...
Building reducers-3.10.3...
Installed reducers-3.10.3
Installed lens-4.7
Configuring trifecta-1.5.1...
Building trifecta-1.5.1...
Installed trifecta-1.5.1
cabal: Error: some packages failed to install:
cheapskate-0.1.0.2 depends on streaming-commons-0.1.9.1 which failed to
install.
idris-0.9.16 depends on streaming-commons-0.1.9.1 which failed to install.
streaming-commons-0.1.9.1 failed during the building phase. The exception was:
ExitFailure 1
wai-extra-3.0.4.1 depends on streaming-commons-0.1.9.1 which failed to
install.

**Comment by edwinb** [comment]
Have you done a cabal update? It installs fine here.

**Comment by rosenk** [comment]
Yes. If I haven't done update I wouldn't have the 0.9.16 as latest idris version in the first place.

**Comment by rosenk** [comment]
I've manulay installed older version which fixes the problem:
cabal install  streaming-commons-0.1.8.1
maybe it is realted to this one:
https://github.com/fpco/streaming-commons/issues/16

**Comment by edwinb** [comment]
oh yes, good point :). I’ve done a fresh clean install in a new sandbox and still can’t reproduce it though - this could be due to various other dependencies not being constrained right. streaming-commons isn’t a direct dependency of Idris so we don’t have any constraints on it at all.

I don’t know if there’s anything we can do about this, other than making more binary releases which don’t require cabal.

Edwin.

**Comment by jfdm** [comment]
FWIW, for those experiencing issues installing `idris` from hackage due to streaming commons playing funny buggers, the following command worked for me.

```sh
cabal install --force-reinstalls streaming-commons-0.1.8.1 idris
```

**Comment by manny-fp** [comment]
I'm working on fixing fpco/streaming-commons#16, which I have been unable to reproduce locally.  Can those of you on this issue let me know which versions of GHC and cabal-install you are using, and whether you are able to install streaming-common-0.1.9.1?  I'm interested both in reports for those of you who can't install it *as well as* those of you who *can*.

**Comment by manny-fp** [comment]
One more request: if experiencing this problem, please provide the output of `cabal install -v3 streaming-commons-0.1.9.1`.  If using GHC 7.6.3, it *should* contain something like this, where it decides to install bytestring-builder since you have an older version of bytestring that doesn't include Data.ByteString.Builder:

```
[_24] rejecting: streaming-commons-0.1.9.1:-use-bytestring-builder (conflict: unix => bytestring==0.10.0.2/installed-4f9..., streaming-commons-0.1.9.1:use-bytestring-builder => bytestring>=0.10.2.0)
[_24] trying: streaming-commons-0.1.9.1:+use-bytestring-builder
[_25] trying: bytestring-builder-0.10.4.0.1/installed-358... (dependency of streaming-commons-0.1.9.1:+use-bytestring-builder)
```

**Comment by rosenk** [comment]
$ cabal -V
cabal-install version 1.22.0.0
using version 1.22.0.0 of the Cabal library 

$ ghc -V
The Glorious Glasgow Haskell Compilation System, version 7.6.3

$ cabal install -j8 streaming-commons-0.1.9.1
Resolving dependencies...
Notice: installing into a sandbox located at
/home/rosen/home/dev/haskell/.cabal-sandbox
Configuring bytestring-builder-0.10.4.0.1...
Configuring random-1.1...
Configuring stm-2.4.4...
Configuring zlib-0.5.4.2...
Configuring transformers-0.4.2.0...
Configuring network-2.6.0.2...
Configuring text-1.2.0.4...
Building stm-2.4.4...
Building random-1.1...
Building zlib-0.5.4.2...
Building transformers-0.4.2.0...
Building text-1.2.0.4...
Installed stm-2.4.4
Building bytestring-builder-0.10.4.0.1...
Installed bytestring-builder-0.10.4.0.1
Installed zlib-0.5.4.2
Building network-2.6.0.2...
Installed random-1.1
Installed transformers-0.4.2.0
Installed network-2.6.0.2
Installed text-1.2.0.4
Configuring blaze-builder-0.3.3.4...
Building blaze-builder-0.3.3.4...
Installed blaze-builder-0.3.3.4
Configuring streaming-commons-0.1.9.1...
Building streaming-commons-0.1.9.1...
Failed to install streaming-commons-0.1.9.1
Build log ( /home/rosen/home/dev/haskell/.cabal-sandbox/logs/streaming-commons-0.1.9.1.log ):
Configuring streaming-commons-0.1.9.1...
Building streaming-commons-0.1.9.1...
Preprocessing library streaming-commons-0.1.9.1...

Data/Streaming/ByteString/Builder.hs:12:8:
    Could not find module `Data.ByteString.Builder.Extra'
    Perhaps you meant
      Data.ByteString.Lazy.Builder.Extras (from bytestring-0.10.0.2)
    Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
streaming-commons-0.1.9.1 failed during the building phase. The exception was:
ExitFailure 1

**Comment by rosenk** [comment]
[__0] trying: blaze-builder-0.3.3.4/installed-995... (user goal)
[__1] trying: base-4.6.0.1/installed-8aa... (dependency of blaze-builder-0.3.3.4/installed-995...)
[__2] trying: rts-1.0/installedbuil... (dependency of base-4.6.0.1/installed-8aa...)
[__3] trying: integer-gmp-0.5.0.0/installed-2f1... (dependency of base-4.6.0.1/installed-8aa...)
[__4] trying: ghc-prim-0.3.0.0/installed-d52... (dependency of base-4.6.0.1/installed-8aa...)
[__5] trying: bytestring-0.10.0.2/installed-4f9... (dependency of blaze-builder-0.3.3.4/installed-995...)
[__6] trying: deepseq-1.3.0.1/installed-5cc... (dependency of bytestring-0.10.0.2/installed-4f9...)
[__7] trying: array-0.4.0.1/installed-3b7... (dependency of deepseq-1.3.0.1/installed-5cc...)
[__8] trying: bytestring-builder-0.10.4.0.1/installed-dce... (user goal)
[__9] trying: network-2.6.0.2/installed-5f6... (user goal)
[_10] trying: unix-2.6.0.1/installed-f12... (dependency of network-2.6.0.2/installed-5f6...)
[_11] trying: time-1.4.0.1/installed-10d... (dependency of unix-2.6.0.1/installed-f12...)
[_12] trying: old-locale-1.0.0.5/installed-672... (dependency of time-1.4.0.1/installed-10d...)
[_13] trying: random-1.1/installed-6f1... (user goal)
[_14] trying: stm-2.4.4/installed-53e... (user goal)
[_15] trying: text-1.2.0.4/installed-a11... (user goal)
[_16] trying: transformers-0.4.2.0/installed-0ec... (user goal)
[_17] trying: zlib-0.5.4.2/installed-ce0... (user goal)
[_18] trying: streaming-commons-0.1.9.1 (user goal)
[_19] trying: streaming-commons-0.1.9.1:!bench
[_20] trying: streaming-commons-0.1.9.1:!test
[_21] trying: process-1.1.0.2/installed-76e... (dependency of streaming-commons-0.1.9.1)
[_22] trying: filepath-1.3.0.1/installed-b12... (dependency of process-1.1.0.2/installed-76e...)
[_23] trying: directory-1.2.0.1/installed-91a... (dependency of streaming-commons-0.1.9.1)
[_24] rejecting: streaming-commons-0.1.9.1:-use-bytestring-builder (conflict: blaze-builder => bytestring==0.10.0.2/installed-4f9..., streaming-commons-0.1.9.1:use-bytestring-builder => bytestring>=0.10.2.0)
[_24] trying: streaming-commons-0.1.9.1:+use-bytestring-builder
[_25] done

**Comment by melted** [comment]
This has been fixed upstream.
