### ISSUE TITLE
"incomplete term" is a confusing error message

### ISSUE THREAD

**Issue by enolan** [idris-lang/Idris-dev#1860]
Idris complains "incomplete term" when it can't solve an implicit variable.
```
Idris> Prelude.List.(++) [] []
(input):0:0:Incomplete term [] ++ []
Idris> Prelude.List.(++) {a = Nat} [] []
[] : List Nat
```
This is a really useless error message for a beginner. You don't know why it's incomplete or how to complete it. Better would be something along the lines of "couldn't solve implicit variable a : Type".

**Comment by david-christiansen** [comment]
I agree that this error message is not the most beginner-friendly!

My ideal message would be something like:
```
Idris> Prelude.List.(++) [] []
(input):0:0:Incomplete term [] ++ []:
  Couldn't determine value of implicit argument a : Type to function (++).
```

In the meantime, if you use the Emacs REPL, you can click "show term interaction widgets" in the menu and then right-click the [] ++ [] in the error message and click "show implicits" to see where it failed. Or, if not in Emacs, you can type `:set showimplicits` and then re-do the evaluation to get an error where you can see the unsolved holes.

**Comment by Melvar** [comment]
That wouldn’t necessarily help if you have multiple calls to `(++)` in your term. What I’m imagining right now is for every implicit that has a hole somewhere under it to be shown by default, just as a thought.

**Comment by david-christiansen** [comment]
Good idea!

/David (from phone)
Den 18 jan 2015 18:47 skrev "Melvar Chen" <notifications@github.com>:

**Comment by davidfstr** [comment]
> for every implicit that has a hole somewhere under it to be shown by default

+1. Ran into this confusing "Incomplete term" message yesterday. IRC folks helped out.
