### ISSUE TITLE
On Mac OS X import statements are case insensitive.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#1865]
On Mac OS X, import statements are treated in a case insensitive manner, on Linux import statements are case sensitive. I believe `System.Directory` respects the underlying file system. This can lead to  code that will only compile on Mac OS X.

The fix *should be* minor and will involve adjusting (I believe) `Imports.hs` to check in a case sensitive test that the given file name in the import statement is equal to an element in the list of available files. I do not have time to do it at the moment.

*edit: spelling \& and incorrect advice*

**Comment by david-christiansen** [comment]
Nice catch!

**Comment by jfdm** [comment]
The joys of working on to platforms...

**Comment by jfdm** [comment]
Having checked on a Mac OS X machine, and Linux machine. The issue has been resolved, and thus can be closed. 

Cheers @Chobbes
