### ISSUE TITLE
0.9.14.2 fails to install with GHC 7.8.3 (not typechecking)

### ISSUE THREAD

**Issue by ocramz** [idris-lang/Idris-dev#1866]
`cabal install idris`, ghc 7.8.3, cabal 1.20.0.2 doesn't typecheck:

[38 of 98] Compiling IRTS.Java.ASTBuilding ( src/IRTS/Java/ASTBuilding.hs, dist/dist-sandbox-fe729cfc/build/IRTS/Java/ASTBuilding.o )

src/IRTS/Java/ASTBuilding.hs:63:22:
    Couldn't match expected type ‘[Exp]’ with actual type ‘Exp’
    In the second argument of ‘ArrayIndex’, namely
      ‘(Lit $ Int (toInteger pos))’
    In the expression: ArrayIndex target (Lit $ Int (toInteger pos))
    In an equation for ‘@!’:
        (@!) target pos = ArrayIndex target (Lit $ Int (toInteger pos))
cabal: Error: some packages failed to install:
idris-0.9.14.2 failed during the building phase. The exception was:
ExitFailure 1

**Comment by david-christiansen** [comment]
This is an old version of Idris, and I don't think we're likely to fix build failures in it. Have you tried 0.9.16? Is there a reason why you need 0.9.14?

**Comment by ocramz** [comment]
not yet, how often is the Hackage version updated? I'll just try 0.9.16 from here then

**Comment by david-christiansen** [comment]
The Hackage version gets updated when we think that the benefit from new features and fixes outweighs the upgrade hassle. It's a bit unpredictable :)
