### ISSUE TITLE
Pattern variables can't start with _

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#1868]
The following doesn't work:
```
module Underscore

foo : Nat -> Nat
foo _bar = Z

```

It fails with the error:
```
     When elaborating left hand side of foo:
     Can't unify
             Nat
     with
             argTy -> retTy
```

which makes me think it's not lexing the underscore as part of the name, but rather as a separate pattern.

The following type checks:
```
module Underscore

foo : Nat -> Nat
foo bar = Z
```

**Comment by edwinb** [comment]
Yes, the lexer doesn’t allow this, I’ve noticed this before. I don’t think this was deliberate (I certainly didn’t intend it). It’s probably a quick fix if anyone has a moment to look at it.

**Comment by david-christiansen** [comment]
I agree that it should be easy - I just wanted to document it quickly while working through exercises with some folks here.
