### ISSUE TITLE
Idris Segfaults due to Allocator issues.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#1871]
Using Idris HEAD (10c9dec) I am experiencing segaults (11) when testing my XML library. 

To reproduce: First we have to install a 'fixed' version of Lightyear. Second we obtain the latest version of the library, and run the test program. Running the test program generates the seg fault.

```sh
git clone git@github.com:jfdm/lightyear.git
git checkout fixes
make install

git clone git@github.com:jfdm/idris-xml.git
make test
```
[The result of `gdb` backtrace and valgrind are available.](https://gist.github.com/jfdm/fa2c064ad71a324f69cd).

If I get a chance to produce a MFE, I shall post it here.

**Comment by david-christiansen** [comment]
Did @melted's fix to the allocation of integers solve this? I just tried the code (with suitable modifications for newer Idris and Lightyear versions) and I didn't see any segfaults. Instead, I saw:
``
make -C test build
make[1]: Entering directory '/home/davidc/Code/Idris/idris-xml/test'
idris  --build test.ipkg
Type checking ./TestRunner.idr
Type checking ./ParsingTest.idr
Type checking ./NotWellFormed.idr
Type checking ./WellFormed.idr
Type checking ./Main.idr
make[1]: Leaving directory '/home/davidc/Code/Idris/idris-xml/test'
(cd test; ./a.out)
Test 1
Test Passed
Test Passed
Test Passed
Test Passed
Test Passed
Test 2
Test Passed
Test Passed
Test Failed as Expected
Test Passed
Test Passed
Test Passed
Test Passed
Test Passed
Test Passed
Test Passed
Test 10
Test Passed
Not WellFormed Tests
Running Test 1
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Running Test 2
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
-------> Expected failing test passed...
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Running Test 3
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Running Test 4
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Running Test 5
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Running Test 6
Test Failed as Expected
Test Failed as Expected
-------> Expected failing test passed...
-------> Expected failing test passed...
-------> Expected failing test passed...
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Running Test 7
Test Failed as Expected
-------> Expected failing test passed...
-------> Expected failing test passed...
Test Failed as Expected
-------> Expected failing test passed...
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Test Failed as Expected
Running Test 8
Test Failed as Expected
-------> Expected failing test passed...
-------> Expected failing test passed...
Test Failed as Expected
-------> Expected failing test passed...
Test Failed as Expected
Test Failed as Expected
-------> Expected failing test passed...
Test Failed as Expected
Test Failed as Expected
-------> Expected failing test passed...
Test Failed as Expected
make -C test clean
make[1]: Entering directory '/home/davidc/Code/Idris/idris-xml/test'
idris --clean test.ipkg
Removing Main.ibc
Removing TestRunner.ibc
Removing ParsingTest.ibc
Removing WellFormed.ibc
Removing NotWellFormed.ibc
Removing 00test-idx.ibc
Removing /home/davidc/Code/Idris/idris-xml/test/a.out
find . -name "*~" -delete
rm -rf a.out
make[1]: Leaving directory '/home/davidc/Code/Idris/idris-xml/test'
``

**Comment by jfdm** [comment]
From what I remember, the above output should be expected. The 'expected failing test passed' style errors are project errors rather than Idris errors.
