### ISSUE TITLE
load .idr file takes long time because of trivial error

### ISSUE THREAD

**Issue by eallik** [idris-lang/Idris-dev#1873]
I was watching https://www.youtube.com/watch?v=P82dqVrS8ik and wanted to try out the code demonstrated:

```idris
module VerifiedOption

data Option a = Some a | None

instance Semigroup a => Semigroup (Option t) where  -- <<< t instead of a
  (Some a1) <+> (Some a2) = Some $ a1 <+> a2
  None <+> a2 = a2
  a1 <+> _ = a1
```

loading that file into idris takes ~20 seconds. This is on 0.9.16 on OS X Mavericks.

**Comment by edwinb** [comment]
Hmm, that is rather slow isn't it... I'll take a look (not sure it'll be particularly soon though) - this sort of error is really useful to see since it helps identify any other sources of slowness in typechecking. Thanks for reporting.

**Comment by eallik** [comment]
only glad I could help! keen on seeing Idris become more mainstream :) dynamically typed languages for systems programming are only a temporary craze!

**Comment by edwinb** [comment]
This seems to have been fixed a while ago - it certainly doesn't behave slowly now - so I'm closing this.
