### ISSUE TITLE
Pretty print produces invalid LaTeX for anonymous functions.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#1876]
The following `Idris` snippet:

``` idris
mkNodeList : List (Document a) -> {auto prf : ValidNode a} -> List $ Document NODE
mkNodeList Nil = Nil
mkNodeList xs = map (\x => Node x) xs
```

when pretty printed using `:pp latex 80`, produces invalid LaTeX for the Verbatim mode used. This is a result of command chars being specified using `commandchars=\\\{\}`. As a result braces and backslashes, used in implicit arguments and anonymous functions, cause Verbatim to think there is a LaTeX command. 

The fix will be to ensure that braces are escaped properly (`\{auto implic\}`), and backslashes are created using the `\textbackslash{}` command.

**Comment by david-christiansen** [comment]
This will be a bit fiddly - probably I'll have to get rid of the stringly typed representation to avoid double-escapes and the like.
