### ISSUE TITLE
map (\x => x * 0.5) (the (List Float) [2.1, 3.4]) can't resolve Functor

### ISSUE THREAD

**Issue by LeifW** [idris-lang/Idris-dev#1891]
Reported in IRC by joergr_, as an example from the book "Seven More Languages in Seven Weeks".

The error message is `Can't resolve type class Functor (\__pi_arg => List Float)` There is a `Functor List`, however.  This works if you remove the type ascription (which was probably necessary at the time the book was written): `map (\x => x * 0.5) [2.1, 3.4]`, or even `map (* 0.5) [2.1, 3.4]`. It also works at the repl if `(the (List Float) [2.1, 3.4])` is assigned to an intermediate var before being mapped over, either via `:let a =  (the (List Float) [2.1, 3.4])`, or `let a = (the (List Float) [2.1, 3.4]) in map (\x => x * 0.5) a`

**Comment by jrings** [comment]
The actual example in the book is `map (\x => x * 0.5) (the (List Float) [3.14, 2.78])`.
Thanks for filing this issue!

**Comment by edwinb** [comment]
This works fine in master
