### ISSUE TITLE
Taking a function argument named P for Language.Reflection.P ?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#1893]
The following error
````
     When elaborating type of with block in Main.lala, iso:
     When elaborating an application of constructor Language.Reflection.P:
             Can't unify
                     alpha
             with
                     NameType
```
pops up when type checking
````
> import Data.Fin
> import Data.Vect
> import Control.Isomorphism

> %default total 

> Dec1 : (P : alpha -> Type) -> Type
> Dec1 {alpha} P  =  (a : alpha) -> Dec (P a) 

> Prop1 : (alpha -> Type) -> Type
> Prop1 {alpha} P = (a : alpha) -> (p : P a) -> (q : P a) -> p = q 

> Finite : Type -> Type
> Finite alpha = Exists (\ n => Iso alpha (Fin n))

> asSigmaVect : (alpha : Type) ->
>               (P : alpha -> Type) ->
>               Finite alpha -> 
>               Dec1 {alpha} P -> 
>               (n ** Vect n (Sigma alpha P))
 
> lula : (alpha : Type) -> 
>        (Q : alpha -> Type) ->
>        Finite alpha -> 
>        Dec1 {alpha} Q -> 
>        Prop1 {alpha} Q -> 
>        Finite (Sigma alpha Q)
> lula alpha Q fa dp pp with (getWitness (asSigmaVect alpha Q fa dp))
>   | (S n) = Evidence (S n) iso where
>     iso  :  Iso (a : alpha ** Q a) (Fin (S n))

> lala : (alpha : Type) -> 
>        (P : alpha -> Type) ->
>        Finite alpha -> 
>        Dec1 {alpha} P -> 
>        Prop1 {alpha} P -> 
>        Finite (Sigma alpha P)
> lala alpha P fa dp pp with (getWitness (asSigmaVect alpha P fa dp))
>   | (S n) = Evidence (S n) iso where
>     iso  :  Iso (a : alpha ** P a) (Fin (S n))
```
Notice that "lulu" type checks fine. It seems that the elaborator gets confused when the second argument (of lula = lala) is named "P" which should obviously not be the case.

**Comment by edwinb** [comment]
It's likely that P is a parameter of Sigma here, so is already in scope. 
We don't explicitly shadow in these cases - maybe we should?

(Sorry no time to look properly now, so this is only a guess - if anyone 
can investigate and back up that claim we can decide what to do with it)

**Comment by edwinb** [comment]
This works in master (not counting a totality checking problem which I haven't looked closely at, so may well be okay, but is certainly a different issue if not.)
