### ISSUE TITLE
deriving instances

### ISSUE THREAD

**Issue by mekeor** [idris-lang/Idris-dev#19]
Idris can't derive instances of data types automatically yet.

```haskell
data Day = Monday | Tuesday | Wednesday | Thursday | Friday | Saturday | Sunday
           deriving (Show, Eq, Ord, Bounded, Read)
```

**Comment by jfdm** [comment]
The reason why this issue has been left open for so long is that 'deriving' involving Dependent Types is not so straightforward in comparison to non-dependent types. If deriving were to be supported then it should be available for both kinds of types, and no special cases should be added. It is all or nothing.

**Comment by edwinb** [comment]
I'm going to close this because it's a bit open ended, and it's not even obvious that deriving is exactly what we want. There is work going on by @david-christiansen to make instance creation much easier, and more general than deriving.

**Comment by corazza** [comment]
@edwinb Can you expand a bit on what @david-christiansen has been doing, I'm interested in what "to make instance creation much easier, and more general than deriving." means, thank you

**Comment by DestyNova** [comment]
Is elaborator reflection really a suitable alternative to deriving? It doesn't seem easier at all...
