### ISSUE TITLE
Equality and application operator

### ISSUE THREAD

**Issue by defanor** [idris-lang/Idris-dev#1903]
`Not $ 2 = 3` evaluates to `(Not 2) = 3`, instead of the expected `Not (2 = 3)`.

**Comment by peterohanley** [comment]
($) and (=) defined in the parser, not as Idris operators. I don't see precedences specified.
https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/ParseOps.hs#L39

**Comment by bmsherman** [comment]
@peterohanley The order of the definitions with that list determines the precedences. As equality is listed last (just after `$`), its precedence is the lowest. It's very possible that the relationship between these precedences is intended to be that way.

**Comment by defanor** [comment]
Then it's probably fine, though the usual ("expected", "from Haskell") purpose of `$` is to be of the lowest precedence.
I don't mind closing the issue if it's really the intended behaviour; apparently it is like that since https://github.com/idris-lang/Idris-dev/commit/865bf99906c1bfe1d979b334c9f377cde539eefa, so @edwinb should know.
