### ISSUE TITLE
Possible Idris RTS error with `realloc`

### ISSUE THREAD

**Issue by ahmadsalim** [idris-lang/Idris-dev#1908]
I have recently turned on cppcheck on a PR, and it found the following error:
`[rts/idris_rts.c:616]: (error) Common realloc mistake: 'line_buf' nulled but not freed upon failure`

A suggestion on how to fix it can be found in (search for memleakOnRealloc):
http://www.mantidproject.org/How_to_fix_CppCheck_Errors

**Comment by ahmadsalim** [comment]
This is fixed by #2005, so I am going to close the issue.

**Comment by david-christiansen** [comment]
Good catch!

/David (from phone)
