### ISSUE TITLE
Add "rename" command in the prover to rename the current hole

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#1914]
This allows `MN` holes to be unfocused and then later refocused. If vars in the prover are resolved, then this is trivial; if not, then it's almost trivial. Scoping rules should deal with conflicts.

```
----------              Other goals:              ----------
f,arg
----------              Assumptions:              ----------
 arg : Nat
 x : Nat
----------                 Goal:                  ----------
{hole9} : Nat
thingy> rename body
----------              Other goals:              ----------
f,arg
----------              Assumptions:              ----------
 arg : Nat
 x : Nat
----------                 Goal:                  ----------
body : Nat
thingy> 
```

**Comment by david-christiansen** [comment]
I guess a better design is to have separate `renameGoal g` and `renameAssumption h h'` commands.

**Comment by david-christiansen** [comment]
After a day's work, I can safely say that this is in fact not low-hanging fruit :-)

**Comment by david-christiansen** [comment]
I've abandoned work on this in favor of the new tactics language, and thus am removing myself.

**Comment by ahmadsalim** [comment]
I will close this issue since your elaborator reflection mechanism supersedes the old tactic language, which is now deprecated.
