### ISSUE TITLE
Data.Fin.(+) return type is too weak

### ISSUE THREAD

**Issue by davidfstr** [idris-lang/Idris-dev#1915]
Currently:

```
Data.Fin.(+) : Fin n -> Fin m -> Fin (n + m)
```

But it should be:

```
Data.Fin.(+) : Fin n -> Fin m -> Fin (n + m - 1)
```

**Comment by davidfstr** [comment]
I tried fixing this myself, but my "fix the unification errors" fu is too weak.

**Comment by peterohanley** [comment]
Data.Fin.(+) : Fin n -> Fin m -> Fin (n + m)
is the correct behavior. Consider Fin Z + Fin Z, which has 0 elements and is thus Fin Z.

**Comment by david-christiansen** [comment]
Luckily, 0 + 0 - 1 = 0 when dealing with Nat!

/David (from phone)
Den 13 feb 2015 05:12 skrev "peterohanley" <notifications@github.com>:

**Comment by peterohanley** [comment]
I was wrong, the plus function indeed does behave like that.

It type checks, but it's very ugly. Have I missed any tricks? (I only found out `replace` existed while writing this, for example)

```idris
%default total
help' : (j : Nat) -> (k:Nat) -> (j + (S k)) = (k + (S j))
help' j k = ?help2

help : Fin (m + (S n)) -> Fin (n + (S m))
help {m=m} {n=n} a = replace (help' m n) a

helpSSP : (j : Nat) -> (k:Nat) -> (S (pred (j + S k))) = (plus j (S k))
helpSSP  Z     Z    = Refl
helpSSP  Z    (S k) = Refl
helpSSP (S k)  Z    = Refl
helpSSP (S k) (S j) = Refl

total
plus : Fin n -> Fin m -> Fin (pred (n + m))
plus {n=S n} {m=S m}  FZ     FZ    = rewrite sym (plusSuccRightSucc n m) in FZ {k=plus n m}
plus {n=S n} {m=S m}  FZ    (FS x) = let tem = weakenN n (FS x) in ?rhs 
plus {n=S n} {m=S m} (FS x)  FZ    = let tem = shift m (FS x) in help tem
plus {n=S n} {m=S m} (FS x) (FS y) = let v = FS (plus x (FS y)) in replace (helpSSP n m) v

---------- Proofs ----------


Main.help2 = proof
  intros
  rewrite plusSuccRightSucc j k
  rewrite plusSuccRightSucc k j
  rewrite plusCommutative j k
  trivial


Main.rhs = proof
  intros
  rewrite plusSuccRightSucc n m
  rewrite plusCommutative m n
  exact tem

```

**Comment by edwinb** [comment]
How about this instead:

Data.Fin.(+) : Fin (S n) -> Fin (S m) -> Fin (S n + m)

Minus might be the obvious thing to do here but functions in return 
types can lead to complications later, especially functions which have 
strange corner cases like minus does on negative numbers. At least 
'plus' is easier to reason about.

Also, Fin Z is empty so not much point in allow that in inputs.

**Comment by davidfstr** [comment]
> Data.Fin.(+) : Fin (S n) -> Fin (S m) -> Fin (S (n + m))

+1. Works. Same effect.

**Comment by ahmadsalim** [comment]
I can't seem to find `Data.Fin.(+)` anymore and since there has been no PR I will close this issue.
