### ISSUE TITLE
Can't unify P a1 with P a1

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#1920]
The program
````
> import Data.Vect

> %default total 

> Dec1 : {A : Type} -> (P : A -> Type) -> Type
> Dec1 {A} P = (a : A) -> Dec (P a) 

> filter : {A : Type} ->
>          {P : A -> Type} ->
>          Dec1 P ->
>          Vect n A -> 
>          (m : Nat ** Vect m A)
> filter d1P Nil = (Z ** Nil)
> filter d1P (a :: as) with (filter d1P as)
>   | (n ** as') with (d1P a)
>     | (Yes _) = (S n ** a :: as')
>     | (No  _) = (n ** as')

> filterSpec : {A : Type} ->
>              {P : A -> Type} ->
>              (d1P : Dec1 P) ->
>              (a : A) ->
>              (as : Vect n A) ->
>              Elem a as ->
>              (p : P a) ->
>              Elem a (getProof (filter d1P as))
> filterSpec {A} {P} d1P a Nil  Here       p impossible
> filterSpec {A} {P} d1P a Nil (There prf) p impossible
> filterSpec {A} {P} d1P a1 (a1 :: as) Here p with (filter d1P as)
>   | (n ** as') with (d1P a1)
>     | (Yes _) = Here {x = a1} {xs = as'}
>     | (No  contra) = void (contra p)
> filterSpec {A} {P} d1P a1 (a2 :: as) (There prf) p with (filter d1P as)
>   | (n ** as') with (d1P a2)
>     | (Yes _) = There {x = a1} {xs = as'} {y = a2} (filterSpec {A} {P} d1P a1 as prf p) -- (*)
>     | (No  _) = filterSpec d1P a1 as prf p
```
does not pass type checking. The error message is
````
     When elaborating argument p to Main.filterSpec:
             Can't unify
                     P a1
             with
                     P a1
```
for line (*). Is this the expected behavior ? Any idea how to avoid this problem ?

**Comment by edwinb** [comment]
I'm getting a different message in master:

```
Type checking ./foo.lidr
foo.lidr:35:23:
When elaborating right hand side of with block in with block in Main.filterSpec:
When elaborating an application of constructor Data.Vect.There:
        Can't unify
                Elem a1 (getProof (filter d1P as))
        with
                Elem a1 as'
        
        Specifically:
                Can't unify
                        getProof (filter d1P as)
                with
                        as'
```

Which version do you have? Is everything up to date? (Not that I know what might have changed recently to change such a message)

**Comment by nicolabotta** [comment]
Hi, I have 0.9.16-git:807d623. I get your very same error message if I do not give the implicit arguments in the recursive call to `filterSpec`, that is:
````
>     | (Yes _) = There {x = a1} {xs = as'} {y = a2} (filterSpec d1P a1 as prf p) -- (*)
```
I have explicitly given the implicits to try to nail down the problem. Best, N.

**Comment by edwinb** [comment]
I'm getting the same message with 807d623 --- I can't reproduce this problem. I think it's right to report an error (I tried `let rec = filterSpec {A} {P} d1P a1 as prf p in ?foo` and poked around the types) but I don't see where the Can't unify P a1 with P a1 is coming from. Can you see if it still happens in master?

**Comment by nicolabotta** [comment]
It does not. With master I get 
````
- + Errors (1)
 `-- unification1.lidr line 35 col 22:
     When elaborating right hand side of with block in with block in Main.filterSpec:
     When elaborating an application of constructor Data.Vect.There:
             Can't unify
                     Elem a1 (getProof (filter d1P as))
             with
                     Elem a1 as'
             
             Specifically:
                     Can't unify
                             getProof (filter d1P as)
                     with
                             as'
```
no matter whether I have `filterSpec d1P a1 as prf p` or `filterSpec {A} {P} d1P a1 as prf p` in (*). Same result with
````
> filterSpec {A} {P} d1P a1 (a2 :: as) (There prf) p with (filter d1P as)
>   | (n ** as') with (d1P a2)
>     | (Yes _) = let rec = filterSpec d1P a1 as prf p in There {x = a1} {xs = as'} {y = a2} rec
>     | (No  _) = filterSpec {A} {P} d1P a1 as prf p
```
I am probably missing something obvious but what's the problem with `as'`and `getProof (filter d1P as)`?

**Comment by edwinb** [comment]
The knowledge that `filter d1P as = (n ** as')` isn't present in the elaborated form, and you'll need that to be allowed to use the result of the recursive call. Elaboration will abstract over `filter d1P as` in the type, but it won't automatically be rewritten when it crops up in the type of the recursive call.

Idris 0.1 had a syntax for exposing that equality (`with proof` rather than just `with`), which might help here if I can work out what its syntax should be now. Otherwise you'll need to find a way to feed the proof in (I can only think of ugly ways at the moment).

**Comment by nicolabotta** [comment]
Thanks Edwin, an ugly way would still be better than no way. I am a bit lost at this point, but the proof pattern seems quite obvious and I would expect the problem to show up in a number of similar proofs. Ciao, N.

**Comment by edwinb** [comment]
To be honest the only way I can think of at the moment is manual 
elaboration of the top level with block, to feed in the equality proof 
as well

(i.e., it takes something like `(x : _) -> (x = filter d1P as) -> ...`)

then you'd match on the `x` as before, but would also have the proof for 
rewriting before making the recursive call.

I tried some ways of doing this without resorting to that trick, but 
then abstracting over `fitler d1P as` didn't work because the argument 
to `with` was something else.

I have encountered this pattern before, but not for a really long time, 
so I've never got around to extending `with` to do it automatically. 
Clearly it's time I did that. It's certainly a pattern we'll see again.

**Comment by nicolabotta** [comment]
*I have encountered this pattern before, but not for a really long time, so I've never got around to extending `with` to do it automatically. Clearly it's time I did that. It's certainly a pattern we'll see again.*

Edwin, I think the pattern arises when one tries to prove elementary properties of Vect, Fin, etc. operations and quantifiers . I have started to collect the results we need for the SDP theory in a small collections of *Operations and *Properties files in https://github.com/nicolabotta/SeqDecProbs.
The idea is that, at some point some and after careful revision, some of these results could be integrated in Idris libraries. Best, Nicola

**Comment by nicolabotta** [comment]
Edwin, I have no idea how difficult it would be to fix this issue but it seems to affect virtually every proof of basic properties of elementary functions: filter, max, argmax, etc. 

I have collected three further examples in https://github.com/nicolabotta/SeqDecProbs/blob/master/VectProperties.lidr (all marked with `issue1920`).

The problem seems to show up whenever recursive calls appear in nested `with` expressions. Recursive calls in one-level `with`expressions work as expected. Ciao, Nicola

**Comment by edwinb** [comment]
I've had a look at VectProperties, and again I don't see any instance of an error message of the form "Can't unify P a1 with P a1" - I'm getting different things in the error message. Or is the issue something else?

**Comment by nicolabotta** [comment]
Edwin, on Feb.14 we have realized that the error message with master was NOT anymore "Can't unify P a1 with P a1", see posts above. Your remark from Feb 14 was:

edwinb referenced this issue from a commit on Feb 14
	@edwinb 	Expose equality proofs in with rule … 

afterwards, I have collected all the instances of this problem in the metavariables issue1920.0...7 in

 https://github.com/nicolabotta/SeqDecProbs/blob/master/VectProperties.lidr

The tentative proofs are commented out in the same line just after the metavariables. Best, Nicola

**Comment by david-christiansen** [comment]
Hi Nicola,

For whatever reason, the `rewrite` syntax is failing me, but I just got your example to typecheck on master using the `with ... proof...` syntax:

```
> import Data.Vect

> %default total 

> Dec1 : {A : Type} -> (P : A -> Type) -> Type
> Dec1 {A} P = (a : A) -> Dec (P a) 

> filter : {A : Type} ->
>          {P : A -> Type} ->
>          Dec1 P ->
>          Vect n A -> 
>          (m : Nat ** Vect m A)
> filter d1P Nil = (Z ** Nil)
> filter d1P (a :: as) with (filter d1P as)
>   | (n ** as') with (d1P a)
>     | (Yes _) = (S n ** a :: as')
>     | (No  _) = (n ** as')

> filterSpec : {A : Type} ->
>              {P : A -> Type} ->
>              (d1P : Dec1 P) ->
>              (a : A) ->
>              (as : Vect n A) ->
>              Elem a as ->
>              (p : P a) ->
>              Elem a (getProof (filter d1P as))
> filterSpec {A} {P} d1P a Nil  Here       p impossible
> filterSpec {A} {P} d1P a Nil (There prf) p impossible
> filterSpec {A} {P} d1P a1 (a1 :: as) Here p with (filter d1P as)
>   | (n ** as') with (d1P a1)
>     | (Yes _) = Here {x = a1} {xs = as'}
>     | (No  contra) = void (contra p)
> filterSpec {A} {P} d1P a1 (a2 :: as) (There prf) p with (filter d1P as) proof itsEqual
>   | (n ** as') with (d1P a2)
>     | (Yes indeed) = There {x = a1} {xs = as'} {y = a2} $
>                        replace {P=\rec => Elem a1 (getProof rec)} (sym itsEqual) $
>                          filterSpec {A} {P} d1P a1 as prf p
>     | (No way)     = replace {P=\rec => Elem a1 (getProof rec)} (sym itsEqual) $
>                        filterSpec {P=P} d1P a1 as prf p
```

What it needed was an argument that the recursive call had the right form. I think in Agda you'd use the `inspect` idiom for this.

**Comment by nicolabotta** [comment]
Thanks for this solution David! If you think this is the canonical way of applying with rules containing recursive calls, please close the issue.
