### ISSUE TITLE
Docstrings in Prelude.String don't display well

### ISSUE THREAD

**Issue by laMudri** [idris-lang/Idris-dev#1924]
See this, taken verbatim from a REPL session:
```
Idris> :doc strTail
strTail : String -> String
    Returns the characters specified after the head of the string.
    
    Doesn't work for empty strings.
    
    Idris> strTail "AB" "B" : String Idris> strTail "A" "" : String
    
```
That last line is supposed to look like a sample REPL session across 4 lines. But the docstring syntax doesn't seem to allow simple line breaks. I'm not sure whether we want to keep these examples, and if so, how we want to present them.

I'm running the stable Cabal version (0.9.16).

**Comment by david-christiansen** [comment]
> But the docstring syntax doesn't seem to allow simple line breaks. I'm not sure whether we want to keep these examples, and if so, how we want to present them.

The docstring syntax is Markdown, so you need two newline chars between paragraphs, or to put things in a code block.

The docstrings' fenced code blocks also allow examples to be specified directly: if you specify the code block language as "idris" and add the "example" class, then it will make a little REPL spot in the docstrings with semantic highlighting and the result automatically computed by the evaluator.

I've updated the definition of `strTail` as follows:
`````idris
||| Returns the characters specified after the head of the string.
|||
||| Doesn't work for empty strings.
|||
||| ```idris example
||| strTail "AB"
||| ```
||| ```idris example
||| strTail "A"
||| ```
partial
strTail : String -> String
strTail = prim__strTail
`````

and now the docs show up as follows:
![docstrings](https://cloud.githubusercontent.com/assets/115330/6224572/1d144e24-b67e-11e4-9954-da4e6eb46dc6.png)
