### ISSUE TITLE
Type inference with tuple sections

### ISSUE THREAD

**Issue by pharpend** [idris-lang/Idris-dev#1930]
I'm pretty new to Idris, but I think this is a bug:

```idris
Idris> :let xy = [(x,y) | x <- [1..10], y <- [11..20]]
Idris> :let z = [y | (_,y) <- xy]
(input):1:11:When elaborating right hand side of case block in {val0}:
When elaborating an application of function Prelude.Monad.return:
        Can't unify
                Integer
        with
                b
```

**Comment by AHartNtkn** [comment]
I think it's not inferring the type of z incorrectly. This isn't a pattern matching problem, so much as a type inference one. The following works;

```
Idris> :let xy = [(x,y) | x <- [1..10], y <- [11..20]]
Idris> :let z : List Integer; z = [y | (_,y) <- xy]
Idris>
```

**Comment by pharpend** [comment]
That would seem to make sense

**Comment by edwinb** [comment]
I've not looked at this closely yet, but remember that full type inference can't be done for a language with full dependent types - instead we have a top level "expected" type and infer everything necessary from that. At the REPL, there is no expected type, so we can only make a best guess. Integer literals complicate things a bit, because in the absence of any other information it will guess you mean 'Integer'.

If you give an explicit type to xy it should work fine.

**Comment by suhr** [comment]
> I've not looked at this closely yet, but remember that full type inference can't be done for a language with full dependent types - instead we have a top level "expected" type and infer everything necessary from that.

I wonder why dependent typed languages can't infer type for its non-dependent subset, and fallback if dependent types actually involved? A lot of code doesn't use dependent types anyway.

**Comment by david-christiansen** [comment]
@suhr: how would you, in a principled manner, be able to see if the term in question should have a dependent type? For example, the non-dependent recursor and the dependent induction principle for Nat have precisely the same implementations:
```
natRec : a -> (Nat -> a -> a) -> Nat -> a
natRec z s Z = z
natRec z s (S k) = s k (natRec z s k)

natElim : {P : Nat -> Type} ->
          P Z -> ((n : Nat) -> P n -> P (S n)) ->
          (n : Nat) -> P n
natElim z s Z = z
natElim z s (S k) = s k (natElim z s k)
```

Without a type annotation, we really don't know which one we have.

**Comment by suhr** [comment]
Well, it isn't possible for polymorphic functions and types, but what about monomorphic one?
