### ISSUE TITLE
Windows CI Setup

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#1948]
Currently we use travis to provide CI testing for `Idris` on Linux boxes, this has the nice side effect of CI for Mac OS X. It would be nice if we can provide CI testing for Windows machines. 

This is not my idea @david-christiansen has mentioned it a few times, and I am in full agreement. [AppVeyor](http://www.appveyor.com/) seems to be a suitable candidate and a cursory glance implies that the [Build Instructions and Scripts for Windows](https://github.com/idris-lang/Idris-dev/wiki/Idris-on-Windows) can be adapted accordingly. Whether AppVeyor is the best (or maybe only) Windows CI service is another matter.

**Comment by david-christiansen** [comment]
AppVeyor seems to be what the F# folks use, in any case, and it seemed the most Travis-like when I looked at it before.

**Comment by jfdm** [comment]
Actually, I agree with AppVeyor but you know devils advocate...

**Comment by Heather** [comment]
Also it will be glad to repair `make test_c` , related issue: https://github.com/idris-lang/Idris-dev/issues/1936

**Comment by LeifW** [comment]
There's also http://win-builds.org. Maybe it's focused more on packaging than CI?

**Comment by enolan** [comment]
I'm working on this. Stuck on commercialhaskell/stack#1482

**Comment by ahmadsalim** [comment]
@enolan Thanks for the effort so far, is there any way one could try to work around the bug you are stuck on?

**Comment by enolan** [comment]
I'm actually past that and stuck on a different bug :) I've been stubbornly
trying to fix a problem with Stack where it intermittently hangs for a long
time now. Turning off concurrent builds might be a workaround. If so, I'm
all but done. I'll look into it.
