### ISSUE TITLE
Proof search on metavars nested in expressions gives curious results

### ISSUE THREAD

**Issue by LeifW** [idris-lang/Idris-dev#1956]
Version 0.9.16--git:cebd1b4 (I don't know what's wrong with my git version embedding; the last commit in the repo I just built from is b32de5ca)

Given the following file:
```idris
import Data.Vect

foo : Vect 10 Nat
foo = ?foo_rhs
```
Proof search on `?foo_rhs` fills it in with `0 :: 0 :: 0 :: 0 :: 0 :: 0 :: 0 :: 0 :: 0 :: ?foo_rhs1 :: ?foo_rhs2`.
Proof search on `?foo_rhs2` will correctly give `[]` (as long as you do it before trying it on `?foo_rhs1`), but proof search on `?foo_rhs1` gives `x8`, which is not in scope anywhere.

**Comment by LeifW** [comment]
Not sure if this a separate issue, but it seems similar:
In other cases trying to have "auto" is not able to fill in a metavar that's part of some other expression using in-scope assumptions (function args).

Filling in a nested metavar using a constructor works
```idris
thing : Maybe Nat
thing = Just ?foo
```
gives `0`

Filling in a nested metavar using an assumption does not work:
```idris
thing : a -> Maybe a
thing x = Just ?foo
```
does not find a result (it should use the in-scope `x` there).

Curiously, you get different behaviour replacing a with specific types. `Int -> Maybe Int` has the same behaviour as above (no solution found), whereas `Nat -> Maybe Nat` finds `x` as a solution. (Which is the desirable result; though I was half expecting it to say `0`, given its claimed ignorance of the assumption in other cases).

Use case:
I was seeing how well interactive editor support would help me implement `(a -> b) -> Maybe a -> Maybe b` (djinn does it in one go).
So having reached this point after a case split and a proof search:
```idris
amap : (a -> b) -> Maybe a -> Maybe b
amap f Nothing = Nothing
amap f (Just x) = ?foo
```
I didn't want to proof search on `?foo` directly, since I knew it would just choose the first constructor and say `Nothing` again, so I thought I'd give it some help to guide it in the direction I wanted, and change that to `Just ?foo`. The type of the `?foo` goal there is `b`, in scope as assumptions we have `f : a -> b` and `x : a`, but proof search does not apply the `f` to `x` to satisfy the goal.

This has all been using the vim support.

**Comment by edwinb** [comment]
I just checked this. The first behaves as you say, but the reason is that there is a depth limit on the proof search in interactive mode which is currently set to 10. Perhaps this should be deeper, I was a bit cautious when first implementing it. So this is as expected, but maybe we should try something a bit more daring. It worked fine when I did increase it, I'm just a bit scared that if search fails it'll take ages.

The other problems are now fixed - I remember fixing a related problem (or possibly even the same one that was just in a different issue).

**Comment by LeifW** [comment]
Everything described here seems to be working fine for me now - thanks!
I'm fine with it only expanding out the Vect 10 steps (or to whatever limit); I can now go ahead and proof search on the additional metavars thus produced and have it give correct results (e.g. not making up non-existent solutions like `x8`)
