### ISSUE TITLE
Empty comments extend to the next line

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#1958]
This issue was first reported at https://github.com/idris-hackers/idris-mode/issues/300 by @jasonhemann.

Idris sucessfully parses and type checks the following module:

```
module Foo
-- 
malformed stuff here
Alias : Type
Alias = Nat
```

It seems that the comment handling code is a bit off.

Pinging @ahmadsalim in case he has time to diagnose it before me.

**Comment by ahmadsalim** [comment]
Oh, that was quick :).
Yeah, I think you found the error which had happened because of `many simpleWhitespace` so it would have parsed until the next non-whitespace text there was including newlines.
