### ISSUE TITLE
Windows: Idris does not find correct make program when compiling base packages

### ISSUE THREAD

**Issue by NobbZ** [idris-lang/Idris-dev#1974]
Here on my windows installation I have severall build tools calling themselves `make`, depending on how my `PATH`-environment is set up, the correct one might be choosen when installing idris, or build of base-packages fails with an error message about not beeing able to recognize an option (Embercadero make does not know about `-C`), not beeing able to parse the Makefile or simply to not beeing able to find one, because of different naming conventions in that particular build tool.

Even worse: I'm not beeing able to temper with build-tool setup at workstations on my university, but would like to "play" with Idris there too.

Additionally build tools and windows is pretty much another kind of annoyance that should be avoided regularly.

So I would suggest to use [`hake`](http://hackage.haskell.org/package/hake) or some other build tool, that can be bundled with the cabalized version of idris, to reduce dependencies on some installed programms (but it will introduce further dependencies on haskell side though).

**Comment by david-christiansen** [comment]
I think that the most reasonable solution to helping people with broken implementations of Make or who are on strange environments where they can't install any packages is to provide appropriate binary packages, rather than spend a lot of time rewriting the build infrastructure to accommodate every possible case.

**Comment by melted** [comment]
I wouldn't mind using shake`for the build, but that is another issue. The standard way to build Idris on Windows this is to install a MSYS2 environment and build idris from there. External tools won't interfere as they come after the msys ones in the PATH.

MSYS2 (http://sourceforge.net/projects/msys2/) is available as a compressed folder that can be unpacked anywhere, so it can be put on systems where the user isn't allowed to install programs. Or you can just move your entire installation from home, it doesn't depend on the registry or the installation location.
