### ISSUE TITLE
"Can't convert" error in type class declaration

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#1975]
The following type class declaration
````
> class Monad m => ContainerMonad (m : Type -> Type) where
>   Elem : a -> m a -> Type
>   tagElem : (mx : m a) -> m (x : a ** Elem x mx)
```
does not type check:
````
- + Errors (1)
 `-- typeClasses.lidr line 1 col 6:
     When elaborating type of constructor of Main.ContainerMonad:
     Can't convert
             a8
     with
             Type
```
Is this the expected behavior ? I remember we ran into this problem years ago and came to the conclusion not to use type classes for the https://github.com/nicolabotta/SeqDecProbs framework for the time being. Is this conclusion still valid? Am I missing something obvious here? Thanks, Nicola

**Comment by david-christiansen** [comment]
I would think that this should work -- it's at least mystifying to me that it doesn't.

I just did some experimentation and it seems that it's the resolver for the implicit type argument to `Elem` that is not doing the right thing here.  The following code type checks for me:

```idris
> class Monad m => ContainerMonad (m : Type -> Type) where
>   Elem : a -> m a -> Type
>   tagElem : (mx : m a) -> m (x : a ** Elem {a=a} x mx)
```

**Comment by nicolabotta** [comment]
Thanks David, that works for me as well! Best, Nicola

**Comment by edwinb** [comment]
It seems that it's not expanding implicits at all when elaborating dependent type classes, and it's doing so deliberately. Whoever wrote that code (*whistles innocently*) apparently didn't want to write a comment to explain that. Even inserting {a=_} is fine.

Once I've worked this out I'll make sure there's a comment! Fortunately it doesn't seem to be a deep unification problem or anything like that, so will only affect dependent type classes.
