### ISSUE TITLE
Can't unify "Identity A" with "Identity A"

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#1976]
The program
````
> import Control.Monad.Identity

> namespace ContainerMonad
>   Elem : {A : Type} -> (M : Type -> Type) -> A -> M A -> Type

> ContainerMonad.Elem {A} Identity a1 (Id {a = A} a2) = a1 = a2
```
yields the title error. I cannot see anything obviously wrong in the definition of "Elem" on the last line. Is this the expected behavior? Am I missing something?

**Comment by zraffer** [comment]
It seems to be an attempt to pattern match against type function `Identity`, don't it?

**Comment by nicolabotta** [comment]
zraffer, I am not sure there is a pattern matching involved here, I would say so if `Identity` was a data constructor but this is not the case. The point here is that I do not see an obvious reason why the program should not type check. For instance:
````
> Lala : Nat -> Type
> Lala n = Nat

> Elem : (M : Nat -> Type) -> (n : Nat)-> M n -> Type
> Elem Lala m n = m = n
```
type checks just fine. I'm probably having a blind spot but ... Best, Nicola

**Comment by zraffer** [comment]
@nicolabotta , `Elem Lala m n = m = n` will type check fine even if you drop the definition of `Lala`. So `Lala` is considered to be a new variable. Here m and n can be typechecke(Id {a = A} a2)d without knowledge of type `M`. 

By the contrast, in `(Id {a = A} a2)` you use data constructor `Id` and require this to be a pattern matching against type `Control.Monad.Identity.Identity`. But in the same line you declare a new variable `Identity` being a new named parameter of the function `ContainerMonad.Elem` :) Then Idris complains about difference of these two `Identity`s.

**Comment by nicolabotta** [comment]
Thanks zraffer ... and blame on me, I was really blind ! It's time to close the issue, I guess. Best, Nicola
