### ISSUE TITLE
Index Too Large Error working with Sigma Types

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#1978]
The code below will produce the following error during compilation:

    idris: Prelude.(!!): index too large

The purpose of the code is convert a list of elements of type `From A` into a list of type `TOs cs`. Sigma types are used to ensure values embedded in types are constructed correctly.

This error 'may be' a result of incorrect use of Sigma types.

```idris
module MFE

data FromTy = A | B
data From : FromTy -> Type where
  MkFrom : String -> From A
  MkFrom' : Int    -> From B

data EmbedTy = C | D
data Embed : EmbedTy -> Type where
  MkVal  : String         -> Embed C
  MkVals : List (Embed C) -> Embed D

mutual
  data ToTy = E | F
  data To : Embed ty -> ToTy -> Type where
    MkTo  : (s : String) -> To (MkVal s) E
    TheTo : TOs cs       -> To (MkVals cs) F

  data TOs : List (Embed C) -> Type where
    Nil  : TOs Nil
    (::) : Embed C -> TOs cs -> TOs (c :: cs)

doConv : From A -> (f : ToTy ** (e : Embed C ** To e f))
doConv (MkFrom s) = (E ** (_ ** MkTo s))

conv : List (From A) -> (cs : List (Embed C) ** TOs cs)
conv Nil     = (Nil ** Nil)
conv (x::xs) = (cs ** ts)
  where
    x'  = getWitness (doConv x)
    xs' = conv xs
    cs  = getWitness x' :: getWitness xs'
    ts  = getProof x' :: getProof xs'
```

**Comment by jfdm** [comment]
As an update: The above code has been replaced in my project with a working version. My use of Sigma types was wrong. I leave this MFE here as the resulting error message was unhelpful.

**Comment by edwinb** [comment]
I think the problem here comes down to the lack of type declarations on the where clauses. If you use 'let' instead you get a reasonable error message.

I will at least make it not crash. But I think we should also remove the ability to leave type declarations off where clauses because it leads to more trouble than it's worth especially with error messages.

**Comment by jfdm** [comment]
Cheers!
