### ISSUE TITLE
isHead: Can construct seemingly bogus proof terms

### ISSUE THREAD

**Issue by davidfstr** [idris-lang/Idris-dev#1984]
Consider the following program, saved as `ElemsAreEq2.idr`:
http://pastebin.com/khHkMssU

You can construct a bogus proof term `IsHead [1,2] 2` via:

```
$ idris --nobanner ElemsAreEq2.idr
 
*ElemsAreEq2> isHead [1,2] 2
Just (HeadOfCons 1 [2]) : Maybe (HeadIs [1, 2] 2)   -- WTF?
```

However you can't construct a bogus proof term manually. This is good, but inconsistent:

```
*ElemsAreEq2> the (HeadIs [1,2] 2) (HeadOfCons 1 [2])
(input):1:5:When elaborating argument x to function Prelude.Basics.the:    -- GOOD
        Can't unify [...]
```

or:

```
*ElemsAreEq2> :let n1 = (S Z)
*ElemsAreEq2> n1
1 : Nat
*ElemsAreEq2> :let n2 = S (S Z)
*ElemsAreEq2> n2
2 : Nat
*ElemsAreEq2> the (HeadIs [n1,n2] n2) (HeadOfCons n1 [n2])
(input):1:5:When elaborating argument x to function Prelude.Basics.the:    -- GOOD
        Can't unify [...]
```

Probably Idris should have rejected the original definition of `isHead` since I can use it to make bogus proof terms. However I am not sufficiently versed in Idris to debug this further myself.

Environment is Idris 0.9.16.

**Comment by edwinb** [comment]
Does this happen in master? I think I fixed this last week (there was a 
missing case in a check for non linear patterns)

**Comment by davidfstr** [comment]
If you fixed this recently, then this issue is probably resolved. This issue was observed on the released Idris 0.9.6.

I'll take another look at Idris master in a day or two. As I recall it took me an hour to compile Idris (plus its dependencies) the last time.

**Comment by davidfstr** [comment]
Same program gives a compilation on iris master as of today, which is the expected behavior:

```
me$ ./.cabal-sandbox/bin/idris --nobanner ~/src/ElemsAreEq2.idr 
Type checking /Users/me/src/ElemsAreEq2.idr
/Users/me/src/ElemsAreEq2.idr:19:14:
When elaborating left hand side of Main.case block in isHead:
Can't match on case block in isHead n
                                    e
                                    xs
                                    h
                                    (Just (MkSigma h proofHeadOfXsIsH))
Metavariables: Main.isHead
```

In case anybody cares, it took 1hr8m to compile idris's dependencies and 36m to compile idris itself on my VM.

**Comment by jfdm** [comment]
@davidfstr Concerning your build times, do you ask cabal to build documentation when install packages...I once had that enabled and it led to long build times. Turning it off sped up the process.
