### ISSUE TITLE
Examples in idris documentation

### ISSUE THREAD

**Issue by suhr** [idris-lang/Idris-dev#1988]
Provide support for examples in code documentation, add some examples to the standard library.

Optionally check that an example compiles.

**Comment by david-christiansen** [comment]
We have this already, or at least something like it. If you use a fenced code block with the language set to "idris" and the class set to "example" then it is rendered as a REPL command with result. Type errors lead to decoration, and in IDE clients the error is available as a tooltip on the bad term.

Is this what you were looking for?

**Comment by david-christiansen** [comment]
Hmm, this may not work properly in the HTML version - I'll try to get that added when I get the time.

**Comment by suhr** [comment]
> If you use a fenced code block with the language set to "idris" and the class set to "example" then it is rendered as a REPL command with result. Type errors lead to decoration, and in IDE clients the error is available as a tooltip on the bad term.

Nice! Unfortunately, it is not mentored in https://github.com/idris-lang/Idris-dev/wiki/Documenting-Idris-Code and standard library lacks examples.

**Comment by david-christiansen** [comment]
Yes, modules can have docs now. I'm not sure if that's in the latest release or if it will be in the next one though.

I suppose I need to write more meta-documentation about the examples feature! Take a look at `Prelude.List` for a few example examples.

**Comment by edwinb** [comment]
I'm closing this not because I think it's a bad idea, but because with this sort of open ended issue it's next to impossible to tell when it's been resolved. I think I would prefer to have a list of open-ended problems on the wiki, as a place to point potential new contributors to.
