### ISSUE TITLE
Can't unify   \k => Fin (f k)   with   Fin . f

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#1990]
The following 
````
> import Data.Fin
> import Control.Isomorphism

> %default total

> tail : {A : Type} -> (Fin (S n) -> A) -> (Fin n -> A)
> tail f k = f (FS k)

> sigmaFinEitherLemma : {n : Nat} -> 
>                       {P : Fin (S n) -> Type} ->
>                       Iso (Sigma (Fin (S n)) P) (Either (P FZ) (Sigma (Fin n) (tail P)))

> sigmaFinEitherLemma1 : {n : Nat} -> {f : Fin (S n) -> Nat} ->
>                        Iso 
>                        (Sigma (Fin (S n)) (\ k => Fin (f k))) 
>                        (Either (Fin (f FZ)) (Sigma (Fin n) (\ k => Fin ((tail f) k))))
> sigmaFinEitherLemma1 {n} {f} =
>     ( Sigma (Fin (S n)) (\ k => Fin (f k))                            ) 
>   ={ sigmaFinEitherLemma {n = n} {P = Fin . f} }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (tail (Fin . f)))            )     
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (\ k => (tail (Fin . f)) k)) )     
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (\ k => Fin ((tail f) k)))   )
>   QED
```
yields the unification problem at line
````
>   ={ sigmaFinEitherLemma {n = n} {P = Fin . f} }=
```
I think this is a bug. Any idea how to avoid this problem ? Best, Nicola

**Comment by edwinb** [comment]
It's because (.) needs three arguments to reduce, and you've only given it two here, so unification can't make any progress. It may be that manually eta expanding the composition will help - I think it's right to say it can't unify these things though, by the current definition which doesn't know about eta.

By the way, the updated error message says:

```
        Can't unify
                Either (Fin (f FZ))
                       (Sigma (Fin n) (tail (\k => Fin (f k)))) (Inferred value)
        with
                Either (Fin (f FZ))
                       (Sigma (Fin n)
                              (tail (Fin . (\k4 => f k4)))) (Given value)
```

which implies that it has inferred the value itself and doesn't agree with what you've given.

**Comment by nicolabotta** [comment]
It seems to me there are two problems here: the first one is that the error message comes from within Preorder reasoning:
````
- + Errors (1)
 `-- ./Syntax/PreorderReasoning.idr line 7 col 42:
     When elaborating right hand side of sigmaFinEitherLemma1:
     When elaborating argument a to function Control.Isomorphism.step:
             Can't unify
                     Either (Fin (f FZ))
                            (Sigma (Fin n) (tail (\k => Fin (f k)))) (Inferred value)
             with
                     Either (Fin (f FZ))
                            (Sigma (Fin n) (tail (Fin . f))) (Given value)
             
             Specifically:
                     Can't unify
                             \k => Fin (f k)
                     with
                             Fin . f
```
For the user it would be useful to know which line of code leads to the error. The second problem is that \k => Fin (f k) does not reduce to (Fin . f). Is this the expected behaviour ? If so, then the main issue is that the error message is not very useful. Otherwise the main issue is that \k => Fin (f k) fails to reduce to (Fin . f), I think.

**Comment by edwinb** [comment]
There is certainly a problem with line numbers in syntax declarations, 
being that it reports the line number where the syntax rule was defined, 
and not the line number where the resulting code is. This should be fixed.

I've changed the definition of (.) so that it doesn't require the third 
argument to reduce - that doesn't make this code type check but should 
at least work better overall.

**Comment by nicolabotta** [comment]
Ok thanks Edwin! With
````
> postulate lambdaLemma1 : {A, B : Type} -> (f : A -> B) -> (\ a => f a) = f
```
and
````
> isoCong : {A : Type} -> {x : A} -> {y : A} -> {P : A -> Type} -> x = y -> Iso (P x) (P y)
> isoCong {x} {P} prf = replace {P = \ z => Iso (P x) (P z)} prf isoRefl 
```
one can easily implement sigmaFinEitherLemma1:
````
> sigmaFinEitherLemma1 {n} {f} =
>     ( Sigma (Fin (S n)) (\ k => Fin (f k))                            ) 
>   ={ isoCong {P = \ X => (Sigma (Fin (S n)) X)} (lambdaLemma1 (Fin . f)) }=
>     ( Sigma (Fin (S n)) (Fin . f)                            ) 
>   ={ sigmaFinEitherLemma {n = n} {P = Fin . f} }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (tail (Fin . f)))            )     
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (\ k => (tail (Fin . f)) k)) )     
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (\ k => Fin ((tail f) k)))   )
>   QED
```
The question is whether it makes sense to postulate lambdaLemma1 or whether it should be built in. In the first case this is just an error message issue, I guess. Ciao, Nicola

**Comment by edwinb** [comment]
Closing this since I think it's behaving correctly...
