### ISSUE TITLE
Allow docstrings for type provider invocations

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#1992]
I'd like this to work:
```
||| Some test of something
%provide (myTest : Code) with getTestCode 42

Idris> :doc myTest
myTest : Code
    Some test of something
```

**Comment by adamse** [comment]
I have an implementation of this, based on the refactored parser from #1983, see https://github.com/adamse/Idris-dev/compare/instance-docs...adamse:type-provider-docs, will file a PR when #1983 is merged!

**Comment by david-christiansen** [comment]
Nice!
