### ISSUE TITLE
Cannot Unify Unit with Itself When on Right Hand Side

### ISSUE THREAD

**Issue by AHartNtkn** [idris-lang/Idris-dev#1994]
When running a file with the following code;
```
unitTest : Unit = ()
unitTest = Refl

unitTest' : () = Unit
unitTest' = Refl
```
The following error occurs;
```
When elaborating right hand side of unitTest':
Can't unify
        x = x
with
        () = ()

Specifically:
        Can't unify
                ()
        with
                ()
```

Note that unitTest works fine, unitTest' does not.

**Comment by LeifW** [comment]
The colorized output gives some info as to what's going on. I get "Can't unify () with ()" where the first one is red, the second one is blue. The default Idris color scheme is values are red, types are blue...
Semi-recently actual names were added for Unit: `data Unit = MkUnit`, but leaving the () as an alias for both the type and the value (which one is picked depends on the type context).
When you say just `()` by itself at the repl, I get `() : ()`, where the first `()` is red, and the second is blue. That is, `MkUnit : Unit`. (You can alter this by changing the expected type at that location, e.g. `the Type ()` or `the Unit ()`).

I'm guessing Idris does this resolution from left to right. So in the first example, you're specifying an equality to the type Unit, and then () is disambiguated to be the type Unit. In the second case, I'm guessing the () is first disambiguated to be the value MkUnit, and then you're trying to have it equal the type Unit.

**Comment by AHartNtkn** [comment]
I see. I think it would be helpful to change the constructor of Unit, or remove the () sugar for the type. One is not allowed to do something like this, for instance;
```
data Verum : Type where
 Verum : Verum
```
Anyway, thanks for clearing this up.
