### ISSUE TITLE
No such variable Eff

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#1995]
I am probably missing something obvious but the "Hello world" example from the tutorial:
````
> module Main
> import Effect.StdIO
> hello : { [STDIO] } Eff ()
> hello = putStrLn "Hello world!"
> main : IO ()
> main = run hello
```
fails to type check with the error message
````
nicola@cirrus:~/github/SeqDecProbs/reports$ idris -p effects effects.lidr
Type checking ./effects.lidr
effects.lidr:3:7:When elaborating type of Main.hello:
No such variable Eff
*effects>
```
What am I doing wrong ? Thanks, Nicola

**Comment by david-christiansen** [comment]
I think you're missing `import Effects` in the module header.

**Comment by nicolabotta** [comment]
Thanks David, I close the issue. Best, Nicola

**Comment by david-christiansen** [comment]
Happy to help :-)
