### ISSUE TITLE
Repl doesn't treat Stream monad operations as lazy

### ISSUE THREAD

**Issue by AHartNtkn** [idris-lang/Idris-dev#2003]
The following code runs forever;
```
Idris> take 10 [ i | i <- [1..] ]
```
This too;
```
Idris> take 10 ([1..] >>= \i => return i)
```
This makes comprehension and monad operations useless for streams. I'm not sure if this is necessarily a bug, but this does seem wrong to me.

**Comment by Chobbes** [comment]
This seems to be a problem with the REPL as @defanor helped point out on IRC. If you compile this, instead of running it in the REPL it works fine.

    module Main

    x : List Int
    x = take 10 [i | i <- [1..]]

    main : IO ()
    main = print x

**Comment by AHartNtkn** [comment]
Okay. I'll change the issue to be one with the repl then. Thanks for the correction.

**Comment by edwinb** [comment]
Both of these appear to work fine now, so I'm closing this. Not sure what we did to fix it, though I vaguely remember tweaking something else in REPL evaluation in the last few months!
