### ISSUE TITLE
Follow-up of issue #1990

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2039]
The following example type checked fine until my last post in #1990 (4 days ago, about 17.03.2015) 
````
> import Data.Fin
> import Control.Isomorphism

> %default total

> postulate lambdaLemma1 : {A, B : Type} -> (f : A -> B) -> (\ a => f a) = f

> isoCong : {A : Type} -> {x : A} -> {y : A} -> {P : A -> Type} -> x = y -> Iso (P x) (P y)
> isoCong {x} {P} prf = replace {P = \ z => Iso (P x) (P z)} prf isoRefl 

> tail : {A : Type} -> (Fin (S n) -> A) -> (Fin n -> A)
> tail f k = f (FS k)

> sigmaFinEitherLemma : {n : Nat} -> 
>                       {P : Fin (S n) -> Type} ->
>                       Iso (Sigma (Fin (S n)) P) (Either (P FZ) (Sigma (Fin n) (tail P)))

> sigmaFinEitherLemma1 : {n : Nat} -> {f : Fin (S n) -> Nat} ->
>                        Iso 
>                        (Sigma (Fin (S n)) (\ k => Fin (f k))) 
>                        (Either (Fin (f FZ)) (Sigma (Fin n) (\ k => Fin ((tail f) k))))
> sigmaFinEitherLemma1 {n} {f} =
>     ( Sigma (Fin (S n)) (\ k => Fin (f k))                            ) 
>   ={ isoCong {P = \ X => (Sigma (Fin (S n)) X)} (lambdaLemma1 (Fin . f)) }=
>     ( Sigma (Fin (S n)) (Fin . f)                            ) 
>   ={ sigmaFinEitherLemma {n = n} {P = Fin . f} }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (tail (Fin . f)))            )     
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (\ k => (tail (Fin . f)) k)) )     
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (\ k => Fin ((tail f) k)))   )
>   QED
```
But with 0.9.17-git:e10c205, one gets
````
- + Errors (1)
 `-- ./Syntax/PreorderReasoning.idr line 7 col 42:
     When elaborating right hand side of sigmaFinEitherLemma1:
     When elaborating argument a to function Control.Isomorphism.step:
             Can't unify
                     Either (Fin (f FZ))
                            (Sigma (Fin n) (tail (\x => Fin (f x)))) (Inferred value)
             with
                     Either (Fin (f FZ))
                            (Sigma (Fin n) (\k4 => tail (Fin . f) k4)) (Given value)
             
             Specifically:
                     Can't unify
                             tail (\x => Fin (f x))
                     with
                             \k4 => Fin (f (FS k4))
```
As in #1990, the error can be avoided by applying once more |lambdaLemma1|, this time in reverse:
````
> sigmaFinEitherLemma1 : {n : Nat} -> {f : Fin (S n) -> Nat} ->
>                        Iso 
>                        (Sigma (Fin (S n)) (\ k => Fin (f k))) 
>                        (Either (Fin (f FZ)) (Sigma (Fin n) (\ k => Fin ((tail f) k))))
> sigmaFinEitherLemma1 {n} {f} =
>     ( Sigma (Fin (S n)) (\ k => Fin (f k))                            ) 
>   ={ isoCong {P = \ X => (Sigma (Fin (S n)) X)} (lambdaLemma1 (Fin . f)) }=
>     ( Sigma (Fin (S n)) (Fin . f)                            ) 
>   ={ sigmaFinEitherLemma {n = n} {P = Fin . f} }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (tail (Fin . f)))            )     
>   ={ isoCong {P = \ X => Either (Fin (f FZ)) (Sigma (Fin n) X)} (sym (lambdaLemma1 (tail (Fin . f)))) }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (\ k => (tail (Fin . f)) k)) )     
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (\ k => Fin ((tail f) k)))   )
>   QED
```
As in #1990, I am not sure whether this is a bug or the expected behavior. In the latter case the only issue here would be that the error message is not very useful to understand which step in the implementation is responsible for the error.

**Comment by ahmadsalim** [comment]
I think the issue here is that `tail` is not getting all the arguments and so not reducing.
I believe this is expected behaviour, and so I will close this issue if it is OK.

**Comment by ahmadsalim** [comment]
I think this might be however remedied if one defines tail as:
```idris
tail f = \k => f (FS k)
``` 
instead.

**Comment by nicolabotta** [comment]
You are right Ahmad! The program
```
> import Data.Fin
> import Control.Isomorphism

> %default total
> %auto_implicits off

> isoCong : {A : Type} -> {x : A} -> {y : A} -> {P : A -> Type} -> x = y -> Iso (P x) (P y)
> isoCong {x} {P} prf = replace {P = \ z => Iso (P x) (P z)} prf isoRefl 

> tail : {n : Nat} -> {A : Type} -> (Fin (S n) -> A) -> (Fin n -> A)
> tail f k = f (FS k)

> postulate sigmaFinEitherLemma : {n : Nat} -> 
>                                 {P : Fin (S n) -> Type} ->
>                                 Iso (DPair (Fin (S n)) P) (Either (P FZ) (DPair (Fin n) (tail P)))

> sigmaFinEitherLemma1 : {n : Nat} -> {f : Fin (S n) -> Nat} ->
>                        Iso 
>                        (DPair (Fin (S n)) (\ k => Fin (f k))) 
>                        (Either (Fin (f FZ)) (DPair (Fin n) (\ k => Fin ((tail f) k))))
> sigmaFinEitherLemma1 {n} {f} =
>     ( DPair (Fin (S n)) (\ k => Fin (f k))                            ) 
>   ={ isoRefl }=
>     ( DPair (Fin (S n)) (Fin . f)                            ) 
>   ={ sigmaFinEitherLemma {n = n} {P = Fin . f} }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (tail (Fin . f)))            )     
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (\ k => (tail (Fin . f)) k)) )     
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (\ k => Fin ((tail f) k)))   )
>   QED
```
type checks fine with 0.11-git:4a4548e, no matter whether `tail` is defined as above or as 
```
> tail f = \ k => f (FS k)
```
Thanks, Nicola
