### ISSUE TITLE
FFI and point free style don't work well together

### ISSUE THREAD

**Issue by raichoo** [idris-lang/Idris-dev#204]
alert : String -> IO ()
    alert s = mkForeign (FFun "alert" [FString] FUnit) s

Results in

    (SForeign LANG_C FUnit "alert" [(FString,Loc 1)])

But

    alert : String -> IO ()
    alert = mkForeign (FFun "alert" [FString] FUnit)

yields

    (SForeign LANG_C FUnit "alert" []))

**Comment by edwinb** [comment]
This is related to the old FFI, so I'm closing. A similar problem might happen with the updated FFI, but the need to apply in full is documented (er, I think it is anyway, I'd better check).
