### ISSUE TITLE
Javascript callbacks registered but not called

### ISSUE THREAD

**Issue by guidouva** [idris-lang/Idris-dev#2043]
Using idris 0.9.17 the following example doesn't work for me with the node or javascript code generators. There is something registered, using node I can see the process waiting for the timeout but the callback is not being called.

```haskell
module Main

setTimeout : (() -> JS_IO ()) -> Int -> JS_IO ()
setTimeout f ms = foreign FFI_JS "setTimeout(%0,%1)"
    (JsFn (() -> JS_IO ()) -> Int -> JS_IO ())
    (MkJsFn f) ms

main : JS_IO ()
main = setTimeout (\_ => putStr "Hello, World") 2000
```

The same thing happens when I try to register something with the browser's "addEventListener" method (something succesfully registered but callback not called).

**Comment by ak3n** [comment]
Interesting fact: if you put `i$CALL(_idris_io_95_bind$0,[oldbase,myoldbase]);` at the end of declaration of `_idris_Prelude_46_putStr`, "Hello, World" will be displayed.

**Comment by rbarreiro** [comment]
I made this small test to try to shed some light on the problem:
```
%include Node "test.js"

jscall : (fname : String) -> (ty : Type) ->
          {auto fty : FTy FFI_JS [] ty} -> ty
jscall fname ty = foreign FFI_JS fname ty


call_fn : (String -> JS_IO String) -> String -> JS_IO String
call_fn f x = jscall  "call_fn(%0, %1)" ((JsFn(String -> JS_IO String)) -> String -> JS_IO String) (MkJsFn f) x

prepend_hello : String -> JS_IO String
prepend_hello x = jscall "prepend_hello(%0)" (String -> JS_IO String) x

debug : String -> JS_IO ()
debug x = jscall "debug(%0)" (String -> JS_IO ()) x


main : JS_IO ()
main = do
  s <- call_fn prepend_hello "world"
  d <- prepend_hello "world"
  debug d
  debug s
```

javascript:
```
function call_fn(f, x){
    return f(x);
}

function prepend_hello(x){
    return "hello " + x;
}

function debug(x){
    var console = require('console');
    console.log(x);
}
```

result in idris 0.9.17.1-

```
$ idris --codegen Node test.idr  -o out.js
$ nodejs out.js 
hello world
{ tag: 65622, args: [ 'world' ], app: [Function], ev: null }
```

**Comment by rbarreiro** [comment]
this is the commit that breaks it, 
https://github.com/idris-lang/Idris-dev/commit/15590d71071a32757ea0b851d0d04f13cc2700f1

I am trying to understand this but using the old i$ffiWrap made my example work

**Comment by david-christiansen** [comment]
Pinging @raichoo

**Comment by edwinb** [comment]
I'll try to take a look at this shortly. I expect to do a few bits and
pieces with the JS codegen soon.

**Comment by worldsayshi** [comment]
Here is a related example:
http://lpaste.net/137046
With generated js:
http://lpaste.net/137047 

Discussion on irc said that the issue is with non exhaustive pattern in `translateBC`:
https://github.com/idris-lang/Idris-dev/blob/master/src/IRTS/CodegenJavaScript.hs#L1346

Or rather. It seems that the issue is that my example does not cause an error. It is my understanding that `foreign` shouldn't accept non-static values in the second argument. But I might misunderstand things.

**Comment by melted** [comment]
The first problem actually doesn't have anything to do with the new one. rbarreiro pointed to a commit up there that made the rts only call the the first thing in the call stack, so putStrLn would be put on the stack and never called.  So I reverted that. Hopefully there's a solution to the issue the patch was an attempt at.

**Comment by melted** [comment]
The second issue is easily fixed, sadly there's no way short of "error" to propagate an error in JS codegen, as even the compile is a pure function from the AST to Text. So I added an error as is used in oither places there.
