### ISSUE TITLE
License contains odd slashes on readthedocs

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#2045]
On the readthedocs view of the documentation, we can see the following:

> The documentation for Idris has been published under the Creative Commons CC0 License. As such to the extent possible under law, /The Idris Community/ has waived all copyright and related or neighboring rights to Documentation for Idris.

Shouldn't those slashes be removed?

**Comment by jfdm** [comment]
ah that looks like a mistake in syntax used.
