### ISSUE TITLE
Unification failure in type class depends on type variable name in instance declaration !

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2057]
The instance declaration
````
> class Preorder t where
>   total po : t -> t -> Type 
>   total reflexive : (a : t) -> po a a   
>   total transitive : (a : t) -> (b : t) -> (c : t) -> po a b -> po b c -> po a c                                          

> instance Preorder a => Preorder (a,b) where
>   po a1b1 a2b2 = po (fst a1b1) (fst a2b2)
>   reflexive ab = reflexive (fst ab)
>   transitive a1b1 a2b2 a3b3 a1poa2 a2poa3 = transitive (fst a1b1) (fst a2b2) (fst a3b3) a1poa2 a2poa3
```
does not type check:
````
- + Errors (1)
 `-- typeClasses5.lidr line 4 col 77:
     When elaborating type of Main.Main.(a, b) instance of Main.Preorder, method transitive:
     Can't unify
             (a1, b2) (Type of c)
     with
             (a, b) (Expected type)
     
     Specifically:
             Can't unify
                     b1
             with
                     b
```
but
````
> class Preorder t where
>   total po : t -> t -> Type 
>   total reflexive : (a : t) -> po a a   
>   total transitive : (a : t) -> (b : t) -> (c : t) -> po a b -> po b c -> po a c                                          

> instance Preorder t1 => Preorder (t1,t2) where
>   po a1b1 a2b2 = po (fst a1b1) (fst a2b2)
>   reflexive ab = reflexive (fst ab)
>   transitive a1b1 a2b2 a3b3 a1poa2 a2poa3 = transitive (fst a1b1) (fst a2b2) (fst a3b3) a1poa2 a2poa3
```
type checks fine. The difference is in the name of the type parameters in the instance declaration:
````
> instance Preorder a => Preorder (a,b) where
```
vs
````
> instance Preorder t1 => Preorder (t1,t2) where
```

**Comment by edwinb** [comment]
It's supposed to explicitly rename the names in the instance head when creating the function types for the instance methods, but unfortunately I got it wrong and it only renames parameters... fix on its way.
