### ISSUE TITLE
Namespaces leaking instance declarations: expected behaviour ?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2058]
Namespaces are closed for variable declarations and
````
> namespace lala
>   foo : Nat
> namespace lula
>   foo : Nat
```
type checks fine. However, instance declarations seem to leak through namespaces and
````
> class Preorder t where
>   total PO : t -> t -> Type 
>   total reflexive : (x : t) -> PO x x   
>   total transitive : (x : t) -> (y : t) -> (z : t) -> PO x y -> PO y z -> PO x z

> namespace lala
>   instance Preorder t1 => Preorder (t1, t2) where
>     PO x y = PO (fst x) (fst y)
>     reflexive x = reflexive (fst x)
>     transitive x y z xy yz = transitive (fst x) (fst y) (fst z) xy yz

> namespace lula
>   instance Preorder t2 => Preorder (t1, t2) where
>     PO x y = PO (snd x) (snd y)
>     reflexive x = reflexive (snd x)
>     transitive x y z xy yz = transitive (snd x) (snd y) (snd z) xy yz
```
does not type check: 
````
- + Errors (1)
 `-- namespace1.lidr line 13 col 11:
     Overlapping instance: Preorder (t1, t2) already defined
```
Is this the expected behavior ? Thanks, Nicola

**Comment by Melvar** [comment]
*Unnamed* instances may not overlap. This applies even across modules, certainly across namespaces. I’m not sure how you expected to use what you wrote; you can’t use the namespace name in any way to refer to the instances within, unless you name them, in which case it should be happy.

**Comment by nicolabotta** [comment]
> Unnamed instances may not overlap. This applies even across modules, certainly across namespaces. 

Thanks Melvar, if you can confirm that this is the expected behavior I will close the issue.

> I’m not sure how you expected to use what you wrote ...

No particular expectations. I am just trying to understand how type classes work and to assess whether we can use type classes in https://github.com/nicolabotta/SeqDecProbs or whether it is safer to only rely on plain data declarations as we have done so far. Type classes still seem to suffer from quite serious bugs, see for instance issue #2057 or my post "Modules, type classes and modular libraries" on idris-lang@googlegroups.com. I was a bit puzzled by the first tests I made with named instances and that's the reason I started to play around with namespaces.

**Comment by Melvar** [comment]
Okay, well, *I* expect this behavior.

**Comment by edwinb** [comment]
Yes, this is expected behaviour, so I'll close this issue. - instances are global.

**Comment by nicolabotta** [comment]
Thanks Melvar, Edwin. I will keep that in mind but: what is the rationale behind this exception? Why should instance declaration be treated in a different way from any other declaration? What about class declarations? The code
````
> namespace lala
>   class Preorder t where
>     total PO : t -> t -> Type 
>     total reflexive : (x : t) -> PO x x   
>     total transitive : (x : t) -> (y : t) -> (z : t) -> PO x y -> PO y z -> PO x z
```
type checks fine but
````
> namespace lala
>   class Preorder t where
>     total PO : t -> t -> Type 
>     total reflexive : (x : t) -> PO x x   
>     total transitive : (x : t) -> (y : t) -> (z : t) -> PO x y -> PO y z -> PO x z

> namespace lula
>   class Preorder t where
>     total PO : t -> t -> Type 
>     total reflexive : (x : t) -> PO x x   
>     total transitive : (x : t) -> (y : t) -> (z : t) -> PO x y -> PO y z -> PO x z
```
yields
````
- + Errors (1)
 `-- namespace1.lidr line 8 col 8:
     When elaborating type of constructor of Main.lula.Preorder:
     Too many arguments for PO
```
The error message little sense to me. Also, it seems perfectly reasonable to allow the same name (`Preorder` in this case) to represent different notions in different namespaces or modules, this is finally the idea behind domain specific notions! Best, Nicola

**Comment by edwinb** [comment]
On 31/03/2015 07:07, nicolabotta wrote:
> Thanks Melvar, Edwin. I will keep that in mind but: what is the
> rationale behind this exception? Why should instance declaration be
> treated in a different way from any other declaration?

If there's overlapping instances, how do we know which one to pick when 
there's more than one valid?

**Comment by nicolabotta** [comment]
> If there's overlapping instances, how do we know which one to pick when there's more than one valid?

I would expect the user would have to disambiguate overlapping instances like in
````
> namespace lala
>   foo : Nat
> namespace lula
>   foo : Nat

> i : Nat
> i = foo
```
I find it a bit strange to have different mechanisms -- namespaces and named instances -- to cope with apparently the same problem. Why not just namespaces?
