### ISSUE TITLE
Proof search not filling in goal with matching assumption

### ISSUE THREAD

**Issue by LeifW** [idris-lang/Idris-dev#2060]
Given the following (I started with the type sig, and then ran \d followed by \c to case-split in vim):
```idris
fold : List elm -> acc -> (acc -> elm -> acc) -> acc
fold [] x f = ?fold_rhs_1
fold (y :: xs) x f = ?fold_rhs_2
```
proof search on `?fold_rhs_1` doesn't fill in the (correct) impl of `x`, even though the type hole is of type `acc`, and so is `x`. My understanding of proof search is that it first used in-scope assumptions (arguments) if they matched the goal type, and next tried constructors for that type.
This program typechecks if you manually replace that metavar with `x`.

Also, when doing the interactive proof script mode on that type hole, you get `INTERNAL ERROR: Ambiguous name`:
```
*Fold> :p fold_rhs_1


----------                 Goal:                  ----------
{hole0} : (acc : Type) -> acc -> (elm : Type) -> (acc -> elm -> acc) -> acc
-Fold.fold_rhs_1> intros
----------              Other goals:              ----------
{hole3},{hole2},{hole1},{hole0}
----------              Assumptions:              ----------
 acc : Type
 x : acc
 elm : Type
 f : acc -> elm -> acc
----------                 Goal:                  ----------
{hole4} : acc
-Fold.fold_rhs_1> search
INTERNAL ERROR: Ambiguous name
This is probably a bug, or a missing error message.
Please consider reporting at https://github.com/idris-lang/Idris-dev/issues
```

**Comment by LeifW** [comment]
Smaller case:
```idris
blah : a -> a
blah x = ?blah_rhs
```
Same behaviour / errour message.

**Comment by edwinb** [comment]
Seems to be a clash of assumptions - proof search assumed it was working on data types at the top level, then later assumed the thing it was looking up would have at least one result. The ambiguous name error actually results from there being no such name 'acc' globally...

Anyway, that first assumption is false, so we're no longer making it.
