### ISSUE TITLE
The Provisional definitions has a bug that can mislead programmers

### ISSUE THREAD

**Issue by TorosFanny** [idris-lang/Idris-dev#2061]
I simply tried this:

append : Vect n a -> Vect m a -> Vect (m + n) a
append []           ys ?= ys++ys                   --It's not true, but I can prove it easily
append (x :: xs) ys ?= x :: append xs ys

I can prove the append_lemma_1 with this:
simple.append_lemma_1 = proof
  intros
  rewrite sym (plusZeroRightNeutral m)
  exact ys

It can be loaded into REPL, but `append [] [3, 4]` gives
[3,4]
just as constructed in the proof. The provisional definitions seems to do nothing at all.

**Comment by edwinb** [comment]
What is it?

?= doesn't make any claims about the final reduction behaviour - it's 
always possible to write something which is misleading here. But it's 
quite possible to write misleading programs in lots of ways (implicit 
conversions, giving variable strange names, etc).

**Comment by TorosFanny** [comment]
But I think this issue is unique to Idris.
If we just replace the first `?=` to `=`, and it will complain that

#Can't unify
#               m
#        with
#                plus m 0

Maybe `m = plus m 0` is what we should prove

**Comment by edwinb** [comment]
Perhaps we should change it, but the current behaviour is exactly what is documented, and is as it is because it's much easier to implement and describe, especially in the presence of dependent things (equalities get tricky when the index depends on something too).
