### ISSUE TITLE
Nats aren't showed properly

### ISSUE THREAD

**Issue by TorosFanny** [idris-lang/Idris-dev#2063]
test 1:
I wrote a file named fib.idr with content like this:

fibs : Stream Nat
fibs = 0 :: 1 :: zipWith (+) fibs (tail fibs)

And I loaded it and tried this. 
*try> take 15 fibs 
[0,
 1,
 1,
 2,
 3,
 5,
 8,
 13,
 21,
 34,
 55,
 89,
 144,
 233,
 S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (plus 43 ...

All `take n fibs ` with n < 15 print normally and all with n >= 15 print abnormally to my experience.

test 2:
I wrote a file named c.idr with content like this:

c : Stream Nat
c = 0 :: map S c

And I loaded it and tried this. 

*c> take 1 c
[0] : List Nat
*c> take 2 c
[0, 1] : List Nat
*c> take 3 c
[0, 1, 2] : List Nat
*c> take 4 c
-- oops. The tail is `))))))))) : List Nat`

My Environment:
Platform Ubuntu 14.04
GHC7.8.4
master HEAD build with
CABALFLAGS += -f LLVM -f FFI -f curses -f gmp
CI = true

**Comment by edwinb** [comment]
This is expected behaviour. Reduction at the repl cuts off after a 
number of steps, which it seems to have hit here (I'm not so surprised 
about that). Try compiling it and it'll be fine.

**Comment by TorosFanny** [comment]
But it's obvious that the output isn't very pretty and need some refine

**Comment by edwinb** [comment]
What should it look like? There's an unevaluated Nat there, and there 
will be other special cases like this - we can't add hacks for every 
special case.

Maybe we could add some way to tune the reduction limit, or even turn it 
off. It may even be that it's not necessary any more - I can't remember 
exactly why we added it.

**Comment by TorosFanny** [comment]
The spaces between `plus 43` and `233)))))....` may be easily reduced into one, I think.
