### ISSUE TITLE
":let c = 0 :: map S c" reports "No such variable c" when it's in REPL

### ISSUE THREAD

**Issue by TorosFanny** [idris-lang/Idris-dev#2064]
Idris> :let c = 0 :: map S c
When elaborating an application of function Prelude.Functor.map:
        No such variable c

I expected it should behaves like when I was in ghci REPL.

But when I write the following content into a file named c.idr and load it, all worked fine.
c : Stream Nat
c = 0 :: map S c

Maybe it's because of the absence of type declaration, but I currently don't know how to add type declaration in REPL

**Comment by edwinb** [comment]
This is expected behaviour. c isn't in scope in the body of the 
definition because you haven't given a type declaration for it. You can 
add a type declaration in the REPL just like in a file.

:let c : Stream Nat; c = 0 :: map S c

**Comment by TorosFanny** [comment]
I understand, thank you
