### ISSUE TITLE
Type error when using "intros" tactic in REPL

### ISSUE THREAD

**Issue by gonzaw** [idris-lang/Idris-dev#2072]
I'm trying to prove a theorem using tactics in the REPL (and in idris-mode too), but when I use "intros" (and even "intro" alone) I get the following type error:
Can't convert
Type
with
(a : Type) ->
(b : Type) -> (a -> b) -> (iType : Type) -> (b -> iType) -> a -> iType

I'm attaching a screenshot, which includes the goal too.

I'm using idris 0.9.17. This error happens both in the common REPL (using the command line) and in idris-mode.

![screenshot from 2015-03-29 02 37 35](https://cloud.githubusercontent.com/assets/6629501/6884254/c7ea9f98-d5bd-11e4-917a-72a2554b3c60.png)

**Comment by edwinb** [comment]
This is fixed in 0.9.17.1,which is on hackage
