### ISSUE TITLE
getLine inconsistent behaviour

### ISSUE THREAD

**Issue by JakobBruenker** [idris-lang/Idris-dev#2073]
The output of the following program

```idris
main : IO ()
main = map show getLine >>= putStrLn
```
results in the following output, if the user enters `foo`:
```idris
"foo\n"
```
Which means getLine appends a '\n' to its result.

However, in the REPL, writing
```idris
:x the (IO ()) $ map show getLine >>= putStrLn
```
results in this, if the user enters `foo`:
```idris
"foo"
```
So here, getLine doesn't append a '\n'.

**Comment by edwinb** [comment]
I'm not bothered which way this goes, as long as it's consistent. Any volunteers?
