### ISSUE TITLE
Implicit pattern matching unexpected behaviour

### ISSUE THREAD

**Issue by chamini2** [idris-lang/Idris-dev#2075]
Hi, we were trying to create a `neutral` function without writing a class, but pattern matching on the `Type` to return, and give an appropiate value.

    cero : {a : Type} -> a
    cero {a = Integer} = 0

We started with that function, and when loading it in the interactive prompt it compiled correctly:

    *cero> the Integer cero
    0 : Integer

Afterwards, we tried to add a `Bool` option with `False`:

    cero : {a : Type} -> a
    cero {a = Integer} = 0
    cero {a = Bool}    = False

And got this:

    *cero> :r
    Type checking ./cero.idr
    cero.idr:3:6:When elaborating right hand side of cero:
    Can't unify
            Bool
    with
            Bool

    Specifically:
            Can't unify
                    Bool
            with
                    Bool
    Metavariables: Main.cero

So we tried `Bool` by itself:

    cero : {a : Type} -> a
    --cero {a = Integer} = 0
    cero {a = Bool}    = False

But got the same type-checking error.

We tried with `Nat` and got the same, only `Integer` works (and was the first one we tried with, that's just coincidence).

*****

Another thing we came across with this example is that when only using `Integer` in the pattern matching it compiles, but behaves weird anyways:

    *cero> the Bool cero
    0 : Bool
    *cero> the Nat cero
    0 : Nat
    *cero> the (List Void) cero
    0 : List Void

And also this happened:

    *cero> the cero
    id : 0 -> 0

Which shouldn't type-check because `cero` is of type `a`, where `a : Type`, so `cero` is never of type `Type`, where the signature of `the` is:

    the : (a : Type) -> a -> a

**Comment by edwinb** [comment]
What version are you using? Matching on types hasn't been allowed for a 
while (nor should it be since it breaks parametricity and types aren't 
available at run-time anyway) and when it was it didn't work anyway 
(which wasn't surprising).

**Comment by chamini2** [comment]
$ idris --version
    0.9.15.1

**Comment by edwinb** [comment]
Right - you'll definitely not get the behaviour in the latest version, which is 0.9.17.1.
