### ISSUE TITLE
Foldable instance for List is silly

### ISSUE THREAD

**Issue by treeowl** [idris-lang/Idris-dev#2086]
The `foldr` for `List` is defined tail-recursively. There is no good reason to expect this to offer any meaningful efficiency benefit. The only situation where a `foldr` on a list is fast enough to be practically useful is when the function being folded is lazy in its second argument, and in that situation only a `foldr` that is *not* tail recursive will be fast. For proofs, a non-tail-recursive version should be much more useful.

The `foldl` method for lists is allowed to take its default value, which can be expected to give terrible performance with the current `foldr` implementation. If `foldr` is fixed, it may be possible to leave `foldl` alone, but it would likely be better to redefine it in the natural tail-recursive fashion.

**Comment by treeowl** [comment]
See #2088.

**Comment by jfdm** [comment]
@treeowl your recent PR #2088 was accepted and merged. Is this issue still pertinent?
