### ISSUE TITLE
Proof via tactics checks correctly, but source doesn't type check

### ISSUE THREAD

**Issue by gonzaw** [idris-lang/Idris-dev#2087]
Hi.
I encountered a weird situation, where I have to create a proof of a certain proposition. I am able to find it using tactics, and idris is happy about it. However, after I compile the source (with the added proof) it gives me a typecheck error.
If I try including the expression that gives said error into the source code explicitly, it throws that error as well.
I don't know if the type checker doesn't typecheck it for some reason, when the proof is correct, or the problem is with the tactics system of the REPL, which shows an incorrect proof as correct.
I personally think the proof is correct and should typecheck, but I guess I am not really sure

This is the goal I'm trying to prove

    ?theorem_compile_rhs_plus : (e1 : Exp TyNat) -> (e2 : Exp TyNat) -> (sType : StackType) -> (s : Stack sType) -> SCons (plus (eval e1) (eval e2)) s = exec AddC (exec (compile e1) (exec (compile e2) s))

Screenshots:

![idris_proof_1](https://cloud.githubusercontent.com/assets/6629501/6928871/6f58f638-d7cd-11e4-89bb-aeda6fd2d3fd.png)

![idris_proof_2](https://cloud.githubusercontent.com/assets/6629501/6928873/73a255d6-d7cd-11e4-8812-6dcd537a4aff.png)

![idris_proof_3](https://cloud.githubusercontent.com/assets/6629501/6928874/75e54664-d7cd-11e4-92bc-cbf0b49f10c6.png)

It may be related to this issue that appears too, which seems weird too (since I believe I applied "with" correctly):

![idris_proof_4](https://cloud.githubusercontent.com/assets/6629501/6928884/7ac0b7a4-d7cd-11e4-86cd-476488184c08.png)

The relevant code is this:

    data TyExp = TyNat | TyBool

    Val : TyExp -> Type
    Val TyNat = Nat
    Val TyBool = Bool

    data Exp : TyExp -> Type where
      ValE : {t : TyExp} -> (v : Val t) -> Exp t
      PlusE : (e1 : Exp TyNat) -> (e2 : Exp TyNat) -> Exp TyNat
      IfE : {t : TyExp} -> (b : Exp TyBool) -> (e1 : Exp t) -> (e2 : Exp t) -> Exp t

    StackType : Type
    StackType = List TyExp

    data Stack : StackType -> Type where
      EmptyS : Stack []
      SCons : {t : TyExp} -> {sType : StackType} -> (v : Val t) -> (s : Stack sType) -> Stack (t :: sType)

    eval : {t : TyExp} -> Exp t -> Val t
    exec : (code : Code s0 s1) -> (stack : Stack s0) -> Stack s1
    compile : {t : TyExp} -> (e : Exp t) -> Code s (t :: s)
    -- Code for the above omitted

    theorem_compile : {t : TyExp} -> (e : Exp t) -> (s : Stack sType) -> SCons (eval e) s = exec (compile e) s
    theorem_compile (ValE v) s = Refl
    theorem_compile (PlusE e1 e2) s = ?theorem_compile_rhs_plus
    theorem_compile (IfE b e1 e2) s with (decEq (eval b) True)
    theorem_compile (IfE b e1 e2) s | Yes prf = ?theorem_compile_rhs_if_true
    theorem_compile (IfE b e1 e2) s | No prfNo = ?theorem_compile_rhs_if_false

If necessary I can include the whole code (but it's a little big, so I posted the relevant snippets above)
Could it be a problem with some implicits?

I'm using idris 0.19.7.1

**Comment by gonzaw** [comment]
The proof created by idris is the following:

    Main.theorem_compile_rhs_plus = proof
        intros
        let pfE2 = theorem_compile e2 s
        rewrite pfE2
        let pfE1 = theorem_compile e1 (SCons (eval e2) s)
        rewrite pfE1
        compute
        trivial

If I make this change, I can finally get it to compile

    let pfE1 = theorem_compile e1 (SCons {t=TyNat} (eval e2) s)

Though it gives me the following warning:

    Main.theorem_compile is possibly not total due to: Main.theorem_compile_rhs_plus

Though this specific issue can be solved by explicitly defining the implicit argument, I still believe idris should generate sources that typecheck (for example generating the source with the above fix into it)

**Comment by ahmadsalim** [comment]
I will close this issue since tactics are going to be phased out in favour of elaborator reflection.
