### ISSUE TITLE
Interative proves with implicit arguments render source file broken.

### ISSUE THREAD

**Issue by raichoo** [idris-lang/Idris-dev#209]
I'm trying to prove the following proposition via tactics.

    module Main    
    foo : a -> b -> a

    *foo> :p foo
    ----------                 Goal:                  ----------
    { hole 0 }:
     (a : Type) -> (b : Type) -> a -> b -> a
    -Main.foo> intro a
    ----------              Other goals:              ----------
    { hole 0 } 
    ----------              Assumptions:              ----------
     a : Type
    ----------                 Goal:                  ----------
    { hole 1 }:
     (b : Type) -> a -> b -> a
    -Main.foo> intro b
    ----------              Other goals:              ----------
    { hole 1 } 
    { hole 0 } 
    ----------              Assumptions:              ----------
     a : Type
     b : Type
    ----------                 Goal:                  ----------
    { hole 2 }:
     a -> b -> a
    -Main.foo> intro x
    ----------              Other goals:              ----------
    { hole 2 } 
    { hole 1 } 
    { hole 0 } 
    ----------              Assumptions:              ----------
     a : Type
     b : Type
     x : a 
    ----------                 Goal:                  ----------
    { hole 3 }:
     b -> a
    -Main.foo> intro y
    ----------              Other goals:              ----------
    { hole 3 } 
    { hole 2 } 
    { hole 1 } 
    { hole 0 } 
    ----------              Assumptions:              ----------
     a : Type
     b : Type
     x : a 
     y : b 
    ----------                 Goal:                  ----------
    { hole 4 }:
     a   
    -Main.foo> refine x
    foo: No more goals.
    -Main.foo> qed 
    Main.foo = proof {
      intro a;
      intro b;
      intro x;
      intro y;
      refine x;
    }

The function works as expected.

    *foo> :addproof
    Added proof Main.foo
    *foo> foo 666 "foo"
    666 : Int

Loading after that does not work anymore.

        ____    __     _ 
       /  _/___/ /____(_)____                                  
       / // __  / ___/ / ___/     Version 0.9.6.1
     _/ // /_/ / /  / (__  )      http://www.idris-lang.org/   
    /___/\__,_/_/  /_/____/       Type :? for help             

    Type checking ./foo.idr
    foo.idr:7:INTERNAL ERROR: "Nothing to introduce"
    This is probably a bug, or a missing error message.
    Please consider reporting at https://github.com/edwinb/Idris-dev/issues

Changing the typesignature to `foo : (a, b : Type) -> a -> b -> a` fixes the issue.

It looks like Idris is not aware of the implicit arguments when parsing the proof
from source therefore it complains that there is `Nothing to introduce`.

**Comment by edwinb** [comment]
I'm closing this because I don't think anyone has any intention of maintaining the interactive proof mode further now that elaborator reflection is making progress, and that will have a better way around this problem anyway.
