### ISSUE TITLE
error from c compiler after generating code

### ISSUE THREAD

**Issue by ezrosent** [idris-lang/Idris-dev#2107]
I have some code that works without errors in the idris REPL and with the javascript code generated by idris-node, but which gets errors from gcc (or clang) when generating a binary from C code. The error is as follows:
```
> $ ./idris Bos_main.idr -p effects -o FLK_bos 
/var/folders/5t/px6kvwwx3l17pccr6c3bqll80000gn/T/idris56145:4790:10: error: duplicate case value '65725'
    case 65725:
         ^
/var/folders/5t/px6kvwwx3l17pccr6c3bqll80000gn/T/idris56145:4780:10: note: previous case defined here
    case 65725:
         ^
/var/folders/5t/px6kvwwx3l17pccr6c3bqll80000gn/T/idris56145:4905:10: error: duplicate case value '65738'
    case 65738:
         ^
/var/folders/5t/px6kvwwx3l17pccr6c3bqll80000gn/T/idris56145:4895:10: note: previous case defined here
    case 65738:
         ^
/var/folders/5t/px6kvwwx3l17pccr6c3bqll80000gn/T/idris56145:4925:10: error: duplicate case value '65740'
    case 65740:
         ^
/var/folders/5t/px6kvwwx3l17pccr6c3bqll80000gn/T/idris56145:4915:10: note: previous case defined here
    case 65740:
         ^
/var/folders/5t/px6kvwwx3l17pccr6c3bqll80000gn/T/idris56145:9286:6: error: redefinition of '_idris_FLK_95_bos_46__123_case_32_block_32_in_32_case_32_block_32_in_32_evalCFI10_125_'
void _idris_FLK_95_bos_46__123_case_32_block_32_in_32_case_32_block_32_in_32_evalCFI10_125_(VM* vm, VAL* oldbase) {
     ^
/var/folders/5t/px6kvwwx3l17pccr6c3bqll80000gn/T/idris56145:6417:6: note: previous definition is here
void _idris_FLK_95_bos_46__123_case_32_block_32_in_32_case_32_block_32_in_32_evalCFI10_125_(VM* vm, VAL* oldbase) {
     ^
/var/folders/5t/px6kvwwx3l17pccr6c3bqll80000gn/T/idris56145:9312:6: error: redefinition of '_idris_FLK_95_bos_46__123_case_32_block_32_in_32_evalCFI10_125_'
void _idris_FLK_95_bos_46__123_case_32_block_32_in_32_evalCFI10_125_(VM* vm, VAL* oldbase) {
     ^
/var/folders/5t/px6kvwwx3l17pccr6c3bqll80000gn/T/idris56145:6460:6: note: previous definition is here
void _idris_FLK_95_bos_46__123_case_32_block_32_in_32_evalCFI10_125_(VM* vm, VAL* oldbase) {
     ^
/var/folders/5t/px6kvwwx3l17pccr6c3bqll80000gn/T/idris56145:9371:6: error: redefinition of '_idris_FLK_95_bos_46__123_case_32_block_32_in_32_evalCFI11_125_'
void _idris_FLK_95_bos_46__123_case_32_block_32_in_32_evalCFI11_125_(VM* vm, VAL* oldbase) {
     ^
/var/folders/5t/px6kvwwx3l17pccr6c3bqll80000gn/T/idris56145:7005:6: note: previous definition is here
void _idris_FLK_95_bos_46__123_case_32_block_32_in_32_evalCFI11_125_(VM* vm, VAL* oldbase) {
     ^
6 errors generated.
FAILURE: "gcc" ["-O2","-fwrapv","-fno-strict-overflow","-DHAS_PTHREAD","-DIDRIS_ENABLE_STATS","-I.","-x","c","/var/folders/5t/px6kvwwx3l17pccr6c3bqll80000gn/T/idris56145","-L/Users/ezrosenthal/Library/Haskell/ghc-7.8.3/lib/idris-0.9.16/share/rts","-lidris_rts","-lpthread","-I/Users/ezrosenthal/Library/Haskell/ghc-7.8.3/lib/idris-0.9.16/share/rts","-I.","-I/Users/ezrosenthal/Library/Haskell/ghc-7.8.3/lib/idris-0.9.16/share/effects","-I../base","-I../prelude","-I.","-I/Users/ezrosenthal/Library/Haskell/ghc-7.8.3/lib/idris-0.9.16/share/prelude","-I/Users/ezrosenthal/Library/Haskell/ghc-7.8.3/lib/idris-0.9.16/share/base","-o","FLK_bos"]
```
I am writing this code for a class so I am not sure how much of this code I can post here, but I'll be able to post more in the morning once I have permission from an instructor. I am running OS X. This happens with both version 0.9.16 and 0.9.17. 

Thanks!

**Comment by edwinb** [comment]
Hi,
I haven't seen anything like this before, so unfortunately I have no 
idea without seeing the code itself. If you aren't able to post it here, 
perhaps it would be okay to mail to to me directly?

Or if it's possible to create a minimal failing example, that would be 
even better.

Edwin.

**Comment by ezrosent** [comment]
Okay! I confirmed with my instructor that I could post the work on a public repo. The error shows up compiling [Bos_main.idr](https://github.com/ezrosent/FLK-Semantics/blob/master/Bos_main.idr), which depends on [FLK_bos.idr](https://github.com/ezrosent/FLK-Semantics/blob/master/FLK_bos.idr) and [FLK_ast.idr](https://github.com/ezrosent/FLK-Semantics/blob/master/FLK_ast.idr). This is my first attempt at idris; I am using this for a programming languages class. I may have some time in a few days to pare this down to a smaller example, but my guess looking at the generated function names is that there is an issue in eval_CFI in FLK_bos.idr. 

Thanks!
--Eli

**Comment by markuspf** [comment]
The problem exists in the JS backend as well, it looks as if idris produces duplicate cases, the JS backend just deals with it differently, but the cases are there in the generated javascript.

**Comment by edwinb** [comment]
This turns out to have been caused by name clashes when lambda lifting; the name generation should generate unique names but for various reasons generated clashing ones. It seems it took some particular combination of nested cases to trip over this. Fix coming shortly. Thanks for the report and the code.
