### ISSUE TITLE
FFI_C pointer handling bug

### ISSUE THREAD

**Issue by davidpeklak** [idris-lang/Idris-dev#2113]
I am facing a problem when trying to allocate and free memory though the C FFI. The bug is a bit cumbersome to reproduce: I have to build a package first, and then use it. The minimal structure I need for this can be found here:
https://github.com/davidpeklak/ffiexp

Note that if I change this line https://github.com/davidpeklak/ffiexp/blob/master/FfiExpTest.idr#L12 such that I do not use the package that I am building, I get no error.
Also, the address that I allocate and the one that I try to free (in the error case) always resemble each other in the last digits. (e.g. 0x7ff6e2d011c0, 0xffffffffe2d011c0) 

I am doing this on a Mac Book Intel Core i7, OS X 10.9.5 (13F34), idris v 0.9.17.1-

**Comment by markuspf** [comment]
It looks as if your pointer is truncated to 32 bits somewhere on the way and then extended back to 64 bits (apparently sign extended, i.e. the upper bits are all set to the value of the highest bit in the 32bit representation). I cannot reproduce the problem on my machine which suggests a problem with how things are built on your machine (the ffiexp.o in the github is 64bit Mach-O).

Did you try just compiling your code using idris and running it? Does the problem persist? Can you find out what architecture your compiler produces files for (in particular whether there's anywhere in the chain that does 32bit, look in the temporary directory for the executables that the REPL produces and see what architecture they are compiled for).

**Comment by davidpeklak** [comment]
So I tried compiling the code to an executable and running it, and the problem does persist. The executable that idris produces is a Mach-O 64-bit executable x86_64 however.
I installed idris on my machine from here:
http://www.idris-lang.org/pkgs/idris-current.pkg
I will try to build idris from source instead and check if the problem persists.

**Comment by davidpeklak** [comment]
I installed idris in a cabal sandbox as described [here](https://github.com/idris-lang/Idris-dev/wiki/Idris-on-OS-X-using-Homebrew) with `cabal install idris --constraint='blaze-markup <0.6.3'`as suggested [here](https://github.com/ekmett/trifecta/issues/41) (because it would fail otherwise). Using idris from that sandbox for building the package and running solves the problem.

**Comment by markuspf** [comment]
I do not have the knowledge to fix this on MacOS, but this should be either fixed or documented. For some reason 32bit and 64bit code (or rather, code with 32bit pointers and code with 64bit pointers) are happily linked together and assumed to work together which is quite obviously not the case. Someone with more knowledge of MacOS will need to address this.

**Comment by melted** [comment]
Seems this is resolved and is unlikely to go further.
