### ISSUE TITLE
Idris fails to resolve an implicit parameter

### ISSUE THREAD

**Issue by markuspf** [idris-lang/Idris-dev#2115]
With the following silly idris code

```
module Main

import Data.Fin

import Data.VectType
import Data.Vect

data Permutation : Nat -> Type where
  Nil : Permutation Z
  (::) : Fin (S n) -> Permutation n -> Permutation (S n)

mutual
  permute : Permutation n -> Vect n elt -> Vect n elt 
  permute = permute'

  permute' : Permutation n -> Vect n elt -> Vect n elt 
  permute' [] [] = []
  permute' {elt} (k::p) (a::as) = insert (permute' p as) k
    where insert : Vect n elt -> Fin (S n) -> Vect (S n) elt 
          insert xs FZ = a :: xs
          insert [] (FS i) = [a] 
          insert (x::xs) (FS k) = x :: insert xs k

id : Permutation n
id {n=Z} = []
id {n=S n} = FZ :: id

psplit : {r : Nat} -> (s : Nat) -> Permutation (s + r) -> Vect (s + r) a -> (Vect s a, Vect r a)
psplit s perm v = (splitAt s) $ (permute perm v)

t1 : Vect 4 Int
t1 = [1,2,3,4]
```

I can do the following

```
test> psplit 0 id t1
([], [1, 2, 3, 4]) : (Vect 0 Int, Vect 4 Int)
test> psplit 4 id t1
([1, 2, 3, 4], []) : (Vect 4 Int, Vect 0 Int)
```

But interestingly not

```
test> psplit 4 ((FS FZ) :: id) t1
(input):0:0:No such variable r
```

I can help it along by giving it the value of the implicit parameter though, or by constructing the permutation differently:

```
test> psplit {r=0} 4 ((FS FZ) :: id) t1
([2, 1, 3, 4], []) : (Vect 4 Int, Vect 0 Int)
test> psplit 4 [1,0,0,0] t1
([2, 1, 3, 4], []) : (Vect 4 Int, Vect 0 Int)
```

This I would maybe not be too fussed by if it only happened in the repl, but it also happens when compiling.

Maybe I am missing something silly here, then I'd be grateful for a pointer.

**Comment by edwinb** [comment]
All it has to go on here is (s + r), since it doesn't have the return 
type, and it isn't going to infer an r from that even if it knows the s, 
since + is a function which could be anythng as far as the unifier is 
concerned. So I wouldn't expect it to be able to resolve r here.

It should say "incomplete term" rather than no such variable, however.

This is an example of the sort of code that I'd expect to work fine in a 
program but the repl will struggle with because it has to infer a type.

**Comment by markuspf** [comment]
Should something like

```
idris> the ((Vect _ _), (Vect _ _)) (psplit 4 ((FS FZ) :: id) t1))
```

work then? (because it doesn't) I tried checking that this is not a problem where there is not enough type information around (Including compiling a program, which might have been lost in the slightly verbose issue report), but maybe I am still expecting too much magic.

**Comment by ahmadsalim** [comment]
It seems that Idris has gotten a bit smarter:

```idris
*test> psplit 4 ((FS FZ) :: id) t1
([2, 1, 3, 4], []) : (Vect 4 Int, Vect 0 Int)
```
