### ISSUE TITLE
Totality checker says "missing cases" when obviously there are not

### ISSUE THREAD

**Issue by falsifian** [idris-lang/Idris-dev#2119]
This bug is like https://github.com/idris-lang/Idris-dev/issues/1928: I understand the totality checker is not guaranteed to mark every total function as total, but I don't understand why the below case is difficult for it.

Idris 0.9.17.1- when given the below program says ```./tmp/bug.idr:7:1:Main.f is not total as there are missing cases```, even though it is perfectly happy to say ```g``` is total.

    %default total

    t : Type
    t = (a : Nat) -> (Z = S Z) -> Void

    f : t
    f Z Refl impossible
    f (S _) Refl impossible

    g : t
    g _ Refl impossible

**Comment by edwinb** [comment]
I think it's just because the checker forgets to normalise the type 
before checking for missing cases so fails to generate them properly. If 
you replace the type by hand, it works fine.

While I can probably fix this quickly when I get around to it, it would 
be a good opportunity for someone else to look at the coverage checker 
(and hopefully improve it...) by fixing something relatively easy. 
Anyone interested?

**Comment by benjamin-hodgson** [comment]
I think I may have run into the same issue:

```idris
%default total

emptyListsHaveZeroLength :
       (xs : List a)           -- give me a list
    -> (c : isCons xs = False) -- and a proof that the list is not a cons cell
    -> length xs = 0           -- and i'll give you a proof that the list has 0 length
emptyListsHaveZeroLength [] {c=p} = Refl
emptyListsHaveZeroLength (x::xs) {c=Refl} impossible
```

Just putting it here as further documentation :smiley:

**Comment by mietek** [comment]
Another example:

```idris
%default total


Bool_ : Type
Bool_ = {a : Type} -> a -> a -> a

true_ : Bool_
true_ = \a, a' => a

false_ : Bool_
false_ = \a, a' => a'

toBool_ : Bool -> Bool_
toBool_ True = true_
toBool_ False = false_
```

Replacing `toBool_ : Bool -> Bool_` with `toBool_ : Bool -> a -> a -> a` is a workaround.

**Comment by edwinb** [comment]
All of these examples get past the totality checker now.
