### ISSUE TITLE
Class resolution trouble

### ISSUE THREAD

**Issue by treeowl** [idris-lang/Idris-dev#2136]
This may or may not be a proper bug, but it's a bit surprising to me. I have a class for "measuring" things with some semigroup:
```idris
class Semigroup v => Measurable (a : Type) (v : Type) | a where
  measure : a -> v
```
I would expect that the following would be able to determine `v` from `a` and be happy, but it doesn't work.

```idris
data Node : (a : Type) -> Measurable a v -> Type where
  Node2 : (m : v) -> (x : a) -> (y : a) ->
          .(pf : m = measure x <+> measure y) ->
                 Node a mai
  Node3 : (m : v) -> (x : a) -> (y : a) -> (z : a) ->
          .(pf : m = measure x <+> measure y <+> measure z) ->
                 Node a mai
```

Instead, I seem to need

```idris
data Node : (v : Type) -> (a : Type) -> Measurable v a -> Type where
  Node2 : (m : v) -> (x : a) -> (y : a) ->
          .(pf : m = measure x <+> measure y) ->
                 Node v a mai
  Node3 : (m : v) -> (x : a) -> (y : a) -> (z : a) ->
          .(pf : m = measure x <+> measure y <+> measure z) ->
                 Node v a mai
```

**Comment by edwinb** [comment]
It also works if you are explicit about `{mai : Measurable a v} ->` in `Node2` and `Node3`. It should probably do better about inferring this earlier, or at least knowing it before resolve type classes, but at the moment sometimes you need to be a bit more explicit than you'd like and give types for the unbound explicits.
