### ISSUE TITLE
dependent map confuses the typechecker

### ISSUE THREAD

**Issue by identicalsnowflake** [idris-lang/Idris-dev#2142]
The following code works:

```idris

isPrime : Nat -> Bool
isPrime a =
    (==0)
    $ length
    $ filter (==0)
    $ map (modNat a) [2..(a-1)]

data PN : Bool -> Type where
    MkPN : (n:Nat) -> PN (isPrime n)

test1 : List (PN True)
test1 = [MkPN 2, MkPN 3, MkPN 5, MkPN 11, MkPN 23, MkPN 31]

-- test2 : List (PN True)
-- test2 = map MkPN [2]

```

However, if I uncomment test2, typechecking fails.

I'm guessing the reason is that if you think about partially applying (map MkPN), it can't figure out how to make a dependently-typed functor instance.

EDIT: The more I think about this, I think I'm the one that's confused. Does Functor even exist in the dependently-typed world?

**Comment by edwinb** [comment]
It's a long error message, but it is correct behaviour - the "a -> b" 
expected by map doesn't unify with the "(n : Nat) -> PN (isPrime n)" 
given by MkPN because of the binding of n.

**Comment by david-christiansen** [comment]
Should we close this?

**Comment by identicalsnowflake** [comment]
I understand what's happening now. I was incorrectly thinking in syntactic terms, as if map were simply a shorthand syntax for writing out the list, and that is incorrect. map has semantic meaning which is not (in the case of applying a dependent function) the same thing as simply a syntactic shorthand.

Sorry to bother everyone with that! I'll close this now.

**Comment by david-christiansen** [comment]
It's no bother :)
