### ISSUE TITLE
Namespaces lead to internal errors

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2150]
The following program type checks fine
````
> import Data.Fin
> import Data.Vect
> import Control.Isomorphism

> %default total

> -- namespace ScrewUp
> --   k : Fin 2

> postulate lambdaLemma1 : {A, B : Type} -> (f : A -> B) -> (\ a => f a) = f

> isoCong : {A : Type} -> {x : A} -> {y : A} -> {P : A -> Type} -> x = y -> Iso (P x) (P y)
> isoCong {x} {P} prf = replace {P = \ z => Iso (P x) (P z)} prf isoRefl 

> tail : {A : Type} -> (Fin (S n) -> A) -> (Fin n -> A)
> tail f k = f (FS k)

> sigmaEitherLemma : {n : Nat} -> 
>                    {P : Fin (S n) -> Type} ->
>                    Iso (Sigma (Fin (S n)) P) (Either (P FZ) (Sigma (Fin n) (tail P)))

> sigmaFinEitherLemma : {n : Nat} -> {f : Fin (S n) -> Nat} ->
>                       Iso 
>                       (Sigma (Fin (S n)) (Fin . f)) 
>                       (Either (Fin (f FZ)) (Sigma (Fin n) (Fin . (tail f))))
> sigmaFinEitherLemma {n} {f} =
>     ( Sigma (Fin (S n)) (Fin . f)                                     ) 
>   ={ sigmaEitherLemma {n = n} {P = Fin . f} }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (tail (Fin . f)))            )     
>   ={ isoCong {P = \ X => Either (Fin (f FZ)) (Sigma (Fin n) X)} (sym (lambdaLemma1 (tail (Fin . f)))) }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (\ k => (tail (Fin . f)) k)) )     
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (\ k => (Fin . f) (FS k)))   )     
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (\ k => Fin (f (FS k))))     )     
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (\ k => Fin ((tail f) k)))   )     
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (\ k => (Fin . (tail f)) k)) )     
>   ={ isoCong {P = \ X => Either (Fin (f FZ)) (Sigma (Fin n) X)} (lambdaLemma1 (Fin . (tail f))) }=
>     ( Either (Fin (f FZ)) (Sigma (Fin n) (Fin . (tail f)))            )
>   QED
```
But uncommenting 
````
> -- namespace ScrewUp
> --   k : Fin 2
```
yields the internal error
````
- + Errors (1)
 `-- internal_error.lidr line 26 col 20:
     When elaborating right hand side of sigmaFinEitherLemma:
     When elaborating an application of function Control.Isomorphism.step:
             Unifying b and Either (Fin (f FZ))
                                   (Sigma (Fin n)
                                          (\lamp =>
                                             case block in sigmaFinEitherLemma n
                                                                               f
                                                                               b
                                                                               lamp
                                                                               lamp)) would lead to infinite value
```

**Comment by patrikja** [comment]
Here is the file with the error:
https://github.com/nicolabotta/SeqDecProbs/blob/717518cb7bebc4302d855e274138a617f1cad2ae/issue_reports/internal_error.lidr

The error is triggered when there is a "k" is scope, but not if it is called "ko".

As far as I can tell there are no free "k"s in the code so this should be a real bug and not a forgotten "implicit implicit".
/Patrik

**Comment by ahmadsalim** [comment]
This still seems to be an error.

**Comment by nicolabotta** [comment]
Thanks for looking into this issue Ahmad! The error is still there with 0.11-git:7e7d0eb. It seems that `Troublemaker.k` somehow interferes with lambda declarations because also replacing
```
> import Data.Fin
> import Data.Vect
> import Control.Isomorphism

> namespace Troublemaker
>   k : Fin 2
>   k = FS FZ

> postulate lambdaLemma1 : {A, B : Type} -> (f : A -> B) -> (\ a => f a) = f

> isoCong : {A : Type} -> {x : A} -> {y : A} -> {P : A -> Type} -> x = y -> Iso (P x) (P y)
> isoCong {x} {P} prf = replace {P = \ z => Iso (P x) (P z)} prf isoRefl 

> tail : {A : Type} -> (Fin (S n) -> A) -> (Fin n -> A)
> tail f k = f (FS k)

> sigmaEitherLemma : {n : Nat} -> 
>                    {P : Fin (S n) -> Type} ->
>                    Iso (DPair (Fin (S n)) P) (Either (P FZ) (DPair (Fin n) (tail P)))

> sigmaFinEitherLemma : {n : Nat} -> {f : Fin (S n) -> Nat} ->
>                       Iso
>                       (DPair (Fin (S n)) (Fin . f))
>                       (Either (Fin (f FZ)) (DPair (Fin n) (Fin . (tail f))))
> sigmaFinEitherLemma {n} {f} =
>     ( DPair (Fin (S n)) (Fin . f)                                     )
>   ={ sigmaEitherLemma {n = n} {P = Fin . f} }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (tail (Fin . f)))            )
>   ={ isoCong {P = \ X => Either (Fin (f FZ)) (DPair (Fin n) X)} (sym (lambdaLemma1 (tail (Fin . f)))) }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (\ k => (tail (Fin . f)) k)) )
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (\ k => (Fin . f) (FS k)))   )
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (\ k => Fin (f (FS k))))     )
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (\ k => Fin ((tail f) k)))   )
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (\ k => (Fin . (tail f)) k)) )
>   ={ isoCong {P = \ X => Either (Fin (f FZ)) (DPair (Fin n) X)} (lambdaLemma1 (Fin . (tail f))) }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (Fin . (tail f)))            )
>   QED
```
with
``> import Data.Fin
> import Data.Vect
> import Control.Isomorphism

> namespace Troublemaker
>   k : Fin 2
>   k = FS FZ

> postulate lambdaLemma1 : {A, B : Type} -> (f : A -> B) -> (\ a => f a) = f

> isoCong : {A : Type} -> {x : A} -> {y : A} -> {P : A -> Type} -> x = y -> Iso (P x) (P y)
> isoCong {x} {P} prf = replace {P = \ z => Iso (P x) (P z)} prf isoRefl 

> tail : {A : Type} -> (Fin (S n) -> A) -> (Fin n -> A)
> tail f k = f (FS k)

> sigmaEitherLemma : {n : Nat} -> 
>                    {P : Fin (S n) -> Type} ->
>                    Iso (DPair (Fin (S n)) P) (Either (P FZ) (DPair (Fin n) (tail P)))

> sigmaFinEitherLemma : {n : Nat} -> {f : Fin (S n) -> Nat} ->
>                       Iso
>                       (DPair (Fin (S n)) (Fin . f))
>                       (Either (Fin (f FZ)) (DPair (Fin n) (Fin . (tail f))))
> sigmaFinEitherLemma {n} {f} =
>     ( DPair (Fin (S n)) (Fin . f)                                     )
>   ={ sigmaEitherLemma {n = n} {P = Fin . f} }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (tail (Fin . f)))            )
>   ={ isoCong {P = \ X => Either (Fin (f FZ)) (DPair (Fin n) X)} (sym (lambdaLemma1 (tail (Fin . f)))) }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (\ lala => (tail (Fin . f)) lala)) )
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (\ lala => (Fin . f) (FS lala)))   )
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (\ lala => Fin (f (FS lala))))     )
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (\ lala => Fin ((tail f) lala)))   )
>   ={ isoRefl }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (\ lala => (Fin . (tail f)) lala)) )
>   ={ isoCong {P = \ X => Either (Fin (f FZ)) (DPair (Fin n) X)} (lambdaLemma1 (Fin . (tail f))) }=
>     ( Either (Fin (f FZ)) (DPair (Fin n) (Fin . (tail f)))            )
>   QED`

```
makes the problem disappear. Best, Nicola
