### ISSUE TITLE
Haskell style guard syntax should fail, but doesn't

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris-dev#2162]
The following code should fail on | p x, but doesn't:

    findIndex' : (n: Nat) -> (a -> Bool) -> Vect n a -> Maybe (Fin n)
    findIndex' Z p [] = Nothing
    findIndex' (S n) p (x :: xs) | p x = Just $ (fromNat n)

It appears to just ignore the | p x, since it's not under a `with`.

**Comment by edwinb** [comment]
(Edited the initial issue description to remove the irrelevant line, which had a type error in it anyway)

**Comment by ahmadsalim** [comment]
It fails now.
