### ISSUE TITLE
%instance is not searched for implicit arguments

### ISSUE THREAD

**Issue by scshunt** [idris-lang/Idris-dev#2171]
Some playing on IRC led to this code, attempting to create an instance of `Show` for sigma types:

    showSigma : {P : a -> Type} -> {default %instance sx : Show a} -> {default %instance sp : {x : a} -> Show (P x)} -> Show (Sigma a P)
    showSigma = mkShow $ \(x ** p) => "(" ++ show x ++ " ** " ++ show p ++ ")"

It can then be used:

    show @{showSigma} $ the (n : Nat ** Vec n _) [1,2,3]

Explicitly specifying the instance is required, but that would be a separate issue. The issue here is the `default %instance` clauses in the definition of `showSigma`. Without them, this code stops working, which seems a bit silly since I've just gone and told the compiler to figure out which instance to use for me. The compiler should be able to infer that `%instance` is a valid potential argument in this case and make it so that the `default` clause is not needed.

**Comment by david-christiansen** [comment]
The implicit argument resolution mechanism will use unification, unless a default or auto modifier is provided. Type class resolution is much more complicated than unification, so we shouldn't expect unification to solve those arguments.
