### ISSUE TITLE
:doc should show totality status

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#2176]
`:doc` should show Idris's take on totality.

**Comment by GuglielmoS** [comment]
Hi, I would like to contribute to the project and I ended up modifying Idris/Docs.hs to show the totality status of a given function. However I don't know if what I obtained is the desired behaviour or not.
In particular I have a working version that shows the totality status for all functions except:
* data types and their related constructors
* type classes and their instance constructors and named instances

The following is an example of output:

```
Idris> :doc map
map : Functor f => (m : a -> b) -> f a -> f b
    The action of the functor on morphisms
    Totality:
        The function is Total
Idris> :doc divNat
divNat : Nat -> Nat -> Nat
    
    Totality:
        The function is not total as there are missing cases
```

Could this be considered correct? Is there a preferred way to show the totality status?
I tried to be as consistent as possible by printing totality in the same way as the REPL :totality command does, but if I'm missing something please let me know about it.

**Comment by david-christiansen** [comment]
This looks pretty good to me! I think that it might be better if there were a blank line between the docs and the totality status, and if the "Totality" header were either on the same line or removed completely, but that's minor stuff.

Thanks a ton!

**Comment by david-christiansen** [comment]
If you like working on this kind of thing, #2241 might also be a good place to use the knowledge you've gotten. If you'd rather move on to other areas, let me know and I'll point you at some useful, accessible bits.

Thanks again!

**Comment by GuglielmoS** [comment]
Thanks I'll give a look at it in the next weeks!

**Comment by david-christiansen** [comment]
Thank you!
