### ISSUE TITLE
Can prove _|_ with mutually defined data & 'impossible'

### ISSUE THREAD

**Issue by BlackBrane** [idris-lang/Idris-dev#2182]
The following code is accepted by idris.

```idris
module BadEvenOdd

%default total

-- a defective even-odd definition allows me to prove bottom

mutual
  data Even : Nat -> Type where
    ZeroEven : Even Z
    MkEven : Odd n -> Even (S n)
    MkBad  : Even n -> Even (S n)

  data Odd : Nat -> Type where
    MkOdd : Even n -> Odd (S n)

evenNotS : Even n -> Not (Even (S n))
evenNotS MkEven ZeroEven impossible

bad : Void
bad = evenNotS ZeroEven $ MkBad ZeroEven
```

**Comment by treeowl** [comment]
This seems likely to be related to #2129. If the type signature for `evenNotS` is changed to

```idris
evenNotS : Even n -> Even (S n) -> Void
```
then `evenNotS` fails the totality check as it should.

**Comment by treeowl** [comment]
The apparent fragility of the `impossible` mechanism makes me wonder whether it might be possible to remove it from the *core* language altogether. Is it always possible to desugar it to use a postulated `exFalso`?

**Comment by Melvar** [comment]
`impossible` marks that the *LHS* of a clause is ill-typed. You can not replace such a clause with one with a RHS, because the LHS will just fail to typecheck.

**Comment by treeowl** [comment]
@Melvar, Failing to typecheck is not, I think, sufficient. To avoid being tricked, I think we need not only to fail to find a proof that it is well-typed, but rather to find ar proof that it is ill-typed. Once we have such, I would *think* we should be able to express it with an absurdity on the right.

**Comment by Melvar** [comment]
@treeowl Failing to typecheck is sufficient to block use of the clause with an actual RHS, and is implied by the stronger condition on use of impossible in non-bugged cases. Or maybe you mean changing the clause structure in the process?

**Comment by treeowl** [comment]
@Melvar, I didn't have a terribly clear plan/understanding, but yes, I was wondering if it would be possible to rearrange the structure in such a fashion that the weirdness could be shifted to the right and thus confined. It sounds like the answer is probably no.

**Comment by ahmadsalim** [comment]
This doesn't even seem to require the `mutual` datatypes, the following also passes:

```
data Even : Nat -> Type where
    ZeroEven : Even Z
    MkEven : Even n -> Even (S (S n))
    MkBad  : Even n -> Even (S n)

evenNotS : Even n -> Not (Even (S n))
evenNotS (MkEven o) ZeroEven impossible

bad : Void
bad = evenNotS ZeroEven $ MkBad ZeroEven
```

**Comment by ahmadsalim** [comment]
I would guess this is an issue with the Idris coverage checker.

**Comment by david-christiansen** [comment]
This is still an issue in 0.9.18.

**Comment by Melvar** [comment]
This is still an issue in 0.9.19.

**Comment by edwinb** [comment]
I could have sworn I'd fixed and closed this earlier today.... but none of these pass the totality checker in master, so I'll close.

**Comment by Melvar** [comment]
Huh, I guess I should have pulled before reconfirming. It is indeed fixed in master.
