### ISSUE TITLE
Using a where clause seems to confuse the termination checker

### ISSUE THREAD

**Issue by treeowl** [idris-lang/Idris-dev#2183]
I don't know if this is a bug or just a misunderstanding on my part. I'm trying to translate some well-founded recursion basics from Agda. With these definitions:

```idris
Rel : Type -> Type
Rel T = T -> T -> Type

data Acc : Rel a -> a -> Type where
  MkAcc : ({y : a} -> y `r` x -> Acc r y) -> Acc r x
````
this works:

```idris
sparserAcc : (r1, r2 : Rel a) -> ((x,y:a) -> r1 x y -> r2 x y) -> Acc r2 p -> Acc r1 p
sparserAcc {a} {p} r1 r2 f (MkAcc g) = MkAcc (\r1zp => sparserAcc r1 r2 f (g (f _ p r1zp)))
```

But this (which I personally find easier to understand) isn't accepted as total:

```idris
sparserAcc : (r1, r2 : Rel a) -> ((x,y:a) -> r1 x y -> r2 x y) -> Acc r2 p -> Acc r1 p
sparserAcc {a} {p} r1 r2 f (MkAcc g) = blah
  where
    blah : {z : a} -> r1 z p -> Acc r1 z
    blah {z} r1zp = sparserAcc {a} {p=z} r1 r2 f (g (f z p r1zp))
```

**Comment by david-christiansen** [comment]
It's important to note that lambdas and top-level defined functions are quite different things in Idris. Top-level functions can pattern-match and be recursive, while lambdas cannot. They are treated very differently by the totality checker, and they mean very different things in the core language. So it's not reasonable to expect that you can always lift a lambda to a definition.

Here, you've gone from one recursive function to two mutually recursive functions. That is more difficult.

To get some insight into what's going on, try turning on logging at level 3 or 5 and see what happens.

**Comment by treeowl** [comment]
I would, perhaps naively, have expected the type checker to be able to
recognize "lambda-like" functions and turn them into lambdas. But I can
certainly imagine that there could be compilation machinery complicating
that. It's much easier for me, at least, to understand what a local
function does (or needs to do) if I can give it a type signature; Lambdas
are rather opaque in this regard.

**Comment by edwinb** [comment]
The totality checker is paranoid about partially applied things and isn't going to be happy about this. I imagine the Agda checker does a better job, but their checker was written by a specialist in that area which I am very much not. The Idris totality checker tries to be as simple and sound as possible.

I'm closing this as expected behaviour, but if someone does want to write a better totality checker that is always something I'd be open to.
