### ISSUE TITLE
Non-exhaustive patterns in function defaultCase in JS backend

### ISSUE THREAD

**Issue by enolan** [idris-lang/Idris-dev#2184]
If I install the [IdrisScript](https://github.com/idris-hackers/IdrisScript) library and then try to build the following program with --codegen javascript,

```
import IdrisScript

main : JS_IO ()
main = jscall "alert(\"HI!\")" (JS_IO ())
```

I get the following error:

```
enolan at enolan-desktop in ~/junk  
$ idris --codegen javascript -p idrisscript -o alert.js alert.idr 
idris-javascript: src/IRTS/CodegenJavaScript.hs:423:5-45: Non-exhaustive patterns in function defaultCase

FAILURE: "idris-javascript" ["./alert.ibc","-o","alert.js"]
```

The relevant lines are [here](https://github.com/idris-lang/Idris-dev/blob/master/src/IRTS/CodegenJavaScript.hs#L425-L426). (It's moved since April.)

**Comment by melted** [comment]
Can't reproduce on Idris 1.1.1
