### ISSUE TITLE
Can prove Void by problem with case expression in type signature

### ISSUE THREAD

**Issue by gonzaw** [idris-lang/Idris-dev#2196]
Version: Idris 0.9.17.1

Idris allows me to implement something like the following:

    getNo : (res : Dec p) -> case res of { Yes _ => () ; No _ => p }
    getNo (Yes prf) = ()
    getNo (No contra) = contra

I can prove Void with such a definition, like this:

    voidProof : Void
    voidProof = noEmptyElem (getNo (isElem 1 []))

In the case expression of "getNo", Idris allows the expression "No _ => p" when it shouldn't

**Comment by david-christiansen** [comment]
I'd say that, even worse, Idris is accepting the definition of `getNo`. The type of `contra` should be `p -> Void`, not `p`.

You can make an even easier hole in the logic by constructing a `Dec Void` directly:

```
getNo : (res : Dec p) -> case res of { Yes _ => () ; No _ => p }
getNo (Yes prf)   = ()
getNo (No contra) = contra

oops : Void
oops = getNo (No id)
```

Even worse, this works in the latest Git version.

**Comment by david-christiansen** [comment]
I'm out of time to look at this today, but here's the results of some poking, so I don't forget. The following program is not accepted:
```
module Test


getNo : (res : Dec p) -> case res of { Yes _ => () ; No _ => p }
getNo {p} (Yes prf)   = "foo"
getNo {p} (No contra) = "I like to eat sandwiches"
```
It claims a type mismatch between String (the type of `"foo"`) and the expected type `()`. So far so good.

The following program _is_ accepted:
```
getNo : (res : Dec p) -> case res of { Yes _ => () ; No _ => p }
getNo {p} (Yes prf)   = ()
getNo {p} (No contra) = "I like to eat sandwiches"

oops : Void
oops = getNo (No id)
```
So is the following:
```
getNo : (res : Dec p) -> case res of { Yes _ => () ; No _ => p }
getNo {p} (No contra) = "I like to eat sandwiches"
getNo {p} (Yes prf)   = ()


oops : Void
oops = getNo (No id)
```

When I manually lift the `case` expression to the top level, everything seems to work as it should.

My guess is that the case block in the type expression is being elaborated incorrectly - probably, it's some kind of scope issue with de Bruijn indices, if I had to bet.

Unfortunately, abstracting over `p` in the case block and applying it yields a universe inconsistency:
```
getNo : (res : Dec p) -> (\p' => case res of { Yes _ => () ; No _ => p' }) p
getNo {p} (Yes prf)   = ()
getNo {p} (No contra) = "I like to eat sandwiches"

Universe inconsistency.
Working on: k3
Old domain: Domain 0 10
New domain: Domain 0 (-1)
Involved constraints: 
	ConstraintFC {uconstraint = k3 < 0, ufc = Test.idr:7:7}
```

**Comment by treeowl** [comment]
I can't help wondering if this is related to the scope errors I've been reporting. One thing they *seem* to have in common is that (as far as I can tell) the problems come up when the last arrow target is an expression that must be reduced.

**Comment by edwinb** [comment]
Nothing to do with any of this, it turns out. It's the type inference proof search machinery that breaks this.

When there's a metavariable in a type, Idris assumes you want to solve that metavariable by proof search and allows unification problems in the body to help solve that metavariable later. However, in this case, the metavariable is solved by a case (since that's how it's elaborated).

The end result is a type error which goes uncaught because the assumption is broken and the resulting clause is never fed to the type checker.
