### ISSUE TITLE
idris.exe: Data.Binary.Get.runGet at position 0: demandInput: not enough bytes

### ISSUE THREAD

**Issue by Heather** [idris-lang/Idris-dev#2197]
Just rebuild `master` Idris on windows and that's what I get:

``` shell
F:\P\thridparty\M\idris-xml>make
idris  --build xml.ipkg
Type checking .\XML\DOM\Model.idr
Type checking .\XML\DOM\Eq.idr
Type checking .\XML\DOM\Utils.idr
Type checking .\XML\DOM\Show.idr
Type checking .\XML\DOM\API.idr
Type checking .\XML\DOM\ShowXML.idr
Type checking .\XML\DOM.idr
Type checking .\XML\DOM\Eff.idr
idris.exe: Data.Binary.Get.runGet at position 0: demandInput: not enough bytes
make: *** [lib] Error 1
```

**Comment by david-christiansen** [comment]
Try recursively finding and deleting .ibc files. There have been some
format changes recently.

**Comment by Heather** [comment]
@david-christiansen aha... thanks, rebuilding another package (lightyear) helped

**Comment by david-christiansen** [comment]
Glad to hear it!

**Comment by melted** [comment]
This is from my expansion of the version field to 16 bits, as it was only present with a zip archive and the small field for a few days (the ones that aren't zip archives are detected) I thought a cryptic error message was acceptable.

----- Ursprungligt meddelande -----
Från: "David Christiansen" <notifications@github.com>
Skickat: ‎2015-‎04-‎27 10:17
Till: "idris-lang/Idris-dev" <Idris-dev@noreply.github.com>
Ämne: Re: [Idris-dev] idris.exe: Data.Binary.Get.runGet at position 0:demandInput: not enough bytes (#2197)

Glad to hear it!
