### ISSUE TITLE
Unqualified `Raw` causes coverage failure in elaborator

### ISSUE THREAD

**Issue by ziman** [idris-lang/Idris-dev#2199]
Try loading this `crashing.idr`:
```idris
x : Raw Int
x = MkRaw 0
```
(Just the above two lines in a file.)

It turns out that the case expression in `Idris/Elab/Utils.hs:176` does not cover the case when lookup returns more than one result. Unfortunately, `Raw` exists both unqualified and as `Language.Reflection.Raw`.

The result is that you basically cannot use the non-namespaced token `Raw` in any Idris program and there is probably no way to refer to the unqualified `Raw` from `Prelude.IO`. (`%hide Language.Reflection.Raw` does not change anything.)

There are several options; we could take this either as a deeper question
> Do we really need unqualified builtins? There's no way to refer to them once someone in some namespace defines something with the same name, even if the coverage condition is solved. Also, with nice names such as `Raw`, clashes can happen quite frequently.

or find a way to explicitly refer to unqualified names; or just hack around it.

**Comment by david-christiansen** [comment]
I think we should qualify all the built-in names under either `Builtins` or `Idris`.

**Comment by ahmadsalim** [comment]
It seems to type check fine now.
