### ISSUE TITLE
%runElab in a default value can’t use previous args

### ISSUE THREAD

**Issue by Melvar** [idris-lang/Idris-dev#2209]
When I use an Elab script as a default value, and within the Elab script use one of the previous arguments, the name is not found:
```idris
getNamedVar : (nm : TTName) -> {default (%runElab (do fill (Var nm); solve)) x : t} -> t
getNamedVar nm {x} = x
```
```
*InterpolateElab> \x => getNamedVar "x"
When elaborating an application of constructor Language.Reflection.Var:
        No such variable nm
```
In something simple, like
```idris
dbl : (n : Nat) -> {default n m : Nat} -> Nat
dbl n {m} = n + m
```
the problem does not occur; `n` can be used perfectly well and calling this function gives the expected results.

I believe https://github.com/idris-lang/Idris-dev/pull/1031 implemented this functionality originally, but I have no idea how it actually accomplished this, so I don’t know where to look for the problem.

**Comment by david-christiansen** [comment]
In the latest commit in the elab reflection branch:
```
λΠ> \x => getNamedVar `{plus}
(input):0:0:Incomplete term \x =>
                              getNamedVar (NS (UN "plus") ["Nat", "Prelude"])
λΠ> getNamedVar `{plus}
plus : Nat -> Nat -> Nat
λΠ> \x => getNamedVar (UN "x")
(input):0:0:Incomplete term \x => getNamedVar {t = ([__])} (UN "x")
λΠ> \x : Type => getNamedVar (UN "x")
\x => x : Type -> Type
λΠ> \x : Nat -> Nat => getNamedVar (UN "x")
\x => x : (Nat -> Nat) -> Nat -> Nat
```

Looks right to me!

**Comment by Melvar** [comment]
That does indeed look right.
