### ISSUE TITLE
Totality checker fails for function with effects

### ISSUE THREAD

**Issue by icasperzen** [idris-lang/Idris-dev#2231]
Trying to compile the following code gives an error: `EffMissingCases.bar is not total as there are missing cases`. I'm pretty sure `bar` is total. (Though, I am still very new to effects.)

```idris
module EffMissingCases
import Effects
import Effect.StdIO
%default total

data OneConstructor : Type where
  TheOneAndOnly : OneConstructor

foo : OneConstructor -> ()
foo TheOneAndOnly = ?foo_rhs

bar : OneConstructor -> { [STDIO] } Eff ()
bar TheOneAndOnly = ?bar_rhs
```

I also tested `RND` and `State Int` and had the same problem.

**Comment by JanBessai** [comment]
You inserted a hole `?bar_rhs` in the right hand side of bar. Can you post the proof associated with that hole, please?

**Comment by edwinb** [comment]
If anyone has a moment to look at this, here's a hint - it appears to be about scoped implicits. The following code also exhibits the problem:

    FooTy : Type
    FooTy = {i : Int} -> ()
  
    foo : OneConstructor -> FooTy
    foo TheOneAndOnly = ?foo_rhs

**Comment by icasperzen** [comment]
@JanBessai 
This was just the smallest example I could find that exhibited the problem. I didn't think the RHS would matter, but it could be `()` and `return ()`.

Also, my choice of unit was just to simplify the example. `s/()/Integer/` would give the same problem.
I would love to take a look at it myself, but I'm certainly not capable.

**Comment by mietek** [comment]
Another instance of what appears to be an issue with the totality checker being confused by scoped implicits:

```idris
module IScott

%default total


BoolS : Type
BoolS = {A : Type} -> A -> A -> A

unBoolS : {A : Type} -> A -> A -> BoolS -> A
unBoolS a a' s = s a a'

trueS : BoolS
trueS = \a, a' => a

falseS : BoolS
falseS = \a, a' => a'

fromBoolS : BoolS -> Bool
fromBoolS s = unBoolS True False s

toBoolS : Bool -> BoolS
toBoolS True  = trueS
toBoolS False = falseS
```
```
Type checking ./IScott.idr
IScott.idr:22:1:
IScott.toBoolS is not total as there are missing cases
```
