### ISSUE TITLE
Idris overconstrains its dependencies

### ISSUE THREAD

**Issue by feuerbach** [idris-lang/Idris-dev#2235]
The latest idris from hackage (0.9.17.1) is impossible to install with current [stackage lts](http://www.stackage.org/snapshot/lts-2.7) because of the upper bounds on such packages as annotated-wl-pprint, blaze-html, blaze-markup, utf8-string.

These version constraints are actively harmful, because they force cabal to pick and try to build an old version of idris, and the build results in a puzzling type error (#1866).

To be clear, it's not just a problem with stackage; simple `cabal install idris` will try to build an old version and result in a compile error.

**Comment by edwinb** [comment]
We do this because in practice we get more trouble by underconstraining
than overconstraining. I have no idea what the solution is other than
releasing binaries or using some other distribution mechanism.

**Comment by feuerbach** [comment]
As a fellow Haskell developer, I try to support the latest versions of my dependencies. I also try to keep the number of dependencies to a reasonable minimum, which certainly helps here.

**Comment by jfdm** [comment]
@feuerbach we are already aware of the current problems trying to built against LTS Haskell. See #2135 for more information about that, however, I haven't had the time recently to further act upon it. I think it would be nice to be able to build against LTS Haskell but we have to wait for it to be stable for our use.

**Comment by edwinb** [comment]
Our real problem seems to be the number of dependencies that are pulled in by the things we actually use. While it would be nice to support the latest versions of things, it's not easy to keep up especially when things change their APIs (this has been a problem in the past and part of the reason we constrain so aggresively now).

We should make sure idris compiles properly on cabal/stackage but it's annoying because it feels like we're constantly battling against it whichever approach to constraints we take. Anyone able to take a look at this?

**Comment by feuerbach** [comment]
Correction: it appears that `cabal install idris-0.9.17.1` in a fresh sandbox without stackage compiles well, which makes this issue less severe than I initially thought.

It is still annoying that I can't build idris in a shared stackage sandbox.

**Comment by LeifW** [comment]
We do want to support the latest versions of other libraries as much as possible when they come out, but only after vetting them first to ensure this still builds against them. If we don't have conservative upper bounds `cabal install idris` will constantly be broken as people release new versions of libs with breaking changes.

**Comment by LeifW** [comment]
The upper bounds of blaze-html, blaze-markup and utf8-string were raised in #2421. Idris now builds with stackage nightly. Can this be closed?

**Comment by juhp** [comment]
idris still depends on utf8-string <= 1 at least, whereas current Stackage has utf8-string-1.0.1.1.
