### ISSUE TITLE
Allow Idris source files to contain a shebang line

### ISSUE THREAD

**Issue by melted** [idris-lang/Idris-dev#2247]
So idris source files can be made executable on unixy systems by putting `#!/bin/env runidris` on the first line.

This would also require a script/program `runidris` that works like `runhaskell`

**Comment by alexchandel** [comment]
Why was #2289 closed?

**Comment by ahmadsalim** [comment]
#2289 was closed because Idris is not an interpreted language and people thought it wouldn't make sense to add shebang support. I will close this issue as well for the same reason.

**Comment by alexchandel** [comment]
@ahmadsalim But yet, the idris compiler supports executing Idris files on the fly with `idris --execute`. If that exists, then it makes sense to support its invocation via `#!/bin/idris --execute`.

**Comment by ahmadsalim** [comment]
@david-christiansen Should I reopen this? I think you were the one who argued against shebangs last time.

**Comment by melted** [comment]
Has come ip again.

**Comment by david-christiansen** [comment]
Hmm, I was pretty sure I'd argued in favor of them... No objections here.
