### ISSUE TITLE
Odd universe inconsistency

### ISSUE THREAD

**Issue by ghost** [idris-lang/Idris-dev#2254]
```idris
module Cat

class Semigroupoid where
  constructor MkSemigroupoid
  Obj : Type
  Arr : Obj -> Obj -> Type
  comp : Arr b c -> Arr a b -> Arr a c

set : Semigroupoid
set = MkSemigroupoid Type (\a, b => a -> b) (\_, _, _ => (.))

op : Semigroupoid => Semigroupoid
op = MkSemigroupoid Obj (flip Arr) (\_, _, _ => flip comp)

op' : Semigroupoid -> Semigroupoid
op' a = op @{a}

opSet : Semigroupoid
opSet = op' set

--everything above works, but the following doesn't

badOpSet : Semigroupoid
badOpSet = op @{set}
```

 cat.idr line 24 col 0:
     Universe inconsistency.
             Working on: c8
             Old domain: (8,8)
             New domain: (8,7)
             Involved constraints: 
                     ConstraintFC {uconstraint = c8 <= g8, ufc = cat.idr:24:1}
                     ConstraintFC {uconstraint = b8 < c8, ufc = cat.idr:24:1}
                     ConstraintFC {uconstraint = c8 < d8, ufc = cat.idr:24:1}
                     ConstraintFC {uconstraint = c8 <= g8, ufc = cat.idr:24:1}

**Comment by AaronMV** [comment]
@ozgurakgun

**Comment by ahmadsalim** [comment]
I seem to not have gotten any inconsistency anymore.
