### ISSUE TITLE
Rename Semigroup and Monoid

### ISSUE THREAD

**Issue by treeowl** [idris-lang/Idris-dev#2263]
The current `Semigroup` class actually represents something more like a magma. The current `Monoid` class represents ... I guess a pointed magma. The names are reasonable in Haskell, where class laws are purely a social construct, but in Idris, I think such names should be reserved for subclasses that impose laws on the structures. That said, it seems most algebra in Agda and Coq is done with setoids. I think there's every reason to believe that this will be true in Idris as well, since non-trivial abstract data types are generally implemented using redundant representations. Therefore, even using the name `Magma` may be going too far.

**Comment by david-christiansen** [comment]
I don't think we should do this. Such a renaming may be more true to the mathematical theory, but it will make code more difficult to read for Haskellers, and imposing proof obligations makes it harder to get stuff done. I'd rather have a library with opt-in proof obligations for when you really want to do mathematics.

After all, the point of `Semigroup` in Idris is to stick stuff together in programs, not to write proofs about algebra.

You haven't actually proposed new names; but if you had, who would such a renaming benefit?

**Comment by treeowl** [comment]
Not everything we want to stick together is, or is even supposed to be, a
semigroup. The particular obvious case I've been playing with is a type of
expressions using a given operator, where expressions associated
differently should be considered different, even if they represent
equivalent underlying values. What led me to dislike the current naming
scheme was considering

class (Semigroup a, Setoid a) => Magma a ....

which just feels terribly backwards, since every mathematical semigroup is
already a magma. The Semigroup name makes sense in the Haskellverse,
because an extra Semigroup class over a Magma class would offer absolutely
nothing but more boilerplate when writing instances. I think Idris is just
fundamentally different in that regard.

**Comment by david-christiansen** [comment]
Right, things we want to stick together *associatively* are Semigroup in Idris. But the precise meaning of "associative" should perhaps not necessarily be WRT propositional equality (e.g. there might be some kind of implicit quotient, such as equality modulo rendering). That doesn't mean we should force people to prove it - it's also useful to just say "hey, this is associative".

**Comment by david-christiansen** [comment]
That said - I encourage you to put together a coherent library of all these structures, and we can take a look at it and see if it is something that would make writing programs easier.

**Comment by treeowl** [comment]
@david-christiansen, yeah, I think I see the tension—for unverified versions, the Haskell-style approach makes sense for the same reasons, but that approach then interacts a bit poorly with the verified approach. On the other hand, would it really be such a burden to require users to postulate the equivalences they don't want to prove? Maybe, but I'm not convinced yet. I guess we'll have to wait and see.

**Comment by zraffer** [comment]
If I were writing my own library (I understand it's not the case), I would (re)name current haskell-like `Monoid` to be `Monoid0`, `VerifiedMonoid` to be `Monoid1`, and `MonoidalCategory` (if we would have it) to be `Monoid2`. It seems the most simple and straight solution. There are some categorical reasons for such names: there are its own kind of structure at each dimension.

**Comment by david-christiansen** [comment]
I'm going to go ahead and close this, because we're not planning on doing this renaming.
