### ISSUE TITLE
Unexpected error when importing System and Effect.System

### ISSUE THREAD

**Issue by Heather** [idris-lang/Idris-dev#2271]
``` idris
module Main
 
import Prelude.Monad

import System
import Effect.System
 
main : IO ()
main = do
    args <- System.getArgs
    putStrLn (concat args)
```

Error message:
``` shell
When elaborating an application of function Prelude.Monad.>>=:
        No such variable System.getArgs
```

It was working fine about month or two ago, I will be glad if that will work without error or at least error should say more clear that I should not import both modules at once...

If main module imports module `A` and only imports `System`
And module `A` imports `Effect.System`
there is still being this error

and in addition errors alike:
```idris
Can't resolve type class Handler System                                  
(IO' (MkFFI C_Types String String))
```

**Comment by david-christiansen** [comment]
It should be allowed to import both at once. The code should either work or throw an error that it couldn't disambiguate the name.

**Comment by david-christiansen** [comment]
Looks like this was my fault. Sorry! And thanks @edwinb!

**Comment by Heather** [comment]
Now I'm getting

``` idris
When elaborating an application of function Prelude.Monad.>>=:
        Can't unify
                EffM m
                     (List String)
                     [SYSTEM]
                     (\v => [SYSTEM]) (Type of getArgs m)
        with
                IO' (MkFFI C_Types String String) a (Expected type)
```

seems like wrong getArgs is taken
