### ISSUE TITLE
Mysterious "No such variable with block" error

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2276]
Both

`https://github.com/nicolabotta/SeqDecProbs/blob/b927ffcce1fd1590cfe308f0a67167c173317319/VectOperations.lidr`

and

`https://github.com/nicolabotta/SeqDecProbs/blob/b927ffcce1fd1590cfe308f0a67167c173317319/SeqDecProbMonadicSmallTheoryExample2.lidr`

type check fine. But attempts at compiling the latter with

```
 idris -p contrib -p effects SeqDecProbMonadicSmallTheoryExample2.lidr -o example
```

yield

```
SeqDecProbMonadicSmallTheoryExample2.lidr:391:13:
No such variable with block in VectOperations.filterTag
```

The error seems to be triggered by the computation `vt` at line 397. Computing `vt` at the Idris prompt works fine. Maybe is something wrong with the compiler?

**Comment by ahmadsalim** [comment]
@nicolabotta 
Is this still a problem and would you please if possible produce a smaller version of the issue? Thanks!

**Comment by ahmadsalim** [comment]
I will close the issue since no new updated information was provided for a long time.
