### ISSUE TITLE
Incorrect use of seemingly-implicit arguments at applications

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#2279]
None of these should work:
```
λΠ> (+) {food=S Z} Z
1 : Nat
λΠ> (+) {food=S Z} {tofu=Z}
1 : Nat
λΠ> (+) (S Z) {tofu=Z}
1 : Nat
λΠ> (+) {tofu=Z}
\meth => meth : Nat -> Nat
```

**Comment by edwinb** [comment]
It seems to be discarding unknown implicits rather than reporting that it doesn't know what they are - this also affects the implementation of scoped implicits. Probably the thing to do is add an "Unknown Implicit" error for this.
