### ISSUE TITLE
Documentation on tactics is missing

### ISSUE THREAD

**Issue by suhr** [idris-lang/Idris-dev#2306]
The only documentation on tactics available is outdated http://eb.host.cs.st-andrews.ac.uk/Idris/theorems.html.

**Comment by edwinb** [comment]
There is a brief discussion of tactics at http://docs.idris-lang.org/en/latest/proofs/interactive.html#interactive-theorem-proving and a tutorial on theorem proving at http://docs.idris-lang.org/en/latest/proofs/index.html#proofs-index

**Comment by suhr** [comment]
This doesn't have the list of all tactics available, only intro-rewrite-trivial examples. It doesn't even mention `refine` tactics [used in prelude implementation](https://github.com/idris-lang/Idris-dev/blob/master/libs/prelude/Prelude/Nat.idr).
Tactics need much more attention in documentation.

**Comment by suhr** [comment]
The brief discussion is too brief, it doesn't even have the whole list of tactics available.

**Comment by edwinb** [comment]
I'm sorry you feel it's too brief, but it's not going to have the whole list of tactics available. We don't encourage using tactics, as the theorem proving documentation explains, and the system is likely to change.
