### ISSUE TITLE
idris-0.9.18 broken by text update

### ISSUE THREAD

**Issue by peti** [idris-lang/Idris-dev#2314]
Citing from http://hydra.cryp.to/build/884326/log/raw:

~~~~~~~~~~~~~
src/Idris/Core/Binary.hs:309:10:
    Duplicate instance declarations:
      instance Binary T.Text
        -- Defined at src/Idris/Core/Binary.hs:309:10
      instance Binary T.Text -- Defined in ‘Data.Text’
~~~~~~~~~~~~~~

**Comment by david-christiansen** [comment]
I just pushed a fix. This doesn't help the version on Hackage, but you should be able to build from Git now.

**Comment by peti** [comment]
Git doesn't help us in NixOS. We cannot distribute random, unsupported versions from the repository to our users.

**Comment by david-christiansen** [comment]
Then there's something you can do, in the meantime, while we sort things out: put an upper bound on text in the version you package for NixOS.

**Comment by peti** [comment]
It's not that simple, I'm afraid.

Anyway, I'll try pulling https://github.com/idris-lang/Idris-dev/commit/22c8cda08501a29f4042097bf863e602e0519f4a as a patch into the current release to make it build.

**Comment by david-christiansen** [comment]
Edwin has pushed 0.9.18.1 to Hackage which should solve this problem. Did it take care of it for you?

**Comment by peti** [comment]
Yes, we've updated to the new version a few minutes ago. Thank you for the new release!
