### ISSUE TITLE
Docs broken example

### ISSUE THREAD

**Issue by NCrashed** [idris-lang/Idris-dev#2316]
Examples are same, but should not. http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html

![screenshot from 2015-05-24 00 15 05](https://cloud.githubusercontent.com/assets/2116167/7785802/66452c9a-01aa-11e5-9bb5-9e221d40a60c.png)

**Comment by NCrashed** [comment]
It's my eyes are broken :(

**Comment by joneshf** [comment]
Maybe there should be an explanation about what is different, and why it fails so that it's easier to understand WHY it's broken, not just that it is broken.

**Comment by NCrashed** [comment]
> Maybe there should be an explanation about what is different, and why it fails so that it's easier to understand WHY it's broken, not just that it is broken.

This would help, one symbol difference is hard to find to.
