### ISSUE TITLE
Cabal constraint solving hits the backjump limit

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2321]
No problems with 0.9.18-git:db84bf8 on Debian stable (3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux) but attempts at installing the latest commit fail with
```
nicola@cirrus:~/src/Idris-dev-5f33e4a51a68339fcb813f5217c5f85c783afa7b$ make
cabal install 
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: idris-0.9.18.1 (user goal)
trying: unordered-containers-0.2.5.0/installed-11c... (dependency of
idris-0.9.18.1)
next goal: hashable (dependency of
unordered-containers-0.2.5.0/installed-11c...)
rejecting: hashable-1.2.1.0/installed-7e8... (conflict: hashable =>
text==0.11.3.1/installed-e38..., idris => text>=1.2.1.0 && <1.3)
rejecting: hashable-1.2.1.0/installed-e5c..., 1.2.3.2, 1.2.3.1, 1.2.3.0,
1.2.2.0, 1.2.1.0, 1.2.0.10, 1.2.0.9, 1.2.0.8, 1.2.0.7, 1.2.0.6, 1.2.0.5,
1.2.0.4, 1.2.0.3, 1.2.0.2, 1.2.0.1, 1.2.0.0, 1.1.2.5, 1.1.2.4, 1.1.2.3,
1.1.2.2, 1.1.2.1, 1.1.2.0, 1.1.1.0, 1.1.0.0, 1.0.1.1, 1.0.1.0, 1.0.0
(conflict: unordered-containers => hashable==1.2.1.0/installed-7e8...)
Backjump limit reached (change with --max-backjumps).
Makefile:11: recipe for target 'install' failed
make: *** [install] Error 1
nicola@cirrus:~/src/Idris-dev-5f33e4a51a68339fcb813f5217c5f85c783afa7b$
```

**Comment by melted** [comment]
Looks like we need to do something for this more than the band aid for Travis. We discussed it on IRC last night and tightening some dependency bounds may help cabal solve the constraints with less work.

Temporarily, while that is fixed, adding a --max-backjumps=-1 to the cabal install command line will help.

**Comment by nicolabotta** [comment]
Installation with --max-backjumps=-1works, thanks! Still, resolving dependencies and installation take about one hour on a Thinkpad X230 at 1.2GHz. I am not closing the issue but feel free to do so if you think this is appropriate. Best, Nicola

**Comment by melted** [comment]
Of course it shouldn't be closed, it's valid and important. I renamed it to reflect the bug.
