### ISSUE TITLE
Can't disambiguate name: Prelude.Show, Prelude.Show.Show

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2325]
The following program
```
> -- import Data.Vect

> data Action = Do | Undo

> instance Show Action where
>   show Do = "Do"
>   show Undo = "Undo"
```
type checks fine. But uncommenting the first line yields
```
- + Errors (1)
 `-- show.lidr line 5 col 9:
     Can't disambiguate name: Prelude.Show, Prelude.Show.Show
```
which is not the  expected behavior, I think.

**Comment by edwinb** [comment]
I think this is related to the changes to the Show type class. You
should find that cleaning out the libraries and rebuilding sorts this out.

This suggests something is wrong with the dependency chasing (I had a
similar issue) but I haven't found a way to reproduce it so I'm a bit
stuck for now.

**Comment by nicolabotta** [comment]
Right, `make relib` solves the problem. Thanks, I am closing the issue. Best, Nicola
