### ISSUE TITLE
Improve Logging Output, and document logging process.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#2334]
I have been trying to debug a memory explosion that occurs when using Idris. The logging output makes it hard to determine at what stage of the compilation process that the explosion is occurring. Logging level 1, provides too much detail. As part of PR #2332 I have added details of the current compilation and logging process, documenting (roughly) what is being logged at each level. However, I think we need to rethink what is actually being logged at these levels, and move things around the levels to make it easier to diagnose problems.

**Comment by jfdm** [comment]
Just to add to this comment, Logging Level 0 should be kept, and Logging Level 1 should *just* detail the stages of the compilation process. Levels above this can introduce more information as necessary.

**Comment by jfdm** [comment]
I have just made PR #2335 that reports where in the compilation process we are at level 1 and everything that else that was at level 1 shunted to level 2. Once #2335 is accepted this issue can be closed.

**Comment by ahmadsalim** [comment]
@jfdm What is the status on this, I see that PR #2856 did something to logging as well. Can this be closed?

**Comment by jfdm** [comment]
Oh, i've completely forgotten about this...

This shouldn't be closed, I still think an adjustment of the logging levels needs to be done so output is consistently more detailed at each level. I do not think I change the levels in #2856.

**Comment by jfdm** [comment]
I shall take a look some point soon.

**Comment by ahmadsalim** [comment]
OK, thanks for the response :)

**Comment by jfdm** [comment]
I think PR #3551 addresses my issue sufficiently here. I still think the logging information, levels, and categories need tweaking, but that can come later.

**Comment by jfdm** [comment]
I think this issue can now be closed.
