### ISSUE TITLE
type search maybe showing non-applicable results?

### ISSUE THREAD

**Issue by LeifW** [idris-lang/Idris-dev#2341]
`:search List Char -> String` gives me cast, concat, show, and showArg.
`cocat`'s type sig is `Foldable t => Monoid a => t a -> a`
While List is Foldable, there's no Monoid instance for Char. Also, `t a -> a` cannot be made to equal `List Char -> String`, because `Char` does not equal `String`.

**Comment by david-christiansen** [comment]
This is funny - especially because `pack : Foldabe t -> t Char -> String` doesn't show up!

**Comment by bmsherman** [comment]
Good catch! Looks like there's a couple of bugs - I'll look into them. Feel free to assign this issue to me.

**Comment by ahmadsalim** [comment]
This seems to not give mentioned results any more, I get the following now:

```idris
= PE_pack_16311912 : List Char -> String


< Prelude.Strings.pack : Foldable t => t Char -> String
Turns a Foldable of characters into a string.

< Prelude.Cast.cast : Cast from to => from -> to
Perform a cast operation.

< Prelude.Show.show : Show ty => ty -> String
Convert a value to its String representation.

< Prelude.Show.showArg : Show a => a -> String
A helper for the common case of showing a non-infix constructor with at least one argument, for use with showCon.
```
