### ISSUE TITLE
In tutorial adding to $PATH "~/.cabal/bin" should be mentioned earlier

### ISSUE THREAD

**Issue by ozanerdem** [idris-lang/Idris-dev#2356]
In the "Getting Started" section of the tutorial (under docs/tutorial/starting.rst), installing Idris using cabal includes only these instructions:

`cabal update; cabal install idris`

However, to the inexperienced reader the location of the idris binary is unknown, so the first example which is:

    $ idris hello.idr -o hello
    $ ./hello
    Hello world

does not work right away. The next paragraph mentions `$PATH`, but I believe this is a bit too late. I'm sure many people would quit early (or defer their interest in Idris) after being frustrated after an `idris not found` error. 

What do you think about mentioning `$PATH` just after the installation instructions?

**Comment by LiamGoodacre** [comment]
:+1:

**Comment by jfdm** [comment]
Thank you for your comments. One of the problems being close to the material is that we sometimes cannot see how those new to the project will interpret things. If you think the tutorial could be improved (or other parts of the project) we always welcome PRs.

**Comment by paulkoerbitz** [comment]
@jfdm @david-christiansen This issue should probably be closed(?)
