### ISSUE TITLE
Semicolon syntax

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2357]
The program
```
> module Semicolon
> lala : Nat -> Nat
> lala n = m where
>   m : Nat;; m = Z
```
type checks fine but
```
> module Semicolon
> lala : Nat -> Nat
> lala n = m where
>   m : Nat; m = Z
```
fails to type check:
```
- + Errors (1)
 `-- ./semicolons.lidr line 4 col 11:
      error: not
         a terminator, expected: ";",
         "in", end of input
       m : Nat; m = Z
```
I seem to remeber this is not the expected behavior and had been corrected. If this is the case, this is regression in 0.9.18.1-git:84bca25.

**Comment by david-christiansen** [comment]
Is this a duplicate of #1471?

**Comment by nicolabotta** [comment]
I'm pretty sure it is! I somehow could not remember/find #1471. I am closing this issue since #1471 is open. Best, Nicola
