### ISSUE TITLE
"Nothing to fill in" error in proofs of declared-only functions

### ISSUE THREAD

**Issue by Yurry** [idris-lang/Idris-dev#2360]
(Idris 0.9.18, Windows x64 binaries)

When the function has only the type declaration and no definition, REPL states its name in as a metavariable. Trying to prove them interactively gives "Declarations not solvable using prover" error. 
When the proof is written manually, sometimes the compiler gives the internal error:
```idris
||| Exercise: 1 star (snd_fst_is_swap)
snd_fst_is_swap : (p : (a, b)) -> (snd p, fst p) = swap_pair p
--snd_fst_is_swap = ?sfis

Lists.snd_fst_is_swap = proof
  intros
  case p
  intros
  compute
  trivial
```
```
When elaborating right hand side of snd_fst_is_swap:
INTERNAL ERROR: Nothing to fill in.
This is probably a bug, or a missing error message.
```
When the metavariable is explicitly defined (see the commented line), everything is fine. I'm not sure it this _should_ work either. However, sometimes it still works.

**Comment by david-christiansen** [comment]
Defining the explicit metavariable sets up various things that cause the proof script to work properly. You shouldn't expect that it will work for top-level names in general, at least not without understanding more about how the internals of the compiler are put together. This is why the tactic prover was disabled for top-level declarations, actually.
