### ISSUE TITLE
idris --client fails on Windows

### ISSUE THREAD

**Issue by kevinsullivan** [idris-lang/Idris-dev#2369]
idris --client '2+2' fails on Windows. It returns " invalid command."

To confirm, either run "idris --client '2+2'" from the command line, or try to invoke any idris command from within vim using vim's idris mode. 

This occurs whether I issue the idris command on the command line, or by invoking idris commands from within vim using vim mode.

I note the string "[unix]" in the message output from within vim, which suggests a possible error formatting the command sent to the server?

**Comment by david-christiansen** [comment]
Are you already running an Idris REPL?  `--client` requires that there be a running Idris listening on a particular port.

**Comment by kevinsullivan** [comment]
Yes. Without a running REPL, I get an appropriate error message about no REPL found. With a running REPL, I get "invalid command" no matter what command I try to send.

**Comment by LeifW** [comment]
I have a windows computer at home and can test this out myself in a few
hours. Does a simple expression like idris --client 5 work any different?
One thing to ensure is that the expression passed to --client is quoted / a
single arg.

**Comment by melted** [comment]
This works for me, from both Powershell and from the msys2 shell

**Comment by melted** [comment]
I tested a little more, single quotes do in fact fail in cmd, but succeeds in ps and msys2. Double quotes work everywhere. It believe the result is because single quotes in cmd.exe aren't stripped, they mean nothing special in the old batch world. And idris considers the input a char literal, and 2+2 isn't a valid one. 

Which is verified by `idris --client '2'` outputting `'2' : char`

**Comment by melted** [comment]
The best solution is probably to make a PR for the vim package that uses double quotes for the command on windows.

**Comment by melted** [comment]
Closing as it's unrelated to Idris.
