### ISSUE TITLE
Idris fails to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by kevinsullivan** [idris-lang/Idris-dev#2372]
Following the simple instructions for building Idris on a clean Ubuntu 14.04 eventually yields failure. Some packages fail to build. I could provide details. A very capable student of mine tried a range of work-arounds and concluded that "something is really broken."

We care about this because we're hoping to use Idris (easy parts thereof) in an early intro CS course this fall. But right now (1) it fails to build on ubuntu, and (2) as filed here separately, idris --client just produces "invalid command" on windows, so the current system is not usable on either platform, as far as we can tell.

We're equipped to provide this feedback, and to provide additional information if asked, but we're not in a position at this point, unfortunately, to dive in to the implementation.

**Comment by david-christiansen** [comment]
Thanks for the report! Would you please post the output from Cabal when it fails to build?

I can try to figure out how to throw together binary packages for Ubuntu and Debian if it gets Idris used in a course and there's real interest. We have binaries for Windows, Mac OS, and a couple other Linuxen already, so it shouldn't be so terrible.

The `--client` option is really only necessary when using the vim mode - is that a hard requirement? @archaeron is making good progress on the Atom mode, which might be more accessible to students, and it uses the IDE protocol that Emacs and a few other tools use.

**Comment by kevinsullivan** [comment]
Here are the last 20 lines of the build. Fresh install of Ububtu 14.04 followed by apt-get update and apt-get dist-upgrade.

[13 of 13] Compiling Text.Trifecta    ( src/Text/Trifecta.hs, dist/build/Text/Trifecta.o )
In-place registering trifecta-1.5.1.3...
Installing library in /home/cs1/.cabal/lib/trifecta-1.5.1.3/ghc-7.6.3
Registering trifecta-1.5.1.3...
Installed trifecta-1.5.1.3
cabal: Error: some packages failed to install:
cheapskate-0.1.0.4 depends on zlib-0.5.4.2 which failed to install.
digest-0.0.1.2 failed during the configure step. The exception was:
ExitFailure 1
haskeline-0.7.2.1 depends on terminfo-0.4.0.1 which failed to install.
idris-0.9.18.1 depends on zlib-0.5.4.2 which failed to install.
streaming-commons-0.1.12.1 depends on zlib-0.5.4.2 which failed to install.
terminfo-0.4.0.1 failed during the configure step. The exception was:
ExitFailure 1

**Comment by kevinsullivan** [comment]
David, Regarding --client and vim mode. Our use case is an undergraduate CS1 course. These will be students with no experience at all in computer science. One of our goals is to get students set up from the outset to develop software "for real." . Several requirements follow. First, we must make it as easy for them as possible. They'll have to learn to use a text editor and Linux command line / shell, and that is ok, but we don't want them to have to deal with bugginess in the tools. Second,  we'd like to have them using *standard* tools. Vim is standard these days for this kind of work. We could conceivably switch to emacs, but my sense is that vim is the better choice for them for the long term. 

We realize that idris is research software. What we're doing right now is working really hard to make sure that every detail of the beginning student experience will be without glitchiness. I have several people, including a rising first-year undergraduate, working in my lab, developing our programming environment and exercises in  detail to be sure that everything will work: vim, vim configuration, git, vim mode, writing "test cases" as simple equality propositions (in a "how to design programs/HTDP" style, making sure that we'll be able to explain error messages, such as when refls fail to unify, etc.

So, to finally answer your question about vim, we'd very much like to use it and vim mode. That said, we are still evaluating our options, both assuming use of Idris, and not. We just have to decide soon. Coq could work. We have plenty of experience using it at this level. But for good reasons, we'd really strongly prefer to use Idris if we can get the tooling and platform issues worked out.

**Comment by LeifW** [comment]
We can absolutely get idris / vim mode working on these platforms. If we
can't get those build issues sussed out quickly, we can (maybe should
anywats) make an Ubuntu package you can dpkg -I install. I'm just on my
phone right now, but I was thinking a quick approach would be to use the
checkinstall tool the same way we use a similar tool to make Mac packages:
essentially a zipfile of the install output. I can do that this weekend if
someone else doesn't get to it first.

**Comment by kevinsullivan** [comment]
Thank you both. We're not set up to become committers (at least not yet), but we'll be happy to work with you to identify and work through glitches that would make it hard to use this language/system in classes of the kind we're planning to teach. So far, the vim mode and Ubuntu build issues are the only quasi-show-stoppers we've encountered.

Quick question: What environment do you devs think is best for Idris programming? OS, program editor. plug-ins/extensions/packages, etc?

**Comment by jfdm** [comment]
I run Ubuntu 14.04 LTS for work and actively develop using Idris. I found several months ago that the default Ubuntu was not conducive to my work flow: GHC and friends were too out-of-date. I solved my problem by installing more uptodate versions of ghc and friends using the [hvr ppa](https://launchpad.net/~hvr/+archive/ubuntu/ghc) and installing the 7.8 series. Once this was installed everything was fine. I have yet to install Idris straight from Cabal, as I follow development of HEAD, and I do use cabal sandboxes. This will affect my experience when not using head versions.

As for tooling. I develop on both Mac OS X and Ubunutu 14.04 LTS platforms both of these are sufficient for my needs. For these I tend to use:

+ GHC 7.8 series and friends
+ Emacs with HEAD version of idris mode.
+ Sphinx (as supported for readthedocs) for building local copies of documentation.

That is it really. But if I wasn't following HEAD versions, then hopefully the stable version of idris-mode and idris should be suitable for teaching.

**Comment by jfdm** [comment]
As an alternate to providing a binary build, FPComplete [recently released stack](https://www.fpcomplete.com/blog/2015/06/announcing-first-public-beta-stack). It is:

> a new, complete, cross-platform development tool aimed at both new and experienced Haskell 
> developers alike, for installing and setting up the compiler, installing packages needed, and building, 
> testing or benchmarking one or more packages in a project at a time. It's the whole stack.

This might be an alternate (more user heavy; idris dev light) approach to distribute Idris more reliably.

**Comment by jfdm** [comment]
As an update. On: Ubuntu 14.04 using GHC 7.8.4 and Cabal 1.22.4.0 installed using the her papa and running the command:

    cabal install idris

successfully installs Idris 0.9.18.1. Personally, I had to include force-reinstalls on cabal, but on a fresh Ubuntu box with ghc freshly installed it shouldn't be a problem.

Hopefully Idris Mode and Vim Mode will work out the box too. I think it is time maybe that we ensure that these editor tools are also tagged along side the current version of idris it works with.

**Comment by david-christiansen** [comment]
> What environment do you devs think is best for Idris programming? OS, program editor. plug-ins/extensions/packages, etc?

Probably Mac OS X or some kind of Linux is easiest these days, simply because Haskell code is easier to make build there for various dumb reasons. But @melted has put in a lot of work, and as of the latest Idris release, no special patches are needed on Windows, the test cases work fine, and everything seems to be as it should be. So the Unixy OSes aren't likely to be a _huge_ decrease of effort anymore, even for Idris developers, and there are binaries for Windows. The semantic colors don't yet work on Windows' console, though I would like to get around to fixing that at some point. In Emacs and soon Atom, they're fine.

I'm perhaps somewhat biased, as the main developer of the Emacs mode these days, but I think that it's currently the best. The Emacs mode has tons of features that the vim mode doesn't yet have, like seeing documentation in a tooltip when hovering the mouse over a name in source code, getting a tree view that shows the callers/callees of a particular name, interactively exploring a namespace, clicking errors to jump to the associated source location, a Proof-General-like interface to the prover, and more. You can even do things like normalizing terms that occur in-place in error messages. Vim gets you the essentials, like case splitting and looking up types, but nobody's figured out how to run the IDE protocol as a subprocess to get the kind of interactivity that the Emacs mode provides.

If you are going to try the Emacs mode, the X version is much nicer to use than the console version due to having good mouse support, all the commands in menus, etc. Everything's available through keybindings, but the right-click menu does make it more accessible. WRT extensions/plugins, `helm-idris` lets you incrementally search the documentation of the whole system, but learning `helm` has its own pile of complication.

We do want to support a diversity of platforms and editors, rather than being locked up in one of each, and experience reports like yours are highly valuable in helping this happen - so thanks!

> Here are the last lines of the build. Fresh install of Ububtu 14.04 followed by apt-get update and apt-get dist-upgrade.

This looks like missing C dependencies to me, given that both zlib and terminfo are Haskell wrappers around the corresponding C libs. My guess is that it's missing some development headers, and that our instructions need updating. I'll try to find time soon to spin up a 14.04 VM and take notes as I install things, and also to look into what it takes to make an Ubuntu PPA for a package.

> writing "test cases" as simple equality propositions (in a "how to design programs/HTDP" style, making sure that we'll be able to explain error messages, such as when refls fail to unify, etc

Be aware that this will only work for total programs - partial ones won't reduce in the type of the equality. It might be worth doing some traditional testing as well.

Thanks for your engagement and for good feedback! Also, while evaluating options, you might want to look at Agda as well as Coq. It's much more difficult to run an Agda program than to run an Idris program, but other aspects of the implementation are more mature.

**Comment by david-christiansen** [comment]
@jfdm the Emacs mode is tagged, and the version on melpa-stable is always compatible with the latest Hackage Idris to the best of my ability. I think there's a bit less version sensitivity with the vim plugin, because it doesn't have as many of the newer commands.

**Comment by jfdm** [comment]
@david-christiansen Ah cool. I thought so, but was not sure. Hence the wording.

I just checked the installation instructions for Idris on 14.04, and I am a little shocked. The wiki used to contain my detailed notes for getting Idris installed: including dependencies. However, they were obliterated earlier in the year for simpler instructions, and everything was lost. I might have a back up on my machine at work. Anyway, I will look into updating the notes at some point.

**Comment by david-christiansen** [comment]
The wiki has history of each page, luckily!

**Comment by jfdm** [comment]
it turns out my stuff was on another page, and heavily edited nonetheless. I will sponsor the Ubuntu Page and updated it when I can next get round to it.

**Comment by kevinsullivan** [comment]
Well, with help from above and a little Google searching, I have now managed to build idris in an  Ubuntu 14.04 VM.  Here's what worked.

sudo add-apt-repository -y ppa:hvr/ghc
sudo apt-get update
sudo apt-get install -y cabal-install-1.20 ghc-7.8.4                         ### 1.22.4.0 is current cabal-install
cat >> ~/.bashrc <<EOF
export PATH="~/.cabal/bin:/opt/cabal/1.20/bin:/opt/ghc/7.8.4/bin:\$PATH"
EOF
cabal install cabal-install                                  ### in response to instructions to update  cabal-install
cabal install idris

## The unresolved dependencies were no longer a problem at this point.
## However the install now failed due to memory exhaustion (on a VM with 2GB)
## Re-installing using the "gold" instructions also failed due to memory exhaustion
## Stopping the VM, increasing memory to 4GB, and re-starting and re-installing did the trick

export PATH=~/.cabal/bin:/opt/cabal/1.20/bin:/opt/ghc/7.8.4/bin:$PATH
cabal update

Thanks everyone! I'll check vim mode, etc, and will let you know. But we might also just switch over to emacs.

**Comment by david-christiansen** [comment]
Great news!

Do you plan on distributing VM images to your students? That might save them some hassle getting everything installed and going.

**Comment by kevinsullivan** [comment]
Yes, the plan is to give them a VM, set up and ready to go.

Quick question (sorry to be off-issue-topic here): Is there a recommended pattern or technique for adding (ordinary, not propositional) test cases to a program? A unit testing framework, for example?

**Comment by david-christiansen** [comment]
I started on a port of QuickCheck, but got distracted and didn't finish it. I did get as far as adding test support to the build tool, so you can run tests when compiling your package. It's still pretty rudimentary, and it's designed to be a hook for testing libraries, but we don't have those yet to my knowledge.

I think the best use of this so far is @jfdm's containers library. In the `.ipkg` file, you provide a list of IO actions to be run when you call `idris --testpkg FILE.ipkg`. These can be anything. An example is at https://github.com/jfdm/idris-containers/blob/master/containers.ipkg#L32-L37 .

A little traditional test-running thing in the style of HUnit might be a good first project if you have an undergrad helping out with the planning who needs to get familiar with Idris fast.

**Comment by LeifW** [comment]
For a boolean test of something at compile time there's that 'So' type,
populated by 'Oh : So True', documented in the tutorial.

**Comment by david-christiansen** [comment]
@LeifW `So` is for type-correctness when you have a runtime check - it's not really for the purpose of making sure that your program is computing what it should!

**Comment by kevinsullivan** [comment]
Tried to build dev version tonight. Ubuntu 14.04 (pretty fresh), Haskell 7.8.4. Got this:

/home/cs1/System/Idris-dev/.cabal-sandbox/lib/x86_64-linux-ghc-7.8.4/trifecta-1.5.1.3
Registering trifecta-1.5.1.3...
Installed trifecta-1.5.1.3
cabal: Error: some packages failed to install:
haskeline-0.7.2.1 failed during the building phase. The exception was:
ExitFailure 1

**Comment by melted** [comment]
you likely need to install the ubuntu dev package for terminfo.

**Comment by melted** [comment]
Ah, it's libtinfo-dev. but install ncurses anyway, that is used if you build with -f curses.

**Comment by kevinsullivan** [comment]
Ok, thank you. --kevin

**Comment by edwinb** [comment]
I'm closing this since it appears to be resolved. If there's still an issue that we can do something about in the Idris distribution, please reopen.
