### ISSUE TITLE
Equality type error

### ISSUE THREAD

**Issue by identicalsnowflake** [idris-lang/Idris-dev#2377]
I'm trying to map an associative function from one type to another via isomorphism, and I'm getting the following type error (all the relevant code should be visible in the pic):

http://i.imgur.com/f22LRfZ.png

Is this a compiler bug? Am I doing something wrong?

**Comment by david-christiansen** [comment]
It looks to me like the types differ only in implicit arguments. In Emacs,
you can turn on the display of the implicit arguments by either setting the
checkbox in the options section of the Idris menu, or term-for-term by
putting point on the term and saying C-c C-m i (or by picking "show term
widgets" in the menu and right-clicking the widget for the term). At the
console, use :set showimplicits.

If this doesn't help you find the solution, please paste your code in, so
that we can experiment without having to retype it from the screenshot.

2015-06-14 18:52 GMT+02:00 identicalsnowflake <notifications@github.com>:

**Comment by identicalsnowflake** [comment]
Ah ok, I didn't realize I could turn on implicits in the error messages. That revealed my problem. Thanks

**Comment by david-christiansen** [comment]
You're welcome!

2015-06-15 0:06 GMT+02:00 identicalsnowflake <notifications@github.com>:
