### ISSUE TITLE
Memory or space leak when reloading

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#2386]
Given the following files:

Empty.idr:
```
module Empty

```

input: 
```
:l Empty.idr
:r
```
where the :r is repeated around 100,000 times, running the command `idris --quiet < input` causes memory usage to grow steadily.

I've been unable to find out where it's coming from using GHC profiling - I just figured I'd document it here in case someone else wants to have a go.

This isn't a problem in and of itself, but it's cut down from a real problem. If the module has more in it, memory usage grows faster, and large modules can grow very quickly indeed. For example, I have one large program where I need to restart Idris every 20 or so reloads due to memory consumption.

**Comment by LeifW** [comment]
It seems like a problem for long running services like the irc bot,
tryidris, idrisonline, etc. I suppose I could just restart the idris repl
every so often.

**Comment by identicalsnowflake** [comment]
> I have one large program where I need to restart Idris every 20 or so reloads due to memory consumption.

Can confirm. I have to restart pretty frequently and have less than 1k total LoC. I try to do all of my new work in an empty file, then copy it to the actual intended file when I have something I like.

**Comment by jfdm** [comment]
I think we have to be careful when sharing or diagnosing problems.

The reported problem is memory/space leakage when reloading Idris programs. This can occur at the command line or in Emacs. However, this symptom could also be indicative of an unnecessarily long compile time.

In the past I have realised that some styles of coding in Idris had a negative effect on code compilation performance. Also forgetting how the Idris evaluator works, and that this differs between the REPL and Compiler, is important to note.

Regardless the point is, when reporting/commenting on this issue, can people please check if their code compiles 'normally' outside of the scenario described by @david-christiansen.

**Comment by david-christiansen** [comment]
Larger modules do make the memory usage increase more quickly. With an empty module, it takes multiple thousands of reloads to get much bigger, while with some realistic programs I only get through 10 or so reloads before I need to restart it. I interpreted @identicalsnowflake as simply confirming this fact.

**Comment by melted** [comment]
I wonder if it is instances of Text from the previous IState that keeps everything alive by indexing into big arrays that then hang around, in that case it could be solved by using copy so we slice off just the bit we need. Sadly Text got a Binary instance some time ago, so we can't fix it in that one place.

**Comment by david-christiansen** [comment]
It looked like it was something like that, based on my naive reading of the profiles.

**Comment by david-christiansen** [comment]
Since 1cdc9dd, there's no longer a noticable space leak, but I don't think the issue should be closed. I just ran out of time and resources to truly find it.

So as to not violate the implicit contract of `DeepSeq` instances, the committed version has a `DeepSeq` on `IState` that in fact normalizes all the fields. An alternate version, that just normalizes the definition context, has a similar effect. So that's where we should look for the placement of the magic `!` in the future.

**Comment by ahmadsalim** [comment]
I think this is less of an issue now, with the new module system rules. I will close it for now since there has been not much active development anyhow, and when someone encounters a new related problem we could just open a new issue in the tracker.
