### ISSUE TITLE
Can't specify precedence and associativity of syntax extensions

### ISSUE THREAD

**Issue by kevinsullivan** [idris-lang/Idris-dev#2388]
Idris syntax extensions do not support the specification of precedence and associativity properties. 

To be practically useful, the Idris syntax extension features should provide such functionality. 

This "issue" is thus a feature request, to be addressed in due time, rather than a bug report.

Coq provides a possible model for Idris. In Coq, one introduces syntax extensions using the Notation feature. Here's an example:

Notation "A /\ B" := (and A B) (at level 80, right associativity).

More is possible. See Section 12.1 of the Coq reference manual for a possibly reasonable starting point for maturing the design of Idris syntax extensions: https://coq.inria.fr/refman/Reference-Manual014.html

**Comment by jfdm** [comment]
Whilst it is true that with idris the precedence and associativity of syntax extensions cannot be specified, the precedence and associativity for custom operators can.

In case what you are looking for is specifying the precedence and fixity for operators, the syntax is:

```idris
infix <level> <operator> 
infixl <level> <operator>
infixr <level> <operator>
--

With the definition of the operator comming later.
This syntax is much like the notation found in Haskell.

[An example can be found in the definition for list](https://github.com/idris-lang/Idris-dev/blob/master/libs/prelude/Prelude/List.idr#L17-L18).
Having a look through the idris documentation, I see that we do not explicitly treat custom operator definition, [its definition is rather weak](http://idris.readthedocs.org/en/latest/tutorial/typesfuns.html#data-types),

**Comment by kevinsullivan** [comment]
Thanks for this. One of the earliest examples I'll try to teach is "How to build a Boolean expression language of the sort that you find in languages such as Java and Python." The lesson will ideally come in 4 parts: (1) a bool data type and set of unary and binary operators, (2) a bool expression language with the bool abstract data type as a semantic domain, (3) a bool expression evaluator: expr -> bool, and (4) concrete syntax.

(4) would ideally define sugars such as "!" (prefix) for negb, "&&" (infix) for andb, "||" for orb, and so on.It would also eventually include this: IF a THEN b ELSE c = ifThenElse a b c. The pointer on custom binary operators is helpful, but doesn't give me everything I need. The syntax extension language looks like it *could* but that it isn't there yet.

We found two problems actually: (1) lack of assoc/prec, as above, and also (2) what might be a bug. In particular, when we make this definition ----  "!" B = not B ---- then Idris evaluates this expression fine: !True (where True is a boolean literal expression), but if we ask it to evaluate this it fails --- ( !True ) --- with a monad error (i.e., we just surrounded the expression to evaluate with parens, which we figured Idris would strip before trying to do something with the expression inside. Bug?

**Comment by david-christiansen** [comment]
On 2015-06-19 22:00, Kevin Sullivan wrote:
> Thanks for this. One of the earliest examples I'll try to teach is 
> "How to build a Boolean expression language of the sort that you
> find in languages such as Java and Python." The lesson will ideally
> come in 4 parts: (1) a bool data type and set of unary and binary 
> operators, (2) a bool expression language with the bool abstract
> data type as a semantic domain, (3) a bool expression evaluator: expr
> -> bool, and (4) concrete syntax.
p>
> (4) would ideally define sugars such as "!" (prefix) for negb, "&&" 
> (infix) for andb, "||" for orb, and so on.

You don't need to use syntax rules for these in Idris, with the
exception of a prefix operator. ! is already taken as built-in syntax
meaning something similar to do-notation - it lifts its operand to a >>=
binding just under the most recent binder. But you can use "not". For
all the other operators, you can just call the function && or ||, but
these are already included in the Prelude, so you'd need to run Idris
with a custom prelude for this assignment.

> It would also eventually include this: IF a THEN b ELSE c =
> ifThenElse a b c. 

Idris's if-then-else syntax already desugars this way, so you can use that.

> The pointer on custom binary operators is helpful,
> but doesn't give me everything I need. The syntax extension language
> looks like it *could* but that it isn't there yet.

Aside from !, is there anything else missing?

> We found two problems actually: (1) lack of assoc/prec, as above,
> and also (2) what might be a bug. In particular, when we make this 
> definition ----  "!" B = not B ---- then Idris evaluates this 
> expression fine: !True (where True is a boolean literal expression), 
> but if we ask it to evaluate this it fails --- ( !True ) --- with a 
> monad error (i.e., we just surrounded the expression to evaluate
> with parens, which we figured Idris would strip before trying to do 
> something with the expression inside. Bug?

If it lets you define a prefix operator called !, then that's a bug.
This is reserved syntax.

/David

**Comment by david-christiansen** [comment]
On 2015-06-19 22:00, Kevin Sullivan wrote:
> Thanks for this. One of the earliest examples I'll try to teach is 
> "How to build a Boolean expression language of the sort that you
> find in languages such as Java and Python." The lesson will ideally
> come in 4 parts: (1) a bool data type and set of unary and binary 
> operators, (2) a bool expression language with the bool abstract
> data type as a semantic domain, (3) a bool expression evaluator: expr
> -> bool, and (4) concrete syntax.
p>
> (4) would ideally define sugars such as "!" (prefix) for negb, "&&" 
> (infix) for andb, "||" for orb, and so on.

You don't need to use syntax rules for these in Idris, with the
exception of a prefix operator. ! is already taken as built-in syntax
meaning something similar to do-notation - it lifts its operand to a >>=
binding just under the most recent binder. But you can use "not". For
all the other operators, you can just call the function && or ||, but
these are already included in the Prelude, so you'd need to run Idris
with a custom prelude for this assignment.

> It would also eventually include this: IF a THEN b ELSE c =
> ifThenElse a b c. 

Idris's if-then-else syntax already desugars this way, so you can use that.

> The pointer on custom binary operators is helpful,
> but doesn't give me everything I need. The syntax extension language
> looks like it *could* but that it isn't there yet.

Aside from !, is there anything else missing?

> We found two problems actually: (1) lack of assoc/prec, as above,
> and also (2) what might be a bug. In particular, when we make this 
> definition ----  "!" B = not B ---- then Idris evaluates this 
> expression fine: !True (where True is a boolean literal expression), 
> but if we ask it to evaluate this it fails --- ( !True ) --- with a 
> monad error (i.e., we just surrounded the expression to evaluate
> with parens, which we figured Idris would strip before trying to do 
> something with the expression inside. Bug?

If it lets you define a prefix operator called !, then that's a bug.
This is reserved syntax. What's the code you're using?

/David

**Comment by kevinsullivan** [comment]
Here's what I'd be happy with for teaching. Only the last line is broken. Using it yields "Can't resolve type class Monad m." Consider adding "prefix" and "postfix" to complement "infix" (with precedence)??

=======================

module mybool

-- bool abstract data type

data bool = true | false

not: bool -> bool
not true = false
not false = true

and: bool -> bool -> bool
and true true = true
and true false = false
and false true = false
and false false = false

or: bool -> bool -> bool
or true true = true
or true false = true
or false true = true
or false false = false

ite: bool -> bool -> bool -> bool 
ite true tb fb = tb
ite false tb fb = fb

-- abstract syntax

data bExp =
  litExp bool |
  notExp bExp |
  andExp bExp bExp |
  orExp bExp bExp |
  iteExp bExp bExp bExp 
  
-- semantics

eval: bExp -> bool 
eval (litExp b) = b
eval (notExp e) = not (eval e)
eval (andExp e1 e2) = and (eval e1) (eval e2)
eval (orExp e1 e2) = or (eval e1) (eval e2)

-- concrete syntax

infixl 4 &&, ||

(&&): bExp -> bExp -> bExp 
(&&) e1 e2 = andExp e1 e2
(||): bExp -> bExp -> bExp 
(||) e1 e2 = orExp e1 e2

syntax True = litExp true
syntax False = litExp false
syntax IF [c] THEN [t] ELSE [f] = iteExp c t f
syntax "!" b =  notExp b

**Comment by david-christiansen** [comment]
What about this? I've tweaked cases to follow Idris convention more closely, and replaced most of the syntax extensions with ordinary definitions. I also added a missing case to eval - you can avoid these kinds of things by adding "%default total" to the beginning.
```
module MyBool

||| Our own Boolean type, written in lower case to avoid conflicts
||| with the built-in Bool
data bool = true | false

not: bool -> bool
not true = false
not false = true

and: bool -> bool -> bool
and true true = true
and true false = false
and false true = false
and false false = false

or: bool -> bool -> bool
or true true = true
or true false = true
or false true = true
or false false = false

ite: bool -> bool -> bool -> bool
ite true tb fb = tb
ite false tb fb = fb

||| Abstract syntax for Boolean expressions
data BExp =
  LitExp bool |
  NotExp BExp |
  AndExp BExp BExp |
  OrExp BExp BExp |
  IteExp BExp BExp BExp

||| Semantics of Boolean expressions
eval: BExp -> bool
eval (LitExp b) = b
eval (NotExp e) = not (eval e)
eval (AndExp e1 e2) = and (eval e1) (eval e2)
eval (OrExp e1 e2) = or (eval e1) (eval e2)
eval (IteExp c t f) = ite (eval c) (eval t) (eval f)

-- concrete syntax

infixl 4 &&, ||

(&&): BExp -> BExp -> BExp
(&&) e1 e2 = AndExp e1 e2
(||): BExp -> BExp -> BExp
(||) e1 e2 = OrExp e1 e2

T : BExp
T = LitExp true

F : BExp
F = LitExp false

ifThenElse : BExp -> BExp -> BExp -> BExp
ifThenElse = IteExp

syntax "~" [b] = NotExp b
```

REPL examples:
```
λΠ> if T then F else T
iteExp (litExp true) (litExp false) (litExp true) : BExp
λΠ> T || F
orExp (litExp true) (litExp false) : BExp
λΠ> T || ~F
orExp (litExp true) (notExp (litExp false)) : BExp
λΠ> ~T || ~F
notExp (orExp (litExp true) (notExp (litExp false))) : BExp
λΠ> ~(T || F)
notExp (orExp (litExp true) (litExp false)) : BExp
```

As you can see, `~` gets the wrong precedence. If you instead define:
```
neg : BExp -> BExp
neg = NotExp
```
then things work:
```
λΠ> neg T || neg F
OrExp (NotExp (LitExp true)) (NotExp (LitExp false)) : BExp
```

You also avoid the pain of syntax extensions entirely. They're really intended as a kind of last-ditch thing, rather than something used all over the place like Coq notations.

With this setup, it's also fairly easy to prove things like de Morgan's laws:
```
deMorgan1 : (b1, b2 : BExp) -> eval (neg b1 || neg b2) = eval (neg (b1 && b2))
deMorgan1 b1 b2 with (eval b1)
  deMorgan1 b1 b2 | res1 with (eval b2)
    deMorgan1 b1 b2 | true  | true  = Refl
    deMorgan1 b1 b2 | true  | false = Refl
    deMorgan1 b1 b2 | false | true  = Refl
    deMorgan1 b1 b2 | false | false = Refl
```

**Comment by jfdm** [comment]
One thing to add to the comments of @david-christiansen is what is happening in `deMorgan1`. I think those new to Idris will not grasp completely what is going on here. 

 Idris supports inspection of intermediate values during computation, [these are known as "views" and more information is available about it on our docs](http://idris.readthedocs.org/en/latest/tutorial/views.html). When you first see the `with` syntax and use of pipe operators in operation it can be confusing. I know that I haven't experienced the complete "a-ha" moment  with the use of "views".

```idris
deMorgan1 : (b1, b2 : BExp) -> eval (neg b1 || neg b2) = eval (neg (b1 && b2))
deMorgan1 b1 b2 with (eval b1) -- Here we inspect the computation for evaluating b1
  deMorgan1 b1 b2 | res1 with (eval b2) -- Here we inspect the computation for evaluating b2
    -- Here we specify the desired values for what b1 and b2 can be.
    deMorgan1 b1 b2 | true  | true  = Refl  
    deMorgan1 b1 b2 | true  | false = Refl  
    deMorgan1 b1 b2 | false | true  = Refl
    deMorgan1 b1 b2 | false | false = Refl
```

Now, I have a feeling that my explanation might not be sufficient. Hopefully others can say what is going on.

**Comment by david-christiansen** [comment]
This isn't the same thing as a view. A view is a particular way of using the with rule, where a special kind of datatype that witnesses an equality is used to make the patterns to the left of the pipe character do something interesting. It's a technique to get some of what you would get from Wadler's 1987 POPL paper, but implemented as a library or design pattern rather than as a language feature.

In this example, what's happening is that the with-match transforms the goal. I start with this:
```
deMorgan1 : (b1, b2 : BExp) -> eval (neg b1 || neg b2) = eval (neg (b1 && b2))
deMorgan1 b1 b2 = ?rhs
```
I have the following metavariable context:
```
Metavariables
- + MyBool.lkj [P]
 `--          b1 : BExp
              b2 : BExp
     ---------------------------------------------------------------------------------
      MyBool.lkj : or (not (eval b1)) (not (eval b2)) = not (and (eval b1) (eval b2))
```
Case splitting `b1` or `b2` doesn't help me, because what I care about here is not so much the syntactic structure of `b1` or `b2` as it is the result of evaluating them (though I could probably hack together some kind of giant induction over the term structure). What I really want to do is see the result of the evaluation. Because this will change the type of the right-hand side, I need to do it on the left. The with rule lets me extend the left-hand pattern match with new expressions, where the result of the pattern match refines the type of the right-hand side.

So I add a with match for the result of `eval b1`:
```
deMorgan1 : (b1, b2 : BExp) -> eval (neg b1 || neg b2) = eval (neg (b1 && b2))
deMorgan1 b1 b2 with (eval b1)
  deMorgan1 b1 b2 | res1 = ?deMorgan1_rhs
```

My goal has now changed:
```
Metavariables
- + MyBool.deMorgan1_rhs [P]
 `--                  res1 : bool
                        b1 : BExp
                        b2 : BExp
     ---------------------------------------------------------------------------------
      MyBool.deMorgan1_rhs : or (not res1) (not (eval b2)) = not (and res1 (eval b2))
```

The important thing is that my pattern variable `b1` has replaced the expression that it represents in the goal, which means that I'll be able to case split it in a moment!

The next step is to do the same for `eval b2`:
```
deMorgan1 : (b1, b2 : BExp) -> eval (neg b1 || neg b2) = eval (neg (b1 && b2))
deMorgan1 b1 b2 with (eval b1)
  deMorgan1 b1 b2 | res1 with (eval b2)
    deMorgan1 b1 b2 | res1 | res2 = ?deMorgan1_rhs
```
giving the goal:
```
Metavariables
- + MyBool.deMorgan1_rhs [P]
 `--                  res2 : bool
                      res1 : bool
                        b1 : BExp
                        b2 : BExp
     -----------------------------------------------------------------------
      MyBool.deMorgan1_rhs : or (not res1) (not res2) = not (and res1 res2)
```

Now I have something to work with, because I know that the result is a function of pattern variables directly. I case split `res1` giving:
```
deMorgan1 : (b1, b2 : BExp) -> eval (neg b1 || neg b2) = eval (neg (b1 && b2))
deMorgan1 b1 b2 with (eval b1)
  deMorgan1 b1 b2 | res1 with (eval b2)
    deMorgan1 b1 b2 | true  | res2 = ?deMorgan1_rhs_1
    deMorgan1 b1 b2 | false | res2 = ?deMorgan1_rhs_2
```
and
```
Metavariables
- + MyBool.deMorgan1_rhs_1 [P]
 `--                    res2 : bool
                          b1 : BExp
                          b2 : BExp
     --------------------------------------------------------------------
      MyBool.deMorgan1_rhs_1 : or false (not res2) = not (and true res2)

- + MyBool.deMorgan1_rhs_2 [P]
 `--                    res2 : bool
                          b1 : BExp
                          b2 : BExp
     --------------------------------------------------------------------
      MyBool.deMorgan1_rhs_2 : or true (not res2) = not (and false res2)
```

The reason that the `or`s and `and`s don't reduce in those goals is that they are defined as pattern matches on both of their arguments. If we had had
```
and : bool -> bool -> bool
and true b2 = b2
and false _ = false
```
then the goal would already be simplified.

Anyway, I need to pattern-match res2 to make progress. I case split both of the `res2` pattern variables:
```
deMorgan1 : (b1, b2 : BExp) -> eval (neg b1 || neg b2) = eval (neg (b1 && b2))
deMorgan1 b1 b2 with (eval b1)
  deMorgan1 b1 b2 | res1 with (eval b2)
    deMorgan1 b1 b2 | true  | true  = ?deMorgan1_rhs_3
    deMorgan1 b1 b2 | true  | false = ?deMorgan1_rhs_4
    deMorgan1 b1 b2 | false | true  = ?deMorgan1_rhs_1
    deMorgan1 b1 b2 | false | false  = ?deMorgan1_rhs_5
```
giving:
```
Metavariables
- + MyBool.deMorgan1_rhs_3 [P]
 `--                      b1 : BExp
                          b2 : BExp
     ----------------------------------------
      MyBool.deMorgan1_rhs_3 : false = false

- + MyBool.deMorgan1_rhs_4 [P]
 `--                      b1 : BExp
                          b2 : BExp
     --------------------------------------
      MyBool.deMorgan1_rhs_4 : true = true

- + MyBool.deMorgan1_rhs_1 [P]
 `--                      b1 : BExp
                          b2 : BExp
     --------------------------------------
      MyBool.deMorgan1_rhs_1 : true = true

- + MyBool.deMorgan1_rhs_5 [P]
 `--                      b1 : BExp
                          b2 : BExp
     --------------------------------------
      MyBool.deMorgan1_rhs_5 : true = true
```

All of these cases are trivially true by reflexivity, so I can just write `Refl` in all four right-hand sides:
```
deMorgan1 : (b1, b2 : BExp) -> eval (neg b1 || neg b2) = eval (neg (b1 && b2))
deMorgan1 b1 b2 with (eval b1)
  deMorgan1 b1 b2 | res1 with (eval b2)
    deMorgan1 b1 b2 | true  | true  = Refl
    deMorgan1 b1 b2 | true  | false = Refl
    deMorgan1 b1 b2 | false | true  = Refl
    deMorgan1 b1 b2 | false | false = Refl
```

The key here was getting a case-splittable variable that stood for the result of evaluating a sub-expression in my goal type. That's what `with` is for.

**Comment by jfdm** [comment]
Ah cheers for the explanation, I have yet to full come to terms with the 'with' construct let alone views. I am even tempted to ask if we can take this bool example complete with demorgan 'proof' and have another little short guide on how to do x in idris.

**Comment by kevinsullivan** [comment]
You guys are great. Let me digest this all.

**Comment by ahmadsalim** [comment]
I think I will close this issue, since it seems that the original questions was answered.
