### ISSUE TITLE
Not type

### ISSUE THREAD

**Issue by identicalsnowflake** [idris-lang/Idris-dev#2389]
There is a built-in `Not : Type -> Type` which matches an equality proof and maps it to Void. Is there any more general version? For example, I have a `LessThan : (a:N) -> (b:N) -> Type` type, and when I say "not less than", I have to write `LessThan a b -> Void` instead of `Not (LessThan a b)`, which looks super weird because all of the preceding code dealing with equality says `Not (a = b)` instead of `a = b -> Void`.

It's not a big deal, it just... makes my code look weird to write the same thing in multiple ways.

**Comment by david-christiansen** [comment]
On 21/06/15 15:51, identicalsnowflake wrote:
> There is a built-in |Not : Type -> Type| which matches an equality proof
> and maps it to Void. Is there any more general version? For example, I
> have a |LessThan : {n:N} -> (a:n) -> (b:n) -> Type| type, and when I say
> "not less than", I have to write |LessThan a b -> Void| instead of |Not
> (LessThan a b)|, which looks super weird because all of the preceding
> code dealing with equality says |Not (a = b)| instead of |a = b -> Void|.

I think you may have misunderstood Not - there's nothing specific to the
equality type about it. The definition is:

Not : Type -> Type
Not a = a -> Void

What kind of error messages are you getting? Perhaps you could paste
them here?

/David

**Comment by identicalsnowflake** [comment]
Ah, wow, yeah I definitely misread that. In any case, the reason that I became suspicious of it is that `Not X` is behaving differently than `X -> Void` in my code. Specifically, sometimes `a = b -> Void` will typecheck, but replacing it with `Not (a = b)` causes an error.

The replacement works most of the time, but sometimes it doesn't. Here's the snippet where the actual error occurs:

```haskell

lessThanImpliesNotEqual : (a:Natural p) -> (b:Natural p) -> LessThan a b -> a = b -> Void
lessThanImpliesNotEqual a b (MkLessThan a b (c ** (aPlusCIsB,cNonZero))) aEqualsb =
  let step = symmetric aPlusCIsB in
  let step2 = transitivity aEqualsb step in
  let (MkMonoid _ _ mn _) = plusMonoid p in
  let step3 = mn a in
  let step4 = transitivity step3 step2 in
  let mono = plusMonomorphic p in
  let (MkMonomorphicFunction ((+) a) monoprf) = mono a in
  let fin = monoprf 0 c in
  let cIsZero = fin step4 in
  cNonZero $ symmetric cIsZero

```

That probably won't be of much help, but the code it depends on is becoming kind of enormous. Anyway, in this function, if I replace `a = b -> Void` in the type signature with `Not (a = b)`, it stops compiling, but if I leave it as is, it compiles just fine.

**Comment by david-christiansen** [comment]
The fact that the error message is "No such variable p" makes me think that this has nothing to do with the Not type _per se_ and rather is a problem with implicit argument resolution. I don't have your code to test, but what if you make the signature into
```
lessThanImpliesNotEqual : (a:Natural p) -> (b:Natural p) -> LessThan a b -> Not ((=) {A=Natural p} {B=Natural p} a b)
```
? What if you define

```
data Id : {A : Type} -> A -> A -> Type where
  Refl' : {A : Type} -> {x : A} -> Id x x
```
and then use
```
lessThanImpliesNotEqual : (a:Natural p) -> (b:Natural p) -> LessThan a b -> Not (Id a b)
```
?

**Comment by identicalsnowflake** [comment]
> The fact that the error message is "No such variable p" makes me think that this has nothing to do with the Not type per se and rather is a problem with implicit argument resolution.

Yeah, it seems that somehow Not is scopeblocking (for lack of a better term) the implicit arguments to a and b.

The `Id` thing didn't work, but I'm not worried about it. After sleeping on it, I've come to the conclusion that `X -> Void` is more philosophically in harmony with intuitionism than the English term "not" anyway, so I'm happy to leave it as is.

**Comment by david-christiansen** [comment]
I'd prefer to leave this open - as far as I can see, this kind of thing should work.

What error did you get with the `Id` version?

**Comment by identicalsnowflake** [comment]
Ok, I've [posted my code](https://github.com/identicalsnowflake/NewEden) to a repo on my account, so you can try it there and experience the error. As far as what it is, the library is basically a natural numbers library where instead of defining the natural numbers, I simply accept a set of axioms (proofs, properties, whatever you want to call them) on a given type t, then write all my code in terms of Natural p (where p is the given properties). When I finally want to run my code, I just plugin whatever implementation of natural suits my purpose (e.g., I could use Natural Nat if I want purely formal checking, Natural UInt64 for machine implementation, etc) by proving (or assuming) the basic natural axioms for my particular implementation.

Or at least, that's the idea. Right now it's me just hacking around and sucking at dependent types.

Anyway, you can find this `lessThanImpliesNotEqual` in the NaturalTheorems module and see this error by playing around with the end of its type signature. I'm fairly sure some of the others will produce similar results when using `Not`, but many of them don't.

**Comment by edwinb** [comment]
It's because 'p' is being treated as a parameter when using `a = b -> Void`, but not when using `Not (a = b)`. You don't actually bind `p` explicitly anywhere on the left hand side, hence the "no such variable" error. 

It's okay when it's treated as a parameter. Parameters are in scope in the body (because they can't vary, and because it's useful to propagate them to where clauses). 

The question that I haven't yet answered is why it's not treated as a parameter when there is a `Not`, but in any case if you bring it into scope explicitly on the lhs with {p} then it'll be fine.

**Comment by edwinb** [comment]
Oh, I see why. It's because an instance of `p` appears under the `Not` and so Idris isn't sure any more.

There may be a deeper problem here, of how we should identify and treat parameters. For now this is expected behaviour, though.

**Comment by edwinb** [comment]
One day I'll learn not to comment in the middle of investigating an issue and waiting until I'm done. Today is not that day :).
