### ISSUE TITLE
Present an option to disable Idris automatically normalising documentation strings on lookup

### ISSUE THREAD

**Issue by ahmadsalim** [idris-lang/Idris-dev#2397]
Currently, when I lookup a documentation string for a datatype or function, Idris will automatically normalize the type. This has the unfortunate consequence that all type synonyms that are used&mdash;to make the signature more readable and understandable&mdash;are reduced to their core values which are often the same.

For example:

```idris
ClassId : Type
ClassId = String

FieldId : Type
FieldId = String

VarId : Type
VarId = String

record Class where
  constructor MkClass
  name : ClassId
  inherits : List ClassId
  children : Dict FieldId ClassId
  references : Dict FieldId ClassId
```

will get the following docs:

```
> :doc Class
Data type Class : Type


Constructors:
    MkClass : (name : String) ->
        (inherits : List String) ->
        (children : Dict String String) -> (references : Dict String String) -> Class
```

which looses all semantic information provided by the type synonyms.

**Comment by david-christiansen** [comment]
Honestly, I don't think this should be an option - it should just be what `:doc` does. If someone wants it normalized, they can easily get that, either by copy-pasting or using the IDE protocol's active terms. It's much more difficult to go the other way!

**Comment by ahmadsalim** [comment]
Seems to work now!
