### ISSUE TITLE
Another odd universe inconsistency

### ISSUE THREAD

**Issue by Melvar** [idris-lang/Idris-dev#2398]
```idris
module TestUniverseError3

%default total

record IdT (m : Type -> Type) a where
  constructor IT
  runIdT :
    (r : Type) ->
    (a -> m r) ->
    m r

instance Functor (IdT m) where
  map f (IT p) = IT $ \r, us => p r (us . f)

instance Applicative (IdT m) where
  pure x = IT (\r, us => us x)

  (<*>) (IT f) (IT g) = IT $ \r, us =>
    f r (\f' => g r (us . f'))

infixl 2 *!>
(*!>) : IdT m a
     -> IdT m b
     -> IdT m b
x *!> y = x *> y
```
yields
```
TestUniverseError3.idr:25:1:Universe inconsistency.
        Working on: w23
        Old domain: (7,7)
        New domain: (7,6)
        Involved constraints: 
                ConstraintFC {uconstraint = w23 < x23, ufc = TestUniverseError3.idr:25:1}
                ConstraintFC {uconstraint = v23 < w23, ufc = TestUniverseError3.idr:25:1}
                ConstraintFC {uconstraint = w23 < x23, ufc = TestUniverseError3.idr:25:1}
```

Substituting the definition of `(*>)` works:
```idris
x *!> y = map (const id) x <*> y
```
It also works if one adds extra `(Monad m)` constraints to the `Applicative` instance and to `(*!>)`. Neither of these workarounds is satisfactory, not least because other functions show a similar problem, and the extra constraints introduce a different universe inconsistency error in a different place.

@ozgurakgun I believe this is your area.

**Comment by ozgurakgun** [comment]
Hey. I just noticed that I was tagged here.

If there is a problem, my first guess is that it will be due to the generation of universe constraints rather than solving them. I know close to nothing about how there get generated, so someone else will have to have a look...

You could dump the generated constraints for the two cases you describe here and see what is different, maybe?

I am happy to have a look if the solver is broken.

**Comment by Melvar** [comment]
Oh, sorry, I thought you’d done the generation too.

**Comment by jfdm** [comment]
Just a note, that today I too have come across the Universe Inconsistency error in a project that is known to have worked previously.

**Comment by jfdm** [comment]
A second update: An MFE can be found in the lightyear repo. If you clone the repo and run `make test` the problem arises on [Line 18 in Test.idr](https://github.com/ziman/lightyear/blob/master/tests/Test.idr#L18) Showing the following error:

```Test.idr:18:1:Universe inconsistency.
        Working on: o39
        Old domain: (7,7)
        New domain: (7,6)
        Involved constraints: 
                ConstraintFC {uconstraint = o39 < p39, ufc = Test.idr:18:1}
                ConstraintFC {uconstraint = o39 < p39, ufc = Test.idr:18:1}
                ConstraintFC {uconstraint = k39 <= o39, ufc = Test.idr:18:1}
                ConstraintFC {uconstraint = m39 <= o39, ufc = Test.idr:18:1}
```

[The Universe Dump is available](https://gist.github.com/jfdm/c2b20f4626f9f72a00e2)

**Comment by ozgurakgun** [comment]
I have now validated that it is not the solver's fault. The dump of universe constraints is unsatisfiable, hence there is a universe inconsistency.

If you think there shouldn't be a universe inconsistency here, some extra constraints must be getting generated. If it is indeed a universe inconsistency, we should think about how to make the error message better somehow.

**Comment by jfdm** [comment]
@ozgurakgun Cheers for checking the solver. @edwinb mentioned on IRC there is issue #287 that indicates a problem still exists.

Also for those seeing universe inconsistency errors, the flag `--typeintype` turns of the checker.

**Comment by Melvar** [comment]
So I’ve done a bisection, and it looks like a problem with a merge, but I should do another couple of tests before pointing.

**Comment by Melvar** [comment]
So, I have tested these commits (time running upwards):
```
     6c673c2        Builds, doesn’t work
        ↑
     cc9895d        Doesn’t build
       ↗ ↖
d57d60a   baad761   Both work
```
Is this a problem with the merge?

**Comment by david-christiansen** [comment]
Links the to commits (for clickability):

 * Original working: d57d60a and baad761
 * Merged, doesn't build: cc9895d
 * Builds, doesn't work: 6c673c2

**Comment by ozgurakgun** [comment]
[This](https://github.com/idris-lang/Idris-dev/commit/cc9895d3d732cadfd0eecac3933c3afa0c39c835#diff-96564a3387879f26f31d7d2f96da2560R224) seems like a suspicious addition.

**Comment by jfdm** [comment]
There has been a recent update to Idris that has addressed my universe problems...are they solved here as well?

**Comment by edwinb** [comment]
This type checks for me now. There were constraints being added that shouldn't have been. I'll close it.

**Comment by Melvar** [comment]
Yay! \o/
