### ISSUE TITLE
Type class error

### ISSUE THREAD

**Issue by identicalsnowflake** [idris-lang/Idris-dev#2399]
Here is my code:

```haskell
class Commutative (f:(t -> t -> t)) where
  commutative : (a:t) -> (b:t) -> f a b = f b a
```

It fails to compile, saying "Type mismatch between `t5` (the type of `a`) and `t` (Expected type)." What else do I need to write to express that the `t` in `(a:t)` is the same `t` as in the above line?

**Comment by suhr** [comment]
I'm not sure what you're trying to define. Class for commutative type constructor probably looks like this:

```idris
class Commutative (f: Type -> Type -> Type) where
  commutative : (a: Type) -> (b: Type) -> f a b = f b a
```

But for commutative functions this can be used:
```idris
Commutative : (f: t -> t -> t) -> Type
Commutative {t} f = (a, b : t) -> a `f` b = b `f` a
```

I'm not experienced at writing idris code though.

**Comment by identicalsnowflake** [comment]
I don't think the first is what I'm looking for. It's operating on objects of different types. The second is deceptive -- it's constructing the *statement* "f is commutative", but it is not providing a proof or a refutation of that statement. It is constructing a `Type` with value `f a b = f b a`, not a value of type `f a b = f b a`.

I can code up the concept of commutativity just fine like this:

```haskell
data CommutativeFunction : (t:Type) -> (f:(t -> t -> t)) -> Type where
  MkCommutativeFunction :
      (f:(t -> t -> t))
   -> (prf:((a:t) -> (b:t) -> f a b = f b a))
   -> CommutativeFunction t f
```

This is correct, but it's a real pain in the ass to use. It would be nice to just make Commutative a type class and show that some function is a member of that type class, but I've had no luck getting that to actually compile.

**Comment by suhr** [comment]
I see what do you mean. Well, in code I have seen (for example, https://github.com/idris-lang/Idris-dev/pull/2205) it is done with several functions, where first (for example, `Symmetric`) constructs the statement, and others (for example, `equalityIsSymmetric`) construct necessary proofs.
Binding them together may be a good idea, but type classes seem not to be capable to do it yet.

**Comment by edwinb** [comment]
You could add 't' as an explicit parameter, like so:

    class Commutative (t : Type) (f:(t -> t -> t)) where
      commutative : (a:t) -> (b:t) -> f a b = f b a

However, you'll have some difficulty using this because type class instances need the parameters to be injective to support some assumptions made when unifying expressions with type classes. You may be better off using a record instead, and using auto-implicit arguments to pass them around implicitly.
