### ISSUE TITLE
Interaction of UniqueTypes and modules needs to be documented

### ISSUE THREAD

**Issue by taruti** [idris-lang/Idris-dev#2401]
Given a A.idr
```idris
data UList : Type -> UniqueType where
     Nil   : UList a
     (::)  : a -> UList a -> UList a

u : UList Int
u = [1,3,5,7]
```
And D.idr
```idris
import A

-- Intentionally not borrowing here...
lU : UList a -> Int
lU [] = 0
lU (_ :: xs) = 1 + lU xs

main : IO ()
main = do
  print $ lU u
  putStrLn ""
  print $ lU u
  putStrLn ""

```
Compiles with idris 0.9.18.1-git:a21064e. 

Adding a ```let u = u``` will get the expected type error.

This should probably be either documented or fixed.

**Comment by edwinb** [comment]
There's nothing wrong with using 'u' twice because it's a global and will be reevaluated each time. They're not memoized, partly because idris isn't lazy like that.

The same thing happens when they're in the same module.

**Comment by taruti** [comment]
The list gets duplicated like global variables are supposed due to strict semantics and everything works as intended.
