### ISSUE TITLE
A mountain from two grains of sand?

### ISSUE THREAD

**Issue by TimRichter** [idris-lang/Idris-dev#2407]
Hi,

in the Idris interactive environment (version 0.9.18 from cabal)
the normalization of the last expression below takes forever...

Somewhere here I read a recommendation to compile things when the IE is
slow, and indeed, it's all fine and fast when compiled.

However, isn't that weird? Doesn't Idris just do the 2 obvious
steps, each of which by itself is done in a wink? 

```
Idris> :module Data.Fin
*Data/Fin> 6857562 `mod` 10
2 : Integer
*Data/Fin> natToFin 2 10
Just (FS (FS FZ)) : Maybe (Fin 10)
*Data/Fin> natToFin (6857562 `mod` 10) 10
```

Best,
Tim

**Comment by david-christiansen** [comment]
At compile time, Idris uses the inductive definition of Nat, which means that you're consing up a 6857562-element linked list. Perhaps we should use the Integer hack at compile time as well as run time.

**Comment by TimRichter** [comment]
Hi David,
thanks, now I see what I missed. 6857562 `mod` 10 yields an Integer, but within natToFin, it is evaluated as a (unary...) Nat.

natToFin (fromInteger (6857562 `mod` 10)) 10
works fine. I'm closing the issue.

Best,
Tim
