### ISSUE TITLE
Idris gets confused if CWD contains files with names that overlap Prelude names

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#2409]
I just spent half a day figuring out something really hairy, so I figured I'd document it here.

I had a project with the following structure:

```
foo/
foo/foo.ipkg
foo/src/Thing/Main.idr
foo/src/Thing/IO.idr
```

where the sourcedir is set to `src` and `Thing.IO` contains IO operations for my program.

When editing `Main.idr`, I'd attempt to load Idris, and it would fail to start, looping forever. What happened was the following:
1. Idris startup would load Builtins and Prelude
2. Loading Prelude would attempt to re-export the IO module
3. The module chaser would find `foo/src/Thing/IO.idr`, because Idris's current working directory is on the load path prior to the built-in libraries
4. `IO.idr` wants the built-in Prelude IO actions, so it triggers a recursive load and mistakenly finds itself.

I'm not sure what the best design to fix this is, but I figured I'd document it here in case anyone else experiences something similar.

**Comment by ahmadsalim** [comment]
I think that the module loading algorithm should detect cycles instead of looping forever and then giving an error while loading. Whether it should do something else, I am unsure about.

**Comment by jfdm** [comment]
Does Idris not already have some form of cycle checking for imports?

**Comment by ahmadsalim** [comment]
@jfdm I am not sure, but perhaps the cycle checking algorithm should be adjusted to detect the one above.

**Comment by melted** [comment]
Fixed by https://github.com/idris-lang/Idris-dev/pull/3998
