### ISSUE TITLE
Type checking aborts

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2418]
The program

https://github.com/nicolabotta/SeqDecProbs/blob/master/frameworks/14-/SeqDecProbMonadicTheoryRVExample2.lidr

compiles in about one minute on my machine:
```
nicola@cirrus:~/github/SeqDecProbs/frameworks/14-$ time make rv_example
idris +RTS -K32000000 -RTS -p contrib -p effects SeqDecProbMonadicTheoryRVExample2.lidr -o rv_example
real	1m18.064s
user	1m17.324s
sys	0m1.516s
nicola@cirrus:~/github/SeqDecProbs/frameworks/14-$
```
Compile time is reliable and at most linear in the parameter `maxColumnO2` set to 5 at line 94. If you double `maxColumnO2`, compilation takes about two minutes. The case  `maxColumnO2 = 20` takes about three minutes to compile. But: uncommenting lines `242-247` and lines `437-442` of

https://github.com/nicolabotta/SeqDecProbs/blob/master/frameworks/14-/SeqDecProbMonadicTheoryRV.lidr

and

https://github.com/nicolabotta/SeqDecProbs/blob/master/frameworks/14-/SeqDecProbMonadicTheoryRVExample2.lidr

respectively, makes compilation virtually impossible even for very small values of `maxColumnO2`. For instance, for `maxColumnO2 = 5`, compilation aborts after about 9 minutes:
```
nicola@cirrus:~/github/SeqDecProbs/frameworks/14-$ time make rv_example
idris +RTS -K32000000 -RTS -p contrib -p effects SeqDecProbMonadicTheoryRVExample2.lidr -o rv_example
Makefile:11: recipe for target 'rv_example' failed
make: *** [rv_example] Killed
real	8m48.732s
user	6m9.868s
sys	0m56.904s
nicola@cirrus:~/github/SeqDecProbs/frameworks/14-$
```
Type checking the example from emacs' idris-mode clearly shows that coloring gets stuck at line 437 and memory usage goes up to about 100%. After a while, type checking aborts and the message `Idris disconnected: killed` appears in the minibuffer.

As far as I can remember, this problem showed up for the first time in April 2014 and has been there since then. What is most annoying is that the function defined at line 437 does not even get evaluated in the program. It is a specification that allows one to compute a correctness proof which is not required in the example. All we need is the specification to type check.

I think I have already reported the problem a few months ago on idris-lang but I thought I would try to have it nailed down in a reproducible issue report. Any idea what is going on here?

**Comment by nicolabotta** [comment]
> Any idea what is going on here? 

Yes, this is an instance of #2423. The problem can be avoided by deferring the definition of 'maxColumnO2' (line 94), `fY` (line 238) and `nefY` (line 243) to the end of the file. The alternative implementation

https://github.com/nicolabotta/SeqDecProbs/blob/master/frameworks/14-/SeqDecProbMonadicTheoryRVExample2b.lidr

type checks in about 30 seconds independently of  the value of 'maxColumnO2'. This is not really a solution, of course. In my view it suggests that there is a basic problem with the current type checking approach.

**Comment by ahmadsalim** [comment]
I will close this as duplicate since this is an instance of another issue as pointed out.
