### ISSUE TITLE
Idris execution hangs on execution of IO action -- simple, complete example

### ISSUE THREAD

**Issue by kevinsullivan** [idris-lang/Idris-dev#2424]
Updated description.

Here's a complete single file exhibiting the problem. Everything should be total so there should be no infinite loops. Looks like something's looping or blocking.  To see the problem cut and paste this code into an Idris file, run it, then uncomment the line commented out in main at the end of the file and run again. Observation:  Delegating through a function with a tighter type signature works, otherwise not. 

````
%default total

{- ************ bool ************** -}

data bool = true | false

negb : bool -> bool
negb true = false
negb false = true

andb : bool -> bool -> bool
andb true true = true
andb true false = false
andb false true = false
andb false false = false

boolToBool : bool -> Bool
boolToBool false = False
boolToBool true = True

{- ************ eq ************** -}

class eq a where
  eql : a -> a -> bool
  neql : a -> a -> bool

  neql x y = negb (eql x y)
  eql x y = negb (neql x y)

{- ************ list ************** -}

data list a = nil | cons a (list a)

isElementOf : (eq a) => list a -> a -> bool
isElementOf nil        val = false
isElementOf (cons h t) val = if (boolToBool (eql h val))
                             then true
                             else (isElementOf t val)

instance (eq a) => eq (list a) where
  eql nil nil = true
  eql (cons h t) nil = false
  eql nil (cons h t) = false
  eql (cons h1 t1) (cons h2 t2) = andb (eql h1 h2) (eql t1 t2)

{- ************ set ************** -}

data set a =
mkSet (list a)

newSet: set a
newSet = mkSet nil

insert : (eq a) => set a -> a -> set a
insert (mkSet l) a = if (boolToBool (isElementOf l a))
then (mkSet l)
else (mkSet (cons a l))

isListInList: (eq a) => list a -> list a -> bool
isListInList nil nil = true
isListInList nil l = true
isListInList (cons h t) nil = false
isListInList (cons h t) l = andb (isElementOf l h) (isListInList t l)

instance (eq a) => eq (set a) where
  eql (mkSet l1) (mkSet l2) = 
    andb (isListInList l1 l2) -- all values in l1 are in l2
         (isListInList l2 l1) -- all values in l2 are in l1

{- ************ nat ************** -}

data nat : Type where
  Z : nat
  S : nat -> nat

instance eq nat where
  eql Z Z = true
  eql Z (S m') = false
  eql (S n') Z = false
  eql (S n') (S m') = eql n' m'

{- ************ testing ************** -}

testEql : (eq a) => String -> a -> a -> IO ()
testEql msg actual expected = 
if (boolToBool (eql actual expected)) then 
putStrLn (msg ++ ": pass") else 
putStrLn (msg ++ ": fail")

testSetEql: (eq a) => String -> set a -> set a -> IO ()
testSetEql msg s1 s2 = testEql msg s1 s2

{- ************ test data ************** -}

emp : set nat
emp = newSet

s1: set nat
s1 = insert emp (S Z)

{- ************ run tests ************** -}

{-
Test #2' works. It calls testSetEql, which just
delegates to testEql. Calling testEql directly
(with a non-empty set) hangs the process.
-}

main : IO ()
main = do testEql "test #1" emp emp -- this works
          -- testEql "test #2" s1 s1 -- this doesn't work
          testSetEql "test #2'" s1 s1 -- this works


````

**Comment by kevinsullivan** [comment]
Okay, here's a complete single file exhibiting the problem. As a novice Idriser, I'm probably making a dumb mistake, but I don't see it. Everything should be total so there should be no infinite loops. Looks to me like something's looping. The key observation is that if I delegate to the problematical function through a function with a tighter type signature, then everything works, but not otherwise.

To see the problem just cut and paste this code into a new Idris file, run it, and comment and uncomment the two or three lines in the main routine at the end of the file.

=============================================================================

%default total

{- ************ bool ************** -}

data bool = true | false 

negb: bool -> bool
negb true = false
negb false = true

andb: bool -> bool -> bool
andb true true = true
andb true false = false
andb false true = false
andb false false = false

boolToBool : bool -> Bool
boolToBool false = False
boolToBool true = True

{- ************ eq ************** -}

class eq a where
  eql : a -> a -> bool
  neql : a -> a -> bool
  neql x y = negb (eql x y)
  eql x y = negb (neql x y)
  
{- ************ list ************** -}

data list a=
  nil | cons a (list a)

isElementOf : (eq a) => list a -> a -> bool
isElementOf nil val = false
isElementOf (cons h t) val = if (boolToBool (eql h val))
  then true
  else (isElementOf t val)
  
instance (eq a) => eq (list a) where
  eql nil nil = true
  eql (cons h t) nil = false
  eql nil (cons h t) = false
  eql (cons h1 t1) (cons h2 t2) = andb (eql h1 h2) (eql t1 t2) 


{- ************ set ************** -}

data set a =
  mkSet (list a)

newSet: set a
newSet = mkSet nil

insert : (eq a) => set a -> a -> set a
insert (mkSet l)  a = if (boolToBool (isElementOf l a))
then (mkSet l)
else (mkSet (cons a l))

isListInList: (eq a) => list a -> list a -> bool
isListInList nil nil = true
isListInList nil l = true
isListInList (cons h t) nil = false
isListInList (cons h t) l = andb (isElementOf l h) (isListInList t l)

instance (eq a) => eq (set a) where
  eql (mkSet l1) (mkSet l2) = 
    andb
       (isListInList l1 l2) -- all values in l1 are in l2  
       (isListInList l2 l1) -- all values in l2 are in l1

{- ************ nat ************** -}

data nat : Type where
  Z : nat
  S : nat -> nat

instance eq nat where
  eql Z       Z     = true
  eql Z      (S m') = false
  eql (S n') Z      = false
  eql (S n') (S m') = eql n' m'


{- ************ testing ************** -}

testEql : (eq a) => String -> a -> a -> IO ()
testEql msg actual expected = 
if (boolToBool (eql actual expected)) then 
putStrLn (msg ++ ": pass") else 
putStrLn (msg ++ ": fail")


testSetEql: (eq a) => String ->  set a ->  set a -> IO ()
testSetEql msg s1 s2 = testEql msg s1 s2


{- ************ test data ************** -}

emp : set nat
emp = newSet

s1: set nat
s1 = insert emp (S Z)

{- ************ run tests ************** -}

{-
Test #2' works. It calls testSetEql, which just
delegates to testEql. Calling testEql directly
(with a non-empty set) hangs the process.

main : IO ()
main = do {
  testEql "test #1" emp emp -- this works
  -- testEql "test #2" s1 s1   -- this doesn't work
  testSetEql "test #2'" s1 s1 -- this works
}

**Comment by david-christiansen** [comment]
I updated the formatting of the example code so that Idris would parse it - hope you don't mind!

**Comment by kevinsullivan** [comment]
Thanks!

**Comment by david-christiansen** [comment]
I can also confirm that I can replicate the issue.

**Comment by edwinb** [comment]
This is a problem with the partial evaluator and overlapping definitions, which is something I forgot about when writing the evaluator. While I work out what to do about it, you can work around either with:

* Turning off the partial evaluator with --no-partial-eval
* Replacing the overlapping cases in `isListInList`, e.g.

```
isListInList nil nil = true
isListInList nil (cons x xs) = true
```

**Comment by kevinsullivan** [comment]
*Thanks*
