### ISSUE TITLE
Upgrade to new Travis infrastructure

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#2443]
Travis has new infrastructure and complains that we're on the old one. Upgrading to the new one would get us the ability to cache dependencies and faster built startup generally, so I think it's worth doing sooner rather than later.

The guide on how to do it is at: http://docs.travis-ci.com/user/migrating-from-legacy/

**Comment by 4e6** [comment]
I had some experience of migration to the new Travis infrastructure recently. I can take this one.

**Comment by 4e6** [comment]
currently waiting for travis-ci/travis-ci#4478 merged
