### ISSUE TITLE
Feature Request: Same type multiple record fields in one line

### ISSUE THREAD

**Issue by xged** [idris-lang/Idris-dev#2460]
One would like to write:

    record Person where
      constructor MkPerson
      name, surname, middleName : String

In Haskell: `data Person = Person {name, surname, middleName :: String}`

**Comment by david-christiansen** [comment]
This seems like a nice extension to me. Want me to point you to the right spot in the Idris source to implement it?

**Comment by xged** [comment]
I am leaving the implementation to somebody with a higher level of skill then mine ;)

**Comment by david-christiansen** [comment]
Fair enough :-)

**Comment by benjamin-hodgson** [comment]
I have opened a pull request (#2470) with this feature in it :smile:

**Comment by david-christiansen** [comment]
#2470 fixed this. Awesome!
