### ISSUE TITLE
Function Request: `Prelude.String.unlines : List String -> String`

### ISSUE THREAD

**Issue by xged** [idris-lang/Idris-dev#2464]
Idris *Prelude.String* has `words`, `unwords`, `lines`, but not `unlines`. Haskell *Prelude* has `unlines`.

    unlines : List String -> String
    unlines Nil = ""
    unlines (l::Nil) = l
    unlines (l::ls) = pack (foldl addLine (unpack l) (map unpack ls) where
      addLine : List Char -> List Char -> List Char
      addLine w s = w ++ ('\n' :: s)

**Comment by jfdm** [comment]
Thanks for the function request. As a matter of fact we welcome contributions to the library in the form of Pull Requests. So if you feel up to it, you can always try contributing your unlines implementation.

**Comment by xged** [comment]
#2472
