### ISSUE TITLE
Conventions: Column limit?

### ISSUE THREAD

**Issue by xged** [idris-lang/Idris-dev#2474]
What is *Idris-dev* convention for column limit (fingers crossed - 120)?

**Comment by david-christiansen** [comment]
We haven't yet made any kind of official policy on this. We've taken it case-by-case so far.

**Comment by xged** [comment]
I will leave the issue open for an official policy to be made then :-)

**Comment by edwinb** [comment]
I aim at 80 but don't always manage it and I don't see why 120 is unreasonable. I don't feel the need for an official policy on this, though.
