### ISSUE TITLE
Problems with colors of syntax highlighting (dark theme)

### ISSUE THREAD

**Issue by xged** [idris-lang/Idris-dev#2475]
1. Too dark (especially green, blue).
2. White (vanilla light) color should be the predominant one (switch green with white?)
3. Colors, which represents closely related semantic structures (green and purple, red and teal) should be related too.

**Comment by ahmadsalim** [comment]
Which editor are you using?

**Comment by xged** [comment]
Spacemacs 0.104.0

**Comment by jfdm** [comment]
The fonts used for semantic highlighting are customisable. There are a series of font faces, I forget their specific names, that you can customise. I think the naming convention is: `idris-semantic-<thing>-face`.

**Comment by xged** [comment]
Aren't there predefined alternative sets of font faces?

**Comment by jfdm** [comment]
AFAIK, the set of faces currently used most Idris tooling wrt to semantic highlighting are based on *Connor's* colours and that is it. There is no support for themes for the semantic highlighting in either of the editor modes, nor the REPL. Whether, 'themes' is something that should be built into Idris or the editor modes I do not know, I am certainly not against it.

**Comment by david-christiansen** [comment]
There is support for themes both in Emacs and in the console REPL. In Emacs, you can use the standard Emacs color-theme features. For example, I use the `leuven` theme, but I have replaced its font-lock defaults for Idris and Agda. I have this in my `init.el`:
```
(load-theme 'idris-leuven-theme t)
```
and, in my `.emacs.d`:
```
(deftheme idris-leuven-theme
  "Idris-mode colors compatible with Leuven")

(custom-theme-set-faces
 'idris-leuven-theme
 '(idris-equals-face ((t (:foreground "black" :weight semi-bold))))
 '(idris-colon-face ((t (:foreground "black" :weight semi-bold))))
 '(idris-hole-face ((t (:underline (:color "#006DAF" :style wave) :slant italic))))
 '(idris-operator-face ((t (:foreground "black" :weight semi-bold))))
 '(idris-repl-output-face ((t (:foreground "#606060"))))
 '(idris-semantic-function-face ((t (:foreground "darkgreen"))))
 '(idris-semantic-implicit-face ((t (:slant italic))))
 '(idris-semantic-data-face ((t (:foreground "red3"))))
 '(idris-keyword-face ((t (:foreground "black" :weight semi-bold))))
 '(idris-directive-face ((t (:foreground "dim gray"))))
 '(idris-directive-face ((t (:foreground "dim gray" :slant italic))))
 '(idris-directive-face ((t (:foreground "dim gray"))))
 '(idris-inline-doc-face ((t (:foreground "dim gray"))))
 '(idris-parameter-face ((t (:inherit idris-semantic-bound-face))))
 '(idris-module-face ((t (:inherit idris-semantic-module-face))))
 '(idris-info-title-face ((t (:family "Sans Serif" :height 1.8 :weight bold :foreground "cornflower blue"))))
 '(idris-quasiquotation-face ((t (:background "light gray"))))
 '(idris-antiquotation-face ((t (:background "white" :box "light gray"))))
 '(agda2-highlight-primitive-type-face ((t (:inherit idris-semantic-type-face))))
 '(agda2-highlight-inductive-constructor-face ((t (:inherit idris-semantic-data-face))))
 '(agda2-highlight-primitive-face ((t (:inherit idris-semantic-function-face))))
 '(agda2-highlight-function-face ((t (:inherit idris-semantic-function-face))))
 '(agda2-highlight-postulate-face ((t (:inherit idris-semantic-function-face))))
 '(agda2-highlight-bound-variable-face ((t (:inherit idris-semantic-bound-face))))
 '(agda2-highlight-keyword-face ((t (:inherit idris-keyword-face))))
 '(agda2-highlight-module-face ((t (:inherit idris-semantic-module-face)))))

(provide-theme 'idris-leuven-theme)
```

This is standard Emacs usage - nothing is Idris-specific about it. I encourage theme authors to integrate support for Idris's faces - they can't really inherit from `font-lock`, because the `font-lock` faces aren't semantic. The ones that do have corresponding `font-lock` faces do inherit.

In the REPL, you can use an init script to set the colors. My terminal has proper support for italics, so I don't need that underlining hack that I put in the default theme for less-good terminals. Here's my `~/.idris/repl/init`:
```
:color prompt bold italic black
:color boundvar dull magenta
:color implicit dull magenta italic
```

**Comment by david-christiansen** [comment]
Given that the particular theme suggested by @xged is not going to be implemented, and that both the editor modes and the REPL already support custom themes, and that the REPL themes are documented at http://docs.idris-lang.org/en/latest/reference/repl.html, I'm going to close this issue.

**Comment by xged** [comment]
@david-christiansen Thanks for the code snippet, it will help.

**Comment by david-christiansen** [comment]
@xged you're welcome! Let me know if these features aren't sufficient.

**Comment by xged** [comment]
@david-christiansen `idris-directive-face` repeated 3 times.

**Comment by david-christiansen** [comment]
Thanks - that's why this is just in my `.emacs.d` as something I load - not exactly highly tested or designed for public consumption :)
