### ISSUE TITLE
%hide: inconsistent behavior?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2483]
The following program does not type check
```
> module HideA
> import Data.Sign
> %hide sign
> data Lala : Type
> public sign : Lala -> Sign
> f  : Lala -> Lala
```
```
> module HideB
> import Data.Sign
> import HideA
> data Lula : Type where
>   MkLula : (l : Lala) -> Lula
> fromLala : Lala -> Lula
> fromLala = MkLula . f
```
When type checking `HideB`, one gets 
```
- + Errors (1)
 `-- HideB.lidr line 7 col 9:
     When checking right hand side of fromLala:
     When checking an application of function Prelude.Basics..:
             No such variable f
```
One can make the program type check in different ways. One is to declare `sign` in `HideA` not to be public. This makes `HideB` type check but also prevents 'HideA.sign' to be accessible in modules that import 'HideA', as one would expect.

Another way to make `HideB` type check is to declare `HideA.f` to be public. In fact, it turns out that all names declared after `public sign : Lala -> Sign` in `HideA` have to be declared `public` in order to be accessible in modules that import `HideA`. It also turns out that the name we actually hide does not really matter:
```
> module HideA
> import Data.Sign
> %hide plus
> data Lala : Type
> public n : Nat
> sign : Lala -> Sign
> f  : Lala -> Lala
```
effectively makes both `sign` and `f` inaccessible in modules that import `HideA`. This behavior seems inconsistent to me or at least quite unexpected.

**Comment by NobbZ** [comment]
I don't know about hide, but as soon as you have any visibility modifier in
your module, everything you don't mark otherwise is private by default,
that is conform with what the manual says.

nicolabotta <notifications@github.com> schrieb am Di., 28.07.2015, 20:32:

**Comment by nicolabotta** [comment]
Thanks NobbZ! Are you saying that if a name in a module is declared to be public, then all other module names become private by default? This would be a bit funny. What would then happen if one declares one name to be public and another one to be private? Do the unqualified names become private or public? I have to admit that I have never used `public` or `private` qualifiers systematically, I have used `%hide` very rarely and I find the interactions between these constructs in the example above quite puzzling.

**Comment by NobbZ** [comment]
As soon as you use ANY qualifier, everything else gets private. That's what
the docs say. But AFAIR there was some pragmatic available to set default
accessibility.

nicolabotta <notifications@github.com> schrieb am Di., 28.07.2015, 21:56:

**Comment by nicolabotta** [comment]
Yes, I see the rule but I do not understand the rationale behind it. Is such behavior consistent with that of other qualifiers? Does a `partial` qualification of a function in a module make every other function automatically qualified as `total`? 

I think there are a number of situations in which one wants to replace some standard implementation with another implementation. For instance something like 
```
module GCD

%hide gcd

public gcd : Nat -> Nat -> Nat
```
Here the `public` keyword is necessary to make the new implementation available to the modules that import `GCD`. The `%hide gcd` is useful if one want to avoid having to explicitely resolve conflicts between `GCD.gcd` and `Prelude.Nat.gcd` in the `GCD` module itself (e.g., in proving properties of the new implementation). 

But I do not see any obvious reason while making `GCD.gcd` public should imply all other names in `GCD` to become private by default. This seems to me an annoying violation of a principle of local influence: qualifying a name (no matter whether with `public`, `total`, `auto`, etc.) should not have a direct effect on other names. Of course, a `partial` qualification of a `lala` function can modify the behavior of functions that "use" `lala`. But this is an indirect effect which can be perfectly understood and justified on the basis of the relationship between the two functions.

**Comment by jfdm** [comment]
Although, the behaviour of accessibility modifiers is [documented](https://idris.readthedocs.org/en/latest/tutorial/modules.html#export-modifiers), there has nonetheless been some discussion about their default behaviour. See Issue #1879. From what I gather the default behaviour is open for 'reasonable' modification, it is just no one has attempted to do so.

**Comment by nicolabotta** [comment]
Right, this post reiterates #1879, thanks for spotting and sorry for opening a fresh issue! 

On the other hand, the post supports the feature request implicit in #1879 with a new argument against the current implementation. I think that the 
```
module GCD
%hide gcd
public gcd : Nat -> Nat -> Nat
```
pattern is quite common and speaks against the "If any definition is given an export modifier, then all names with no modifier are assumed to be private." rule. As I said, I do not grasp the rationale for this rule and it seems to me that the language would improve both in usability and understandability if the rule would be simply dropped. Of course, I might be missing something important.

As far as the default visibility behavior is concerned, I do not really mind whether this is `private`, `abstract` or `public` as long as it can be set in a module via a `%default` pragma.

**Comment by Melvar** [comment]
The pragma for default visibility is `%access`, not `%default`.

**Comment by nicolabotta** [comment]
> The pragma for default visibility is %access, not %default.

Thanks Melvar, it thus seems that the idiom for making all names but `lala` accessible is
```
%access public
%hide lala
```
which is quite ugly considering that `public` is the default visibility property of module member names. On the top of this, we have that 
```
%access private
```
and
```
%hide lala
```
appear to have the same effect on the visibility properties of module member names! What I really would like to have is that directives like 
```
%hide lala
```
```
private lala
```
```
public lala
```
etc. set the visibility properties of `lala` without any side effect on the visibility of other names. Isn't this what anyone would expect?

**Comment by ahmadsalim** [comment]
I believe that things are private by default now after the introduction of the new visiblity modifiers, so this is expected behaviour.
