### ISSUE TITLE
Compiled Code Seg Faulting

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#2493]
The following code snippet will cause a seg fault in compiled code but will function will execute happily in the REPL:

```idris
doThing : List Nat -> List (v,Nat) -> List v
doThing is g = foldr (\(v,i),res => if elem i is then v::res else res) List.Nil g

namespace Main

  main : IO ()
  main = printLn $ doThing [1,2,3] [("as",1),("asasasas",4)]
```

The stack trace using `lldb` is:
```
$ lldb a.out
(lldb) target create "a.out"
Current executable set to 'a.out' (x86_64).
(lldb) r
Process 91546 launched: '/Users/jfdm/Desktop/idris-failings/a.out' (x86_64)
Process 91546 stopped
* thread #1: tid = 0x161637, 0x000000010000357c a.out`_idris_Prelude_46_List_46_elemBy + 188, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
    frame #0: 0x000000010000357c a.out`_idris_Prelude_46_List_46_elemBy + 188
a.out`_idris_Prelude_46_List_46_elemBy:
->  0x10000357c <+188>: movl   0x8(%rsi), %eax
    0x10000357f <+191>: andl   %r15d, %eax
    0x100003582 <+194>: movl   $0x4, %edx
    0x100003587 <+199>: cmpl   $0x100, %eax
```

**Comment by jfdm** [comment]
As an update, if I switch to using a `foldl` rather than a `foldr` the function works as expected one compiled.

**Comment by melted** [comment]
Looks like a miscompile to C, the next step up in the stackframe:
```
void _idris_Main_46__123_doThing2_125_(VM* vm, VAL* oldbase) {
    INITFRAME;
    RESERVE(3);
    ADDTOP(3);
    LOC(3) = NULL;
    allocCon(REG1, vm, 65632, 0, 0);
    
    LOC(4) = REG1;
    LOC(5) = NULL;
    RESERVE(4);
    TOP(0) = LOC(3);
    TOP(1) = LOC(4);
    TOP(2) = LOC(0);
    TOP(3) = LOC(5);
    STOREOLD;
    BASETOP(0);
    ADDTOP(4);
    CALL(_idris_Prelude_46_List_46_elemBy);
```
TOP(3) becomes LOC(3) in the BASETOP macro, but TOP(3) was set to LOC(5) which was set to null.

So it crashes when it gets to elemBy and tries to deref it:
```
void _idris_Prelude_46_List_46_elemBy(VM* vm, VAL* oldbase) {
    INITFRAME;
    RESERVE(4);
    ADDTOP(4);
    if (CTAG(LOC(3)) == 1) {
        PROJECT(vm, LOC(3), 4, 2);
        RESERVE(2);
        TOP(0) = LOC(1);
        TOP(1) = LOC(2);
```

If you don't like trawling through disassembly in lldb, I added `--cg-args` as an idris option recently, so it's easy to pass `-g` to build a debug version.

**Comment by edwinb** [comment]
This looks very like an issue I encountered recently, with a similar
result (i.e. a segfault). One particular quirk of elaboration (with
lambdas including both patterns and ordinary variables) seems to lead to
erasure thinking something is unused when it isn't.

The symptom can be fixed quite easily, by making that quirk of
elaboration not happen, but of course it would be much better to get to
the bottom of what the erasure problem is (since that itself is a bit
worrying). I know @ziman had a look at it, but I don't know if he worked
out what was going wrong...

**Comment by edwinb** [comment]
This appears to be fixed, but the commit which referenced it didn't automatically close it, so I'll do that now.
