### ISSUE TITLE
Please update dependency constraints

### ISSUE THREAD

**Issue by peti** [idris-lang/Idris-dev#2500]
According to http://packdeps.haskellers.com/feed?needle=idris, idris doesn't support recent versions of several important packages, which makes it hard to compile the package in a distribution like NixOS. Most constraints can be bumped without any problem, only `zlib` actually needs code changes to support the current 0.6.x version.

**Comment by david-christiansen** [comment]
The fastest way to make this happen is to submit a pull request with the updated bounds! I'll be in a position to do the work myself in a few days, but in the meantime, you can make it faster by sending in what it sounds like you've already checked yourself.

**Comment by peti** [comment]
I'm not a user of idris myself. I'm just trying to fix the build in NixOS. Because of this, I'd rather not write any patches myself -- I don't feel qualified to judge whether I'm doing the right thing or not.

**Comment by david-christiansen** [comment]
Fair enough!  Though Travis will catch introduced problems with bumped upper bounds, so it should be pretty straightforward, and whoever looks at the pull request does have a chance to check it!

**Comment by david-christiansen** [comment]
Hmm, it looks like most of these are already bumped in master. I'll do the rest, but otherwise NixOS will have to wait for the next release. I don't imagine that it will be a very long time coming.

**Comment by jfdm** [comment]
Is this issue still active or can it be closed? I think it is resolved and will wait until the morrow to close it? Unless anyone thinks otherwise.

**Comment by jfdm** [comment]
tis the morrow.
