### ISSUE TITLE
add idris to Stackage

### ISSUE THREAD

**Issue by juhp** [idris-lang/Idris-dev#2501]
I would like to suggest adding idris to Stackage.
(If it can be done this week it can even be a part of lts-3 even. :-)

The process for adding a package is pretty easy (basically just file a PR against stackage):
see the Package Authors section on http://www.stackage.org/.

**Comment by david-christiansen** [comment]
I was working in that direction at one point, and I think it would be nice to get there. I'm a bit worried about the response times that they demand in case of a breakage though - it makes going on vacation a bit tricky. Also, if I remember correctly, they discourage or forbid upper bounds, but having upper bounds has kept us much more sane!

**Comment by juhp** [comment]
> I'm a bit worried about the response times that they demand in case of a breakage though

Not sure about this but often either a workaround can be put in place (upperbound for your package) or it can be temporarily excluded from Nightly if it is blocking important updates in.
Once it is in LTS Haskell I don't think there should be much problem unless there are really strict version bounds in idris.

> Also, if I remember correctly, they discourage or forbid upper bounds, but having upper bounds has kept us much more sane!

Upper bounds are certainly allowed but if they conflict with Stackage this will indeed be a problem.

**Comment by jfdm** [comment]
There are many of us who would like to get Idris on stackage, specifically building against the LTS Haskell series. There have been several discussions about migrating to stackage, specifically #2135 and #2427. However, there are some aspects that needs discussing as to how this will affect our development set up, support for multiple GHCs, and distribution.

Nonetheless, I think it is safe to say that we would like to get there just want to be sure.

**Comment by juhp** [comment]
idris builds now in Stackage Nightly, so it is possible to add it now. :)
By opening a PR against fpco/stackage.

But if you prefer I can also be the Stackage maintainer.

**Comment by ahmadsalim** [comment]
So it seems that Idris is on Stackage now, so I will close this issue.
Thanks @juhp for adding it.

Regarding maintainership, I am not sure who decides that, but I guess it is fine as long as no one complains.

**Comment by juhp** [comment]
Cool, I am more than happy for someone upstream to take the package in Stackage, but it is also no problem for me to keep it for now. :)
