### ISSUE TITLE
IDE server exits rather than returning error when irrefutable pattern exception encountered

### ISSUE THREAD

**Issue by jeremy-w** [idris-lang/Idris-dev#2512]
## Summary
Clients of an IDE-mode Idris would expect the server to keep running in the face of bogus file input and simply return an error to show to the user. Instead, the server process will exit.

## Configuration
Idris version 0.9.18 (installed via Homebrew)

ProductName:	Mac OS X
ProductVersion:	10.10.4
BuildVersion:	14E46

## Steps to reproduce
1. Write this to a file:
```
let T = 3
using (G: T)
```
2. To demonstrate the idris executable exiting on attempting to parse, run it: `idris -c file.idr`
2. To demonstrate the server exiting:

```
~/D/D/idris> idris --ide-mode-socket &                                                                                                   [1]
64645
~/D/D/idris> echo "00004b((:load-file \"$PWD/crash_me.idr\") 1)" | nc 0.0.0.0 64645                                                      [1]
000018(:protocol-version 1 0)
idris: src/Idris/ParseHelpers.hs:429:20-46: Irrefutable pattern failed for pattern (x : xs)

'idris --ide-mode-socket &' has ended
```

Note that the `00004b` bit is the length of the following string; it'll vary depending on the path to your file. You can calculate it at the command-line using:

```
dc -e "16 o $(echo ((:load-file \"$FILE_PATH_HERE\") 1) | wc -c) p"
```

then prefix it with zeroes so that it becomes a 6-character length field.

## Workaround

Currently, I have to relaunch the entire Atom editor, since the package does not expect the server process to terminate: [idris-hackers/atom-language-idris:#51](https://github.com/idris-hackers/atom-language-idris/issues/51). It's possible to modify the clients to handle the termination case; I don't know that the clients will be able to provide the error message to the user, though.

**Comment by jeremy-w** [comment]
Looks like removing the `let` at the start of the `let Env…` line prevents the crash. It instead reports that `Env` is a mess, which sounds accurate:

```
Type checking ./interpreter.idr
interpreter.idr:12:1:No type declaration for Main.Env
interpreter.idr:14:10:When elaborating type of Main.Expr:
No such variable Env
```

**Comment by jeremy-w** [comment]
Found a minimal input to reproduce the error:

```idris
let T = 3
using (G: T)
```

**Comment by jfdm** [comment]
yeah that is straight up invalid syntax as far as I am aware. Let expressions are only allow on the RHS of an equation, and possibly also a function declaration. If you are trying to do a type synonyms they are declared as follows:

```Idris
FileName : Type
FileName = String
```

Remember types are first class. To alias a type you can create a function to give the alias the type you want. So to provide an alias named `Env` you can do it as follows:

```Idris
Env : Type
Env = Vect n Ty
```
However, this alias 'hides' for want of a better term, the length of the `Vect` from the developer. A better alias could be:

``` Idris
Env : Nat -> Type 
Env n = Vect n Ty
```

**Comment by jeremy-w** [comment]
I eventually worked that out. :)

But this remains an issue in practice because it causes the server REPL to exit rather than just returning an error to the client. I'll see if I can provide simple steps to repro that scenario, since that's what really got me.

**Comment by david-christiansen** [comment]
It's not invalid syntax - it's the syntax for PCaf. It appeared a while
back to little fanfare, and I haven't seen anyone use it, but it is there.

/D

**Comment by jeremy-w** [comment]
Interesting! I'm not clear how a constant applicative form ([parsed here](https://github.com/idris-lang/Idris-dev/blob/7a2dc7b150219b5d83aa39371af787f0c636f5cf/src/Idris/Parser.hs#L828-L842)) differs from the version without the `let`.

Is it reasonable to expect the idris process wouldn't exit on oddball input, but instead print an error? Or is this not-a-bug, and clients just need to handle that the REPL process might exit on loading a file?

**Comment by david-christiansen** [comment]
Well, the Idris process shouldn't be crashing. I don't think we can expect that it will always recover from a mistake that leads to a crash - better to fix the crash. In the meantime, the editor should see that the server exited and restart it. That's probably better than trying to have it diagnose its own state in the middle of an invalid operation and attempt to recover.

**Comment by david-christiansen** [comment]
It looks like the code in questions is exercising a confusion in the indentation parser, rather than being anything with `PCAF` specifically. I'll poke onward a bit.

**Comment by david-christiansen** [comment]
OK, it turns out that the parser for `PCAF` was popping the indent stack without having pushed. This has been ameliorated now. Additionally, while I still think that crashing here would be reasonable, because it's obviously an Idris bug, it says more about why the error occurred, which will make it more fixable in the future, should it happen.
