### ISSUE TITLE
zipWith and friends in Prelude.List

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris-dev#2517]
These currently require length proofs. I think this is a bad idea, because they have perfectly reasonable (and total) definitions without balanced lengths - it's often useful to take the length of the smaller list. If you need length information for lists, that's what Vect is for after all.

So I propose removing the proof requirements. Does anyone actually use these in their current form? 

I do, however, think it's worth retaining proofs where they help preserve totality (e.g. in head and tail).

**Comment by david-christiansen** [comment]
I agree that this makes more sense. The other option would be the "F# semantics" and crash when the lengths are not the same, but that would make them useless in types, so I think that the truncating behavior is better.
