### ISSUE TITLE
Possibly an internal error in quasi-quotations

### ISSUE THREAD

**Issue by shayan-najd** [idris-lang/Idris-dev#2521]
The following does not work:
~~~
import Language.Reflection.Elab

main : IO ()
main = do tm <- getLine
          let s : String = tm
          let r : Raw = quote s
          let x : Raw = `(~r)
          printLn (%runElab (do fill x
                                solve))
 ~~~

Idris 0.9.18.1-git:ba3fab0 REPL returns the following error message:

 >  INTERNAL ERROR: Unknown reflection constant: (Language.Reflection.Str,tm)

**Comment by shayan-najd** [comment]
CC to @david-christiansen

**Comment by shayan-najd** [comment]
I have tried to trace the execution to find the issue. I didn't go far, but you may find the following helpful.

In [Reflection.hs](https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/Reflection.hs), it first calls [`reifyRaw`](https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/Reflection.hs#L203), then [`reifyRawApp`](https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/Reflection.hs#L221), [`reifyTTConst`](https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/Reflection.hs#L330), and fails by calling [`reifyTTConstApp`](https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/Reflection.hs#L354). The problem seems to be that `reifyTTConstApp` does not expect its second input to be `P Bound tm (Constant String)` (where `tm` is a name).

I do expect it to fail in a system with stage-restriction, but I don't quite understand the details here.

**Comment by david-christiansen** [comment]
This isn't a good error message, but other than that I think that what it's doing is correct. I'm not sure why you construct `x`, as quoting and immediately antiquoting something doesn't really do anything, so it should just be `r`. 

What's happening here is that `%runElab` executes at compile time, while IO actions run at run time. At compile time, the string that the user will type in the future is clearly unknown, so it's just a variable. The reflection code is attempting to reify a variable as a string constant, and failing.

**Comment by david-christiansen** [comment]
New error message:
```
Can't reify the variable tm as a constant, because its value is not statically known.
```

**Comment by shayan-najd** [comment]
> This isn't a good error message, but other than that I think that what it's doing is correct. I'm not sure
> why you construct x, as quoting and immediately antiquoting something doesn't really do anything, so it 
> should just be r.

Right, it was not needed. 

> What's happening here is that %runElab executes at compile time, while IO actions run at run time.

Yep, I have constructed this example specifically to understand how stage restriction is implemented in Idris. Then I have faced the error message that you have just fixed.

The new error message looks good to me, and I guess that concludes this issue.

**Comment by david-christiansen** [comment]
It would have been closed when the Elab branch got merged in next :-)
