### ISSUE TITLE
javascript generated files end in .exe

### ISSUE THREAD

**Issue by pmwhite** [idris-lang/Idris-dev#2523]
So I was having trouble getting started with ffi and such on this thread(https://groups.google.com/forum/#!topic/idris-lang/DZA1h9zmTpI) of the google group.

Here is my ipkg file contents:

    package test

    -- Test
    -- by 

    opts = "--codegen javascript"
    sourcedir = src
    modules = Test
    main = Test
    executable = test.js

That's it!  When I build it, it generates a file called test.js.exe.  The file does indeed contains javascript; it's only the file extension.

I'm using idris 0.9.18 and windows 8.1

**Comment by melted** [comment]
Ok, looks like the Package parser appends ".exe" unnecessarily. Easy to fix.
