### ISSUE TITLE
Typechecker takes an unreasonably long time with rank-n qualification

### ISSUE THREAD

**Issue by japesinator** [idris-lang/Idris-dev#2529]
The code linked [here](https://gist.github.com/japesinator/e2f066112c920872124b), when compiled, will take an indefinite amount of time and effort to do so. The problem is in `fi` in `forwards`, specifically the application of `specialize`

**Comment by edwinb** [comment]
Does it compile eventually? I just tried this, and get an immediate response of:

Type checking ./iso.idr
iso.idr:25:6:When checking right hand side of Main.forwards, fi:
Can't resolve type class Profunctor (Forgotten a)
iso.idr:34:6:
When checking right hand side of Main.backwards, bi:
Can't resolve type class Profunctor Tagged

**Comment by ahmadsalim** [comment]
I also get the same error as @edwinb. 
I will close the issue, but if you have an updated version that still fails we can reopen this.
