### ISSUE TITLE
Universe inconsistency

### ISSUE THREAD

**Issue by raichoo** [idris-lang/Idris-dev#2533]
module Main

    data Yoneda : (f : Type -> Type) -> (a : Type) -> Type where
      Yon : ({b : Type} -> (a -> b) -> f b) -> Yoneda f a

    instance Functor f => Functor (Yoneda f) where
      map h (Yon k) = Yon (flip map (k h))

    liftY : Functor f => f a -> Yoneda f a
    liftY h = Yon (flip map h)

    test : Yoneda List Integer
    test = map (*2) (liftY [1..10])

Yields:

    Type checking ./yoneda.idr
    yoneda.idr:16:1:Universe inconsistency.
            Working on: d8
            Old domain: (4,4)
            New domain: (4,3)
            Involved constraints:
                    ConstraintFC {uconstraint = d8 < e8, ufc = yoneda.idr:16:1}
                    ConstraintFC {uconstraint = d8 < e8, ufc = yoneda.idr:16:1}
                    ConstraintFC {uconstraint = c8 <= d8, ufc = yoneda.idr:16:1}
                    ConstraintFC {uconstraint = f8 <= d8, ufc = yoneda.idr:16:1}

Same code typechecks fine in Haskell.

**Comment by jfdm** [comment]
@raichoo Just so you are aware, similar bug reports have been filled, and @ozgurakgun worked out that incorrect data is being passed to the constraint solver. I think @Melvar worked on trying to diagnose them, but that is all I think we know,

**Comment by raichoo** [comment]
Thanks for the Head-up!

**Comment by Melvar** [comment]
The inconsistency that I had reported has been fixed; perhaps test this again now?

**Comment by edwinb** [comment]
I just tried it, it's fine now. Looking at the code, it is consistent with the other sorts of things that were failing surprisingly.
