### ISSUE TITLE
[Doc] How to update an Idris Developement version in a sandbox?

### ISSUE THREAD

**Issue by xged** [idris-lang/Idris-dev#2534]
I know how to [Installing-an-Idris-Development-version-in-a-sandbox](https://github.com/idris-lang/Idris-dev/wiki/Installing-an-Idris-Development-version-in-a-sandbox), but not how to keep it up to date.

**Comment by NobbZ** [comment]
Quick way which may destroy your environment:
1. git pull upstream master
2. cabal install --dependencies-only
3. make

You might omit step 2 here.

Safer way, which takes a long time:

1. rm -rf .cabal-sandbox
2. git pull upstream master
3. Start following the linked instructions, right after cding into the
repo, beginning with `cabal sandbox init`

Julius Gedvilas <notifications@github.com> schrieb am Mi., 19. Aug. 2015 um
09:59 Uhr:

**Comment by suhr** [comment]
You can also use [stack](https://github.com/commercialhaskell/stack) to avoid cabal-install related issues.

**Comment by jfdm** [comment]
Dear all;

I have updated the wiki page (which is for cabal sandboxes) with hints and tips at the bottom. 

Hopefully this addresses the issue. If not it can be reopened.

Documentation on using stack is in [INSTALL.md](https://github.com/idris-lang/Idris-dev/blob/master/INSTALL.md). This information about cabal sandboxes may be added to that in the near future.
