### ISSUE TITLE
Bindings generator

### ISSUE THREAD

**Issue by suhr** [idris-lang/Idris-dev#2542]
Generate bindings stub from C header files.

See also: https://github.com/crabtw/rust-bindgen

**Comment by david-christiansen** [comment]
Is this a compiler feature request? A suggestion for a separate project? Can you give some more details about what you might want to use such a feature or separate system for, and what you think makes a good or bad one?

**Comment by suhr** [comment]
> A suggestion for a separate project?

Yes. Bindgen simplifies bindings writing by generating FFI glue code, so after that only writing a wrapper over it is required. By the way, Haskell have things like cgen.

**Comment by david-christiansen** [comment]
Since this isn't really an issue in Idris _per se_, I'm going to close this issue.  Please consider writing a bit about it on the [wiki page that suggests projects](https://github.com/idris-lang/Idris-dev/wiki/Mini-Projects).
