### ISSUE TITLE
"Can't match on (0)" error when pattern matching on Bits8

### ISSUE THREAD

**Issue by cantora** [idris-lang/Idris-dev#2559]
I'm seeing a mysterious error when I try to pattern match on a Bits8 type. The code below triggers the issue.

```
data Label = LblA | LblB

instance Show Label where
  show LblA = "LblA"
  show LblB = "LblB"

foo : Bits8 -> Maybe Label
foo 0 = Just LblA
foo 1 = Just LblB
foo _ = Nothing

run : String -> IO ()
run ""  = putStrLn "input string was empty"
run str = putStrLn $ show $ foo $ prim__truncInt_B8 (ord (strHead str))

main : IO ()
main = do
  str <- getLine
  run str
```

The compiler returns the error when trying to compile the code above.
```
$> idris -v
0.9.18.1
$> idris -o CantMatchOn0 CantMatchOn0.idr
Can't match on (0)
```

**Comment by edwinb** [comment]
I've just tried this in master and it works fine. Not sure what has changed that would fix it, but maybe it's worth a go with the latest release?

**Comment by cantora** [comment]
I'm still seeing this issue even on 0.9.19. I used `cabal update && cabal install idris` for installation.

Let me know if there's any other information I should provide.

**Comment by melted** [comment]
It works when loading in REPL; not when compiling to C or JS.

**Comment by edwinb** [comment]
Yes, I read this one a bit fast, sorry. It's almost certainly just that pattern matching on Bits constants isn't fully implemented. If anyone feels like poking around the C code generator before I get around to it, it's probably a quick fix...

**Comment by melted** [comment]
I'll take a look at it.
