### ISSUE TITLE
Partial function / pattern match segfault

### ISSUE THREAD

**Issue by davidwlewis** [idris-lang/Idris-dev#2562]
Ran across some quirky pattern matching behaviour. The following code compiles and segfaults:

    module Main
    
    import Data.Vect
    
    fn : (n : Nat ** Vect n Bool) -> Bool
    fn (S Z ** [a]) = a
    
    main : IO ()
    main = do printLn $ fn (0 ** [])

**Comment by jfdm** [comment]
@davidwlewis Thanks for the issue, I have yet had time to look at the issue in depth, but the function `fn` is not total. By default Idris runs with weekend totality constraints that functions are partial. This can be roughly translated as: programs may not terminate, and programs may have missing cases.

Compiling and running your code (against Idris head) results in the run time error:

```
*** Issue.idr:5:1:unmatched case in Issue.fn ***
```

If future if you use the `%default total` directive, or annotating the function with  `covering` you can detect unmatched cases. Further the compiler flags: `--warnpartial` will warn you about partial functions that have not been declared in a total setting.

Of note, it would be handy when submitting an issue if you could report the version of Idris you are using, and what the segfault issue you experience actually is. Personally, the above error is not really a segfault but more of a caught runtime exception.

Cheers.

**Comment by davidwlewis** [comment]
Thanks for the response. This behaviour was observed using af79c58, which is a few weeks old. I just updated to head and the unmatched case is reported as you say.

For further context: I understand that the function is partial. This program should obviously fail, but the manner in which it fails is important. The segmentation fault was the result of trying to index into the array (to extract the term 'a') which should not occur with the supplied argument.
