### ISSUE TITLE
Error message about type class `Nil`

### ISSUE THREAD

**Issue by yfcai** [idris-lang/Idris-dev#2564]
Suppose a file `nil.idr` has the following content.

```Idris
class Nil a where {}

bug : Nil Int => Int
bug = 0
```

Calling `bug` on the 0.9.18.1 REPL produces the message
```Idris
Idris> :l nil.idr
*nil> bug
Can't resolve type class []
```
whereas one would expect something along the line of `Can't resolve type class Nil Int`.

**Comment by ahmadsalim** [comment]
It type checks fine now.
