### ISSUE TITLE
Scoped implicits break unification

### ISSUE THREAD

**Issue by mietek** [idris-lang/Idris-dev#2565]
There’s an issue with Idris 0.9.18.1 in which introducing a datatype wrapper with scoped implicits appears to prevent unification.

```
PHOASProblem.idr:41:15:No such variable sigp
```

* Complete file: [PHOASProblem.idr](https://gist.github.com/mietek/9ee6c87a967f4093604c)
* `%unifyLog` output for the working `Example`: [Example.log](https://gist.github.com/mietek/22012f305f991bb9d83a)
* `%unifyLog` output for the non-working `BrokenExample`: [BrokenExample.log](https://gist.github.com/mietek/3058ada7e984c9585779)

The following code is a simplified portion of a formalisation of classical logic, using [parametric higher-order abstract syntax](http://adam.chlipala.net/cpdt/html/Hoas.html).

---
```idris
module PHOASProblem

data Value : Type where
  unit : Value

infixr 5 |>

data Formula : Type where
  (|>)   : Formula -> Formula -> Formula
  FORALL : (Value -> Formula) -> Formula
  EXISTS : (Value -> Formula) -> Formula
  BOTTOM : Formula

NOT : Formula -> Formula
NOT a = a |> BOTTOM

infixl 5 <|

data Theorem : (Value -> Type) -> (Formula -> Type) -> Formula -> Type where
  hyp  : hs a -> Theorem vs hs a
  lam  : (hs a -> Theorem vs hs b) -> Theorem vs hs (a |> b)
  (<|) : Theorem vs hs (a |> b) -> Theorem vs hs a -> Theorem vs hs b
  pi   : ({x : Value} -> vs x -> Theorem vs hs (pip x)) -> Theorem vs hs (FORALL pip)
  sig  : vs x -> Theorem vs hs (sigp x) -> Theorem vs hs (EXISTS sigp)
  efq  : (hs (NOT a) -> Theorem vs hs BOTTOM) -> Theorem vs hs a
```

This works:
```idris
Example : {p : Value -> Formula} -> Theorem vs hs
  (NOT (FORALL (\x => NOT (p x))) |> EXISTS p)
Example =
  lam (\w =>
    efq (\u =>
      hyp w <| (pi (\x =>
                  lam (\v =>
                    hyp u <| (sig x (hyp v)))))))
```

The two parameters to `Theorem` are not user-serviceable, and should be encapsulated away.  `BrokenTheorem` introduces encapsulation (and breakage):
```idris
BrokenTheorem : Formula -> Type
BrokenTheorem a = {vs : Value -> Type} -> {hs : Formula -> Type} -> Theorem vs hs a
```

This is the exact same code as above, with `Theorem` replaced by `BrokenTheorem`, and does not work:
```idris
BrokenExample : {p : Value -> Formula} -> BrokenTheorem
  (NOT (FORALL (\x => NOT (p x))) |> EXISTS p)
BrokenExample =
  lam (\w =>
    efq (\u =>
      hyp w <| (pi (\x =>
                  lam (\v =>
                    hyp u <| (sig x (hyp v)))))))
```
---

**Comment by mietek** [comment]
Adding a dummy argument to `BrokenExample` did not help.

**{AS}** commented on IRC:

> it seems to me that substitution didn't happen properly
> so it somehow solves sigp, but doesn't remove it from the problems

@edwinb’s [earlier comment](https://github.com/idris-lang/Idris-dev/commit/86dc822af2c1f06974bc0759df618ba64741925a) might also be relevant:

> There is still an underlying issue which is related to the cause of this, which is that scoped implicits are not delaborated properly, but this is less serious in that it doesn't break code which should work...

**Comment by edwinb** [comment]
This isn't the answer you're looking for, I expect, but actually I don't think Example should work either. Certainly, BrokenExample and Example should behave the same way. Also, it turns out not to be related to scoped implicits.

Example gets past the checker because the elaborator is treating its parameters (vs and hs in this case) as being always injective. Sadly, this is not true. They should only be treated as such if they happen to be parameters to type classes, which are checked to be injective.

In BrokenExample, Idris doesn't spot the parameters to Theorem, but that should be okay because they're not relevant anyway.

What remains is the terrible error message. I'll see what I can do about that. But in the end, it looks like Example shouldn't work either!

**Comment by edwinb** [comment]
After poking around a bit, and removing some dodgy hacks, all of this now works after all.

**Comment by mietek** [comment]
Thanks!
