### ISSUE TITLE
Underscore cannot be used in alternative binders

### ISSUE THREAD

**Issue by mietek** [idris-lang/Idris-dev#2567]
An underscore is not accepted as a formal parameter to an alternative binding form. Tested with Idris 0.9.18.1.

```idris
module UnderscoreProblem

foo' : (Unit -> Unit) -> Unit
foo' f = ()

example : Unit
example = foo' (\_ => ())

syntax foo {v} "|>" [w] = foo' (\v => w)

brokenExample : Unit
brokenExample = foo _ |> ()
```
```
./UnderscoreProblem.idr:12:17: error: unexpected
    reserved
    identifier, expected: dependent type signature
brokenExample = foo _ |> () 
                ^  
```

Related to #2566 by way of error message.

**Comment by Melvar** [comment]
This, to me, seems right: An underscore is not a name, and a `{}` binding in syntax takes a name. The error message is horrible though, which by itself warrants the issue.

**Comment by edwinb** [comment]
Seems right to me too. The name could be replaced in places other than the binder where the _ would be invalid. Probably an easy fix would be to get the parser to reject this and require an actual name.

**Comment by mietek** [comment]
It seems equally valid to me to say that a λ-expression also takes a name, just lke a `{}` binding.

FWIW, Agda accepts underscores in alternative binders.

**Comment by Melvar** [comment]
A lambda takes a pattern, not just a name.

**Comment by ahmadsalim** [comment]
I think this is expected behaviour.

**Comment by ahmadsalim** [comment]
As was agreed on by @Melvar and @edwinb
