### ISSUE TITLE
Implicit conversion isn't applied in Idris 0.9.19 

### ISSUE THREAD

**Issue by timjb** [idris-lang/Idris-dev#2570]
My [`quantities`](https://github.com/timjb/quantities) package doesn't typecheck with Idris 0.9.19. Specifically, typechecking

```idris
metre : ElemUnit Length
metre = MkElemUnit "m" 1
```

gives the error

```
When checking type of Quantities.SIBaseUnits.metre:
When checking argument q to type constructor Quantities.Core.ElemUnit:
        Type mismatch between
                Dimension (Type of Length)
        and
                Quantity (Expected type)
        
        Specifically:
                Type mismatch between
                        Dimension
                and
                        FreeAbGrp Dimension
```

Here's the relevant context:

```idris
Dimension : Type
FreeAbGrp : Type -> Type
Quantity : Type
Quantity = FreeAbGrp Dimension
implicit dimensionToQuantity : Dimension -> Quantity
ElemUnit : Quantity -> Type
Length : Dimension
```

The problem seems to be that the implicit conversion `dimensionToQuantity` isn't applied.

**Comment by edwinb** [comment]
Could you make a minimal failing example of this please? It's not quite
enough to reproduce directly (without e.g. the definition of each type...)

There was one change in implicits, which was in commit 0dd2f066:

"'implicit' will now only work if there is a concrete argument type and
a concrete return type. This means we can rule out impossible coercions
much quicker, and has the effect of speeding up error reporting by not
trying to fix up the error with coercions which are never going to work."

Perhaps this is something to do with it. I'll take a look to see if
there is something I've overlooked if you can make a small but complete
test case.

**Comment by timjb** [comment]
Here's a minimal failing example:

```idris
module ImplicitConversionFails

record Dimension where
  constructor MkDimension
  name : String

Quantity : Type
Quantity = List Dimension

implicit
dimensionToQuantity : Dimension -> Quantity
dimensionToQuantity x = [x]

Length' : Dimension
Length' = MkDimension "Length"

Length : Quantity
Length = Length'
```
