### ISSUE TITLE
Issues with prefix operators

### ISSUE THREAD

**Issue by mietek** [idris-lang/Idris-dev#2571]
Prefix operators appear to confuse the parser. Tested with Idris 0.9.19.
#### Setup

This works:

``` idris
infixr 5 |>

data Proposition : Type where
  (|>) : Proposition -> Proposition -> Proposition

data Theorem : Proposition -> Type where
  ded : (Theorem a -> Theorem b) -> Theorem (a |> b)
```
#### Without spaces

This does not work:

``` idris
prefix 1 |-

data (|-) : Proposition -> Type where
  ded1 : (|- a -> |- b) -> |- (a |> b)
```

```
./PrefixProblem1.idr:14:12: error: expected: expression
  ded1 : (|- a -> |- b) -> |- (a |> b)
           ^
```
#### With spaces

It seems that having the operator `|-` next to an opening parenthesis conflicts with the syntax for [alternatives](http://idris.readthedocs.org/en/latest/reference/misc.html#alternatives).  However, inserting spaces does not help:

``` idris
prefix 1 |-

data (|-) : Proposition -> Type where
  ded2 : ( |- a -> |- b ) -> |- (a |> b)
```

```
PrefixProblem2.idr:14:8:
When checking type of PrefixProblem.ded2:
Type mismatch between
        pargTy -> pretTy (Type of pf)
and
        Type (Expected type)
```

**Comment by ahmadsalim** [comment]
I believe the issue here is that it parses it as a slice.
I don't think there is a reasonable way to disambiguate in this case, so I will have to unfortunately close this as a nofix. Thanks for the report, in any case!

**Comment by ahmadsalim** [comment]
Looking at it again, the issue might not be unreasonable.
I think one could see if an operator is already defined as prefix and then not parse it as a slice when used in paranthesis.
