### ISSUE TITLE
Dependent function composition and unification

### ISSUE THREAD

**Issue by yfcai** [idris-lang/Idris-dev#2581]
[metavar]: http://www.cse.chalmers.se/~ulfn/papers/meta-variables.pdf

It is know (#2379) that Idris (0ed71c991df6805d629b1e1ca60a7b34ab34fd53) doesn't handle fully dependent function composition very well:

```Idris
comp : {A : Type} -> {B : (a : A) -> Type} ->
       {C : (a : A) -> (b : B a) -> Type} ->
       (f : {a : A} -> (b : B a) -> C a b) ->
       (g : (a : A) -> B a) ->
       (a : A) -> C a (g a)
comp f g a = f (g a)

-- cannot infer {A = Nat} {B = \a => Nat} {C = \a => \b => Nat}
add2 : Nat -> Nat
add2 = comp S S
```

- Is there any reason why `add2` should not typecheck?
- Is there a simple way to determine whether Idris can infer an implicit argument or not?

Unification and the handling implicit arguments are both present here. Unification seems to have problems of its own, so I won't use any implicit arguments from now on.

First, Idris *does* attempt higher-order unification. Here are some examples where Idris successfully infers type functions.

```Idris
comp0 : (B : Nat -> Type) -> ((n : Nat) -> B n) -> Int
comp0 _ _ = 0

-- infers B = (\_ => Nat)
test00 : Int
test00 = comp0 _ S

-- infers B = (\n => Vect n Int)
test01 : Int
test01 = comp0 _ dummy
  where
    dummy : (n : Nat) -> Vect n Nat
    dummy Z     = []
    dummy (S n) = n :: dummy n
```

The next test reveals a weird bug.

```Idris
-- reports "no such variable n",
-- but typechecks when B = (\n => Maybe (Fin n)) is given.
test02 : Int
test02 = comp0 _ (\n => natToFin n n)
```

Type functions producing function types are not inferred.

```Idris
-- cannot infer B = (\n => Int -> Int)
test03 : Int
test03 = comp0 _ dummy where
  dummy : (n : Nat) -> Int -> Int
  dummy _ = \x => x
```

When constraints about two type functions are generated in the same application, they are not infered.

```
comp1 : (B : Nat -> Type) -> (C : Nat -> Type) ->
        ((n : Nat) -> (y : B n) -> C n) -> Int
comp1 _ _ _ = 0

-- cannot infer B = (\n => Vect n Int), C = (\n => Int)
test10 : Int
test10 = comp1 _ _ dummy
  where
    dummy : (n : Nat) -> Vect n Int -> Int
    dummy _ _ = 0
```

If Idris needn't infer `C`, then it infers `B` when `B` is not a constant function.

```
comp2 : (B : Nat -> Type) ->
        ((n : Nat) -> (y : B n) -> Int) -> Int
comp2 _ _ = 0

-- infers B = (\n => Vect n Int)
test20 : Int
test20 = comp2 _ dummy
  where
    dummy : (n : Nat) -> Vect n Int -> Int
    dummy _ _ = 0
```

It doesn't infer `B` when `B` is a constant type function.

```
-- cannot infer B = (\n => Int)
test21 : Int
test21 = comp2 _ dummy
  where
    dummy : (n : Nat) -> Int -> Int
    dummy _ _ = 0
```

All examples above are solvable with the restricted higher-order unification in [Norell and Coquand][metavar] (page 8, bottom rule). A constraint of the form `B x1 ... xn = M` is only resolved if `x1 ... xn` are distinct, rigid variables, in which case `B` is unified with `\x1 ... xn => nf(M)`.

**Comment by edwinb** [comment]
I've been meaning to do this for ages, but this has finally given me the prod to get on with it, especially since that paper presents the rules so clearly. Thanks! I've added all these examples to the test suite, too.
