### ISSUE TITLE
JVM codegen

### ISSUE THREAD

**Issue by suhr** [idris-lang/Idris-dev#2584]
It would be nice to have a jvm codegen.

**Comment by edwinb** [comment]
Codegens are now written externally (apart from the built in C and Java codegens). As a simple model to see how it works, you can start with https://github.com/edwinb/idris-php 

We won't, however, be adding a JVM codegen to Idris itself. The maintenance burden for multiple codegens is too much. Sorry.

**Comment by melted** [comment]
If you want one, you can update the old backend https://github.com/idris-hackers/idris-java
