### ISSUE TITLE
Provide docs about idiomatic error handling in Idris

### ISSUE THREAD

**Issue by suhr** [idris-lang/Idris-dev#2586]

**Comment by edwinb** [comment]
More documentation of various forms would obviously be nice, but an issue report with no content explaining the details and context of what you really want isn't likely to make it happen any sooner I'm afraid.

We're well aware that more documentation needs writing, and more tutorial materials are needed. However, given the time we have available, I see our main documentation job as providing reference materials for the language and libraries, as completely as possible, with tutorials on specific aspects being a bonus, or things that can be contributed by the community. Idiomatic Idris is, in any case, something which is more likely to be arrived at by the wider community than decreed by us... It's not obvious to me what the right idiomatic way to deal with errors is, yet...

Probably a more constructive thing to do at the moment would be to go to the mailing list, explain what you're trying to do, and see if anyone can help. I'm sure someone will be able to!
