### ISSUE TITLE
Type Class Resolution Failure: Correct or Incorrect?

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#2588]
During the run up to the release of Idris 0.9.19 I was updating the Logging Effect. The PR is #2546. This code used to type check and pass the travis tests. However, around the same time [changes were made to the way type class resolution works](https://github.com/idris-lang/Idris-dev/commit/81e19625f2ce040d653848368073ac5ad2a15b6e). Since this change the category based logging effect stopped compiling. Idris gave the following error message:

```
./Effect/Logging/Category.idr:115:11:
When checking right hand side of setLoglvl:
Can't resolve type class Eq a
```
Now, I may be using typicalness wrong in this example, but I do not know. Dus...has my use of type classes here been correct, or is it erroneous? And how can I address it. I am experiencing similar resolution errors in a bigger project of mine and this happens to provide me with a nice MFE.

**Comment by edwinb** [comment]
I've just pulled this branch and fixed the conflicts and tried it out
and it worked fine. It certainly looks like it should.

It's possible that some of the things I've been fixing up this weekend
have sorted it. So shall I just merge the PR since it seems to be fine?

**Comment by edwinb** [comment]
I just merged them, everything looks fine to me. If it's still a problem in the bigger project, please reopen, but it'll need a new MFE!

**Comment by jfdm** [comment]
Okay thanks for this. I shall check the larger project ASAP with Idris HEAD.

**Comment by jfdm** [comment]
Just a quick update: The issue in the larger project remained with the fix, however, in that case I was using Typeclasses (AFAIK) somewhat 'incorrectly'. I removed the need for typeclasses and things are back to normal.
