### ISSUE TITLE
INTERNAL ERROR: cantSolveGoal

### ISSUE THREAD

**Issue by BartAdv** [idris-lang/Idris-dev#2611]
```idris
import Data.Vect

data Periods : List Nat -> Type where
  Nil : Periods []
  (::) : {auto prf : LTE n' n} -> (v : Vect n' a) -> Periods p -> Periods (n :: p)

v1 : Vect 1 Integer
v1 = with Vect [1]

v2 : Vect 2 Integer
v2 = with Vect [1, 2]

v3 : Vect 3 Integer
v3 = with Vect [1, 2, 3]

p : Periods [1,2]
p = [v1, v3]
```

```
     When checking an application of constructor Periods.:::
             INTERNAL ERROR: cantSolveGoal
             This is probably a bug, or a missing error message.
             Please consider reporting at https://github.com/idris-lang/Idris-dev/issues
```

**Comment by jfdm** [comment]
I cannot speak on the error message itself. But the placement of the auto implicit proof is important. It must occur after the introduction of the values into the type signature context. Otherwise idris cannot work out what the values in the auto implicit should be.

**Comment by BartAdv** [comment]
Right, that made the error go away, though in general, it seemed to work previously (as in, the error was shown only when it couldn't solve the goal, it's just the error wasn't pretty).

**Comment by edwinb** [comment]
The semantics of auto wasn't very well defined previously. (Actually it's still not quite, it's just not as bad...)

I've got rid of the internal error, anyway.
