### ISSUE TITLE
Unhelpful error message when dealing with Legacy IBC files in libs direcrtory.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#2621]
Double checking that my packages compile and install with Idris HEAD. A recent change made in HEAD was that `Data.Floats` was moved from `base`, to `prelude` and renamed `Data.Doubles`, with `Float` being renamed to `Double`. This was not a problem.

A package of mine tripped up as the legacy `Floats.ibc` file was still in the Idris `$LIBDIR`, and Idris reported the error on a cleaned version of the library:
```
Incompatible ibc version.
This library was built with an earlier version of Idris.
Please clean and rebuild.
```

The error was being reported on `Floats.ibc` but that was not clear from the error message. 

Two approaches to fixing:

1. Change the default installation semantics  by clobbering the install directory for the package being installed prior to installing.
2. Update the error message to report the file upon which the incompatible IBC error was called.

**Comment by ahmadsalim** [comment]
It would be even nicer if the rebuilding was done automatically.

**Comment by jfdm** [comment]
i had forgotten about this. Does #3100 actually satisfy this?

**Comment by ahmadsalim** [comment]
I think it does, I will close it. Thanks @jfdm
