### ISSUE TITLE
Module import cycle produces cryptic message

### ISSUE THREAD

**Issue by cbiffle** [idris-lang/Idris-dev#2622]
(Found in 6fc713d.)

The compiler output when it encounters an import cycle is not very informative.

Create a file called `cycle.idr` containing only this text:

    import cycle

When loading this file, e.g. by `:load cycle.idr` in the REPL, or by `\r` in idris-vim, the output is:

    No ibc for cycle

Which is an accurate but somewhat indirect description of what's happening.  In the single file case, the message might be enough to discover the issue --- but the same message appears in cycles of multiple files, where the problem is far more subtle.

**Comment by ahmadsalim** [comment]
I know get the following error message:

```
Cycle detected in imports: test.idr -> test -> test
```
