### ISSUE TITLE
Totality/impossibility checker is behaving strangely

### ISSUE THREAD

**Issue by scshunt** [idris-lang/Idris-dev#2625]
In the following code:

    import Data.Fin

    %default total

    data Permutation : Nat -> Type where
      Nil : Permutation Z
      (::) : Fin (S n) -> Permutation n -> Permutation (S n)

    increment : Fin (S m) -> Permutation m -> Permutation (S m)
    increment FZ [] = [FZ]
    increment FZ (p :: ps) = weaken p :: increment FZ ps
    increment (FS m) (p :: ps) = FS p :: increment m ps

I get the following error:

    /tmp/Foo.idr:10:1:
    Main.increment is not total as there are missing cases

This is not true, as the remaining case is impossible. If I try to tell the compiler this by adding the following case:

    increment (FS m) [] impossible

I'm now told

    /tmp/Foo.idr:13:15:increment (FS m) [] is a valid case

which is simply not true. In a fit of desperation, I challenge the compiler to find a value for `m`, by replacing that case with:

    increment (FS m) [] with (m)
      | _ impossible

Undeterred, the compiler continues to be upset with me:

    /tmp/Foo.idr:14:11:
    with block in Main.increment _ m is a valid case

I decide to get more explicit:

    increment (FS m) [] with (m)
      | FZ impossible

and at this point, the compiler accepts it.

The fact that the compiler cannot rule out the fourth case without help is okay, if a little bit odd. The very strange thing is that I did not also have to add a `(FS _)` line to the `with` pattern. Once I asked the compiler to match on `FZ`, it ruled out `(FS _)` as well.

**Comment by Melvar** [comment]
The coverage checker will only analyze cases as deep as you match them in any clause. `increment (FS m) []` is on the face of it perfectly possible, in particular the following is a valid clause:
`increment (FS m) [] = absurd m`. The checker is not going to analyze the possibilities for `m : Fin 0` of its own accord. It is only upon matching m with a constructor that the case becomes ill-typed and thus eligible for `impossible`, and only then will the checker analyze to this new depth and find the other case also impossible.
