### ISSUE TITLE
Case split fails on private types

### ISSUE THREAD

**Issue by cbiffle** [idris-lang/Idris-dev#2640]
Found in 50878fa.

**To reproduce:**

Given:

```idris
private
data X = MkX Nat
  
public
f : X -> Nat
f x = ?f_rhs
```

Attempt to case-split on the `x` parameter to `f` (e.g. in `idris-vim`, place the cursor on `x` and hit `\c`).

**Observed behavior:**

Attempting to case-split on the `x` parameter to `f` produces:

    Elaborating {__infer0} arg {ival0}: NoSuchVariable

Switching the `data X` declaration to `public` fixes the problem.

**Expected behavior:**

Case split occurs normally.  `f x` rewritten as `f (MkX x)`.  My intent with the access modifiers was not to hide things *from the IDE.*

Alternatively: the error message, if one must be produced, makes some reference to the problem.

**Commentary:**

I noted above that switching `data X` to `public` fixes the problem, but note also that *removing all access modifiers* similarly fixes the problem.  This is relevant, because it's how I stumbled across this behavior.

In editing an existing module, I wrote a lemma and made it `private`.  Being the first use of explicit access modifiers in the module, all my data types were now implicitly `private`.  Before I could get around to fixing this, my *editor broke* with the error message above.

In my opinion, besides misbehavior of the REPL serving the IDE protocol, this is *also* further misbehavior of Idris's access inference rules.  (See #1879.)  Access inference delendum est.

**Comment by david-christiansen** [comment]
Thanks for a great, well-written, specific report! It definitely needs fixing.

**Comment by ahmadsalim** [comment]
The given code now gives me:

```idris
public export Main.f can't refer to private data X
```
which I think is a reasonable error message and expected behaviour.

I will therefore close this issue.
