### ISSUE TITLE
`%access private` doesn't work.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#2644]
Given the module:

```idris
module Secret

%access private

record PrivFoobar where
  constructor MkPrivFoo
  f : String
  b : String

bob : PrivFoobar
bob = MkPrivFoo "a" "b"
```

I expect  nothing to be exported. However, loadiing `Secret.idr` into the REPL allows the following set of commands to be used:

```
λΠ> :t bob
bob : PrivFoobar
λΠ> :t PrivFoobar
PrivFoobar : Type
λΠ> :t f
f : PrivFoobar -> String
λΠ> :t b
b : PrivFoobar -> String
λΠ> bob
MkPrivFoo "a" "b" : PrivFoobar
```

I expected that none of these commands would work. However, when I append the empty definition

```idris
public
x : String
```

to `Secret.idr` the access modifiers resolve them selves, and the contents of `Secret.idr` are no longer accessible, aside from the behaviour documented in #2623.

**Comment by jfdm** [comment]
Note as commented by several people, access modifiers need to be re-visted. Other issues were documented in #2640, #2623, and #1879.

**Comment by edwinb** [comment]
%access now behaves in a more sensible way
