### ISSUE TITLE
Proof search should fail if there are holes in the type

### ISSUE THREAD

**Issue by mrmonday** [idris-lang/Idris-dev#2646]
The following code:

```idris
import Data.List

letters : List Char
letters = ['a']

data Letter : Char -> Type where
  MkLetter : (c : Char) -> { auto p : List.Elem c letters } -> Letter c

letter : Letter 'a'
letter = MkLetter 'a'
```

Gives the errors:

```
Idris> :e
Type checking ./foo.idr
foo.idr:10:8:Can't infer argument xs to (::), 
             Can't infer argument xs to Here
Holes: Main.letter
```

This error is confusing, since the actual error is that `letters` isn't properly qualified as `Main.letters`, on line 7 (making that change removes the error). It's additionally confusing, since not only are the line numbers incorrect, it references identifiers which cannot be found anywhere in the file.

**Comment by edwinb** [comment]
The line number and error message are correct here. The error is in the proof it has constructed (more on this in a moment) which is indeed part of the definition of letter on line 10. The identifiers it references are the names in the arguments to :: and Here. That's what the "Can't infer argument" error message always means. 

It's treating 'letters' on line 7 as an implicit, which is the defined behaviour of name binding in implicits. It's hard for Idris to give error messages which explain misunderstandings about the semantics of various features... all we can do is try to explain as precisely as possible what's wrong, we can't guess about the user's intentions.

I think there is an error here, though - what is actually happening here is that auto implicit search has tried to find a proof when there's still a hole in the type. This should only be valid if the proof is tried in the final step of elaboration (which is fine here) and if proof search actually does resolve those holes (which is what is not fine here). I've edited the title accordingly.

**Comment by ahmadsalim** [comment]
```idris
Type checking ./test.idr
test.idr:9:51-58:WARNING: letters is bound as an implicit
	Did you mean to refer to Test.letters?
test.idr:12:8:Can't infer argument xs to (::), Can't infer argument xs to Here
Holes: Test.letter
```

It know gives a nice warning, about this issue with implicits.
I will therefore close this issue.
