### ISSUE TITLE
Incredibly long/impossible to read error messages with long types

### ISSUE THREAD

**Issue by mrmonday** [idris-lang/Idris-dev#2647]
The following code:

```idris
import Data.List

isNum : (i : Int) -> { auto p : Elem i [0..100] } -> Int
isNum i = i

err : Int
err = isNum (-1)
```

Gives an incredibly long error message when type checking:

```
Type checking ./foo.idr
foo.idr:10:13:When checking right hand side of err:
When checking argument p to function Main.isNum:
        Can't solve goal 
                Elem -1
                     [0,
                      1,
                      2,
<snip>
                      97,
                      98,
                      99,
                      100]
```

The situation can be even worse, when this (or a similar type) ends up nested in another structure, which can cause error messages which print for several minutes due to incredibly long types (unfortunately I've lost my example of this)

**Comment by edwinb** [comment]
If the types are long, the error messages about them are going to be long too. Do you have a suggestion for improving this? We've tried truncating them in the past, and it has led to differently confusing error messages... again, perhaps an IDE could improve this, but I don't see what Idris can do better.

**Comment by david-christiansen** [comment]
There is a pretty-printer depth setting available, which can be customized for a particular session if you're working with things that have a tendency to blow up when they go wrong.
