### ISSUE TITLE
Confusing error message with shadowing names

### ISSUE THREAD

**Issue by mrmonday** [idris-lang/Idris-dev#2652]
The following code:

```idris
foo : Int -> Int
foo i = i

bar : Int -> Int
bar foo = foo foo
```

Gives the error message:

```
Idris> :e
Type checking ./foo.idr
foo.idr:5:11-14:When checking right hand side of bar:
Type mismatch between
        Int (Type of foo)
and
        argTy -> retTy (Is foo applied to too many arguments?)
Holes: Main.bar
```

This can be confusing, generally with a larger/more real world example than this. A better message would be a warning about parameter foo shadowing function foo.

**Comment by edwinb** [comment]
Sometimes shadowing a function is what you want, though. The machine can't read your mind... I think this is a reasonable error message, especially given that in your hypothesised larger example there could be quite a lot of things with the given name.

**Comment by mrmonday** [comment]
I didn't mean to always warn/error on shadowing - obviously shadowing is useful.

What I meant was that when a type mismatch occurs, searching for names in outer scopes to see if they have matching types, /and then/ warning about shadowing occurring.
