### ISSUE TITLE
No such variable Language.Reflection.UN

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#2664]
Compiling an Effectful program I get the following error:

```
When attempting to perform error reflection, the following internal error occurred:
        No such variable Language.Reflection.UNThis is probably a bug. Please consider reporting it at https://github.com/idris-lang/Idris-dev/issues
```

This is in a relatively large project, so getting a MFE will take some time.

**Comment by jfdm** [comment]
Just as an update this was on code that worked before and hasn't been touched for a while.

**Comment by david-christiansen** [comment]
This is almost certainly a duplicate of #2663, as those are constructors of the same datatype.

**Comment by jfdm** [comment]
Okay will close.

**Comment by david-christiansen** [comment]
@jfdm Could you please double-check for me that there's no stale IBCs? Also, would you please load the file so the error occurs, then write ":t Language.Reflection.UN" at the REPL?

**Comment by jfdm** [comment]
So a clean and a build seems to have resolved the issue. However, I swear I did clean the build and tried again prior to submitting the issue.

**Comment by david-christiansen** [comment]
You're certainly not the only one encountering this. Hopefully it's just something that will be a minor build process irritation rather than an honest to goodness nasty bug. In any case, thanks for letting me know that it's working again.

**Comment by jfdm** [comment]
what might be a good advice is to tell people to also clean `idris --libdir` if they can, and then rebuild the base libs...
