### ISSUE TITLE
Poor error message with numeric in if statement

### ISSUE THREAD

**Issue by mrmonday** [idris-lang/Idris-dev#2669]
The following code:

```idris
foo : ()
foo = if 3 then () else ()
```

Gives the error:

```
Type checking ./foo.idr
foo.idr:2:5:When checking right hand side of foo:
Bool is not a numeric type
```

This error message is poor, particularly in comparison to the error when using other incorrect types:

```
Type checking ./foo.idr
foo.idr:2:10:When checking right hand side of foo:
When checking argument b to function Prelude.Bool.ifThenElse:
        Type mismatch between
                String (Type of "")
        and
                Bool (Expected type)
Holes: Main.foo
```

**Comment by david-christiansen** [comment]
I don't think this error message is going to get much better. This is because it would be possible to define

```
fromInteger : Integer -> Bool
fromInteger i = i `mod` 2 == 0
```
which would allow even or odd integer literals to be used as `Bool` literals.  The error is saying that such an overloading of `Integer` literals isn't defined.

**Comment by mrmonday** [comment]
You could also define a `fromString : String -> Bool`, but strings don't suffer from the poor error message - unless I'm misunderstanding?

**Comment by david-christiansen** [comment]
Idris doesn't have overloaded string literals, but it does have overloaded integer literals.

**Comment by mrmonday** [comment]
I still feel like I'm missing something here - you can write:

```idris
implicit fromString : String -> Bool
fromString "" = False
fromString _ = True

foo : ()
foo = if "something" then () else ()
```

For example - how is that any different?

**Comment by david-christiansen** [comment]
Because if I write `17` in Idris code, that's shorthand for `fromInteger 17`. This is what lets us write `17` for a `Nat` or for an `Integer` or for a `Fin 28`.  No corresponding desugaring happens for strings.

**Comment by david-christiansen** [comment]
In other words, `17` is _always_ `fromInteger 17`, while if an implicit coercion doesn't apply, then it doesn't stick around.

**Comment by mrmonday** [comment]
It seems somewhat odd that this is special cased, given that you could achieve the same thing with implicits.

Ignoring that though, we get a more interesting test case for this error:

```idris
foo : Bool
foo = fromInteger 6
```

Gives the same error (does this de-sugar into `fromInteger (fromInteger 6)`? I guess so).

I guess, even with the de-sugaring happening, I would expect the same error as for any other data type.

**Comment by david-christiansen** [comment]
It indeed desugars to `fromInteger (fromInteger 6)`. The inner `fromInteger` becomes the one that converts `Integer` into  `Integer`: the identity.

I can see that you'd expect that, but I think that given the rules for integer literals in Idris, the current message is quite reasonable.

Compare GHC:
```
$ ghci
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
Prelude> if 3 then "yes" else "no"

<interactive>:2:4:
    No instance for (Num Bool) arising from the literal ‘3’
    In the expression: 3
    In the expression: if 3 then "yes" else "no"
    In an equation for ‘it’: it = if 3 then "yes" else "no"
Prelude> if "str" then "yes" else "no"

<interactive>:3:4:
    Couldn't match expected type ‘Bool’ with actual type ‘[Char]’
    In the expression: "str"
    In the expression: if "str" then "yes" else "no"
    In an equation for ‘it’: it = if "str" then "yes" else "no"

```

**Comment by suhr** [comment]
> arising from the literal ‘3’

I believe this makes the error message better.

**Comment by mrmonday** [comment]
Both of the messages from GHC are significantly better than "Bool is not a numeric type". GHC makes it clear that it's expecting an instance of Num Bool in this scenario - that isn't clear at all for Idris.

**Comment by edwinb** [comment]
This error message is actually rewritten using error reflection from the original which says it can't find an instance of Num Bool. Personally I think the rewritten message is better, even in the original case here. Maybe an interactive mode could let you look at the original of a reflected message, but this particular message isn't going to change.

I prefer special casing to implicits for this. Implicits can lead to particularly strange error messages if not used with great care and should be used sparingly, if at all.

**Comment by david-christiansen** [comment]
Just to be clear - Idris already lets you look at the original form of a rewritten message, and it has done so since I first implemented error reflection. The REPL command `:set originalerrors` will show the non-rewritten form in an indented block.

**Comment by mrmonday** [comment]
[It would be really good if there were a list of `:set` options, the repl only seems to list two right now in `:help`]

I've just looked at the original error, and neither are particularly great. I don't know if it would be possible to get an error more like what Haskell has? I think the "arising from the literal '3'" makes a big difference.

**Comment by david-christiansen** [comment]
@mrmonday you can see them all in the tab completion for `:set` - would you mind sending a quick patch that lists all of them in `:help` as well?

Adding provenance information to rewritten integer literals should be reasonably possible as well. We already have it for type mismatches, after all, and the elaborator does keep track of the fact that something represents an original integer literal, because this is used for semantic editor highlighting. I'll open this as a separate feature request, but no guarantees about when I'll get around to doing it!

**Comment by david-christiansen** [comment]
#2747 is the issue to track integer literal provenance info.

**Comment by mrmonday** [comment]
@david-christiansen I've submitted a patch in pull #2753 :)

**Comment by Melvar** [comment]
You can’t use implicits to do the same thing, because implicits will happily work on non-literals, which makes them more troublesome than useful if transforming literals is what you want, and AIUI it often is.
