### ISSUE TITLE
Unable to infer correct type, or poor error message

### ISSUE THREAD

**Issue by mrmonday** [idris-lang/Idris-dev#2672]
The following code:

```idris
bar : IO ()
bar = do x <- getChar
         case x of
           'z' => do putStrLn "foo"; bar
           _   => do putStrLn "bar"; bar

baz : IO ()
baz = do x <- getChar
         the (IO Unit) $ case x of
                           'z' => putStrLn "foo"
                           _   => putStrLn "bar"
         baz

foo : IO ()
foo = do x <- getChar
         case x of
           'z' => putStrLn "foo"
           _   => putStrLn "bar"
         foo
```

Gives the error:

```
Type checking ./foo.idr
foo.idr:16:15:
When checking right hand side of Main.case block in foo:
Type mismatch between
        IO' (MkFFI C_Types String String) () (Type of putStrLn "foo")
and
        IO' (MkFFI C_Types String String) a (Expected type)

Specifically:
        Type mismatch between
                ()
        and
                a
Holes: Main.foo
```

Note that `bar` and `baz` compile correctly, however `foo` gives an error. As far as I can tell, these three functions should all be equivalent. In the event this is behaving as expected, the error message is poor - it gives no insight into why `a` is expected, or what needs to be done to make it work.

**Comment by david-christiansen** [comment]
The reason why `foo` gives the error is that Idris has no way to determine the type of the case expression when it's no longer the last subexpression of the `do` expression. It's a pretty irritating error! It can be solved by wrapping the case expression in something that constrains its type, like a call to `the`, but that's irritating.

**Comment by edwinb** [comment]
I'm not sure how the error message could give any insight here - it is telling you exactly what's wrong, and while that isn't always helpful, it isn't always clear how to make it better. Type checkers aren't very clever, and they can only report on what you wrote, rather than what your intention was. 

Case expressions are limited in that the type needs to be inferrable from the surrounding context, as is documented in the tutorial (http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#case-expressions) - although actually the first limitation there is now lifted. This is due to the type-directed way that type checking works, and it's pretty hard to lift this limitation in a language with full dependent types without making compromises elsewhere.

What do you suggest it should say instead, and how could Idris work out to say it?

**Comment by mrmonday** [comment]
I'm not sure how you'd improve the error, given the requirement that the type of the case expression needs to be inferable from the surrounding context.

I guess the confusion, for me, arises from that fact that, for me, when I see `a`, I think type variable, at which point I don't understand why there's a type mismatch at all (there are quite a few errors where that kind of thing happens - and in most cases `a` is something the compiler has made up and isn't in the source).

Perhaps the error could mention the restrictions on case statements? It's particularly confusing for folk with a Haskell background who haven't necessarily read the documentation to know of the restrictions.

**Comment by edwinb** [comment]
The error message would have to know that the problem arose from the limitation on case statements, and it's not even necessarily going to be that which is causing the problem. This error could arise in any number of situations where an expression is being used in a less generic way than Idris expects.

The name 'a' is arising from the type of >>=. One thing that might make this clearer is giving this variable a more informative name, which is something we should be doing in general anyway for library code.

While we do want error messages to be as informative as possible, I don't think we can reasonably put additional effort into error messages as a substitute for learning about the language itself, or as a substitute for reading the documentation on a particular feature. 

It's just as bad (possibly even worse and more confusing) for an error message to try to explain some insight behind a problem and get it wrong as it is for a message to merely explain the problem as precisely as possible without giving insight. 

One thing that might increase precision here without adding too much noise could be to give the type of the generated function after saying "When checking right hand side of Main.case block in foo". e.g.
"When checking right hand side of Main.case block in foo with expected return type IO a".
