### ISSUE TITLE
Suspicious "Type mismatch" error message: regression?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2673]
The program
```
> module Num

> import Data.Fin
> import Data.Vect
> import Syntax.PreorderReasoning

> total foldrClassic : (t -> acc -> acc) -> acc -> Vect n t -> acc
> foldrClassic f e []      = e
> foldrClassic f e (x::xs) = f x (foldrClassic f e xs)

> foldrImplLemma : {A, B : Type} -> {n : Nat} ->
>                  (f : A -> B -> B) -> (e : B) -> (go : B -> B) ->
>                  (as : Vect n A) ->
>                  foldrImpl f e go as = go (foldrClassic f e as)
> foldrImplLemma f e go []        = Refl
> foldrImplLemma f e go (a :: as) =
>     ( foldrImpl f e go (a :: as) )
>   ={ Refl }=
>     ( foldrImpl f e (go . (f a)) as )
>   ={ foldrImplLemma f e (go . (f a)) as }=
>     ( (go . (f a)) (foldrClassic f e as) )
>   ={ Refl }=
>     ( go (f a (foldrClassic f e as)) )
>   ={ Refl }=
>     ( go (foldrClassic f e (a :: as) ) )
>   QED

> total foldrImplCorr :  {A, B : Type} -> {n : Nat} ->
>                        (f : A -> B -> B) -> (e : B) ->
>                        (as : Vect n A) ->
>                        foldrImpl f e id as = foldrClassic f e as
> foldrImplCorr f e as = replace {x = id (foldrClassic f e as)}
>                                {y = foldrClassic f e as}
>                                {P = \ ZUZU => foldrImpl f e id as = ZUZU}
>                                Refl (foldrImplLemma f e id as)
```
fails to type check with
```
- + Errors (1)
 `-- type_mismatch1.lidr line 33 col 14:
     Type mismatch between
             foldrImpl f e id as = foldrClassic f e as
     and
             foldrImpl f e id as = foldrClassic f e as
     
     Specifically:
             Type mismatch between
                     foldrImpl f e id as = foldrClassic f e as
             and
                     foldrImpl f e id as = foldrClassic f e as
```
with 0.9.19.1. Ist this the expected behavior? Notice that the program type checks fine with 0.9.19-git:PRE. In fact, with 0.9.19-git:PRE, even
```
> foldrImplCorr f e as = foldrImplLemma f e id as
```
does type check fine. Is this a regression?

**Comment by TimRichter** [comment]
Hi Nicola,

if you replace id in the type of foldrImplCorr with Prelude.Basics.id:

    > total foldrImplCorr :  {A, B : Type} -> {n : Nat} ->
    >                        (f : A -> B -> B) -> (e : B) ->
    >                        (as : Vect n A) ->
    >                        foldrImpl f e Prelude.Basics.id as = foldrClassic f e as
    > foldrImplCorr f e as = replace {x = id (foldrClassic f e as)}
    >                                {y = foldrClassic f e as}
    >                                {P = \ ZUZU => foldrImpl f e id as = ZUZU}
    >                                Refl (foldrImplLemma f e id as)

it typechecks. Idris seems to interpret "id" alone as something else (a variable ?).

Ciao,
Tim

**Comment by nicolabotta** [comment]
Interesting Tim, thanks! Edwin, David, is this a consequence of the new rules for  lower-case names in type signatures?

**Comment by david-christiansen** [comment]
I believe that it is!

**Comment by nicolabotta** [comment]
> I believe that it is!

In this case I have to reiterate my opposition to these rules: In my idris-lang post from Fri, 25 Sep 2015 13:14:34 +0200 I doubted the usefulness of the new rules. I am now convinced they are not practicable. I am going to put forward two arguments against them: a conceptual one and a pragmatic one:

The conceptual argument: In the example above, I have (implicitely) imported a file that contains a legal definition of `id`. The example does not contain any `%hide` directive suggesting I might intend hiding any of the imported names. Also, there is no `{id : B -> B}` entry in the argument list of `foldrImplCorr`. Why should the type checker subsume `id` does not refer to the name I have purposly imported? Such behaviour seems to override the purpose of import directives, preempt the effect of hiding directives and subsume user sloppiness.

The pragmatic argument: in a dependently typed language, function names (among others, names of member functions of type classes)  play a prominent role in the signature
of functions that represent logical sentences. If the example above seems contrived, think of examples like
```
> getProofPreservesEq : {A  : Type} ->
>                       {P  : A -> Type} ->
>                       {s1 : Sigma A P} ->
>                       {s2 : Sigma A P} ->
>                       (s1 = s2) -> (getProof s1 = getProof s2),
``` 
```
> sigmaEqLemma1 : {A  : Type} ->
>                 {P  : A -> Type} ->
>                 (s1 : Sigma A P) ->
>                 (s2 : Sigma A P) ->
>                 getWitness s1 = getWitness s2 ->
>                 Unique0 (P (getWitness s1)) ->
>                 s1 = s2
```
or
```
> gcdGreatest : (m : Nat) -> (n : Nat) -> (d : Nat) ->
>               d `Divisor` m -> d `Divisor` n -> d `Divisor` gcd m n
```
Function names start typically with lower-cases. Do you really expect users to replace all the `getWitness`, `getProof`, `map`, `fold`, `gcd` etc. with full qualified names? This would not only lead to hardly readable programs. Application-level code would become virtually unmaintainable! Every little change in the organization of the prelude libraries would imply hundreds of search and replace (in place of a single change of an import directive) in the application level code! 

In short: It seems to me that the consequences of the new rules have not been thought through. I might of course be missing something ovbious, but I also do not see the problems these rules are meant to address. One idea seems to be that they should allow expressions like
```
length : List elem -> Nat
```
to be parsed without generating an (actually very useful) error message. This is a poor motivation. It buys questionable convenience at a very high price: application level code becomes less readable and virtually unmaintainable; the semantics of import directives gets obfuscated by a distinction between upper-case and lower-case names; the reason for full qualified names becomes ambiguous. Are there stronger arguments for the new rules that I am missing? 

If not, I would strongly suggest to rethink these rules or, at least, provide a way to disable them via suitable module wide directives.

**Comment by edwinb** [comment]
It is not a good idea to have name binding rules essentially guess whether a name should be bound or not. None of the examples you cite are affected, other than `id`, and I believe you *should* explicitly qualify that because it's a perfectly valid implicit argument name and one that I might even consider using in some contexts.

The motivation for me is: Name binding rules must be unambiguous.

I think this is also a serious problem:

    a : Type
    a = Int

    foo : Vect n a -> Vect n a

It's unlikely you meant `foo` to have type `Vect n Int -> Vect n Int` here, but that's what you got. It's a particularly big problem if `a` is defined in another module, or if `a` is a more sensibly named thing. Maybe we have, in some module:

length : Nat
length = 5

foo : Vect length a -> Vect length a

`foo` is probably meant to be length preserving, but actually it's only length preserving if the length happens to be 5. 

Even if the machine *can* work out what a name means, it's not always so obvious to the programmer, and that is just as (perhaps even more) important.

Unless you can come up with another rule which is similarly unambiguous, avoids the `foo` problem above, and which doesn't rely on some kind of compiler magic, I'm not changing them. Sorry.

**Comment by nicolabotta** [comment]
We have two problems here: 

The first one is an error message which is not particularly helpful. As Tim has shown, full qualification of `id` makes the original code type check. I would expect the error message for the original code to be something like `Can't disambiguate ...`, not a `Type mismatch ...` error message.

The second problem are the new name-resolution rules that have triggered that error message.  These rules are based on the very new implicit assumption that in programs like
```
a : Type
a = Int
foo : Vect n a -> Vect n a
```
`foo` is meant to be of type `{t : Type} -> {k : Nat} -> Vect k t -> Vect k t`. You believe this assumption is meaningful, I believe it is not.  On one hand, I do not see why `foo`should not be resolved to be of type `{k : Nat} -> Vect k Int -> Vect k Int`. This seems a very reasonable first guess. On the other hand, I believe I have strong reasons that suggest `foo : {k : Nat} -> Vect k Int -> Vect k Int` is the "right" interpretation.

The first one is "moral": `foo : {k : Nat} -> Vect k Int -> Vect k Int` seems the most liberal interpretation of the code which can be established without being unfair to the programmer. If she wanted `foo` to be of type `{t : Type} -> {k : Nat} -> Vect k t -> Vect k t`, she could have written
```
foo : Vect n t -> Vect n t
```
or
``` 
foo : {a : Type} -> Vect n a -> Vect n a
```
or even better
```
foo : {n : Nat} -> {a : Type} -> Vect n a -> Vect n a
```
I like to think that if the programmer has not chosen to do so, she has good reasons for not doing so. 

Another rationale that speaks for `foo` being of type `{k : Nat} -> Vect k Int -> Vect k Int` is that such type does not violate referential transparency: I can safely replace `a` with `Int` in `foo` (which I assume to be entitled to do because of the `a = Int` definition) without changing the interpretation. 

A third reason why I believe that `{k : Nat} -> Vect k Int -> Vect k Int` is the "right" type for `foo` is that patterns like
```
module Lala
lala : Nat -> Vect n Nat
```
```
module LalaSpec
import Lala
lalaSpec : (xs : Vect n Nat) -> sum xs = S Z -> sum (concat (map lala xs)) = S Z 
```
have proven to be so far quite useful for developing Idris applications. The idea of instantiating an application by filling the "lala"s of partially defined modules is at the core of the design of our framework for solving sequential decision problems. This idea relies on `Lala:lala` to be a first-class name in `LalaSpec` and after the `import Lala` directive. This is consistent with `foo : {k : Nat} -> Vect k Int -> Vect k Int` but not with the new rules. Effectively, these override the `import` directive. The fact that the new rules do not hold for names which are applied might help saving a lot of legacy code. But, this practical advantage has a high price: it will inevitably lead to a mix of fully qualified and unqualified names where the same (unqualified) name can refer to an implicit parameters or to an (applied) imported name! From the viepoint of code reading, this is near to the highest level of ambiguity I can think about.

If you do not see the possibility of rethinking the new rules, I would suggest to support a directive that requires all implicit arguments of a function to be explicitely given in its declaration (maybe this is already supported, I seem to remember this is the rule in Agda). The more I think about it, the more it seems to me this would be anyway the cleanest solution or, at least, one programmers should be rewarded for adopting.

**Comment by nicolabotta** [comment]
I find it difficult to believe that issuing a
```
Type mismatch between
             foldrImpl f e id as = foldrClassic f e as
     and
             foldrImpl f e id as = foldrClassic f e as
```
error message is the expected behavior in this situation. Here it would probably be useful to issue a message that clearly identifies `id` as the culprit but I have honestly no idea how such a message could look like. It should probably be a message that suggest that `id` might need full qualification. 

Another related problem is that in the implementation that type checks (thanks Tim!)
```
> total foldrImplCorr :  {A, B : Type} -> {n : Nat} ->
>                        (f : A -> B -> B) -> (e : B) ->
>                        (as : Vect n A) ->
>                        foldrImpl f e Prelude.Basics.id as = foldrClassic f e as
> foldrImplCorr f e as = replace {x = id (foldrClassic f e as)}
>                                {y = foldrClassic f e as}
>                                {P = \ ZUZU => foldrImpl f e id as = ZUZU}
>                                Refl (foldrImplLemma f e id as)
```
and because of the full qualification on `id`, the third argument of `foldrImpl` in the signature of `foldrImplCorr` is syntactically different from the third argument of `foldrImpl` (and from the third argument of `foldrImplLemma`) in its implementation. 

There is obviously a problem of understandability here but, on the top of it,  there is a more fundamental problem: is type checking here the expected behavior?

**Comment by nicolabotta** [comment]
Edwin, here is another example in which the error message could probably be improved: 
```
> import Control.Isomorphism
> import Data.Fin
> import Data.Vect
> import Syntax.PreorderReasoning

> %default total 

Imported stuff 

> data TotalPreorder : Type -> Type where
>   MkTotalPreorder : {A : Type} ->
>                     (R : A -> A -> Type) ->
>                     (reflexive : (x : A) -> R x x) ->
>                     (transitive : (x : A) -> (y : A) -> (z : A) -> R x y -> R y z -> R x z) ->
>                     (totalPre : (x : A) -> (y : A) -> Either (R x y) (R y x)) ->
>                     TotalPreorder A

> namespace TotalPreorderOperations
>   R : {A : Type} -> TotalPreorder A -> (A -> A -> Type)
>   R (MkTotalPreorder R _ _ _) = R
> 
>   reflexive : {A : Type} ->
>               (tp : TotalPreorder A) ->
>               (x : A) -> (R tp) x x
>   reflexive (MkTotalPreorder _ reflexive _ _) = reflexive
> 
>   transitive : {A : Type} ->
>                (tp : TotalPreorder A) ->
>                (x : A) -> (y : A) -> (z : A) -> (R tp) x y -> (R tp) y z -> (R tp) x z
>   transitive (MkTotalPreorder _ _ transitive _) = transitive
>
>   totalPre : {A : Type} ->
>              (tp : TotalPreorder A) ->
>              (x : A) -> (y : A) -> Either ((R tp) x y) ((R tp) y x)
>   totalPre (MkTotalPreorder _ _ _ totalPre) = totalPre
>  
>   from2 : {A, B : Type} -> (B -> B -> Type) -> (A, B) -> (A, B) -> Type
>   from2 R x y = R (snd x) (snd y)
>
>   fromTotalPreorder2 : {A, B : Type} -> TotalPreorder B -> TotalPreorder (A, B)
>   fromTotalPreorder2 to =
>     MkTotalPreorder (from2 (R to))
>                     (\ x => reflexive to (snd x))
>                     (\ x => \ y => \ z => \ xRy => \ yRz => transitive to (snd x) (snd y) (snd z) xRy yRz)
>                     (\ x => \ y => totalPre to (snd x) (snd y))

> namespace FinOperations
>   tail : {A : Type} -> {n : Nat} ->
>          (Fin (S n) -> A) -> (Fin n -> A)
>   tail f = f . FS
>
>   toVect : {A : Type} -> {n : Nat} ->
>            (Fin n -> A) -> Vect n A
>   toVect {n =   Z} _ = Nil
>   toVect {n = S m} f = (f FZ) :: (toVect (tail f))

> namespace IsomorphismOperations
>   from : {A, B : Type} -> Iso A B -> (B -> A)
>   from (MkIso to from toFrom fromTo) = from

> Finite : Type -> Type
> Finite A = Exists (\ n => Iso A (Fin n))

> namespace FiniteOperations
>   card : {A : Type} -> (fA : Finite A) -> Nat
>   card = getWitness
>
>   toVect : {A : Type} -> (fA : Finite A) -> Vect (card fA) A
>   toVect (Evidence n iso) = toVect (from iso)
>   
>   Empty : {A : Type} -> Finite A -> Type
>   Empty fA = card fA = Z
>
>   NonEmpty : {A : Type} -> Finite A -> Type
>   NonEmpty = Not . Empty

> namespace NatProperties
>   idSuccPreservesLTE : (m : Nat) -> (n : Nat) -> m `LTE` n -> m `LTE` (S n)
>   idSuccPreservesLTE  Z     n    prf = LTEZero
>   idSuccPreservesLTE (S m)  Z    prf = absurd prf
>   idSuccPreservesLTE (S m) (S n) prf = LTESucc (idSuccPreservesLTE m n (fromLteSucc prf))
>
>   ltZS : (m : Nat) -> LT Z (S m)
>   ltZS  Z    = LTESucc LTEZero
>   ltZS (S m) = idSuccPreservesLTE (S Z) (S m) (ltZS m)

>   notZisgtZ : {n : Nat} -> Not (n = Z) -> LT Z n
>   notZisgtZ {n = Z}   contra = void (contra Refl)
>   notZisgtZ {n = S m} _      = ltZS m

> pair : (a -> b, a -> c) -> a -> (b, c)
> pair (f, g) x = (f x, g x)

> namespace VectOperations
>   argmaxMax : {A : Type} ->
>               TotalPreorder A -> Vect n A -> .(LT Z n) -> (Fin n, A)
>   argmaxMax {n = Z}       tp  Nil                p = absurd p
>   argmaxMax {n = S Z}     tp (a :: Nil)          _ = (FZ, a)
>   argmaxMax {n = S (S m)} tp (a' :: (a'' :: as)) _ with (argmaxMax tp (a'' :: as) (ltZS m))
>     | (k, max) with (totalPre tp a' max)
>       | (Left  _) = (FS k, max)
>       | (Right _) = (FZ, a')
>
>   max : {A : Type} ->
>         TotalPreorder A -> Vect n A -> .(LT Z n) -> A
>   max tp as p = snd (argmaxMax tp as p)

> namespace VectorProperties
>   instance Uninhabited (Elem {a} x Nil) where
>     uninhabited Here impossible
>     uninhabited (There p) impossible
>     
>   %assert_total
>   maxElemLemma : {A : Type} ->
>                  (tp : TotalPreorder A) ->
>                  (as : Vect n A) -> (p : LT Z n) ->
>                  Elem (max tp as p) as
>   maxElemLemma {n = Z}       tp  Nil                p = absurd p
>   maxElemLemma {n = S Z}     tp (a :: Nil)          p = Here
>   maxElemLemma {n = S (S m)} tp (a' :: (a'' :: as)) p with (argmaxMax tp (a'' :: as) (ltZS m)) proof itsEqual
>     | (k, max) with (totalPre tp a' max)
>       | (Left   _) = replace {P = \rec => Elem (snd rec) (a' :: (a'' :: as))}
>                              (sym itsEqual)
>                              (There (maxElemLemma tp (a'' :: as) (ltZS m)))
>       | (Right  _) = Here
>
>   mapIdfLemma : {A, B : Type} -> (as : Vect n A) -> (f : A -> B) ->
>                 (ab : (A,B)) -> Elem ab (map (pair (Prelude.Basics.id,f)) as) ->
>                 f (fst ab) = snd ab
>   mapIdfLemma  Nil      f  ab     p        = absurd p
>   mapIdfLemma (a :: as) f (a, _)  Here     = Refl
>   mapIdfLemma (a :: as) f  ab    (There p) = mapIdfLemma as f ab p

The actual example

> argmaxMax : {A, B : Type} -> 
>             TotalPreorder B -> 
>             (fA : Finite A) -> 
>             (ne : NonEmpty fA) -> 
>             (f : A -> B) -> (A,B)
> argmaxMax {A} {B} tp fA nefA f = max (fromTotalPreorder2 tp) abs ltZn where
>   n    : Nat
>   n    = card fA
>   ltZn : LT Z n
>   ltZn = notZisgtZ nefA
>   abs  : Vect n (A,B)
>   abs  = map (pair (id, f)) (toVect fA)

> max : {A, B : Type} ->
>       TotalPreorder B -> 
>       (fA : Finite A) -> 
>       (ne : NonEmpty fA) -> 
>       (f : A -> B) -> B
> max tp fA nefA f = snd (argmaxMax tp fA nefA f)

> argmax : {A, B : Type} ->
>          TotalPreorder B -> 
>          (fA : Finite A) -> 
>          (ne : NonEmpty fA) -> 
>          (f : A -> B) -> A
> argmax tp fA nefA f = fst (argmaxMax tp fA nefA f)

> argmaxSpec : {A, B : Type} -> 
>              (tp : TotalPreorder B) -> 
>              (fA : Finite A) -> 
>              (nefA : NonEmpty fA) -> 
>              (f : A -> B) ->
>              (max tp fA nefA f) = f (argmax tp fA nefA f)
> argmaxSpec {A} {B} tp fA nefA f = s3 where
>   ab : (A,B)
>   ab = argmaxMax tp fA nefA f
>   s1 : Elem ab (map (pair (id, f)) (toVect fA))
>   -- s1 : Elem ab (map (pair (Prelude.Basics.id, f)) (toVect fA))
>   s1 = maxElemLemma (fromTotalPreorder2 tp) (map (pair (id, f)) (toVect fA)) (notZisgtZ nefA)
>   s2 : f (fst ab) = snd ab
>   s2 = mapIdfLemma (toVect fA) f ab s1
>   s3 : max tp fA nefA f = f (argmax tp fA nefA f)
>   s3 = sym s2
```
At this point I know that failures to type check under 0.9.19.1 are most likely due to the new name-resolution rules and I could spot the error (in the declaration of `s1` at line 176)  easily. But the context is not completely trivial and in a normal workflow the error might be hard to find. Here, again, it would be useful to have a message pointing at `id` rather than at `map`. Ciao, Nicola
