### ISSUE TITLE
Behaviour of Dependent Records and setting value in the type.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#2675]
Unless I have missed something in the prescribed behaviour for records, it is unclear how to specify the value in the type from a record's constructors if that value is a field in the record. For example, given the code:

```idris
data FTy = A | B | C

namespace Works
  record Foobar (x : FTy) where
    constructor MkFB
    foo : String
    bar : Nat
    ty  : FTy

namespace Undefined
  record Foobar (x : FTy) where
    constructor MkFB
    foo : String
    bar : Nat
    ty  : FTy
    tyB : FTy
```
The field `ty` in the namespace `Works` will be used to populate the value in the type. The following code works:

```idris
apples : Works.Foobar A
apples = MkFB "String" Z A
```

However, given the record defined in the namespace `Undefined`, it is not clear how we can specify which of the two given values is to be promoted to the type. If records were not to be used this problem is straightforward to solve. However, there will be cases in which one wants the `free` setters and getters.

**Comment by edwinb** [comment]
If you look at the type of Undefined.Foobar, you'll see what's expected. They just go in the order you give them. When you say "it is not clear" what would you expect it to be clear from? I think it is clear - you can use the order that they're given in the record declaration, or if that isn't clear, look at the type of the constructor.

I'm closing this since I don't think there is anything that needs fixing.

**Comment by david-christiansen** [comment]
> The field ty in the namespace Works will be used to populate the value in the type.

I sure hope not! My guess is that you're getting it for free by unification with the type declaration. Observe:
```
apples : Works.Foobar A
apples = MkFB "String" Z B
```

The elaboration of a declaration:
```
record R (a1 : t1) ... (an : tn) where
  constructor MkR
  f1 : s1
  ...
  f2 : s2
```
includes, along with getters and setters, the following datatype:
```
data R : (a1 : t1) -> ... -> (an : tn) -> Type where
  MkR :  {a1 : t1} -> ... -> {an : tn} ->
             (f1 : s1) -> ... -> (f2 : s2) -> R a1 ... an 
```
In other words, the fields do not become arguments to the type constructor at the end. It's simply not the case that, when the type of a field and the type of a parameter agree, that the field is promoted to a parameter or enforced to be equal to the parameter.

I agree with @edwinb that nothing needs fixing, but I think there was an extra misunderstanding that needed to be addressed.

**Comment by jfdm** [comment]
So my understanding of how dependent records works was amiss. Which I agree was the real problem here. It might be good at some point for someone who is aware of the prescribed behaviour to document said behaviour.
