### ISSUE TITLE
Document creating Data types in the Agda style

### ISSUE THREAD

**Issue by justjoheinz** [idris-lang/Idris-dev#2678]
The documentation on Data types just mentions the syntax for creating  data types in Haskell style (http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#data-types) , whereas most of the code in the tutorial and libraries uses Agda style data type creation. This does not seem to be documented anywhere.

**Comment by jfdm** [comment]
Mmmhh...i never noticed that. I think a paragraph at the start of the section introducing dependent types explaining the syntax wouldn't go a miss. If you feel like you can contribute such a paragraph, please feel free to do so.

**Comment by justjoheinz** [comment]
I am sorry. I will have to pass.

**Comment by edwinb** [comment]
In the Vectors section (http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#vectors) it says:

"This declares a family of types, and so the form of the declaration is rather different from the simple type declarations above. We explicitly state the type of the [...]"

I think at most one more sentence is needed here, if anything.
