### ISSUE TITLE
New type for Prelude.Nat.(-): not really an issue but a bugging question.

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2688]
In 0.9.19, the type of Prelude.Nat.(-) was 
```
Nat -> Nat -> Nat
```
In 0.9.19.1, the type of Prelude.Nat.(-) is
```
(m : Nat) -> (n : Nat) -> {auto smaller : LTE n m} -> Nat
```
Thus, the new `(-)` can be applied to a much "smaller" set of `Nat` pairs than the old one. At the same time the new implementation does not provide anything more than the old one: it seem that we have traded genericity for nothing. Am I missing something obvious? Thanks, Nicola

**Comment by david-christiansen** [comment]
I didn't make the change, so take this with a grain of salt. We've had new users showing up on IRC for some time asking why `10 - 17 = 0` on `Nat`, instead of it being disallowed or crashing. The new `(-)` is actually subtraction, rather than truncating subtraction, which is perhaps less surprising.

**Comment by LeifW** [comment]
The behaviour of the old one could be confusing, e.g. http://stackoverflow.com/questions/23519043/i-cant-prove-n-0-n-with-idris

**Comment by edwinb** [comment]
I changed it because I several people have been confused by the old behaviour, and it is hard to explain (not to mention ,often wrong...). The change was to add `-` to the `Neg` type class, for numbers which can be negated, which `Nat` can't.

If you really want the old behaviour, you can use `minus`, or you can regain the genericity by making `Nat` an instance of `Neg` locally.

**Comment by nicolabotta** [comment]
@edwinb : Thanks but using `minus` is not really a viable solution: I would loose all the advantages of infix notation which is the reason I used `(-)` instead of `minus` in the very beginning! I am not sure making `Nat` an instance of `Neg` locally is a good approach either: as you point out, `Nat`s cannot be negated. For the moment, I have added to the SDP framework a NatOperations.lidr file with
```
> module NatOperations
> %default total
> %hide (-)
> public (-) : Nat -> Nat -> Nat
> (-) = minus
```
This allows type checking part of the framework with 0.9.19.1 but I am not sure it is a good scheme. Best, Nicola

**Comment by david-christiansen** [comment]
What about using a different operator for truncating `Nat` subtraction? Perhaps something like `x -^ y` or `x --- y` or `x -/- y`?

**Comment by nicolabotta** [comment]
@LeifW : I think the new behavior is even more confusing: In the stackoverflow.com example, and sticking for a moment to the 0.9.19 definition of `(-)`, 
```
theorem1 : (n : Nat) -> (m : Nat) -> (n + (m - n)) = m
```
does not hold as the analysis of the counterexample `3 + (0 - 3) = 0` clearly shows. A natural way to "correct" `theorem1` is to explicitely add the needed assumption, something like
```
theorem1' : (n : Nat) -> (m : Nat) -> n `LTE` m -> (n + (m - n)) = m
```
This function is now easily implementable. At lines 204-326 of https://github.com/nicolabotta/SeqDecProbs/blob/master/frameworks/14-/NatProperties.lidr, we have collected a number of similar properties of the "old" `(-)`, among others one equivalent to `theorem1':
```
> plusRightInverseMinus : (m : Nat) -> (n : Nat) -> m `LTE` n -> (n - m) + m = n
```
Another way of "correcting" `theorem1` is by changing the definition of `(-)` which is what happened between 0.9.19 and 0.9.19.1. In fact, the change incorporates the additional `LTE n m` requirement as an (implicit!) argument of the new infix subtraction. This "cures" your original problem but has two disadvantages:

First, we now have two subtraction operation on `Nat` pairs: a generic `minus` and a less generic infix `(-)`. Letting apart the problem or breaking legacy code, the new situation naturally raises the question, on the user's side, of which subtraction should be used in application-level code and, on the developer's side, of which subtraction should be equipped with "guarantees" of the kind of `theorem1`. I am afraid there is no answer to this question. If `minus` and `(-)` are meant to be both first-class operations on pairs of `Nat`s, one should probably derive results for both. This might lead to redundancies and duplications of efforts. Moreover, if both `minus` and `(-)` are first-class citizen, it seems to me that it would be better to name them `minus1` and `minus2` and let users decide which one should be promoted to `(-)` to enjoy the convenience of infix notation in application-level code. 

Second, I very much doubt that hiding the `LTE n m` constraint of `theorem1` into an implicit argument of `(-)` is beneficial to code understandability, reusability and maintenance: `theorem1` does hold for a well defined subset of `Nat x Nat` (or perhaps, more generally, for types in |Neg|). This subset is an essential notion here and deserves to be well visible in the signature of `theorem1`!

**Comment by nicolabotta** [comment]
> What about using a different operator for truncating Nat subtraction? Perhaps something > like x -^ y or x --- y or x -/- y?
Thanks David, but I think the problem I am trying to address is a bit more general and does not necessarily require an urgent fix. My main concern is not legacy code: for that, we have a pragmatic solution which seems to work. But I am not sure it is a good idea to have multiple versions of Nat.minus or, in fact, any version at all. Also, it seems to me that LeifW `theorem1` should neither read
```
theorem1 : (n : Nat) -> (m : Nat) -> (n + (m - n)) = m
```
nor
```
theorem1 : (n : Nat) -> (m : Nat) -> n `LTE` m -> (n + (m - n)) = m
```
but rather something like
```
theorem1 : (Neg T) => (n : T) -> (m : T) -> n + (m - n) = m
```
In fact, it seems to me that
```
class Num a => Neg a where                                                                                                         
    negate : a -> a                                                                                            
    (-) : a -> a -> a
    abs : a -> a 
```
is incomplete and should be complemented by, at least, something like
```
    negateMinusLemma : (x, y : a) -> x + (negate y) = x - y           
```
This brings us back to the question of the role of type classes in Idris or, more, generally, to the question of how one could express and take advantage of specifications in Idris. In a post on idris-lang, I have argued that interfaces like
```
> gcd : Nat -> Nat -> Nat

> gcdSpec1 : (m : Nat) -> (n : Nat) -> gcd m n `Divisor` m
> gcdSpec2 : (m : Nat) -> (n : Nat) -> gcd m n `Divisor` n
> gcdSpec3 : (m : Nat) -> (n : Nat) -> (d : Nat) ->
>            d `Divisor` m -> d `Divisor` n -> d `Divisor` gcd m n
``` 
could be extremely useful for coordinating developers and contributors on precise tasks and for building unambiguous community notions. If this can be achieved by type classes the better. Best, Nicola

**Comment by edwinb** [comment]
Since this isn't really an issue with a clearly defined way of resolving it, I'm going to close it - questions of type class and library design are quite tricky and we're not pretending they're right yet, and the question of what properties, if any, should be included with a type class is particularly tricky.

Not that that means the discussion should stop, of course. Just that the mailing list might be a better place for it.
