### ISSUE TITLE
No parser error for missing fixities for data constructors

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#2696]
This definition gives a (moderately) friendly error:

```
(+++++++++) : Nat -> Nat -> Nat

- + Errors (1)
 `-- ./Infix.idr line 5 col 0:
      error: Missing
         fixity declaration for
         Infix.+++++++++, expected: "->",
         ";",
         ambiguous use of a left-associative operator,
         ambiguous use of a non-associative operator,
         ambiguous use of a right-associative operator,
         matching application expression
     <EOF> 
     ^     
```

This one does not, but should:

```
data Thing : Type where
  (+++++++++) : Nat -> Nat -> Thing
```

Instead, it will fail when used. The Idris policy is to require fixity declarations, so we should require one here as well.

**Comment by mietek** [comment]
Thanks!

**Comment by BartAdv** [comment]
I think that's the same as: https://github.com/idris-lang/Idris-dev/issues/3275

**Comment by arianvp** [comment]
Yes its the same

**Comment by SantiagoBautista** [comment]
I suggest closing this issue, as #3275 has been solved and closed and referenced the same problem.

**Comment by ahmadsalim** [comment]
@BartAdv @arianvp @SantiagoBautista Thanks for the notice.
