### ISSUE TITLE
:elab `search` fails with non-exhaustive patterns in `autoArg`

### ISSUE THREAD

**Issue by cbiffle** [idris-lang/Idris-dev#2705]
Found in 13045109d058b248a2fc69c786a969b9d14f4b85.

Given this code:

```idris
module IntroFail

import Pruviloj
import Pruviloj.Induction

||| A Boolean expression.
data BExp : Type where
  BTrue : BExp
  BFalse : BExp
  BAnd : BExp -> BExp -> BExp

||| Evaluation function for Booleans.
beval : BExp -> Bool
beval BTrue = True
beval BFalse = False
beval (BAnd x y) = beval x && beval y

||| An identity transform.
bid : BExp -> BExp
bid (BAnd x y) = BAnd (bid x) (bid y)
bid x = x

||| Proof that the identity transform really is one.
bid_id : (b : BExp) -> beval b = beval (bid b)
bid_id b = ?bid_id_rhs
```

...let's attempt to solve the `?bid_id_rhs` hole using the `:elab` shell.

Sequence of commands below with light comments after hash signs.  (This is wordier than it needs to be, but bear with me.)

```
:elab IntroFail.bid_id_rhs
intro `{{b}}
induction (Var `{{b}})
search  # discharge the BTrue case
search  # discharge the BFalse case
attack  # magic lambda powers activate
compute  # declutter things
intro `{{x}}  # LHS of BAnd
intro `{{iX}}  # induction hypothesis on x
intro `{{y}}  # RHs of BAnd
intro `{{iY}}  # induction hypothesis on y
rewriteWith (Var `{{iX}})
attack  # seems necessary
rewriteWith (Var `{{iY}})
search  # discharged, up a level
```

I'm now left with this state:

```
----------              Other goals:              ----------
{BAnd178}
----------              Assumptions:              ----------
 b : BExp
 x : BExp
 iX : beval x = beval (bid x)
 y : BExp
 iY : beval y = beval (bid y)
----------                 Goal:                  ----------
{hole85} : beval x && Delay (beval y) =
           beval x && Delay (beval (bid y)) =?= replace iY Refl
```

Hm, due to my own ignorance, I'm not really sure what to do with this `=?=`, so lemme try `search`, which has been working *really well* so far.  (Not sarcasm -- I love `search`.)

```
-IntroFail.bid_id_rhs> search
src/Idris/Core/ProofState.hs:(413,1)-(420,36): Non-exhaustive patterns in function autoArg

Holes: IntroFail.bid_id_rhs, IntroFail.bcomm_sound_rhs
```

Uh-oh.  Not only did `search` not work, but the proof shell bombed out, apparently losing my work.

From casual inspection of `autoArg`, it's partial, only accepting the `Bind` constructor of `TT` (here masquerading as `Term`), but it's apparently being handed... something else.  Haskell's notoriously helpful runtime error messages leave it to the imagination.

**Expected behavior:** the fact that this partial function is being applied outside its expected domain seems like a pretty clear bug, but in addition, I'd suggest that (if the elab shell is operating in a monad where this is possible) catching such errors *without* losing state would be preferable.

**Comment by david-christiansen** [comment]
Indeed, this should give a reasonable error message rather than crashing!

What you're looking for here is `solve`, btw.
