### ISSUE TITLE
Higher Order Effectful Functions have 'issues'

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#2706]
A user recently reported this issue on the mailing list, and it is something I have experienced in the past. So given a Higher Order Effectful Function such as `mapE` and used as follows:

```idris
module Temp

import Effects
import Effect.System
import Effect.Random

rndList : Eff (List Integer) [RND, SYSTEM]
rndList = do
    srand !time
    mapE (rndInt 0) $ List.replicate 3 100
```

will present an error along the lines of:

```
 `-- Temp.idr line 10 col 20:
     When checking right hand side of rndList:
     When checking an application of function Effects.mapE:
             Type mismatch between
                     Integer -> Eff Integer [RND] (Type of rndInt _)
             and
                     a ->
                     EffM m
                          Integer
                          [RND, SYSTEM]
                          (\result => [RND, SYSTEM]) (Expected type)
             
             Specifically:
                     Type mismatch between
                             EffM m1 Integer [RND] (\v => [RND])
                     and
                             EffM m Integer [RND, SYSTEM] (\result => [RND, SYSTEM])
```

If we take the partially applied function `rndInt` and surround it in an anonymous function with the required parameters, the code compiles as expected. For example:

```idris
mapE (\x => rndInt 0 x) $ List.replicate 3 100
```

I believe Idris has issues trying to work out the type of `rndInt` when partially applied w.r.t to the function type expected to be passed into `mapE`.

**Comment by edwinb** [comment]
I wouldn't expect this to work, because the type of `rndInt` has one effect, and the surrounding context requires two effects, and the implicit conversion `lift` isn't going to happen because `rndInt` isn't fully applied. So this is expected behaviour, even if it's not the behaviour you want.

**Comment by jfdm** [comment]
Makes sense, good to have an answer. Will close the issue.
