### ISSUE TITLE
Allow dashes in package names

### ISSUE THREAD

**Issue by shlevy** [idris-lang/Idris-dev#2721]
Unless there's some ambiguity introduced when doing so? I note that every project owned by @idris-lang has a dash in its name :wink:

**Comment by shlevy** [comment]
Also in `executable` names

**Comment by jeremy-w** [comment]
+1 from me. I'd expect the changes for generated executable names wouldn't be terribly invasive.

**Comment by jeremy-w** [comment]
Executable names:

- `PParser.hs:pClause` parses the executable name as an `iName`.
- `ParseHelpers.hs:iName`'s docstring says that it "Parses an identifier with possible namespace as a name". This is kind of a weird choice for an executable parser! But you can indeed name your executable like "executable.with.dots.in.it".

It looks like adding a parser for a valid filename, and using that instead of `iName`, would fix this.

**Comment by jeremy-w** [comment]
I have the executable name bit almost working, except I'm leaving the quote marks around the executable name. `cabal install` takes so long that I won't be able to resolve and test this tonight.

**Comment by jeremy-w** [comment]
I think I've fixed it, but it remains to add a test to the test suite. Work so far is available [on this branch](https://github.com/jeremy-w/Idris-dev/tree/jeremy-w/ipkg-allow-arbitrary-executable-names-2721).

**Comment by david-christiansen** [comment]
This has annoyed me for a while, but never enough to do anything about it. Thanks for taking initiative!

**Comment by shlevy** [comment]
@edwinb Is this something you'd prefer not to be in the issue tracker?

**Comment by ahmadsalim** [comment]
I think this has been fixed in #2728.

**Comment by jfdm** [comment]
i tried this the other day, and a package name with a hyphen was rejected... I am inclined to reopen this issues if other people are seeing this error.

**Comment by ahmadsalim** [comment]
@jfdm You have to add quotes around the name.

**Comment by jfdm** [comment]
ah okay, we should update the docs...

**Comment by ahmadsalim** [comment]
@jfdm Yeah, I had to look at the source to figure it out :).

**Comment by jeremy-w** [comment]
Ah, changelog should have noted it, but other docs likely still need updating. IIRC at the time I had to look at the source to figure out how IPKG worked in general, and expected eventually to convert that knowledge into proper docs.

Maybe we should open a new issue to update the IPKG docs about this?

**Comment by jfdm** [comment]
@jeremy-w As I understand it, the iPKG docs have been sufficient for a long time over the general use of the iPKG format. For your issue, however, they were not clear as to the prohibited and allowed characters for executables and names. Hence, why you 'had to look at the source' to know what was permissible.

Naturally, the docs should be updated to document the allowed names.

**Comment by jfdm** [comment]
Actually, looking at the code for the iPKG parser, package names are parsed using `identifier`, and not the `filename`. Technically this, issue should be reopened as package names do not allow a dash.

**Comment by jfdm** [comment]
also @ahmadsalim See the latest couple of PRs from myself. They should address package names, and documentation of executable names.

**Comment by ahmadsalim** [comment]
@jfdm OK, thanks! Please close the issue when you merge your PRs :).
