### ISSUE TITLE
Pruviloj takes ages to install

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris-dev#2730]
This is due to chasing up modules in the other Idris libraries, which it shouldn't really be doing because they're already built by then.

This is mostly a problem because it slows down the build/test cycle (building and installing the libraries, even when they're already completely built, takes several minutes) but it probably indicates a problem elsewhere that we should take a closer look at.

**Comment by david-christiansen** [comment]
Hear hear! This issue is quite annoying!

**Comment by edwinb** [comment]
in fact it turns out the underlying problem is that when the module tree is a graph (so, basically always for any interesting project) it won't reuse what it's learned about the part of the tree it's already explored. If we cache these, suddenly everthing is rather quicker...

I'll push a patch once I've convinced myself I haven't broken anything odd on the way.

**Comment by edwinb** [comment]
Well I didn't mean to fix this immediately, or I wouldn't have reported it, but it was sufficiently annoying that I did it anyway. So things should be much better now.

**Comment by david-christiansen** [comment]
Thanks so much! Thesis-writing-induced library iterations will be far less unpleasant now :-)

**Comment by david-christiansen** [comment]
I can confirm that it's now far more pleasant to rebuild everything. Thanks again!
