### ISSUE TITLE
"No such variable m" error when no m is referenced

### ISSUE THREAD

**Issue by shlevy** [idris-lang/Idris-dev#2731]
src/Lambductive/Term2.idr:

``` Idris
module Lambductive.Term2

import Data.Fin

%default total

data Context : Nat -> Type

data TypeTerm : Context n -> Type

data Context : Nat -> Type where
  Empty : Context Z
  Snoc : (ctx : Context n) -> TypeTerm ctx -> Context (S n)

drop : (n : Nat) -> Context (n + m) -> Context m
drop Z ctx = ctx
drop (S k) (Snoc ctx _) = drop k ctx

insertAt : (n : Nat) -> (ctx : Context (n + m)) -> TypeTerm (drop n ctx) -> Context (S (n + m))

data ValueTerm : TypeTerm ctx -> Type

data TypeTerm : Context n -> Type where
  SuccType : TypeTerm ctx -> TypeTerm (insertAt n ctx type)
  U : TypeTerm ctx
  El : ValueTerm {ctx = ctx} U -> TypeTerm ctx
  Pi : (A : TypeTerm ctx) -> TypeTerm (Snoc ctx A) -> TypeTerm ctx

insertAt Z ctx type = Snoc ctx type
insertAt (S k) (Snoc ctx head) type = Snoc (insertAt k ctx type) (SuccType head)

index : (n : Nat) -> (ctx : Context (S (n + m))) -> TypeTerm ctx
index Z (Snoc _ type) = SuccType {n = Z} type
index (S k) (Snoc ctx _) = SuccType {n = Z} (index k ctx)

data TypeEquivalence : TypeTerm ctx -> TypeTerm ctx -> Type

data ValueTerm : TypeTerm ctx -> Type where
  SuccValue : ValueTerm type -> ValueTerm (SuccType type)
  TransportType : TypeEquivalence type1 type2 -> ValueTerm type1 -> ValueTerm type2
  Var : (idx : Nat) -> ValueTerm (index idx ctx)

data TypeEquivalence : TypeTerm ctx -> TypeTerm ctx -> Type where
  SuccU : TypeEquivalence (SuccType U) U
  SuccEl : TypeEquivalence (SuccType (El code)) (El (TransportType SuccU (SuccValue {type = U} code)))
  SuccPi : TypeEquivalence (SuccType {n = n} (Pi a b)) (Pi (SuccType a) (SuccType {n = S n} b))
```

> $ idris --check src/Lambductive/Term2.idr 
> ./src/Lambductive/Term2.idr:46:10:No such variable m
> 
> $ awk 'NR==46' src/Lambductive/Term2.idr 
>   SuccPi : TypeEquivalence (SuccType {n = n} (Pi a b)) (Pi (SuccType a) (SuccType {n = S n} b))

**Comment by shlevy** [comment]
Note: I've determined the 'm' referenced here is the m in `insertAt`'s type signature, via the `insertAt` call in `SuccType`'s type.

**Comment by TimRichter** [comment]
Hi,

I must admit I have no idea what your code is supposed to do and also
don't know too much about idris, but anyway...

It seems what you are trying to do are (heavily!) mutual declarations. 
I changed your code to

    module Lambductive.Term2
    
    import Data.Fin
    
    %default total
    
    mutual
      data Context : Nat -> Type where
        Empty : Context Z
        Snoc : (ctx : Context n) -> TypeTerm ctx -> Context (S n)
      
      data TypeTerm : Context n -> Type where
        SuccType : TypeTerm ctx -> TypeTerm (insertAt n ctx type)
        U : TypeTerm ctx
        El : ValueTerm {ctx = ctx} U -> TypeTerm ctx
        Pi : (A : TypeTerm ctx) -> TypeTerm (Snoc ctx A) -> TypeTerm ctx
    
      data ValueTerm : TypeTerm ctx -> Type where
        SuccValue : ValueTerm type -> ValueTerm (SuccType type)
        TransportType : TypeEquivalence type1 type2 -> ValueTerm type1 -> ValueTerm type2
        Var : (idx : Nat) -> ValueTerm (index idx ctx)
      
      data TypeEquivalence : TypeTerm ctx -> TypeTerm ctx -> Type where
        SuccU : TypeEquivalence (SuccType U) U
        SuccEl : TypeEquivalence (SuccType (El code)) 
                                 (El (TransportType SuccU (SuccValue {type = U} code)))
        SuccPi : TypeEquivalence (SuccType {n = n} (Pi a b)) 
                                 (Pi (SuccType a) (SuccType {n = S n} b))
    
      drop : (n : Nat) -> Context (n + m) -> Context m
      drop Z ctx = ctx
      drop (S k) (Snoc ctx _) = drop k ctx
    
      insertAt : {m : Nat} -> (n : Nat) -> (ctx : Context (n + m)) -> 
                TypeTerm (drop n ctx) -> Context (S (n + m))
      insertAt Z ctx type = Snoc ctx type
      insertAt (S k) (Snoc ctx head) type = Snoc (insertAt k ctx type) (SuccType head)
    
      index : (n : Nat) -> (ctx : Context (S (n + m))) -> TypeTerm ctx
      index Z (Snoc _ type) = SuccType {n = Z} type
      index (S k) (Snoc ctx _) = SuccType {n = Z} (index k ctx)

It doesn't typecheck yet, but at least the syntax is accepted.

Regards,
Tim

P.S. The issue tracker is probably not the right place to discuss this.

**Comment by shlevy** [comment]
You don't think the quoted error message is a bug? I'm not saying there isn't an error in this code, there absolutely is, but the message should be different.

**Comment by TimRichter** [comment]
Oh, that's not what I'm saying. Of course these messages are an issue,
and one the developers are well aware of (compare e.g. #1887).

But I think your code is too complicated to be helpful in exploring and
fixing the problem. 

I'm still wondering why your method of doing mutual declarations 
without using the "mutual" keyword is accepted. I opened a
new issue for that: #2752.

Best,
Tim

**Comment by shlevy** [comment]
Oh, sure, if I could have reproduced the issue in a simpler case I would have. @edwinb I know you're looking to clean up issues generally recently, is this kind of issue (which is about the error message itself, not the fact that my code has an error) something you'd want to keep open?

**Comment by edwinb** [comment]
This error message is particularly irritating, because it's both completely correct and completely useless. Let's leave this one open for the moment, as it's a useful example of the sort of problem, and perhaps I'll consolidate similar things into one issue later (or, even better, get around to fixing it :)).

Usually it means that unbound implicits have turned up in the wrong order and you need to give it a bit of a hint, using {}. This indicates an underlying problem (but one I'm unlikely to look at in the immediate future, sorry...)
