### ISSUE TITLE
Proposal: Annotate prelude with %used

### ISSUE THREAD

**Issue by lenary** [idris-lang/Idris-dev#2743]
I've been doing some work on my erlang backend, and it seems possible to confuse the erasure system into such a way that it thinks `List.::` doesn't take any arguments once it's got to code generation.

I can only assume this is because the uses of cons it inspects is full of proof-terms, not values, and thus every part can be erased. I guess this is partly a bug in erasure, that it doesn't analyse later uses of cons to check if they are full of values.

Given the `%used` annotation exists, is it worth using everywhere in the prelude? I'm happy to make the code changes, just wanted to get a go-ahead before I did. 

I guess if `%used` is still considered to be a hack, rather than a feature, then this is probably a bad idea.

**Comment by david-christiansen** [comment]
I'm a bit confused by your issue - is the problem that no uses of the head or tail arguments to `::` are runtime relevant, causing their erasure, which breaks some assumptions about `List` in the Erlang backend, or is the problem that there are indeed runtime-relevant uses of the head and the tail, but they are getting erased anyway?

**Comment by lenary** [comment]
So, after further discussion with @ziman, it turns out that there were various things leading to the issue.

- It was an example program, all lists were being passed to a foreign function as their only "usage"
- Erasure can't actually look *through* a foreign function, because of a few reasons. Firstly, if it assumed all constructor arguments were used, it would keep type information around (the first argument of `::`). Secondly, if it assumes none are used, it would keep no arguments around, also not quite what is expected. What is expected is that the last 2 arguments are kept, which is not generally deducible. 

This leads me to think annotating all data constructors in the prelude with the correct `%used` annotations would be useful, and would allow backends to assume their presence when used in foreign function interfaces, including if a backend wanted to special-case any prelude items.

I *don't* think that we need to annotate anything outside of prelude, because there isn't quite the same assumption about presence in that code as there is for code inside the prelude.

Upon further inspection, some declarations of the form `data List e = Nil | (::) e (List e)` may need to be changed so I can name the two arguments, so changing to the form below. Currently running tests to see if this breaks anything.

```
||| Generic lists
%elim data List : (elem:Type) -> Type where
  ||| Empty list
  Nil : List elem
  ||| A non-empty list, consisting of a head element and the rest of
  ||| the list.
  (::) : (e : elem) -> (l : List elem) -> List elem

-- Name hints for interactive editing
%name List xs, ys, zs, ws

-- Usage hints for erasure
%used (::) e
%used (::) l
```

**Comment by ziman** [comment]
BTW, you just need to annotate those types that are special-cased in the compiler or back-ends to keep their erasure consistent with the assumptions.

**Comment by lenary** [comment]
@ziman yes, but I propose annotating all types in the prelude with %used, so that any backend implementer can use them.  I've done so, PR incoming once I fiddle about with some tests, because apparently %name doesn't work if you've already named the parameter. :(

**Comment by ziman** [comment]
This seems to call for a type-based annotation system. ;)

**Comment by david-christiansen** [comment]
@lenary Won't this prevent opportunistic optimization on backends that don't special-case Prelude types for their FFIs?

**Comment by lenary** [comment]
@david-christiansen yes. I believe ziman has a suite of programs that are much improved with erasure (including an example that drops a complexity class), I'll ask him to test my changes when i finish them, to see if they still get the massive wins. 

At the moment I'm running into problems with %name and interactivity. Sigh.

**Comment by ziman** [comment]
The whole point of erasure is to prevent heavily indexed programs from dropping down complexity classes because of surprisingly big invisible data.

If you annotate everything in Prelude, you shouldn't cause that problem, it's just that sometimes it happens that e.g. `Either` compiles down just to `Left` and `Right`, effectively becoming `Bool` at runtime.

Annotations as you propose them would disable this (admittedly surprising) opportunistic improvement.

**Comment by ziman** [comment]
Alternatively, you can special-case your special-case and only compile `(::)` to Erlang lists if its arity is 2.

**Comment by lenary** [comment]
Yeah, given my %name issues, I'll just actually do the stupid hack properly.

**Comment by lenary** [comment]
@ziman actually, i've been thinking more about this. I can't provide '%used' annotations inside my module, because the constructor does not name its variables, and then this interacts with '%name' weirdly.

Furthermore, it's very odd for backend designers to have to write FFI conversions for datatype constructors if they can't even be sure of the arity of those constructors. If (::) takes no arguments, how is a backend supposed to deal with converting between the idris term and the term the foreign function is expecting? 

I still think this is an issue, and that annotating the prelude is actually a sensible way forwards. Good job I didn't delete my branch.

**Comment by jfdm** [comment]
This appears to be fixed now. So closing.
