### ISSUE TITLE
trouble with "with"

### ISSUE THREAD

**Issue by TimRichter** [idris-lang/Idris-dev#2744]
Hi all,

in the following code ?lulu and ?lolo can be filled with Refl. For ?lala I'd like
to do the same, but this doesn't work (in idris 0.9.19.1).

    import Data.Fin
    
    mapsFinToBoolDicho : {n : Nat} -> 
                         (f : Fin n -> Bool ) ->
                         Either (x : (Fin n) ** (f x = True)) ()
    mapsFinToBoolDicho {n=Z} f = Right ()
    mapsFinToBoolDicho {n=(S n')} f with (f FZ)
          | True  = Left (FZ ** ?lala)
          | False = Right ()
    
    mapsUnitToBoolDicho : (f : () -> Bool) -> 
                          Either (f () = True) (f () = False)
    mapsUnitToBoolDicho f with (f ())
          | True   = Left ?lulu
          | False  = Right ?lolo

The type of lulu is True = True , that of lolo is False = False. 
"Sure, (f ()) has been reduced according to the matching" is 
(or better was) how I explained that to me.

In lala, however, a reduction of (f FZ) to True does not happen:

    *testWithrule> :t lala
      n' : Nat
      f : Fin (S n') -> Bool
    --------------------------------------
    lala : f FZ = True

In fact, nothing in the type indicates that we are in a branch where (f FZ) has been 
matched with True...  And of course there isn't a chance to prove this lala.

Best,
Tim

**Comment by david-christiansen** [comment]
Hello Tim,

>     import Data.Fin
>     
>     mapsFinToBoolDicho : {n : Nat} -> 
>                          (f : Fin n -> Bool ) ->
>                          Either (x : (Fin n) ** (f x = True)) ()
>     mapsFinToBoolDicho {n=Z} f = Right ()
>     mapsFinToBoolDicho {n=(S n')} f with (f FZ)
>           | True  = Left (FZ ** ?lala)
>           | False = Right ()


Try this:

mapsFinToBoolDicho : {n : Nat} -> 
                     (f : Fin n -> Bool ) ->
                     Either (x : (Fin n) ** (f x = True)) ()
mapsFinToBoolDicho {n=Z} f = Right ()
mapsFinToBoolDicho {n=(S n')} f with (f FZ) proof prf
  | True  = Left (FZ ** sym prf)
  | False = Right ()

The "proof" keyword provides a propositional equality between the
original case and the pattern branch. It's in the wrong order, so we
need "sym".

/David

**Comment by TimRichter** [comment]
Hello David,

great, thank you! I should read the docs...
Tim

**Comment by shlevy** [comment]
Is the `with (exp) proof prf` thing documented anywhere? I've only ever seen `with (exp)` (at http://docs.idris-lang.org/en/latest/tutorial/views.html#sect-nattobin)

**Comment by shlevy** [comment]
Looks like 40d094dda971b24e4ee43eea4854e819873cc6f introduced it

**Comment by TimRichter** [comment]
I just supposed it was in the docs somewhere, but didn't find it either...

**Comment by edwinb** [comment]
I don't think I ever documented it. I added it to fix a similar problem a while ago... What we really need is a complete (if perhaps terse) language reference. Don't all volunteer at once though :).
