### ISSUE TITLE
Case inside do block interferes with effects typechecking

### ISSUE THREAD

**Issue by shlevy** [idris-lang/Idris-dev#2756]
```idris
import Effects
import Effect.StdIO

test : Bool -> Eff () [STDIO]
test b = do
  putStr "Bool is: "
  case b of
    True => putStr "true"
    False => putStr "false"
  putStr "!"
```

fails to typecheck with

```console
$ idris -p effects --check test.idr 
test.idr:8:5-9:
When checking right hand side of Main.case block in test at test.idr:7:8:
Type mismatch between
        EffM m () [STDIO] (\v => [STDIO]) (Type of putStr "true" m)
and
        EffM m a [STDIO] (\bindx => [STDIO]) (Expected type)

Specifically:
        Type mismatch between
                ()
        and
                a
```

**Comment by david-christiansen** [comment]
This is a problem in general for case expressions inside of a do. If it's not the last thing in the do, then the type is general (hence the a), but you fill it with something specific.

The solution here is:
```
test : Bool -> Eff () [STDIO]
test b = do
  putStr "Bool is: "
  the (Eff () [STDIO]) $
    case b of
      True => putStr "true"
      False => putStr "false"
  putStr "!"
```

**Comment by shlevy** [comment]
Aah, I see, thanks.

**Comment by jfdm** [comment]
actually, as a point of style and design. I think using the `the` function here is not the most idiomatic way. Personally, when not the last expression in a `do` block I would extract the `case` statement into a separate function defined either in a `where` block or as a top level function in its own right.
