### ISSUE TITLE
Typecheck error messages are difficult to interpret

### ISSUE THREAD

**Issue by Legogris** [idris-lang/Idris-dev#2763]
Test case: 
```
module Main
import Effects
import Effect.State
import Control.IOExcept

User : Type -> Type
User rTy = Eff rTy [STATE (List Nat)]

myProg : User Bool
myProg = do put Nil; return True

runProg : User ()
runProg = do myProg; return ()


namespace Main
  main = runInit [["x"]] runProg
```

This doesn't typecheck, because the inital resource is a List String instead of a List Nat.

If I gave an invalid resource in release `0.9.19.1`, I just got in uninformative error message about 
`IO' (MkFFI C_Types String String)`. Now (`0.9.19.1-git:f0f1d72`), I get an extremely verbose error message that is difficult to make sense of (Not included since it's a nest of `case block in ioe_run` etc that is 134K in size, 60K after cutting away redundant whitespace).

In this particular case it's possible to realize what's wrong by looking closely at the verbose output, but I found this out from an actual problem that is a little bit more complex where I am completely unable to make sense of the output.

Possibly related to #2729 and 83f0af13fba5498ed4ac7c3944ff36701b6e00b6?

**Comment by edwinb** [comment]
This was caused by something I was playing with that turns out to have been a bad idea, and for uninteresting reasons, only importing Control.IOExcept triggered it. I undid the thing that caused it so I can't reproduce this in master now.
