### ISSUE TITLE
Idris suggests wrong case split

### ISSUE THREAD

**Issue by justjoheinz** [idris-lang/Idris-dev#2764]
Given 
```idris
module Article
import Data.Fin

data Article: (quantity: Nat) -> Type where
      MkArticle:  (name:String) -> (quantity: Nat) -> Article quantity
data Avail = IsNotAvail | IsAvail

availability:  Article n -> Avail
availability article = ?availability_rhs
```

and proceeding with case splits one arrives at:
```idris
availability:  Article n -> Avail
availability (MkArticle name Z) = ?availability_rhs_2
availability (MkArticle name (S k)) = ?availability_rhs_3
```

which in turn results in a compile error.
` When checking left hand side of availability:
      When checking argument quantity to constructor Elem.MkArticle: Type mismatch between n (Inferred value) and 0 (Given value)`

It was suggested on ICQ that idris is proposing an invalid case split here, as Article Z cannot be a Z or S n.
A gist with the code is here: https://gist.github.com/justjoheinz/b2117aa605b5ef79ceab

**Comment by david-christiansen** [comment]
This shouldn't be happening - it should case-split `n` as well.

Indeed, making `n` visible makes the type checker accept it:
```
availability:  Article n -> Avail
availability {n = Z}   (MkArticle name Z) = ?availability_rhs_2
availability {n = S k} (MkArticle name (S k)) = ?availability_rhs_3
```

**Comment by david-christiansen** [comment]
Thanks for the report!

**Comment by justjoheinz** [comment]
This might be related:
The code in https://www.youtube.com/watch?v=4i7KrG1Afbk at 17:01 by Brian McKenna also exhibits different case split behavior now.

It is essentially something like:
```idris
data BinChar: Char -> Type where
  O: BinChar '0'
  I: BinChar '1'

data Every: (a -> Type) -> List a -> Type where
  Nil: {P: a -> Type} -> Every P []
  (::): (P: a -> Type) ->  P x -> Every P xs -> Every P (x :: xs)

fromBinChars : Every BinChar xs -> Nat -> Nat
``` 
Again case splitting on xs results in compile errors:
```idris
Frombinchars : Every BinChar xs -> Nat -> Nat
Frombinchars [] k = ?Frombinchars_rhs_1
Frombinchars (BinChar :: y) z k = ?Frombinchars_rhs_2
```

**Comment by ahmadsalim** [comment]
This seems to work correctly now, so I will close it.
