### ISSUE TITLE
Clean up deprecated FFI mechanisms

### ISSUE THREAD

**Issue by jmitchell** [idris-lang/Idris-dev#2779]
In the Type Provider docs `sizeOfDevT` calls `mkForeign`, which apparently isn't available. Was it part of a deprecated FFI system?

There are a few other [lingering uses](https://github.com/idris-lang/Idris-dev/search?utf8=%E2%9C%93&q=mkForeign).

Unless the new FFI has a drop-in replacement for `mkForeign`, cleanup will involve additional functions and types.

**Comment by david-christiansen** [comment]
Yes, this is part of the old FFI. Thanks for catching it!

**Comment by jmitchell** [comment]
I've started work on this (see ebbae35323e8328757641eda2423fb867589c62b). There's a test to prove type providers and the new FFI are compatible. I can patch up the tutorial soon as well.
