### ISSUE TITLE
Install Failure: OS X Yosemite, trifecta-1.5.2

### ISSUE THREAD

**Issue by whiplash** [idris-lang/Idris-dev#2783]
I'm having issues installing idris.

When I run `cabal install idris` I get:
```
...
Loading package lens-4.9.1 ... <command line>: can't load .so/.DLL for: /Users/johnjohn/Library/Haskell/ghc-7.8.3-x86_64/lib/lens-4.9.1/libHSlens-4.9.1-ghc7.8.3.dylib (dlopen(/Users/johnjohn/Library/Haskell/ghc-7.8.3-x86_64/lib/lens-4.9.1/libHSlens-4.9.1-ghc7.8.3.dylib, 9): Symbol not found: _templatezmhaskell_LanguageziHaskellziTHziSyntax_zdfMonadQ4_closure
  Referenced from: /Users/johnjohn/Library/Haskell/ghc-7.8.3-x86_64/lib/lens-4.9.1/libHSlens-4.9.1-ghc7.8.3.dylib
  Expected in: /Library/Frameworks/GHC.framework/Versions/7.8.3-x86_64/usr/lib/ghc-7.8.3/bin/../template-haskell-2.9.0.0/libHStemplate-haskell-2.9.0.0-ghc7.8.3.dylib
 in /Users/johnjohn/Library/Haskell/ghc-7.8.3-x86_64/lib/lens-4.9.1/libHSlens-4.9.1-ghc7.8.3.dylib)
cabal: Error: some packages failed to install:
idris-0.9.19.1 depends on trifecta-1.5.2 which failed to install.
trifecta-1.5.2 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by whiplash** [comment]
Any hints on how to fix this?

**Comment by whiplash** [comment]
Am I the only one facing this issue?

**Comment by soimort** [comment]
Have you tried a cabal update, and reinstall lens (and possibly
template-haskell)?

Sometimes outdated dependencies won't build as API changes may break GHC
dynamic linking.

**Comment by whiplash** [comment]
I tried those things but to no avail.

**Comment by jfdm** [comment]
@whiplash Idris installs fine on my mac os x machine, so aside from the standard advice of: nuking cabal and starting again, or installing trifecta using cabal. I do not know what else could be of use. Sorry.

**Comment by whiplash** [comment]
Thanks @jfdm. That's what I had to do. All working fine now (it must've been something with the older version of Haskell Platform I had).

**Comment by jfdm** [comment]
@whiplash glad you got it sorted!
