### ISSUE TITLE
Meta002 test gets killed by travis-ci.org

### ISSUE THREAD

**Issue by lenary** [idris-lang/Idris-dev#2785]
As evidenced by this message, the meta002 test seems to get killed by travis-ci when running. (Parallel builds interleave output, but the "meta002 passed" is always printed after this killed message).

https://travis-ci.org/idris-lang/Idris-dev/jobs/86099125#L1091

After looking into this further, it seems to have originated in the builds for #2749 (the build linked, but appears in every test including meta002 since then), it doesn't appear in travis build 4111.

I have run the test on my own machine, trying to get out some figures. Travis will kill some processes, in certain cases: http://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error and it seems this is triggered. I ran the following, and it showed me:

```
$ /usr/bin/time -lp idris -p pruviloj --check Deriving.idr
real        58.89
user        47.99
sys          5.25
4464189440  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
   1629379  page reclaims
       407  page faults
         0  swaps
        31  block input operations
         3  block output operations
         0  messages sent
         0  messages received
      5785  signals received
       124  voluntary context switches
    143867  involuntary context switches
```

That figure for Max RSS is in bytes, so, about 4.4 GB of memory is used at peak by this script. Travis will kill a process if it goes above 3GB.

I can't get the other two files in the test to actually run, but maybe we need to do something like "set +e" or something in the ./run script (this will cause the whole script to error if any of it does, you can "set -e" to remove this again later in a script).

**Comment by lenary** [comment]
It's worth pointing out, I'm pretty sure the test passes, given lack of error messages from it.

**Comment by david-christiansen** [comment]
Yes, the test passes. I think we should just get rid of that test in meta002, until I make the relevant part of pruviloj more efficient.
