### ISSUE TITLE
:exec gives "main:ffi is not an implicit argument of run__IO"

### ISSUE THREAD

**Issue by LeifW** [idris-lang/Idris-dev#2787]
Idris 0.9.19.1-git:b49893
`:x main` or compiling w/ `-o foo` argument works, though.

Related? https://github.com/idris-lang/Idris-dev/commit/eb041bc563a1c2fe7c67ac3554789574376389c7

**Comment by ahmadsalim** [comment]
@LeifW Do you have a specific file, and if you do, could you please provide it?

**Comment by ahmadsalim** [comment]
I will close the issues since no new information was provided for a long time.
