### ISSUE TITLE
Substituting a value for an equal value makes my code not typecheck anymore

### ISSUE THREAD

**Issue by timjb** [idris-lang/Idris-dev#2790]
Substituting a value for an equal value makes a difference in this example:

```idris
module Test

%default total

emptyStringList : List String
emptyStringList = []

data Concatted : List String -> Type where
  MkConcatted : (xss : List (List String)) -> Concatted (concat xss)

-- This typechecks
foo : Concatted []
foo = MkConcatted []

-- This doesn't
foo' : Concatted emptyStringList
foo' = MkConcatted []
```

I'm using version a current version of Idris-dev, `0.9.19.1-git:b49893e`.

This is a minimal example derived from https://github.com/timjb/quantities/issues/2.

**Comment by jfdm** [comment]
@timjb Is it possible to see the error message Idris generates. It is hard to diagnose the problem without it. Also, for future record keeping if people see the issue they know what went wrong without having to time travel to past idris versions.

**Comment by timjb** [comment]
Here's the error message:

```
$ idris --version
0.9.19.1-git:b49893e
$ idris --check Test.idr 
Test.idr:17:6:
When checking right hand side of foo' with expected type
        Concatted emptyStringList

Type mismatch between
        Concatted (Prelude.List.List instance of Prelude.Foldable.Foldable, method foldr (\meth1 =>
                                                                                            \meth =>
                                                                                              meth1 ++
                                                                                              meth)
                                                                                         []
                                                                                         []) (Type of MkConcatted [])
and
        Concatted emptyStringList (Expected type)

Specifically:
        Type mismatch between
                Prelude.List.List instance of Prelude.Foldable.Foldable, method foldr (\meth1 =>
                                                                                         \meth =>
                                                                                           meth1 ++
                                                                                           meth)
                                                                                      []
                                                                                      []
        and
                emptyStringList
```

**Comment by int-index** [comment]
I can reproduce this using Idris `0.9.20`.

**Comment by int-index** [comment]
What's strange is that if you capitalize the name, it works.

```idris
%default total

EmptyStringList : List String
EmptyStringList = []

data Concatted : List String -> Type where
  MkConcatted : (xss : List (List String)) -> Concatted (concat xss)

-- This typechecks
foo : Concatted []
foo = MkConcatted []

-- This typechecks too!
foo' : Concatted EmptyStringList
foo' = MkConcatted []
```

**Comment by david-christiansen** [comment]
This is a change in the auto-implicit rules to make them the same as pattern variable rules. Lowercase names that are not applied to something are now always universally quantified. If you want to refer to one, you need to qualify the name, like "Main.emptyListString".

**Comment by int-index** [comment]
Can I disable the implicit rules completely? (I'd prefer to write forall quantifiers myself).

**Comment by timjb** [comment]
The error message should make the fact that `emptyStringList` is implictly universally quantified more explicit.

**Comment by edwinb** [comment]
I'm not sure how the error message can do this without introducing clutter generally, or without Idris having to guess what the problem might be. The semantic highlighting does show that it's a variable rather than a function, at least.

I'm closing this because it's correct behaviour. If you can come up with what the error message should say, and a suggestion how it might be detected without spoiling other messages, please let me know.

@int-index No, although I have been planning to do this.
