### ISSUE TITLE
Apparent non-termination in auto implicit

### ISSUE THREAD

**Issue by shlevy** [idris-lang/Idris-dev#2793]
With the module at https://github.com/shlevy/lambductive/blob/b4a0848e992d916c32f3eaebde70e7ad3342ce51/src/Lambductive/Core.idr loaded in the repl,

``` idris
the Term (Pi Level (Pi (U (Var Z)) (Pi (Var Z) (Var (S Z)))) {context=[]})
```

seems to hang indefinitely

**Comment by ahmadsalim** [comment]
My guess is that it is taking a long time, and not being in an infinite loop. How long did you try to run it?

**Comment by shlevy** [comment]
Can't remember anymore, sorry
