### ISSUE TITLE
Unhelpful "Incomplete term" error message

### ISSUE THREAD

**Issue by shlevy** [idris-lang/Idris-dev#2794]
With https://github.com/shlevy/lambductive/blob/fbab52c238e056964771a1da5408fe19bc85a992/src/Lambductive/Core.idr in the repl:

> *Lambductive/Core> Lambductive.Core.Pi Level (Pi (U (Var Z)) (Var Z)) {context=[]}
> Incomplete term ([__])

I'm not sure how to debug further.

**Comment by shlevy** [comment]
Same error when I add this to the bottom of the module:

```idris
test : Term
test = Pi Level (Pi (U (Var Z)) (Var Z)) {context=[]}
```

**Comment by bjz** [comment]
I get this error with https://gist.github.com/bjz/01d39a8b73da9bc7138e/74eae0c4ba4b16a94345d563a424b76310fb91d0:

```
*Fmt> format "hello {} hi" "howdy"
(input):Incomplete term ([__])
```

**Comment by ahmadsalim** [comment]
It seems to work now.
