### ISSUE TITLE
strange type mismatch error

### ISSUE THREAD

**Issue by TimRichter** [idris-lang/Idris-dev#2797]
Hi all,

typechecking this

    f : Int -> Int
    f x = mod x 7 
    
    rel : Int -> Int -> Type
    rel x y = f x = f y
    
    test : (x, y : Int) -> rel x y -> f x = f y
    test x y xRely = xRely

in idris 0.9.19.1 gives 

    test.idr:8:6:When checking right hand side of test:
    Type mismatch between
            rel x y (Type of xRely)
    and
            f x = f y (Expected type)

If I leave out the definition of f, everything is fine. For

    f x = 6*x*x + 243*x - 7

or other polynomials, there's no problem,

    f x = abs x

also works. However, mod and also 

    f x = div x 4

give type mismatch as above. Any idea?

**Comment by edwinb** [comment]
It's because 'f' isn't total due to the definition of 'mod' on ints not being total (the offending case being mod x 0). Therefore 'rel' is also not total, so Idris is refusing to reduce it at the type level, just treating it as a constant. So this is correct behaviour.
