### ISSUE TITLE
ide-mode doesn't recognize `:browse`

### ISSUE THREAD

**Issue by archaeron** [idris-lang/Idris-dev#2799]
When I start idris in the ide-mode and type:

```
000029((:interpret ":doc Prelude.Nat.pred") 1)
```

I get a result back. so far so good.

Then I try more:

```
00001b((:interpret ":browse") 2)
```

gives me:

```
000034(:return (:error "Usage is :browse <namespace>") 2)
```

fair enough. So lets try:

```
000027((:interpret ":browse Prelude.Nat") 3)
```

but this results in an error

```
00003f(:return (:error "command not recognized or not supported") 3)
```

This is for an opened issue on the atom-package:
https://github.com/idris-hackers/atom-language-idris/issues/86

Note: I tested this with idris 0.9.19.1 as there are no windows binaries yet and I haven't build my own version.

**Comment by david-christiansen** [comment]
The IDE protocol supports a different version of :browse that has more features. Though perhaps it should also allow it at the REPL.

**Comment by archaeron** [comment]
There is a REPL in the atom-package.
Do you think I should try to catch usages of `:browse` and redirect them to the other command?

I could also impement a UI just for brose as I did with `apropos`. Apropos works in the ide-mode too though.

**Comment by conjunctive** [comment]
Fixed with PR https://github.com/idris-lang/Idris-dev/pull/4873
