### ISSUE TITLE
Function argument order swapped

### ISSUE THREAD

**Issue by shlevy** [idris-lang/Idris-dev#2800]
At https://github.com/shlevy/lambductive/blob/arg-swap/src/Lambductive/Core.idr#L99 I have:

```idris
lift : Term context SortType -> (offset : Nat) -> Term (insertAt offset context type) SortType
lift offset term = ?hole
```

If I load it into the repl, though, I get

```console
*Lambductive/Core> :t lift
lift : (offset : Nat) ->
       Term context SortType ->
       Term (insertAt offset context type) SortType
```

Note that my original definition has the `Term context SortType` as the first argument and the `Nat` as the second.

**Comment by justjoheinz** [comment]
Does it matter that you wrote:
`lift offset term` instead of `lift term offset`?

**Comment by shlevy** [comment]
No, I just added that so that `:t lift` would treat lift as defined instead of as a hole. Swapping it there doesn't change it, and :t hole shows that the first argument is a Nat no matter what it's named.

**Comment by jfdm** [comment]
@shlevy this sounds like another instance of #2352 in action.

**Comment by ahmadsalim** [comment]
I will close this issue since it has been fixed in the others. Note that you code does not type check anymore due to the new totality changes (where `::` is not seen as strictly positive). IF you find this to be a bug please report it.

**Comment by shlevy** [comment]
@ahmadsalim Can you point to a description of the new totality changes?

**Comment by ahmadsalim** [comment]
@shlevy Please see https://github.com/idris-lang/Idris-dev/commit/2cfcbcf0e5dc729f9e0498a8b69a7519fdcf3a37
