### ISSUE TITLE
Syntactic sugar for lists in REPL

### ISSUE THREAD

**Issue by gsscoder** [idris-lang/Idris-dev#2801]
I got following behavior within **Idris REPL** environment, typing examples directly from book.

```haskell
Idris> [1,3..9]
Can't disambiguate name: Prelude.Classes.-, Prelude.Nat.-
Idris> [5,4..1]
Can't disambiguate name: Prelude.Classes.-, Prelude.Nat.-
```

**Comment by jfdm** [comment]
@gsscoder Thanks for the issue. Is it possible for you can tell us the version of Idris you are using. for posterity. I suspect that the Issue relates to recent changes in how the minus and (-) numerical operations work---I am seeing this on `0.9.19.1-git:8bd99ed`. How ranges work in Idris might have been unintentionally affected by this.

For who ever tackles this problem, adding a test including ranges would be good.

**Comment by gsscoder** [comment]
@jfdm, you're wellcome. :)
Requesting version from terminal it prints out: `0.9.19.1`.

Can I do something more for you?

**Comment by jfdm** [comment]
Sorry about the wait for this. On the latest version of idris the problem you encountered has been resolved. However, I am now experiencing an different issue:

```idris
Idris> [5,4..1]
(input):1:1-9:When checking argument smaller to function Prelude.Nat.-:
        Can't solve goal 
                LTE 5 4
```

**Comment by jfdm** [comment]
In fact, I shall close this issue and open another for the change in behaviour.

**Comment by jfdm** [comment]
I have no idea why I reopened this. Closing and opening the correct issue.
