### ISSUE TITLE
Non-terminating behavior when using div on the type level

### ISSUE THREAD

**Issue by pbl64k** [idris-lang/Idris-dev#2805]
Using `%assert_total` on a function that uses `div` seems to cause non-terminating behavior in the type checker when reducing the branch involving said `div`.

Might be related to #2797 but the behavior is different.

    %default total
    
    %assert_total
    conv : Integer -> ()
    conv x = if x > 0 then conv (x `div` 2) else ()
    
    tst1 : conv 0 = ()
    tst1 = Refl
    
    tst2 : conv 1 = ()
    tst2 = Refl

`tst2` here seems to cause Idris to hang consuming ~99% CPU with steadily growing memory consumption over time. Unsurprisingly, both `conv 0` and `conv 1` evaluate just fine in REPL:

    Type checking ./test2.idr
    *test2> conv 0
    () : ()
    *test2> conv 1
    () : ()

**Comment by edwinb** [comment]
This is because of the way 'if' elaborates to a function. Without knowing x it'll just expand forever because of the way the reduction rules work. If you need to %assert_total, it is always possible that you'll end up with non-termination at the type level.
