### ISSUE TITLE
Compiler crash: Prelude.!!: negative index

### ISSUE THREAD

**Issue by int-index** [idris-lang/Idris-dev#2806]
Here's the code:
```idris
data Rho = R

rho : Rho -> Rho
rho r = case r of R => r

data Kappa : (r : Rho) -> Type where K : Kappa r

kappa : Kappa (rho r) -> Kappa (rho r)
kappa k = k' where k' = k
```

And here's the error:
```
$ idris Main.idr -o Main
idris: Prelude.!!: negative index
$ idris --version
0.9.20
```

It took me quite some time to get such a minimal example, I hope it helps to locate the source of the bug.

**Comment by edwinb** [comment]
This is happening because it's failing to infer the type of `k'`. It's fine with an explicit type:

    kappa : Kappa (rho r) -> Kappa (rho r)
    kappa {r} k = k' where k' : Kappa (rho r)
                           k' = k

Obviously it's always bad to have a negative index error though, so I'll do something about that. Fortunately there is only one place that this goes unchecked.

**Comment by int-index** [comment]
The type is inferred just fine if I use `let` instead of `where`:

```idris
kappa k = let k' = k in k'
```

It also works if I change the definition of `rho` to `rho r = r`.

**Comment by int-index** [comment]
Thanks!
