### ISSUE TITLE
Allow disabling automatic insertion of Force/Delay

### ISSUE THREAD

**Issue by shlevy** [idris-lang/Idris-dev#2808]
Automatically inserting Force and Delay usually makes things easier for the user of lazy/infinite types, but sometimes it can make writing proofs a lot more confusing if you don't include explicit annotations in just the right places. It would be nice if in these cases I could write a directive asking for the elaborator to leave my terms alone.

**Comment by ahmadsalim** [comment]
Disabling automatic insertion of `Force/Delay` usually requires you to insert them manually. Do you have an example where it is not useful to have them?

**Comment by ahmadsalim** [comment]
@shlevy Any reason you are closing issues? 😄

**Comment by shlevy** [comment]
Cleaning up things I can no longer reproduce or feature requests I'm no longer pursuing to reduce my open issues list a bit 😁

**Comment by ahmadsalim** [comment]
@shlevy Ah, cool, thanks!
