### ISSUE TITLE
Concerning proof of inequality of bisimulationally equivalent codata

### ISSUE THREAD

**Issue by shlevy** [idris-lang/Idris-dev#2809]
Possibly a bad issue title, sorry. From https://lists.chalmers.se/pipermail/agda/2008/000390.html, I gather that it's desirable to be able to prove, for a type like

``` idris
codata CoNat : Type where
  S : CoNat -> CoNat
```

that `S omega = omega`. Unfortunately I seem to have just proven the opposite:

``` idris
codata Level : Type where
  S : Level -> Level

sInjective' : (x : Level) -> 
              (y : Level) -> 
              S (Delay x) = S (Delay (Force (Delay (S (Delay y))))) -> 
              x = S (Delay (Force (Delay y))) 
sInjective' _ y Refl = replace {P = \level => S (Delay y) = S (Delay level)} Refl Refl 

levelNotSLevel' : (level : Lazy' LazyCodata Level) -> 
                  Not ((Force level) = S level) 
levelNotSLevel' (S (Delay level)) p = levelNotSLevel' level (sInjective' level level p) 

sInjective : (x : Level) -> 
             (y : Level) -> 
             S (Delay x) = S (Delay (S (Delay y))) -> 
             x = S (Delay (Force (Delay y))) 
sInjective _ y Refl = replace {P = \level => S (Delay y) = S (Delay level)} Refl Refl 

levelNotSLevel : (level : Level) -> Not (level = S (Delay level)) 
levelNotSLevel (S (Delay level)) p = levelNotSLevel' level (sInjective level level p) 
```

Is there some inconsistency in this proof?

**Comment by shlevy** [comment]
Yeah, definitely something inconsistent, just inhabited Void with the same technique. Looks like the totality checker has a bug for infinite arguments:

```idris
%default total

codata Level : Type where
  S : Level -> Level

sLevelNotSLevel' : (level : Inf Level) ->
                   Not (S level = S level)
sLevelNotSLevel' (S (Delay level)) p = sLevelNotSLevel' level Refl

sLevelNotSLevel : (level : Level) ->
                  Not (S (Delay level) = S (Delay level))
sLevelNotSLevel (S (Delay level)) p = sLevelNotSLevel' level Refl

l : Level
l = S l

v : Void
v = sLevelNotSLevel l Refl
```

**Comment by falsifian** [comment]
As a side note, I can make an aesthetic argument for Nat.

You are looking for a type which:
* has at least one element, and
* has a successor operator.

This is exactly what Nat specifies. No more and no less.

You can even avoid ever naming zero if you're careful. For example, if you
want to define a type T for your language, instead of saying HasType (U 0)
T, you could make a version of T for whatever level one wants: TT :: (a :
Nat) -> (a type TT(a) such that HasLevel (U a) (TT(a)) holds).

(Sorry, I forgot the Idris notation for dependent pairs.)

James

**Comment by shlevy** [comment]
I ended up going with something isomorphic to ZZ for now, and will worry about universe polymorphism/inference later https://github.com/shlevy/lambductive/blob/1a12a3583d9fdd09281bdd9d5f504a2ba7e1815f/src/Lambductive/Core.idr#L6-L17

**Comment by ahmadsalim** [comment]
It seems that Idris goes into an infinite loop while checking this now
