### ISSUE TITLE
Automatically reduce Force/Delay pairs behind Delay

### ISSUE THREAD

**Issue by shlevy** [idris-lang/Idris-dev#2811]
We can prove:

```idris
p : Delay (Force (Delay x)) = Delay x
p = Refl
```

But Idris won't automatically reduce such Force/Delay pairs, presumably because of laziness semantics because they are in front of a Delay. Combined with the automatic insertion of Delay and Force by the elaborator, though, this makes proofs with Lazy/Inf types very ugly. If we're going to have the automatic insertion, it would be nice to have the automatic reduction/rewrite as well.

**Comment by ozgurakgun** [comment]
This is probably useless to you, but one can also prove the following, right?

```
p : Force (Delay x) = x
p = Refl
```

So you don't need the extra Delay wrapping.

**Comment by ozgurakgun** [comment]
Sorry for the double posting, but I just tried in Idris and all of the following type check. Idris must be handling Force and Delay specially.

```
p : Delay x = x
p = Refl
```

```
p : Force x = x
p = Refl
```

**Comment by shlevy** [comment]
The compiler inserts Forces and Delays for you, I wouldn't have put it there myself :) And yeah, Delay is used to implement laziness so I think it doesn't automatically reduce it like it does other terms

**Comment by ahmadsalim** [comment]
It seems to type check fine now!
