### ISSUE TITLE
Incorrect behavior for lower case type names

### ISSUE THREAD

**Issue by theemathas** [idris-lang/Idris-dev#2812]
Code:
```idris
module Main
 
foo : Type
foo = Int
 
one : foo
one = 1
```

Compile error:
```
test.idr:7:5:
When checking right hand side of one with expected type
        iType

iType is not a numeric type
```

Changing `foo` to `Foo` causes the error to disappear.

**Comment by jfdm** [comment]
As mentioned on IRC a recent change to Idris is that all identifiers specified in a type signature that begin with a lower case letter will automatically be treated as an implicit argument. The code above really looks like:

```idris
one : {foo : Type} -> foo
one = 1
```

Now this will not type check as we do not know to what num type '1' represents. Idris overloads number syntax, as we do lists. Here '1' could be `Nat`, or it could be an `Int` it could even be an `Integer`?

There are two fixes here:

1. Ensure that all type synonyms are Capitalised i.e. `foo` is now `Foo`
2. Fully qualify the name. [Idris has support for namespaces](https://idris.readthedocs.org/en/latest/reference/syntax-guide.html#qualified-names). As in `foo` becomes `Main.foo`. 

With these two the problem will go away.
