### ISSUE TITLE
Elaboration on applied lambda fails but works on binding.

### ISSUE THREAD

**Issue by LeifW** [idris-lang/Idris-dev#2813]
You can define the following lambda (essentially `the`) at the repl:
```
Idris> \a, b : a => b
\a => \b => b : (a : Type) -> a -> 
```
But if you try to apply  it partially or fully, it gives essentially `builtin:Type mismatch between (the type arg you supplied) and a (Expected type)`; like it's not unifying the type arg you supplied and `a`? If you try it with `(\a, b:a => b) Int 5` it just says `No such variable a`

However, if you first bind it to a variable in the repl, e.g. `:let foo = \a, b : a => b`, you can then use it as expected (like `the`).

You can show them equal at the repl
```idris
the (foo = (\a, b : a => b)) Refl
```
but applying the lambda will cause an error:
```idris
the (foo String = (\a, b : a => b) String) Refl
```
gives the same "a is not String" error as before.

Can also use this lambda if you explicitly ascribe a type to it:
```idris
(the ((a : Type) -> a -> a) (\a, b:a => b)) String
```
Though I don't know what new information that's introducing over
```
(\a: Type, b : a => b)
```
the return type, I guess?

**Comment by edwinb** [comment]
Looks fine to me:

    Idris> \a,b : a => b
    \a => \b => b : (a : Type) -> a -> a
    Idris> (\a,b : a => b) Int 4
    4 : Int
    Idris> (\a,b : a => b) Int
    \b => b : Int -> Int

**Comment by int-index** [comment]
I can reproduce this using Idris 0.9.20

**Comment by int-index** [comment]
```
Idris> \a,b : a => b
\a => \b => b : (a : Type) -> a -> a
Idris> (\a,b : a => b) Int 4
(input):1:17:No such variable a
Idris> (\a,b : a => b) Int
builtin:Type mismatch between
        Int -> Int (Type of (\a => \b => b) Int)
and
        a -> a (Expected type)

Specifically:
        Type mismatch between
                Int
        and
                a
```

**Comment by edwinb** [comment]
It doesn't happen in master, though, which is what I'm testing again. It's almost certainly the better elaboration of application that has fixed this, since this is exactly the sort of thing that could have gone wrong.

**Comment by int-index** [comment]
Right, I've just tested it using 0.9.20.1-git:140d06a and the problem is gone (couldn't do it before now because it was building).
