### ISSUE TITLE
Forward pipe operator |> for in Prelude?

### ISSUE THREAD

**Issue by Kazark** [idris-lang/Idris-dev#2817]
I've started learning Idris; I have the MEAP book and have been playing around with it quite a lot. I'm coming more from an F# background than a Haskell background, so like most folks who `F# |> <3`, I like the forward pipe operator. I did notice that Idris already has `$`, like Haskell, and that is seems to be an inherent part of the syntax rather than a function. However, when I tried to use `&`, which is the Haskell equivalent of F#'s `|>`, that did not work.

I tried defining a `|>` operator, and was pleasantly surprised by how easy it was to do so:

```
infixl 5 |> -- I have no idea what the proper precedence of this would be

(|>) : a -> (a -> b) -> b
a |> f = f a
```

and aside from the fact that I wonder about the precedence, it seems that it works, after superficial testing:

```
> "foo" |> length
3 : Nat
> ["asdf", "qwer", "uiop"] |> map length
[4, 4, 4] : List Nat
```

So I would like to submit something to include this in Prelude. However, before doing so, I thought it would be good to ask about this.
1. Is there something about this that won't work well with the type inference in Idris? I know sometimes it can have weird effects on type inference in F#.
2. Is this something you would want in Prelude, or would you rather people just define it themselves if they want it?
3. Would this be considered not idiomatic Idris? If the forward piping concept itself is okay, would it be better to mimic Haskell with `&` to match `$` instead of mimicking F#'s `|>` since we don't have `<|` in Idris?

I'm not emotionally attached to this idea, but just thought I would bring it up because I can't find anything about it by searching (searching you run into the same problems that Hoogle was designed to solve for Haskell...) and see what your thoughts on it were.

**Comment by Melvar** [comment]
1. This will only work for nondependent functions. (One of the reasons that `$` is builtin.)
2. Adding it would at least require discussion. Prelude is supposed to be only things you absolutely need for a reasonable program these days, and it’s debatable whether writing value before function is necessary.
3. I have the strong personal opinion that `(&)` is the wrong choice and it needs to be `(#)`, but apparently nobody else thinks so.

**Comment by david-christiansen** [comment]
I happen to quite like pipeline operators, but it is unfortunate that they won't work for fully dependent functions. I'd be happy to accept a pull request that defined a `Control.Pipelines` module in `contrib`, or one that defined `&`.  WRT `&` vs `#`, I don't see a reason to prefer one arbitrary character over the other, but `&` is already in Haskell, so we might as well be compatible.

**Comment by Kazark** [comment]
Thank you guys both for your responses.

So David, do I understand correctly that you are saying that you would accept a PR to either&mdash;
 1. define `|>` and `<|` in `contrib`, as nice syntactic sugar but with the limitation of not working for fully dependent functions, or
 2. define `&` as a builtin a la `$` so it would work with fully dependent functions

...?

If so, I think I would be interested to try 2. Though I prefer the visual of `|>` and `<|`, since `$` is already established, I think I would prefer the functionality of `&`.

**Comment by foliot** [comment]
Any progress on this? The pipe operator really improves readability in some cases and would be a nice addition to the language

**Comment by ahmadsalim** [comment]
I think people are still welcome to add `|>` and `<|` to contrib (if it is not there already).

**Comment by Kazark** [comment]
I started working on adding `&` but I got stuck and never picked it back up. I went through a phase where I was spending a lot of my free time on Idris for three or four months but I burned out on it somewhat so I never got back to it.

**Comment by zjhmale** [comment]
@david-christiansen @ahmadsalim @Melvar i can not find the definition of `($)` function in idris codebase, i mean it is easily to find `($)` in [GHC](https://github.com/ghc/ghc/blob/master/libraries/base/GHC/Base.hs#L1080-L1082)

**Comment by david-christiansen** [comment]
`$` in Idris is syntax, not a function. So it makes sense that it's hard to find!  This is because dependent application is harder to type, and most uses of $ are just for avoiding heavily-nested parens.

**Comment by zjhmale** [comment]
@david-christiansen cool, but i walk through the codebase again, especially with modules related to Parser, it is still vague to find out which part parse the `$` symbol and then desuger to AST, can you point out the relevant code more explicitly? thx in advance!

**Comment by enolan** [comment]
It's in here:
https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/Parser/Ops.hs
under "table".

**Comment by zjhmale** [comment]
@enolan i see, thx!

**Comment by lpil** [comment]
> I think people are still welcome to add |> and <| to contrib (if it is not there already).

@ahmadsalim Are you suggesting that a PR adding these to https://github.com/idris-lang/Idris-dev/tree/master/libs/contrib would be welcomed?

Thanks :)

**Comment by ahmadsalim** [comment]
@lpil Sure, they are still welcome to be added to contrib.

**Comment by david-christiansen** [comment]
It looks like this PR gets the precedence and associativity right for them, as well. This is a nasty wart in F#.
