### ISSUE TITLE
Simple proof of Void

### ISSUE THREAD

**Issue by enolan** [idris-lang/Idris-dev#2821]
``` idris
%default total

foo : (a : Bool) -> (b : Bool) -> Not (const a b = b)
foo a b Refl impossible

myVoid : Void
myVoid = foo True True Refl
```

Typechecks on 140d06a.

:(

**Comment by xekoukou** [comment]
This doesn't typecheck in 0.10 and thus can be closed.

**Comment by jfdm** [comment]
I checked with Idris Version 0.10.3, and this still type checks.

**Comment by ahmadsalim** [comment]
It fails with a type conversion error rather than a unification error and so it should output that error rather than accepting that it is impossible.

**Comment by jachymb** [comment]
Anton Trunov on StackOverflow says that this is related: http://stackoverflow.com/questions/40687199/valid-case-error-after-idris-hint?noredirect=1
