### ISSUE TITLE
Broken Hackage documentation for idris-0.9.20.1

### ISSUE THREAD

**Issue by TerrorJack** [idris-lang/Idris-dev#2822]

**Comment by jfdm** [comment]
Sorry for being late to respond to this.

Can you elaborate more by what you mean by 'broken hackage documentation'? I have a pretty good idea, but do not want to assume.

**Comment by TerrorJack** [comment]
@jfdm The haddock build on Hackage failed for 0.9.20.1. But since it's a legacy release anyway, I think it's okay to close this issue.

**Comment by jfdm** [comment]
No worries, thanks for taking the time to respond.
