### ISSUE TITLE
Compiler error "doOp not implemented"

### ISSUE THREAD

**Issue by yblein** [idris-lang/Idris-dev#2823]
I obtain the following error when trying to compile my project :
```
$ idris Main.idr -o Main
idris: doOp not implemented ((LFloatInt (ITFixed IT8),[L 0]))
```

Turns out that the error come from this part:
```idris
instance Cast Double Bits8 where
  cast = prim__fromFloatB8
```

I was able to bypass the error for now with the following implementation
```idris
  cast = prim__truncInt_B8 . prim__fromFloatInt
```
but I guess that the first version should work?

**Comment by ahmadsalim** [comment]
Seems to work fine now.
