### ISSUE TITLE
Int only 31 bit. 32 bit possible?

### ISSUE THREAD

**Issue by norm2782** [idris-lang/Idris-dev#2842]
As clarified by markuspf in issue #2839, `Int` only has 31 bits in code compiled through the C backend:

> Int only has 31 bits (in code compiled through the C backend), and hence you run into an overflow.
> The use of 31 bits is because of tagging as Ints are unboxed in the C backend.

While this isn't strictly a *bug* in the current implementation, I believe this design choice is incredibly inconvenient at the very least. Since `Int`s are signed, one only has 30 bits to store numbers, which is not a lot at all (1073741824). I'm opening this issue to start a discussion whether it is possible to have full 32 bit integer support in Idris via the C backend.

Markus' suggestion in #2839 is to use `Integer`s. While this does eliminate the immediate problem, it is not a great solution for my purposes. I'm currently programming sensors with Idris on a Raspberry Pi, so resources are somewhat limited and I need to juggle the integers around quite a bit, which is easier when they are of fixed width. My goal is to use even smaller systems in the future.

**Comment by markuspf** [comment]
I don't see how this would be possible with how things work (which btw is a fairly standard way of doing unboxed types). You can look at the runtime system yourself in [here](https://github.com/idris-lang/Idris-dev/tree/master/rts).

What you could do is update the C backend to use 63 bit integers, if that is of any help, or make a boxed 32bit type (which would have the performance penalties of a boxed type). This might also carry some penalties in terms of space use, which I suggest you first try to work out.

**Comment by ziman** [comment]
If you want to do low-level bit shuffling around sensors, there's the primitive `Bits32` for 32-bit machine words and `Data.Bits` for unsigned words of arbitrary width but I don't know how complete the interface + implementation is atm.

**Comment by norm2782** [comment]
Haskell2010 specifies a range of *at least* [-2^29 .. 2^29-1] for signed integers, so at the very least Idris' behaviour is behaving better than a minimally standards-complient Haskell compiler would. GHC, however, seems to offer full 32/64 bit Ints [2]. I.e. it offers a range of [-2^31 .. 2^31-1]/[-2^63 .. 2^63-1]. I confirmed this in GHCi. I'm not sure how GHC implements that, however, and whether it's efficient or not.

ziman: thanks for the tip, I'll look at that as well.

[1] https://www.haskell.org/onlinereport/haskell2010/haskellch18.html#x26-22300018
[2] https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/bugs-and-infelicities.html#infelicities-numbers

**Comment by markuspf** [comment]
According to https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/primitives.html GHC's `Int`s are boxed, so that corresponds to my suggestion of making them boxed, without any discernible benefits.

If you do bitfiddling, I suggest you go with @zimans suggestion of using Bits32 datatypes and fix those if necessary, because they don't come with a prescribed interpretation of bits.

**Comment by norm2782** [comment]
Ah indeed, so they are boxed in GHC by default. Clean uses another approach. It compiles to the ABC-machine, which has three stacks, one of which (the B-stack) is dedicated to values of Basic types, including Int. Using this approach, Clean has fast unboxed signed integers in the range of [-2^31 .. 2^31-1]/[-2^63 .. 2^63-1].

**Comment by markuspf** [comment]
Is there any evidence (benchmarks at least) suggesting that this added complexity is worth the effort?
Since Idris' sourcecode is available this is of course the time to call proof (of concept) + benchmarks.

**Comment by domoszlai** [comment]
GHC unboxes Int S to the primitive I# type in strict context, so there is no associated overhead

**Comment by markuspf** [comment]
@domoszlai it'd be very helpful if you gave a reference for this. I am not familiar with the internals of GHC.

**Comment by norm2782** [comment]
@markuspf I could run some benchmarks on my machine. Do you happen to know of an existing benchmark that tests integer performance really well?

**Comment by domoszlai** [comment]
I guess it is already described here: http://research.microsoft.com/en-us/um/people/simonpj/papers/slpj-book-1987/index.htm
If strictness is derived for a function then it works on the primitive type instead of the boxed one.

And this is how Int is defined in Type.hs (http://git.haskell.org/packages/ghc-prim.git/blob/HEAD:/GHC/Types.hs)

data {-# CTYPE "HsInt" #-} Int = I# Int#

I was wrong, the type is Int#, I# is the data constructor

The easiest way to check is to generate STG with -O2

**Comment by norm2782** [comment]
Ok, did a preliminary benchmark. Criticism is welcome. First the benchmark code:

Haskell:
```haskell
mkBench :: Int -> Int -> Int
mkBench n acc
  | n < 1 = acc
  | otherwise = mkBench (n - 1) (acc + 1)

main :: IO ()
main = print (mkBench 100000000 0)
```

Idris:
```idris
module Main

mkBench : Int -> Int -> Int
mkBench n acc
  = if n < 1
      then acc
      else mkBench (n - 1) (acc + 1)

main : IO ()
main = putStrLn (show (mkBench 100000000 0))
```

Clean:
```haskell
module bench

import StdEnv

mkBench :: Int Int -> Int
mkBench n acc
  | n < 1 = acc
  | otherwise = mkBench (n - 1) (acc + 1)

Start :: Int
Start = mkBench 100000000 0
```

Compiled as follows:
```make
default: benchIdrO0 benchIdrO3 benchHaskO2 benchHaskO0 benchClean

benchClean: bench.icl
	cpm bench.prj

benchIdrO0: bench.idr
	idris -O0 bench.idr -o benchIdrO0

benchIdrO3: bench.idr
	idris -O3 bench.idr -o benchIdrO3

benchHaskO2: bench.hs
	ghc --make -O2 bench.hs -o benchHaskO2

benchHaskO0: bench.hs
	ghc --make -O0 bench.hs -o benchHaskO0

clean:
	rm -f benchClean benchIdrO0 benchIdrO3 benchHaskO2 benchHaskO0
	rm -f *.o *.ibc *.hi

.PHONY: clean
```

and ran them:

```shell
#!/bin/bash
echo "Haskell O0: "
time ./benchHaskO0

echo ""
echo "Haskell O2: "
time ./benchHaskO2

echo ""
echo "Idris O0: "
time ./benchIdrO0

echo ""
echo "Idris O3: "
time ./benchIdrO3

echo ""
echo "Clean: "
time ./benchClean
```

I get the following results:

```
Haskell O0:
100000000

real	0m0.036s
user	0m0.032s
sys	0m0.002s

Haskell O2:
100000000

real	0m0.034s
user	0m0.031s
sys	0m0.002s

Idris O0:
100000000

real	0m9.385s
user	0m9.359s
sys	0m0.017s

Idris O3:
100000000

real	0m10.363s
user	0m10.192s
sys	0m0.056s

Clean:
100000000

real	0m0.036s
user	0m0.032s
sys	0m0.001s
```

Clean and Haskell are about as fast. Idris is significantly slower than either Haskell or Clean.

O0 Haskell core. It uses unboxed integers for the constants. The rest looks boxed.
```
==================== Tidy Core ====================
Result size of Tidy Core = {terms: 34, types: 15, coercions: 0}

Rec {
mkBench_rjG :: Int -> Int -> Int
[GblId, Arity=2, Str=DmdType]
mkBench_rjG =
  \ (n_alG :: Int) (acc_alH :: Int) ->
    case < @ Int GHC.Classes.$fOrdInt n_alG (GHC.Types.I# 1)
    of _ [Occ=Dead] {
      False ->
        mkBench_rjG
          (- @ Int GHC.Num.$fNumInt n_alG (GHC.Types.I# 1))
          (+ @ Int GHC.Num.$fNumInt acc_alH (GHC.Types.I# 1));
      True -> acc_alH
    }
end Rec }

main :: IO ()
[GblId, Str=DmdType]
main =
  print
    @ Int
    GHC.Show.$fShowInt
    (mkBench_rjG (GHC.Types.I# 100000000) (GHC.Types.I# 0))

:Main.main :: IO ()
[GblId, Str=DmdType]
:Main.main = GHC.TopHandler.runMainIO @ () main
```

Some Clean ABC code (where pushI pushes to the B-stack and push_b too)

```
s2
	pushI 0
	pushI 100000000
.d 0 2 ii
	jmp s1
.o 0 2 ii
s1
	pushI 1
	push_b 1
	ltI
	jmp_false else.1
	pop_b 1
.d 0 1 i
	rtn
else.1
	pushI 1
	push_b 2
	addI
	pushI 1
	push_b 2
	subI
	update_b 1 3
	updatepop_b 0 2
.d 0 2 ii
	jmp s1
```

Idris' output is too big to paste here. Is there any way to dump Idris core code?

**Comment by markuspf** [comment]
I suspect that the reason for Idris being slow in this case is *not* the implementation of `Int` but the lack of proper TCO (and other optimisations) from looking at the produced C code:

```C
void _idris_Main_46_mkBench(VM* vm, VAL* oldbase) {
    INITFRAME;
    RESERVE(3);
    ADDTOP(3);
    LOC(2) = MKINT(1);
    RESERVE(2);
    TOP(0) = LOC(0);
    TOP(1) = LOC(2);
    STOREOLD;
    BASETOP(0);
    ADDTOP(2);
    CALL(_idris_Prelude_46_Classes_46_Prelude_46_Classes_46__64_Prelude_46_Classes_46_Ord_36_Int_58__33_compare_58_0);
    LOC(2) = RVAL;
    if (CTAG(LOC(2)) == 0) {
        PROJECT(vm, LOC(2), 3, 0);
        LOC(2) = NULL_CON(1);
    }
    else
    {
        LOC(2) = NULL_CON(0);
    }
    if (CTAG(LOC(2)) == 0) {
        PROJECT(vm, LOC(2), 3, 0);
        LOC(3) = MKINT(1);
        LOC(3) = INTOP(-,LOC(0), LOC(3));
        LOC(4) = MKINT(1);
        LOC(4) = ADD(LOC(1), LOC(4));
        RESERVE(2);
        TOP(0) = LOC(3);
        TOP(1) = LOC(4);
        SLIDE(vm, 2);
        TOPBASE(2);
        TAILCALL(_idris_Main_46_mkBench);
    }
    else
    {
        PROJECT(vm, LOC(2), 3, 0);
        RVAL = LOC(1);
        TOPBASE(0);
        REBASE;
    }
}
```

even more so if one looks at the assembly produced by GCC.

**Comment by norm2782** [comment]
That does indeed seem to be a problem. Do you have any suggestions for a representative benchmark that can be executed?

**Comment by markuspf** [comment]
I'd first suggest to put in TCO, because that's a much bigger gain ;). I seem to remember that has come recently, probably on the mailing list...

**Comment by norm2782** [comment]
I was afraid you were going to say that ;) Unfortunately, I know next to nothing about the Idris compiler's internals and only very little about implementing TCO, so I'm not going to be the one to do that (in the near future) :(

**Comment by norm2782** [comment]
Found some time for more fiddling with benchmarks. This time, I used nfib:

```idris
module Main

nfib : Int -> Int
nfib n
  = if n < 2
      then 1
      else nfib (n - 1) + nfib (n - 2) + 1

main : IO ()
main = putStrLn (show (nfib 40))
```

Similar code for Haskell and Clean. No TCO getting in the way of a fair benchmark this time. These are the results:

```
Haskell O0:
331160281

real	0m0.713s
user	0m0.707s
sys	0m0.004s

Haskell O2:
331160281

real	0m0.693s
user	0m0.689s
sys	0m0.002s

Idris O0:
331160281

real	0m32.215s
user	0m32.040s
sys	0m0.105s

Idris O3:
331160281

real	0m31.845s
user	0m31.699s
sys	0m0.092s

Clean:
331160281

real	0m0.510s
user	0m0.506s
sys	0m0.002s
```

Over several runs, Clean is consistently ~100ms faster than GHC. Idris is by far the slowest.

**Comment by Melvar** [comment]
The title is, strictly speaking, false. `Int` has 63 bits when compiled with the C backend for x86_64. If compiled to JS, it has a 52-bit range but doesn’t overflow as such outside of it (because it’s really a JS Number). Any backend may make any other choice. (If you need a specific number of bits, that’s specifically what the `Bits*` types are for. If you don’t have a specific size in mind, use `Integer`. IIRC small `Integer`s are even represented like `Int`s.)

**Comment by edwinb** [comment]
We rely on gcc/clang to do TCO for us, but it isn't reliable. There are various ways we could fix this, and we really need to at some point, but I haven't got around to it yet.

As for the issue itself, this is just the way the C RTS represents Ints. As others have said, it's pretty standard, and if you really need the bit patterns that's what the Bits* types are for. So I'm going to close the issue.
