### ISSUE TITLE
idris_heap.h: No such file or directory

### ISSUE THREAD

**Issue by user471** [idris-lang/Idris-dev#2846]
I have just installed Idris, and there is an error.
```idris hello.idr -o hello.exe```

```
C:\Users\main\AppData\Roaming\cabal\idris-0.9.8\rts/idris_rts.h:12:24: fatal error: idris_heap.h: No
 such file or directory
compilation terminated.
FAILURE: gcc -O2 -I.  -x c  C:\Users\main\AppData\Local\Temp\idris3520 -LC:\Users\main\AppData\Roami
ng\cabal\idris-0.9.8\rts -lidris_rts -lgmp -lpthread -IC:\Users\main\AppData\Roaming\cabal\idris-0.9
.8\rts -lm  -o hello.exe
```

**Comment by enolan** [comment]
Your Idris is very old. Does this still happen with 0.9.20.1? Cabal may have picked 0.9.8 because of packages you already had installed, if that's the case you can try wiping out your directory or using a sandbox.

**Comment by user471** [comment]
I downloaded https://github.com/idris-lang/Idris-dev/wiki/Windows-Binaries and now everything works fine.

**Comment by enolan** [comment]
Great!
