### ISSUE TITLE
Package not loaded in idris emacs mode

### ISSUE THREAD

**Issue by eklavya** [idris-lang/Idris-dev#2847]
Hi,

I can't seem to get idris emacs mode to load Lightyear package.
I have added the package by using the Idris > Choose Packages > lightyear <enter> <enter> y n
But this doesn't work and when I do "Cc Cl" it errors out with "Can't find import Lightyear".

I am able to get this to work by doing "idris -p lightyear" > :l file

Lightyear was installed with "idris --install lightyear.ipkg"

Please let me know if I can give more useful information to ascertain if it's a bug or a problem with my setup.

Please help, I am unable to write any code (for a long time now!).

**Comment by david-christiansen** [comment]
Are you working relative to a .ipkg file?

**Comment by eklavya** [comment]
Tried that too. I made an ipkg file and put it in the root dir. I can build it just fine using "idris --build mypkg.ipkg" but the emacs behaviour is unchanged. It still doesn't load anything.

**Comment by david-christiansen** [comment]
What happens if you do `M-: (idris-compute-flags) RET`?

**Comment by eklavya** [comment]
("-p" "lightyear")

**Comment by david-christiansen** [comment]
That means that the compiler is getting the right arguments, anyway. What does `M-: idris-current-flags` give?

**Comment by eklavya** [comment]
same - ("-p" "lightyear")

**Comment by eklavya** [comment]
It turns out the idris version in emacs was different (for some reason it was using the one in Haskell/bin).
Setting idris executable path in "idris menu -> customize idris-mode -> idris interpreter path" to "which idris" fixed it.
Thanks @david-christiansen :)
