### ISSUE TITLE
Is the garbage collector reentrant?

### ISSUE THREAD

**Issue by antoyo** [idris-lang/Idris-dev#2863]
Hello.
I wonder if the Idris garbage collector is reentrant.
Is it?
Thanks.

**Comment by melted** [comment]
If the runtime is built with threading it should be.

----- Ursprungligt meddelande -----
Från: "antoyo" <notifications@github.com>
Skickat: ‎2015-‎12-‎17 15:14
Till: "idris-lang/Idris-dev" <Idris-dev@noreply.github.com>
Ämne: [Idris-dev] Is the garbage collector reentrant? (#2863)

Hello.
I wonder if the Idris garbage collector is reentrant.
Is it?
Thanks.
