### ISSUE TITLE
assert_smaller doesn't work in pattern lets

### ISSUE THREAD

**Issue by porglezomp** [idris-lang/Idris-dev#2872]
Given the following simplified example, the totality checker complains about the last case of `tokenize` being potentially non-total.
```idris
%default total
||| Return the first space terminated sequence as a string and the rest of the list
findWord : Char -> List Char -> (String, List Char)
findWord c xs = findWord' xs (singleton c)
  where findWord' []          str = (str, [])
        findWord' (' ' :: xs) str = (str, xs)
        findWord' (x :: xs)   str = findWord' xs (str ++ singleton x)

||| Split a list of characters on spaces
tokenize : List Char -> List String
tokenize [] = []
tokenize (' ' :: xs) = tokenize xs
tokenize (c :: xs) =
  let (word, xs') = findWord c xs in
    word :: tokenize (assert_smaller (c :: xs) xs')
```
If I change the destructuring let
```idris
let (word, xs') = findWord c xs in
    word :: tokenize (assert_smaller (c :: xs) xs')
```
into a single binding and then `fst` and `snd` it
```idris
let wordAndRest = findWord c xs in
    fst wordAndRest :: tokenize (assert_smaller (c :: xs) (snd wordAndRest))
```
then the totality checker stops complaining.

I'm new enough to Idris that I can't quite figure out what the origin of the problem might be, but I doubt it's an intended behavior.

**Comment by ahmadsalim** [comment]
I think this was because Idris didn't look under case-trees which would have been built when using the destructuring let, but now it does. I have indeed checked with the latest Idris and it works npw
