### ISSUE TITLE
Website links to wrong effects tutorial

### ISSUE THREAD

**Issue by porglezomp** [idris-lang/Idris-dev#2873]
**Update:** This is caused by using the wrong version of the documentation.
```idris
module Main

import Effect.StdIO

hello : { [STDIO] } Eff ()
hello = putStrLn "Hello, World!"

main : IO ()
main = run hello
```
The effects tutorial code above fails with the error
```
effectTest.idr:6:7:When checking type of Main.hello:
No such variable Eff
```
Adding `import Effects` above the `import Effect.StdIO` fixes it, but the tutorial code *should* just work.

**Comment by imuli** [comment]
The (latest version)[http://docs.idris-lang.org/en/latest/effects/introduction.html#hello-world] has `import Effects`. Where are you finding it?

**Comment by porglezomp** [comment]
On the http://www.idris-lang.org/documentation/effects/ page, it links to an apparently older pdf.
I suppose it's just one link that needs to be changed, then.

**Comment by LeifW** [comment]
Yes, we need that link on the site changed to something current, like http://docs.idris-lang.org/en/latest/effects/. @edwinb?

**Comment by argent0** [comment]
Hi,

I'm also havinig problems with the effects tutorial. In particular with the code:

```Idris
module Main

import Effects
import Effect.StdIO

hello : Eff () [STDIO]
hello = putStrLn "Hello world!"

main : IO ()
main = run hello
```Idris

That is giving me the following compilation error:

    $idris hello.idr -o hello -p effects
    overapplied data constructor: Language.Reflection.Elab.Prim__BindElab (MkFFI FFI_C.C_Types String String) Char {e3} Prelude.Interactive.getChar (\ x8 : [__] => {e6} x8 MkUnit)

    $idris --version
    0.9.20.2-git:9c99198

**Comment by LeifW** [comment]
Shouldn't the type sig for hello be Eff [STDIO] () ?

**Comment by argent0** [comment]
I upgraded to HEAD( 0.9.20.2-git:f6f97eb) but I'm still getting the same error: 

   overapplied data constructor: Language.Reflection.Elab.Prim__BindElab (MkFFI FFI_C.C_Types String String) Char {e3} Prelude.Interactive.getChar (\ x8 : [__] => {e6} x8 MkUnit)

I took special care to rebuild all my *.ibc files (in llbs/). I've also installed idris using the cabal-sandbox method.

@LeifW IDK I'll read on into the tutorial. I tried your code and it doesn't type check.

Also libs/effects/Effects.idr suggests that the order of the arguments is right.

```idris
namespace SimpleEff
  -- Simple effects, no updates
  Eff : (x : Type) -> (es : List EFFECT) -> Type
```

**Comment by LeifW** [comment]
Sorry, I was emailing from my phone and mis-remembering the signature.

The code snippet you posted works fine for me in my Idris.

**Comment by argent0** [comment]
It also works for me, but only when I use

    idris --execute hello.idr -p effects

Any idea of what could be causig the compilation to fail?

**Comment by jfdm** [comment]
@argent0 I am going to be a bit of a pain, can you post this problem in a separate issue please. It is just so we can track the issues documented here better and separately.

**Comment by jfdm** [comment]
I am going to close this issue because the *main* issue in this thread has been resolved. @argent0 if you are still experiencing problems can you please post a separate issue.
