### ISSUE TITLE
raw access to strings

### ISSUE THREAD

**Issue by imuli** [idris-lang/Idris-dev#2874]
The doesn't appear to be a way to look at the actual values inside a String since #20 was fixed.

I'm imagining a set Bits8 functions matching the Char ones, either on strings directly or another name with that backing.

**Comment by Melvar** [comment]
The underlying representation of strings is backend-specific, and should not leak out. What exactly would you want to do with this “raw access”?

**Comment by david-christiansen** [comment]
The String abstraction should not be broken here by allowing byte-level access. Some kind of byte array structure would be useful, but it's not really a proper subject for a bug report.

If you'd like to get hacking on this, please let us know on the mailing list!
