### ISSUE TITLE
Coverage.hs: Non-exhaustive patterns in case

### ISSUE THREAD

**Issue by LeifW** [idris-lang/Idris-dev#2879]
Reported by @athanclark in #idris IRC:
```
idris-map> idris --build map.ipkg
Type checking ./Data/Map/Base.idr
idris: src/Idris/Coverage.hs:(469,16)-(476,51): Non-exhaustive patterns in case
```
http://lpaste.net/148073
Run on this repo: https://github.com/athanclark/idris-map
I'm able to reproduce this; just trying to load Base.idr in the repl is enough.

So it looks like this is the case that *should* be matched: https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/Coverage.hs#L470

I added a `x -> error $ show x` fallthrough case, and this is what I get:
`Just TyDecl: Ref (c : Type v124) -> (b : Type y124) -> (a : Type b125) -> (k : Type e125) -> (k -> a -> b -> Prelude.Maybe.Maybe c) -> (Data.Map.Base.Map k a -> Data.Map.Base.Map k c) -> (Data.Map.Base.Map k b -> Data.Map.Base.Map k c) -> Prelude.Classes.Ord k -> Prelude.Maybe.Maybe k -> Prelude.Maybe.Maybe k -> k -> a -> Data.Map.Base.Map k a -> Data.Map.Base.Map k a -> Data.Map.Base.Map k b -> Prelude.Nat.Nat -> Prelude.Maybe.Maybe k`

**Comment by athanclark** [comment]
Have you seen the work done with this, by chance? I think `--repl` is now strictly used for executables - this is in 0.10.2 commit 88d8075660d9620d1127ad7e8c20f9dd4e90471f

**Comment by ahmadsalim** [comment]
It seems to not give that error anymore:

```
>  idris --build map.ipkg
Type checking ./Data/Map/Base.idr
> 
```
