### ISSUE TITLE
Test Infrastructure does not work for with stack.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#2919]
The new test runner cannot be used when the project is built using stack. 

Doing:

```sh
stack install
make test_c
```

will fail with 

```sh
$ make test_c
make -C test IDRIS=../dist/build/idris/idris test
make[1]: Entering directory `/home/jfdm/projects/idris/source/test'

runtest.hs:16:8:
    Could not find module ‘Text.Regex’
    Perhaps you meant Text.Read (from base-4.8.2.0)
    Use -v to see a list of the files searched for.
make[1]: *** [runtest] Error 1
make[1]: Leaving directory `/home/jfdm/projects/idris/source/test'
make: *** [test_c] Error 2
```
Although, the `idris.cabal` file stipulates that the required dependency should be installed, due to stack's sandboxing efforts this won't be picked up when building the test runner. The fix for using stack would be to build the  test runner using:

```sh
stack runghc runtest.hs <args>
```

I do not know what the appropriate fix would be when cabal sandboxes are being used.

**Comment by jfdm** [comment]
I believe a fix for building with cabal sandboxes is to pass the location of the sandbox's `packages-conf.d` to ghc/runhaskell. For example:

```
runhaskell -package-db=../.cabal-sandbox/<packages-conf.d location> runtest.hs <args>
```

**Comment by melted** [comment]
I think the best solution is to make a little cabal file for runtest. Integrating it into idris.cabal will cause other problems. 
But is really heavyweight for scripting use as the exe will not be nearby and the location depends on sandboxing.

So I might just cut out the regex, there are other ways to find three digits in a row. :/

**Comment by jfdm** [comment]
It might be better to enforce a naming convention, for example: 

```
name ::= <test type name>, '-', <numerical identifier>, ('-disabled')?
```

That way you can say split on the 'hyphen' and if the name doesn't conform you can drop the test.

**Comment by melted** [comment]
It's easy and we don't have to change the names if we say that a valid test ends in three digits.
