### ISSUE TITLE
ReBase the test suite on Tasty and Tasty.Golden.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#2927]
@melted has replaced the current test suite written in Perl with one written in Haskell. Kudos.

This now allows for the test suite to be run using cabal-see #2922. However, we are still using a home grown test suite. Haskell has existing infrastructure with which we can replace our own one with another. Thereby reducing possible technical debt, and gaining access to an existing infrastructure.

At some point I think it would be wise to rebase the testing suite on [Tasty](http://documentup.com/feuerbach/tasty) and [Tasty-Golden](https://hackage.haskell.org/package/tasty-golden), with a smattering of [Tasty-Rerun](https://hackage.haskell.org/package/tasty-rerun).

It is not high on my list of priorities, but I will eventually look at it. Regardless, I thought I would mention it hear in case any aspiring contributor wishes to help.

**Comment by ysusuk** [comment]
hi Jan, i will be happy to help =)

**Comment by jfdm** [comment]
Ah cool. As the description says, it would be nice to get the idris test suite converted over to tasty. So just have at it, really.

The only real constraint is that the current interaction and execution of the test suit is kept the same. That is different backends can be tested against different subsets of the tests suite. If there are features of tasty that we can use then great. 

Any questions, just ask.

**Comment by ysusuk** [comment]
Hi @jfdm ,

what do you think about [tasty-program](https://github.com/jstolarek/tasty-program/):

```scala
import Test.Tasty
import Test.Tasty.Options
import Test.Tasty.Program

main :: IO ()
main = defaultMain tests

tests :: TestTree
tests = testGroup "idris" [
    testProgram "primitives006" "/Users/ysusuk/Idris-dev/test/primitives006/run" [""] Nothing
  ]
```

**Comment by jfdm** [comment]
Whilst `tasty-program` does look interesting, I do not see how it can be used to perform *whole program golden testing`. That is, not only do we run the program, but also we have checks of the expected output with the actual output. If that can be taken into account then great.

Also please bear in mind the constraint:

> The only real constraint is that the current interaction and execution of the test suit is kept the 
> same. That is different backends can be tested against different subsets of the tests suite. If there 
> are features of tasty that we can use then great.

**Comment by ysusuk** [comment]
Hi @jfdm ,
what do you think about this then,

```scala
import ...

main :: IO ()
main = defaultMain tests

tests :: TestTree
tests = testGroup "Tests" [goldenTests]

goldenTests = testGroup "Golden Tesst" [
    goldenVsFile "basic001" "pathTo/basic001/output-g" "bathTo/basic001/output"
      (callProcess "bash" ["cd", "pathTo/basic001/", "run"])
  ]
```

if output and output-g files differ:

```bash
  Golden Test
    basich001: FAIL
      Files 'pathTo/basic001/output-g' and 'pathTo/basic001/output' differ
```

**Comment by jfdm** [comment]
Closing this as a result of #3231
