### ISSUE TITLE
C backend can't handle libs installed in path with spaces

### ISSUE THREAD

**Issue by melted** [idris-lang/Idris-dev#2934]
Results in 

```
dris> :load d:\\Niklas\\idris\\test.idr
*d:\\Niklas\\idris\\test> :exec
gcc: error: Files: No such file or directory
gcc: error: (x86)\idris\./libs\rts: No such file or directory
gcc: error: Files: No such file or directory
gcc: error: (x86)\idris\./libs\rts: No such file or directory
gcc: error: Files: No such file or directory
gcc: error: (x86)\idris\./libs\prelude: No such file or directory
gcc: error: Files: No such file or directory
gcc: error: (x86)\idris\./libs\base: No such file or directory
FAILURE: "gcc" ["-O2","-fwrapv","-fno-strict-overflow","-DHAS_PTHREAD","-DIDRIS_ENABLE_STATS","-I.","C:\\Users\\niklas\\AppData\\Local\\Temp\\idris2810211069.c","-LC:\\Program","Files","(x86)\\idris\\./libs\\rts","-lidris_rts","-lpthread","-IC:\\Program","Files","(x86)\\idris\\./libs\\rts","-lm","-I.","-IC:\\Program","Files","(x86)\\idris\\./libs\\prelude","-IC:\\Program","Files","(x86)\\idris\\./libs\\base","-IC:\\Niklas\\src\\Idris-dev\\dist\\dist-sandbox-2b9f32d0\\build\\idris\\./libs\\prelude","-IC:\\Niklas\\src\\Idris-dev\\dist\\dist-sandbox-2b9f32d0\\build\\idris\\./libs\\base","-I.","-IC:\\Niklas\\src\\Idris-dev\\.cabal-sandbox\\x86_64-windows-ghc-7.10.3\\idris-0.10\\prelude","-IC:\\Niklas\\src\\Idris-dev\\.cabal-sandbox\\x86_64-windows-ghc-7.10.3\\idris-0.10\\base","-o","C:\\Users\\niklas\\AppData\\Local\\Temp\\idris29212382"]
C:\Users\niklas\AppData\Local\Temp\idris29212382.exe: rawSystem: does not exist (No such file or directory)
```

Thanks to pmwhite on IRC

**Comment by melted** [comment]
The includes into the build dir and .cabal-sandbox should also go away.

**Comment by Melvar** [comment]
IIRC why this happened is as follows: after I changed it to use `rawSystem` to inhibit injection attacks (and *fix* things with spaces in them), someone decided they absolutely needed to be able to specify multiple args in a single directive (instead of using multiple directives), and instead of adding that to the directive parsing they just added splitting on spaces in the C codegen.

**Comment by Melvar** [comment]
See for history #1701 and e57170d06ff108623222b3c53a4969e8821bec73. Further I objected to the latter on IRC and got the response that I’d broken the SDL library with #1701.

**Comment by melted** [comment]
Ok, seems like the correct thing is to put the splitting when the %flag directive is parsed. And not to do it on all of the things. But it seems to me that even that directive should respect quoted strings. 


----- Ursprungligt meddelande -----
Från: "Melvar Chen" <notifications@github.com>
Skickat: ‎2016-‎02-‎01 13:16
Till: "idris-lang/Idris-dev" <Idris-dev@noreply.github.com>
Kopia: "Niklas Larsson" <metaniklas@gmail.com>
Ämne: Re: [Idris-dev] C backend can't handle libs installed in path withspaces (#2934)

See for history #1701 and e57170d. Further I objected to the latter on IRC and got the response that I’d broken the SDL library with #1701.

**Comment by Melvar** [comment]
My problem is that I never understood why this was considered a problem with idris, rather than one with the way the SDL library inserted its includes.
