### ISSUE TITLE
Release notes for 0.10 contains error in interfaces example

### ISSUE THREAD

**Issue by jmgimeno** [idris-lang/Idris-dev#2944]
In the example about interface Eq

    interface Eq a where
        (==) : ty -> ty -> Bool
        (/=) : ty -> ty -> Bool

as you can see the type parameter is a but ty is used in the signatures of the functions.

**Comment by jfdm** [comment]
@jmgimeno Thanks for the issue, I am sure someone with write access to the website will fix the mistake.

**Comment by jfdm** [comment]
It has been fixed. I will close this issue now.
