### ISSUE TITLE
:printdef does not print records or interfaces as such

### ISSUE THREAD

**Issue by Melvar** [idris-lang/Idris-dev#2947]
`:printdef` when applied to something which is declared as a record or interface will print the underlying generated datatype as a `data` declaration.

```
> :printdef FFI
data FFI : Type where
  MkFFI : (Type -> Type) -> Type -> Type -> FFI
> :printdef Show
data Show : Type -> Type where
  constructor of Prelude.Show.Show : (ty -> String) -> (Prec -> ty -> String) -> Show ty
```

**Comment by enolan** [comment]
Yeah, it's incomplete. See also #2526.

**Comment by jfdm** [comment]
Maybe as this is a duplicate of #2526 we can remove this issue, perhaps?

**Comment by Melvar** [comment]
I didn’t see that because I was looking for *records*. I’ll add it to that.
