### ISSUE TITLE
Non-exhaustive patterns in function lamToLet

### ISSUE THREAD

**Issue by aaronc** [idris-lang/Idris-dev#2961]
I get this error:

```
idris: src/Idris/Erasure.hs:495:5-70: Non-exhaustive patterns in function lamToLet
```

when I have some code that tries to do list destructuring in a lambda binding, like: `([x] => ?rhs)`. (Note: this is assuming I know the number of elements as in `Vect 1 t`.)

**Comment by aaronc** [comment]
@ziman since you worked on erasure, maybe you have some idea as to the proper cases to handle in `lamToLet`?

**Comment by david-christiansen** [comment]
At the very least, all our functions that don't handle cases should have a
catchall that dumps an error message with a hint as to what it failed to
handle!

2016-02-09 19:03 GMT-05:00 Aaron Craelius <notifications@github.com>:

**Comment by ahmadsalim** [comment]
@aaronc Would it be possible for you to provide an extended snipped? I think it is hard to reproduce with just the provided information.

**Comment by bernstein** [comment]
Here is a small code snippet that produces the error.
```
idris bug.idr -o bug
idris: src/Idris/Erasure.hs:502:5-70: Non-exhaustive patterns in function lamToLet
```

```
-- bug.idr
data Op = Add | Mul

binop : Op -> Integer -> Integer -> Integer
binop Add = (+)
binop Mul = (*)

doOp : Op -> IO Integer
doOp op = pure (binop op 1 2)

main : IO ()
main = doOp Add >>= print
-- main = pure (binop Add 1 2) >>= print -- this works
```

**Comment by ahmadsalim** [comment]
@bernstein Thanks for the snippet!

**Comment by ziman** [comment]
@bernstein many thanks for the MFE!

**Comment by ziman** [comment]
(It turned out that nested lambdas are not resolved by repeated application of the rule for a single lambda.)
