### ISSUE TITLE
EDITOR should support commands with spaces

### ISSUE THREAD

**Issue by enolan** [idris-lang/Idris-dev#2963]
It's nice to be able to use EDITOR to set command line arguments to the editor. Presently:
```
enolan at Behemoth in ~/mystuff/code/Idris-dev-tests [parse*] 
$ EDITOR="emacs -nw" stack exec -- idris foo.idr
     ____    __     _                                          
    /  _/___/ /____(_)____                                     
    / // __  / ___/ / ___/     Version 0.10-git:fa9af46
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/      
 /___/\__,_/_/  /_/____/       Type :? for help               

Idris is free software with ABSOLUTELY NO WARRANTY.            
For details type :warranty.
Type checking ./foo.idr
*foo> :e
Uncaught error: emacs -nw: rawSystem: runInteractiveProcess: exec: does not exist (No such file or directory)
```

**Comment by jfdm** [comment]
That would be a nice idea. Given my lack of Windows knowledge: Is this a feature we can provide for all platforms on which we run Idris?

**Comment by melted** [comment]
Windows isn't the problem, it can use system just fine (starting in a cmd shell instead of sh), the problem here is the possibility to inject shell strings that are executed in a "system" call, which would be undesirable for bots such as idris-bot.

This shouldn't need to use rawSystem as a bot wouldn't need this command. I don't know if it is useful to have a switch to disable such commands or if the bots can scrub the inputs themselves just as well.

**Comment by melted** [comment]
Another possibility is to slice and dice the string ourselves, but correctly handlig quotations and escapes is dicey. The bug that made idris unusable in a directory with spaces was caused by aggressive cutting.

**Comment by david-christiansen** [comment]
I don't think we should reimplement shell parsing. Escaping and quotes may also be different from platform to platform.

I think that using normal `system` for `:e` should be safe - is there something I'm missing?

**Comment by melted** [comment]
No, you're not missing anything. Bots have no use for :e.

**Comment by Melvar** [comment]
idris-bot, for example, has a command whitelist, which there is no reason to include `:e` in.

However, I believe we wish to supply further arguments to the `$EDITOR`, so one either needs to escape those to include them in `system`, or split `$EDITOR` to include it in `rawSystem`. Assuming you wish to use the former, make sure to *test* filenames with awkward characters like space, `*`, `\` in them.

**Comment by jfdm** [comment]
erm i actually meant does idris currently access environment variables, and is this something that can be done on windows. I do not know much about windows programming. Naturally, you want to sanitise input taken from the user.

**Comment by melted** [comment]
Windows has env vars, the only difference with Posix is that Windows doesn't allow empty env vars, they're deleted if set to nothing.
