### ISSUE TITLE
basic017 breaks my terminal - Curses problem

### ISSUE THREAD

**Issue by enolan** [idris-lang/Idris-dev#2964]
Running `.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/regression-and-sanity-tests/regression-and-sanity-tests basic017` in tmux either makes my terminal stop updating anything other than the last line or makes it as though the terminal were half as tall as it is. The test fails as well. Outside of tmux, it runs properly, but I still get a test failure. This is the error:
```
Using stack work dir at ../.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/idris
basic017 finished...FAILURE
1c1,3
Uncaught error: user error (Curses[-1]:endwin)
---
> basic017a.idr:11:8:When checking type of Main.append:
> When checking an application of Main.Vect:
>         No such variable n

----
1 tests run: 0 succesful, 1 failed, 0 updated.

Failed tests:
basic017
```

The left side of the diff above is the same as the content of `test/basic017/output`, regardless of tmux. It runs successfully, giving the current output, if I `cd` into `tests/basic017` and do `./run`. And if I do `./run > log`. Running it with `make basic017.test` instead of from Stack's build of the test runner gives the same error as above.

Why would whether or not it's run from the test runner change the behavior of curses? And why would curses even be an issue when it's redirected to a file instead of the terminal? And what does the content of basic017 have to do with curses anyway?

This is 56122b5

**Comment by jfdm** [comment]
@enolan I have been running into the same issue. I believe it is related to the use of coloured output or the way in which coloured output put through the test runner might affect one's shell, however, I have yet to confirm that suspicion. Curses is used in Idris for getting the console width.

**Comment by melted** [comment]
It doesn't set the consolewidth like the other tests.
