### ISSUE TITLE
Clear documentation that type checker doesn't reduce what it can't see is total

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#2983]
Right now, the documentation doesn't clearly state that non-total definitions aren't reduced when type checking. As far as I can tell, it's only mentioned in the middle of a moderately-related FAQ entry. We should make this more obvious.

**Comment by david-christiansen** [comment]
Supersedes #2981

**Comment by xekoukou** [comment]
The relevant section on the tutorial is when the Dependent Types are discussed. Probably add a new section before them.

**Comment by edwinb** [comment]
I wonder what would happen if the type checker issued a warning when it encountered a non-total name in a type... given that it's unlikely to be what you wanted.

**Comment by ahmadsalim** [comment]
I think that #3098 actually fixes this.
