### ISSUE TITLE
(id : Nat ** Vect id Int) does not type check - but (n : Nat ** Vect n Int) does

### ISSUE THREAD

**Issue by jhegedus42** [idris-lang/Idris-dev#2984]
`(id : Nat ** Vect id Int)` does not type check (neither in the REPL nor in code - type checking with emacs-mode)
 
similarly 

`(map : Nat ** Vect map Int)` fails to type check too.

Probably already existing function names conflict with the sugar.

**Comment by jfdm** [comment]
Sorry no one has gotten back to you on this. We need to do better...

It is *hard* to say what is going on without access to the error messages. However, your intuition does imply a probably cause for type checking failure. That is, both `id` and `map` are pre-existing names; this will result in a type error.
