### ISSUE TITLE
"'public' is deprecated. Use 'public export' instead." Expected behavior? Bug?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2985]
The warning is triggered (0.10-git:65125ae) by replacing
```
> %access public export
```
with
```
> %access public
```
at line 30 of
```
https://github.com/nicolabotta/SeqDecProbs/blob/master/frameworks/14-/FractionProperties.lidr
```
:
```
nicola@cirrus:~/github/SeqDecProbs/frameworks/14-$ idris +RTS -K32000000 -RTS -p contrib -p effects --verbose --warnreach FractionProperties.lidr 
FractionProperties.lidr:33:1:
'public' is deprecated. Use 'public export' instead.
Type checking ./FractionProperties.lidr
*FractionProperties>
```
Is this the expected behavior? Why is `public` deprecated here? 

More generally, I have difficulties understanding how the new visibility rules are meant to be used to control the access of names in derived modules. For instance, is
```
> public export fromNatNormal : {n : Nat} -> Normal (fromNat n)
> fromNatNormal = MkNormal anyCoprimeOne
> %freeze fromNatNormal
```
equivalent to 
```
> public fromNatNormal : {n : Nat} -> Normal (fromNat n)
> fromNatNormal = MkNormal anyCoprimeOne
```
for derived modules? Is it equivalent for in-module expressions in which `fromNatNormal` appears and is not implicitely quantified? 

How are functions whose implementation has to be accessible in some derived modules and has to be inaccessible in other derived modules meant to be declared? `public export` or `public`? Is it possible to "thaw" frozen implementations in client code?

Thanks,
Nicola

**Comment by david-christiansen** [comment]
This is expected behavior. The old keyword `public` has simply been renamed to `public export`, the old keyword `abstract` has been renamed to `export`, and the default has been set to `private`.

> How are functions whose implementation has to be accessible in some derived modules and has to be inaccessible in other derived modules meant to be declared?

Derived modules aren't _really_ a feature in Idris - rather, it's been a happy accident of the implementation that you've made good use of in the absence of a proper module system. Because it's been an accidental side effect, there aren't well-considered semantics.

It might be a good idea for you to construct some self-contained test cases that demonstrate the desired behavior, and contribute them to the Idris test suite.

**Comment by nicolabotta** [comment]
> This is expected behavior. The old keyword public has simply been renamed to public export, the old keyword abstract has been renamed to export, and the default has been set to private.

Thanks David! Blame on me!

> It might be a good idea for you to construct some self-contained test cases that demonstrate the desired behavior, and contribute them to the Idris test suite.

I think that the example that I have posted on idris-lang:
```
module LalaOps
...
plus : Lala -> Lala -> Lala
plus x y = ...
...
```
is paradigmatic enough. Just replace `Lala` with `Rational`, `Double`, `Nat` or whatever you like. 

It is clear that there will be modules that import `LalaOps` and need access to the implementation of `LalaOps.plus`. For instance, a `LalaProps`module. 

But it is also very clear that there might be modules that import `LalaOps` but should not have access to the implementation of `LalaOps.plus`. 

For instance, in SeqDecProbs, we found a very strong argument for hiding the implementation of imported functions when we realized, a few months after my visit to Chalmers in 2014, that freezing certain implementations can make the difference between type checking within seconds and type checking within days!

Thus, it seems clear that whether the implementation of `LalaOps.plus` should be accessible or not, can only be meaningfully decided by the modules that import `LalaOps`, not by `LalaOps`itself.

This suggests that a canonical idiom could be to declare all module features to be `public export`-able (which would support the "old" default) and to leave it to clients to restrict the accessibility of certain features via specific `%freeze` directives:
```
module Main
import LalaOps
%freeze LalaOps.plus
```
But, as I reported in #2977, `%freeze` seems to behave fuzzily in conjunction with the new visibility rules. Also, I am not sure that this is how the new rules are meant to be applied.

I guess the bottom line is that I have not understood how the new rules are meant to be applied for clients to be able to set the accessibility status of imported features.

**Comment by jfdm** [comment]
@nicolabotta I do not know if the following will help, as I haven't read too much into this issue currently, as I have been busy. However, have you considered use of the public modifier for imports? 

Use of the modifier `public` in an import declaration allows you to promote the imported module's definition to the definition of the calling module.  I have used this on many occasions to control how a client exposes features. That is: say you have a module, `Provider` that provides some functionality. The `Subscribe` module can then promote the API of `Provider` as follows:

```idris
import public Provider
```

No idea if that helps, but worth a shot.

**Comment by nicolabotta** [comment]
Thanks jfdm! 

I do believe that import directive (or perhaps a combination of import and hide + freeze directives?) should control the accessibility of features of the imported modules. 

I have tried your suggestion and for my example it does not work. I am going to close this issue an open another one with the title "How to apply the 'private', 'export' and ' public export' accessibility qualifiers?" and with a paradigmatic example.

**Comment by nicolabotta** [comment]
David, Jan, I have opened #2990 with a self-contained example (a base module, two library modules and an application module) that illustrate the problem of how to apply the new accessibility qualifiers. Best, Nicola
