### ISSUE TITLE
Lifting hole to top level definition missing parentheses

### ISSUE THREAD

**Issue by cameron-martin** [idris-lang/Idris-dev#2987]
If I have a program such as

```
doubleList : List Int -> List Int
doubleList xs = map ?double xs
```

This type checks fine.

When I ask idris to move the double hole to a top level definition, it gives

```
double : (xs : List Int) -> Int -> Int

doubleList : List Int -> List Int
doubleList xs = map double xs xs
```

This no longer type checks, and should instead be:

```
double : (xs : List Int) -> Int -> Int

doubleList : List Int -> List Int
doubleList xs = map (double xs) xs
```

**Comment by david-christiansen** [comment]
Thanks for the report! It seems that the issue is that the parens aren't added, so I've updated the title accordingly.

**Comment by edwinb** [comment]
This works in master now
