### ISSUE TITLE
No such variable Prelude.cast_error

### ISSUE THREAD

**Issue by colin-adams** [idris-lang/Idris-dev#2996]
After upgrading from 0.10.1 to 0.10.2 I get:

When attempting to perform error reflection, the following internal error occurred:
        No such variable Prelude.cast_errorThis is probably a bug. Please consider reporting it at https://github.com/idris-lang/Idris-dev/issues

**Comment by colin-adams** [comment]
To reproduce:

Clone https://github.com/colin-adams/chu_shogi_server.git

Type-check src/Move.idr

**Comment by edwinb** [comment]
This is odd - I can't reproduce this, it type checks fine.

The only thing I can think of to try is to delete all the ibc files and try again, possibly even deleting any old versions of idris libraries in your .cabal directory. Though I don't know why that would cause this particular error, nor can I think of anything recent that would have made ibcs fail to load, or even find anything in git log...

It would be useful to know why this happened, even if just to give a useful message saying  what you need to do, but I'm not sure how to do that given that I can't reproduce it from scratch.

**Comment by colin-adams** [comment]
1) Tried idris --clean chu.ipkg followed by idris --checkpkg chu.ipkg. This progresses further - it passes Move.idr but fails later with a variation on the same theme:

ype checking ./Direction.idr
Type checking ./Piece.idr
Type checking ./Coordinate.idr
Type checking ./Board.idr
Type checking ./Move_state.idr
Type checking ./Forsythe_parser.idr
Type checking ./Move.idr
Type checking ./Stack.idr
Type checking ./Game_state.idr
When attempting to perform error reflection, the following internal error occurred:
        No such variable Language.Reflection.UNThis is probably a bug. Please consider reporting it at https://github.com/idris-lang/Idris-dev/issues

2) Tried idris --clean chu.ipkg  then rm -rf ~/.cabal/packages/h*/idris/0.10 and rm -rf ~/.cabal/packages/h*/idris/0.10 
followed by idris --checkpkg chu.ipkg.
This gives the identical result to step (1).

I'll try to think of anything else I might be able to try.

**Comment by colin-adams** [comment]
Also tried rm ~/.idris/repl/history then clean and checkpkg as before. No change.
Also tried rm -rf /home/colin/.cabal/lib/x86_64-linux-ghc-7.8.4/idris-0.10
then clean and checkpkg as before. Again no change.
Also tried rm -rf /home/colin/.cabal/lib/x86_64-linux-ghc-7.8.4/idris-0.10.1 etc. No change.
Also tried rm -rf /home/colin/.cabal/share/doc/x86_64-linux-ghc-7.8.4/idris-0.10 and 0.10.1 etc. No change.
Also tried rm -rf /home/colin/.cabal/share/x86_64-linux-ghc-7.8.4/idris-0.10 and 0.10.1 etc.

This finally seems to do the trick (I get a proper programming error now - I've been developing blind since reporting the issue).

**Comment by colin-adams** [comment]
Confirmed fixed.

Please either code the issue as a user error (if there are upgrade instructions that I've overlooked), or as a documentation error (if multiple versions of idris are not supposed to be able to coexist, but this is documented), or fix it if you think there's still a bug.

**Comment by jfdm** [comment]
Sometimes when renaming files, or doing general refactoring of a code base some old ibc files may get left and are still accessible to the Idris compiler. These files also won't be removed when calling `idris --clean` as if they are not in the idris package file, idris will ignore them. The trick here is to find all ibc files in your project (or lib install dir) and move them manually.

**Comment by colin-adams** [comment]
OK. 
I think it may be worth adding a note about this in http://docs.idris-lang.org/en/v0.10.2/tutorial/starting.html#downloading-and-installing . 

In the longer term, something more automatic will be necessary, I think.

**Comment by edwinb** [comment]
I believe I've found the problem (largely by chance...) and fixed this, as in #2986
