### ISSUE TITLE
SKI combinators don't mix well

### ISSUE THREAD

**Issue by chamini2** [idris-lang/Idris-dev#3008]
I'm comparing some programming languages and noticed that in Idris the SKI combinators don't work well together:

```
subs : (a -> b -> c) -> (a -> b) -> a -> c
subs f g x = f x (g x)
konst : a -> b -> a
konst x _ = x
iid : t -> t
iid x = x
```

And when using them:

```
*idris> subs konst konst 2
(input):Can't infer argument b to konst
```

That is equivalent to `iid`, it should just return `2`.

**Comment by edwinb** [comment]
This is expected. What should 'b' be here in each application of 'konst'? Idris needs to fill in all of the implicit arguments to konst, and has no information that tells it what type it should be throwing away. Compare:

    *konst> konst 2 3
    2 : Integer

    *konst> konst 2
    (input):Can't infer argument b to konst

    *konst> konst 2 {b=Nat}
    konst 2 : Nat -> Integer
