### ISSUE TITLE
public export Foo.getP can't refer to private Foo.getW: expected behavior?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3015]
The program
```
> module Foo
> %default total
> %access public export

> private getW : {P : a -> Type} -> Exists {a} P -> a
> getW (Evidence x pf) = x
> getP : {P : a -> Type} -> (x : Exists {a} P) -> P (getW x)
> getP (Evidence x pf) = pf
```
fails to type check with the error message:
```
- + Errors (1)
 `-- private.lidr line 7 col 5:
     public export Foo.getP can't refer to private Foo.getW
```
Is this the expected behavior? My understanding is that a `private foo` in a `Foo` module should make `Foo.foo` not accessible in modules that import `Foo`. 

But, in `Foo`, I would expect `private foo` to be accessible! What is otherwise the point in implementing functions that cannot be used? 

Notice that, in the specific example, declaring `getP` to be `export` accessible (instead of `public export`) does not help either because `getW` is applied in defining the signature of `getW`, not its implementation.

The rationale behind the example is obviously that, for a dependent pair with erasurable first component, one might want to make `getProof` `export` (perhaps `public export`) accessible but `getWitness` only `private` accessible.

**Comment by edwinb** [comment]
If it's a public export, it's definition is exported, so that will mean the private thing leaks. So yes, this is expected. If you want getW in an exported type, it'll need to be exported itself.
