### ISSUE TITLE
Type functions in records introduce spurious parameters?

### ISSUE THREAD

**Issue by fmap** [idris-lang/Idris-dev#3027]
On [`60f2277`](https://github.com/idris-lang/Idris-dev/commit/60f2277b4df1e145f3e99e642ee0b119b84a6445) the following is fine:

```idris
Symmetric : {c : Type} -> (c -> c -> Type) -> Type
Symmetric {c} rel = {a, b : c} -> rel a b -> rel b a

record Symmetry (t : Type) (rel : t -> t -> Type) where
  constructor MkSymmetry
  is_symmetric : Symmetric {c=t} rel

symmetry : {a : Type} -> Symmetry a (=)
symmetry = MkSymmetry sym
```

But on [`504187b`](https://github.com/idris-lang/Idris-dev/commit/504187ba5809023a8bd3ed79dd65d19a832a8de1) it fails to type-check, as if the first implicit were an explicit parameter:

```
When checking right hand side of symmetry with expected type
        Symmetry a (=)

Type mismatch between
        (l = r) -> r = l
and
        (\a2 => (a2 = b) -> b = a2) a2
```

It may be appeased as it suggests:

```diff
9c9
< symmetry = MkSymmetry sym
---
> symmetry = MkSymmetry (\_ => sym)  
```

Or, alternatively, by inlining the definition:

```diff
1,3d0
< Symmetric : {c : Type} -> (c -> c -> Type) -> Type
< Symmetric {c} rel = {a, b : c} -> rel a b -> rel b a
<
6c3
<   is_symmetric : Symmetric {c=t} rel
---
>   is_symmetric : ({a, b : t} -> rel a b -> rel b a)
```

The issue seems restricted to records; this works with both builds of Idris:

```idris
symmetry : Symmetric (=)
symmetry = sym
```

**Comment by edwinb** [comment]
This is to do with the scoped implicits in the definition of Symmetric rather than records. I have a fix for this, but I'd like to convince myself of why the old way didn't work properly before I push it. Won't be long...

**Comment by fmap** [comment]
Thank you!
