### ISSUE TITLE
Can't disambiguate name: expected behavior?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3028]
The programs
```
> module Foo
> %access public export 
> Foo : Type
> Foo = Bool
```
```
> import Foo
> Foo : Type
> Foo = Foo.Foo
> a : Bool
> a = True
> p : Foo.Foo = Main.Foo
> p = Refl
```
type check fine in 0.10.2. But replacing
```
> a : Bool
```
with
```
> a : Foo
```
in the second program yields
```
- + Errors (1)
 `-- Main.lidr line 4 col 2:
     When checking type of Main.a:
     Can't disambiguate name: Foo.Foo, Main.Foo
```
Is this the expected behavior?

**Comment by david-christiansen** [comment]
Yes, I'd expect this behavior. It encounters the expression `Foo` in a context where it expects an element of `Type`. Two such `Foo`s are in scope. I don't think it should traverse them to find that they in fact reduce to the same thing - that would be a bit too magical for my taste.
