### ISSUE TITLE
Error message does not name the offending function

### ISSUE THREAD

**Issue by colin-adams** [idris-lang/Idris-dev#3040]
When trying to build a package that uses another package (the latter wrapping C functions and still under development, likely to be highly buggy), I get the following:

idris: Idris function couldn't be wrapped.

This is annoying as it does not name the C function that it could not wrap. In this case, I was able to guess the function concerned (commenting out the foreign call stops the message). But really the message should name the function it was attempting to wrap, at least (why it couldn't wrap it would be a bonus).

**Comment by melted** [comment]
The most likely reason to get this this error message is if the idris function is passed as a parameter to the foreign call, that is you have something like this:

```idris
example : (Int -> ()) -> IO ()
example f = foreign FFI_C "callbacker" (CFnPtr (Int -> ()) -> IO ()) (MkCFnPtr f)
```
(I see I forgot the MkCFnPtr in the example in the documentation)

That isn't supported as it would require too much clairvoyance about what functions are exported to handle in the current implementation, it would have to make an analysis pass to determine all possible candidates.

The reason the name isn't in the error message is likely that it isn't immediately available at the location where it's generated. It shouldn't be hard to thread it to there.

**Comment by colin-adams** [comment]
If it's not supported then I can't wrap the libmicrohttpd library. It is
compulsory to pass a callback function for the request handler. And this is
something the client of the wrapper library has to write.

**Comment by colin-adams** [comment]
Or perhaps I could just add an extra level of indirection - a fixed
callback function that takes a callback argument itself?

**Comment by melted** [comment]
Sounds like a feature request. :-)

It's functionality I would like to add in any case, I just have to think if there's a way to do it quickly.

**Comment by melted** [comment]
There's one way to do it now, but it requires that the users call foreign with `%wrapper` themselves to generate a C function pointer from an idris function.

**Comment by melted** [comment]
then you can have that function just take a Ptr. (which the users get from their %wrapper)

**Comment by colin-adams** [comment]
But %wrapper returns an IO Ptr, not a Ptr.

**Comment by colin-adams** [comment]
So I tried pulling the pointer out of the IO ptr to pass it as a Ptr. This
type checks but now at build time:

idris: Cannot create C callbacks for IO functions, wrap them with
unsafePerformIO.

So my question is what and where do I wrap with undafePerformIO?

To put a bit of context, here's the call that TAKES the callback:

export start_daemon : (flags : Bits32) -> (port : Bits16) -> (apc : Ptr) ->
(apc_cls : Ptr) -> (handler : Ptr) -> (arg : Ptr) -> IO Ptr
start_daemon flags port apc apc_cls handler arg = do
  daemon <- foreign FFI_C "C_start_daemon" (Bits32 -> Bits16 -> Ptr -> Ptr
-> Ptr -> Ptr -> IO Ptr) flags port apc apc_cls handler arg
  pure daemon

And here's the callback itself:


||| Our URL handler
answer_to_connection : Request_handler
answer_to_connection cls conn url method version up_d up_d_sz con_cls = do
  response <- create_response_from_buffer page MHD_RESPMEM_PERSISTENT
  ret <- queue_response conn HTTP_OK response
  destroy_response response
  pure ret

 where page : String
       page = "<html><body>Hello, browser!</body></html>"


wrapper : IO Ptr
wrapper = foreign FFI_C "%wrapper" ((CFnPtr Request_handler) -> IO Ptr)
(MkCFnPtr  answer_to_connection)

main : IO ()
main = do
  wr <- wrapper
  daemon <- start_daemon MHD_USE_SELECT_INTERNALLY 8912 null null (wr) null
-- MHD_OPTION_END
  case daemon == null of
    True  => pure () -- set exit code to 1 - HOWTO
    False => do
      x <- getChar
      stop_daemon daemon
      pure ()

**Comment by melted** [comment]
answer_to_connection could just have `unsafePerformIO $` stuck in front of the do

**Comment by melted** [comment]
It's pretty silly looking to require unsafePerformIO, but the function isn't run from main so there's no IO around when the callback is called. I hope I can make that go away.

**Comment by colin-adams** [comment]
That doesn't work.

First, it doesn't type-check:

 `-- Hello_browser.idr line 15 col 7:
     When checking right hand side of answer_to_connection with expected
type
             IO Int

     When checking an application of function Prelude.Applicative.pure:
             Type mismatch between
                     Int (Type of ret)
             and
                     IO Int (Expected type)

I can restore type-checking by changing pure ret to pure $ pure ret, but
that yields the same error message at build time as without the
unsafePerformIO (I think the two changes just cancel each other out).

**Comment by colin-adams** [comment]
Oh. You mean also change it's return type from IO int to plain int?

**Comment by colin-adams** [comment]
Doing that gets me a compiled web server, but when make a request, I get:

[colin@localhost example]$ idris --build *.ipkg
Type checking ./Hello_browser.idr
[colin@localhost example]$ ./hello_browser
No vm available in callback.[colin@localhost example]$
[colin@localhost example]$

So it seems we have only dodged the issue at compile time, for it to rear
it's ugly head at runtime.

**Comment by melted** [comment]
I see, that's weird. I wonder how that could even happen. Can you share the
code?
Den 17 mars 2016 08:29 skrev "Colin Adams" <notifications@github.com>:

> Doing that gets me a compiled web server, but when make a request, I get:
>
> [colin@localhost example]$ idris --build *.ipkg
> Type checking ./Hello_browser.idr
> [colin@localhost example]$ ./hello_browser
> No vm available in callback.[colin@localhost example]$
> [colin@localhost example]$
>
> So it seems we have only dodged the issue at compile time, for it to rear
> it's ugly head at runtime.
>
>

**Comment by colin-adams** [comment]
I've checked in.

git@github.com:colin-adams/idris-libmicrohttpd.git

then

idris --install MHD.ipkg
cd example

idris --build *.ipkg

./hello_browser

go to a web browser and type in http://localhost:8912/

**Comment by colin-adams** [comment]
Oh. That's with /usr/lib64/libmicrohttpd.so on the system (that's how it
gets installed in fedora 23)

**Comment by melted** [comment]
Thanks, I'll take a look at it after work.

**Comment by melted** [comment]
It's multithreading, there's a vm per thread so if the callback is called on another thread without a vm there's nothing there. I can just create a vm on that thread in that case.

**Comment by colin-adams** [comment]
That makes sense. In fact the callback will never be on the same thread as
the thread that calls C_start_daemon (I just checked the documentation in
case there's a single-threaded mode I could use for further testing in the
meantime, but there isn't).

**Comment by melted** [comment]
I have merged a fix for that.

**Comment by colin-adams** [comment]
I noticed. Unfortunately idris HEAD doesn't build at the moment, so I can't test it.

**Comment by colin-adams** [comment]
I worked out what to do to build HEAD. The problem is fixed (but my example program just hangs :-( )
