### ISSUE TITLE
Сhurch encoding sample

### ISSUE THREAD

**Issue by zraffer** [idris-lang/Idris-dev#3042]
the code checks well:

```
myTrue : (A : Type) -> A -> A -> A
myTrue a c d = c
```

whereas the following with named type doesn't:

```
myBool : Type
myBool = (A : Type) -> A -> A -> A

myTrue : myBool
myTrue a c d = c
```

with error

```
Test.idr:7:8:
When checking right hand side of myTrue with expected type
        iType

Type mismatch between
        _ (Type of c)
and
        iType (Expected type)
```

**Comment by nicolabotta** [comment]
But the program
```
> myBool : Type
> myBool = (A : Type) -> A -> A -> A

> myTrue : Main.myBool
> myTrue a c d = c
```
type checks fine!

**Comment by nicolabotta** [comment]
This
```
> MyBool : Type
> MyBool = (A : Type) -> A -> A -> A

> myTrue : MyBool
> myTrue a c d = c
```
and this
```
> %auto_implicits off
 
> myBool : Type
> myBool = (A : Type) -> A -> A -> A

> myTrue : myBool
> myTrue a c d = c
```
also type checks fine. The problem with your original example is that 'myBool' in
```
> myTrue : myBool
``` 
is implicitly quantified:

> Names which begin with a lower case letter, which appear in an argument position or unapplied, are always automatically implicitly quantified.

I guess that, with `%auto_implicits on` (the default), your declaration is equivalent to something like
```
> myTrue : {myBool : _} -> myBool
```
Switching auto implicits off makes the type checker bind the name 'myBool' in 
```
> myTrue : myBool
``` 
to `Main.myBool` which is what you want.

**Comment by zraffer** [comment]
Oh! Thank you.
