### ISSUE TITLE
Improve the error message of `rewrite ... in ...` by showing the term that is rewritten with

### ISSUE THREAD

**Issue by ahmadsalim** [idris-lang/Idris-dev#3052]
Hi,

Currently the error message of rewrite is somewhat confusing since it may not be immediately clear why the rewrite failed. A simple suggestion would be to include the term to be rewritten with in the error message, which may give the programmer a hint on why it did not match.

For example

```idris
import Data.Vect

test : {n : Nat} -> Vect (n + 0) Integer
test {n} = rewrite (plusCommutative 0 n) in replicate n 10
```

currently gives the following error message:

```idris
 `-- test.idr line 4 col 5:
     When checking right hand side of test with expected type
             Vect (n + 0) Integer
     
     rewrite did not change type Vect (plus n 0) Integer
```

which does not give much additional information.

I suggest that the message is changed to something like:

```idris
 `-- test.idr line 4 col 5:
     When checking right hand side of test with expected type
             Vect (n + 0) Integer
     
     rewriting with 0 + n did not change type Vect (plus n 0) Integer
```

which now makes it immediately clear that the arguments to `plusAssociative` were switched around.

**Comment by Melvar** [comment]
Pondering this, perhaps that line should mention both sides, as in
```
    rewriting 0 + n to n + 0 did not change type Vect (plus n 0) Integer
```
But that could get verbose quick too.

**Comment by ahmadsalim** [comment]
Melvar: Perhaps, this would make sense if both sides were identical, and then the error message could be extended to (rewriting with something else):

```idris
rewriting with n did not change type Vect n Integer, left and right hand sides of the equation are identical
```

or something like that.
