### ISSUE TITLE
Feature request: issue a warning when an automatic implicit variable shadows another variable 

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3053]
Issues #3042, #3041, #3031 and a number of posts on idris-lang suggest that it would be useful to **issue a warning** when (with `%auto_implicits on` as per default) an **automatic implicit variable shadows another variable**. 

The rationale: unintended shadowing can be difficult to spot and lead to error messages that are not necessarily very useful. On the other hand, it should be fairly easy to issue a warning whenever a (possibly unintended) shadowing occurs as a consequence of automatically generated local bindings. In such situations, it seems that warnings would significantly improve support for program development at a moderate cost.

**Comment by edwinb** [comment]
It would be easy, but also very noisy in a lot of reasonable cases. e.g.

    reverse : List elem -> List elem

The machine is unable to read your mind about your intention, and if we have warnings for shadowing here, why not warnings for shadowing in lots of other places which would be equally unintended and equally easy to detect?

**Comment by edwinb** [comment]
What might be possible actully would be an elaborator directed warning which reports if the name would happen to work. I don't know how easy this will be, but I will have a quick look just in case.

**Comment by nicolabotta** [comment]
... works like a charm! Thanks, Nicola
