### ISSUE TITLE
Interface declarations broken? Me too old for Idris? Perhaps both?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3055]
I am not completely new to Idris but it seems that I have so far failed to understand how interfaces are supposed to be used. Consider the fragment
```
> module ContainerMonad
> %default total
> %auto_implicits off
> %access public export
> M : Type -> Type
> Elem : {A : Type} -> A -> M A -> Type
> All : {A : Type} -> (P : A -> Type) -> M A -> Type
> tagElem : {A : Type} -> (ma : M A) -> M (DPair A (\ a => a `Elem` ma))
```
This type checks fine and, as expected, generates 4 holes. I understand that modules with holes are not a canonical idiom for putting forward specifications. Thus, let's try to use interfaces, instead. Now, the pretty obvious
```
> module ContainerMonad
> %default total
> %auto_implicits off
> %access public export
> interface Monad M => ContainerMonad (M : Type -> Type) where
>   Elem : {A : Type} -> A -> M A -> Type
>   All : {A : Type} -> (P : A -> Type) -> M A -> Type
>   tagElem : {A : Type} -> (ma : M A) -> M (DPair A (\ a => a `Elem` ma))
```
fails to type check with
```
- + Errors (1)
 `-- ContainerMonad.lidr line 8 col 49:
     When checking type of constructor of ContainerMonad.ContainerMonad:
     When checking argument P to type constructor Builtins.DPair:
             Type mismatch between
                     M A -> Type (Type of Elem A _)
             and
                     Type (Expected type)
```
Is this the expected behavior? What am I doing wrong here? How can I extend the `Monad` interface with the additional features `Elem`, `All` and `tagElem`? Thanks, Nicola

**Comment by edwinb** [comment]
This should work as you intend, but something weird is going on with the implicit in Elem. I'll take a look - it would be nice to finally get dependent interfaces right.

I made this elaborate by adding A as a parameter to the interface (it makes the implicit problem go away), but you don't want to have to do that.

**Comment by edwinb** [comment]
Oh, I missed the %auto_implicits off at the top. It's related to that, because if I turn it off and remove the implicits, it works fine. Hopefully this won't take long...

**Comment by nicolabotta** [comment]
Thanks a lot Edwin! Here, for completeness, the envisaged interface:
```
> module ContainerMonad

> %default total
> %auto_implicits off
> %access public export


> ||| The container monad interface
> interface Monad M => ContainerMonad (M : Type -> Type) where

>   Elem    : {A : Type} -> A -> M A -> Type
>   All     : {A : Type} -> (P : A -> Type) -> M A -> Type
>   tagElem : {A : Type} -> (ma : M A) -> M (DPair A (\ a => a `Elem` ma))

>   spec1   : {A : Type} -> {a : A} -> a `Elem` (return a) 

>   spec2   : {A : Type} -> {a : A} -> {ma : M A} -> {mma : M (M A)} ->
>             a `Elem` ma -> ma `Elem` mma -> a `Elem` (join mma)

>   spec3   : {A : Type} -> {P : A -> Type} -> {a : A} -> {ma : M A} ->
>             All P ma -> a `Elem` ma -> P a

>   spec4   : {A : Type} -> {ma : M A} -> map fst (tagElem ma) = ma
```
Best,
Nicola
