### ISSUE TITLE
`stack build` fails

### ISSUE THREAD

**Issue by tswilkinson** [idris-lang/Idris-dev#3056]
I have a clone of the latest version of this github repo, and running `stack build` fails with this error:

> ./Pruviloj/Derive/DecEq.idr:79:8:
> When checking right hand side of headIs with expected type
>         Bool
> 
> When checking argument val to constructor Delay:
>         Can't find implementation for Eq TTName
> ./Pruviloj/Derive/DecEq.idr:84:10:
> When checking right hand side of Pruviloj.Derive.DecEq.case block in mkRhs at
> ./Pruviloj/Derive/DecEq.idr:84:10 with expected type
>        Elab ()
> 
> No such variable unApply
> ./Pruviloj/Derive/DecEq.idr:165:18-20:
> When checking right hand side of Pruviloj.Derive.DecEq.case block in case block in case block in deriveDecEq at ./Pruviloj/Derive/DecEq.idr:139:26 at ./Pruviloj/Derive/DecEq.idr:141:64 at ./Pruviloj/Derive/DecEq.idr:162:17 with expected type
>         Elab (List (TTName, Binder Raw),
>               List (TTName, Binder Raw),
>               (TTName, Binder Raw),
>               TTName,
>               Binder Raw)
>
> No such variable binderTy
> Makefile:5: recipe for target 'build' failed
> make[1]: Leaving directory '/home/tom/Idris-dev/libs/pruviloj'
> make[1]: *** [build] Error 1
> make: *** [build] Error 2
> Makefile:2: recipe for target 'build' failed
> make: Leaving directory '/home/tom/Idris-dev/libs'

**Comment by jfdm** [comment]
@tswilkinson I was updating my idris this morning too, and have noticed the error. I am currently doing a series of numpty checks to find out the cause, and also bumping stack at the same time.

**Comment by jfdm** [comment]
In the mean time, can I suggest using the recent hackage version of idris. This release of Idris was only released in the last couple of days, so it is not that out-of-date w.r.t. to HEAD.

It can be installed using: `cabal install idris`, and presumably `stack install idris`.

A good tip if working with and developing on idris, is to keep a known stable copy around. I achieve this by installing the hackage version after each point release, but generally use HEAD.

**Comment by jfdm** [comment]
Right, turns out the issue is *most* likely due to a stale ibc or un-removed ibc file. Purging `libs/` of all ibc files should fix the issue. 

If not, (I personally did this), purge the `.stack-work/` directory.

Let me know if this is fixed for you then I can close the issue.

**Comment by tswilkinson** [comment]
Purging `libs/` worked.  Cheers!
