### ISSUE TITLE
Memory leak in 0.11? Type checking not terminating ...

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3077]
With `0.10.3-git:PRE` and on a fresh installation of https://github.com/nicolabotta/SeqDecProbs, 
```
$ cd SeqDecProbs-master/frameworks/14-/
$ make example1
```
terminates in about 1.5 minutes and with memory usage constantly well below 10%. But with `0.11-git:faa58ad`, memory usage creeps up to about 80% within a few minutes and type checking does not appear to terminate.

**Comment by nicolabotta** [comment]
I have done some bisection on the latest commits and the culprit is ...

**c9d2027 "Use exact name lookup for hiding"**

Type checking and compilation terminate until commit cba27c8. With c9d2027 and later commits, type checking does not terminate. In the specific example, type checking goes well until line 328 and starts eating-up memory (and finally swapping) in type checking lines 330-335.

**Comment by edwinb** [comment]
It looks like the change I made for hiding should also have been done for freezing. I'm not sure why I didn't just do that, but there you go. This seems to fix things. Patch coming shortly.

It's probably worth looking more closely at the problem that causes freeze to be required in the first place here. I've implemented a weak head normal form evaluator now which may improve things a lot.

**Comment by nicolabotta** [comment]
Thanks Edwin! I have no idea what is going on under the hood here but what I can say with (a reasonable degree of) certainty is that, from the very first time the problem of type checking not terminating showed up -- and it was a few years ago when we had a lot of believe_me floating around and we thought that they could be the cause of the problem -- it was while type checking `maxSpec` and `argmaxSpec`, not `max` and `argmax`. I find it difficult to understand how type checking `max` and `argmax` can be a matter of seconds but type cheking `maxSpec` and `argmaxSpec` can take hours (days? months?) . The definitions seem equivalent to me. I guess I'll have to go for another beer or, perhaps better, straight to bed. Best, Nicola
