### ISSUE TITLE
':x main' and ':exec main' yield inconsistent results!

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3088]
On a fresh installation of `https://github.com/nicolabotta/SeqDecProbs`, you should be able to do
```
$ cd SeqDecProbs-master/frameworks/14-/
$ idris +RTS -K32000000 -RTS -p contrib -p effects SeqDecProbMonadicExample1.1.lidr
```
The program should type check in about 2 minutes. Now, at the Idris prompt, do
```
*SeqDecProbMonadicExample1.1> :x main
```
and enter 1 and 1 for the required "number of steps" and "initial column". This yields, in about three minutes:
```
*SeqDecProbMonadicExample1.1> :x main
enter number of steps:
1
 Nat: thanks!
enter initial column:
1
 Nat, < 11: thanks!
computing optimal policies ...
computing optimal controls ...
[[(1 ** L), (0 **  )]]
done!
MkIO (\w => prim_io_return ()) : IO' (MkFFI C_Types String String) ()
*SeqDecProbMonadicExample1.1>
```
This is the expected result of the computation. Now, try
```
*SeqDecProbMonadicExample1.1> :exec main
```
and, again, enter 1 and 1 for "number of steps" and "initial column". This yields
```
*SeqDecProbMonadicExample1.1> :exec main
enter number of steps:
 Nat: 1
thanks!
enter initial column:
 Nat, < 11: 1
thanks!
computing optimal policies ...
No location:No pattern clauses
*SeqDecProbMonadicExample1.1>
```
Thus, **we have that `:x main`and `:exec main` yield inconsistent results!**. This issue is a follow-up of #3054 which is now closed. 

The problem already shows up in 10.2 and makes it virtually impossible to build reliable executables in Idris.

**Comment by edwinb** [comment]
I've flagged this as Major because "No pattern clauses" should never happen at run-time (it most likely means 'void' is being executed)

**Comment by nicolabotta** [comment]
Thanks Edwin! I have just reproduced the error from a fresh installation and with 8133d8b. I have also made some further tests and all what I compute at the Idris prompt makes perfectly sense to me. It is only when trying to execute the object code that things go wrong. 

It this can help, there is an `example1` in the same directory (`make example1`) that type checks, compiles and executes fine. `example1.1` should compute the same results as `example1`modulo some pretty printing. The essential difference between `example1`and `example1.1`is that in `example1` certain functions that compute an `x : X` actually return `Id x` whereas in `example1.1` they return `[x]`.

**Comment by edwinb** [comment]
It does indeed happen because 'void' gets executed. It's in a higher order context, and gets called with erased arguments, but I think erasure may be defeated by it being used in a higher order function.
@ziman may know if I've got that right...

Since this can only ever happen for void (nothing else is ever allowed to have no pattern clauses) I can put a special case into the compiler, but it probably needs a better solution in the long run.

**Comment by nicolabotta** [comment]
Thanks Edwin!
