### ISSUE TITLE
IDE mode :browse doesn't know about plicity

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#3102]
`:browse` in IDE mode is showing all type signatures without plicity information now.

See https://github.com/idris-hackers/idris-mode/issues/422 for details and a screenshot.

**Comment by zjhmale** [comment]
has this been fixed?

![image](https://cloud.githubusercontent.com/assets/6234553/17386913/75de4ab2-5a21-11e6-889e-562c5591b3e5.png)

the type signature via browse is the same with one via apropos, i use Idris 0.12

**Comment by david-christiansen** [comment]
Yes, this is looking good now. I wonder what happened. Thanks for posting the update!
