### ISSUE TITLE
Bad error message (wrong argument incorrectly flagged)

### ISSUE THREAD

**Issue by colin-adams** [idris-lang/Idris-dev#3105]
With the following code fragment:

            str <- string_from_c answer
            send_page conn str code -- (prim__zextB32_Int code)

I get the error message:

    When checking argument text to function Main.send_page:
             Type mismatch between
                     IO String (Type of str)
             and
                     String (Expected type)

This is wrong. str has type String. The real error is that code has the wrong type. The commented out code shows shows what I should have coded.

This is typical of a pervasive tendency of idris to report the wrong, or else highly mis-leading error.

**Comment by jfdm** [comment]
@colin-adams is it possible for you to expand your answer with the following:

+ type signatures for `string_from_c` and `send_page`, and the function in which the code fragment is called.
+ version of Idris you are using.

With this information we should be able to get a better understanding of the context in which Idris is complaining.

**Comment by colin-adams** [comment]
string_from_c : Ptr -> IO String
send_page : (conn : Ptr) -> (text : String) -> (code : Int) -> IO Int

called from:

answer_to_connection : Ptr -> Ptr -> String -> String -> String -> String -> Ptr -> Ptr -> Int

but the body to answer_to_connection is unsafePerformIO $ do ...
This is because it is a callback from C and wrappers to such are not allowed to have an IO Int type.

Version of idris is HEAD. Do you need the exact hash?

**Comment by edwinb** [comment]
A minimal failing example would be really useful here, to make it easier to reconstruct.

Reporting the "right" error is hard (probably next to impossible to guess most of the time) especially when attempting to infer the types of the local variables.

**Comment by colin-adams** [comment]
Finding the minimal example is also very hard - it is so difficult to predict the behaviour of Idris error messages.

But I managed it (if I remove the conditional if answer /= null then do, I get the correct error reported):

module Main

import CFFI

string_from_c : Ptr -> IO String
string_from_c str = foreign FFI_C "make_string_2" (Ptr -> IO String) str

connection_information_struct : Composite
connection_information_struct = STRUCT [I8, PTR, PTR, PTR, I32]

send_page : (conn : Ptr) -> (text : String) -> (code : Int) -> IO Int
send_page conn page code = pure (the Int 1)
  
answer_to_connection : Ptr -> Ptr -> IO Int
answer_to_connection conn conn_info = do
  code_fld <- pure $ (connection_information_struct#4) conn_info
  code <- peek I32 code_fld
  answer_fld <- pure $ (connection_information_struct#1) conn_info
  answer <- peek PTR answer_fld
  if answer /= null then do
    str <- string_from_c answer
    send_page conn str code -- (prim__zextB32_Int code)
  else do
    send_page conn str (prim__zextB32_Int code)

**Comment by edwinb** [comment]
Great, thanks for the snippet, I can reproduce this now. Curiously, this seems to be about the if..then..else implementation (which is via a function with lazy arguments). Every other way of doing the test (e.g. via a case block, or via a different implementation of if_then_else without lazy arguments) leads to a more useful error being reported.

More later...

**Comment by edwinb** [comment]
I only have about half an hour to look at this now, so I'll make a quick note before I go. This turns out to be about the Lazy arguments to if, and it's quite likely that similar problems will be caused elsewhere where Lazy is involved. I've shrunk `answer_to_connection` a bit, so a minimal example is:

    if_then_else : Bool -> Lazy a -> Lazy a -> a
    if_then_else True x y = x
    if_then_else False x y = y
  
    code : translate I32
  
    answer_to_connection : Ptr -> Ptr -> IO Int
    answer_to_connection conn conn_info = do
      if_then_else True (do -- answer /= null then do
           str <- string_from_c null
           send_page conn str code) -- (prim__zextB32_Int code)
         (pure 42)

Removing the `Lazy` from `if_then_else` leads to the right error being reported.

My implementation of the automatic coercions for lazy types was, most likely, also lazy, in that I didn't really think much about its impact on error messages. I'll rethink that - it is probably trying to be too clever, which has regularly turned out to  be a bad idea in the past.

In general, I don't see Idris reporting the wrong error, which makes me suspect the other places you see the problem also involve laziness. But wrong error messages are definitely worth knowing about, and I think some attention to error messages is overdue.
