### ISSUE TITLE
Using JS libraries for JS code generation

### ISSUE THREAD

**Issue by KesterTong** [idris-lang/Idris-dev#3109]
The JS ecosystem has a very mature set of libraries (acorn, escodegen, babel, etc.) for parsing and generating JS.  The [ESTree](https://github.com/estree/estree) standard defines an AST for JS, which is used by many of these libraries, and babel uses a similar AST.

Emitting an AST in ESTree format and using a library such as escodegen (or babel, using babel's AST), might make code generation simpler, more correct, and easier for people familiar with the JS transpiler ecosystem to understand.  On the other hand, it would add node, and whichever node library was used for code generation, to the toolchain when targeting JS, and toolchain complexity is always a big problem.

One feature that might make this worthwhile is support for source maps, which would be much easier to support if using escodegen or babel for code generation

So I'm just putting this out there as an idea, not necessarily saying it would be an improvement, but it's something worth thinking about.

**Comment by jfdm** [comment]
I see this not as a replacement for the current JS backends but as something complimentary.

One could even suggest that we add a new output type AST such that each backend has the opportunity to provide such information.

In the first instance, I believe that providing a backend flag to the JS backends to spit out an AST in ESTree standard would be a good solution for *this* issue. As for source maps, I am not familiar enough with them to comment. But would adding a backend flag to enable source maps in the output be a solution.

**Comment by melted** [comment]
Close because of inaction and no bug.
