### ISSUE TITLE
Interfaces again: how to implement Show for sequences of dependent pairs?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3113]
Consider a sequence of dependent pairs where both pair components depend on a `t : Nat` value: 

```
> Foo : (t : Nat) -> Type
> Bar : (t : Nat) -> (ft : Foo t) -> Type
> data FooBarSeq : (t : Nat) -> (n : Nat) -> Type where
>   Nil   :  {t : Nat} -> 
>            (ft : Foo t) -> FooBarSeq t Z
>   (::)  :  {t : Nat} -> {n : Nat} -> 
>            DPair (Foo t) (Bar t) -> FooBarSeq (S t) n -> FooBarSeq t (S n)
```

I want to say that, if `Foo t` and `Bar t ft` implement `Show` for every `t : Nat`, `ft : Foo t`, then `FooBarSeq t n` implements `Show` for every `t : Nat`, `n : Nat`. The obvious

```
> implementation {t : Nat} -> {ft : Foo t} -> {n : Nat} -> (Show (Foo t), Show (Bar t ft)) => Show (FooBarSeq t n) where
>   show = ?lala
```

appears to be syntactically incorrect. Embedding the implementation in a `using` clause

```
> using (t : Nat, ft : Foo t, n : Nat)
>   implementation (Show (Foo t), Show (Bar t ft)) => Show (FooBarSeq t n) where
>     show = ?lala
```

is rejected by the type checker. The error message

```
- + Errors (1)
 `-- ./Prelude/Show.idr line 66 col 11:
     When checking right hand side of Prelude.Show.Main.FooBarSeq t n implementation of Prelude.Show.Show, method showPrec with expected type
             FooBarSeq t n -> String

     Can't find implementation for Show (FooBarSeq t n)
```

refers to library code, not to the code written by the user. What am I missing here? What is the canonical way of implementing `Show`for sequences of parameterized dependent pairs? Thanks, Nicola

**Comment by edwinb** [comment]
Foo and Bar here are function names, so you're not going to be able to find instances since unification will never unify Foo x and Foo y to get x = y. Maybe we can spot this in advance by looking at the instance head and seeing that the constraints don't make sense.

If they're data types it's fine:

    data Foo : (t : Nat) -> Type where
    data Bar : (t : Nat) -> (ft : Foo t) -> Type where

**Comment by nicolabotta** [comment]
Edwin, I am afraid that I do not grasp the reason why `Foo` would have to be injective in the example above! 

No matter, the point that I'm trying to make is that, in "interfaceless Idris", one can easily derive showability of `FooBarSeq t n` for arbitrary `t`and `n` from showability of `Foo t` and `Bar t ft` for arbitrary `t` and `ft`:
```
> %default total
> %access public export
> %auto_implicits off
 
> data Showable : Type -> Type where
>   MkShowable : {t : Type} -> (t -> String) -> Showable t
> show : {t : Type} -> {st : Showable t} -> (t -> String)
> show {st = MkShowable show'} = show'

> Foo : (t : Nat) -> Type
> Bar : (t : Nat) -> (ft : Foo t) -> Type
> data FooBarSeq : (t : Nat) -> (n : Nat) -> Type where
>   Nil   :  {t : Nat} -> 
>            (ft : Foo t) -> FooBarSeq t Z
>   (::)  :  {t : Nat} -> {n : Nat} -> 
>            DPair (Foo t) (Bar t) -> FooBarSeq (S t) n -> FooBarSeq t (S n)

> postulate showableFoo : (t : Nat) -> Showable (Foo t)
> postulate showableBar : (t : Nat) -> (ft : Foo t) -> Showable (Bar t ft)

> showableFooBar : (t : Nat) -> Showable (DPair (Foo t) (Bar t))
> showableFooBar t = MkShowable show' where
>   show' : DPair (Foo t) (Bar t) -> String
>   show' (foo ** bar) = "(" ++ show {st = showableFoo t} foo ++ ", " ++ show {st = showableBar t foo} bar ++ ")"

> showableFooBarSeq : (t : Nat) -> (n : Nat) -> Showable (FooBarSeq t n)
> showableFooBarSeq t n = MkShowable show' where
>   show' : FooBarSeq t n -> String
>   show' fbs = "[" ++ show'' t n "" fbs ++ "]" where
>     show'' : (t' : Nat) -> (n' : Nat) -> String -> FooBarSeq t' n' -> String
>     show'' t'  Z     acc (Nil f)     = acc ++ "(" ++ show {st = showableFoo t'} f ++ " ** " ++ " " ++ ")" 
>     -- show'' t' (S m') acc (fb :: fbs) = show'' (S t') m' (acc ++ showFooBar t' fb ++ ", ") fbs
>     show'' t' (S m') acc (fb :: fbs) = show'' (S t') m' (acc ++ show {st = showableFooBar t'} fb ++ ", ") fbs
```
My understanding is that interfaces should provide enough syntactic sugar for expressing the above derivation more cleanly. 

If interfaces cannot be used to improve the above implementation, then perhaps there is a problem with the design of interfaces. Or perhaps interfaces are meant to be used for different purposes! In this case, we should try to come up with some guidelines for when to use interfaces and when to use plain Idris data types. 

Another approach could be to avoid interfaces altogether and just rely on modules (for overloading names) and on data declarations for expressing relationships between types. But, as one can see from the example, expressing relationships between types via data declarations means a lot of wrapping / unwrapping which is a bit ugly.

**Comment by edwinb** [comment]
On 17/04/2016 16:54, nicolabotta wrote:
> Edwin, I am afraid that I do not grasp the reason why `Foo` would have to be injective in the example above! 

Because those are the rules for interfaces. You can only have an
implementation on a concrete data type (rather than, say, somethign
which might be a function like Foo or Bar here).

If unification sees `Foo x = Foo y`, it can't make any assumptions about
the relationship between x and y. But in code which uses interfaces,
especially when it's highly polymorphic it is often very useful indeed
for the unifier to be able to assume that implementations are on type
constructors.

If you think there is a problem with the design of interfaces, perhaps
it's because you're trying to push them too far, and I suggest you
propose an alternative which would support what you want to do.

**Comment by nicolabotta** [comment]
> If you think there is a problem with the design of interfaces, perhaps it's because you're trying to push them too far, and I suggest you propose an alternative which would support what you want to do.

Edwin, I do not know how interfaces are actually implemented and whether the current implementation could possibly be improved and how! 

But it is clear that where, as in the example above, we cannot use interfaces, we can still use plain data declarations. The problem is that using different approaches for solving similar problems is not satisfactory. Thus, if we do not manage to come up with guidelines on when to use interfaces and when to use plain data declarations, we should perhaps always use data declarations. We know that data declarations are expressive enough, it's just that enumerating all features of an interface as arguments of a data constructor (and implementing all their projections) is sometimes a bit awkward.

A similar dilemma arises when we try to extend already existing interfaces. Here, as exemplified by the `Num` case #3078, we can easily end up with diamond shaped patterns which, in turn, lead to problems that seem only avoidable by either using unnatural linear patterns or, as in the above example, by going back to data declarations.

**Comment by nicolabotta** [comment]
I am probably missing something obvious here but it is not clear to me why 
```
> %default total
> %access public export
> %auto_implicits off
 
> Foo : Type
> Bar : (foo : Foo) -> Type
> data FooBarSeq : (n : Nat) -> Type where
>   Nil   :  (f : Foo) -> FooBarSeq Z
>   (::)  :  {n : Nat} -> DPair Foo Bar -> FooBarSeq n -> FooBarSeq (S n)

> showFooBarSeq : (Show Foo, {f : Foo} -> Show (Bar f)) => (n : Nat) -> FooBarSeq n -> String
> showFooBarSeq n fbs = "[" ++ show' n "" fbs ++ "]" where
>   show' : (n' : Nat) -> String -> FooBarSeq n' -> String
>   show' = ?lala
```
should yield
```
- + Errors (1)
 `-- 3113_show_foobarseq_plain.lidr line 12 col 14:
     When checking right hand side of showFooBarSeq with expected type
             String
     
     Can't disambiguate since no name has a suitable type: 
             Prelude.List.++, Prelude.Strings.++
```
Any ideas?

**Comment by ahmadsalim** [comment]
@nicolabotta 

If there is a disambiguation error, it usually means that some of the arguments do not have the right type, so it can't figure out which one of the listed alternatives it should use. I have recently figured out how to use `with` properly (with help of @edwinb) and the following code shows the true underlying error of why it doesn't pick `Strings.++`:

```idris
 %default total
 %access public export
 %auto_implicits off

 Foo : Type
 Bar : (foo : Foo) -> Type
 data FooBarSeq : (n : Nat) -> Type where
   Nil   :  (f : Foo) -> FooBarSeq Z
   (::)  :  {n : Nat} -> DPair Foo Bar -> FooBarSeq n -> FooBarSeq (S n)

 showFooBarSeq : (Show Foo, {f : Foo} -> Show (Bar f)) => (n : Nat) -> FooBarSeq n -> String
 showFooBarSeq n fbs = with Strings ("[" ++ show' n "" fbs ++ "]") where -- Notice the with for disambiguation
   show' : (n' : Nat) -> String -> FooBarSeq n' -> String
   show' = ?lala
```.

The error I get then is:

```idris
test.idr:12:51:
When checking right hand side of showFooBarSeq with expected type
        String

Type mismatch between
        Show (Bar f) (Type of constraint1)
and
        Show (Bar f1) (Expected type)

Specifically:
        Type mismatch between
                Show (Bar f)
        and
                Show (Bar f1)
```

**Comment by nicolabotta** [comment]
Thanks Ahmad! Could you pleae elaborate a little bit on your example? I know how to use `with` to pattern match on intermediate results, but I do not understand the idiom you apply here. What is `Strings` in
```
showFooBarSeq n fbs = with Strings ("[" ++ show' n "" fbs ++ "]") where -- Notice the with for disambiguation
```
? I can only find a `Strings` module (in "prelude/Prelude/Strings.idr"), nothing that can be "applied" to values!

Apart from understanding your computation, the point that I am trying to make is that the
message
```
- + Errors (1)
 `-- 3113_show_foobarseq_plain.lidr line 13 col 14:
     When checking right hand side of showFooBarSeq with expected type
             String
     
     Can't disambiguate since no name has a suitable type: 
             Prelude.List.++, Prelude.Strings.++
```
for
```
> showFooBarSeq : (Show Foo, {f : Foo} -> Show (Bar f)) => (n : Nat) -> FooBarSeq n -> String
> showFooBarSeq n fbs = "[" ++ show' n "" fbs ++ "]" where
>   show' : (n' : Nat) -> String -> FooBarSeq n' -> String
>   show' = ?lala
```
is, to my understanding,  just incorrect. I might be overseeing something, of course. But I expect here `"["`, `show' n "" fbs` and `"]"` to be all of type `String`and `++` in
```
> showFooBarSeq n fbs = "[" ++ show' n "" fbs ++ "]" where
```
to (have to) be `Prelude.Strings.++` without any ambiguity! Also notice that
```
> showFooBarSeq : (Show Foo, {f : Foo} -> Show (Bar f)) => (n : Nat) -> FooBarSeq n -> String
> showFooBarSeq n fbs = 
>   let show' : ((n' : Nat) -> String -> FooBarSeq n' -> String)
>             = \ n' => \ s' => \ fbs' => ?lala
>   in "[" ++ show' n "" fbs ++ "]"
```
type checks fine. This suggests that, again modulo a blind spot of mines, `where` and `let` clauses behave inconsistently in 0.11-git:7e7d0eb, please see also #3124.

**Comment by ahmadsalim** [comment]
In Idris, `with` is overloaded for two things.

One is view patterns as you mentioned, and the other is for name disambiguation.

The name disambiguation with has syntax `with [[namespace]] [[expression]]` and basically states that whenever Idris has to disambiguate a name in `[[expression]]` it should only look at the given ``[[namespace]`` (essentially hiding all other options).

So `with Strings ("[" ++ show' n "" fbs ++ "]")` basically states that when it disambiguates the `++` it should use the one in the `Strings` namespace.

**Comment by nicolabotta** [comment]
I was not aware of this second way of applying `with`: very interesting, thanks! 

This suggests that, here, the type checker does not believe that the type of `show' n "" fbs` is `String`. But it seems to me that this is precisely what the definition of `show'` states!

**Comment by ahmadsalim** [comment]
@nicolabotta As far as I can see the type checker gives an implementation dictionary of a wrong type to the `show'` function. I am not sure for what reason, or whether it should work in general.

**Comment by nicolabotta** [comment]
@ahmadsalim: I do not see ovbious reasons why the type checker should reject the code. Notice that
```
> show' : (n : Nat) -> String -> FooBarSeq n -> String
> showFooBarSeq : (Show Foo, {f : Foo} -> Show (Bar f)) => (n : Nat) -> FooBarSeq n -> String
> showFooBarSeq n fbs = "[" ++ show' n "" fbs ++ "]"
``` 
type checks fine but
```
> show' : (Show Foo, {f : Foo} -> Show (Bar f)) => (n : Nat) -> String -> FooBarSeq n -> String
> showFooBarSeq : (Show Foo, {f : Foo} -> Show (Bar f)) => (n : Nat) -> FooBarSeq n -> String
> showFooBarSeq n fbs = "[" ++ show' n "" fbs ++ "]"
```
fails to type check with the same error message as for the local implementation! Notice also that
```
> using (n : Nat)
>   implementation (Show Foo, {f : Foo} -> Show (Bar f)) => Show (FooBarSeq n) where
>     show fbs = "[" ++ show' "" fbs ++ "]" where
>       show' : String -> FooBarSeq n -> String
>       show' = ?lala
```
fails to type check, this time with an error from within the prelude:
```
- + Errors (1)
 `-- ./Prelude/Show.idr line 66 col 11:
     When checking right hand side of Prelude.Show.Main.FooBarSeq n implementation of Prelude.Show.Show, method showPrec with expected type
             FooBarSeq n -> String
     
     Can't find implementation for Show (FooBarSeq n)
```
This is another example of how difficult it can be, for Idris users, to apply Idris interfaces. My impression is that Idris interfaces have been from the beginning quite fragile and that the error messages that one gets when things go wrong can be misleading. But, of course, I cannot judge whether this is a design problem or just implementational bugs.

**Comment by ahmadsalim** [comment]
@nicolabotta Sorry, I meant that the implementation resolution algorithm seems to have resolved an instance of a wrong type, which it gave to the function and then the type checker complained.
I am not sure whether this is a bug of implementation resolution, or just something that is not intended to work but giving a weird error message.

**Comment by edwinb** [comment]
You can't have implementations on Foo and Bar because they are not constructors.

It should, of course, be reported that that's the problem. Sometimes it might get resolved, but that will only be by chance due to something else unifying things.

**Comment by nicolabotta** [comment]
> You can't have implementations on Foo and Bar because they are not constructors.

I guess we are talking about different problems here. The program
```
> %default total
> %access public export
> %auto_implicits off
 
> Foo : Type
> Bar : (foo : Foo) -> Type
> data FooBarSeq : (n : Nat) -> Type where
>   Nil   :  (f : Foo) -> FooBarSeq Z
>   (::)  :  {n : Nat} -> DPair Foo Bar -> FooBarSeq n -> FooBarSeq (S n)

> Foo = Nat
> f : Foo
> f = Z
> sf : String
> sf = show f

> Bar _ = Nat
> b : Bar Z
> b = Z
> sb : String
> sb = show b
```
type checks fine. To me, this means that I can very well define `Foo` and `Bar f` which are implementations of `Show` for every `f : Foo`. I understand that
```
> showFooBarSeq : (Show Foo, {f : Foo} -> Show (Bar f)) => (n : Nat) -> FooBarSeq n -> String
> showFooBarSeq n fbs =
>   let show' : ((n' : Nat) -> String -> FooBarSeq n' -> String)
>             = \ n' => \ s' => \ fbs' => ?lala
>   in "[" ++ show' n "" fbs ++ "]"
```
, which also type checks fine, explains (modulo `lala`) how to compute a string from a value of type `FooBarSeq n` under the assumptions that `Foo` is showable and that `Bar f` is showable for every `f : Foo`. With these explanations in place, I would expect that
```
> using (n : Nat)
>   implementation (Show Foo, {f : Foo} -> Show (Bar f)) => Show (FooBarSeq n) where
>     show = showFooBarSeq n
```
provides an implementation of `Show` for `FooBarSeq n` again, provided implementations of `Show` for `Foo` and `Bar f`.  The last bit does not type check, however. One gets
```
     When checking right hand side of Prelude.Show.Main.FooBarSeq n implementation of Prelude.Show.Show, method show with expected type
             FooBarSeq n -> String
     
     When checking argument n to function Main.showFooBarSeq:
             No such variable n
```
which I also do not understand.

**Comment by ahmadsalim** [comment]
I will close the issue, since it has been inactive for a while and there seem to be no objection/continuation of the thread (and it's marked as expected behaviour). Please reopen the issue if there are important things left to be taken care of.
