### ISSUE TITLE
Add "covering" as a possible value for %default

### ISSUE THREAD

**Issue by colin-adams** [idris-lang/Idris-dev#3143]
Presently only "total" and "partial" are permitted.

**Comment by colin-adams** [comment]
I need some help with this.

I've managed to get it to recognize %default covering, but it doesn't actually have any effect.

I've just been following my nose through the source code. I can't see any further right now, so clues are welcome. Here is what I have changed so far:

diff --git a/src/Idris/AbsSyntaxTree.hs b/src/Idris/AbsSyntaxTree.hs
index ae729b7..b25f662 100644
--- a/src/Idris/AbsSyntaxTree.hs
+++ b/src/Idris/AbsSyntaxTree.hs
@@ -527,6 +527,7 @@ data Opt = Filename String
          | TypeInType
          | DefaultTotal
          | DefaultPartial
+         | DefaultCovering
          | WarnPartial
          | WarnReach
          | EvalTypes
diff --git a/src/Idris/CmdOptions.hs b/src/Idris/CmdOptions.hs
index e55c842..ebe16be 100644
--- a/src/Idris/CmdOptions.hs
+++ b/src/Idris/CmdOptions.hs
@@ -102,14 +102,15 @@ parseFlags = many $
   <|> (Output <$> strOption (short 'o' <> long "output" <> metavar "FILE" <> help "Specify output file"))
 
   --   <|> flag' TypeCase (long "typecase")
-  <|> flag' Interface      (long "interface"   <> help "Generate interface files from ExportLists")
-  <|> flag' TypeInType     (long "typeintype"  <> help "Turn off Universe checking")
-  <|> flag' DefaultTotal   (long "total"       <> help "Require functions to be total by default")
-  <|> flag' DefaultPartial (long "partial")
-  <|> flag' WarnPartial    (long "warnpartial" <> help "Warn about undeclared partial functions")
-  <|> flag' WarnReach      (long "warnreach"   <> help "Warn about reachable but inaccessible arguments")
-  <|> flag' NoCoverage     (long "nocoverage")
-  <|> flag' ErrContext     (long "errorcontext")
+  <|> flag' Interface       (long "interface"   <> help "Generate interface files from ExportLists")
+  <|> flag' TypeInType      (long "typeintype"  <> help "Turn off Universe checking")
+  <|> flag' DefaultTotal    (long "total"       <> help "Require functions to be total by default")
+  <|> flag' DefaultPartial  (long "partial")
+  <|> flag' DefaultCovering (long "covering")
+  <|> flag' WarnPartial     (long "warnpartial" <> help "Warn about undeclared partial functions")
+  <|> flag' WarnReach       (long "warnreach"   <> help "Warn about reachable but inaccessible arguments")
+  <|> flag' NoCoverage      (long "nocoverage")
+  <|> flag' ErrContext      (long "errorcontext")
 
   -- Show things
   <|> flag' ShowLoggingCats (long "listlogcats" <> help "Display logging categories")
diff --git a/src/Idris/DeepSeq.hs b/src/Idris/DeepSeq.hs
index 11e3399..a53316b 100644
--- a/src/Idris/DeepSeq.hs
+++ b/src/Idris/DeepSeq.hs
@@ -124,6 +124,7 @@ instance NFData Opt where
     rnf (TypeInType) = ()
     rnf (DefaultTotal) = ()
     rnf (DefaultPartial) = ()
+    rnf (DefaultCovering) = ()
     rnf (WarnPartial) = ()
     rnf (WarnReach) = ()
     rnf (EvalTypes) = ()
diff --git a/src/Idris/Parser.hs b/src/Idris/Parser.hs
index 7e4f7b6..e62d056 100644
--- a/src/Idris/Parser.hs
+++ b/src/Idris/Parser.hs
@@ -1396,7 +1396,7 @@ pLangExt = (reserved "TypeProviders" >> return TypeProviders)
 {- | Parses a totality
 
 @
-Totality ::= 'partial' | 'total'
+Totality ::= 'partial' | 'total' | 'covering'
 @
 
 -}
@@ -1404,6 +1404,7 @@ totality :: IdrisParser Bool
 totality
         = do reservedHL "total";   return True
       <|> do reservedHL "partial"; return False
+      <|> do reservedHL "covering"; return False
 
 {- | Parses a type provider
 
diff --git a/src/Pkg/Package.hs b/src/Pkg/Package.hs
index 4da9f05..7093d29 100644
--- a/src/Pkg/Package.hs
+++ b/src/Pkg/Package.hs
@@ -405,16 +405,17 @@ mergeOptions copts popts =
     filtOpt _              = True
 
     chkOpt :: Opt -> Either String Opt
-    chkOpt o@(OLogging _)     = Right o
-    chkOpt o@(OLogCats _)     = Right o
-    chkOpt o@(DefaultTotal)   = Right o
-    chkOpt o@(DefaultPartial) = Right o
-    chkOpt o@(WarnPartial)    = Right o
-    chkOpt o@(WarnReach)      = Right o
-    chkOpt o@(IBCSubDir _)    = Right o
-    chkOpt o@(ImportDir _ )   = Right o
-    chkOpt o@(UseCodegen _)   = Right o
-    chkOpt o                  = Left (unwords ["\t", show o, "\n"])
+    chkOpt o@(OLogging _)      = Right o
+    chkOpt o@(OLogCats _)      = Right o
+    chkOpt o@(DefaultTotal)    = Right o
+    chkOpt o@(DefaultPartial)  = Right o
+    chkOpt o@(DefaultCovering) = Right o
+    chkOpt o@(WarnPartial)     = Right o
+    chkOpt o@(WarnReach)       = Right o
+    chkOpt o@(IBCSubDir _)     = Right o
+    chkOpt o@(ImportDir _ )    = Right o
+    chkOpt o@(UseCodegen _)    = Right o
+    chkOpt o                   = Left (unwords ["\t", show o, "\n"])
 
     genErrMsg :: [String] -> String
     genErrMsg es = unlines

**Comment by ahmadsalim** [comment]
@colin-adams Could you try to start a PR with your code, and then it may be easier to take a look at the diffs and make code comments?

**Comment by colin-adams** [comment]
OK.

**Comment by ahmadsalim** [comment]
This was fixed by #3151
