### ISSUE TITLE
Streamline pragmas and annotations

### ISSUE THREAD

**Issue by ahmadsalim** [idris-lang/Idris-dev#3145]
Currently we have many pragmas and annotations, but they have different syntaxes, weird naming and are applied inconsistently across the language.

For example, the following global pragmas have different naming, and are somewhat inconsistent in naming

``` idris
%access <<accessibility>>
%default <<totality>>
%hide <<name>>
%default_usage <<usage>> -- proposed in docs

```

and probably more I can't remember.

Similarly, we have annotations that apply in different places with different naming conventions e.g.:

``` idris
total -- totality annotation
public export -- two worded accessibility annotation
foo : {a : A} -> 
       %static -- Staticness annotation 
       {auto a : 2 = 2} -> -- Auto parameter
       {default Z depth: Nat} -> -- Default parameter
       Bar

%elim -- data type annotation for automatically generating eliminators
data Bla = ...
```

and compile time functions

``` idris
prim_syntactic_eq ...

%runElab ...

%provide <<type provider>> -- type providers
```

This is a request for comment which aims to discuss how to streamline pragmas and annotations, such that it easy for users to use and the language has a more consistent feel.

**Comment by ahmadsalim** [comment]
My rough suggestions:

- Change all global pragmas to be of form `%pragma <<aspect>>: <<value>>`, for example:
```idris
%pragma default totality: total
%pragma default accessibility: public export
%pragma default usage: use

%pragma hide function: quux
%pragma hide implementation: Vect Nat

%pragma provide type: Nat with: func
```
- Change all annotations to be of form `%<<annot>> or %<<annot>>(args...)`, are one word, and ensure that they always are before a particular declaration element, for example:

```idris
%total -- totality annotation
%export(public) -- one could imagine also something like %export without any arguments etc.
foo : {a : A} -> 
       %static -- Staticness annotation 
       %auto {a : 2 = 2} -> -- Auto parameter
       %default(Z) {depth: Nat} -> -- Default parameter
       Bar

%elim(elim_name) -- data type annotation for automatically generating eliminators
data Bla = ...
```

**Comment by Melvar** [comment]
I don’t like almost any of this suggestion just for not being the status quo and other classic bikeshed reasons, but most of all the idea that annotation arguments would go in a separate set of parens after the annotation, which is a style of function application inconsistent with everything else in Idris. If you need to set them off specially, require a set of parens around the whole thing, such as `%(export public)`, at which point they can just as well be merged syntactically with the ones you call “static functions”.

**Comment by ahmadsalim** [comment]
@Melvar You are welcome to suggest improvements. 

Status quo is broken as I referred to on the top, and so of course we want to streamline things a bit better. If you have ideas on how we could have syntax that look more like what we current have, then that would be great.

**Comment by david-christiansen** [comment]
I think that "broken" is a bit over the top - the things that we have do work, and the inconsistencies are relatively minor!

If it's going to be redone, I would suggest instead that three syntaxes be adopted: one for saying "from this point on, do things this way", which is like `%default` or `%access`; one for saying "in this top-level declaration, do things this way", and one for saying "in this subexpression, do things this way". Then, represent all annotations as datatypes.

Next, write up an interface `Pragma`:
```
interface Pragma a where
  runPragma : a -> Elab ()
```
that interprets these, and add `Elab` actions that implement all present pragmas.  We might then have, for instance:
```
data TotalityChecker = DefaultTotal | DefaultCovering | DefaultPartial

implementation Pragma TotalityChecker where
  runPragma DefaultTotal = setDefaultTotality Total
  runPragma DefaultCovering = setDefaultTotality Covering
  runPragma DefaultPartial = setDefaultTotality Partial
```
as a replacement for %default.

This has the following advantages:
 1. Keep Elab reflection honest by making sure it can do anything at all
 2. The collection of pragmas becomes user-extensible, so a library can implement its own pragma (think `%attribute BoveCapretta` before a definition causing an Elab script to apply the Bove-Capretta transformation to it)
 3. It becomes possible to use Idris's documentation features to document pragmas

It has the following disadvantages:
 1. Potentially ugly
 2. Someone's gotta do the work
 3. Makes alternate Preludes a bit harder to do

**Comment by ahmadsalim** [comment]
@david-christiansen Hmm, I didn't think that broken had those connotations.

**Comment by david-christiansen** [comment]
To me, "broken" means "doesn't work" and "useless", and in an IT context "fundamentally flawed". It can be used with irony in a context like "this is slightly broken" to mean "this is mostly OK", but when it's alone, it's a pretty strong word.

**Comment by Melvar** [comment]
@david-christiansen Invoking Elab for every access modifier on a declaration seems a bit much, but I kinda like the idea in general. This approach would effectively be committing to moving more things out of the compiler and into Elab-accessible commands, in a somewhat radical way.

Concerning advantage 1, certainly Elab is currently missing a way to control the visibility of things it declares, and it can’t simulate `%dynamic` or any of the backend flags. (This of course adds to the importance of disadvantage 2.)

Concerning advantage 2, isn’t that a transformation of a declaration? The Elab script would have to receive the declaration before it is added to the globals to transform it.

Concerning disadvantage 1, syntax rules could take some of the edge off, even if restricted in a way previously discussed elsewhere and especially if they were namespaced. (More disadvantage 2.)

Concerning disadvantage 3, aren’t alternate Preludes already quite difficult without copying a good deal of code concerning builtins (whether in `Builtins` or in `Language.Reflection{,.Elab}`? Perhaps splitting out a `builtins` package would be useful if we wished to make that easier. (More disadvantage 2.)

I’ll also add one more disadvantage: Making it fast in the common case may be quite difficult indeed.

**Comment by david-christiansen** [comment]
> This approach would effectively be committing to moving more things out of the compiler and into Elab-accessible commands, in a somewhat radical way.

Idris's elaborator should eat itself.

> The Elab script would have to receive the declaration before it is added to the globals to transform it.

Yes, it would. Annotations on declarations should probably be a pair of actions that are run before and after elaboration, which could do things like rewinding to a previous state and rewriting the saved definition in the craziest case. Specific design remains to be done!

> aren’t alternate Preludes already quite difficult

Yes, and I don't think they're that important. Others disagree, of course, and there's no reason to step on their feet if we don't have to.

> Making it fast in the common case may be quite difficult indeed

I don't think so. A single-effect Elab script (which is what these will be) isn't particularly slow. Elab gets slow when it starts doing heavy computation or lots of reification of terms, but that shouldn't be necessary to call something like:

```
warnIfNotCovering : TTName -> Elab ()
```

**Comment by ahmadsalim** [comment]
@david-christiansen I think your idea is generally very interesting.

Maybe one could distinguish between active (elaborated) annotations and passive annotations (which can be read by the elaborator or other external tools?).

@Melvar One way to solve the issue with `%dynamic`, `%link` etc., is to have some primitive functions which are used by the Elab script, like all other primitives I think.

I think if we have a generalized attribute system, we should be able to have some syntactic categories where it applies, e.g. constructors, fields, functions, arguments, implicits, etc.
Does anyone have a general idea of syntax that is alternative to mine? And how should attributes be declaretd?

**Comment by david-christiansen** [comment]
@ahmadsalim I vastly prefer the current syntaxes :-) It might just be familiarity, but I don't think so. @Melvar has a good point about the parens for application.

What do you mean by active and passive? This suggestion was to use Idris's ordinary overloading and interface mechanisms to interpret all annotations.

As far as declaring attributes, it would be done precisely by implementing an interface for the datatype. We don't need them to be external to the computation language now that we have a reflected elaborator.

**Comment by ahmadsalim** [comment]
@david-christiansen I meant that some attributes are just attached to datatypes/function declarations without being handled further.

Also, the idea is that some attributes should only be applied to particular syntax elements, and so we may need to restrict them (e.g. public export only makes sense on top-level declarations whereas %static only makes sense on function arguments).

As for keeping current syntaxes, it would be nice if the naming was proper and they were uniform in shape. How would you suggest we handle the latter?

**Comment by ahmadsalim** [comment]
To be honest, I didn't expect that we would use my proposed syntaxes but I didn't want to be "empty handed" and wanted to suggest a way to handle things uniformly. I would love to see something that looks more like we currently have but is more flexible (e.g. allowing arguments).

**Comment by david-christiansen** [comment]
According to the proposal in my comment earlier, where all pragmas and annotations and such are ordinary Idris expressions, the application syntax falls right out. The "only makes sense on X" bit could perhaps be done by adding another parameter to the interface, which would be a value of:
```
data AnnotationScope = FunctionArg | Module | Declaration | ...
```

**Comment by david-christiansen** [comment]
In any case, if we're not planning to redo the semantics of these various directives:

I think that starting every directive with `%pragma` is both noisy and misleading.  Noisy, because it's very long, and misleading, because these things really aren't pragmas, which traditionally are for adding extra metadata to programs rather than for changing their meaning.

Also, I don't see any reason to add a bajillion percents to things like `auto`. What's wrong with the current syntax? It's fine to have a language in which the syntax looks inviting - if we don't want that, we might as well go full s-expression and get the benefits of _real_ consistency!

Finally, if there is going to be a common application syntax for all these directives, please make it the same as Idris's expression syntax. That opens the door for future improvements RE reflection.

**Comment by ahmadsalim** [comment]
@david-christiansen I just meant that we should align auto, default, static an the rest.

It is not to make it more or less inviting :).

**Comment by ahmadsalim** [comment]
It looks pretty weird that you have to write `%static {auto bla : 2 = 2} -> ...`

**Comment by david-christiansen** [comment]
FWIW we could just drop the % on static. I think the only reason for that is to not extend the set of keywords.

**Comment by ahmadsalim** [comment]
@david-christiansen To be honest I would prefer that all of this was handled by the `elaboration-time` annotation system, so that we can add a new attribute to implicit arguments and still keeping the nice uniform syntax.

**Comment by ahmadsalim** [comment]
What I got from discussion from @david-christiansen and @Melvar was that we should have one syntax for elaboration-time functions/annotations which looks like `%<<name>>` or `%(<<expression>>)` instead of the weird syntaxes I proposed above.
The idea of this is that not only does it make the current system uniform, but it will also make it possible to add a more extensible system afterwards if we so desire (which we probably do, but someone has to make it).

**Comment by ahmadsalim** [comment]
We should probably also have some kind of consistent style.
I think that since `%default_usage` is not implemented yet we should go with camel case throughout all annotations, since that will break least amount of code (i.e. it will become `%defaultUsage`).

We should also rename `%default` to something that makes sense w.r.t. to totality. Does people have any idea what it should be named to? ( @david-christiansen , @Melvar )

@edwinb Would you like to give some thoughts on this whole process?

**Comment by david-christiansen** [comment]
I'm still not entirely convinced that we should change these things, FWIW. Have real users actually had significant confusion? I haven't noticed it.

**Comment by ahmadsalim** [comment]
@david-christiansen I find it a perfectly reasonable answer that this issue is closed without any changes at all. I have met a few people who was confused about the naming of the pragmas, especially `%default` since it only pertains to totality and does not change things like access, usage, etc.

The context for this discussion is that we discussed the above on IRC with @jfdm and @edwinb, where @edwinb stated that the addition of the `%default` keyword was an early hack, and that it may be a good idea to have a general discussion on pragma/attribute (whatever you call them) design in the language, which led to this RFC.

I agreed with the motion that these pragmas should be discussed and I think that even though we end up changing nothing, it is still good that the choices move from "simple hack" to "explicit design decision".
However, I tried to come up with a more general solution, but of course we could end up with having a simpler renaming of conventions as well.

I hope that @jfdm and @edwinb and others will join our conversation when they have time.

**Comment by ahmadsalim** [comment]
I mean this is my first RFC about the design process, so if people thing that the process should have been different (e.g. inviting people from the mailing list, IRC, etc.), that the format should be different (more QA style) or that I generally am bad at holding RFCs, then feedback is welcome (although I would prefer feedback pertaining to the final ones by email :) )

**Comment by ahmadsalim** [comment]
Btw, I found that there is a `%specialise` which takes an integer list as arguments (between brackets) and a `%export` which takes a string as an argument and confusingly is not the same as `export`...

**Comment by Melvar** [comment]
Minor idea: Rather than renaming `%default` to something clearer, extend it to be used with any arbitrary declaration modifier.
