### ISSUE TITLE
“Bind” alternatives for let

### ISSUE THREAD

**Issue by Melvar** [idris-lang/Idris-dev#3158]
The syntax

```
do pat1 <- act | pat2 => other
   rest
```

is, if I recall correctly, equivalent to

```
do case !act of
     pat1 => rest
     pat2 => other
```

I now find myself using `pat1 <- pure $ val | pat2 => other` to save a nesting depth if I need to match on a pure value in a `do` block. It would be nice if

```
do let pat1 = val | pat2 => other
   rest
```

would analogously act like

```
do case val of
     pat1 => rest
     pat2 => other
```

to streamline this case.

This could be generalized to `let … in …`, but I think that might be less useful and harder to read.

**Comment by Melvar** [comment]
\@edwinb has expressed approval for both parts of this syntax on IRC (quoted with permission):
```
< edwinb> no, I got caught out by that recently too because I thought I'd implemented it
< edwinb> I can't remember why I didn't. probably just didn't get around to it.
```
```
< Melvar> edwinb: I presume that you don’t want this syntax to work with a normal «let … in …»?
< edwinb> I don't see an obvious reason why not, but it is a different part of the grammar iirc so might be a bit annoying
< edwinb> If it's fiddly I'd leave it, but no obvious reason not to do it if it's easy
```

**Comment by Melvar** [comment]
Apparently the latter part was already implemented in https://github.com/idris-lang/Idris-dev/commit/ecb9da6d767d4e8ef778f6e2da9b0e1a2e46117d.

**Comment by ahmadsalim** [comment]
@Melvar You are welcome to make a documentation PR 😄 or an issue.
