### ISSUE TITLE
Support building idris-0.11.1 on OpenBSD

### ISSUE THREAD

**Issue by neduard** [idris-lang/Idris-dev#3170]
Hello, when attempting to build on OpenBSD, `cabal install` fails with:
```
Downloading idris-0.11.1...
[1 of 1] Compiling Main             ( /tmp/idris-0.11.1-9302/idris-0.11.1/Setup.hs, /tmp/idris-0.11.1-9302/idris-0.11.1/dist/setup/Main.o )
Linking /tmp/idris-0.11.1-9302/idris-0.11.1/dist/setup/setup ...
....
Configuring idris-0.11.1...
*** Parse error in /tmp/idris-0.11.1-9302/idris-0.11.1/rts: Missing dependency operator (../config.mk:1)
*** Parse error: Need an operator in 'endif' (../config.mk:8)
*** Parse error: Missing dependency operator (../config.mk:21)
...
```

Turns out this is caused by using `make` instead of `gmake` in Setup.hs. Adding a check for `defined(openbsd_HOST_OS)` fixes the problem and idris-0.11.1 compiles fine.

PR submitted at #3171

**Comment by LeifW** [comment]
There's also the e.g. `if os(freebsd)` stuff in idris.cabal that defines some CPP options. https://github.com/idris-lang/Idris-dev/blob/master/idris.cabal#L1110

If we have to enumerate all the BSD's separately, maybe we should add NetBSD while we're at it, too?

**Comment by neduard** [comment]
@LeifW Yes, that is a good idea, I have replied to a similar comment on the PR (#3171), basically I'm wondering if the cpp-options can be removed and just use `*_HOST_OS` in `IRTS/System.hs` and `Util/DynamicLinker.hs`.

**Comment by neduard** [comment]
Fixed
