### ISSUE TITLE
make -j2 test_c shouldn't give up when a test fails

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris-dev#3176]
It would be nice if `make -j2 test_c` didn't immediately fail when a test fails, so that all the test failures could be seen at once. `./runtest all` does the right thing, but more slowly.

**Comment by melted** [comment]
You can pass -i to make to continue on error.
Den 18 maj 2016 00:43 skrev "Edwin Brady" <notifications@github.com>:

**Comment by edwinb** [comment]
@melted Hmm, that may be enough to make this issue irrelevant, thanks.
