### ISSUE TITLE
Names do matter when they should not!

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3181]
The program
```
> %default total
> %auto_implicits off

> postulate decLT : (m : Nat) -> (n : Nat) -> Dec (LT m n)
> postulate last : Nat

> LTB : Nat -> Type
> LTB b = DPair Nat (\ n  => LT n b)

> Foo : (t : Nat) -> Type
> Foo t = LTB (S last)

> Bar : {t : Nat} -> (n : Nat) -> Foo t -> Type
> Bar  Z    _ = Unit
> Bar (S n) x with (decLT (fst x) last)
>   | (Yes _) = Unit
>   | (No  _) = Void

> lemma : {t : Nat} -> {n : Nat} -> {x : Foo t} -> 
>         (fst x) `LT` last -> Bar (S n) x = Unit
> lemma {n} {x} prf with (decLT (fst x) last)
>   | (Yes _) = Refl
>   | (No contra) = void (contra prf)
```
type checks fine in 0.11.2-git:2cfcbcf. But replacing
```
> lemma : {t : Nat} -> {n : Nat} -> {x : Foo t} -> 
>         (fst x) `LT` last -> Bar (S n) x = Unit
> lemma {n} {x} prf with (decLT (fst x) last)
>   | (Yes _) = Refl
>   | (No contra) = void (contra prf)
```
with
```
> lemma : {t : Nat} -> {m : Nat} -> {x : Foo t} -> 
>         (fst x) `LT` last -> Bar (S m) x = Unit
> lemma {m} {x} prf with (decLT (fst x) last)
>   | (Yes _) = Refl
>   | (No contra) = void (contra prf)
```
yields the error
```
- + Errors (1)
 `-- namesMatter.lidr line 22 col 12:
     When checking right hand side of with block in Main.lemma with expected type
             with block in Main.Bar m t x (decLT (fst x) last) = ()
     
     Type mismatch between
             () = () (Type of Refl)
     and
             with block in Main.Bar m t x (decLT (fst x) last) = () (Expected type)
     
     Specifically:
             Type mismatch between
                     ()
             and
                     with block in Main.Bar m t x (decLT (fst x) last)
```
In fact, replacing `n` with any other name yields an error. Also replacing
```
> lemma : {t : Nat} -> {n : Nat} -> {x : Foo t} -> 
>         (fst x) `LT` last -> Bar (S n) x = Unit
> lemma {n} {x} prf with (decLT (fst x) last)
>   | (Yes _) = Refl
>   | (No contra) = void (contra prf)
```
with just
```
> lemma : {t : Nat} -> {n : Nat} -> {x : Foo t} -> 
>         (fst x) `LT` last -> Bar (S n) x = Unit
> lemma {x} prf with (decLT (fst x) last)
>   | (Yes _) = Refl
>   | (No contra) = void (contra prf)
```
leads to the same error message! I might be missing something obvious here, but it seems to me that the problem that names do matter when they should not keeps on popping up in slightly different incarnations over and over again. Maybe a signal of some deeper issue?

**Comment by ahmadsalim** [comment]
I am unsure if the initial code you have should type check, but I do agree that it is counter-intuitive that naming the variable `n` leads to a different result than naming it otherwise.

**Comment by nicolabotta** [comment]
> I am unsure if the initial code you have should type check, but I do agree that it is counter-intuitive that naming the variable n leads to a different result than naming it otherwise. 

It seems to me that, independently of whether `lemma` should type check or not, the fact that it type checks if its second argument is named `n` but it does not type check if the same argument is named `m`is an Idris error.

**Comment by edwinb** [comment]
This turns out to be because 'with' clause elaboration turns out to be unaware of the need for alpha conversion, and when it builds the type for the function in the with block it is therefore ignoring the fact that a variable might have been renamed.

So, fortunately, it's nothing particularly deep. I'll try to fix it soon, but in case I don't (or in case someone else is inspired to have a go) I'll leave this note...

The problem is in TT.substTerm, which substitutes a term for another in a TT expression. It checks whether it has found an appropriate subterm using ==, in the line `st t | t == old = new`, but should instead use an equality test that is aware of alpha conversion.

**Comment by nicolabotta** [comment]
Thanks Edwin!
