### ISSUE TITLE
Differences between repl and compiled code?

### ISSUE THREAD

**Issue by HuwCampbell** [idris-lang/Idris-dev#3182]
I recently put together a quick [port](https://github.com/HuwCampbell/idris-lens/) of Control.Lens to Idris, which seems to be working out ok so far.

Some expressions which work fine when specified in source don't work in the repl however.

From my [examples](https://github.com/HuwCampbell/idris-lens/blob/master/Control/Lens/Examples.idr)
`(2,3) & over both (+1)` gives an error message
`(input):No such variable b` when entered in the repl despite it compiling fine.

**Comment by jfdm** [comment]
Just a quick response, for now whilst I have time.

Essentially, REPL evaluation works differently than during compilation. See the following link for more details.

http://docs.idris-lang.org/en/latest/faq/faq.html#evaluation-at-the-repl-doesn-t-behave-as-i-expect-what-s-going-on

Hopefully, this is why your code is working the way it is. Hopefully, someone with more time can have a closer look to ensure that nothing else is going on.

**Comment by ahmadsalim** [comment]
Have you tried entering `the (Int, Int) $ (2,3) & over both (+1)`

**Comment by HuwCampbell** [comment]
`the (Int, Int) $ (2,3) & over both (+1)` 
works, but
`the (Int, Int) (2,3) & over both (+1)`
(without the dollar) does not.

So seems that something's up with the type inference.

**Comment by ahmadsalim** [comment]
Generally, it is undecidable to have type inference for dependently-typed languages and so you can't get around needing annotations some place or another. However, the error message is not useful it seems.

**Comment by HuwCampbell** [comment]
Ok, I'll close then. Hopefully the error message will improve.
