### ISSUE TITLE
Type checker accepts invalid patterns (non-existent constructors)

### ISSUE THREAD

**Issue by KesterTong** [idris-lang/Idris-dev#3189]
The type checker will accept a pattern even when it refers to a non-existent constructor for a data type, e.g.
```
data MyData = A | B

myFunction : MyData -> String
myFunction C = ""
```
is accepted by the type checker even though C is not a constructor for MyData

**Comment by ahmadsalim** [comment]
This is because `C` is treated as a pattern variable, and so it is perfectly fine. Please see #3153 for discussion on this.

I will close this as a duplicate of #3153.

**Comment by KesterTong** [comment]
Thanks for the clarification.
