### ISSUE TITLE
RFC - Javascript code generation needs a variant for wrapping event callbacks

### ISSUE THREAD

**Issue by colin-adams** [idris-lang/Idris-dev#3192]
I am trying to add an Idris function as a DOM event callback. Whilst I can successfully add the callback, the function does not get called. Inspection of the generated code shows that it falls into the following pattern:

``` javascript
var i$ffiWrap = function(fid,oldbase,myoldbase) {
    return function() {
   ...
  return i$ret;
 }
}
```

I was able to get it to work by editing the generated code so that the last 3 lines read:

``` javascript
 return i$ret;
 }
}()
```

So I think that this is analagous to the case of storing C callbacks in C structs, for which the %wrapper syntax is provided. And maybe we need an equivalent for JS.
It may be the case that it is already possible to generate such code, and I am just not aware of how to do it. My existing Idris code looks like this:

``` idris
add_event_listener : JSRef -> String -> (() -> JS_IO ()) -> JS_IO ()
add_event_listener target event action = do
  if target == null then
    jscall "function () {console.log(\"No target\");}()" (JS_IO ())
  else
    jscall "function () {%0.addEventListener(%1,%2);}()" (JSRef -> String -> (JsFn (() -> JS_IO ()
  )) -> JS_IO ()) target event (MkJsFn action)

```

**Comment by colin-adams** [comment]
So by analogy with the FFI_C case, perhaps a suitable syntax would be to use MkJSFnPtr in place of MkJsFn?

**Comment by colin-adams** [comment]
This proposal won't help.
Although adding the () gets the function executed at the correct time, the action I am passing through is actually:

```idris
(reset socket_di)
```

where socket_di was obtained from calling 
```javascript
new WebSocket (...)
```
This object is functionally fine in other parts of the code, but when I try to call .send on it (within reset), Javascript raises "Uncaught TypeError: socket_di.send is not a function" Inspection of socket_di shows it has lost its prototype. So i$ffiWrap is a dead end for me. (socket_di - the identical object) is functional in other parts of my code.

**Comment by colin-adams** [comment]
Debugging confirms that socket_di has a WebSocket prototype at the time of the call to add_event_listener. So something is somehow stripping the prototype. Debugging shows that this has already occurred at entrance to i$ffiWrap.

**Comment by rbarreiro** [comment]
I think this works well on master after the switch to liftdecls

**Comment by ahmadsalim** [comment]
@rbarreiro Would it be possible to add a test for that?

**Comment by rbarreiro** [comment]
@ahmadsalim I created pull request #3859, this is a test that was failing before. I think colin was experiencing the same problem.

**Comment by ahmadsalim** [comment]
@rbarreiro Great, thanks!
