### ISSUE TITLE
GHC 8 build fails with "error: expected: declaration, end of input"

### ISSUE THREAD

**Issue by ilovezfs** [idris-lang/Idris-dev#3193]
Putting aside the dependency restrictions mentioned in https://github.com/idris-lang/Idris-dev/pull/3128 the build currently fails with

```
Preprocessing executable 'idris-codegen-node' for idris-0.11.2...
[1 of 2] Compiling Paths_idris      ( dist/dist-sandbox-c22f35f3/build/autogen/Paths_idris.hs, dist/dist-sandbox-c22f35f3/build/idris-codegen-node/idris-codegen-node-tmp/Paths_idris.o )
[2 of 2] Compiling Main             ( codegen/idris-codegen-node/Main.hs, dist/dist-sandbox-c22f35f3/build/idris-codegen-node/idris-codegen-node-tmp/Main.o )
Linking dist/dist-sandbox-c22f35f3/build/idris-codegen-node/idris-codegen-node ...
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused
clang: warning: argument unused during compilation: '-L/usr/local/opt/libffi/lib'
clang: warning: argument unused during compilation: '-L/usr/local/lib'
clang: warning: argument unused during compilation: '-L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries'
Building libraries...
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C prelude build
../../dist/dist-sandbox-c22f35f3/build/idris/idris --build prelude.ipkg
./Builtins.idr:6:1: error: expected: declaration,
    end of input
||| The canonical single-element type, also known as the trivially 
^                                                                  
Type checking ./Builtins.idr
make[1]: *** [build] Error 1
make: *** [build] Error 2
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
```

**Comment by LeifW** [comment]
Same issue as #3127, though perhaps this one is a bit more direct in describing the issue. Technically, the Idris compiler itself builds just fine, it's just that it then can't parse its own included Idris source files (for the included libs).

**Comment by ilovezfs** [comment]
@LeifW were you ever able to get a successful build with the earlier GHC 8 RCs?

**Comment by ilovezfs** [comment]
Also, to be clear, this has prevented the formula from being "boneyarded," as would otherwise have occurred: https://github.com/Homebrew/homebrew-core/issues/1486#issuecomment-222528930

**Comment by ahmadsalim** [comment]
@ilovezfs Thanks for fixing this.
I think we still have to take a look at why it fails with cabal.

**Comment by ilovezfs** [comment]
@ahmadsalim You're welcome. The issue is GHC 8, not cabal. By using stack, it forces the use of GHC 7. A cabal based build with GHC 7 is fine.

**Comment by KaneTW** [comment]
This seems to be caused by a GHC bug (https://ghc.haskell.org/trac/ghc/ticket/12201).

Idris (non-minimized) example: http://lpaste.net/6317261125587042304

**Comment by gpyh** [comment]
The `lpaste` link is dead. You can use gists for the same effect.

**Comment by KaneTW** [comment]
Thanks.
https://gist.github.com/KaneTW/e618339a4b11e06971d60c3218fbc3e6
