### ISSUE TITLE
Feature request: introduce %unfreeze directive

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3200]
As shown in #3198, we need to be able to both %freeze and %unfreeze features in order to avoid unacceptable type checking times in modular programs. The canonical use would be:
```
> module IsSucProperties

> import IsSuc
> import ANat

> %default total
> %access public export
> %auto_implicits off

> -- %freeze n

> snnIsSuc : IsSuc (S (n * n))
> snnIsSuc = YesItIs

> -- %unfreeze n

> nEQ100 : n = 100
> nEQ100 = Refl
```
with
```
> module IsSuc

> %default total
> %access public export
> %auto_implicits on

> data IsSuc : Nat -> Type where
>      YesItIs : IsSuc (S x)
```
and
```
> module Parameters

> %default total
> %access public export
> %auto_implicits off

> n : Nat
> n = 100
```
At the moment the alternatives are to 1) comment out `%freeze n` in `IsSucProperties` and be patient (it takes about one minute to type check on my machine) 2) split `IsSucProperties` into two files: one that does not need access to the implementation of `Parameters.n` and one that does.

I think that both alternatives are unacceptable. By contrast, the freeze-unfreeze pattern would be a simple means of achieving acceptable type checking times without breaking modularity.

**Comment by edwinb** [comment]
%unfreeze should be pretty easy to add. I'll aim to do it while travelling today...

**Comment by nicolabotta** [comment]
Great, thanks Edwin!

**Comment by nicolabotta** [comment]
That works perfectly Edwin, thanks! 

I am perhaps mistaken but I was under the impression that `%freeze` directives were preserved through import chains. I other words, I thought that
```
> module Parameters

> %default total
> %access public export
> %auto_implicits off

> n : Nat
> n = 100
> %freeze n
```
would effectively make the implementation of `n` not visible in all modules importing `Parameters`. 

Now it seems that the scope of `%freeze` and `%thaw` directives is limited to the local module. This would be fine as well, I just want to make sure I understand the rules.
