### ISSUE TITLE
Make Idris HLint compliant

### ISSUE THREAD

**Issue by ahmadsalim** [idris-lang/Idris-dev#3205]
I just ran `hlint` on the Idris source code, and here is the report:

https://rawgit.com/ahmadsalim/d5705dc9b9bbadc6b1a232b3608ccd0d/raw/860f067111458433c04e17fd4f80067ef83741c4/idris-hlint.html

I think it is relatively a low hanging fruit to clean up some of the things mentioned in the report and cleaner and more efficient/understandable code.

**Comment by david-christiansen** [comment]
It would be better to first define a collection of HLint rules that create a style we like.

For instance, it suggests
```
 src/IRTS/CodegenC.hs:84:30: Suggestion: Use list comprehension
Found

if isWindows then ["-Wl,--stack,16777216"] else []

Why not

["-Wl,--stack,16777216" | isWindows]
```
which I think is much harder to read.

**Comment by david-christiansen** [comment]
Likewise, I think that:
```
src/IRTS/Compiler.hs:204:35: Suggestion: Avoid lambda
Found

\ x -> sMN x "op"

Why not

(`sMN` "op")
```
is a particularly unfortunate choice.

**Comment by ahmadsalim** [comment]
@david-christiansen Yeah, I wasn't sure what to do with the results, but I guess that would be a part of the task as well :).

**Comment by david-christiansen** [comment]
I believe that HLint allows one to configure the particular ruleset that it applies. I think that finding a good ruleset for Idris is the interesting part here. For instance, the default HLint ruleset really pushes point-free style, which we don't have a lot of.

**Comment by ozgurakgun** [comment]
Chipping in: I don't know about including new rules (I only know that it is possible), but to exclude one you can use, e.g., `--ignore 'Avoid lambda'`. You can pass multiple ignore options as well, so adding a `--ignore 'Use list comprehension'` would exclude that one (though I happen to quite like that so I keep it on for my personal projects).

**Comment by quchen** [comment]
@david-christiansen Yes, you can put a HLint.hs file in your directory tree. Here's an example: https://github.com/quchen/stg/blob/master/HLint.hs
