### ISSUE TITLE
Can't call Idris functions from Javascript

### ISSUE THREAD

**Issue by colin-adams** [idris-lang/Idris-dev#3213]
At least in the browser (I know nothing about node.js), the names of Idris functions are not visible to Javascript code (or to html events), and adding FFI_Exports for them does nothing (as far as I can tell).

This seems to make the Javascript codegen target fairly useless for most applications.

**Comment by colin-adams** [comment]
I wouldn't have described it as minor - it has caused me to stop developing completly for the moment (until I can find the time to implement the fix - probably not before August).

I wouldn't have thought it was the build system either - I think it just needs some code generation - generating a wrapper with an umangled name to call the function with the mangled name, and pass-through the arguments.

**Comment by melted** [comment]
One hacky solution could be to implement the idris name mangler in
Javascript and use eval to call them. It's very simple so it would be
little work.

Though implementing export is the right thing to do, of course. Then it
could make proper JS modules and all.
Den 20 juni 2016 06:54 skrev "Colin Adams" <notifications@github.com>:

**Comment by ahmadsalim** [comment]
@colin-adams I am just careful about tagging things as major unless they form a major inconsistency or affect many users. Tagging this as `minor` does not mean that it is not important for you or us, which of course it is! Perhaps I should consider adding a `medium` serverity as well.

**Comment by ahmadsalim** [comment]
I am unfortunately not familiar with the code generation part (including the JS backend) of Idris myself, so I am not of much help here unfortunately.
