### ISSUE TITLE
Can't pattern match on Refl for (as ++ [b]) ++ cs = as ++ b :: cs

### ISSUE THREAD

**Issue by markandrus** [idris-lang/Idris-dev#3222]
Hi! I'm new to Idris, so this may just be my own misunderstanding, but I think I have found a bug.

I can write the function, `foo`, which type checks, but when I try to pattern match on the result in `bar` I get a type error.

```idr
foo : (as : List x) -> (b : x) -> (cs : List x) -> (as ++ [b]) ++ cs = as ++ b :: cs
foo as b cs = rewrite appendAssociative as [b] cs in Refl

-- > foo [] () []
-- Refl : [()] = [()]

bar : (as : List x) -> (b : x) -> (cs : List x) -> (as ++ [b]) ++ cs = as ++ b :: cs
bar as b cs = case foo as b cs of Refl => Refl

-- Type mismatch between
--         as ++ b :: cs = as ++ b :: cs (Type of Refl)
-- and
--         (as ++ [b]) ++ cs = as ++ b :: cs (Expected type)
-- 
-- Specifically:
--         Type mismatch between
--                 as ++ b :: cs
--         and
--                 (as ++ [b]) ++ cs
```

**Comment by andreasabel** [comment]
This does not look like a bug (Agda would say the same here).
`as ++ b :: cs` is equal to `as ++ ([b] ++ cs)` by __definition__ of `++`.  But you want `(as ++ [b]) ++ cs` which is only equal to the former by associativity, which can be __proven__ but does not hold by definition.  In type theory, provable (propositional) equality and built-in definitional equality are distinguished.

**Comment by markandrus** [comment]
Thank you for taking a look at my question, @andreasabel. So IIUC, I can construct the proof in `foo` using `rewrite` and `appendAssociative`, but I cannot pattern match on it because it does not hold by definition. If I want to use the result of `foo`, I have to again use a `rewrite` rule, e.g.

```idr
bar : (as : List x) -> (b : x) -> (cs : List x) -> (as ++ [b]) ++ cs = as ++ b :: cs
bar as b cs = case foo as b cs of prf => rewrite prf in Refl
```

**Comment by enolan** [comment]
The explanation here is that evaluation happens in the type when you pattern match on `Refl`. `(as ++ [b]) ++ cs = as ++ b :: cs` turns into `as ++ b :: cs = as ++ b :: cs` which, as @markandrus said, aren't definitionally equal. Not pattern matching works fine. Two examples:

```idris
bar : (as : List x) -> (b : x) -> (cs : List x) -> (as ++ [b]) ++ cs = as ++ b :: cs
bar as b cs with (foo as b cs)
  bar as b cs | with_pat = with_pat

baz : (as : List x) -> (b : x) -> (cs : List x) -> (as ++ [b]) ++ cs = as ++ b :: cs
baz as b cs = case foo as b cs of qwf => qwf
```
Not a bug, just surprising.

**Comment by markandrus** [comment]
Thank you both, @enolan and @andreasabel!
