### ISSUE TITLE
basic013 and primitive001 fail

### ISSUE THREAD

**Issue by yacinehmito** [idris-lang/Idris-dev#3227]
The `basic013` test fails because of a `hGetContents: invalid argument (invalid byte sequence)` error.

In particular, the `basic013` involves elaborate Unicode characters (mainly lambda and arrow). However, they display fine in my terminal. Furthermore, idris has no problem compiling the file.

The `primitive001` causes the same problem. This one as many Chinese ideograms.

~~Because it makes the test suite crash, I believe the error originates from the comparison procedure. A regression in some dependency may have caused this, but I was unable to investigate further.~~

**Comment by Melvar** [comment]
For reference, the test runner was somewhat recently rewritten as a Haskell program, and the given error is the usual one when the encoding is set wrong on the `Handle` in question. The Makefile simply calls `ghc --make` to compile the test runner; this may cause a different GHC and/or different base libraries to be used than for Idris itself.

Idris itself on the other hand I believe requires all source to be UTF-8, which it therefore sets explicitly when reading the source, and Idris programs compiled via C use only UTF-8 for input and output as well.

**Comment by melted** [comment]
Seems to be something with the encoding, though both those tests work fine when I set my shell to ISO-8859-1. I see that the test runner doesn't do hSetEncoding h utf8 like Idris does, so it's possible this could occur I guess.

**Comment by melted** [comment]
#3228 shouldn't be needed to fix this, this should be one-liner :-)

**Comment by melted** [comment]
I don't think this is relevant anymore.
