### ISSUE TITLE
Improving the testing infrastructure

### ISSUE THREAD

**Issue by gpyh** [idris-lang/Idris-dev#3228]
This issue will track progress on a proposal of improvement of the testing infrastructure. It is motivated by #2577 and other similar issues. Discussion on the proposed changes is more than welcome.
## Progress

The proposed changes in [End goal] describe an ideal state.
It is not clear that the amount of work required to get there is worth the benefits.

However, we can move toward that goal incrementally, as to reap some of the benefits as early as possible. This is the progress that has made and what's left to be done:
- [x] Port the current infrastructure to Tasty (more specifically Tasty.Golden) with feature parity
- [x] Use cabal to run the test suite
- [x] Provide incremental tests with Tasty.Rerun (done, but somewhat unsatisfying)
- [ ] Put test logic in Haskell code
- [ ] Put related tests in the same subfolders
- [ ] Put test metadata in Haskell code, specifically:
  - [x] Test family
  - [ ] Related files
  - [ ] Description
  - [x] Compatible backends
  - [ ] Expected failures
- [ ] Use the idris library instead of the executables

Some more specific, pressing issues:
- [x] Don't bail out if a test crashes (~~see 3265~~ I was mistaken, it is completely unrelated)
- [x] Move the "blacklist" of tests with the node backend out of `runtest.hs` (will put a link when merged)
- [ ] Don't use `__GLASGOW_HASKELL__` in `Setup.hs` (will put a link when merged)
- [x] Use both the C and Node backend in the same run
## Initial issues

We face the following problems with the original infrastructure.
1. Because of the file hierarchy, every test snippet must be registered in the `.cabal` file. It is in my view a tedious bookkeeping that provides no advantages as this list is not used by any test logic. (cabal's wildcards are very restrictive ; see [the documentation](https://www.haskell.org/cabal/users-guide/developing-packages.html#package-properties))
2. A new bash instance is called for every test case, which is
   1. Somewhat slow
   2. Somewhat error prone (you do need to write a small bash script ; some test code is actually [generated by the script](https://github.com/idris-lang/Idris-dev/blob/95c92972be549bf87dc1d108983ee4164ae4f2fe/test/primitives002/run))
   3. Undermining compatibility with Windows (and even OS X considering the supplied bash version)
   4. Relying on setting an `$IDRIS` environment variable
3. Test cases don't have meaningful names and don't document what they are testing against
4. Some tests are actually comprised of multiple tests ; it would be desirable to have a more granular view of which tests succeed and which do not, and why
5. Test outputs are written on disk ; I am not convinced of the necessity of doing IO, and even in that case, we do not wish to pollute the directories with the outputs of the tests
6. We wish to express tests that are expected to fail (see #2928)
7. If a test fails for external reasons, it makes the whole test suite crash
8. Similar to **2**: A new idris process is fired up for each test, which is slow (see #2577)
9. Some logic and features are provided by/with make, which is undesirable (see #2915). Specifically:
   1. a way to run the tests one by one
   2. parallel tests with `make -j`
   3. cleaning up the artifacts that result from running the test suite
   4. a way to run all tests with the node backend, omitting those that are incompatible with it
10. Features are provided by an in-house Haskell script. Although it works great, it is preferable to rely on tried and true solutions. Features are specifically:
    1. running the tests and comparing the actual output with the expected output
    2. report of successes and failures
    3. output time spent testing
    4. output the difference between actual outputs and expected outputs when a test fails
    5. replaces the expected outputs (the golden files) with the actual outputs on demand
11. Absence of incremental testing ; we may wish to only rerun tests that failed between consecutive runs.
12. Testing with the C backend and with the Node backend is done separately. Therefore:
    - most tests are needlessly duplicated
    - Travis CI runs them in two different containers ; this is wasteful because it makes us exceed the maximum number of simultaneous, parallel containers (which is 5)
## End goal

I submit to you the following proposal:

Deriving from the current nomenclature of tests (into what I will call test families), we would have a directory for each of the test families. In each of these, we would allow files of extensions `.idr`, `.input` and `.expected`. This solves **1** as we will only need to add to the `.cabal` file the corresponding wildcards for each of the test family.

In each of those directories, we put a `Tests.hs` file. This top level Haskell file will handle the logic and the metadata for the tests of the family. Specifically, for each test:
- what kind of test is should be (type-checking?, comparing outputs?, compiling against a particular backend?, expected to fail? etc.) -- this solves **6** and matches **9.iv**
- what are the files involved (source file, golden file if applicable)
- a description in one or two sentences of what it is testing against, with the GitHub issue if applicable -- this solves **3**

This data is what each `Tests.hs` module should expose. Naturally, a top-level Haskell module that will be imported by each of them would provide a lean API as to make those `Tests.hs` as small and as type safe as possible. Because this is just Haskell code, you can very well generate tests in them, which would solve **2.ii**.
We can organize tests into groups in an arbitrarily deep hierarchy, solving **4**.

The `Tests.hs` modules are then imported by a top-level Haskell module in the test directory that will massage the data into IO actions in order to be used with the Tasty framework. It provides the following benefits:
- Colored and well-indented report -- it betters **10.ii**
- Time spent for each test and in total -- it betters **10.iii**
- Ability to run the tests in parallel but output them in a deterministic order -- it betters **9.ii**
- Restrict the run to tests matching a regular expression -- it betters **9.i**
- Tasty captures the exit codes -- it solves **7** for free.
- Comparison between desired and expected output with [Tasty.Golden](https://hackage.haskell.org/package/tasty-golden) -- it matches **10.i**
- Ability to replace the golden files with the output with Tasty.Golden -- it matches **10.v**

It doesn't match **10.iv** out of the box but provides a way to customize the display in case of failures, which we'll do.

Furthermore, [Tasty.Rerun](https://hackage.haskell.org/package/tasty-rerun) provides a way to partially solve **11**. It is not void of issues, as it only stores the result of the previous run instead of keeping every run and a cache and cleaning it on request. Full-blown incremental testing will require some work on our part.

Using [Tasty.ExpectedFailure](https://hackage.haskell.org/package/tasty-expected-failure) will solve **6**.

How we turn the data into IO actions is on our control.

We can replace bash scripts with regular Haskell code, which will solve **2**. To fix **2.iv** specifically, we have two solutions:
In the short term, using `cabal test` or `stack test` will temporarily add the project `bin` directory in the `PATH`, so we can get rid of the `IDRIS` environment variable. A passthrough can easily be added in order to add flags to the calls.
In the long term, we would rather link to the idris Haskell library. We would still call idris itself via a `runIdris` function, but such a function will live in its own Haskell thread instead of requiring an OS process. This would solve **8** aswell. Going further, we could try to share the loaded Idris modules between all of those `runIdris` invocations.

Knowing which code generator works with each tests (and which tests don't depend on a code generator), we could automatically prevent the incompatibilities. Better still, we could simultaneously run a test with every compatible code generator (if it makes sense to do so), which would solve **12**.

We will be able to save the outputs anywhere ; by putting them all in the same directory and adding a simple hook to clean it up, we can solve **5** and **9.iii**. We can also put the expected output directly in the `Tests.hs` module. Although it cancels the benefits of **10.v**, it reduces the amount of IO calls, helping **5**.

**Comment by ahmadsalim** [comment]
I think the proposed architecture is great, and we would love to see the suggested improvements.

**Comment by gpyh** [comment]
https://github.com/agda/agda might be a good source of inspiration. 
Their tests run very fast (although [the whole build](https://travis-ci.org/agda/agda/jobs/146969910) is slow) and they have quite a lot of them. I'll study it to see which ideas are worth stealing.

Furthermore, they don't do `cabal sdist` so they don't have to register the tests in the cabal file, which tedious and error prone.

This brings a question: do we really want to distribute the whole test suite along with the compiler?
I'd argue that tests suites are useful in two scenarios:

- When developing, to make sure that changes didn't break anything
- When packaging and distributing, to make sure that the executable runs well on the target platform

I propose to selectively add tests that make sense for the second scenario in the cabal file.
We could split the travis jobs between those testing the distribution and those testing the source directly, or we could split the test suite in two and run them consecutively with the right files.

Thoughts?

**Comment by steshaw** [comment]
@gpyh thanks for your work on updating the test suite to `tasty`!

I like the idea about not having to duplicate test cases in `idris.cabal`. I hope it gets traction.

**Comment by gpyh** [comment]
I still intend to work on this. However, I'm quite busy with work right now. This will have to wait for the next holiday.

**Comment by david-christiansen** [comment]
I like that Travis gets the result of cabal sdist, because it makes sure
that the Hackage package has all that's needed. I really don't think it's
particularly odious to put a test file into a list, and it's quite useful
for Travis to be checking that our sdist works.

**Comment by gpyh** [comment]
AFAIK, the test files are now automatically added in Setup.hs, which voids my concerns.

I like the use of cabal sdist too. However I don't think that we need to distribute everything.
This is nitpicking though at this point.

**Comment by ahmadsalim** [comment]
I will close the issue, since I think many of the improvements were made. While the rest are good to have, I think there has been not much activity in development recently. If there is any update in development, please reopen the issue!
