### ISSUE TITLE
Mutable arrays in the IO monad.

### ISSUE THREAD

**Issue by DemiMarie** [idris-lang/Idris-dev#3238]
This is a proposal for mutable arrays in the IO monad.  The following implementation details are made with performance in mind:  it is an explicit goal to be able to approach the speed of C on tight numeric loops, thanks to unboxing and rectangular, cache-friendly layout.

Mutable arrays can be either boxed (can hold any type) or unboxed (can only hold C-like types).  Bounds are checked at compile time: it is a type error to access an array out of its bounds.

Multidimensional mutable arrays have a flat rectangular layout.

Multidimensional arrays of unboxed types can be stored in the C heap.  It is possible to pass a pointer to the array to foreign code.

Array accesses are lowered to the straightforward code for each backend.  Unboxed arrays are lowered to typed arrays on the Javascript backend.

**Comment by ahmadsalim** [comment]
This is actually fixed https://github.com/idris-lang/Idris-dev/blob/7936fbb8d843335cbe914f1e91e5a26989e7c2e5/libs/contrib/Data/IOArray.idr
