### ISSUE TITLE
Where can I find a detailed documentation of LDecl's constructors?

### ISSUE THREAD

**Issue by MaiaVictor** [idris-lang/Idris-dev#3247]
I'm trying to translate LDecl to JavaScript. In order to do so, I must understand each of its constructors. It depends on `LExp`, which has `LLazyApp`, `LNothing`, `PrimFn` and so on. There is also`Name`, which I'm not sure how works.

Most of those are self explanatory, but some details aren't obvious to me. Is there simple documentation about the IRlift language somewhere?

**Comment by melted** [comment]
Please ask questions on the [mailing list](https://groups.google.com/forum/#!forum/idris-lang) or IRC.
