### ISSUE TITLE
Segfaults that occur with integral data types but not doubles or strings

### ISSUE THREAD

**Issue by KesterTong** [idris-lang/Idris-dev#3254]
The following code results in a segfault
```idris
%default total

data Label = Optional | Required

interpLabel : Label -> Type
interpLabel Optional = Maybe Int
interpLabel Required = Int

printCase : (l : Label) -> interpLabel l -> String
printCase Optional Nothing = "Optional with Nothing"
printCase Optional (Just x) = "Optional with Just"
printCase Required x = "Required"

main : IO ()
main = do {
  putStrLn (show (printCase Optional (Nothing)))
  putStrLn (show (printCase Optional (Just 12)))
  putStrLn (show (printCase Required 12))
}
```
If `Int` is replaced by `String` or `Double` (with appropriate changes elsewhere) no segfault occurs.  If the first two cases of `printCase` are combined into `printCase Optional _ = "Optional"` then no segfault occurs either.

The output is 
```idris
"Optional with Nothing"
"Optional with Just"
Segmentation fault: 11
```

**Comment by ahmadsalim** [comment]
The problem it seems is that it tries to pattern match on the second argument before the first, according to the generated case tree:

```idris

[{e0},{e1}] case {e1} of
    Prelude.Maybe.Just({t3}, {e4}) => case {e0} of
        Main.Optional() => "Optional with Just"
        _ => "Required"
    Prelude.Maybe.Nothing({t2}) => case {e0} of
        Main.Optional() => "Optional with Nothing"
        _ => "Required"
    _ => "Required"
```

This is of course incorrect behaviour, since the type of the second argument value is dependent on the first. I wonder whether this is related to #3233 as well.

**Comment by KesterTong** [comment]
Thanks a lot @ahmadsalim.  In my case a workaround is to get the compiled code to switch on the first argument, e.g.
```
printMaybe : Maybe Int -> String
printMaybe Nothing = "Optional with Nothing"
printMaybe (Just x) = "Optional with Just"

printCase : (l : Label) -> interpLabel l -> String
printCase Optional x = printMaybe x
printCase Required x = "Required"
```
This also worked on the original code I discovered this bug in.  I don't know the root cause of the problem so I can't say if this will work in all cases.

**Comment by ahmadsalim** [comment]
@KesterTong I think your workaround (with explicitly staging matching) always would work, but requires a bit more code.

**Comment by edwinb** [comment]
This is because of an error in the way the case tree compiler optimises the ordering of arguments for building run time case trees, combined with the way Ints are represented at run-time.

In short, it wasn't spotting that the second argument could take more than one type. I've fixed this by having the case tree compiler actually look at the type... we have types, we might as well use them :).

Patch coming soon...
