### ISSUE TITLE
Fixity not checked for Type constructors and Data constructors

### ISSUE THREAD

**Issue by arianvp** [idris-lang/Idris-dev#3275]
Minimal example:
```
data Qux : a -> Type where
  Tux : String -> Qux a

data Bar : a -> Type where
  Nil : Bar a
  (:>) : Qux a -> Bar a -> Bar a

data (:>>) : a -> b -> Type where
```

Current behaviour:  The file compiles

If you use the type constructors or data constructors in another module, the parser stops with an obscure error.  

Expected behaviour:
```
 error: Missing
    fixity declaration for
    Minimal.:>

 error: Missing
    fixity declaration for
    Minimal.:>>
```

**Comment by david-christiansen** [comment]
Thanks for the good report!

**Comment by david-christiansen** [comment]
https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/Parser.hs#L621-L636 is the part of the parser that implements the check for functions. It should be pretty straightforward for a new developer to generalize that to work for data and constructor declarations as well.
