### ISSUE TITLE
help-required links

### ISSUE THREAD

**Issue by steshaw** [idris-lang/Idris-dev#3276]
The [help-required page](http://www.idris-lang.org/help-required/) (Wordpress) could do with updating:

- The "Low Hanging Fruit" link needs updating [as the label has changed name](https://github.com/idris-lang/Idris-dev/labels/C-Low%20Hanging%20Fruit).
- The "Patches Welcome" label doesn't seem to exist any longer.

**Comment by jfdm** [comment]
@steshaw Thanks, the website has been updated.
