### ISSUE TITLE
No such variable scty

### ISSUE THREAD

**Issue by steshaw** [idris-lang/Idris-dev#3280]
When defining `valToString'` in the following code, I used the editor support to create a case statement. I haven't filled in the `_` — so I'm expecting to get an error when I reload the file. However, "at line 14, character 14  No such variable scty" doesn't seem like a nice one.

``` Idris
StringOrInt : Bool -> Type
StringOrInt False = String
StringOrInt True = Int

getStringOrInt : (isInt : Bool) -> StringOrInt isInt
getStringOrInt False = "Ninety four"
getStringOrInt True = 94

valToString : (isInt : Bool) -> StringOrInt isInt -> String
valToString False x = trim x
valToString True x = cast x

valToString' : (isInt : Bool) -> (case _ of
                                       case_val => ?argType) -> String
valToString' False x = ?valToString'_rhs_1
valToString' True x = ?valToString'_rhs_2
```

The code is from Chapter 6 of TDDwI.

Searching the Idris codebase reveals:

``` ShellSession
$ ag scty
src/Idris/Elab/Term.hs
1035:             tyn <- getNameFrom (sMN 0 "sty")
```

**Comment by jfdm** [comment]
@steshaw Thanks for the issue report. 

To help us further, can you detail the version of Idris you are using, and also the full error message as given by Idris.

**Comment by steshaw** [comment]
@jfdm I'm using Version 0.12

**Comment by ahmadsalim** [comment]
I believe the `scty` comes from the `case ... of` which type it can't infer.
