### ISSUE TITLE
Reclaim CData Memory.

### ISSUE THREAD

**Issue by xekoukou** [idris-lang/Idris-dev#3287]
There are cases where one creates CData that it might need to pass at a C function, that takes over the ownership of the memory.

For this to be possible, we would need to change the finalizer so as not to free the memory.
This requires an addition to `rts.h` of a small function that changes the finalizer.

This seems to be possible already but according to [this](https://github.com/idris-lang/Idris-dev/blob/b3fdc3e2dc6256b9cb03e4cee89edb1dd97b081d/docs/reference/misc.rst) , we are only expected to access the data of the struct.

**Comment by ahmadsalim** [comment]
I am closing this as no fix since no one has volunteered to implement the feature request.
PRs are of course still welcome .
