### ISSUE TITLE
test suite failed unexpectedly

### ISSUE THREAD

**Issue by zjhmale** [idris-lang/Idris-dev#3297]
i use `stack test` to run all the test suites at the moment, but two test suites just failed unexpectedly as following pics exhibit.

![idris-fail1](https://cloud.githubusercontent.com/assets/6234553/17271871/96979408-56ba-11e6-8c8f-459c8cb64b4e.png)
![idris-fail2](https://cloud.githubusercontent.com/assets/6234553/17271872/96c4cdf6-56ba-11e6-945e-7de9e6405e79.png)

after remove two golden files and regenerate use `stack test --test-arguments="--accept"`, these two suites can finally pass.

but it is really wired, isn't it? how can i fix this.

**Comment by gpyh** [comment]
`--accept` replaces the golden files (files that tell if the tests should pass) by your files, so it's natural that the tests pass as a consequence.

I wouldn't be surprised if this is a problem with line breaks or whitespace. What OS are you running?

**Comment by melted** [comment]
I see the same in my travis run on OSX. I'll check it on my Mac.

**Comment by melted** [comment]
Huh, those two tests produce CRLF on Mac, when I ported the normalize function from the old test runner I left out that case, as I believed it wasn't needed and the line breaks would be handled by the IO system. But apparently it was there for a reason.

**Comment by melted** [comment]
Ok, those two tests do weird shell stuff to set a timeout, no idea why that would have this effect. But it's not putStrLn that is broken (it couldn't be, it's used in most tests). I'll just add back the missing case in normalize.

**Comment by zjhmale** [comment]
@gpyh i use OSX 10.10.4, @melted thx for fix this!
