### ISSUE TITLE
Enable unified diff of actual/expected with tasty

### ISSUE THREAD

**Issue by steshaw** [idris-lang/Idris-dev#3309]
With the porting of the testing infrastructure to `tasty` (#3231), its become difficult to see what the differences are when tests fail on the CI servers. This is because the comparison process no longer uses (GNU) diff. Ordinarily, you'd just plug in [`goldenVsFileDiff`](https://hackage.haskell.org/package/tasty-golden-2.3.1/docs/Test-Tasty-Golden.html#v:goldenVsFileDiff) in the appropriate place but it looks like there's a couple of issues which meant that a modified version of `goldenVsFile` was used.

The comment from `test/TestRun.hs`:

```haskell
      -- just pretend that backslashes are slashes for comparison
      -- purposes to avoid path problems, so don't write any tests
      -- that depend on that distinction in other contexts.
      -- Also compare CRLF and LF as equal, fixes a weird corner case
      -- on Mac where basic010 and reg039 produces CRLF
```

Hopefully it will be possible to address basic010 and reg039 by changing their `run` files to normalise the output as necessary. Then we can just plug in `goldenVsFileDiff` to call upon `diff -u`.

I'd like to start working on this 'cause I've run into the problem with #3281.

**Comment by melted** [comment]
Fixing that in those tests would just help with the CRLF which are produced on mac. The main function of normalize is to make the comparison blind to differences in path separators.

**Comment by melted** [comment]
We used to call diff if the test failed, why not just do that in printDiff?

**Comment by melted** [comment]
No because it compared the output and only ran diff on fail.

**Comment by melted** [comment]
See how it was done here
https://github.com/idris-lang/Idris-dev/blob/570845577856dabade20d70b1203020148acce85/test/runtest.hs

Look at the runTest function

**Comment by steshaw** [comment]
Would you agree that the normalisation procedure could be run on the actual output prior to calling `goldenVsFileDiff`?

**Comment by melted** [comment]
I think that it's better to stick a call to diff in printDiff with your favored arguments than persisting distorted files on disk.

**Comment by steshaw** [comment]
Perhaps you'd be happy if I used `goldenVsStringDiff` which will write the normalised actual output file to a temporary system directory?

**Comment by melted** [comment]
That's ok, out of sight, out of mind.

And we have CI now that will catch any windows or osx trouble.

**Comment by steshaw** [comment]
The extra '\r' at the end of the line is caused by the use of `expect` for test basic010 and reg039. It turns out that `expect` is used as a substitute for GNU `timeout` when it isn't available (i.e. on Mac). An alternative would be to install `coreutils` on Macs (then `timeout` is available as `gtimeout`). I suppose there may be other options for timeouts with `tasty`. In the patch I'm working on, I'm pushing the stripping of the '\r' into the bash scripts that use `expect`.

**Comment by steshaw** [comment]
Turns out that only 12 (of 212) `expected` files contain the '/' character. Of these 12, only 8 refer to files. All of the files look something like "./foo.idr" or "./src". I've been able to narrow down the amount of "normalisation" that's done in order to compare `output` with `expected`. I more-or-less used a regex like '\.\\[a-zA-Z]' (which is quite hard to read) — a dot, followed by a backslash, followed by a letter is replaced by: a dot, following by a forward slash and the letter.

This narrowing gives a less surprising output from `diff` when the files don't match. Previously all backslashes were translated to forward slashes meaning that you could end up seeing strings like "Hello world**/**n".

A pull request will be coming soon.
