### ISSUE TITLE
Idris module system and subfolders: inconsistent behaviour?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3321]
When organizing a collection of software components, the following idiom

`Foo.lidr`:
```
> module Foo
> data Foo
```

`Bar.lidr`:
```
> module Bar
> data Bar
```

`FooOperations.lidr`:
```
> module FooOperations
> import Foo
> public export toNat : Foo -> Nat
> toNat f = Z
```

`BarOperations.lidr`:
```
> module BarOperations
> import Bar
> import Foo
> import FooOperations
> toFoo : Bar -> Foo
> toNat : Bar -> Nat
> toNat = FooOperations.toNat . toFoo
```
is quite common and the above files type check flawlessly. But implementing the same components in separate `Foo` and `Bar` subdirectories

`Foo/Foo.lidr`:
```
> module Foo
> data Foo
```

`Foo/Operations.lidr`:
```
> module Operations
> import Foo
> public export toNat : Foo -> Nat
> toNat f = Z
```

`Bar/Bar.lidr`:
```
> module Bar
> data Bar
```

`Bar/Operations.lidr`:
```
> module Operations
> import Bar
> import Foo.Foo
> import Foo.Operations
> toFoo : Bar -> Foo
> toNat : Bar -> Nat
> toNat = Foo.Operations.toNat . toFoo
```
yields the error
```
- + Errors (1)
 `-- (no file) line 0 col -1:
     Operations.lidr:6:7:Operations.toNat already defined
```
and `Bar/Operations.lidr` fails to type check (the other files type check fine). This behavior seems to be inconsistent. 

More importantly, it makes it virtually impossible to reorganize a shallow hierarchy of Idris components into separated subdirectories containing `Operations.lidr`, `Properties.lidr`, `Predicates.lidr`, etc. files sharing certain standard (`toNat`, for example) names.

Would it be possible to correct this behavior?

**Comment by jfdm** [comment]
I notice in your examples for `Bar/Operations.lidr` and friends that you do not qualify the module name declaration with the parent directory. That is, should the name for the module in `Bar/Operations.lidr` be:

```idris
module Bar.Operations
```

and not

```idris
module Operations
```

I've organised my modules with multiple nested hierarchies and have not encountered the problems you have described. That, or I am misunderstanding your problem.

**Comment by nicolabotta** [comment]
@jfdm you are right and full module name qualification solves the issue! Thanks a lot, Nicola
