### ISSUE TITLE
stderr is suppressed in golden tests

### ISSUE THREAD

**Issue by steshaw** [idris-lang/Idris-dev#3323]
The stderr of tests (i.e. the ./run script) isn't hooked up to the terminal. This has the effect that if things go very wrong (e.g. segfault), it's not obvious what's going on from the log. Particularly a problem for CI.

I believe @melted had a go at fixing this but `tasty` was a bit unhappy. @melted, could you say more about what you tried and what went wrong?

**Comment by melted** [comment]
Those stty messages came through stderr when I wrote to it inside the testrunner. Guess one solution could be to write it to a file, say stderr_output, and add it to the string that is returned on error.
