### ISSUE TITLE
Introduce a switch to configure source file search paths, similarly to `-i` for IBC files

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3324]
I am probably missing something obvious but when I try to reorganize a shallow hierarchy of files into subdirectories, for example

`Foo/Foo.lidr`:
```
> module Foo.Foo
> data Foo
```

`Foo/Operations.lidr`:
```
> module Foo.Operations
> import Foo.Foo
> public export toNat : Foo -> Nat
> toNat f = Z
```

`Bar/Bar.lidr`:
```
> module Bar.Bar
> data Bar
```

`Bar/Operations.lidr`:
```
> module Bar.Operations
> import Bar.Bar
> import Foo.Foo
> import Foo.Operations
> toFoo : Bar -> Foo
> toNat : Bar -> Nat
> toNat = Foo.Operations.toNat . toFoo
```
dependencies are not reloaded automatically. Thus, for instance
```
nicola@cirrus:~/gitlab/IdrisLibs/tmp/Bar$ idris -i .. --check Operations.lidr
```
fails with something like
```
Loading ./Operations.ibc failed: Module needs reloading:
	SRC : "../Foo/Operations.lidr"
	Modified at: 2016-08-04 12:08:32.335160527 UTC
	IBC : "../Foo/Operations.ibc"
	Modified at: 2016-08-04 12:04:27.099847781 UTC
nicola@cirrus:~/gitlab/IdrisLibs/tmp/Bar$
```
if the time stamp of `../Foo/Operations.ibc` happens to lag behind that of `../Foo/Operations.lidr`. If `../Foo/Operations.ibc` does not exists, one gets
```
nicola@cirrus:~/gitlab/IdrisLibs/tmp/Bar$ idris -i .. --check Operations.lidr
Loading ./Operations.ibc failed: Must be an ibc
```
For files with hundreds of dependencies, this behaviour is less than useful and one would like dependencies to be reloaded automatically as it happens when files are organized in a shallow hierarchy of modules.

Are there specific options to force Idris to reload files whose *.ibc files are inexistent or out-of sync?

**Comment by jfdm** [comment]
@nicolabotta You might be interested in the Idris `.ipkg` format for describing packages: 

http://idris.readthedocs.io/en/latest/tutorial/packages.html

The package can help with maintenance of large scale idris projects.

**Comment by nicolabotta** [comment]
@jfdm Thanks for the pointer Jan! I came across that reference and I have tried to work with .ipkg a number of times. I might be mistaken of course, but my impression is that packages are solving a different problem from the one described in this issue: I could of course add a

`bar.ipkg`:
```
package bar

modules = Bar
        , Operations
```
 file to the `Bar/` directory but
```
nicola@cirrus:~/gitlab/IdrisLibs/tmp/Bar$ idris -i .. --build bar.ipkg
```
would still fail with
```
Type checking ./Bar.lidr
No ibc for Foo/Foo
```
if `Foo/Foo.ibc` and `Foo/Operations.ibc` have not been built before type checking `Bar/Operations.lidr`.

Thus, the problem is really that of tracking down dependencies and building *.ibc files in a suitable order! I could not find any reference to this problem in the documentation of packages but I might have overseen it, of course. 

**Tracking down dependencies and building *.ibc files in a proper order works fine if all the dependencies of a file are in the same directory of that file but, as shown above, it does not appear to work if the dependencies are not local.** 

This would imply that software components (packages?) have to be self-contained. This is a condition that should be quite difficult to meet in most realistic systems, I am afraid!

**Comment by nicolabotta** [comment]
The problem is simply:
```
$ find . -name *.ibc -delete
$ idris -i .. --check Bar/Operations.lidr 
$ find . -name *.ibc -delete
$ cd Bar/
$ idris -i .. --check Operations.lidr 
No ibc for Foo/Foo
```
Thus, type checking works fine if Idris is called from the parent directory of `Foo` and `Bar` but fails if Idris is called in `Bar`! This seems quite inconsistent to me.

A  far-reaching consequence of this behaviour is that type checking files with non-local depenencies does not work in the idris emacs mode!

This essentially means that one is forced to put all the dependencies of a file in the same directory of that file. 

This, in turns, means that maintaining a large Idris project with a lot of interdependencies is hardly possible.

**Comment by jfdm** [comment]
@nicolabotta Is the directory layout with idris files in your first comment of this thread indicative of the problem you are having? 

> This, in turns, means that maintaining a large Idris project with a lot of interdependencies is hardly possible.

I do not believe that statement to be true; I have written reasonably large Idris projects with multiple project dependencies that do work.

Of note: the flag `-i <path>` adds a location to search for existing `ibc`. It will not recompile Idris files for you. Your above REPL sequence, as far as I can tell is expected behaviour.

**Comment by jfdm** [comment]
Of note, the originasl examples have incorrect accessibility modifiers, remember the default accessibility for a project is private. The contents of `Bar.Bar` and `Foo.Foo` are not exported.

**Comment by jfdm** [comment]
@nicolabotta 

The following link contains some examples of using idris packages to organise projects. 

+ `default` is contains the example you described above.
+ `with-global-pkg` organises the project as a single pacakge.
+ `with-local-pjg` organises the projects as multiple single packages with dependencies accessed locally. 

This might help your situation out.

http://jfdm.host.cs.st-andrews.ac.uk/misc/pkg-examples.tar.gz

**Comment by nicolabotta** [comment]
>  @nicolabotta Is the directory layout with idris files in your first comment of this thread indicative of the problem you are having? 

Yes

> I do not believe that statement to be true; I have written reasonably large Idris projects with multiple project dependencies that do work.

I very much hope that I am missing some type checking option or settin and that my statement is in fact false. But, at this point, I do not have any ovious reasons to believe so. The example above clearly shows that type checking from the parent directory of `Foo` and `Bar` works flawlessly and as expected:
```
nicola@cirrus:~/gitlab/IdrisLibs$ cd tmp/
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ find . -name *.ibc -delete
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ idris -V -i .. --check Bar/Operations.lidr 
Type checking ./Foo/Foo.lidr
Type checking ./Foo/Operations.lidr
Type checking ./Bar/Bar.lidr
Type checking ./Bar/Operations.lidr
nicola@cirrus:~/gitlab/IdrisLibs/tmp$
```
In contrast, type checking from `Bar` bluntly fails:
```
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ find . -name *.ibc -delete
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ cd Bar/
nicola@cirrus:~/gitlab/IdrisLibs/tmp/Bar$ idris -V -i .. --check Operations.lidr 
No ibc for Foo/Foo
nicola@cirrus:~/gitlab/IdrisLibs/tmp/Bar$
```
This (inconsistent) behavior is confirmed by attempts at type checking `Bar/Operations.lidr` in the idris-emacs mode with `C-c C-l`. This fails with the same error message
```
- + Errors (1)
 `-- (no file) line 0 col -1:
     No ibc for Foo/Foo
```
The example shows that type checking files with non-local depenencies does not work in the idris emacs mode with standard settings. If this is the case, I would argue that my statement

> maintaining a large Idris project with a lot of interdependencies is hardly possible.

is rather a matter of facts than a matter of belief: if one is forced to put all dependencies of a file in the same directory of that file, one can still build software systems, of course. 
But, as the example https://github.com/nicolabotta/SeqDecProbs (a sizeable but not a "large" system by any measure, I believe) suggests, one easily gets to the point of having hundreds of files in the same directory. For me, this is already beyond the border or maintainability.

Beside maintainability issue: I very much hope that Idris developers do not consider not being able to type check files with non-local depenencies to be the expected behavior!

**Comment by nicolabotta** [comment]
> Of note, the originasl examples have incorrect accessibility modifiers, remember the default accessibility for a project is private. The contents of Bar.Bar and Foo.Foo are not exported.

If this is the case, why does
```
nicola@cirrus:~/gitlab/IdrisLibs$ cd tmp/
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ find . -name *.ibc -delete
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ idris -V -i .. --check Bar/Operations.lidr 
Type checking ./Foo/Foo.lidr
Type checking ./Foo/Operations.lidr
Type checking ./Bar/Bar.lidr
Type checking ./Bar/Operations.lidr
nicola@cirrus:~/gitlab/IdrisLibs/tmp$
```
work fine? Perhaps an Idris error?

**Comment by nicolabotta** [comment]
> The following link contains some examples of using idris packages to organise projects. 

Thanks a lot Jan! The examples are very useful!

The `with-global-pkg` works fine but I really would like to have individual packages. The `with-local-pjg` fails with the same error message as reported above:
```
nicola@cirrus:~/gitlab/IdrisLibs/examples/packages/pkg-examples/with-indiv-pkg/bar$ less Makefile 
nicola@cirrus:~/gitlab/IdrisLibs/examples/packages/pkg-examples/with-indiv-pkg/bar$ less bar.ipkg 
nicola@cirrus:~/gitlab/IdrisLibs/examples/packages/pkg-examples/with-indiv-pkg/bar$ make check
idris --checkpkg bar.ipkg
Type checking ./Bar/Bar.idr
No ibc for Foo/Foo
Makefile:7: recipe for target 'check' failed
make: *** [check] Error 1
nicola@cirrus:~/gitlab/IdrisLibs/examples/packages/pkg-examples/with-indiv-pkg/bar$
```
Perhaps something wrong with my Idris installation? This is with `0.12.2-git:98c892c`.

**Comment by jfdm** [comment]
erm...it works fine here for me...otherwise I would not publish it.

I've checked with versions `11.2`, `0.12.2`, `0.12.2-git:51da43f`

**Comment by jfdm** [comment]
Oh, with the examples, if you are running make on each package individually you need to do them in order of use. That is, make sure Foo has been compiled first, then compile Bar. Otherwise the ibc's won't have been generated for the first package. Remember, `-i <path>` augments the search path for ibc files, they still need to be generated first.

The global makefile in the archive takes care of the ordering for you.

**Comment by nicolabotta** [comment]
> Oh, with the examples, if you are running make on each package individually you need to do them in order of use. That is, make sure Foo has been compiled first, then compile Bar. Otherwise the ibc's won't have been generated for the first package. Remember, -i <path> augments the search path for ibc files, they still need to be generated first.

> The global makefile in the archive takes care of the ordering for you.

Well, this sucks, right? The global makefile is not automatically generated, I understand. For this trivial example, one can easily determine that Foo needs to be built before building Bar. But, in general, how would you compute a proper build order? There might be none. In which order should one build
```
nicola@cirrus:~/gitlab/IdrisLibs$ ll
total 56
drwxr-xr-x 2 nicola nicola 4096 Aug  5 12:14 Decidable
drwxr-xr-x 3 nicola nicola 4096 Aug  5 14:09 examples
drwxr-xr-x 2 nicola nicola 4096 Aug  5 12:14 Fin
drwxr-xr-x 2 nicola nicola 4096 Aug  5 12:14 Finite
drwxr-xr-x 2 nicola nicola 4096 Aug  5 12:14 Fun
drwxr-xr-x 2 nicola nicola 4096 Aug  5 12:14 Isomorphism
drwxr-xr-x 2 nicola nicola 4096 Aug  5 12:59 List
drwxr-xr-x 2 nicola nicola 4096 Jul  1 17:09 Num
drwxr-xr-x 2 nicola nicola 4096 Aug  5 12:14 Pair
drwxr-xr-x 2 nicola nicola 4096 Aug  5 12:14 Pairs
drwxr-xr-x 2 nicola nicola 4096 Aug  5 12:14 Sigma
drwxr-xr-x 2 nicola nicola 4096 Aug  5 12:14 SimpleProb
drwxr-xr-x 4 nicola nicola 4096 Aug  4 14:19 tmp
drwxr-xr-x 2 nicola nicola 4096 Aug  5 12:14 Unique
```
for, say `SimpleProb/Operations.idr` to build? Perhaps there are dependency cycles and `SimpleProb/Operations.idr` cannot be built at all! It would be very difficult to determine a proper building order without computing the whole dependency tree. What if a component is modified and the modification introduces new dependencies? How would the build order change?

The point that I'm trying to make is that if the computation of dependencies (discovery of hidden cycles, computation of a proper building sequence, automatic building of out-of-sync files) only works when all files are in the same directory, then the system essentially sucks and one is left with only one usable guideline for organizing a collection of files: put them all in the same directory.

**Comment by jfdm** [comment]
One thing that has to be taken into consideration is how you wish to view your project. If it is a monolithic project in a single Idris package, then use of a single ipkg file is sufficient. It will take care of all the building, if you specify all the modules in your ipkg file. This works even if you organise your files as a nested hierarchy with the correct module declarations. 

However, if you view your project as a collection of separate idris packages then we have to take a bit of care with their development. As Idris does not have a package manager, we have to ensure correct installation of dependencies ourselves and do so manually. I do not advise the use of `-i`, and apologise if I concinved you that *was the way* you had to do it in idris, it is not.

As an alternative approach to the solution I suggested when using many small packages is to forgo specifying the `-i` option in the ipkg file, and install each of the packages individually (using `idris --install <pkg>.ipkg`) and within each ipkg file specify the dependencies. Idris will take care of module package loading et cetera. However, if you change something in one of your dependencies you then have to re install it. This is not ideal either; but is the same as I have encountered in any programming language I have worked with.

A third alternative would be to use the directory structure and monolithic ipkg file for development, then provide individual ipkg files that specify dependencies when you are ready to install/deploy the final solution..

Regardless, from what you have been mentioning in your responses over the organisation of your project. I do not think the use of individual Idris packages is suitable for your projects development. I think it would be better to use a single monolithic ipkg file, then if you are to provide these packages for others to use provide individual ipkg files for each sub package. This way when you develop your project you know the packages work together as a whole. I have updated the examples in the linked archive. with the third approach as detailed.

**Comment by nicolabotta** [comment]
Thanks for the detailed explanations Jan! For the moment, I am simply trying to cleanup and reorganize https://github.com/nicolabotta/SeqDecProbs a little bit. I am not pretending to build packages (to be honest, I do not even know what a package precisely is). If you do something like
```
cd SeqDecProbs-master/frameworks/14-/
make example5
```
you will immediately understand that finding out a proper build sequence for `example5` by hand would be hopeless.

But the type checker does that for you. The type checker seems to have no problems computing and building all dependencies of `example5` in a proper order as long as these have the same parent directory of `example5`!

What I do not understand is why the type checker is not able to track (and build) the dependencies of `example5` when the example and its dependencies are stored in subdirectory of `SeqDecProbs-master/frameworks/14-/`.

This seems to be completely inconsistent to me considering that the `import` directives contain all the information needed to locate all dependencies!

**Comment by nicolabotta** [comment]
Back to the original problem: with `Foo/Foo.lidr`, `Foo/Operations.lidr`, `Bar/Bar.lidr` and `Bar/Operations.lidr` defined as in my first post,
```
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ idris -V -i .. --check Bar/Operations.lidr
```
works flawlessly: the dependencies of `Bar/Operations.lidr` are computed and built in a proper order:
```
Type checking ./Foo/Foo.lidr
Type checking ./Foo/Operations.lidr
Type checking ./Bar/Bar.lidr
Type checking ./Bar/Operations.lidr
nicola@cirrus:~/gitlab/IdrisLibs/tmp$
```
So far so good. However
```
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ cd Bar/
nicola@cirrus:~/gitlab/IdrisLibs/tmp/Bar$ idris -V -i .. --check Operations.lidr
```
fails to compute and build the dependencies of `Bar/Operations.lidr`:
```
No ibc for Foo/Foo
nicola@cirrus:~/gitlab/IdrisLibs/tmp/Bar$
```
I think that **this is a bug and a huge obstacle toward software development in Idris**. Idris packages are not designed to address this issue. My questions are: **do Idris developers believe the above to be the expected behavior?** If not, would it be possible to correct the behavior in such a way that
```
nicola@cirrus:~/gitlab/IdrisLibs/tmp/Bar$ idris -V -i .. --check Operations.lidr
``` 
computes and builds the dependencies of `Bar/Operations.lidr` and yields something like
```
Type checking ../Foo/Foo.lidr
Type checking ../Foo/Operations.lidr
Type checking ../Bar/Bar.lidr
Type checking ./Operations.lidr
nicola@cirrus:~/gitlab/IdrisLibs/tmp/Bar$
```
? Thanks fo looking into this issue!

**Comment by ahmadsalim** [comment]
@nicolabotta I am not sure which strategy it should use without a package to discover the `Foo/Foo.lidr` which is in an unrelated folder to the one you are currently in (`Bar`).  

The primary point of packages is exactly that it allows you to organize your project as you want while providing a way for the system to find where they are by listing them.

**Comment by ahmadsalim** [comment]
If the issue is primarily that packages do not do automatic dependency resolution, then you would be welcome to suggest that as a feature request.

**Comment by nicolabotta** [comment]
> @nicolabotta I am not sure which strategy it should use without a package to discover the Foo/Foo.lidr which is in an unrelated folder to the one you are currently in (Bar). 

Hmm ... what does actually need to be discovered here? My understanding is that the directive
```
> import Foo.Foo
```
and the command `idris -i ..` unambiguously indicate that the file to be imported is either ./Foo/Foo.lidr or ../Foo/Foo.lidr. I could understand if the type checker had problems if both files would exist. But otherwise, I would expect no problems. Notice that not only
```
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ idris -V -i .. --check Bar/Operations.lidr
```
works fine, as reported above. Type checking works flawlessly also without the `-i ..` search path
```
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ find . -name *.ibc -delete
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ idris -V --check Bar/Operations.lidr
Type checking ./Foo/Foo.lidr
Type checking ./Foo/Operations.lidr
Type checking ./Bar/Bar.lidr
Type checking ./Bar/Operations.lidr
nicola@cirrus:~/gitlab/IdrisLibs/tmp$
```
as one would expect given the fully qualified import directives. This suggests that Idris does in fact know that the module `Foo.Foo` is to be found in `./Foo/Foo.lidr`! But then
```
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ cd Bar/
nicola@cirrus:~/gitlab/IdrisLibs/tmp/Bar$ idris -V -i .. --check Operations.lidr
```
fails. Why? Is this failure the expected behavior? This would be very surprising to me since I would expect Idris to now know that the module `Foo.Foo` can be found in `../Foo/Foo.lidr`. Otherwise, what is `-i ..` meant to be used for? Notice also that the error message is
```
No ibc for Foo/Foo
```
which suggests that the type checker in fact is not looking for `../Foo/Foo.ibc` but only for `./Foo/Foo.ibc`. Perhaps is the `-i ..` option simply broken?

**Comment by nicolabotta** [comment]
> If the issue is primarily that packages do not do automatic dependency resolution, then you would be welcome to suggest that as a feature request.

Thanks Ahmad but I think that the issue has little to do with packages. I might be mistaken, of course.

**Comment by ahmadsalim** [comment]
@nicolabotta Ah, I see now, I missed that you used `-i ..`. I guess you are right that it is reasonable that it should find the dependency if you provided that directive.

**Comment by nicolabotta** [comment]
> @nicolabotta Ah, I see now, I missed that you used -i ... I guess you are right that it is reasonable that it should find the dependency if you provided that directive.

That's it! Small problem but big impact. The failure to find and process the dependencies makes it virtually impossible to organize files with many cross-dependencied in all but a shallow hierarchy. Idris packages do not help very much here. But if the `-i` option would work as expected, there would be no problems, no matter whether with or without packages.

**Comment by nicolabotta** [comment]
Is there a chance to get the `-i` option working properly in the near future? This issue is really a dealbraker when one tries to organize a flat collection of files into subdirs! Thanks, Nicola

**Comment by jfdm** [comment]
@nicolabotta Actually, the issue you are experiencing with the `-i` options is most certainly *not* a deal breaker when organising a large Idris project into subdirectories to respect module hierarchies.

The different styles of organisations given in the archive [I posted earlier in this conversation](http://jfdm.host.cs.st-andrews.ac.uk/misc/pkg-examples.tar.gz) give alternative ways in which to organise a large project. Of one, use of a global ipkg file is what I think you are looking for and is the most safe option for organising projects irrespective of any perceived problems associated with the use of `-i`. The `Prelude` and `Base` use this means of internal organisation, so do all my Idris projects.

For the record, the flag `-i` is for adding ibc files to Idris search path, and is useful when working with packages that have not been installed or have been installed in a custom location. This flag may best best explained as analogous to Java's `--classpath`. With the use of this flag, I believe it is entirely reasonable for Idris to not expect source files to be adjacent to this ibc files. If the flag was to add external source files (i.e. something analgous to Java's `--sourcepath`) then that is a different matter entirely.

**Comment by nicolabotta** [comment]
@jfdm I disagree with your observations Jan and I do not understand why you insist in mixing up the issue reported here -- a misbehavior or an unexpected behavior of the `-i` option -- with the problem of how to take advantage of .ipkg files to build Idris packages. 

As shown in previous posts (and acknowledged by your comments), these problems are completely orthogonal: .ipkg files are fine if one already knows the order in which the dependencies of a file need to be build. But they do not provide any support for computing that order.

The issue reported here is about the computation of the order in which the dependencies of a file should be built. As it turns out, this computation works fine if all dependencies are in the same directory of that file and fails if this is not the case. This failure can be drawn back to an erroneous or unexpected behavior of the `-i` option.

I am glad that such behavior has no bearing on your work. It is possible that your projects can be decomposed in components with only internal dependencies (like the `Prelude`, for instance) and that you therefore do not need the `-i` option at all.

But, as explained above, the issue has devastating consequences on my project and I do not see anything wrong in asking for a fix.

It is possible that the flag -i was conceived for adding search paths for ibc files only, not for dependencies. In this case, I argue that we badly need a similar option for adding search paths for dependencies.

**Comment by ahmadsalim** [comment]
@nicolabotta I have changed the title to reflect the request.

**Comment by ahmadsalim** [comment]
@nicolabotta Is there a particular reason you prefer to not use package files, until this feature request is implemented? I perfectly understand it requires a bit more bookkeeping, but it should otherwise allow you to develop your project as you want.

**Comment by nicolabotta** [comment]
> @nicolabotta Is there a particular reason you prefer to not use package files, until this feature request is implemented? I perfectly understand it requires a bit more bookkeeping, but it should otherwise allow you to develop your project as you want.

The problem is not bookkeeping, the problem is that .ipkg files do not help finding out the order in which the dependencies of a specific file have to be built. As Jan pointed out above

> As Idris does not have a package manager, we have to ensure correct installation of dependencies ourselves and do so manually.

It goes without saying that, if we knew a proper build order, we would use .ipkg files or makefiles or a combination of both to enforce it. But, in all but the most trivial cases, we do not know such order and we have to rely on Idris to compute it.

As reported, this works fine if all dependencies of a file are in the same directory of that file. But otherwise it does not work. 

Thus, at the present, the only practicable way of organising a sizeable project for which a partitioning into self-contained sub-project is not known, seems to be that of keepeng all files in the same directory.

**Comment by nicolabotta** [comment]
Great, thanks Ahmad!

**Comment by jfdm** [comment]
The comment I made about dependencies was in reference to the *installation* of *idris packages* *external* to a single idris project. External packages have to be installed in the correct order, however, once installed the order in which they are specified in the ipkg file using the pkgs option does not matter. 

Within a project the ordering of modules in the ipkg does not matter. Idris already calculates the dependencies for each file with a project using the contents of the ipkg file. 

If you are developing multiple idris packages that rely on each other, one trick to use during development is to develop the packages alongside each other and use a single ipkg to ensure everything builds fine. You can then produce individual ipkg files for each package for their deployment with the correct pkg dependencies. Then it is up to the user to ensure that they are installed correctly.

**Comment by nicolabotta** [comment]
> @nicolabotta I have changed the title to reflect the request.

Thanks Ahmad!

**Comment by ahmadsalim** [comment]
@nicolabotta Sure! I will take a look at how to introduce a switch and the feature tomorrow. As far as I can see it should not be unreasonably hard to add.

**Comment by nicolabotta** [comment]
> If you are developing multiple idris packages that rely on each other, one trick to use during development is to develop the packages alongside each other and use a single ipkg to ensure everything builds fine. You can then produce individual ipkg files for each package for their deployment with the correct pkg dependencies. Then it is up to the user to ensure that they are installed correctly.

Right. This, in practice, implies that -- in projects where packages heavily rely on each other -- subdirectories can only be used once the the build order has been computed by keeping a project version with all files in the same directory. In turn, this means that, without code duplications, projects with strong dependencies between component are essentially unmanageable.  Such limitation could easily be avoided by letting Idris search not only .ibc files but also .ird (.lidr) files in the arguments of the `-i` option. This behavior seems (to me) both logical and doable.

**Comment by nicolabotta** [comment]
> @nicolabotta Sure! I will take a look at how to introduce a switch and the feature tomorrow. As far as I can see it should not be unreasonably hard to add.

That would be extremely helpful! Thanks again for your support. Best, Nicola

**Comment by ahmadsalim** [comment]
Hmm, this seems weird. So as far as I can tell, it is already searching for source files when using `-i`.

**Comment by ahmadsalim** [comment]
Anyway, I have started to add the switch and investigate the reasons. Hopefully I can figure out a solution soon.

**Comment by nicolabotta** [comment]
> Hmm, this seems weird. So as far as I can tell, it is already searching for source files when using -i.

That's what I would expect Idris to do
```
-i,--idrispath ARG       Add directory to the list of import paths
```
Thus, I was surprised that
```
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ find . -name *.ibc -delete
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ idris -V --check Bar/Operations.lidr
Type checking ./Foo/Foo.lidr
Type checking ./Foo/Operations.lidr
Type checking ./Bar/Bar.lidr
Type checking ./Bar/Operations.lidr
nicola@cirrus:~/gitlab/IdrisLibs/tmp$
```
works fine but
```
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ cd Bar/
nicola@cirrus:~/gitlab/IdrisLibs/tmp/Bar$ idris -V -i .. --check Operations.lidr
No ibc for Foo/Foo
nicola@cirrus:~/gitlab/IdrisLibs/tmp/Bar$
```
fails! The function that controls this behavior is `loadSource` at lines 1701-1729 of `src/Idris/Parser.hs`.

**Comment by jfdm** [comment]
I was looking at the original problem, not the lack of source path option, which is in itself a useful feature to have,  and noticed that when you are looking to load `Operations.idr` located in the directory `Bar` you are doing so from within `Bar` itself and not within the project's root directory.

Normally when working on an Idris project with a large nested module hierarchy I tend to invoke idris only from the projects root. This allows the compiler to have full view of the projects contents. That is, with the following files and setup as described in the initial issue comment:

`Foo/Foo.lidr`:
```
> module Foo.Foo
> data Foo
```

`Foo/Operations.lidr`:
```
> module Foo.Operations
> import Foo.Foo
> public export toNat : Foo -> Nat
> toNat f = Z
```

`Bar/Bar.lidr`:
```
> module Bar.Bar
> data Bar
```

`Bar/Operations.lidr`:
```
> module Bar.Operations
> import Bar.Bar
> import Foo.Foo
> import Foo.Operations
> toFoo : Bar -> Foo
> toNat : Bar -> Nat
> toNat = Foo.Operations.toNat . toFoo
```

I would have a single ipkg file `mypkg.ipkg` defined in the project root:

```
package mypkg

modules = Bar.Operations
        , Bar.Bar
        , Foo.Foo
        , Foo.Operations
```

I would compile and check the project as:

```sh
$ idris --build mypkg.ipkg
$ idris --checkpkg mypkg.ipkg
```

Then to load an individual file i would invoke idris from the project root as:

```sh
$ idris Bar/Operations.idr
```

If we try this with your original example, everything works as expected.

When defining modules there is no need to have a single ipkg file defined for each submodule in a nested module hierarchy. ipkg files used for organising a collection of modules including nested package hierarchies. Which from your original example appears to be what you are trying to aim for, and not have a collection of distinct packages.

I hope this helps with your original original problem.

**Comment by nicolabotta** [comment]
> I was looking at the original problem, not the lack of source path option, which is in itself a useful feature to have, and noticed that when you are looking to load Operations.idr located in the directory Bar you are doing so from within Bar itself and not within the project's root directory.

Right, the example is meant to mimic what happens when one attempts at type checking a leaf component of a project from emacs' idris-mode with C-c C-l. Thus, you are perfectly right and, as shown in
```
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ find . -name *.ibc -delete
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ idris -V --check Bar/Operations.lidr
Type checking ./Foo/Foo.lidr
Type checking ./Foo/Operations.lidr
Type checking ./Bar/Bar.lidr
Type checking ./Bar/Operations.lidr
nicola@cirrus:~/gitlab/IdrisLibs/tmp$
```
one can always type check no matter which leaf component in a project by calling Idris from the project root directory. This is a useful **workaround** when type checking from the command like.

Unfortunately, this **workaround** cannot be applied when type checking components from emacs' Idris mode. In emacs, and while editing a leaf component, C-c C-l fails in much the same way as
```
nicola@cirrus:~/gitlab/IdrisLibs/tmp$ cd Bar/
nicola@cirrus:~/gitlab/IdrisLibs/tmp/Bar$ idris -V -i .. --check Operations.lidr
No ibc for Foo/Foo
nicola@cirrus:~/gitlab/IdrisLibs/tmp/Bar$
```
does even though we have `-i ..` in the idris-mode customization options. The fact that **C-c C-l in the idris-mode only works when all dependencies of a file are in the same directory of that file** strongly suggests that the `-i` option is broken, as I have been arguing.

**Comment by jfdm** [comment]
Forgetting about the status of `-i`. 

If your project has an `ipkg` file in the project's root directory, idris mode will use the ipkg file to aide in compilation of the project.. Using the example I described in my previous message, if there the ipkg mode is present, I can load `Bar/Operations.idr` using idris mode.

**Comment by jfdm** [comment]
The feature [I described about idris-mode is documented](https://github.com/idris-hackers/idris-mode#package-files).

**Comment by nicolabotta** [comment]
> If your project has an ipkg file in the project's root directory, idris mode will use the ipkg file to aide in compilation of the project.. Using the example I described in my previous message, if the ipkg mode is present, I can load Bar/Operations.idr using idris mode.

This is nice but still does not solve the problem of how to generate the .ipkg file for a non-trivial case. This would require at least two steps

1) from the project's root directory, compute a build order for each leaf component of the project

2) merge the outcome of 1) in a suitable order

These steps would have to be recomputed every time new `import` directives are added to some leaf component.

**Comment by nicolabotta** [comment]
> All you need to do is ensure that the modules listed conform to the modules in the project. 

What does that mean precisely? Is it fine just listing all the modules of a project? That would solve the issue, it seems to me. Thanks, Nicola

**Comment by jfdm** [comment]
>  Is it fine just listing all the modules of a project?

Yes, that is what I meant, I try to order them alphabetically.

In the first instance, the modules option in an IPKG file acts as a listing to explicitly tell idris what to copy over when installing and what to remove when cleaning builds. If I recall correctly it also tells idris what to compile. Naturally, idris will also compile things referenced in an import statement but if they are not listed they won't get copied during installation nor removed when the package is cleaned.

**Comment by nicolabotta** [comment]
> Yes, that is what I meant, I try to order them alphabetically.

Thanks Jan! I am going to try this approach on https://gitlab.pik-potsdam.de/botta/IdrisLibs/tree/master and report. Best, Nicola

**Comment by nicolabotta** [comment]
This is precisely what we needed, thanks a lot Ahmad! Best, Nicola

**Comment by ahmadsalim** [comment]
You are very welcome!
