### ISSUE TITLE
Tests segfaulting on Windows 32-bit

### ISSUE THREAD

**Issue by steshaw** [idris-lang/Idris-dev#3325]
The following tests cause a segmentation fault:
- `basic003`
- `basic011`
- `bignum001`
- `effects001`
- `effects003`
- `sugar003`

I wonder if this might be a know problem — I built with GMP. i.e. my `custom.mk` file looks like:

``` Makefile
CABALFLAGS += -f GMP  -f FFI --disable-documentation
```

**Comment by melted** [comment]
I have only one failure on 32-bit windows, the one calculating hashes returns wrong output but doesn't crash. Possibly Data.Hash just isn't portable over different bit widths.

I didn't build with gmp, not the binaries either.

**Comment by steshaw** [comment]
I recompiled without gmp. Now there are 7 test failures — the ones above and `basic013`.

I'm on Windows 8.1 32-bit, with ghc 7.10.3 and cabal 1.22.0.0.

**Comment by melted** [comment]
Hmmm, I have same 32-bit GHC, but I'm on a 64-bit OS.  I also a 64-bit MSYS2 (it has 32-bit compilers too,  I found it rather more stable). I can set up a 32-bit VM and test.

**Comment by ahmadsalim** [comment]
@steshaw @melted Does this still happen in `0.99.2`?

**Comment by steshaw** [comment]
I no longer have that 32-bit Windows VM. It was one of the ones that was
available from http://modern.ie/ but this site and the available VMs has
changed since I last visited. It's no longer clear which if any are 32-bit.

**Comment by ahmadsalim** [comment]
@steshaw OK, thanks.

**Comment by ahmadsalim** [comment]
I am wondering whether this is something that could be tested with appveyor as well.

**Comment by steshaw** [comment]
Not sure but it looks like Appveyor uses only 64-bit Windows Server images.
However, it does have a variety of MinGW/MSYS/Cygwin options
<https://www.appveyor.com/docs/build-environment/#mingw-msys-cygwin>.

**Comment by ahmadsalim** [comment]
I will close the issue since there was no updates from anyone.
If the issue comes up again, we can handle it then.
