### ISSUE TITLE
Infinite loop when type family is specified as an implicit argument

### ISSUE THREAD

**Issue by alercah** [idris-lang/Idris-dev#3329]
The below example causes compiler non-termination:

```
data Foo : (b : Type) -> {pi : b -> Type} -> a -> Type where
  Bar : (b : Type) -> {pi : b -> Type} -> {f : (x : b) -> pi x} ->
              ((x : b) -> Foo b {pi} (f x)) -> Foo b {pi} f
```

Omitting f or making pi into an explicit argument causes the example to typecheck successfully. The former is particularly surprising behaviour.

**Comment by ahmadsalim** [comment]
Yeah it definitely seems that something is acting up here.

**Comment by atacratic** [comment]
I hit this as well.  Doesn't bother me too much as I can work around by making the type argument explicit.

```
-- idris 0.12

-- hangs
data A : {s : Type} -> Type -> Type where

-- no hang
data B : {s : Type} -> Type where

-- no hang
data C : (s : Type) -> Type -> Type where
```

**Comment by edwinb** [comment]
This seems to be fine now.
