### ISSUE TITLE
C header files should are not copied during package installing.

### ISSUE THREAD

**Issue by BartAdv** [idris-lang/Idris-dev#3368]
Let's use https://github.com/idris-hackers/idris-array for example:

    idris --install array.ipkg
    idris -p array

    λΠ> :module Data.Array
    λΠ> :exec fromList [1,2] >>= index 0 >>= printLn

```
/tmp/idris8594844211914544919.c:1:19: fatal error: Array.h: No such file or directory
 #include "Array.h"
                   ^
compilation terminated.
FAILURE: "gcc" ["-O2","-fwrapv","-fno-strict-overflow","-DHAS_PTHREAD","-DIDRIS_ENABLE_STATS","-I.","/home/bart/sources/idris-dev/.stack-work/install/x86_64-linux/lts-6.9/7.10.3/share/x86_64-linux-ghc-7.10.3/idris-0.12.2/array/Array.o","/tmp/idris8594844211914544919.c","-L/home/bart/sources/idris-dev/.stack-work/install/x86_64-linux/lts-6.9/7.10.3/share/x86_64-linux-ghc-7.10.3/idris-0.12.2/rts","-lidris_rts","-lgmp","-lpthread","-I/home/bart/sources/idris-dev/.stack-work/install/x86_64-linux/lts-6.9/7.10.3/share/x86_64-linux-ghc-7.10.3/idris-0.12.2/rts","-lm","-I.","-I/home/bart/sources/idris-dev/.stack-work/install/x86_64-linux/lts-6.9/7.10.3/share/x86_64-linux-ghc-7.10.3/idris-0.12.2/array","-I.","-I/home/bart/sources/idris-dev/.stack-work/install/x86_64-linux/lts-6.9/7.10.3/share/x86_64-linux-ghc-7.10.3/idris-0.12.2/prelude","-I/home/bart/sources/idris-dev/.stack-work/install/x86_64-linux/lts-6.9/7.10.3/share/x86_64-linux-ghc-7.10.3/idris-0.12.2/base","-o","/tmp/idris11311762291653377373"]
/tmp/idris11311762291653377373: rawSystem: runInteractiveProcess: exec: permission denied (Permission denied)
```

So, the directory where package has been installed is included correctly `"-I/home/bart/sources/idris-dev/.stack-work/install/x86_64-linux/lts-6.9/7.10.3/share/x86_64-linux-ghc-7.10.3/idris-0.12.2/array"`, but the Array.h file is not there.

**Comment by jfdm** [comment]
I have a peak at idris-array's ipkg file. When creating a binding to a c library as an idris package the header files should be listed in the 'obj' field of the ipkg file. This way Idris is aware of what 'objects' object files and header files need to be copied across.

**Comment by BartAdv** [comment]
Indeed, it does the trick. I guess, perhaps, the docs should be updated, but now when I look in the https://github.com/idris-lang/Idris-dev/blob/master/docs/tutorial/packages.rst it doesn't mention `objs` at all, whereas version published on readthedocs does...

**Comment by jfdm** [comment]
There are two locations in the Docs where packages are detailed:

1. The Tutorial. https://idris.readthedocs.io/en/latest/tutorial/packages.html
2. The reference: https://idris.readthedocs.io/en/latest/reference/packages.html

The tutorial contains a link to the reference docs that details the packages.

**Comment by BartAdv** [comment]
Now when I look at it, for sufficiently clever person it should be obvious that `objs` is the way to go, but for others, like me, I've proposed tiny change to the docs: https://github.com/idris-lang/Idris-dev/pull/3371
