### ISSUE TITLE
class used in error messages instead of interface

### ISSUE THREAD

**Issue by arianvp** [idris-lang/Idris-dev#3375]
How to reproduce:

```
data EmptyU = VOID

data Unifies : a -> b -> Type where
  ItUnifies : Unifies a b

interface DecUnifies a where
  decUnifies : a -> a -> Dec (Unifies a a)

DecUnifies EmptyU where
  decEq VOID VOID = Yes ItUnifies
```

Expected behaviour:
```
/home/arian/Projects/thesis2/src/Servis/API.idr:24:1:
Servis.API.decEq not a method of interface DecUnifies

```

Current behaviour:
```
/home/arian/Projects/thesis2/src/Servis/API.idr:24:1:
Servis.API.decEq not a method of class DecUnifies

```

**Comment by jfdm** [comment]
Looks like a few error messages need updating. These appear to be from in `Idris.Elab.Class` and friends. Easy fix, buy the looks of it.

**Comment by david-christiansen** [comment]
This would also be a great first project for an aspiring Idris contributor :-)

**Comment by zjhmale** [comment]
@jfdm actually, i think this message is from `Idris.Elab.Instance`

**Comment by jfdm** [comment]
maybe, there were a couple other places that came up when i grep'd for the error message. Any fixes should seek to fix *all* the uses of class (log messages and all) that should be updated.

**Comment by zjhmale** [comment]
>maybe, there were a couple other places that came up when i grep'd for the error message. Any fixes should seek to fix all the uses of class (log messages and all) that should be updated.

**Comment by ahmadsalim** [comment]
@zjhmale You could try using (the silver searcher)[https://github.com/ggreer/the_silver_searcher] and then search for `class` and `instance` and fix the right places. It is almost just as simple as a search/replace with a smart person to determine whether it makes sense :).

**Comment by jfdm** [comment]
I think for now the error messages, the other names can come later.

**Comment by zjhmale** [comment]
@jfdm ok.

**Comment by zjhmale** [comment]
@ahmadsalim thx!
