### ISSUE TITLE
Wired CI error

### ISSUE THREAD

**Issue by zjhmale** [idris-lang/Idris-dev#3385]
the CI servers were just unhappy with #3376, #3379 and #3381 that

```
Type checking ./System/Concurrency/Raw.idr
Can't find import System/Concurrency/Channels
make[1]: *** [build] Error 1
make[1]: Leaving directory `/home/travis/build/idris-lang/idris-0.12.2/libs/base'
make: *** [build] Error 2
make: Leaving directory `/home/travis/build/idris-lang/idris-0.12.2/libs'
```

is this caused by `.ibc` files which built up use previous version of Idris?

maybe should add a script to clean all the ibc files before build like

```
find . -name "*.ibc" -type f -delete
```

i use this command with locally build cause it always complains `ibc file build with old Idris` build error.

**Comment by Melvar** [comment]
I’m pretty sure that this was because a file was renamed but the references to it in other files were not.

**Comment by zjhmale** [comment]
@Melvar perhaps because the module name was renamed but the file name still the same, i mean `Session.idr` [here](https://github.com/idris-lang/Idris-dev/compare/1ca7a2c410...037ea33456)
