### ISSUE TITLE
No such variable "ty" error

### ISSUE THREAD

**Issue by xekoukou** [idris-lang/Idris-dev#3398]
```
module Main

import Data.HVect
import Data.Vect

%default total


data SFun : Vect k Type -> Type where
  MkSfun : {v2 : Vect k2 Type} -> {nv2 : Vect l1 (j: Nat ** o : Vect j Type ** SFun o) } -> HVect (map (\ (l ** (x ** y)) =>  HVect x ) nv2  ) -> SFun v2
```

The error is at the hole : 

```
module Main

import Data.HVect
import Data.Vect

%default total


data SFun : Vect k Type -> Type where
  MkSfun : {v2 : Vect k2 Type} -> {nv2 : Vect l1 (j: Nat ** o : Vect j Type ** SFun o) } -> HVect (map (\ (l ** (x ** y)) =>  ?hole ) nv2  ) -> SFun v2
```

Inspecting it , one can see that idris can deduce the type of x to be Vect l Type.

According to #3212 and #2134 , idris seems not to be able to infer an implicit argument. I can't find the implicit argument who cannot be deduced here.

**Comment by ahmadsalim** [comment]
@xekoukou The issue is basically I think that it can't deduce the type of the pattern matching lambda expression.

**Comment by ahmadsalim** [comment]
Specifically `HVect (map (\ (l ** (x ** y)) =>  ?hole ) nv2  )` the lambda expression here is my guess.

**Comment by xekoukou** [comment]
Probably because I use Vect into 2 different universes. I do not know. I haven't learned how to count universes yet.

**Comment by xekoukou** [comment]
Another example. Here the reasons might be different. If you want to make a new issue tell me.

```
import Data.Vect
import Data.HVect

findT3 : {hv : HVect [Type, ((a: Type) -> a -> Type), ((a: Type) -> (middle : (a -> Type))
 -> (xm : a) -> middle xm -> Type)]} -> 
         let [a, middle' , srest'] = hv in
         let middle = middle' a in 
         let srest = srest' a middle in
             ?dsf
```

The problem is on the last let statement.

**Comment by ahmadsalim** [comment]
@xekoukou Yeah, so in general you can't expect Idris to infer all types for you.
If it doesn't work, try annotate things with the target type, and it should go through.

**Comment by xekoukou** [comment]
It seems that there is nothing to annotate here. I am simply applying ```a``` and  ```middle``` to ```srest'``` .
