### ISSUE TITLE
Totality check failure for vectTake

### ISSUE THREAD

**Issue by shanemikel** [idris-lang/Idris-dev#3414]
Very eagerly and happily enjoying the new Idris book. (TYVM)

Unfortunately, I've stumbled upon a little bit of a problem with this function (ch4 exercise):

```idris
vectTake : (m : Fin (S n)) -> Vect n a -> Vect (cast m) a
vectTake FZ xs = []
vectTake (FS k) (x :: xs) = x :: vectTake k xs
```

The totality checker and case filler, alike, insist that there is the possibility of these args:
```idris
vectTake (FS x) [] = ?vectTake_rhs_1
```

Idris V0.12.2

**Comment by xekoukou** [comment]
```x : Fin 0``` is a possible type since ```data Fin : Nat -> Type```

If you casesplit on x, then all options are impossible, because neither of FZ or FS  construct Fin 0.

```
import Data.Vect
import Data.Fin

%default total

vectTake : (m : Fin (S n)) -> Vect n a -> Vect (cast m) a
vectTake FZ xs = ?vectTake_rhs_1
vectTake (FS FZ) [] impossible
vectTake (FS (FS _)) [] impossible
vectTake (FS x) (y :: xs) = ?vectTake_rhs_4
```

**Comment by ahmadsalim** [comment]
@shanemikel You should probably want to use `(m : Fin n) -> Vect n a -> Vect (cast m) a` instead, otherwise as @xekoukou said it is perfectly valid. This is because it is only later when we pattern match on `x` that the cases become impossible.

**Comment by ahmadsalim** [comment]
Or I now see that you use `FZ` to mean take none, so the maximum value you want is `n`. Therefore your signature is fine.
If you are satisfied with the provided answers, could you kindly close the issue?

**Comment by shanemikel** [comment]
I see.  I suspected it had to do with legality of Fin 0.
Thanks
