### ISSUE TITLE
oldeffects isn't buildable

### ISSUE THREAD

**Issue by enolan** [idris-lang/Idris-dev#3435]
It's in `libs/oldeffects/`, but it's not hooked up to the build system, and compiling it manually fails:

```
Type checking ./Effect/Default.idr
./Effect/Default.idr:39:16:When checking type of Default.Vect n a implementation of Default.Default:
When checking argument a to type constructor Default.Default:
        No such variable Vect
```

It hasn't been buildable since at least v0.10. Probably earlier, but the `stack.yaml`s either don't work or are nonexistent. I don't think anyone would miss it if it were removed.

**Comment by jfdm** [comment]
Ah yes, `oldeffects`. I think `effects` is sufficient stable and used that `oldeffects` can be spun out somewhere for posterity/conservancy. I'll leave that up to @edwinb to decide where.

**Comment by ahmadsalim** [comment]
We should have some tests for building bundled standard libraries I think.

**Comment by LeifW** [comment]
Would throwing in a "idris --build oldeffects.ipkg" in the travis file
somewhere beer enough?

**Comment by enolan** [comment]
Leif, it's too early for beer :p

**Comment by LeifW** [comment]
Would "Freudian slip" be applicable to a phone's overeager autocorrect?

**Comment by ahmadsalim** [comment]
I don't think this is relevant to fix anymore, beyond removing oldeffects
