### ISSUE TITLE
"return" still present in tutorial

### ISSUE THREAD

**Issue by siddharthist** [idris-lang/Idris-dev#3453]
https://github.com/idris-lang/Idris-dev/search?utf8=%E2%9C%93&q=m_add+x+y+%3D+return+%28%21x+%2B+%21y%29&type=Code

**Comment by ahmadsalim** [comment]
@siddharthist Thank you for the bug report.

This seems like a good low hanging fruit for an initial PR, if you are interested in providing that :).
