### ISSUE TITLE
ffi009 seems to fail silently

### ISSUE THREAD

**Issue by steshaw** [idris-lang/Idris-dev#3465]
I thought I'd broken something on my branch when I noticed `ffi009` succeeds but has what looks to be a nasty runtime error. Perhaps that's expected?

> idris-0.12.3: test (suite: regression-and-feature-tests, args: --pattern ffi009)
> 
> Progress: 1/2Regression and feature tests
>   FFI
>     ffi009:
> Error: test/ffi009
> idris: Foreign Function calls cannot be partially applied, without being inlined.
> CallStack (from HasCallStack):
>   error, called at src/IRTS/CodegenC.hs:343:36 in idris-0.12.3-LoUXGyrDJU677RY2CaNGaq:IRTS.CodegenC
> clang: warning: argument unused during compilation: '-fno-strict-overflow'
> 
> OK (7.63s)
> 
> All 1 tests passed (7.63s)
> 
> Completed 2 action(s).
>       641.07 real       579.88 user        23.90 sys
>

**Comment by jfdm** [comment]
@steshaw I am responsible for `ffi009`. What you are seeing is expected. There are two tests being performed here:

1. Use the FFI as expected, no failure.
2. Use the FFI with a partially applied FFI call and expect to fail. 

The second test will report the error to stderr and will fail. Before Idris didn't complain about partially applied FFI calls, and this error would arise during runtime. This test is there to check that we can catch such errors in the C FFI backend. We still need to catch it generically higher up in the compilation stack. Unfortunately, we cannot check expected stderr output.

Hope this satisfies your query.

**Comment by ahmadsalim** [comment]
@jfdm Perhaps for this test, you can capture stderr into an `errors` file or something, and then use the comparison feature of the test suite? I think that would be a nicer solution than outputting it during the run of the test suite.

**Comment by steshaw** [comment]
No worries, @jfdm. Just wanted to make sure everything was ok. At least this issue will be here if other folks think they've broken something :).
