### ISSUE TITLE
Circular dependencies - no error message

### ISSUE THREAD

**Issue by BartAdv** [idris-lang/Idris-dev#3468]
```idris
import Debug.Trace

mutual
  record Foo where
    constructor MkFoo
    fee : Integer
    bar : Bar

  record Bar where
    constructor MkBar
    foo : Foo

mkFoo : Integer -> Bar -> Foo
mkFoo = trace "mkFoo" $ MkFoo

mkBar : Foo -> Bar
mkBar = trace "mkBar" $ MkBar

knot : Integer -> Bar
knot i = b
  where
    mutual
      f : Foo
      f = mkFoo i b
      b : Bar
      b = mkBar f

main : IO ()
main = do
  let b = knot 10
  printLn $ show $ fee $ foo $ b
```

Above code, when run, loop endlessly then segfaults.

With following changes:

```idris
mkFoo : Integer -> Bar -> Foo
mkFoo i b = trace "mkFoo" $ MkFoo i b

mkBar : Foo -> Bar
mkBar f = trace "mkBar" $ MkBar f
```

it does not loop. Without traces:

```idris
mkFoo : Integer -> Bar -> Foo
mkFoo = MkFoo

mkBar : Foo -> Bar
mkBar = MkBar
```

it does not loop as well.

Are we even allowed to use mutual like this? If so, when is it correct?

**Comment by ahmadsalim** [comment]
Remember that Idris is a strict language, and so in order to do knot-tying you have to use `Lazy` explicitly for the members you want to knot.

The segmentation fault is probably because you run out of stack space (I think we have an issue of making a better error message for that).

**Comment by ahmadsalim** [comment]
Oh, I see. I am not sure about the particular semantics of why it doesn't loop when you change the definitions of `MkFoo` and `MkBar`. I would guess that the semantics would specify that it should loop in any case, so I am surprised it doesn't.

**Comment by BartAdv** [comment]
Thanks! 

So I guess what this issue now is about is the lack of error message that would prevent user from shooting himself in the foot...

**Comment by BartAdv** [comment]
On a second thought - I guess the fact it's being picked up as partial is enough.
