### ISSUE TITLE
Null pointer dereference in generated C code

### ISSUE THREAD

**Issue by andreas23** [idris-lang/Idris-dev#347]
The following code crashes when compiled and executed with the C backend:

<pre>
module Main
 
import Data.Bits
 
Byte : Type
Byte = Bits 8
 
Buffer : Type
Buffer = List Byte
 
infixl 9 &
infixl 8 |||
infixl 8 ^
 
(&) : Bits x -> Bits x -> Bits x
(&) = and
 
(|||) : Bits x -> Bits x -> Bits x
(|||) = or
 
(^) : Bits x -> Bits x -> Bits x
(^) = xor
 
(<<) : Bits x -> Bits x -> Bits x
(<<) {x} a b = a `shiftLeft` b
 
(>>) : Bits x -> Bits x -> Bits x
(>>) a b = a `shiftRightLogical` b

decodeDigit : List Char -> Char -> Maybe Byte
decodeDigit digits c = [| intToBits [| cast (elemIndex c digits) |] |]
 
encodeDigit : List Char -> Byte -> Maybe Char
encodeDigit digits i = case drop (fromInteger (bitsToInt i)) digits of
  []     => Nothing
  (x::_) => Just x
 
hexdigits : List Char
hexdigits = unpack "0123456789abcdef"
 
decodeHexDigit : Char -> Maybe Byte
decodeHexDigit = (decodeDigit hexdigits) . toLower
 
encodeHexDigit : Byte -> Maybe Char
encodeHexDigit = encodeDigit hexdigits
 
decodeHex : List Char -> Maybe Buffer
decodeHex []           = Just []
decodeHex (a::b::tail) = [| List.(::)
                            [| [| (decodeHexDigit a) << (Just (cast 4)) |]
                               ||| (decodeHexDigit b) |]
                            (decodeHex tail) |]
decodeHex _            = Nothing
 
decodeHexString : String -> Maybe Buffer
decodeHexString = decodeHex . unpack
 
-- we should be able to prove that encodeHexDigit never fails here,
-- and change the return type to List Char.
encodeHex : Buffer -> Maybe (List Char)
encodeHex []     = Just []
encodeHex (b::t) = [| List.(::) (encodeHexDigit (b >> (cast 4)))
                      [| List.(::) (encodeHexDigit (b & (cast 0xf)))
                         (encodeHex t) |] |]
 
encodeHexString : Buffer -> Maybe String
encodeHexString x = [| pack (encodeHex x) |]
 
hexString : String
hexString = "49276d206b696c6c696e6720796f757220627261696e206c696b65206120706f69736f6e6f7573206d757368726f6f6d"
 
testHex : Bool
testHex = flatten {m=Maybe} [| encodeHexString (decodeHexString hexString) |] == Just hexString
 
main : IO ()
main = if testHex then
         putStrLn "hex tests pass."
       else
         putStrLn "hex tests FAIL!"

</pre>

**Comment by melted** [comment]
After swapping out |||, this worked for me.
