### ISSUE TITLE
PDF version of docs.idris-lang.org only contains "Tutorials on the Idris Language"

### ISSUE THREAD

**Issue by owickstrom** [idris-lang/Idris-dev#3473]
Hi!

The latest versions of the docs at docs.idris-lang.org, in the PDF format, contains only the two parts in "Tutorials on the Idris Language" (https://media.readthedocs.org/pdf/idris/latest/idris.pdf). The EPUB and HTML export formats seem to contain all the chapters.

I can take a look at the Sphinx config and see if I find something.

**Comment by jfdm** [comment]
@owickstrom This is on purpose, as LaTeX was complaining during compilation of the PDFs. I've switched it off in the meantime, as that was easiest and I thought it best that we at least get the tutorial out as a PDF.

You are more than welcome to try and get ALL the PDFs compiling successfully.

**Comment by owickstrom** [comment]
@jfdm I see, and agree with your prioritization. :+1:  I'll have a go at and see if I can get it to work. Been doing some Sphinx documentation work lately, but far from export in the area. Anyways, I'll ping you when I've tried.

**Comment by owickstrom** [comment]
@jfdm Sent a PR that seems to fix this.
