### ISSUE TITLE
System.Exit returns `()`, not `a`

### ISSUE THREAD

**Issue by HuwCampbell** [idris-lang/Idris-dev#3488]
In System.idr, the `exit` function returns `()`, unlike its haskell equivalent, which has type signature `IO a`. It seems a bit inflexible.

`https://github.com/idris-lang/Idris-dev/blob/master/libs/base/System.idr#L57`

**Comment by HuwCampbell** [comment]
This isn't important enough to clutter the issues page.

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue.
I do think you have a valid point here, so I have reopened it; we apologize for the delayed response.
