### ISSUE TITLE
OS X builds timing out when cache is stale

### ISSUE THREAD

**Issue by enolan** [idris-lang/Idris-dev#3496]
[Here](https://travis-ci.org/idris-lang/Idris-dev/jobs/168413151) [are](https://travis-ci.org/idris-lang/Idris-dev/jobs/167139415#L753) [three](https://travis-ci.org/idris-lang/Idris-dev/jobs/164820550) recentish PRs where Travis failed because the OS X build timed out. The cache is stale in all of them. I think Travis' caches are per user/matrix entry so PRs don't have access to the main cache.

Travis' time limit is 50 minutes total or 10 minutes without any output. It's not possible to pre-warm the cache or save it if a build times out, so it needs to be able run to completion within the limit without using the cache. This obviously happens sometimes, otherwise the cache would never get filled and all the builds would fail, but it looks like we're on the edge.

**Comment by ahmadsalim** [comment]
Thanks for the bug report. Any suggestions on how to fix this?

**Comment by jfdm** [comment]
Maybe the problem will have resolved itself naturally, given the recent pushes by @edwinb that provide some performance improvements?

**Comment by ahmadsalim** [comment]
@jfdm  Sorry, is this a response to another issue? I am not sure I understand the context.

**Comment by jfdm** [comment]
So looking at the OS X builds, pre-build steps,and some install steps, are taking longer than we see for other builds. It might be of use to see how we can speed this up. These builds are not using a stale cache from what I can see.

**Comment by melted** [comment]
We don't have macOS builds on Travis anymore.
