### ISSUE TITLE
Wrong implementation of atan2 in Doubles.idr

### ISSUE THREAD

**Issue by Niriel** [idris-lang/Idris-dev#3497]
Idris provides two arc-tangent functions:
- `atan: Double -> Double` and
- `atan2: Double -> Double -> Double`.

Both return an angle, but their images in the codomain differ.  `atan` is limited to half the unit circle, while `atan2` covers the whole unit circle.  `atan2` is able to determine the correct quadrant of an angle by looking at the sign of each of its arguments.  When both arguments are positive, then `atan2 y x = atan (y/x)`, but as soon as one is negative, the results differ.

The current implementation of `atan` and `atan2` in `Doubles.idr` are

```
atan : Double -> Double
atan x = prim__floatATan x

atan2 : Double -> Double -> Double
atan2 y x = atan (y/x)
```

By calling `atan(y/x)` in all cases, even when `x` or `y` is negative, this version of `atan2` loses sign information and therefore does not fulfill its job.

I do not know whether there exists a `prim__floatATan2` that you can use.  If not, Wikipedia describes the algorithm clearly https://en.wikipedia.org/wiki/Atan2 .

(Edit: grammar)

**Comment by enolan** [comment]
I started on a version written in Idris but I think it's better to add a primop and use an optimized C version. It has a *ton* of special cases and the [glibc people go to a lot of effort to make it fast](https://github.com/lattera/glibc/blob/master/sysdeps/ieee754/dbl-64/e_atan2.c#L65-L393).
