### ISSUE TITLE
Nonsensical ranges should be empty

### ISSUE THREAD

**Issue by orokanasaru** [idris-lang/Idris-dev#3503]
```
Idris> [3,1..15]
[3, 1, -1, -3, -5, -7, -9] : List Integer
```

Why is that the result? The same input in Haskell just returns []

**Comment by ahmadsalim** [comment]
This is indeed a bug. If anyone is interested in fixing these bugs take a look at:
https://github.com/idris-lang/Idris-dev/blob/0d3d2d66796b172e9933360aee51993a4abc624d/libs/prelude/Prelude.idr#L186
