### ISSUE TITLE
Using "vim -f" as EDITOR crashes REPL

### ISSUE THREAD

**Issue by berndlosert** [idris-lang/Idris-dev#3506]
When I type :e in the REPL, it dies with:

```
Uncaught error: vim -f: rawSystem: runInteractiveProcess: exec: does not exist (No such file or directory)
```

By the way: I'm using Idris 0.12.2 on Mac OS X El Captian.

**Comment by melted** [comment]
I don't see the value of not running the editor via a shell (ie system instead of rawSystem). On the other hand, I'm surprised this isn't already fixed. I seem to remember me doing it.

**Comment by melted** [comment]
Oh, yes, I did: https://github.com/idris-lang/Idris-dev/commit/799b4321a19b41b8e74069ecd6a3dc493a7bfe63

It first appeared in 0.12.3, so just upgrade.

**Comment by melted** [comment]
I see @ahmadsalim confirmed it. So reopening in case we have a bug on some platform.

**Comment by berndlosert** [comment]
I upgraded and it fixed the problem.

**Comment by jfdm** [comment]
Problem solved then?

**Comment by berndlosert** [comment]
Yes. I'll close the issue.
