### ISSUE TITLE
Improve documentation of abstract functions by adding concrete examples

### ISSUE THREAD

**Issue by Qqwy** [idris-lang/Idris-dev#3510]
Hello, dear Idris developers,

I have some experience with Haskell and Elixir, and am now learning Idris. I notice that there are still many functions in the prelude that either have no documentation at all yet, or have only a very short description.

What seems to me the hardest hurdle to overcome for newcomers, is that there are no examples on how certain functions can be, or ought to be, used. Because of the generalized nature of many of these functions, without some understanding of category theory, I expect that many newcomers will get lost very easily.

For instance: `map` is obviously 'abstract' in that it works on any Functor. But it would be very helpful to show what happens when we do e.g. `map (+ 5) [1,3,5,7]` and `map (* 2) Just 10` (and maybe some more examples for other Functor instances that ship with the Prelude as well).

Likewise, it is not mentioned in the documentation of e.g. the `Monad` interface, that data types are required to also implement the `Applicative` interface.

I would love to help Idris out by writing some documentation and adding some concrete examples to these relatively abstract concepts. 

Do you agree that this is a good idea, or are there other plans in this area and would it be better to focus my efforts on something else?

**Comment by NobbZ** [comment]
Hi Qqwy!

I'm not in the core team, but someone who tries to figure out how Idris
works, just like you do. Even our functional background seems to be similar
;) Maybe you even recognize me from the elixir world (known as NobbZ there).

I often thought the same about the documentation as you do, but never found
the time to actually try to write some of it. Also I am not a native
speaker, so I have trouble to write up technical documentation in english.

So, yes, at least as a "customer" I'd appreciate anything that improves
documentation around Idris.

Qqwy <notifications@github.com> schrieb am Di., 1. Nov. 2016 um 08:57 Uhr:

**Comment by Qqwy** [comment]
Helllo Nobbz,

Yes, our backgrounds definitely seem similar. And of course I recognize you from the Elixir world :grin: !

Glad to hear that I am not the only person that thinks this way about the documentation (Maybe recognizing the need for clear documentation actually is an Elixir influence? :stuck_out_tongue_winking_eye: ). 

English isn't my native language either (Dutch and German are), but I've been using it daily for the past... 8 years professionally, so I feel confident enough to write some documentation. As for my category theory skills... they definitely have an apparent ceiling, but we'll cross that bridge when we get to it.

Unless someone from the Idris core team suggests that I should not do so, I will go forward and conjure up one (or a few) PRs.

If anyone has any tips or suggestions, those are of course very welcome. :-)

Have a wonderful day,

~Qqwy

**Comment by david-christiansen** [comment]
Examples are a great idea!  You do know that you can put examples directly in Idris's API docs, right?

It does seem that this is missing support for implementation docs, however, because an implementation is not in scope in its own docs, which means that resolution fails. This would be worth improving!

**Comment by ahmadsalim** [comment]
I think this is a great idea as well and people are welcome to add more examples as needed.
However, I am not sure how much value there is in keeping this in the issue tracker if no one volunteers to do them, and so I will close the issue.
