### ISSUE TITLE
Too many arguments in interface definition

### ISSUE THREAD

**Issue by alercah** [idris-lang/Idris-dev#3511]
The following produces an error:

    module Map

    interface Map (M : Type) where
        empty : M
        IsEmpty : M -> Type
        emptyIsEmpty : IsEmpty empty

    
    /path/to/Map.idr:8:11:When checking type of constructor of
    Data.Certified.Map.Map:
    Too many arguments for empty

which is kind of strange since empty has no arguments given to it.

**Comment by tsani** [comment]
Idris seems to be confusing your *declaration* of `empty` with a *use* of `Prelude.Applicative.empty`. If you write `%hide Prelude.Applicative.empty` before your interface declaration, the file typechecks.

What is extremely odd though is that if you write the desugared interface declaration
```
data Map : Type -> Type where
  MkMap : (empty : m) -> (IsEmpty : m -> Type) -> IsEmpty empty -> Map m
```
there is no error.

**Comment by edwinb** [comment]
This appears to be fine now. I assume that when I redid interface elaboration a couple of months ago it resolved this (that wouldn't surprise me, it did make things work much more sensibly, and this is the kind of thing I was trying to resolve...)
