### ISSUE TITLE
Streams sugar unobvious and contradicts TDD book

### ISSUE THREAD

**Issue by zmactep** [idris-lang/Idris-dev#3512]
Hi everyone.

My Idris REPL (version `0.12.3` from Homebrew on macOS Sierra 10.12.1) shows me this:
```
Idris> take 10 [1,3..]
[1, 4, 7, 10, 13, 16, 19, 22, 25, 28] : List Int
```
when in ghci (GHC 8):
```
Prelude> take 10 [1,3..]
[1,3,5,7,9,11,13,15,17,19]
```

In TDD book (11.1.5, page 334 of V12 MEAP) also presented a natural variant (haskell-like), so it seam to be a bug.

The origin, as I understand:
```
Idris> [1,3..]
1 :: Delay (enumFromThen 4 3) : Stream Integer
```
but it should be
```
1 :: Delay (enumFromThen 3 2) : Stream Integer
```

**Comment by xekoukou** [comment]
The implementation is wrong as pointed out by #3502 #3503.

**Comment by ahmadsalim** [comment]
The Stream implementation is still wrong.

**Comment by ahmadsalim** [comment]
Actually, the next step is correct now, but the following step is wrong.
