### ISSUE TITLE
:let does not perform pattern matching

### ISSUE THREAD

**Issue by Qqwy** [idris-lang/Idris-dev#3513]
The `:let` command that can be used in the Idris console is somewhat specific in its use:

`:let x = 10` works fine, it binds the name `x` to  `10`.
`:let (y) = (11)` does not define `y`.
`:let (z :: zs) = [1,2,3,4]` does not define `z` or `zs`.

From Haskell, I am used to do pattern matching on a result in the REPL if I want to zoom in on a particular portion of a data structure. Am I doing something wrong, or is `:let` as it is made right now more limited than it ought to be?

**Comment by jfdm** [comment]
From what I remember, and I could be wrong, the `:let` REPL command is designed to work for quickly assigning variables more than assigning functions.

**Comment by Qqwy** [comment]
`:let` has as description: _"Evaluate a declaration, such as a function definition, instance implementation, or fixity declaration"_.

The interesting thing about the current behaviour, is that in the above two cases where nothing happens, no error or warning is shown; it effectively becomes a no-op. At the very least, this will be a source of confusion for newcomers (it confused me, at least... :sweat_smile:).

So I think one of two things should happen:

- 1) Make `:let` show an error message if anything unrecognizeable is used as LHS of the `=` (anything other than a single variable name).
- 2) Make `:let` smarter, so it supports pattern-matching. (Of course, it still would be great if it explicitly warns you when you do something unsupported.)


---------

There are even more confusing situations where `:let` behaves oddly:

```
Idris>:let x = 10
Idris> x
10 : Integer
Idris>:let myId something = something
No such variable something
Idris>:let myId x = x
myId 20
Too many arguments for myId
Idris>myId
10
```
So it seems that, while the documentation string of `:let` (you can see it when typing `:h` in the REPL) tells you that you can define functions using it, it will actually just take the first name, interpret all other names as the values they are bound to (including pointing out unbound variables) and, if successful, simply assign the RHS to the first name read on the LHS.

**Comment by ahmadsalim** [comment]
PRs are welcome, but I will close the issue since discussions have stalled and there has been no update on implementation of the feature request.
