### ISSUE TITLE
Inf disappears in some cases

### ISSUE THREAD

**Issue by zmactep** [idris-lang/Idris-dev#3514]
For the code sample:
```
data InfList : Type -> Type where
  (::) : (value : elem) -> Inf (InfList elem) -> InfList elem

%name InfList xs, ys, zs

getPrefix : (count : Nat) -> InfList a -> List a
getPrefix Z xs = []
getPrefix (S k) (value :: xs) = value :: getPrefix k ?hole_xs
```

The `xs` type should be `Inf (InfList elem)`, but **type of** (Ctrl-Alt-T in Atom) `?hole_xs` gives me:
```
  a : Type
  k : Nat
  value : a
  xs : InfList a
--------------------------------------
hole_xs : InfList a
```
So, the type of `xs` is `InfList elem`, not `Inf (InfList elem)`, so
```
getPrefix (S k) (value :: xs) = value :: getPrefix k (Force xs)
```
will not typecheck (but it should based on TDD 11.1.4).

I can write
```
getPrefix (S k) (value :: (Delay xs)) = value :: getPrefix k ?hole_xs
```
and this typechecks as well. So, the type of `xs` is however `Inf (InfList elem)` in this way of writing of this line.

**Comment by edwinb** [comment]
This is correct - the 'Delay' is being inserted implicitly, which is what makes Inf disappear.

**Comment by zmactep** [comment]
Thanks, got it. I thought I can write this construction fully explicit. And then there is a typo in TDD.

**Comment by ahmadsalim** [comment]
@zmactep Is this issue something we can close now?

**Comment by zmactep** [comment]
@ahmadsalim I think we can close it, as this implicit conversion is a normal way.
