### ISSUE TITLE
lines/unlines only works with List String, not with Vect n String.

### ISSUE THREAD

**Issue by Qqwy** [idris-lang/Idris-dev#3515]
I am working through the Idris book.
During the section in Ch. 4 where you are building a schema to store strings in, I implemented the 'search' command, which was one of the exercises.

You there have a `Vect n String`, and you want to print all strings that a `query : String` is an infix of.

So I ended up with something like `show $ filter (isInfixOf query) (items store)`.

I wanted to use the function `unlines` instead of `show` (I know it from Haskell), but it turns out that `unlines` only works with lists, and not with Vects.

Looking [in the documentation](http://www.idris-lang.org/docs/current/prelude_doc/docs/Prelude.Strings.html) of `Prelude.Strings`, it seems that there are many other functions (`lines`, `words`, `unwords`, `split`) that expect a List as type.
Is there a way to make these functions work for Vectors as well?

**Comment by ahmadsalim** [comment]
@Qqwy Take a look at `fromList` and `toList`, which allow you to convert and back and forth between `Vect` and `List`

**Comment by ahmadsalim** [comment]
@Qqwy Was the answer satisfactory, and can we close this issue now?

**Comment by ahmadsalim** [comment]
OK, I will close the issue. Feel free to reopen if necessary.

**Comment by Qqwy** [comment]
For posterity: `toList` and `fromList` are indeed what I was looking for.

This issue did start [an interesting discussion](https://groups.google.com/forum/#!topic/idris-lang/MWJ4zDcjl10) about what functions should be generalized to work on other listlike types as well, and what the difference between e.g. a Vector and a List actually is.

Thank you, @ahmadsalim !
