### ISSUE TITLE
Add nonzero restriction on `gcd`

### ISSUE THREAD

**Issue by Qqwy** [idris-lang/Idris-dev#3517]
The current version of `gcd` is defined as follows:

```Idris
gcd : Nat -> Nat -> Nat
gcd a 0 = a
gcd a b = assert_total (gcd b (modNat a b))
```

Because I'm working on a small hobby project that needs to prove things about Greatest Common Divisors, I stumbled across a page on [proofwiki](https://proofwiki.org/wiki/Existence_of_Greatest_Common_Divisor). It states that a requirement for being able to compute `gcd a b`, is that `a≠0 ∨ b≠0`. The current definition does not have this requirement, which means that `gcd 0 0` is accepted as valid input (producing the value 0. Of course, zero can never be a divisor for anything, as you cannot ever divide by zero, so this is wrong.).

I am too new to Idris to know how to write `a≠0 ∨ b≠0` in Idris proofs (especially the 'or' operation), but I think changing the definition of GCD would be great, as we can then use `modNatNZ`(which is total) instead of `modNat` (which is not), so the `assert_total` would no longer be needed.

**Comment by ahmadsalim** [comment]
@Qqwy A simple way to write that constraint would be to take argument `(notBothZero : (a = 0) -> (b = 0) -> Void)` (which is isomorphic to `Either (Not (a = 0)) (Not (b = 0))` and `Not (a = 0, b = 0)`).

**Comment by fabianhjr** [comment]
Note: changing from `modNat` to `modNatNZ` was not enough to gurantee that gcd would be total. Asertion had to be kept. (Refer to #3537)
