### ISSUE TITLE
eqSucc and succInjective parameters

### ISSUE THREAD

**Issue by jachymb** [idris-lang/Idris-dev#3529]
I believe the functions `succInjective` and `eqSucc` would be more useful if the parameters `left` and `right` were implicit. I want to use them when I have relatively complex expressions in both and I don't see a good reason why I should be forced to pass them explicitly.

**Comment by jachymb** [comment]
i.e. we would have
    
    total succInjective : {left : Nat} -> {right : Nat} -> (p : S left = S right) -> left = righ
    succInjective Refl = Refl

it typechecks. Perhaps there was a reason to have the arguments explicit. If yes, please enlighten me :-)

**Comment by edwinb** [comment]
As a convention, we've generally made arguments explicit in functions which manipulate proofs - I've found it's generally clearer in things which are intended as proofs to write the arguments explicitly, and it might not be possible to infer them in more complex cases.

I'd just suggest writing your own wrapper if you'd prefer the arguments to be implicit.
