### ISSUE TITLE
Tuples of different lengths can unify.

### ISSUE THREAD

**Issue by alercah** [idris-lang/Idris-dev#3532]
I'm reporting this based on a conversation on IRC from a few weeks ago. I don't have time to dig out the logs but wanted to get the ticket down. Feel free to close as wontfix and point me at an explanation.

Related sort of to #3166, the issue is that tuples are represented as nested pairs, so for instance `(a, b, c)` is actually `(a, (b, c))`. This is irritating because it means that `(a, b)` will actually unify fine with `(c, d, e)`, where `b = (d, e)`. The complainant in IRC provided a good example of why this is irritating but I cannot remember myself right now.

**Comment by ahmadsalim** [comment]
@alercah This was as far as I understand a design decision to make it easier to work with tuple operations without doing a lot of duplication like Haskell does with some `op22` that only works on 22-tuples.

If you are interested in having an intensional difference between a 3-tuple and a 2-tuple which has a 2-tuple nested in it's right component, you can of course roll out your own `Tuple3` type or provide a custom record with fields that are named something semantically meaningful for your purpose.

**Comment by edwinb** [comment]
It may be irritating in some ways, but it's just as irritating in other ways not to. It's a syntactic convenience, and if you need the distinction you'd be better making a type that makes the distinction explicit.
