### ISSUE TITLE
Current package for mac os wrongly packaged

### ISSUE THREAD

**Issue by YaZko** [idris-lang/Idris-dev#3538]
Dear all,

The package distributed here for instance: https://github.com/idris-lang/Idris-dev/wiki/Idris-on-Mac-OS-X seems to be broken. 
Trying to compile, I obtain the following error:

> ld: library not found for -lidris_rts
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> FAILURE: "gcc" ["-O2","-fwrapv","-fno-strict-overflow","-DHAS_PTHREAD","-DIDRIS_ENABLE_STATS","-I.","/var/folders/xq/my2cmz3n26bf9sw4ryqk_cnh0000gn/T/idris1144108930470211272.c","-L/usr/local/share/x86_64-osx-ghc-7.10.3/idris-0.99/rts/","-lidris_rts","-lpthread","-I/usr/local/share/x86_64-osx-ghc-7.10.3/idris-0.99/rts/","-lm","-I.","-I/usr/local/share/x86_64-osx-ghc-7.10.3/idris-0.99/libs/prelude","-I/usr/local/share/x86_64-osx-ghc-7.10.3/idris-0.99/libs/base","-I.","-I/Users/edwin/.cabal/share/x86_64-osx-ghc-7.10.3/idris-0.99/libs/prelude","-I/Users/edwin/.cabal/share/x86_64-osx-ghc-7.10.3/idris-0.99/libs/base","-o","hello"]
> 

References to an "edwin" user are out of place. 
Installing the (older) package currently distributed on brew works perfectly.

Best,
Yannick

**Comment by ahmadsalim** [comment]
Thank you for the report, I am glad you got it working with Homebrew.
We will investigate as soon as possible; I actually plan to look at automating the packaging from CI services soon, so maybe that could help as well.

**Comment by edwinb** [comment]
Oh, I shouldn't have linked this because 0.99 isn't ready yet. Having said that, I think there's been a problem with the Mac binary package for a while (most likely since I upgraded to El Capitan). None of this would explain where the references to my local user came from though. Anyway - @jfdm has been tweaking the script, and so hopefully it'll work when I upload the new release shortly.

**Comment by edwinb** [comment]
I've uploaded a new version, which should have the paths correct - I've successfully installed it locally.

**Comment by YaZko** [comment]
Dear Edwin,
I actually had not made the link between the user name and yourself, despite jumping in from your book :) At any rate, thank you for the updated link. I just gave it a shot, it worked perfectly.
Thanks again,
Best,
Yannick
