### ISSUE TITLE
safe == 0.3.9

### ISSUE THREAD

**Issue by juhp** [idris-lang/Idris-dev#3543]
I didn't understand change aa91025 well.

Would `safe >= 0.3.9` not work equally well?

It looks like if this was done then latest idris might build in Stackage Nightly again.

**Comment by jfdm** [comment]
From what I can remember, I did originally try using `safe>=0.3.9` but ran into problems. However, I am unsure at the moment. I will look into it later.

**Comment by jfdm** [comment]
@juhp As an update, There is a problem in using `safe>=0.3.9` when compiling with the earliest version of GHC and Cabal in our build matrix: See #3549 for more information. Fortunately, Idris builds with every other version in the build matrix.

I am unsure why cabal and ghc are not playing well together for that particular build. I have an inkling that the wrong version of cabal is being used but I could be wrong. Unfortunately, I don't know how to fix, and will investigate later. If you have any thoughts please do contribute.

**Comment by juhp** [comment]
Perhaps it could be made conditional on the ghc version?

**Comment by juhp** [comment]
Thanks
