### ISSUE TITLE
idris-0.99: /usr/share/idris-0.99/idrisdoc/styles.css: copyFile: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by juhp** [idris-lang/Idris-dev#3544]
I tried to build idris-0.99 for Fedora:

```
:
Installing 00prelude-idx.ibc to /builddir/build/BUILDROOT/idris-0.99-1.fc26.x86_64/usr/share/idris-0.99/libs/prelude
../../dist/build/idris/idris --installdoc prelude.ipkg
Attempting to install IdrisDocs for prelude in: /builddir/build/BUILDROOT/idris-0.99-1.fc26.x86_64/usr/share/idris-0.99/docs/prelude
/usr/share/idris-0.99/idrisdoc/styles.css: copyFile: does not exist (No such file or directory)
make[1]: *** [Makefile:9: install] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/idris-0.99/libs/prelude'
make: Leaving directory '/builddir/build/BUILD/idris-0.99/libs'
make: *** [Makefile:10: install] Error 2
```

Full buildlog at https://copr-be.cloud.fedoraproject.org/results/petersen/idris/fedora-26-x86_64/00484508-idris/build.log.gz

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue.
Which method are you using to build Idris for Fedora?

**Comment by juhp** [comment]
I think the build details are in the buildlog, but if needed I can copy and paste the command sequence here.

**Comment by felixonmars** [comment]
Same here for Arch. I have tried different combination of commands and all resulted in the same failure.

**Comment by jfdm** [comment]
Right, After looking at the code, I think I know what is happening here.

It *could* be that IdrisDoc is expecting the css file to be somewhere else than where it actually is. How this hasn't cropped up before now is beyond me. I shall look into it.

**Comment by jfdm** [comment]
@juhp and @felixonmars 

I have created a PR #3550, that should hopefully address the issue. If it is possible that you can test this PR locally that would be great. I am not sure how to reproduce the fault here.

**Comment by felixonmars** [comment]
This fixes the problem here, and the build went on well. Thanks a lot!

**Comment by jfdm** [comment]
That is good to hear!

**Comment by juhp** [comment]
Fixed the problem for me too, thanks!!
