### ISSUE TITLE
Data.String.View are not exporting functions

### ISSUE THREAD

**Issue by Termina1** [idris-lang/Idris-dev#3545]
It seems that there should be:
```idris
%access public export
```
in https://github.com/idris-lang/Idris-dev/blob/master/libs/base/Data/String/Views.idr.

Otherwise I'm not sure how to use it. Also, why is there assert_total, just curious?

**Comment by xekoukou** [comment]
You are right. It needs ```public export```.

If one removes ```assert_total``` , the totality checker will probably complain. But one can change that function in a way that it does not.

Idris cannot understand that ```xs``` is smaller than ```x```.

**Comment by ahmadsalim** [comment]
You are welcome to add it and contribute a PR!

**Comment by Termina1** [comment]
@ahmadsalim thanks, done!

**Comment by ahmadsalim** [comment]
@Termina1 Thanks!
