### ISSUE TITLE
install via cabal likely to break packages

### ISSUE THREAD

**Issue by libeako** [idris-lang/Idris-dev#3546]
Trying to install idris-0.99 on my debian 8 ["jessie"] stable :
Cabal says:

```
regex-base-0.93.2 (reinstall) changes: mtl-2.1.2 -> 2.2.1
cabal: The following packages are likely to be broken by the reinstalls:
regex-posix-0.95.2
regex-compat-0.95.1
Use --force-reinstalls if you want to install anyway.
```

I have installed all OS packages mentioned by the page
https://github.com/idris-lang/Idris-dev/wiki/Idris-on-Debian

I even reinstalled the whole haskell-platform, but the problem still exists.

**Comment by xekoukou** [comment]
Stack seems to work well ,though, with debian jesie and with minor modifications with debian testing.

**Comment by jfdm** [comment]
Hi, @libeako thanks for the issue report.

It looks like we need to tweak the bounds for some dependencies for the release on Hackage. Although @xekoukou does mention stack as an alternative installation method, it would also be nice to have people use `cabal install idris`, as that is the advertised way to obtain Idris, and not run into problems.

**Comment by jfdm** [comment]
@libeako Whilst I remember, cabal has some flags that might be helpful in the meantime:

```
--reinstall                      Install even if it means installing the same version again.
--avoid-reinstalls         Do not select versions that would destructively overwrite installed packages.
--force-reinstalls         Reinstall packages even if they will most likely break other installed packages.
--upgrade-dependencies           Pick the latest version for all dependencies, rather than trying to pick an installed version.
```

It might be the case that some packages are not uptodate, if you *first* try: `cabal update` and then `cabal install idris`. If not, it might be good to try ``--upgrade-dependendencies``.

**Comment by libeako** [comment]
@jfdm, thank you. Indeed : 
using cabal flag "--avoid-reinstalls" the installation succeeds without warning message.

**Comment by jfdm** [comment]
@libeako Glad to hear that you were successful in getting idris installed. 

Given that the 'problem' can be resolved entirely through cabal, I am going to close this issue. The bounds we have work, but may require a cabal flag. 

Happy Hacking!

**Comment by jfdm** [comment]
As an addendum, i've updated the unofficial FAQs and the notes on the wiki for installing.
