### ISSUE TITLE
leading | in data type definition

### ISSUE THREAD

**Issue by libeako** [idris-lang/Idris-dev#3555]
Please extend the simple syntax of data type definition with the possibility of "|" before the first case.

I want to be able to write
```
data Color =
	| Red
	| Green
	| Blue
```

Currently 
```
data Color =
	  Red
	| Green
	| Blue
```
```
data Color 
	= Red
	| Green
	| Blue
```
are some formatting choices, but anyway there is some asymmetry between the case-members. This makes the code somewhat unpleasant to read because the code look suggests something false [that the first case is exceptional]. And also somewhat more problematic to edit [for example to change order of cases].

What i ask is used in coq, f#, f*.

**Comment by jfdm** [comment]
Hi @libeako;

As we are [heading to v1.0 of Idris](http://www.idris-lang.org/towards-version-1-0/) various parts of the language are being considered stable, and not subject to change. This includes the 'simple' syntax associated with the definition of non-dependent types. 

I believe that this syntax has been considered stable for a while now, and as such it is highly unlikely that we will change it. Further, the syntax is also seen in Haskell.

I'm sorry if this doesn't sit with you, it is hard to appease everyone.

Jan

**Comment by libeako** [comment]
Just in case i was misunderstood : i meant the leading "|" to be optional.

**Comment by jfdm** [comment]
Hi @libeako;

I understood what you meant. Unfortunatly, the answer is still the same. 

Jan
