### ISSUE TITLE
Idris 0.99: incorrect cast of Nat

### ISSUE THREAD

**Issue by bach741974** [idris-lang/Idris-dev#3558]
Hello
Idris 0.99:
Idris> the Integer $ cast $ length "Hello!"
6 : Integer
Idris> the Integer $ cast $ length "Hello!" - 3
3 : Integer
Idris> the Integer $ cast $ length "Hello!" - 30
(input):1:38-39:When checking argument smaller to function Prelude.Nat.-:
        Can't find a value of type
                LTE 30 6

I suppose it is a bug

Thanks

**Comment by ahmadsalim** [comment]
@bach741974 Next time, please use the mailing list or IRC before submitting a bug report. Thanks
