### ISSUE TITLE
ipkg files should allow comments

### ISSUE THREAD

**Issue by justjoheinz** [idris-lang/Idris-dev#3559]
The ipkg file parser should allow for single line comments, e.g.

```
package somepackage

# if you require packages to load add them here as a comma seperated list
# pkgs = 

modules = MyModule
        , MyModule.Impl
```

should be a valid ipkg file. In my opinion that would help to create more human readable package files. Currently the implementation in `Idris.Package.Parser` is lacking such a functionality.

**Comment by jfdm** [comment]
Hi @justjoheinz;

As far as i am aware, the IPKG files can have haskell/idris style single and multi line comments. The only difference is that the ipkg file must start with package.

**Comment by justjoheinz** [comment]
This is correct. Sorry, I missed that reading the source.
For future reference `--` and `{- ... -}` work.
