### ISSUE TITLE
Idris 0.99 hangs indefinitely during typecheck

### ISSUE THREAD

**Issue by Termina1** [idris-lang/Idris-dev#3566]
I'm trying to typecheck this file:
https://gist.github.com/Termina1/139f90d4b7f587208e57d467da4b5f8a

But it never stops.

I'm running OS X
```
Model Name:	MacBook Pro
Model Identifier:	MacBookPro12,1
Processor Name:	Intel Core i5
Processor Speed:	2,7 GHz
Number of Processors:	1
Total Number of Cores:	2

System Version: OS X 10.11.6 (15G31)
Kernel Version: Darwin 15.6.0
```

**Comment by ahmadsalim** [comment]
@Termina1 It seems to me that type checking things with Bits is taking a long time, even for simpler programs. It may just be the case that it is taking too much time rather than hanging.

In any case, I still would consider this an issue, thanks for reporting.

**Comment by Termina1** [comment]
@ahmadsalim also, I forgot to add, that version 0.12.3 typechecks this in few seconds.

**Comment by Termina1** [comment]
I spent some time with git bisect and it seems this commit is a source of problem.
d0671a3c3b901ab6d5131405df0639844adfb1bf

**Comment by jfdm** [comment]
This looks familiar. Have you tried against Idris head?

**Comment by Termina1** [comment]
@jfdm tried with 0.99-git:0ceaa30, and this is still an issue

**Comment by anton-trunov** [comment]
Also, 59577e6c takes around 5 sec to typecheck on my machine with
```
time idris --check <filename>
```
At 97319d9f7edb1ab075b8cc2940678115cf15ff57 typechecking time doubles (10 sec), and at d0671a3c3b901ab6d5131405df0639844adfb1bf I didn't wait until the end, however, typechecking  takes at least 10 times longer.

**Comment by edwinb** [comment]
I think I'm going to revert to normal form rather than weak head normal form during type checking, because it causes way more problems than it solves. In particular, it often leads to rather larger intermediate expressions than are useful, like in this case.
