### ISSUE TITLE
Documentation on main site broken

### ISSUE THREAD

**Issue by GetContented** [idris-lang/Idris-dev#3569]
There are several links to prelude, base, contrib, etc on the main documentation site that are broken links. Trying to find out what functions and types are included in these packages is difficult for beginners.

http://www.idris-lang.org/documentation/

for example: http://www.idris-lang.org/docs/current/base_doc/

Are these installed with idris?

**Comment by jfdm** [comment]
@GetContented as of Idris v0.99 the documentation is installed with Idris. Please see the contents of `idris --docdir` for the same documents.Also there are built in search tools within the Idris compiler, for [which information is available](https://github.com/idris-lang/Idris-dev/wiki/Unofficial-FAQ#is-there-some-documentation-for-the-standard-lib-list-of-functions).

 Unfortunately, when we release dead links may occur unintentionally. Sorry for that.

**Comment by GetContented** [comment]
It's fine. I just wanted to let you know as it's not the best if the docs can't be found on the official website :)

Thanks, though! that caused me to realise I hadn't updated since 0.10.something ! :) (because `--docdir` didn't exist). I can close this if you'd like, but maybe it should stay open until we've updated the website? Can I help?

**Comment by ahmadsalim** [comment]
It seems to work now.
