### ISSUE TITLE
Distributing idris for `guixsd`

### ISSUE THREAD

**Issue by dvc94ch** [idris-lang/Idris-dev#3573]
Hi,

While updating the idris package for the guixsd distribution I noticed a couple of things that could be improved to help packaging idris and idris modules.

`IDRIS_LIBRARY_PATH` only accepts a single path instead of a colon separated list. I think this would help packaging nixos too.

I think that the location of the idris standard libraries is `/share/x86_64-linux-ghc-7.10.2/idris-0.12.3` by default. It would be nice to be able to overwrite this, since guix/nix already take care of making sure that the idris modules are built using the right ghc/idris versions, by setting the correct `IDRIS_LIBRARY_PATH`. Having them in /share/idris makes it easy to have guix set the search path automatically by adding something like this to the idris package definition.
```scheme
(native-search-paths
   (list (search-path-specification
           (variable "IDRIS_LIBRARY_PATH")
           (files '("share/idris")))))
```

If I understand correctly the tests currently run on the installed idris binary and not on the one that was just built. Running `runhaskell Setup.hs test` after `runhaskell Setup.hs` build fails to find idris.

**Comment by jfdm** [comment]
Hi @dvc94ch 

`IDRIS_LIBRARY_PATH` is used to point to the single directory where Idris packages are installed to. At the moment, Idris does not support having multiple directories on that path.

How Idris is installed can be customised using cabal. Please see `mkpkg.sh` script in Idris' source folder for an example, and read cabal's documentation for more information. This is the best approach when looking to change default locations.

If you run the tests using cabal then the version of Idris used is the one that was just built. Same goes if you use stack to build Idris.

Hope this helps.

**Comment by allancto** [comment]
@jfdm, editing the "download" instructions for ubuntu to include stack might be useful, right now afaik they refer only to cabal but not stack, which might be helpful to a new generation of hs folks who use stack but not cabal directly. 

Thanks!

**Comment by jfdm** [comment]
@allancto

Thanks for the suggestions. 

However, as building Idris with stack is in a quasi-official-unofficial state, I am (personally) tempted to shy away from updating the documentation in the Idris wiki to include stack for general Idris installation. Although, I am aware that stack can be used to install idris globally, stack is more of a tool for developing Haskell packages and not their installation.

On a more practical point, as I only have access to Mac OS X, I don't really want to update instructions that I cannot reasonably test. If you are in a position to update the Wiki docs please feel free to do so.

**Comment by dvc94ch** [comment]
Hi @jfdm 

I think that IDRIS_LIBRARY_PATH taking a colon separated list is necessary as other distros are hacking around this too. I'll try to submit a patch for this.
https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/idris-modules#with-packages

Changing the installation location of the stdlib is relatively straightforward, I can patch this on the distro end, I just thought I'd mention it.
https://github.com/idris-lang/Idris-dev/blob/master/Setup.hs#L257

When I run `cabal test` I get this error message:
```sh
run: line 4: idris: command not found
```
To get it to run the tests I have to do this:
```sh
export PATH=PATH:$PWD/dist/build/idris
export IDRIS_LIBRARY_PATH=$PWD/libs
export LIBRARY_PATH=$PWD/rts
export C_INCLUDE_PATH=$PWD/rts
```
and then I get a bunch of these
```sh
run: line 3: ./totality004: No such file or directory
```
which I haven't figured out how to get around yet.

But maybe I'm doing something wrong?

**Comment by jfdm** [comment]
@dvc94ch I suggest looking at the contents of Idris' Makefile, as we use that to build and test Idris on Travis. This will show how we use cabal to build and runs tests.

As for the environment variables. Some are useful for overriding Idris' defaults once Idris is installed (e.g. `IDRIS_LIBRARY_PATH`), and some are useful for helping with the installation---`TARGET`. When installing Idris for testing, you don't technically need to change the environment variable: Doing it all via cabal is sufficient and, in my opinion, preferable.

**Comment by dvc94ch** [comment]
Ah I forgot to mention that the tests worked with idris 0.9.19.1. I assume a lot has changed since then, it's the update to 0.12.3 that broke the test suite. I'll see if I can narrow down the commit that caused this.

**Comment by allancto** [comment]
@jfdm, i apologize for not volunteering about stack, i agree with the comment that stack isn't designed for distributing binaries, and I have a confession to make I've been using Idris on windows (works great) and only just was thinking of installing it on a second (linux mint) machine BUT I'm no expert on Linux distribution, probably someone should volunteer who is a Linux hacker :p

**Comment by allancto** [comment]
again, I'm not primarily Linux, but it seems as though stack is also having its own Linux distribution issues. Is there a chief Linux hacker who is up on this? 
reddit.com/r/haskell/comments/5i9yv1/release_v130_commercialhaskellstack_github/db7ga3y/ reddit.com/r/haskell/comments/5i9yv1/release_v130_commercialhaskellstack_github/db7ywzk/

**Comment by jfdm** [comment]
@dvc94ch I believe that the tests do work in a custom cabal sandbox. A user who builds Fedora packages is successfully building and testing Idris. They use cabal to ensure Idris is installed correctly for Fedora. It *could be* that the problems you are experiencing with Idris on nixos or guix could be the result of them *incorrectly* installing Idris; they *could be* hacking their build system when they do not need to be.

There was also a test suite in 0.9.19.1 but it was not integrated into cabal.

**Comment by dvc94ch** [comment]
@jfdm Thanks! I've disabled the tests for now.

**Comment by LeifW** [comment]
As far as controlling where Idris's libraries get installed to, there's the cabal options `--prefix`, and also `--datasubdir`. The Idris package for Arch Linux sets those to `/usr` and `idris`, respectively, so Idris libs for that package get installed to `/usr/share/idris`. https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/idris#n39
@felixonmars (the maintainer of that package and tons more Haskell packages on Arch) would know more.

**Comment by jfdm** [comment]
@dvc94ch Just to point out as well, Idris does have a series of command line flags to be used at runtime to add additional search paths for idris libraries. Please see `-i <path>` `--idrispath <path>` for adding additional `.ibc` to idris search path, and `--sourcepath <path>` for adding additional sources. I cannot remember of the top of my head if `-i` negates the use of package specification.

**Comment by dvc94ch** [comment]
The workflow I'm aiming for is the following:

```sh
guix environment --ad-hoc idris idris-lightyear idris-wl-pprint
idris
:module Lightyear
```

Preferably without adding a wrapper around idris that parses an env variable to prefix cli flags. I'm not sure yet when exactly the -p flag is needed.

I haven't used idris since January last year so I have to refresh my memory on the details. Packaging new languages and module support for guix can be a pain sometimes, but I think it's well worth it once it works...
