### ISSUE TITLE
Idris 0.99 on OS X 10.6.8

### ISSUE THREAD

**Issue by berndlosert** [idris-lang/Idris-dev#3578]
I installed Idris today using the OS X idris-current.pkg installer on my old MacBook running OS X 10.6.8 (Snow Leopard) and it worked fine. However, when I run `idris` from the Terminal, it dies saying `segmatation fault` or `Illegal instruction`. I assume this is because my OS X version is too old. If this is the case though, why does the pkg installer let me install it?

**Comment by jfdm** [comment]
@berndlosert Sorry for not getting back to you earlier. 

While we know a thing or two about dependent types, distributing Idris is another matter entirely. Not specifying the OS X version is an oversight on our part. Although, I am not experienced in building installers for mac os x, I am sure there [is a way to do so](http://thegreyblog.blogspot.co.uk/2014/06/os-x-creating-packages-from-command_2.html).

In the meantime, if you install Idris using cabal (or stack) it will build from source, and *should work* on Snow Leopard.

**Comment by LeifW** [comment]
So based on that link, sounds like we could use the `productbuild` command on the package we create with `packagebuild` to make a fancier-looking package that specifies the minimum OS version? And maybe it'd even have uninstall functionality? (the current "uninstall" is just to delete the directory with idris in it)
https://github.com/idris-lang/Idris-dev/blob/master/mkpkg.sh#L61

**Comment by ahmadsalim** [comment]
I will close the issue since no one complained on newer versions of Idris, and 0.98 seems to be an old version.
