### ISSUE TITLE
problem installing 0.99 : styles.css: copyFile: does not exist

### ISSUE THREAD

**Issue by mpkh** [idris-lang/Idris-dev#3579]
`copyFile` should respect `DESTDIR` (`/var/tmp/portage/dev-lang/idris-0.99/image`)

```
Installing 00prelude-idx.ibc to /var/tmp/portage/dev-lang/idris-0.99/image/usr/share/idris-0.99/ghc-8.0.1/libs/prelude
../../dist/build/idris/idris --installdoc prelude.ipkg
Attempting to install IdrisDocs for prelude in: /var/tmp/portage/dev-lang/idris-0.99/image/usr/share/idris-0.99/ghc-8.0.1/docs/prelude
/usr/share/idris-0.99/ghc-8.0.1/idrisdoc/styles.css: copyFile: does not exist (No such file or directory)
```

**Comment by jfdm** [comment]
Hi @mpkh;

Apologies about the problem you have experienced. 

We are aware of the problem and it has been fixed upstream---see #3550. I will liaise with @edwinb about pushing a new 'hot fix' release with the changes. 

Jan

**Comment by mpkh** [comment]
@jfdm thank you, please don't edit current release, make 0.99.1 or alike, editing published sources is not very good idea, specially if I will put provided patch as workaround.

**Comment by jfdm** [comment]
@mpkh Thanks for the comments. Part of Idris' release strategy is to respect PVP and releases are never 'edited', and version numbers are always incremented. I used the term 'hot fix' to recognise that any new release will be brought about to fix something.

**Comment by mpkh** [comment]
@jfdm I've tested that provided commit helps https://github.com/gentoo-haskell/gentoo-haskell/commit/05d8822df181fe46b684c2a5490e1538822f10b5
feel free to close this issue.

**Comment by jfdm** [comment]
Thanks @mpkh I was going to close this issue regardless, as it was fixed upstream.
