### ISSUE TITLE
Incorrect implementation of div and mod

### ISSUE THREAD

**Issue by dalcde** [idris-lang/Idris-dev#3592]
The functions `div` and `mod` of `Integer` (and `Int` etc.) do not satisfy

    (div a b) * b + (mod a b) = a

since in the backend, the Haskell function `div` is used for `div` while `rem` is used for `mod`, where in fact `div` should be paired with `mod` and `quot` should be paired with `rem` for the above equation to hold.

This causes issues when implementing, say, the Euclidean algorithm.

**Comment by Melvar** [comment]
I checked the C backend, which turns out to also use mismatched functions, `mpz_tdiv_q` vs. `mpz_mod`.
`mpz_tdiv_q` rounds the quotient towards zero, so the corresponding remainder should have the same sign as the dividend. `mpz_mod` instead always produces a nonnegative result.

**Comment by dalcde** [comment]
Any pointers to how one can go about fixing this?

**Comment by ahmadsalim** [comment]
@dalcde Change the C backend to use the matching functions :)

**Comment by dalcde** [comment]
What would be the relevant pieces of code?

**Comment by ahmadsalim** [comment]
@dalcde I would guess having `mpz_tdiv_q` and `mpz_tdiv_r`, but I am unsure.

**Comment by dalcde** [comment]
Does the Haskell backend have to be changed as well?

**Comment by ahmadsalim** [comment]
@dalcde You mean the Haskell code? I would guess not.

**Comment by Melvar** [comment]
Well of course it does, the original issue is that the evaluator is wrong, I just noted that the C runtime is *also* wrong, not that it is the only wrong one.

**Comment by ahmadsalim** [comment]
@Melvar Ah, I missed that, thanks. Yeah, then both should be changed.

**Comment by Melvar** [comment]
[Place of unsigned prims in evaluator](https://github.com/idris-lang/Idris-dev/tree/823d5d7cf19b0e4de9faa1b867abbd8b2dc8faa5/src/Idris/Primitives.hs#L213-L216), [place with signed prims in evaluator](https://github.com/idris-lang/Idris-dev/tree/823d5d7cf19b0e4de9faa1b867abbd8b2dc8faa5/src/Idris/Primitives.hs#L313-L339). [Impl for `Integer` in the C rts](https://github.com/idris-lang/Idris-dev/tree/823d5d7cf19b0e4de9faa1b867abbd8b2dc8faa5/rts/idris_gmp.c#L178-L202). If you want to check the rest, [impl for `BitsN` in the C rts (just uses C `/ %`)](https://github.com/idris-lang/Idris-dev/tree/823d5d7cf19b0e4de9faa1b867abbd8b2dc8faa5/rts/idris_bitstring.c), [impl for `Int` in the C backend (likewise)](https://github.com/idris-lang/Idris-dev/tree/823d5d7cf19b0e4de9faa1b867abbd8b2dc8faa5/src/IRTS/CodegenC.hs#L426-L429).

jsbn is confusing but the JS backend code is [here for `Integer`](https://github.com/idris-lang/Idris-dev/blob/823d5d7cf19b0e4de9faa1b867abbd8b2dc8faa5/src/IRTS/CodegenJavaScript.hs#L716-L719), [here for `BitsN`](https://github.com/idris-lang/Idris-dev/blob/823d5d7cf19b0e4de9faa1b867abbd8b2dc8faa5/src/IRTS/CodegenJavaScript.hs#L956-L1041) (unsigned remainder seems to be missing), [here for `Int`](https://github.com/idris-lang/Idris-dev/blob/823d5d7cf19b0e4de9faa1b867abbd8b2dc8faa5/src/IRTS/CodegenJavaScript.hs#L1064-L1067), and jsbn itself is [here](https://github.com/idris-lang/Idris-dev/blob/823d5d7cf19b0e4de9faa1b867abbd8b2dc8faa5/jsrts/jsbn/jsbn.js).

**Comment by dalcde** [comment]
I suppose it would be a good idea to leave the internal, say, `bsrem` intact, and produce a new function bsmod that is to be used for the mod operator?
