### ISSUE TITLE
The Pruviloj.Induction.induction error message could be improved

### ISSUE THREAD

**Issue by yurrriq** [idris-lang/Idris-dev#3594]
When I make this typo:

```idris
mapPreservesLen : (f : a -> b) -> (l : List a) ->
                  length (map f l) = length l
mapPreservesLen = %runElab mush
```

*[Specifically, I forgot to include `f` on the left-hand side.]*

I get the [somewhat cryptic error message](https://github.com/idris-lang/Idris-dev/blob/v0.99/libs/pruviloj/Pruviloj/Induction.idr#L135):

```
When checking right hand side of mapPreservesLen with expected type
        (f : a -> b) -> (l : List a) -> length (map f l) = length l

a -> b is not an inductive family
```

`f` needs to be on the left-hand side so we do induction on `l`, which, unlike `f`, **is** an *inductive family*:

```idris
mapPreservesLen f = %runElab mush
```

**Comment by yurrriq** [comment]
> [Consider] prefix[ing the error message] with a `NamePart` referring to the function so it gets colored and is clickable in interfaces that make names clickable.

**Comment by david-christiansen** [comment]
Isn't `mapPreservesLen` already highlighted and clickable in that message?

I'm all for better messages, though. At the very least, "inductive family" can be replaced with "a datatype declared with the data keyword"

**Comment by yurrriq** [comment]
> Isn't `mapPreservesLen` already highlighted and clickable in that message?

For me it's not highlighted (`List`, `length` and `map` are), but it is indeed clickable.

:+1: for "a datatype declared with the data keyword"

**Comment by david-christiansen** [comment]
Right, it's not highlighted because the highlighting is based on it having defined the function, and the function does not yet exist when it makes that message :-) It would be nice to figure out a model where that doesn't happen.
