### ISSUE TITLE
Incorrect typing of instance method when using named parent instances

### ISSUE THREAD

**Issue by atacratic** [idris-lang/Idris-dev#3616]
I'm trying to define a named implementation which has two named parent implementations, with the new experimental "using" syntax (from https://github.com/idris-lang/Idris-dev/commit/254a227307830016a4cf277ab9866395fe155893).  But the expected type of the methods is coming out wrong (I think).

The problem is in the last line of the code below, in the implementation of MultNatMonoidV.  The compiler reckons the expected type of the hole (?h3) involves plus and 0, but I think it should be mult and 1.

(If I can get round this I'd like to add implementations for VerifiedMonoid and the like, for Nat and Data.ZZ, into libs/contrib/Interfaces/Verified.idr - any comments on the work in progress here https://github.com/idris-lang/Idris-dev/compare/master...atacratic:NatZZVerifiedImpls?expand=1 would be welcome.)

```
-- idris --noprelude --nobuiltins
module Main

import Prelude.Nat

infixl 6 <++>

interface Semigroup' ty where
  (<++>) : ty -> ty -> ty

interface Semigroup' ty => Monoid' ty where
  neutral' : ty

interface Semigroup' a => VerifiedSemigroup a where
  total semigroupOpIsAssociative' : (l, c, r : a) -> l <++> (c <++> r) = (l <++> c) <++> r

[MultNatSemi] Semigroup' Nat where
  (<++>) = mult

[MultNatMonoid] Monoid' Nat using MultNatSemi where
  neutral' = S Z

[MultNatSemiV] VerifiedSemigroup Nat using MultNatSemi where
  semigroupOpIsAssociative' = ?h1

interface (VerifiedSemigroup a, Monoid' a) => VerifiedMonoid a where
  total monoidNeutralIsNeutralL : (l : a) -> l <++> Main.neutral' = l
  total monoidNeutralIsNeutralR : (r : a) -> Main.neutral' <++> r = r

[MultNatMonoidV] VerifiedMonoid Nat using MultNatSemiV, MultNatMonoid where
  monoidNeutralIsNeutralL = ?h2
  monoidNeutralIsNeutralR = ?h3 -- ":t h3" returns "(r : Nat) -> plus r 0 = r" but it should be "(r : Nat) -> mult r 1 = r"

```

**Comment by Melvar** [comment]
No, what comes from your definition of `VerifiedMonoid` is `mult 1 r = r`, not `mult r 1 = r`. Then, by the definition of `mult`, `mult 1 r` immediately reduces to `plus r (mult 0 r)` which reduces to `plus r 0`, which is what you see.

**Comment by atacratic** [comment]
Ha - thanks!

My actual problem was that my branch https://github.com/atacratic/Idris-dev/tree/NatZZVerifiedImpls2 isn't building.  See https://github.com/atacratic/Idris-dev/blob/NatZZVerifiedImpls2/libs/contrib/Interfaces/Verified.idr#L80 where the compile fails as follows.

```
Type checking .\Idris-dev/libs/contrib/Interfaces/Verified.idr
.\Idris-dev/libs/contrib/Interfaces/Verified.idr:80:1:
When checking right hand side of Interfaces.Verified.MultNatMonoidV with expected type
        VerifiedMonoid Nat

Type mismatch between
        (<+>) {{Nat implementation of Prelude.Algebra.Semigroup}}
              neutral
              meth =
        meth (Type of Interfaces.Verified.MultNatMonoidV, method monoidNeutralIsNeutralR meth)
and
        (<+>) {{constructor of Interfaces.Verified.VerifiedSemigroup#Semigroup a}}
              neutral
              meth =
        meth (Expected type)

Specifically:
        Type mismatch between
                S meth
        and
                neutral <+> meth
```

Would love a clue about that one?

**Comment by edwinb** [comment]
So is it the case that the initially reported issue is expected behaviour, and there is a different problem? If so, it'd be better to close this and open a new issue, ideally with a minimal failing example.

**Comment by atacratic** [comment]
Ah, in 0.99 it's working! :smile:
