### ISSUE TITLE
Strange behavior of totality checker

### ISSUE THREAD

**Issue by rodrigogribeiro** [idris-lang/Idris-dev#3621]
I've developed a certified regex string matching algorithm based on derivatives in Idris. 
The totality checker of Idris 0.99 is complaining about the following theorem

    derivComplete : InRegExp (x :: xs) e -> InRegExp xs (deriv e x)
    derivComplete {e = Zero}{xs = xs}{x = x} pr = void (inZeroInv pr)
    derivComplete {e = Eps}{xs = xs}{x = x} pr with (inEpsInv pr)
     derivComplete {e = Eps}{xs = xs}{x = x} pr | eq = void (lemma_val_not_nil eq)
     derivComplete {e = (Chr y)}{xs = xs}{x = x} pr with (decEq y x)
       derivComplete {e = (Chr x)}{xs = []}{x = x} InChr | (Yes Refl) = InEps
       derivComplete {e = (Chr x)}{xs = []}{x = x} InChr | (No contra) = void (contra Refl)
     derivComplete {e = (Cat y z)}{xs = xs}{x = x} pr with (hasEmptyDec y)
       derivComplete {e = (Cat y z)}{xs = xs}{x = x} (InCat {xs = []} w s Refl) | (Yes prf)
         = altOptComplete (deriv y x .@. z) (deriv z x) xs (InAltR (derivComplete s))
       derivComplete {e = (Cat y z)}{xs = ys ++ ys1}{x = x} (InCat {xs = (x :: ys)}{ys = ys1} w s Refl)
         | (Yes prf)
           = altOptComplete (deriv y x .@. z) (deriv z x) _
                            (InAltL (catOptComplete (deriv y x) z (ys ++ ys1)
                                     (InCat (derivComplete w) s Refl)))
       derivComplete {e = (Cat y z)}{xs = xs}{x = x} (InCat {xs = []} w s eq) | (No contra)
           = void (contra w)
       derivComplete {e = (Cat y z)}{xs = ys ++ ys1}{x = x} (InCat {xs = (x :: ys)}{ys = ys1} w s Refl)
         | (No contra)
           = catOptComplete (deriv y x) z (ys ++ ys1) (InCat (derivComplete w) s Refl)
     derivComplete {e = (Alt e e')}{xs = xs}{x = x} (InAltL y)
       = altOptComplete (deriv e x) (deriv e' x) xs (InAltL (derivComplete y))
     derivComplete {e = (Alt e e')}{xs = xs}{x = x} (InAltR y)
       = altOptComplete (deriv e x) (deriv e' x) xs (InAltR (derivComplete y))
     derivComplete {e = (Star y)}{xs = xs}{x = x} (InStar (InAltL z))
       = void (lemma_val_not_nil (inEpsInv z))
     derivComplete {e = (Star y)}{xs = xs}{x = x} (InStar (InAltR (InCat {xs = []} z w Refl)))
       = derivComplete w
     derivComplete {e = (Star y)}{xs = ys ++ ys1}{x = x} (InStar (InAltR (InCat {xs = (x :: ys)}{ys = ys1} z w Refl)))
       = catOptComplete (deriv y x) (Star y) (ys ++ ys1) (InCat (derivComplete z) w Refl)

which is marked as partial due to a `with` block. I've retried to prove it again using the interactive emacs mode but before finishing all holes, Idris complains that are missing cases. At least to me, this seems total. Am I missing something? Is that possible that totality checker could return more informative error messages to ease the debugging of such proofs?

Complete code including the problematic theorem is available in this [repository](https://github.com/rodrigogribeiro/idrisregexp) . I've used Idris 0.9.19.

**Comment by ahmadsalim** [comment]
@rodrigogribeiro What does `:missing` in the interactive shell tell you?

**Comment by rodrigogribeiro** [comment]
@ahmadsalim : I've used missing and added the missing (impossible) case. But now is complaining that the `derivComplete` theorem isn't complete due to a with block. Is there any command for helping debugging this on interactive shell, like `:missing`?

**Comment by ahmadsalim** [comment]
@rodrigogribeiro Could you paste the error and the updated code, please?

**Comment by rodrigogribeiro** [comment]
@ahmadsalim : Again, thanks for answering! The error message is:

     Teste.idr line 283 col 0:
         Teste.derivComplete is possibly not total due to: with block in Teste.derivComplete

And the offending function is pasted below. 

     derivComplete : InRegExp (x :: xs) e -> InRegExp xs (deriv e x) 
     derivComplete {e = Zero}{xs = xs}{x = x} pr = void (inZeroInv pr)
     derivComplete {e = Eps}{xs = xs}{x = x} pr with (inEpsInv pr)
       derivComplete {e = Eps}{xs = xs}{x = x} pr | eq = void (lemma_val_not_nil eq)
     derivComplete {e = (Chr y)}{xs = xs}{x = x} pr with (decEq y x)
       derivComplete {e = (Chr x)}{xs = []}{x = x} InChr | (Yes Refl) = InEps
       derivComplete {e = (Chr x)}{xs = []}{x = x} InChr | (No contra) = void (contra Refl)
     derivComplete {e = (Cat y z)}{xs = xs}{x = x} pr with (hasEmptyDec y)
       derivComplete {e = (Cat y z)}{xs = xs}{x = x} (InCat {xs = []} w s Refl) | (Yes prf)
         = altOptComplete (deriv y x .@. z) (deriv z x) xs (InAltR (derivComplete s))
       derivComplete {e = (Cat y z)}{xs = ys ++ ys1}{x = x} (InCat {xs = (x :: ys)}{ys = ys1} w s Refl)
         | (Yes prf) 
           = altOptComplete (deriv y x .@. z) (deriv z x) _
                            (InAltL (catOptComplete (deriv y x) z (ys ++ ys1)
                                     (InCat (derivComplete w) s Refl)))
       derivComplete {e = (Cat y z)}{xs = xs}{x = x} (InCat {xs = []} w s eq) | (No contra)
           = void (contra w)
       derivComplete {e = (Cat y z)}{xs = ys ++ ys1}{x = x} (InCat {xs = (x :: ys)}{ys = ys1} w s Refl)
         | (No contra)
           = catOptComplete (deriv y x) z (ys ++ ys1) (InCat (derivComplete w) s Refl)
     derivComplete {e = (Alt e e')}{xs = xs}{x = x} (InAltL y)
       = altOptComplete (deriv e x) (deriv e' x) xs (InAltL (derivComplete y))
     derivComplete {e = (Alt e e')}{xs = xs}{x = x} (InAltR y)
       = altOptComplete (deriv e x) (deriv e' x) xs (InAltR (derivComplete y))
     derivComplete {e = Star _}{xs = _}{x = _}(InStar (InAltL InEps)) impossible
     derivComplete {e = Star e'}{xs = xs}{x = x}(InStar (InAltR (InCat {zs = x :: xs}{xs = []}{ys = x :: xs} y z Refl))) = derivComplete z
     derivComplete {e = Star e'}{xs = xs1 ++ ys1}{x = x}(InStar (InAltR (InCat {zs = (x :: (xs1 ++ ys1))}{xs = x :: xs1}{ys = ys1} y z Refl))) 
       = catOptComplete (deriv e' x) 
                        (star e') 
                        (xs1 ++ ys1) 
                        (InCat (derivComplete y) (starOptComplete _ _ z) Refl)
     derivComplete {e = Star _}{xs = _}{x = _}(InStar (InAltR (InCat {xs = []}{ys = []} _ _ Refl)))
       impossible

The missing equation detected by `:missing` is the last one. The complete working code that exhibit the error message is at the following
[gist](https://gist.github.com/rodrigogribeiro/9881be2f1a66f47454556e89db97ac2f).

**Comment by ahmadsalim** [comment]
@rodrigogribeiro Sure, no problem.

As far as I understand, there is currently no way to check missing for `with`-blocks. How did you perform the case splits: manually or using the editor support?

You could try to see if using the editor to split provides you more complete cases.

**Comment by ahmadsalim** [comment]
Btw

```idris
   derivComplete {e = (Cat y z)}{xs = xs}{x = x} (InCat {xs = []} w s Refl) | (Yes prf)
     = altOptComplete (deriv y x .@. z) (deriv z x) xs (InAltR (derivComplete s))
   derivComplete {e = (Cat y z)}{xs = ys ++ ys1}{x = x} (InCat {xs = (x :: ys)}{ys = ys1} w s Refl)
     | (Yes prf) 
       = altOptComplete (deriv y x .@. z) (deriv z x) _
                        (InAltL (catOptComplete (deriv y x) z (ys ++ ys1)
                                 (InCat (derivComplete w) s Refl)))
   derivComplete {e = (Cat y z)}{xs = xs}{x = x} (InCat {xs = []} w s eq) | (No contra)
       = void (contra w)
   derivComplete {e = (Cat y z)}{xs = ys ++ ys1}{x = x} (InCat {xs = (x :: ys)}{ys = ys1} w s Refl)
     | (No contra)
       = catOptComplete (deriv y x) z (ys ++ ys1) (InCat (derivComplete w) s Refl)
```
looks a bit suspicious for me, since it continues pattern matching after a `with`-block.

**Comment by rodrigogribeiro** [comment]
@ahmadsalim : I've implemented this using editor support for `case`-splits and the functionality for building`with` blocks. Originally, I've implemented this on Idris 0.9.19 and it worked without any problems. After updating to Idris 0.99, this function starts to shows these issues. 

BTW, I've managed to code the same in Agda and it worked. Does Idris uses a different approach for totality than Agda's?

**Comment by ahmadsalim** [comment]
@rodrigogribeiro There were some changes to the coverage checker in between.
I am not sure about the algorithmic implementations, but as far as I understand coverage checking is undecidable so different heurestics could probably be used.

In any case, could you kindly also provide the minimal amount of other code for this to run? It is unfortunately hard to check concretely what the issue is without.

**Comment by ahmadsalim** [comment]
I will close the issue, since there has been some inactivity.
However, if a more minimal case shows up, I will reopen the issue.
