### ISSUE TITLE
The type of (s1 : EQ = compare x y) does not appear to be EQ = compare x y!

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3623]
I would like to prove that
```
> compareLT : (x, y : Double) -> LT = compare x y -> So (x < y)
```
The plan is to first show that `LT = EQ` (and `LT = GT`) are not inhabited:
```
> Uninhabited (LT = EQ) where
>   uninhabited Refl impossible
```
and then do something like
```
> compareLT x y p with (compare x y) proof q
>   compareLT x y p | LT = Oh
>   compareLT x y p | EQ = absurd s2 where
>                       s1 : EQ = compare x y
>                       s1 = q
>                       s2 : LT = EQ
>                       s2 = trans p (sym s1)
>   compareLT x y p | GT = ?kiku
```
This fails with
```
     When checking an application of function sym:
             Type mismatch between
                     EQ =
                     compare x
                             y (Type of with block in Double.Postulates.compareLT, s1 x
                                                                                      y
                                                                                      p
                                                                                      q)
             and
                     EQ = EQ (Expected type)
             
             Specifically:
                     Type mismatch between
                             if intToBool (prim__eqFloat x y)
                               then EQ
                               else if intToBool (prim__sltFloat x y) then LT else GT
                     and
                             EQ
```
which is a bit surprising given that the types of `p` and `s1` are `LT = compare x y` and `EQ = compare x y`, respectively. Any idea what is going on here?

**Comment by ahmadsalim** [comment]
@nicolabotta Thanks for the question.

This is a correct type error, since `p` has type `LT = EQ` already and therefore `trans p (sym s1)` will get the type `LT = compare x y` which is not your target type (specifically `sym s1` has type `EQ = compare x y` but your target is `EQ = EQ`).

**Comment by nicolabotta** [comment]
@ahmadsalim I understand but if the type of `p` already reduces to `LT = EQ` why doesn't the type of `s1` already reduce to `EQ = EQ`? This behavior seems a bit inconsistent to me.

**Comment by ahmadsalim** [comment]
@nicolabotta Actually, what is happening is not that `compare x y` is reducing to `EQ` but rather the term is being substituted in the type of `p`, which is what `with`-clauses generally allow you. 

This in terms also means that new terms `compare x y` are not automatically substituted with `EQ` and so you get the mentioned type error.

**Comment by ahmadsalim** [comment]
@nicolabotta I will close this issue. I hope this is OK, thanks!

**Comment by nicolabotta** [comment]
@ahmadsalim Thanks Ahmad, closing the thread is fine, of course. Sorry for the late feedback!
