### ISSUE TITLE
Reusing Refl constructor leads to crash (Version 0.99, Mac OS)

### ISSUE THREAD

**Issue by MartinErwig** [idris-lang/Idris-dev#3625]
When I try to load a file that contains the following definition:

```idris
data E = Refl
```

The interpreter crashes with the following error message:

```
Type checking ./Tmp.idr
idris: buildSCG: (Refl,[CGInfo {calls = [=], allCalls = Nothing, scg = [], usedpos = []},CGInfo {calls = [Main.E], allCalls = Nothing, scg = [], usedpos = []}])
CallStack (from HasCallStack):
  error, called at src/Idris/Termination.hs:284:13 in idris-0.99-FHCzX0uWTXOLp5FRG0yExP:Idris.Termination
```

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue.
I am currently unsure on whether there is any other workaround than to avoid using the name `Refl`, but this should probably be fixed.

**Comment by edwinb** [comment]
Well that's embarrassing. I think it's due to 'Refl' being an unqualified name, part of the global namespace, but the manner in which it crashes is very odd. I'll take a look now, and at least make it fail in a less odd way.
