### ISSUE TITLE
Custom entry point for C backend, like WinMain

### ISSUE THREAD

**Issue by be5invis** [idris-lang/Idris-dev#3637]
The definition of win32 WinMain is:

```c
int CALLBACK WinMain(
  _In_ HINSTANCE hInstance,
  _In_ HINSTANCE hPrevInstance,
  _In_ LPSTR     lpCmdLine,
  _In_ int       nCmdShow
);
```

which could be mapped into something like

```idris
winMain : Ptr -> Ptr -> String -> Int -> IO Int
winMain hInstance hPrevInstance lpCmdLine nCmdShow = do ...
```

**Comment by ahmadsalim** [comment]
@be5invis Have you looked at the foreign function call API, and is it not already supported there?

**Comment by be5invis** [comment]
@ahmadsalim It is not **calling** WinMain, but **replace** `main` with `WinMain`, which is the entry point for all Windows GUI applications.

**Comment by melted** [comment]
I think the best bet here is a command line argument that allows rts/idris_main.c to be swapped out for another C file containing an entry point.

**Comment by melted** [comment]
That could also be useful for people who needed to init other stuff before starting idris main.

**Comment by mmn80** [comment]
I think you can have your custom entry point by compiling with the `--interface` flag and writing your main module in `C`. Look into test `ffi006` to learn how to do it. It looks pretty easy.

**Comment by mmn80** [comment]
The `--interface` flag is a simple & general solution to the custom entry problem, as it allows you to write your main module in whatever language/compiler you want, and also, at the back end, use whatever linker you need.

In my mind it only has 2 problems:
1. Undocumented, although I'm pretty sure Edwin considers tests as a perfectly good form of documentation.
2. Unfortunately named (nothing to do with _Idris_ interfaces). Perhaps is should be renamed to something like `--library`.

**Comment by mmn80** [comment]
I implemented point 3 [here](https://github.com/mmn80/idris-loader). All you have to do is make a package without the `main` and `executable` fields, and add a field `opts = "--interface -o entryPoint.o"`.

The entry point module included in the package looks like this:
```Idris
module EntryPoint

export myMain : IO ()
myMain = ...

exportMyMain : FFI_Export FFI_C "entryPoint.h" []
exportMyMain = Fun myMain "myMain" $ End
```

`main.c` (you could use here `WinMain` or whatever):
```C
#include "src/entryPoint.h"

int main() {
    VM* vm = idris_vm();
    myMain(vm);
    close_vm(vm);
}
```

`Makefile`:
```Makefile
build:
	idris --build mypackage.ipkg
	cc main.c src/entryPoint.o `idris --include` `idris --link` -o myexe

clean:
	idris --clean mypackage.ipkg
	rm -f myexe src/*.obj src/*.h
```

Then you build it with `make`.

I think the package manager could be taught to do this by itself.

**Comment by ahmadsalim** [comment]
I will close the issue since @mmn80's workaround seems good, and no one has volunteered to implement the feature request.
PRs still welcome
