### ISSUE TITLE
use _wfopen in RTS for Windows because MSVCRT/MinGW fopen does not support Unicode

### ISSUE THREAD

**Issue by be5invis** [idris-lang/Idris-dev#3638]
It calls ANSI WINAPIs underneath, while Unicode support is in Wide APIs.

**Comment by be5invis** [comment]
UTF-8 fopen:

```c
#include <Windows.h>

int widen_utf8(char *filename_utf8, LPWSTR *filename_w) {
	int num_chars = MultiByteToWideChar(CP_UTF8, 0, filename_utf8, -1, 0, 0);
	int size = sizeof(WCHAR);
	*filename_w = (LPWSTR)malloc(size * num_chars);
	MultiByteToWideChar(CP_UTF8, 0, filename_utf8, -1, *filename_w, num_chars);
	return num_chars;
}
FILE *__u8fopen(char *path, char *mode) {
	LPWSTR wpath, wmode;
	widen_utf8(path, &wpath);
	widen_utf8(mode, &wmode);
	FILE *f = _wfopen(wpath, wmode);
	free(wpath);
	free(wmode);
	return f;
}
```

Getting argc and argv in UTF-8 `char*`:

```c
#include <Windows.h>

int get_argv_utf8(int *argc_ptr, char ***argv_ptr) {
	int argc;
	char **argv;
	wchar_t **argv_utf16 = CommandLineToArgvW(GetCommandLineW(), &argc);
	int i;
	int offset = (argc + 1) * sizeof(char *);
	int size = offset;
	for (i = 0; i < argc; i++) {
		size += WideCharToMultiByte(CP_UTF8, 0, argv_utf16[i], -1, 0, 0, 0, 0);
	}
	argv = (char **)malloc(size);
	for (i = 0; i < argc; i++) {
		argv[i] = (char *)argv + offset;
		offset += WideCharToMultiByte(CP_UTF8, 0, argv_utf16[i], -1, argv[i], size - offset, 0, 0);
	}
	*argc_ptr = argc;
	*argv_ptr = argv;
	return 0;
}
```

**Comment by ahmadsalim** [comment]
@be5invis You are welcome to open a PR with changes to the runtime, if you want them included.

**Comment by be5invis** [comment]
@ahmadsalim IDK how many system APIs are there exposed to Idris... almost all APIs takes and returns `char*` on Windows needed to be wrapped in order to support Unicode.

**Comment by melted** [comment]
Idris is set up to work with UTF8 strings. It is probably best if you add a new opaque type for UTF16 strings in a lib (containing a pointer to it). And make idris functions for conversion to and from String. This would be a nice contribution to lib if it can be done portably. 

I see no need to touch the rts for this. UTF8 strings are widely used on windows too and it shouldn't use a different encoding.

**Comment by be5invis** [comment]
@melted No, in the WINAPI/CRT level, they recognize ONLY wide strings as Unicode. All `char*` are interpreted as legacy encodings (“ANSI”).

**Comment by melted** [comment]
Yes, but idris uses utf-8 (like say Rust). The impedance mismatch should be solved by defining another type for working with wide strings to use with windows APIs. And conversion to and from that.

**Comment by be5invis** [comment]
@melted 
for WINAPI bindings, yes, the best solution is to add a WSTR type.
but for RTS functions, well, add some `#if`s to maintain interface compatibility is a better solution.

**Comment by melted** [comment]
Yeah, filenames are a problem. if you do a special windows version, put it in rts/windows/win_utils.c, so the ifdeffing is minimized.

**Comment by be5invis** [comment]
closed due to my PR.
