### ISSUE TITLE
Explicit Sort hierarchy

### ISSUE THREAD

**Issue by be5invis** [idris-lang/Idris-dev#3653]
Status quo:
```idris
Prop : Type
Prop = Type
```

Looks better:
```idris
Prop : Type_1
Prop = Type
```

**Comment by ahmadsalim** [comment]
@be5invis Could you kindly provide a deeper rationale for why you need this explicit sort hierarchy?

**Comment by be5invis** [comment]
Don’t you think
```idris
Prop : Type
Prop = Type
```
is weird?

**Comment by ahmadsalim** [comment]
@be5invis I do not, in fact I think the opposite is weird :).

Sorry, but I will close this issue since I think it would require a lot of work to add explicit levels without a very small benefit and so I would think there is an abysmal chance of this getting implemented.
