### ISSUE TITLE
Possible compiler bug generating impossible case when it's possible

### ISSUE THREAD

**Issue by codygman** [idris-lang/Idris-dev#3655]
Here's a quick video displaying the problem: https://www.youtube.com/watch?v=7RmDrzpGg7w

Basically I have the code:

```Idris

ordN : Char -> Nat
ordN c = cast (ord c)

data Between : Nat -> Nat -> Nat -> Type where
  MkBetween : LTE a n -> LTE n b -> Between a b n

isBetween : (a, b, n : Nat) -> Dec (Between a b n)
isBetween a b n = case isLTE a n of
  Yes prf1 => case isLTE n b of
    Yes prf2 => Yes (MkBetween prf1 prf2)
    No contra => No (\(MkBetween bad1 bad2) => contra bad2)
  No contra => No (\(MkBetween bad1 bad2) => contra bad1)

data IsUpper : Char -> Type where
  CapitalAscii : (c : Char) -> Between 65 90 (ordN c) -> IsUpper c

isUpper' : (c : Char) -> Dec (IsUpper c)
isUpper' c = case isBetween 65 90 (ordN c) of
  Yes prf => Yes (CapitalAscii c prf)
  No contra => No (\(CapitalAscii _ bad) => contra bad)

data IsCapitalized : String -> Type where
  MkIsCapitalized : (c : Char) -> (cs : String) -> IsUpper c -> IsCapitalized (strCons c cs)

emptyNotCapitalized : IsCapitalized "" -> Void
emptyNotCapitalized (MkIsCapitalized _ _ _) impossible

isCapitalized : (s : String) -> Dec (IsCapitalized s)
isCapitalized s = case strM s of
  StrNil => No emptyNotCapitalized
  StrCons c cs => case isUpper' c of
    Yes prf => Yes ?hmm1
    No contra => No (\weird => ?hmm2)
```

My specific problem is with trying to use idris-add-clause followed by idris-case-dwim, it generating a case match it claims is impossible but then being told that the case it generated is actually possible after loading the file into the repl. Below are the transformations:

When I hover over emptyNotCapitalized and execute idris-add-clause I get:

```Idris
emptyNotCapitalized : IsCapitalized "" -> Void
emptyNotCapitalized x = ?emptyNotCapitalized_rhs

```
If I then hover over x and use idris-case-dwim I get:

```Idris
emptyNotCapitalized : IsCapitalized "" -> Void
emptyNotCapitalized (MkIsCapitalized _ _ _) impossible
```

Then I use Idris load-file on my newly generated code and am surprised to get:
```

- + Errors (1)
 `-- blah.idr line 42 col 20:
     emptyNotCapitalized (MkIsCapitalized _ _ _) is a valid case

```

I think it might be to do with the fact that:

`IsCapitalized ""`

Means MakeCapitalized would look like:

```Idris
MkIsCapitalized : (c : Char) -> (cs : String) -> IsUpper c -> IsCapitalized (strCons c cs)
MkIsCapitalized '' "" prfIsUpper
```

And there is no such thing as an empty Char. If this is the case I don't think I should be able to write this case where something I can't write (empty char) is the underlying value.

**Comment by xekoukou** [comment]
```strCons``` uses a primitive function to construct the string, thus it is impossible for Idris to know the values that would allow the constructor to be well typed.


```
data IsCapitalized : String -> Type where
  MkIsCapitalized : (c : Char) -> (cs : String) -> IsCapitalized (strCons c cs)
  
fun : IsCapitalized "hello" -> String 
fun x = ?fun_rhs
```

```
data IsCapitalized : String -> Type where
  MkIsCapitalized : (c : Char) -> (cs : String) -> IsCapitalized (strCons c cs)
  
fun : IsCapitalized "hello" -> String 
fun (MkIsCapitalized _ _) impossible
```


But Idris should not return impossible on one of the constructors and continue with the rest. The case is not impossible. Idris should return an error of not being able to infer the values/types of ```MkIsCapitalized``` that would make it type correct.

```
data IsCapitalized : String -> Type where
  MkIsCapitalized : (c : Char) -> (cs : String) -> IsCapitalized (strCons c cs)
  Test : IsCapitalized "hello"
  
  
fun : IsCapitalized "hello" -> String 
fun Test = ?fgfd_1
```

**Comment by ahmadsalim** [comment]
Thanks for the issue report. This is similar to #3244, I will move your comments to there and close this issue to keep things consolidated.
