### ISSUE TITLE
Case declared as 'impossible is actually possible.

### ISSUE THREAD

**Issue by geigerzaehler** [idris-lang/Idris-dev#3663]
The following snippet compiles on `0.99-git:bc553c70` and segfaults.

~~~idris
module Bug

%default total

data Singleton : List a -> Type where
  IsSingleton : a -> Singleton [a]

tailNotSingleton : Not (Singleton as) -> Singleton (a :: as) -> Void
-- This case _is_ possible
tailNotSingleton tailNotSingleton (IsSingleton _) impossible

emptyNotSingleton : Not (Singleton [])
emptyNotSingleton x impossible

counterExample : Void
counterExample = tailNotSingleton emptyNotSingleton (IsSingleton ())


main : IO ()
main = do
  putStrLn $ absurd $ counterExample
  pure ()
~~~

Maybe the problem is that the type checker unifies types in contravariant position in `tailNotSingleton`. From `Singelton as -> Void` it deduces `as ~ [a']` which leads to `Singleton ( a :: as ) ~ Singleton [a, a']` which is indeed impossible.

**Comment by xekoukou** [comment]
Well, if you put a hole and check the types, it correctly identifies them as ``` as ~ [] ``` and ``` a :: as ~ [a] ```

I do not know why it considers it impossible.

**Comment by ahmadsalim** [comment]
Yeah, this does actually seem like a bug. Thanks for the report!

**Comment by ahmadsalim** [comment]
From @qknist, @bravit in #3666:
```idris
%default total

bug : (n, m : Nat) -> n + m = n -> Void
bug _ _ Refl impossible
```

**Comment by edwinb** [comment]
This was because of an attempt to identify empty types in the coverage checker that I made a silly mistake in. This was fixed when I fixed another issue, so I'll close now.
