### ISSUE TITLE
Typechecking hangs

### ISSUE THREAD

**Issue by alexknvl** [idris-lang/Idris-dev#3665]
The following hangs during typechecking.
```idris
module Data.RecursionSchemes

interface Functor b => Recursive (t : Type) (b : Type -> Type) | t where
  project : t -> b t

cata : Recursive t b => (b a -> a) -> t -> a
cata f x = c x where c = f . map c . project

data ListF : Type -> Type -> Type where
  Cons : a -> b -> ListF a b
  Nil  : ListF a b

implementation Functor (ListF a) where
  map f (Cons x y) = Cons x (f y)
  map f []         = Nil

implementation Recursive (List a) (ListF a) where
  project []        = Nil
  project (x :: xs) = Cons x xs

test : Nat
test = cata f [1, 2, 3] where
  f Nil        = 0
  f (Cons x y) = y + 1
```

**Comment by ahmadsalim** [comment]
It seems to hang on `test` in particular, even when f is explicitly given type `ListF Integer Nat -> Nat`. I am unsure why it is hanging because it does not say so in the log, and so this would require more debugging to solve.

**Comment by edwinb** [comment]
This is caused by the partial evaluator going far too deep. I'm turning this off by default, because there's still much to understand about how to make it behave well with interfaces and implementations.
