### ISSUE TITLE
Idris fails find possible all possible cases.

### ISSUE THREAD

**Issue by qnikst** [idris-lang/Idris-dev#3666]
In some cases Idris misses possible cases even with totality check enabled, while running session and after restart.

Minimal example:
```idris
%default total

bug : (n, m : Nat) -> n + m = n -> Void
bug _ _ Refl impossible
```
Then in repl:
```
*bug> bug 2 0 Refl
bug 2 0 Refl : Void
```

This proof in `bug` possible to get semi-automatically by generating default implementation and then case-splitting on `Refl`. (Kudos to @bravit  for finding minimal reproducible example)

**Comment by ahmadsalim** [comment]
Thanks for the bug report. This is actually a duplicate of #3663 so I will move your example over there.

**Comment by edwinb** [comment]
I'm reopening because it's a different issue (although one I hope to fix fairly quickly...)
