### ISSUE TITLE
Issues resolving dependencies for 0.99

### ISSUE THREAD

**Issue by hdgarrood** [idris-lang/Idris-dev#3671]
I tried to install Idris just now, and had a bit of an issue getting it to build. Possibly my fault for not following what the tutorial said (I tried to use stack, not cabal-install, as I'm more familiar with the former) but maybe this will be useful information anyway.

This is what I ran:

```
# Download the idris-0.99 tarball from Hackage
$ stack unpack idris-0.99
$ cd idris-0.99
$ ls stack.yaml
stack.yaml
# yay, there's a stack.yaml!
$ stack build

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for trifecta-1.6:
    base-4.9.1.0 must match >=4.4 && <4.9.1 (latest applicable is 4.9.0.0)
needed due to idris-0.99 -> trifecta-1.6

Plan construction failed.
```

I did a bit of digging and I think this is happening because trifecta-1.6 (which is the version of trifecta which is in LTS 7.10) was revised last December to tighten the upper bound it has on base, and the resulting upper bound means that the GHC version in LTS 7.10 ships with a version of base that does not satisfy the updated constraint (see: http://hackage.haskell.org/package/trifecta-1.6/revisions/).

I found two different options for modifying stack.yaml to get it to build with stack:

1. Change the resolver to LTS 7.19; this LTS snapshot has trifecta at version 1.6.2.1 (the current latest version, the same one cabal-install will currently select)
2. Add trifecta-1.6.2.1 to extra-deps.

I'm not suggesting you necessarily do anything about this, mainly just writing this down in case it helps someone else later; although it might be nice for stack users if a new version of idris were uploaded to Hackage with an updated stack.yaml so that it will just work for people who do what I did.

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue. I hope someone more familiar with stack can take a look? @idris-lang/contributors .

**Comment by steshaw** [comment]
@hdgarrood I managed to get a build of idris-0.99 by:

```shell-session
$ stack unpack idris-0.99
$ cd idris-0.99
$ stack --version
Version 1.3.2 x86_64 hpack-0.15.0
$ PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig stack build
$ stack exec idris
     ____    __     _
    /  _/___/ /____(_)____
    / // __  / ___/ / ___/     Version 0.99
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/
 /___/\__,_/_/  /_/____/       Type :? for help

Idris is free software with ABSOLUTELY NO WARRANTY.
For details type :warranty.
Idris>
```

I wonder if it could be something to do with the haskell-stack version (I'm on 1.3.2). I'm running on macOS which needs the PKG_CONFIG_PATH set as above. See also the [docs on installing Idris](https://github.com/idris-lang/Idris-dev/blob/master/INSTALL.md#experimental-support-for-building-with-stack).

I've not kept up with Idris development lately so hopefully you'll hear from other contributors. 

BTW, on Mac you need to also have libffi and libgmp installed too, IIRC:

```bash
$ brew install libffi gmp
```

However, I did notice that building with `stack` no longer works on `master`:

```shell-session
$ PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig stack build

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for idris-0.99(+FFI +GMP):
    code-page must match >=0.1 && <0.2, but the stack configuration has no specified version
              (latest applicable is 0.1.2)

Recommended action: try adding the following to your extra-deps in /Users/steshaw/Projects/idris/stack.yaml:
- code-page-0.1.2

You may also want to try the 'stack solver' command
Plan construction failed.
```

**Comment by david-christiansen** [comment]
@RyanGlScott , IIRC you added the code-page dependency. Is adding it to extra deps the right way to go, or should we push to get it into Stack?

**Comment by RyanGlScott** [comment]
@steshaw, I'm not sure which Stackage resolver you're using, but `code-page` has been in Stackage ever since [LTS-7.17](https://www.stackage.org/lts-7.17).

**Comment by steshaw** [comment]
@RyanGlScott on idris master it's `lts-7.14`:

https://github.com/idris-lang/Idris-dev/blob/master/stack.yaml

When I update it locally to `lts-7.17` the build plan works out fine and idris builds.

**Comment by hdgarrood** [comment]
@steshaw 

> I wonder if it could be something to do with the haskell-stack version (I'm on 1.3.2)

I'm on Ubuntu with stack-1.3.2. The only way of explaining this I can think of is that you have the older version of trifecta's dependency bounds, from before they were tightened. What happens if you run `stack update` and try again?

> See also the docs on installing Idris.

Not really relevant to this issue, but I noticed that these docs say that `stack build` will copy executables to `./local/bin`, and that's not quite true: you need to run `stack build --copy-bins` (or `stack install`, which is equivalent) to actually copy executables into a directory that's likely to be on your PATH. You can ask stack what directory it's going to copy executables into by running `stack path --local-bin`. Should I send a PR?

**Comment by jfdm** [comment]
@hdgarrood and others thanks for the reports. Normally, I've tried to keep on top of building Idris with stack, but have let it slip of late. @steshaw is correct and that if we bump Idris' version of stack things *should* work, and this will get the 'codepage' dependency working. 

@hdgarrood if you wish to send a PR with a commit to update the documentation, and a commit to update the stack version then feel free to.

**Comment by steshaw** [comment]
@hdgarrood I tried `stack update` but it didn't help.

As for the `INSTALL.md` stack docs, it should probably read `stack install` which is just a shortcut for your `stack build --copy-bins`.

**Comment by jfdm** [comment]
Dear all;

I've updated Idris' stack files, and the documentation too.

If nobody objects I'll close the issue in the morrow.

**Comment by hdgarrood** [comment]
:+1: the update looks good to me, thanks!

**Comment by jfdm** [comment]
right, i shall close the issue then.
