### ISSUE TITLE
interface type dependent return values

### ISSUE THREAD

**Issue by imuli** [idris-lang/Idris-dev#3674]
This seems to have worked [back when interfaces where classes](https://github.com/idris-hackers/idris-crypto/blob/master/src/Data/Crypto/Hash.idr), I'm trying to adapt that to current Idris.

```idris
interface Test a where
  q : Nat
  p : Nat
  foo : Nat -> Fin q
  bar : Fin q -> Fin p
  baz: Fin q -> Nat
```

One difference between the old idris and new idris is:

```idris
quux : Test a => a -> Nat -> Nat
quux _ k = baz (foo k)
```

needs to be 

```idris
quux {a} _ k = baz {a} (foo {a} k)
```

Which is mildly inconvenient, but whatever.

However I haven't been able to figure out how to rewrite:

```idris
quux : Test a => a -> Nat -> Fin p
quux {a} _ k = bar {a} (foo {a} k)
```

which yields the amusing error message:

```
...:When checking right hand side of baz with expected type
        Fin p

Type mismatch between
        Fin p (Type of bar (foo k))
and
        Fin p (Expected type)

Specifically:
        Type mismatch between
                p
        and
                p
```

(The two are indeed different colors in the output, but…)

What's going on?

**Comment by imuli** [comment]
```idris
quux : (test : Test a) => a -> Nat -> Fin (p @{test})
quux : _ k = bar (foo k)
```
fixes that, much nicer than all the explicit implicits actually.

**Comment by edwinb** [comment]
All of this happens because there's no "a" in the types of the methods. Previously, Idris guessed which instance you meant in situations like this, which was a bad idea because it could easily have got it wrong (and sometimes did, causing some very strange errors)... so I think this is correct behaviour, even if it is annoying to have to be explicit.

The error message could clearly be more helpful, though.

**Comment by clayrat** [comment]
@wurmli Works for me on 1.3

**Comment by wurmli** [comment]
@imuli Thank you, but this still doesn't work on my side with 1.3:

```
import Data.Fin

interface Test a where
  q   : Nat
  p   : Nat
  foo : Nat -> Fin q
  bar : Fin q -> Fin p
  baz : Fin q -> Nat

quux : (test : Test a) => a -> Nat -> Fin (p @{test})
quux _ k = (bar @{test}) (foo @{test} k)
```
with error message:
```
-- ITest.idr line 14 col 11:
    When checking right hand side of quux with expected type
            Fin p
    
   When checking an application of function Main.bar:
            No such variable test
```

**Comment by imuli** [comment]
Spoke too soon!

```idris
import Data.Fin

interface Test a where
  q   : Nat
  p   : Nat
  foo : Nat -> Fin q
  bar : Fin q -> Fin p
  baz : Fin q -> Nat

quux : (test : Test a) => a -> Nat -> Fin (p @{test})
quux {a} _ k = bar {a} $ foo {a} k
```
