### ISSUE TITLE
Prelude.Bits: document target serialization (hex); support additional encodings

### ISSUE THREAD

**Issue by jmitchell** [idris-lang/Idris-dev#3675]
Without referring to the source or experimenting, it's unclear what `b8ToString` does.

I propose we

* add documentation indicating the `Bits* -> String` functions return a non-"0x"-prefixed hex encoding
* consider renaming them to clarify (e.g. `b8ToHexString`)
* consider adding more encodings, like `b8ToBinString` and `b8ToOctString`

**Comment by edwinb** [comment]
I think all of these are good ideas. As long as `b8ToString` etc remain, with suitable documentation (or even a deprecation warning) I think a PR that did all this would be accepted.

**Comment by edwinb** [comment]
I believe this is fixed by the above reference patch
