### ISSUE TITLE
Missing LTrunc cases in JavaScript code generator

### ISSUE THREAD

**Issue by jmitchell** [idris-lang/Idris-dev#3677]
The build for PR #3676 failed with the following error:

```
Error: test/bounded001
/home/travis/build/idris-lang/idris-0.99.1/test/bounded001/bounded001:1417
  i$valstack[i$valstack_base + 1] = (function(){throw new Error("Not implement
                                                      ^
Error: Not implemented: LTrunc (ITFixed IT32) (ITFixed IT8)
    at /home/travis/build/idris-lang/idris-0.99.1/test/bounded001/bounded001:1417:55
    at _idris_Prelude_46_Bits_46_b32ToBytes (/home/travis/build/idris-lang/idris-0.99.1/test/bounded001/bounded001:1417:122)
    at i$RUN (/home/travis/build/idris-lang/idris-0.99.1/test/bounded001/bounded001:1351:10)
    at main (/home/travis/build/idris-lang/idris-0.99.1/test/bounded001/bounded001:2728:3)
    at Object.<anonymous> (/home/travis/build/idris-lang/idris-0.99.1/test/bounded001/bounded001:2730:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
OK (32.85s)
    bignum002:         OK (6.36s)
  Bounded
    bounded001:        FAIL (5.69s)
      --- test/bounded001/output	2017-03-06 01:11:15.453876002 +0000
      +++ test/bounded001/expected	2017-03-06 00:57:18.000000000 +0000
      @@ -1,2 +1,6 @@
       FFFF
       0000
      +FFFFFFFF
      +00000000
      +FFFFFFFFFFFFFFFF
      +0000000000000000
```

For the PR's code to work the following cases which aren't handled must be implemented:

* `LTrunc (ITFixed IT32) (ITFixed IT8)`
* `LTrunc (ITFixed IT64) (ITFixed IT8)`

There are more combinations for `LTrunc (ITFixed from) (ITFixed to)` that aren't supported yet either. Implementing a more generic case for `ITFixed from` to `ITFixed to` would be good. That's how it's done in the C generator: https://github.com/idris-lang/Idris-dev/blob/master/src/IRTS/CodegenC.hs#L575

**Comment by jmitchell** [comment]
Side question: is it generally considered a bug when an official code generator doesn't handle some of the IRTS.Lang representation? If so, are there tools, existing or planned, to assess coverage?

**Comment by ahmadsalim** [comment]
@jmitchell Thanks for report, I do think it is a bug since it affects a backend shipped with Idris.
As far as I understand we currently do not have a maintainer for the ECMAScript backend, but contributions are welcome in fixing this bug.

**Comment by jmitchell** [comment]
Resolved. See https://github.com/idris-lang/Idris-dev/pull/3676/commits/f0b13faf6ea84c59eb9ee4d4ab8a3d950ba36152
