### ISSUE TITLE
Unable to define an interface and datatype which depend on each other

### ISSUE THREAD

**Issue by canndrew** [idris-lang/Idris-dev#3686]
I'm trying to define the following two items in tandem:

```idris
interface Syntax syn where
    reduce : syn -> NF syn

data NF : (t : Type) -> (Syntax t) => Type where
    N : Syntax t => (x : t) -> (reduce x = x) -> NF t
```

There doesn't seem to be any way to make this work, the compiler always complains about something not being defined yet when I go to use it. Putting them in a mutual block doesn't help.

This would be fixable if it were possible to pre-declare interfaces like we can with datatypes.

**Comment by echo-oddly** [comment]
Put the code in a `mutual` block. Documented [here](http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#note-declaration-order-and-mutual-blocks)

**Comment by ahmadsalim** [comment]
@canndrew I think the issue is that you also include the interface constraint in type level as well, so you have a type-level cycle (which shoud not be accepted).

Instead try:
```idris
interface Syntax syn where
    reduce : syn -> NF syn

data NF : (t : Type) -> Type where
    N : Syntax t => (x : t) -> (reduce x = x) -> NF t
```

**Comment by ahmadsalim** [comment]
@canndrew In any case, I do not think it is possible to instantiate your type with something useful, e.g.:

```idris
implementation Syntax Unit where
    reduce () = N () ?p
--- Here ?p is recursively dependent on the result of reduce ()
```

**Comment by ahmadsalim** [comment]
The proper design pattern would probably be something like:

```idris
interface Syntax syn where
   reduce : syn -> syn
   reduceIdempotent : reduce (reduce x) = reduce x
```

**Comment by canndrew** [comment]
@ahmadsalim Thanks, I figured it was probably logically unsound. It would be good if Idris explained that though rather than complaining about things not being defined.
