### ISSUE TITLE
No such variable Prelude.cast_error

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3695]
When trying to install the latest Idris version on a Debian stable system I get
```
Type checking ./Control/ST/Exception.idr
When attempting to perform error reflection, the following internal error occurred:
        No such variable Prelude.cast_error Type error while constructing reflected error This is probably a bug. Please consider reporting it at https://github.com/idris-lang/Idris-dev/issues
```
The last successful installation was about one week ago. I have done a `cabal update` before `cabal install --enable-tests`.

**Comment by ahmadsalim** [comment]
Have you tried removing all `*.ibc` files in the `idris --libdir` subdirectories?

**Comment by nicolabotta** [comment]
I have not and removing the `*.ibc` files in `idris --libdir` indeed solves the issue. Thanks!
