### ISSUE TITLE
Interface implementations using type functions cannot be found

### ISSUE THREAD

**Issue by schell** [idris-lang/Idris-dev#3700]
I may not have worded that correctly but my problem is summed up in the following example:
```idris
data MyType a b = MkMyType a b

Functor (\ a => MyType a x) where
  map f (MkMyType a x) = MkMyType (f a) x

myType : MyType Int String
myType = MkMyType 6 "dude"

yourType : MyType Int String
yourType = map (+2) myType

--- + Errors (1)
-- `-- hello.idr line 7 col 9:
--     When checking right hand side of yourType with expected type
--             MyType Int String
--     
--     When checking argument func to function Prelude.Functor.map:
--             String is not a numeric type
```

It's possible to define an interface that cannot be used. It was pointed out on freenode #idris that one may have to tell idris which implementation to pick ala `yourType = map {f=\ a => MyType a String} (+2) myType` but it errs similarly. 

I'm trying to update my mental model of dependent types and interfaces, so after this error (in the first call site's case) I decided "that makes sense that it would error because I essentially wrote a Functor instance for a type level function involving `MyType` instead of writing a Functor instance for `MyType` itself" but after supplying the implicit argument to map I can't believe that assertion.

**Comment by schell** [comment]
This also errs:
```idris
myType : (\ a => MyType a String) Int
myType = MkMyType 6 "dude"

yourType : (\ a => MyType a String) Int
yourType = map (+2) myType
```

**Comment by edwinb** [comment]
Just a quick note - as I said on irc I think the right thing to do is to reject the implementation, given the way they are resolved at the moment.
