### ISSUE TITLE
Strange behaviour of type constructors and Refl

### ISSUE THREAD

**Issue by danilkolikov** [idris-lang/Idris-dev#3703]
I found strange behavior of type checker. Suppose we have two functions - `check` and `foo`, second somehow transforms passed type constructor:
```idris
%auto_implicits off

foo: {a: Type} -> (constr: a -> a -> Type) -> a -> a -> Type

check: {a: Type} -> (constr: a -> a -> Type) -> foo constr = constr
check constr = Refl
```
Such version of `foo` compiles:
```idris
foo constr = constr
```
Such doesn't:
```idris
foo constr x = constr x
```
Error:
```
Type mismatch between
        constr = constr (Type of Refl)
and
        foo constr = constr (Expected type)
```
I found a workaround:
```idris
foo constr = \x => constr x
```
But if we pass 2 arguments instead of one, it doesn't help, every combination of arguments and lambda-functions fails:
```idris
foo constr x y = constr x y
foo constr x = \y => constr x y
foo constr = \x, y => constr x y
```
```
Type mismatch between
        constr = constr (Type of Refl)
and
        foo constr = constr (Expected type)
```

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue. I think it should not reduce foo since you have not given it a definition yet.

**Comment by ahmadsalim** [comment]
It seems that in the latest of Idris (HEAD) makes sure that the first version also does not compile, so it's fixed now.
