### ISSUE TITLE
Strange Erasure/getArity issue

### ISSUE THREAD

**Issue by mgttlinger** [idris-lang/Idris-dev#3713]
I have been struggling for days to find the cause of the segfaults I get when running my idris application and producing a minimal reproducible example. Using gdb and valgrind I traced the cause to String operations `idris_concat` and `idris_streq`. 
During the reduction of the project I hit the error:
```
idris: Erasure/getArity: definition not found for with block in Prelude.Interfaces.Prelude.Nat.Nat implementation of Prelude.Interfaces.Ord, method <
```
@edwinb said this should never happen, so here is a bug report on it.

repo project here: https://github.com/mgttlinger/idris-bugrepro

There may also still be the issue of the segfault in there but I cant check as the error above prevents me from compiling. Hints on that: If the `FromJSON` instances get defined differently the segfault goes away and if the `g_runnableAbb` isn't used anywhere it also goes away.

**Comment by edwinb** [comment]
I'm taking a look at this now, but I get an error when building dependencies:

    The following packages were specified but cannot be found:
    - testparse

Is there something missing from the dependencies script?

**Comment by mgttlinger** [comment]
When building my package or when building the dependencies?

**Comment by mgttlinger** [comment]
Ok, given that `config` depends on that it may be an issue with that build. This is unmodified from https://github.com/jfdm/idris-config so you could build that instead of using the contained clone.

**Comment by jfdm** [comment]
If you are building using the latest verison's of my test repo, then it could be that I recently deprecated the testparse package as the functionality is now integrated into lightyear itself. Apologies if this was the case.

**Comment by jfdm** [comment]
I've updated config to work with latest test and lightyear.

**Comment by edwinb** [comment]
I still can't build this. I cloned the repo again, then I removed the testparse dependency but now I get "Can't find import Test/Parsing" when I try to run buildDeps.sh. So - what are the steps to reproduce from scratch? I am surely doing something wrong.

**Comment by mgttlinger** [comment]
I recommend just cloning the idris-config repo directly instead of usind the one I checked in. I thought this would make it easier but apparently it did not...

**Comment by edwinb** [comment]
Okay, I can build this now, and I can reproduce the segfault.

**Comment by edwinb** [comment]
What is a definition of FromJSON that makes the segfault go away? It's not at all obvious what's going wrong here, or even where to start poking, so anything that gives me some kind of clue would be useful!

**Comment by edwinb** [comment]
It seems you stumbled on a rather nasty problem with code generation where, under some unlikely circumstances that you happened to hit, a variable reference ended up being wrong. I'm glad you found this now, as I am about to release version 1.0 and that would have been a nasty error to have missed... there's a fix coming soon.
