### ISSUE TITLE
Type mismatch between same terms in interface

### ISSUE THREAD

**Issue by JakobBruenker** [idris-lang/Idris-dev#3715]
```Idris
interface Test t where
  exists : (e : t ** e = e)

interface (Test t) => Test2 t where
  equal : (let a : (e : t ** e = e) = exists in (DPair.fst a = DPair.fst a))
```
results, on version 0.99.2 on Windows, in
```bash
Type mismatch between
        (e : t ** e = e)
and
        (e6 : t ** e6 = e6)
```

Another thing, that might be related:
```Idris
interface Test where
  test1 : (b : ()) -> ()
  -- test1 : (c : ()) -> () -- this would work, suggesting that Idris
                            -- thinks it should still use b from test1
  test2 : (b : () ** b = b)
```
results in
```bash
Type mismatch between
        (b : () ** b = b)
and
        (b1 : () ** b1 = b1)

Specifically:
        Type mismatch between
                (b1 : () ** b1 = b1)
        and
                (b : () ** b = b)
```

**Comment by edwinb** [comment]
This is weird, because it's failing a conversion check even though the terms are obviously convertible. The only difference in the terms is the names, and the conversion check explicitly keeps track of that (nothing would work if it didn't...)

Anyway. I will fix this ASAP.

**Comment by edwinb** [comment]
Fixed now, but one other thing you'll need to fix the original code is, in the Test2 interface, explicitly say which "exists" you mean. "exists" alone gives Idris no hint as to which implementation it might be, but if you write "exists {t}" it knows you mean the one from the "Test t" implementation.

Even though this is the only possible implementation in this situation, unification needs this.

**Comment by JakobBruenker** [comment]
That makes sense; thanks for fixing it!
