### ISSUE TITLE
Error in Code Generation 'duplicate case value'

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#3719]
When generating a Toy executable, the C codegen reports a 'duplicate case value' error during compilation.

I've yet to create a MFE but have dumped the offending code in to:

https://github.com/jfdm/idris-error-temp

The first script compiles as expected, the second one fails.

**Comment by edwinb** [comment]
I'll take a look at this as soon as I can if you can find an MFE... as it stands, I'm not going to let it get in the way of a release (epsecially since it results in not compiling, rather than compiling and failing...)

**Comment by jfdm** [comment]
no worries, i'll try and get a MFE at some point...

**Comment by jfdm** [comment]
thanks @edwinb
