### ISSUE TITLE
repl function not working in the REPL when invoked via :x main?

### ISSUE THREAD

**Issue by darrenrhea** [idris-lang/Idris-dev#3726]
I am on mac os x 10.11 El Capitan running idris 1.0 as it was installed by homebrew.  Most things are working great.  However, if you make the program

```idris
module Main

main : IO ()
main = repl "> " reverse
```

and then start the REPL via

```bash
$ idris Main.idr
```

this behaves a bit weird when you run the program via

```
:x main
```

in that it will not initially show the prompt, and will let you enter multiple lines until you press ctrl-C, then it does all lines at once, giving a prompt for each:

```
$ idris Main.idr
     ____    __     _
    /  _/___/ /____(_)____
    / // __  / ___/ / ___/     Version 1.0
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/
 /___/\__,_/_/  /_/____/       Type :? for help

Idris is free software with ABSOLUTELY NO WARRANTY.
For details type :warranty.
*Main> :x main
bat
cat
dog
kitty
^C> tab> tac> god> yttik> Interrupt
*Main>
```

Not sure if this is a bug or not.  `:exec` works fine, as does compiling and running the program at the command line.  Is there something different between `:exec` and `:x main`?

**Comment by david-christiansen** [comment]
Yes, there is. One of them uses an interpreter for IO actions, the other compiles and runs an executable. My guess is that the interpreter needs to flush the output stream at some point, but doesn't.
