### ISSUE TITLE
Network.Socket does not compile on Windows

### ISSUE THREAD

**Issue by bascott** [idris-lang/Idris-dev#3732]
Idris version: 1.0
OS Version: Windows 10
Attempted to build the example from http://docs.idris-lang.org/en/latest/st/examples.html

    C:\Users\Brian\Scratch\STServer> idris --build .\simpleecho.ipkg
    Entering directory `.\src'
    Type checking .\Network\Sockets.idr
    Type checking .\Main.idr
    C:\Users\Brian\AppData\Local\Temp\idris4118467.c:1:19: fatal error: netdb.h: No such file or d
    irectory
     #include "netdb.h"
                       ^
    compilation terminated.
    FAILURE: "gcc" ["-O2","-fwrapv","-fno-strict-overflow","-DHAS_PTHREAD","-DIDRIS_ENABLE_STATS",
    "-I.","C:\\Users\\Brian\\AppData\\Local\\Temp\\idris4118467.c","-Lc:\\idris\\./libs\\rts\\","-
    lidris_rts","-lpthread","-Ic:\\idris\\./libs\\rts\\","-lm","-I.","-Ic:\\idris\\./libs\\libs\\p
    relude","-Ic:\\idris\\./libs\\libs\\base","-Ic:\\idris\\./libs\\libs\\contrib","-I../base","-I
    ../prelude","-I.","-ID:\\Niklas\\repo\\Idris-dev\\.cabal-sandbox\\x86_64-windows-ghc-8.0.1\\id
    ris-1.0\\libs\\prelude","-ID:\\Niklas\\repo\\Idris-dev\\.cabal-sandbox\\x86_64-windows-ghc-8.0
    .1\\idris-1.0\\libs\\base","-Wl,--stack,16777216","-o","C:\\Users\\Brian\\Scratch\\STServer\\s
    impleecho"]
    Leaving directory `.\src'

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue. Could you provide us more detail on whether you are using 32-bit or 64-bit Windows?

**Comment by be5invis** [comment]
replace with `<winsock.h>` perhaps?

**Comment by bascott** [comment]
@ahmadsalim I'm using 64-bit Windows.

**Comment by melted** [comment]
Net/Socket.idr contains:

```idris
%include C "sys/types.h"
%include C "sys/socket.h"
%include C "netdb.h"
```

As there is no easy way to conditionally exclude those, your best bet is probably to make your own custom Net/Socket.idr (call it Net/WinSocket.idr maybe?) or creating dummy include files, one containing the #include that is used for Windows.

**Comment by be5invis** [comment]
@melted I think replacing it with libuv may be a better idea given that WINSOCK is slow...

**Comment by melted** [comment]
Fixed in https://github.com/idris-lang/Idris-dev/pull/4017
