### ISSUE TITLE
Redefining declarations in the REPL is cumbersome

### ISSUE THREAD

**Issue by dwijnand** [idris-lang/Idris-dev#3733]
In the REPL, redefining previously defined functions currently requires invoking `:unlet` first, which is cumbersome. An example:

```idris
Idris> :let palindrome : String -> Bool; palindrome s = reverse s == s
Idris> palindrome "racecar"
True : Bool
Idris> palindrome "Racecar"
False : Bool
Idris> palindrome "race car"
False : Bool
Idris> :let palindrome : String -> Bool; palindrome s = let ss = toLower s in reverse ss == ss
(input):1:17:palindrome already defined
(input):1:17:palindrome is already defined
Idris> palindrome "Racecar"
False : Bool
Idris> :unlet palindrome
Undefined palindrome.
Idris> :let palindrome : String -> Bool; palindrome s = let ss = toLower s in reverse ss == ss
Idris> palindrome "Racecar"
True : Bool
Idris> palindrome "racecar"
True : Bool
```

Perhaps the solution is to add a `-f/--force` to `:let`, or perhaps the restriction on `:let` redefining declarations should be dropped or relaxed.

I'm happy to attempt to submit a PR to improve this, but I would need a little guidance.

**Comment by ahmadsalim** [comment]
Thanks for your interest in contributing.

The folder [src/Idris/Repl](https://github.com/idris-lang/Idris-dev/tree/master/src/Idris/REPL) folder contains the parser and abstract structure (especially notice `NewDefn` and `Undefine` in the AST). The actual definition happens in the following line: https://github.com/idris-lang/Idris-dev/blob/b7cf1ec0f4a2ca455c8cc32769c3607641be88fd/src/Idris/REPL.hs#L857 .

If you have any other question, please do ask!

**Comment by dwijnand** [comment]
Hey @ahmadsalim,

* Do you know how I could create a test for this change in behaviour in the REPL?
* Do you have any advice or opinion on which solution I should pursue? Perhaps: do you know why REPL currently is coded to not let you redefine functions?

**Comment by ahmadsalim** [comment]
The instructions for adding the test are in the README, here: https://github.com/idris-lang/Idris-dev/blob/master/test/README.md#adding-a-test . For inspiration I would take a look at the `interactiveXX` tests which try to test similar behaviours.

I do not remember the rationale then, but I would not mind allowing redefinitions myself, as long as redefining something would not break things that had references to the old definition. I guess opinions from other @idris-lang/contributors would be valuable here as well.

**Comment by david-christiansen** [comment]
The reason why we prevent immediate redefinition is to prevent proofs of `Void`. Imagine this interaction sequence:
```
> :let x : Nat ; x = 1
> :let foo : x = Z -> Void ; foo x = absurd x
> :let x : Nat ; x = Z
> :let oops : Void ; oops  = foo Refl
```
So at the very least, redefining something should remove all the definitions that depend on it, or perhaps recheck them and remove the ones that no longer work.

**Comment by ahmadsalim** [comment]
One could try to correctly rename the old definition, I think.

**Comment by david-christiansen** [comment]
This all seems overcomplicated and fragile, though, compared to having a file that gets edited and reloaded.

**Comment by ahmadsalim** [comment]
Yeah, I guess the easiest would be to just have the functionality of `:unlet ... :let` I guess.

**Comment by dwijnand** [comment]
I'm happy to pursue any simple and robust solution that aids my use case, or close this issue if one cannot be found.

There's something wrong with your snippet, @david-christiansen, and unfortunately I don't know Idris enough to know how to correct any typos:

```
Idris> :let foo : x = Z -> Void ; foo x = absurd x
(input):1:12-13:WARNING: x is bound as an implicit
	Did you mean to refer to x?
(input):1:32:When checking right hand side of foo with expected type
        Void

Can't find implementation for Uninhabited (x = 0)
```

**Comment by ahmadsalim** [comment]
@dwijnand I think the easiest would be to check if it is already defined and use the functionality of `:unlet` before using the functionality of standard `:let`

**Comment by bbarker** [comment]
+1 for this Idea for @david-christiansen: "So at the very least, redefining something should remove all the definitions that depend on it, or perhaps recheck them and remove the ones that no longer work."

I like the idea since it automates work, and if it gives you error messages along the way for dependent definitions that break upon redefinition; that amounts to valuable and quick feedback.
