### ISSUE TITLE
Error doesn't break the build

### ISSUE THREAD

**Issue by ctford** [idris-lang/Idris-dev#3739]
It seems that there's a FFI test that's erroring, but because the error goes to `stderr` the test runner doesn't see it:

```$ stack test --test-arguments="--pattern ffi --accept"
idris-1.0: test (suite: regression-and-feature-tests, args: --pattern ffi --accept)

Regression and feature tests
  FFI
    ffi001: OK (3.15s)
    ffi002: OK (2.62s)
    ffi003: OK (3.11s)
    ffi004: OK (3.48s)
    ffi005: OK (3.91s)
    ffi006: OK (5.22s)
    ffi007: OK (5.44s)
    ffi008: OK (6.58s)
    ffi009: 
Error: test/ffi009
idris: Foreign Function calls cannot be partially applied, without being inlined.
CallStack (from HasCallStack):
  error, called at src/IRTS/CodegenC.hs:343:36 in idris-1.0-FDsvJd4UUF63PBUG6EK03I:IRTS.CodegenC

OK (5.80s)

All 9 tests passed (12.33s)
```

**Comment by ctford** [comment]
This may be an intentional error message. A comment from `Bad.idr` in `test/ffi009`:

```
-- [ NOTE ]
--
-- As `commen_call` is a partial function and not inline, Idris should complain.
```

**Comment by jfdm** [comment]
It is an intentional error message, that we don't capture. If you can get std error to be captured and compared to an expected file that would be great otherwise, this is an acceptable 'behaviour'.

**Comment by ctford** [comment]
Thanks. Will close.

For reference, to implement the checking of error message you suggest would involve changing `runTest` in `test/TestRun.hs`.
