### ISSUE TITLE
Totality checker seems to ignore Inf hidden in the function type

### ISSUE THREAD

**Issue by yanok** [idris-lang/Idris-dev#3746]
For example, `run` function from Listing 11.13 in the Type-Driven Development with Idris book is reported as total by Idris 1.0.

here is the code:
```
data InfIO : Type where
     Do : IO a ->
          (a -> Inf InfIO) ->
          InfIO

total
run : InfIO -> IO ()
run (Do x f) = do r <- x
                  run (f r)
```
If I change the type of the second argument of `Do` constructor to `Inf (a -> InfIO)` the problem goes away.

**Comment by yanok** [comment]
I've bisected this to be55376d45a4415c342875580bac44ed5d92056b.

**Comment by edwinb** [comment]
Yikes, that is odd, and shouldn't have crept in! Clearly we have something missing in the tests... thanks for spotting, I'll fix it as soon as I can.
