### ISSUE TITLE
Can't build using stack on macOS 10.12.4: missing gmp

### ISSUE THREAD

**Issue by artagnon** [idris-lang/Idris-dev#3750]
```
$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
$ brew install gmp
Warning: gmp-6.1.1 already installed
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
$ PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig stack build
idris-1.0: build (lib + exe)
Package idris uses a custom Cabal build, but does not use a custom-setup stanza
Not using the explicit setup deps approach based on configuration
Strongly recommend fixing the package's cabal file
Preprocessing library idris-1.0...
ld: library not found for -lgmp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)

--  While building package idris-1.0 using:
      /Users/artagnon/src/idris-dev/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.2.0 build lib:idris exe:idris exe:idris-codegen-c exe:idris-codegen-javascript exe:idris-codegen-node --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

Specifying `LD_LIBRARY_PATH=/usr/local/Cellar/gmp/6.1.1/lib` explicitly doesn't work either.

**Comment by ahmadsalim** [comment]
@artagnon are you using the latest version and what version of the resolver are you using? @jfdm Any hints on other issues?

**Comment by artagnon** [comment]
@ahmadsalim Sorry, but what is the resolver, and how do I find out the version? As far as I can tell, I'm using the latest version of everything.

**Comment by ahmadsalim** [comment]
@artagnon I think it uses the default one if you did not change it with `--resolver`.

**Comment by ahmadsalim** [comment]
@artagnon In any case, I can not seem to reproduce your issue, so it might be because of your particular environment. Could you please consider using the Binaries (under OS X): https://www.idris-lang.org/download/ , or using the mailing list for further debugging?
I think that would be a better place, since this is not an issue of Idris in general. Thanks!

**Comment by artagnon** [comment]
Oh, I'm already running Idris from brew. I wanted idris-dev to build so I
can contribute.

I'll join the mailing list. Thanks.
