### ISSUE TITLE
Conditional directives

### ISSUE THREAD

**Issue by be5invis** [idris-lang/Idris-dev#3751]
As in #3732 ...
```idris
%if (codegen "nodejs")
%lib Node "net"
%elseif (platform "win32" || platform "win64")
%include C "winsock.h"
%else
%include C "sys/types.h"
%include C "sys/socket.h"
%include C "netdb.h"
%endif
```
It’s ugly but necessary.

**Comment by ahmadsalim** [comment]
@be5invis The C issue could probably be handled using making a custom header file with the conditionals and including that. I think the other directives are only run on the particular codegen, or am I mistaken?

**Comment by be5invis** [comment]
@ahmadsalim there is a `%if (codegen ...)` in the example, showing that the Idris should able to have different Idris code for different backend. In the example above, for `nodejs` we use `net` module and for `C` backend we use headers.

**Comment by ahmadsalim** [comment]
@be5invis I think `%lib Node "net"` is only run when the `node` backend is used or no? It is kind of a conditional already.

**Comment by be5invis** [comment]
@ahmadsalim but we may have different Idris code to wrap these foreign functions, the code for Node.js and for C are definitely different.

**Comment by ahmadsalim** [comment]
@be5invis Yeah, but this can be handled using interfaces or by providing specialized functions. I.e. we have `IO FFI_JS` and `IO FFI_C` already I think which depend on the specific `FFI`.

**Comment by be5invis** [comment]
@ahmadsalim 
Example:
```idris
%if (codegen "c")
do_fopen : String -> String -> IO Ptr
do_fopen f m = foreign FFI_C "fileOpen" (String -> String -> IO Ptr) f m
%elseif (codegen "node")
%lib Node "fs"
do_fopen : String -> String -> IO Ptr
do_fopen f m = foreign FFI_JS "fs.open(%0, %1)" (String -> String -> IO Ptr) f m
%endif
```

**Comment by be5invis** [comment]
Things may just get complex somehow, for example, network...

**Comment by ahmadsalim** [comment]
@be5invis Note that `IO` is actually `IO' FFI_C`.
One could try to do something like:

```idris
interface Files ffi where
     do_fopen : String -> String -> IO' ffi Ptr

implementation Files FFI_C where
     do_fopen f m = foreign FFI_C "fileOpen" (String -> String -> IO Ptr) f m

implementation Files FFI_JS where
     do_fopen f m = foreign FFI_JS "fs.open(%0, %1)" (String -> String -> JS_IO Ptr) f m
```

**Comment by be5invis** [comment]
@ahmadsalim 
hmm, what if the "wrapper" varies more for multiple backends? like `char*` vs `WSTR`, sync vs async, ...

**Comment by ahmadsalim** [comment]
@be5invis One could try to use associated types. If the interfaces are completely different I would not treat them as overloaded, but rather make different libraries which use the correct `FFI_X` for operations.

**Comment by ahmadsalim** [comment]
I will close the issue since there has been no progress on discussion.
