### ISSUE TITLE
Operator sections

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3755]
The declaration
```
foo : DPair Nat (\ n => n `LTE` 5)

```
type checks fine. But
```
bar : DPair Nat (`LTE` 5)
```
does not. One gets
```
- + Errors (1)
 `-- ./issues/operator_section.lidr line 3 col 8:
      error: expected: type signature
       bar : DPair Nat (`LTE` 5) 
```
From http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html?highlight=operator%20section, one would expect that both declarations type check.

**Comment by ahmadsalim** [comment]
@nicolabotta Thanks for reporting the issue. I think currently ticked operators are not supported in sections, but perhaps they should be allowed in the parser.

**Comment by nicolabotta** [comment]
@eraserhd, @ahmadsalim Thanks!
