### ISSUE TITLE
repl function being weird on ^D

### ISSUE THREAD

**Issue by 1-p** [idris-lang/Idris-dev#3757]
module Main
    
    main : IO()
    main = repl "What? " id

Entering a single `^D` (`Ctrl-D`) will trigger an infinite stream "What? "

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue. As far as I can see from the implementation, this is because the `replWith` function does not check for `EOT` before recursion.

**Comment by Synthetica9** [comment]
Doesn't seem to be the case anymore.

**Comment by ahmadsalim** [comment]
@Synthetica9 That is weird, do you know what has changed since then?

**Comment by ether42** [comment]
Pinging @melted in case he wants to close this issue since he merged #4375.

**Comment by melted** [comment]
Thanks!
