### ISSUE TITLE
type mismatch between `m` and `plus m 0`

### ISSUE THREAD

**Issue by amarpotghan** [idris-lang/Idris-dev#3760]
Idris version: 1.0

test case:

```
append : Vect n a -> Vect m a -> Vect (m + n) a
append [] ys = ys
append (x :: xs) ys = x :: (append xs ys)
```

full error message:
```
When checking right hand side of append with expected type
        Vect (m + 0) a

Type mismatch between
        Vect m a (Type of ys)
and
        Vect (plus m 0) a (Expected type)

Specifically:
        Type mismatch between
                m
        and
                plus m 0 
```

Minimally:

```
Idris> :let m = the Nat 1
Idris> the (plus m 0 = m) Refl
Refl : 1 = 1
Idris> :let m = the Nat ?z
Holes: z
Idris> the (plus m 0 = m) Refl
(input):1:5:When checking argument value to function Prelude.Basics.the:
        Type mismatch between
                ?z = ?z (Type of Refl)
        and
                plus m 0 = m (Expected type)

        Specifically:
                Type mismatch between
                        ?z
                and
                        plus ?z 0
Holes: z
 ```

**Comment by amarpotghan** [comment]
Closed this because I learnt about rewrite tactic.

**Comment by zjhmale** [comment]
Hi @amarpotghan, I think simply change the type signature from 

```
append : Vect n a -> Vect m a -> Vect (m + n) a
```

```
append : Vect n a -> Vect m a -> Vect (n + m) a
```

Can fix this :)

**Comment by amarpotghan** [comment]
That order was intentional not accidental

**Comment by jfdm** [comment]
Sorry for the late reply, but I've only just saw the issue.

At the type level ordering can be important, especially when pattern matching and elaborating. IIRC, the error you encountered was related to the desugaring of `m + n` to `plus m n`; the structure of `plus`; and the structure of the function w.r.t pattern matching. By structure, I mean how the functions recurse. Sometimes it is better when things align, and when they don't rewriting is handy.

**Comment by amarpotghan** [comment]
@jfdm No problem, got that :-). Thanks @jfdm and @zjhmale.
