### ISSUE TITLE
Record syntax for constructing records with explicit labels.

### ISSUE THREAD

**Issue by be5invis** [idris-lang/Idris-dev#3764]
The current record syntax,
```idris
record {field = value}
```
is only for updating a record value.

Could we have a syntax for creating? like, `new`?
```idris
record Person where
  firstName, middleName, lastName : String

tom = Person
tom = new { firstName = "Tom", middleName = "", lastName = "Soya" }
```

**Comment by ahmadsalim** [comment]
I would guess it would be bad to have add a new keyword `new` now, since it could potentially break a lot of the existing code. Maybe one could use `record new { ... }` instead or something that is more local.

**Comment by be5invis** [comment]
@ahmadsalim `record new` is fine, also may be explicit typing: `record new Person {...}`.

**Comment by ahmadsalim** [comment]
@be5invis You are welcome to contribute it if you are interested. I am not sure why explicit typing is needed or preferred over just having an explicit record constructor.

**Comment by be5invis** [comment]
@ahmadsalim I am also curious about whether a record can have a point syntax, i.e. `tom.name` instead of `name top`.

**Comment by ahmadsalim** [comment]
@be5invis For larger design decision you probably need to discuss this on the mailing list. In any case, the probability of new features being implemented is fairly small if you do not implement them yourself (I learned that myself as well).

**Comment by jfdm** [comment]
Maybe, I do not understand the original issue here, but I thought records already have simple means to create records. For example:

```idris
record Foobar where
  constructor MkFoobar
  foo : String
  bar : Nat

myFoo : Foobar
myFoo = MkFoobar "Foobar" 42

newFoo : String -> Nat -> Foobar
newFoo = MkFoobar
```

**Comment by be5invis** [comment]
@jfdm The existing record construction uses positional parameters instead of named. This could be annoying.

**Comment by ahmadsalim** [comment]
PRs are welcome, but I will close the issue request since it has been a while and discussion has stalled.

**Comment by clayrat** [comment]
This would probably be solved by https://github.com/idris-lang/Idris-dev/issues/2488, were it ever finished :)
