### ISSUE TITLE
Pre- and postscripts for ipkg, so that we can standardize installation of packages.

### ISSUE THREAD

**Issue by Supernerd11** [idris-lang/Idris-dev#3769]
I'm trying to make a package manager for Idris, but have run into trouble when it comes to installing packages, as there are a lot of differences in installation. So I think standardizing installation and building would be a great help.

**Comment by ahmadsalim** [comment]
@Supernerd11 Could you kindly explain more what your goal is with this issue? I do not think I understand what the purpose is.

**Comment by Supernerd11** [comment]
Ignore this. It was nothing.
