### ISSUE TITLE
:exec error message

### ISSUE THREAD

**Issue by ankhers** [idris-lang/Idris-dev#3774]
I was recently playing around with the REPL and wanted to see an example output from `System.time`. So I did the following

```
Idris> :module System
*System> :exec time
main:When checking argument value to function Prelude.Basics.the:
        Type mismatch between
                IO Integer (Type of time)
        and
                Integer (Expected type)
```

I was expecting to get a value from the function. I have since found that `:exec` only works with functions that return unit.

If this is intentional, I would suggest a better error message stating that `:exec` only works for things that return unit.

**Comment by ostera** [comment]
Hey @ankhers, while you can work around this with `>>= print`, I agree that it would make sense to have an `:exec` that simply prints out the returning value (whatever that is). Thou I'm not representative of an Idris dev.

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue.

**Comment by ankhers** [comment]
@ahmadsalim Would you be able to say if this is expected behaviour and the error message should be improved, or should the value actually be shown?

**Comment by ahmadsalim** [comment]
@ankhers I am not sure what the expected behaviour should be, but I think it would be nicer if the value would be shown.

**Comment by jdevuyst** [comment]
I submitted a pull request for this: #3818

**Comment by jfdm** [comment]
Oops, we've forgotten to close the issue now that @jdevuyst fixed it. Thanks everyone!
