### ISSUE TITLE
foldr (*) 1 [1, 2, 3, 4, 5, 6, 7, 8] unreasonbly slow 

### ISSUE THREAD

**Issue by 1-p** [idris-lang/Idris-dev#3775]
`foldr (*) 1 [1, 2, 3, 4, 5, 6, 7, 8]` took about 30 seconds on a relatively modern CPU (2.3 GHz Intel Core i7). 

`foldl` is roughly the same. I don't know if this could be called a bug but definitely something that stops people from using it in practice.

**Comment by LeifW** [comment]
The REPL uses recursively defined peano nats, which are slow for large
numbers. If you compile your program to a binary they will be translated
into GMP bigints.

**Comment by ostera** [comment]
@1-p, you can coerce your list to be of Int's instead:

```idris
foldr (+) 0 (the (Vect _ Int) [1,2,3,4,5,6,7,8,9])
```

**Comment by 1-p** [comment]
@LeifW @ostera Thanks. Now it works better...

Maybe the REPL can add some hint on that for better user experience.

**Comment by jfdm** [comment]
I don't think we should provide a hint at the REPL just for Nats. It is too specific a message. Maybe a good work around would be to add to the REPL's welcome banner a message pointing to the specific FAQ, or the FAQs in general.:

http://idris.readthedocs.io/en/latest/faq/faq.html#evaluation-at-the-repl-doesn-t-behave-as-i-expect-what-s-going-on

Please feel free to do a PR. I shall probably do it towards the end of the day.

**Comment by ahmadsalim** [comment]
I will close the issue since this seems resolved. We have other issues regarding the performance of the type checker with Nats.
