### ISSUE TITLE
Unhelpful error message: 'No such variable __retTy' when user never wrote '__retTy'

### ISSUE THREAD

**Issue by xoltar** [idris-lang/Idris-dev#3779]
Idris 1.0, Ubuntu 16.04.

When compiling this simple example misquoted from Ch 8 Ex 2 of Edwin's book:

```
module RetTyBug
import Data. Vect

rev : Vect n a -> Vect n a
rev xs = rev' [] xs
  where rev' : Vect n a -> Vect m a -> Vect (n+m) a
        rev' acc [] = ?revProofNil acc
        rev' acc (y :: ys) = ?revProof_accs rev' (y::acc) ys

```

Type checking ./rettybug.idr
rettybug.idr:8:45:
When checking right hand side of RetTyBug.rev, rev' with expected type
        Vect (n + S len) a

No such variable __retTy
Holes: RetTyBug.rev

The problem is that parens are missing in the last line, it should be  `?revProof_accs (rev' (y::acc) ys)` . However, the error message is little help in discovering that, since __retTy looks like an internal implementation detail rather than anything the user wrote.

**Comment by mrkgnao** [comment]
You can also get this by triggering the `default#whatever` completions in the REPL (in Emacs).

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue. It seems that we have plenty of issue with these confusing error messages that are introduced by unsolvable meta-variables introduced internally in the compiler. I will close this issue as a duplicate, but contributions more than welcome!

**Comment by xoltar** [comment]
@ahmadsalim It would be helpful if you could include which issue this one duplicates, so we know which one to track.

**Comment by ahmadsalim** [comment]
@xoltar The are plenty of similar issues as can be seen by this search: https://github.com/idris-lang/Idris-dev/search?utf8=%E2%9C%93&q=No+such+variable&type=Issues

I hope we could consolidate the issues at some point.
