### ISSUE TITLE
Preserve more typing information in `LProj`/`DProj`/`SProj` 

### ISSUE THREAD

**Issue by be5invis** [idris-lang/Idris-dev#3782]
Currently Idris’ `LProj`/`DProj`/`SProj` only provides the object and the index, without typing information (like the constructor name), making it hard to optimize in the codegen level.

**Comment by edwinb** [comment]
Are there specific optimisations you want to do that you can't?

Type level optimisations (eg Nat -> Integer) are generally assumed to be done at a higher level. By the IR, there has been some pretty aggressive erasure and there may even have been some transformations which break types - for example, you can end up with functions that merely translate one type to another (e.g. Vect to List and vice versa) that run in linear time, which can be optimised to an identity function if you're aggressive enough about type erasure, so any codegen specific optimisation you do would have to take this sort of thing into account. (Chapter 6 of my thesis has a few examples of this, iirc...)

As far as Proj is concerned, you can assume that it's a constructor form and that the index is guaranteed to exist. As it happens, I don't think the currently compilation scheme generates any Proj nodes, but that isn't guaranteed to always be the case.

**Comment by be5invis** [comment]
Mainly for mapping Idris types to host types, for example, map Nothing directly to host Null, and Just to non-null values.

发自我的 iPhone

在 2017年4月25日，22:08，Edwin Brady <notifications@github.com<mailto:notifications@github.com>> 写道：


Are there specific optimisations you want to do that you can't?

Type level optimisations (eg Nat -> Integer) are generally assumed to be done at a higher level. By the IR, there has been some pretty aggressive erasure and there may even have been some transformations which break types - for example, you can end up with functions that merely translate one type to another (e.g. Vect to List and vice versa) that run in linear time, which can be optimised to an identity function if you're aggressive enough about type erasure, so any codegen specific optimisation you do would have to take this sort of thing into account. (Chapter 6 of my thesis has a few examples of this, iirc...)

As far as Proj is concerned, you can assume that it's a constructor form and that the index is guaranteed to exist. As it happens, I don't think the currently compilation scheme generates any Proj nodes, but that isn't guaranteed to always be the case.

**Comment by minad** [comment]
@be5invis Note that it is not possible to map Nothing to null, since you also want to represent `Just Nothing`.

**Comment by be5invis** [comment]
Another example would be better, like mapping Idris List or Either into the equivalent host types...

发自我的 iPhone

在 2017年4月25日，22:32，Daniel Mendler <notifications@github.com<mailto:notifications@github.com>> 写道：


@be5invis<https://github.com/be5invis> Note that it is not possible to map Nothing to null, since you also want to represent Just Nothing.

**Comment by edwinb** [comment]
Indeed, as @minad says. Even so, I think this would be better done at a higher level to benefit all codegens (not that we have a framework to talk about this sort of thing yet.) Same for other higher level types.

**Comment by be5invis** [comment]
@edwinb The key is that, different backend may prefer different mapping strategy. For example, if I am writing a backend targeting Scheme I'd like to map Idris list into Scheme list. However if the target is C, then preserving Idris data constructors may be a better idea.

**Comment by ahmadsalim** [comment]
Personally, I can see advantages of providing more typing information in the IR to guide optimizations of representations. Although, I agree that it would also be nice to allow more of these optimizations at high-level à la https://infoscience.epfl.ch/record/214606/files/EPFL_TH6850.pdf . 

In any case, I would guess that a PR is more than welcome (unless @edwinb disagrees).

**Comment by ahmadsalim** [comment]
Since no PR has been suggested for a while I will close this feature request. 
PRs are still welcome if anyone is interested!
