### ISSUE TITLE
Misleading error message for missing interface implementation when overloaded names are used

### ISSUE THREAD

**Issue by esmolanka** [idris-lang/Idris-dev#3785]
When both interface implementation search and name disambiguation come into play, the error messages might be a bit misleading.

```
data Foo : Type where
  MkFoo : Foo

displayFoo : Foo -> String
displayFoo foo = "This is Foo: " ++ show foo
```

Gives the following error message:

```
foo.idr:5:12:When checking right hand side of displayFoo with expected type
        String

Can't disambiguate since no name has a suitable type:
        Prelude.List.++, Prelude.Strings.++
```

However with concrete `(++)` the message is much better:

```
displayFoo' : Foo -> String
displayFoo' foo = the (String -> String -> String) (++) "This is Foo: " (show foo)
```

Gives:

```
foo.idr:8:23:When checking right hand side of displayFoo' with expected type
        String

Can't find implementation for Show Foo
```

On the other hand, function `show` always returns `String`, so this fact could be used in search of `(++)` with its second argument with type `String`.

(Reproduces in Idris 1.0)

**Comment by ahmadsalim** [comment]
This is a hard issue to solve, because it is not clear which error message should be prioritized.  In any case #3162 highlights a similar issue, so I will close this as a duplicate.
