### ISSUE TITLE
Totality checking for interface implementations

### ISSUE THREAD

**Issue by Synthetica9** [idris-lang/Idris-dev#3788]
Take the following code sample:

```idris
module Test

data Vect : (len : Nat) -> (elem : Type) -> Type where
  Nil  : Vect Z elem
  (::) : (x : elem) -> (xs : Vect len elem) -> Vect (S len) elem

Semigroup (Vect Z a) where
  [] <+> [] = []

Semigroup a => Semigroup (Vect (S n) a) where
  (x :: xs) <+> (y :: ys) = (x <+> y) :: (xs <+> ys)
```

This doesn't compile, with the following error:

```
When checking right hand side of Prelude.Algebra.Test.Vect (S n) a implementation of Prelude.Algebra.Semigroup, method <+> with expected type
        Vect (S n) a

When checking argument xs to constructor Test.:::
        Can't find implementation for Semigroup (Vect n a)
```
I would expect the compiler to be smart enough to infer that we have defined instances for all constructors of `Nat`, sort of like totality checking. This is clearly not the case. Has this use case just not been considered, is it hard to implement, or is there another reason this has not been implemented?

(The approach I outlined in the code sample has the upside that you can leave out the `Semigroup a =>` restraint for the empty `Vect`, for those who missed it)

**Comment by ahmadsalim** [comment]
@Synthetica9 I am not sure there is a nice algorithm to 'totality check' interface implementations; at least it is not trivial. This is especially considering that one can also have named interfaces and there is no requirement that one must implement an interface covering all possible instantiations of indices.

As for your code, it should work if one has:

```idris
(Semigroup a, Semigroup (Vect n a)) => Semigroup (Vect (S n) a) where
  (x :: xs) <+> (y :: ys) = (x <+> y) :: (xs <+> ys)
```

**Comment by ahmadsalim** [comment]
I have closed the issue since this is expected behaviour, and I am unsure how to fix it. If you have a suggestion on how to fix this, and perhaps is willing to implement it, then I would not mind reopening the issue.

**Comment by ahmadsalim** [comment]
In any case, thanks for reporting the issue.
