### ISSUE TITLE
Allow paramterising blocks with implementation arguments

### ISSUE THREAD

**Issue by mrkgnao** [idris-lang/Idris-dev#3789]
This fails to find a `Ring` instance for Double:

```idris
DoubleRing : Ring Double 0.0 Add 1.0 Mul
DoubleRing = DeriveRing.AbMonoid

DefaultDouble : {default DoubleRing ring : Ring Double z a o m} -> Ring Double z a o m
DefaultDouble {ring} = ring

using implementation DefaultDouble
  t : Double -> Double -> Double
  t x y = (+..) @{%implementation} x y
```

(I first thought that was because `%implementation` looked for an implementation "globally", but using `@{_}` or leaving it out completely doesn't help either.)

But this works fine:

```idris
DoubleRing : Ring Double 0.0 Add 1.0 Mul
DoubleRing = DeriveRing.AbMonoid

DefaultDouble : {default DoubleRing ring : Ring Double z a o m} -> Ring Double z a o m
DefaultDouble {ring} = ring

using implementation DefaultDouble
  t : Double -> Double -> Double
  t x y = (+..) @{im} x y
    where im : Ring Double z a o m
          im = %implementation
```

Are there any other such "tips" on helping the instance search do things one wants it to do? In particular, I'd like to do something like

```idris
using implementation (default SomeInstance inst : Interface param anotherparam)
   -- code
```

**Comment by ahmadsalim** [comment]
As far as I know this is currently the only way. 
What is the semantics of your suggested code in the end?

**Comment by mrkgnao** [comment]
Essentially, what I'm looking for is to parameterize a block of code over an implementation, i.e. something like

```idris
using (inst : Interface a b)
  f : a -> Foo b
  f = g @{inst}
```

where I'd expect `foo` to have a type like `Interface a b => a -> Foo b`. Some of this could possibly be alleviated by allowing constructor-created/named implementations to be available during instance resolution, which I think isn't supported at the moment.

**Comment by ahmadsalim** [comment]
@mrkgnao I see, thanks for the suggestion. If you are interested in implementing this feature request, you could try to take a look how to extend `parameters` blocks to support e.g. implicit and implementation arguments.

**Comment by mrkgnao** [comment]
@ahmadsalim where should I look in the code?

**Comment by ahmadsalim** [comment]
@mrkgnao The main part is the elabroration here: https://github.com/idris-lang/Idris-dev/blob/c271f587a09ef88e3e55c47fd3a7a0afa9a4a923/src/Idris/ElabDecls.hs#L264 . However, also look in the parser if you need to make a change.

Could you elaborate more what you mean by it becoming unavailable?

**Comment by mrkgnao** [comment]
@ahmadsalim the second code block in

https://github.com/idris-lang/Idris-dev/issues/3114#issuecomment-297325502 

shows what I'm thinking of.

**Comment by ahmadsalim** [comment]
@mrkgnao I think we are delving deeply in the design of the language here, so I am unsure what to answer regarding subsumption of issues.

I think you are right in that it would be useful if the named super-interface arguments are available in the body of the interface itself.

**Comment by ahmadsalim** [comment]
I think the discussion here has been stalled, and since there has been no progress on implementation I will close the feature request.
