### ISSUE TITLE
Can't compile due to trailing backslash in gcc args on Windows

### ISSUE THREAD

**Issue by meta-inf** [idris-lang/Idris-dev#3801]
Version: 1.0-git:e6575c2b

On Windows, the compiler adds trailing backslash in include and link path when calling gcc, which seems to invalidate these paths (at least for the gcc included in MSYS2 and Haskell Platform). Could you change the behavior?

e.g. the call to gcc below works iff the trailing `\\` are removed in `-I` and `-L ...\\idris-1.0\\rts\\`.
```
idris ffi.idr -o ffi.exe
C:\Users\w\AppData\Local\Temp\idris9961491.c:3:23: fatal error: idris_rts.h: No such file or directory
compilation terminated.
FAILURE: "gcc" ["-O2","-fwrapv","-fno-strict-overflow","-DHAS_PTHREAD","-DIDRIS_ENABLE_STATS","-I.",".\\lib.o","C:\\Users\\w\\AppData\\Local\\Temp
\\idris9961491.c","-LC:\\Users\\w\\AppData\\Roaming\\cabal\\x86_64-windows-ghc-8.0.2\\idris-1.0\\rts\\","-lidris_rts","-lpthread","-IC:\\Users\\w\
\AppData\\Roaming\\cabal\\x86_64-windows-ghc-8.0.2\\idris-1.0\\rts\\","-lm","-I.","-I.","-IC:\\Users\\w\\AppData\\Roaming\\cabal\\x86_64-windows-g
hc-8.0.2\\idris-1.0\\libs\\prelude","-IC:\\Users\\w\\AppData\\Roaming\\cabal\\x86_64-windows-ghc-8.0.2\\idris-1.0\\libs\\base","-Wl,--stack,167772
16","-o","ffi.exe"]
```

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue

**Comment by melted** [comment]
Not seeing this with MSYS gcc. I don't use the GHC gcc though. And that one broke on the Windows 10 update last month.  Even if not, they have something in front of gcc (and the real gcc has been renamed realgcc.exe), so it might be related to that. I'll test GHC's gcc and put in a fix, it shouldn't break anything.

**Comment by melted** [comment]
Yes, it's broken in GHC's gcc, even the updated ones they posted to fix the latest issue. I'll post a fix. 

I suppose this should be fixed in their wrapper too (if it's that which causes it, which seems likely to me).
