### ISSUE TITLE
Provide better error messages when **all** overloads of a name direct to a typing error

### ISSUE THREAD

**Issue by be5invis** [idris-lang/Idris-dev#3802]
Like this:

```idris
whatever : [Int] -> Int
```

Idris reports
```
When checking type of whatever:
Can't disambiguate since no name has a suitable type: 
        Prelude.List.::, Prelude.Stream.::
```

However in this situation **all** versions of `(::)` would cause an error.

Should we replace the word to clarify it?

**Comment by ahmadsalim** [comment]
@be5invis I think it already states what you mean (albeit using a double negative). 
You are welcome to suggest a better wording with a PR if you are interested 😄.

**Comment by be5invis** [comment]
@ahmadsalim "Disambiguating" may be misleading since in this situation, all versions would lead to typing error.
Perhaps a sentence like "All overloads of `(::)` led to typing error..." and show the errors below.

**Comment by ahmadsalim** [comment]
@be5invis Again, you are more than welcome to make a PR if you are interested in changing the error message to make it more clear.
