### ISSUE TITLE
GC incorrectly frees old heap before copying

### ISSUE THREAD

**Issue by bmaxa** [idris-lang/Idris-dev#3814]
Old heap should be freed after collection.

**Comment by ahmadsalim** [comment]
@bmaxa Thanks for reporting the issue.
We welcome Pull Requests if you have an idea how to fix this.

**Comment by bmaxa** [comment]
fix si simple just delay free. eg:

void idris_gc(VM* vm) {
....
    void *old_heap=0;
    if (vm->heap.old != NULL){
        printf("freeing\n");
        old_heap = vm->heap.old;
        //free(vm->heap.old);
    }
....
    HEAP_CHECK(vm)
    free(old_heap);
}
