### ISSUE TITLE
Add `StablePtr` analogous in Idris, to make it possible to access Idris data from C without the GC accidentally freeing it

### ISSUE THREAD

**Issue by bmaxa** [idris-lang/Idris-dev#3815]
This is useful to implement global variable that is held in C data. I use this to implement global table for callback purpose.

eg:

```c
static struct Data {
    VAL* p_;
    VM* vm_;
} data[256] = {0};
static int next;
void register_for_update(VAL* p){
    printf("next %d\n",next);
    data[next].p_ = p;
    data[next].vm_ = get_vm();
    next++;
}
```

and 
```c
for (int i = 0;i<256;++i){
        if (data[i].p_ && data[i].vm_ == vm ){
            printf("copying %d\n",i);
            *data[i].p_ = copy(vm,*data[i].p_);
            printf("done %d\n",i);
        }
 }
```

**Comment by ahmadsalim** [comment]
@bmaxa I am not sure I understand what the feature request is about.
Could you please elaborate with an Idris example as well?

**Comment by bmaxa** [comment]
This is useful for passing global data to Idris call back eg:
callme : Bits64 -> Bits64 -> String -> Bits64
callme a b c = unsafePerformIO $ do {
  ref <- refp;
  m <- readIORef ref;
.....
refp : IO(IORef(SortedMap Int String))
refp = do
  MkRaw ref <- foreign FFI_C "getp" (IO (Raw (IORef(SortedMap Int String))))
  pure ref
......
ccall : IO Bits64
ccall = foreign FFI_C "ccall" (CFnPtr (Bits64->Bits64->String->Bits64) -> IO Bits64) (MkCFnPtr callme)

and in c code:
VAL v;

void setp(VAL p){
    register_for_update(&v);
    v = p;
}
VAL getp() {
    return v;
}

**Comment by melted** [comment]
Is the use case for this something like StablePtr in Haskell? That is, do you need to turn`an Idris value into a C pointer and send it through C without the GC deleting it while it's outside Idris code?

**Comment by bmaxa** [comment]
No, I just want to keep Idris value as opaque type. This is because I need global table of callbacks as I call from C idris function. Idris function gets table from c and resolves callback. I actually keep reference to table in Idris code. This is not needed if I could pass Raw to Idris callback as I can to C function.

**Comment by ahmadsalim** [comment]
Ok, I will update the title.

**Comment by bmaxa** [comment]
I have to note that implementing stableptr requires much more effort then what I propose ;)
Actually I have shown whole implementation that I use now ;p

**Comment by jfdm** [comment]
How does this compare/differ to `ManagedPtr`?

**Comment by bmaxa** [comment]
Differs that I want to point to Idris data from C, and that pointer needs to be updated. If C has reference to managedptr it is not updated so it has to be passed before use as I understand. So ManagedPtr solves completely different issue.
What I want is actually way to implement global variable in Idris.

**Comment by jfdm** [comment]
Okay, I understand the issue now. Not sure if I support it, but would need to think about it more.

**Comment by ahmadsalim** [comment]
I will close the issue since it has not come up again, people are welcome to reopen it if they are interested at contributing a PR.
