### ISSUE TITLE
Segmentation fault on setting byte of small buffer

### ISSUE THREAD

**Issue by TartanLlama** [idris-lang/Idris-dev#3828]
I get a segmentation fault when I try to create a `Data.Buffer` with a size less than 4 and call `setByte` on it.

Reproduction:

```
module Main

import Buffer

main : IO()
main = do
     buf <- newBuffer 3
     doSet buf
  where
    doSet (Just buf) = setByte buf 0 0
    doSet (Nothing) = pure ()
```

If you change that `3` to a `4` then the program runs to completion.

Idris version 1.0 from Cabal
Linux Mint 18 Sarah

**Comment by melted** [comment]
Thanks for the bug report!

**Comment by melted** [comment]
Looks like there's some confusion in the buffer handling.
