### ISSUE TITLE
Can't cast from String to String

### ISSUE THREAD

**Issue by julian-becker** [idris-lang/Idris-dev#3833]
I was just following along the first chapter of the idris book, when I came across the example of `StringOrInt`. This was just after having read about the function `cast` which can be used to cast a character to a string. So naturally, I wanted to print out the result of a call to

    getStringOrInt : (x : Bool) -> StringOrInt x

So, I did 

    main : IO ()
    main = putStrLn (cast (getStringOrInt True))

which worked just fine, but when I tried 

    main : IO ()
    main = putStrLn (cast (getStringOrInt False))

Sadly, it won't typecheck. Doing the same in the interactive interpreter I get the following:

    *Hello> putStrLn (cast "already a String") 
    When checking an application of function Prelude.Interactive.putStrLn:
            Can't cast from String to String

I would expect the cast to work (since it's the trivial case of no conversion) and having this cast work would me to write more generic code.

I can probably do a pull-request to add/extend the generic identity cast in the Prelude if that is desired.

**Comment by melted** [comment]
The idea has been rejected before https://github.com/idris-lang/Idris-dev/issues/3479.
