### ISSUE TITLE
Casting to wrong type by pattern matching on a type.

### ISSUE THREAD

**Issue by lambda-11235** [idris-lang/Idris-dev#3839]
The following code compiles but segfaults when ran.
```
module Main

foo : (a : Type) -> (b : Type) -> a -> b
foo a a x = x

boo : Bool
boo = foo Int Bool 9

main : IO ()
main = print (boo == True)
```
In the REPL `boo` evaluates to `9 : Bool`.

**Comment by ahmadsalim** [comment]
@lambda-11235 Thanks for reporting the issue.
This does seem wrong, and should definitely not type check.

**Comment by lambda-11235** [comment]
I don't if this will help, but I discovered the bug by looking at the core code for
``` idris
eqId : (a : Type) -> (b : Type) -> a = b -> a -> b
eqId _ _ Refl x = x
```

Which is
``` idris
eqId : (a : Type) → (b : Type) → (__pi_arg : = Type Type a b) → (__pi_arg3 : a) → b
var a : Type, x : a .
  eqId a a (Refl <<<erased>>> <<<erased>>>) x ↦ x
```

`foo` was thus a function where I simply left out the argument `a = b`. Hope that helps!

**Comment by edwinb** [comment]
Oops, sorry to have left this so long. I've just looked at the code - What is *supposed* to happen is that, if there's any repeated variables on the left hand, those positions have to be solvable by unification. However, that isn't happening in this case and instead it's solving a metavariable it shouldn't be.

Just in case anyone finds it worrying that I'm leaving unsoundness bugs for so long: Sorry - I can mostly only do this in my spare time, and for the last few months I've been working on a new system which is taking into account the more serious issues we have at the moment. In the long term, I think this is a much better use of time and will result in a much better system, but it may take a while. More on this reasonably soon, I hope (and perhaps in a more prominent place than comment on a github issue when the time comes :))
