### ISSUE TITLE
Type system thinks a case is possible with auto proofs

### ISSUE THREAD

**Issue by Risto-Stevcev** [idris-lang/Idris-dev#3862]
When a data constructor in a type uses an auto proof to constrain the type, Idris correctly doesn't let you construct the type unless it also satisfies the proof, but it will incorrectly think that it's a valid case in pattern matching:

```idris
data CatQueue a = MkCatQueue (List a) (List a)

data EitherNonEmpty : (l : List a) -> (r : List b) -> Type where
  LeftNonEmpty  : {auto leftNonEmpty  : NonEmpty l} -> EitherNonEmpty l r
  RightNonEmpty : {auto rightNonEmpty : NonEmpty r} -> EitherNonEmpty l r

data NonEmptyQueue : CatQueue a -> Type where
  IsNonEmptyQueue : {x : List a} ->
                    {y : List a} ->
                    {auto eitherNonEmpty : EitherNonEmpty x y} ->
                    NonEmptyQueue (MkCatQueue x y)

bbbb : NonEmptyQueue (MkCatQueue [] [])
bbbb = IsNonEmptyQueue
{-
./Data/CatQueue.idr:110:8-23:When checking right hand side of bbbb with expected type
        NonEmptyQueue (MkCatQueue [] [])
When checking argument eitherNonEmpty to constructor Data.CatQueue.IsNonEmptyQueue:
        Can't find a value of type
                EitherNonEmpty [] []
-}


qqqq : (q : CatQueue a) -> {auto prf : NonEmptyQueue q} -> Unit
qqqq (MkCatQueue [] []) impossible
qqqq (MkCatQueue xs ys) = ?qqqq_rhs_1
{-
./Data/CatQueue.idr:122:6:qqqq (MkCatQueue [] []) is a valid case
-}
```

**Comment by ahmadsalim** [comment]
@Risto-Stevcev As we discussed on IRC, then this is perfectly reasonable, so I will close the issue.
It requires more than just unification to see that `NonEmptyQueue (MkCatQueue [] [])` and an implicit absurdity proof is needed.

**Comment by Risto-Stevcev** [comment]
Can you give a little bit of context for those that aren't aware of our discussion on IRC?
Why is this issue closed? removing the implicit and adding an Uninhabited instance that you suggested on IRC didn't work

**Comment by ahmadsalim** [comment]
@Risto-Stevcev 
It will only figure out that `NonEmptyQueue (MkCatQueue [] [])` is impossible if it can by unification determine that this is true. However your data-type has the following signature for the constructor `NonEmptyQueue (MkCatQueue x y)`, and so it can not exclude the case by just looking at the indices.

You have to add an Uninhabited instance and use it, i.e.

```idris
implementation Uninhabited (NonEmptyQueue (MkCatQueue [] [])) where
   absurd = ?proof_here

-- ...

qqqq : (q : CatQueue a) -> {auto prf : NonEmptyQueue q} -> Unit
qqqq (MkCatQueue [] []) {prf} = absurd prf
qqqq (MkCatQueue xs ys) = ?qqqq_rhs_1
```

**Comment by Risto-Stevcev** [comment]
Ah ok, thanks that makes sense
