### ISSUE TITLE
Compiling Hello.c via gcc after: idris -S -o Hello.c Hello.idr

### ISSUE THREAD

**Issue by 0xMF** [idris-lang/Idris-dev#3866]
I couldn't find help in the usual places (wiki/man pages/mailing list/grep for "gcc" on source tree), so opening issue as I'm a new to Idris and am drawn to using Idris for its C backend. Steps to reproduce:

$ cd samples/tutorial
$ idris -S -o Hello.c Hello.idr
$ pushd ../../rts
$ make
....
$ popd
$ gcc -pthread Hello.c -lidris_rts -e _idris_Main_46_main -I ../../rts/ -L ../../rts
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status

$ gcc --version
gcc (Debian 6.3.0-18) 6.3.0 20170516

Very likely, I may've missed something obvious.

**Comment by ahmadsalim** [comment]
As far as I understand, the output code is not meant to be compiled by GCC manually.
I think it is possible, but you have to take a look at how Idris calls GCC internally. Is there a reason you are trying to manually compile the file?

**Comment by ahmadsalim** [comment]
If you are interested concretely, take a look here:
https://github.com/idris-lang/Idris-dev/blob/32a05ba077aeb65002096bba157f5edd78593c4c/src/IRTS/CodegenC.hs#L80-L98

**Comment by melted** [comment]
There's a difference how it works in the code generator, it pastes in idris_main.c at the end of the file to be built, maybe that makes a difference. It would be nice if the files output with -S would build.

**Comment by 0xMF** [comment]
I built idris with patch #3867 included, however, even with that patch and the separate compilation working correctly, I get a segfault when I run the generated executable. Steps to reproduce:

$ cd samples/tutorial
$ ../../.cabal-sandbox/bin/idris -S -o Hello.c Hello.idr
$ gcc -Wall -DHAS_PTHREAD Hello.c ../../rts/idris_main.c -lpthread -lidris_rts -I ../../rts -L ../../rts 2>&1 |tee /tmp/log

$ ./a.out
Hello world
Segmentation fault

Contents of /tmp/log (trimmed)

-- [begin] --

In file included from Hello.c:2:0:
Hello.c: In function ‘_idris_assert_95_unreachable’:
../../rts/idris_rts.h:238:24: warning: unused variable ‘myoldbase’ [-Wunused-variable]
 #define INITFRAME VAL* myoldbase
                        ^
Hello.c:65:5: note: in expansion of macro ‘INITFRAME’
     INITFRAME;
     ^~~~~~~~~
Hello.c: In function ‘_idris_call_95__95_IO’:
../../rts/idris_rts.h:238:24: warning: unused variable ‘myoldbase’ [-Wunused-variable]
 #define INITFRAME VAL* myoldbase

--[snip/end]--

$ pwd 
/home/mark/repos/Idris-dev/samples/tutorial
$ ../../.cabal-sandbox/bin/idris --version
1.0-git:180fc753
$ gcc -version
gcc (Debian 6.3.0-18) 6.3.0 20170516

Meanwhile, the executable created directly from Hello.idr works fine.

$ ../../.cabal-sandbox/bin/idris Hello.idr -o Hello
$ ./Hello
Hello world

**Comment by melted** [comment]
You need -DIDRIS_ENABLE_STATS too, loke at CodegenC.hs

**Comment by 0xMF** [comment]
Works.

$ gcc -Wall -DHAS_PTHREAD -DIDRIS_ENABLE_STATS Hello.c -lpthread -lidris_rts -I ../../rts -L ../../rts
$ ./a.out
Hello world
$

It'd be nice if it compiled without warnings. Thanks @melted

**Comment by 0xMF** [comment]
Using latest Idris commits, I was able to compile without warnings and run without crashing, however, based on these results if someone with more experience with the Idris codebase might be in a better position to decide if a patch (if possible) so the default auto generated C code standalone compiles without warnings and runs without crashing can be done. Steps to reproduce:

$ pwd
/home/mark/repos/Idris-dev/samples/tutorial
$ ../../.cabal-sandbox/bin/idris --version
1.0-git:d9e3a207

$ ../../.cabal-sandbox/bin/idris -S -o Hello.c Hello.idr
$ rm -f ./a.out
$ gcc -Wall -DHAS_PTHREAD -DIDRIS_ENABLE_STATS Hello.c ../../rts/idris_main.c -lpthread -lidris_rts -I ../../rts -L ../../rts 2> /tmp/log
$ ./a.out
Hello world
$ wc -l /tmp/log
393 /tmp/log

$ rm -f ./a.out 
$ cp Hello.c Hello-no-warnings.c

....[ hand edited Hello-no-warnings.c to remove all warnings and run without crashing ]...

$ gcc -Wall -DHAS_PTHREAD -DIDRIS_ENABLE_STATS Hello-no-warnings.c ../../rts/idris_main.c -lpthread -lidris_rts -I ../../rts -L ../../rts 2> /tmp/log
$ ./a.out 
Hello world
$ wc -l /tmp/log 
0 /tmp/log

The warnings were caused with INITFRAME macro expansion, but not all lines from the C file could be removed since some functions needed that macro. The ones that must have the INITFRAME macro for the Hello.idr example are:

$ grep -wC 1 INITFRAME Hello-no-warnings.c
void _idris_io_95_bind(VM* vm, VAL* oldbase) {
    INITFRAME;
    RESERVE(2);
--
void _idris__123_runMain_95_0_125_(VM* vm, VAL* oldbase) {
    INITFRAME;
    RESERVE(2);
--
void _idris__123_io_95_bind_95_1_125_(VM* vm, VAL* oldbase) {
    INITFRAME;
    RESERVE(1);

Basically, the (unused variable) warning message I got with the default inclusion of the INITFRAME macro expansion in every C function was:

In file included from Hello.c:2:0:
Hello.c: In function ‘_idris_assert_95_unreachable’:
../../rts/idris_rts.h:245:24: warning: unused variable ‘myoldbase’ [-Wunused-variable]
                   VAL* myoldbase
                        ^
Hello.c:65:5: note: in expansion of macro ‘INITFRAME’
     INITFRAME;
     ^~~~~~~~~
Hello.c: In function ‘_idris_call_95__95_IO’:
../../rts/idris_rts.h:245:24: warning: unused variable ‘myoldbase’ [-Wunused-variable]
                   VAL* myoldbase
                        ^

I realize creating a patch based on the blanket approach of removing INITFRAME from all functions but the 3 required above might not work for all Idris source files since this is only the Hello example.

**Comment by 0xMF** [comment]
The changes boil down to this:

INITFRAME can be removed from all functions except:
```
void _idris_io_95_bind(VM* vm, VAL* oldbase) {
void _idris__123_runMain_95_0_125_(VM* vm, VAL* oldbase) {
void _idris__123_io_95_bind_95_1_125_(VM* vm, VAL* oldbase) {
```
INITFRAME cannot be removed from those 3 functions because the STOREOLD macro in those same functions need myoldbase variable got from the INITFRAME expansion. Whether all these other functions are needed for the Hello example I can't say but they are probably needed in the general case. Still if there were a way to detect the presence of STOREOLD and only then add INITFRAME might be something that could be looked at further (if need be). The functions from where INITFRAME was removed and still compiled and run with no problems are:

```
void _idris_assert_95_unreachable(VM* vm, VAL* oldbase) {
void _idris_call_95__95_IO(VM* vm, VAL* oldbase) {
void _idris_idris_95_crash(VM* vm, VAL* oldbase) {
void _idris_io_95_pure(VM* vm, VAL* oldbase) {
void _idris_Main_46_main(VM* vm, VAL* oldbase) {
void _idris_mkForeignPrim(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_asPtr(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_eqManagedPtr(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_eqPtr(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_null(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_peek16(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_peek32(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_peek64(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_peek8(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_peekDouble(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_peekPtr(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_peekSingle(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_poke16(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_poke32(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_poke64(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_poke8(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_pokeDouble(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_pokePtr(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_pokeSingle(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_ptrOffset(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_readChars(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_readFile(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_registerPtr(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_sizeofPtr(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_stderr(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_stdin(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_stdout(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_vm(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_writeFile(VM* vm, VAL* oldbase) {
void _idris_prim_95__95_writeString(VM* vm, VAL* oldbase) {
void _idris_prim_95_io_95_bind(VM* vm, VAL* oldbase) {
void _idris_prim_95_write(VM* vm, VAL* oldbase) {
void _idris_Prelude_46_Interactive_46_putStr_39_(VM* vm, VAL* oldbase) {
void _idris_run_95__95_IO(VM* vm, VAL* oldbase) {
void _idris_unsafePerformPrimIO(VM* vm, VAL* oldbase) {
void _idris_world(VM* vm, VAL* oldbase) {
void _idris__123_APPLY_95_0_125_(VM* vm, VAL* oldbase) {
void _idris__123_APPLY2_95_0_125_(VM* vm, VAL* oldbase) {
void _idris__123_EVAL_95_0_125_(VM* vm, VAL* oldbase) {
void _idris__123_io_95_bind_95_0_125_(VM* vm, VAL* oldbase) {
void _idris_Prelude_46_Interactive_46__123_putStr_39__95_0_125_(VM* vm, VAL* oldbase) {
void _idris__123_io_95_bind_95_2_125_(VM* vm, VAL* oldbase) {
void _idris_Decidable_46_Equality_46_Decidable_46_Equality_46__64_Decidable_46_Equality_46_DecEq_36_Char_58__33_decEq_58_0_58_primitiveNotEq_58_0(VM* vm, VAL* oldbase) {
void _idris_Decidable_46_Equality_46_Decidable_46_Equality_46__64_Decidable_46_Equality_46_DecEq_36_Int_58__33_decEq_58_0_58_primitiveNotEq_58_0(VM* vm, VAL* oldbase) {
void _idris_Decidable_46_Equality_46_Decidable_46_Equality_46__64_Decidable_46_Equality_46_DecEq_36_Integer_58__33_decEq_58_0_58_primitiveNotEq_58_0(VM* vm, VAL* oldbase) {
void _idris_Decidable_46_Equality_46_Decidable_46_Equality_46__64_Decidable_46_Equality_46_DecEq_36_ManagedPtr_58__33_decEq_58_0_58_primitiveNotEq_58_0(VM* vm, VAL* oldbase) {
void _idris_Decidable_46_Equality_46_Decidable_46_Equality_46__64_Decidable_46_Equality_46_DecEq_36_Ptr_58__33_decEq_58_0_58_primitiveNotEq_58_0(VM* vm, VAL* oldbase) {
void _idris_Decidable_46_Equality_46_Decidable_46_Equality_46__64_Decidable_46_Equality_46_DecEq_36_String_58__33_decEq_58_0_58_primitiveNotEq_58_0(VM* vm, VAL* oldbase) {
void _idris_io_95_bind_95_IO_95__95_idr_95_107_95_34_95_case(VM* vm, VAL* oldbase) {
void _idris_Void_95__95__95_casefun_95__95_Void_95__95__95_case(VM* vm, VAL* oldbase) {
void _idris_Void_95_elim(VM* vm, VAL* oldbase) {
```

**Comment by melted** [comment]
The usage of it will differ depending on the program compiled, I think it's an unnecessary fix to introduce a lot of bookkeeping just to keep the generated code neat (it's perfectly legal to introduce an unused variable and it will be optimized out in the end product).
