### ISSUE TITLE
src/Idris/REPL.hs:(823,1)-(1460,70): Non-exhaustive patterns in function process

### ISSUE THREAD

**Issue by zilinc** [idris-lang/Idris-dev#3883]
In version 1.0 REPL, if I do `:verbosity 1`, it splits out the above error.

**Comment by ahmadsalim** [comment]
Thanks for reporting the error!

**Comment by mdimjasevic** [comment]
Hi all!

I'd like to work on this issue as my first contribution to Idris.

I looked at patterns for the `process` function in `src/Idris/REPL.hs` and identified the following 7 patterns that are not matched at the moment:

```haskell
process fn Quit = ?process_quit
process fn Reload = ?process_reload
process fn Watch = ?process_watch
process fn (Load filePath maybeInt) = ?process_load
process fn Edit = ?process_edit
process fn Proofs = ?process_proofs
process fn (Verbosity i) = ?process_verbosity
```

User {AS} from the IRC channel suggested to provide a user facing error for these cases, as a starting point. I guess that would be something like:

```haskell
process fn Quit = iPrintError "Unimplemented pattern for command Quit"
```

Would that be a good implementation or should I implement something more useful?

**Comment by mdimjasevic** [comment]
Pull request #4054 addressed this issue so it is ready to be closed.
