### ISSUE TITLE
Function doesn't reduce

### ISSUE THREAD

**Issue by zenon** [idris-lang/Idris-dev#3885]
Hi, 

in the below code, the result of a function call is not reduced to normal form, but when I try the computation in the REPL, it works fine. Is this a bug? I use Idris 1.0 with Windows.

Code:

```idris
integerSqrt : Integer -> Integer
integerSqrt 0 = 0
integerSqrt n = 
  if n < 2 then
    n
  else
    let
      smallCandidate = (integerSqrt (div n 4)) * 2
      largeCandidate = smallCandidate + 1
      in if largeCandidate * largeCandidate > n then
           smallCandidate
         else
           largeCandidate

step : (Integer, Integer, Integer) -> Integer
step (p, d, q) = div (p + (integerSqrt d)) q

s : (Integer, Integer, Integer)
s = (25,53,22)
```

The call `step s` gives the unreduced result

```idris
λΠ> step s
Prelude.Interfaces.Integer implementation of Prelude.Interfaces.Integral, method div (prim__addBigInt 25
                                                                                                      (integerSqrt 53))
                                                                                     22 : Integer
```
But the following gives the expected result:

```idris
λΠ> div (25 + (integerSqrt 53)) 22
1 : Integer
```

**Comment by zenon** [comment]
[issue01.txt](https://github.com/idris-lang/Idris-dev/files/1102969/issue01.txt)

issue01.txt contains formatted Idris code.

**Comment by ahmadsalim** [comment]
Thanks for the issue. I am unsure whether this is a bug, but it certainly seems non-intuitive.

Perhaps @edwinb can weigh in, on whether this is expected behaviour for reduction?

**Comment by zenon** [comment]
PS.: A workaround would make me happy too.

**Comment by ahmadsalim** [comment]
@zenon What version of Idris are you using? It seems to work in the latest version, so I will close the issue.

**Comment by zenon** [comment]
Version 1.0

**Comment by ahmadsalim** [comment]
@zenon I am running on the git version. You can either try building manually or waiting until next release. If you still find the issue on the next release, we can reopen.

**Comment by zenon** [comment]
Thank you.
