### ISSUE TITLE
The implementation of Foldable (Vect n).

### ISSUE THREAD

**Issue by Junology** [idris-lang/Idris-dev#3890]
Please tell me why Foldable (Vect n) has such a complicated implementation:
```idris
foldrImpl : (t -> acc -> acc) -> acc -> (acc -> acc) -> Vect n t -> acc
foldrImpl f e go [] = go e
foldrImpl f e go (x::xs) = foldrImpl f e (go . (f x)) xs

implementation Foldable (Vect n) where
foldr f e xs = foldrImpl f e id xs
```
I am asking this question because I need to have a proof of the following type.
```idris
prop_sum : {x : Nat} -> {xs : Vect n Nat} -> sum (x::xs) = x + sum xs
```
This _obvious_ proposition is not actually obvious with ``Foldable (Vect n)`` above.
Note it is obvious for ``List`` since it has a straightforward implementation of ``Foldable``.

**Comment by jfdm** [comment]
@Junology Thanks for taking the time to ask a question about Idris. However, the issue tracker is not the most appropriate place to ask questions about programming in Idris. The issue tracker is for documenting problems with Idris' implementation. 

We do have an IRC channel (#idris) on freenode, and a [mailing list](https://groups.google.com/forum/#!forum/idris-lang) in which these questions are best asked.

Thanks.

**Comment by Junology** [comment]
Thank you for the reply, but I don't think my question is about _programming in Idris_.
In fact, I am able to write the actual term of ``prop_sum``, and it is not the point.
I am sorry for the misleading question.
The point is, as I wrote, the reason why ``Vect n`` has an implementation of ``Foldable`` very different from that of ``List``.
To be honest, I would like to say it should not be so.

**Comment by ahmadsalim** [comment]
@Junology Have you tried writing the `fold` implementation yourself? Maybe that could shed some light on why it is more complex.

**Comment by Junology** [comment]
@ahmadsalim Thank you for the reply, and I am sorry for the delay.
Yes, I have checked the following code passes the compile.
```idris
data MyVect : Nat -> Type -> Type where
  Nil : MyVect 0 a
  (::) : a -> MyVect n a -> MyVect (S n) a

implementation Foldable (MyVect n) where
  foldr f init Nil = init
  foldr f init (x::xs) = f x $ foldr f init xs
  foldl f init Nil = init
  foldl f init (x::xs) = foldl f (f init x) xs
```
No idea occured to me.

Furthermore, I began to be worried about the performances.
I tried several code to compare two implementations, and it seems that the above one is faster than the one in library.
I haven't made any precise profiling and am trying it.

**Comment by ahmadsalim** [comment]
@Junology I think your implementation of `foldr` is not tail recursive, so it may overflow the stack for large vectors.

**Comment by Junology** [comment]
@ahmadsalim Oh, I completely forgot about it.
Thank you for pointing out it and kindly answering my stupid question.
