### ISSUE TITLE
Allow overriding of fixities for operators

### ISSUE THREAD

**Issue by SantiagoBautista** [idris-lang/Idris-dev#3891]
**Edit:**
It is currently possible in Idris to override infix operators. For example, the following code works
```
(<<) : Nat -> Nat -> Nat
(<<) x y = x + y

example: Nat
example = 3 << 2
```
and there is already a ` << ` operator defined in Prelude.

But, it is not possible to override the fixity of an existing operator. Hence it is not possible to choose for the new operator a fixity different from the fixity of the already defined operator.

If I try

```
infixl 5 <<

(<<) : Nat -> Nat -> Nat
(<<) x y = x + y
```

I get the error

```
error: Illegal
    redeclaration of fixity: "infixl
    5 <<" overrides "infixl 7
    <<"
```

And if I try with a fully qualified name

```
module Test

infixl 5 Test.<<

(<<) : Nat -> Nat -> Nat
(<<) x y = x + y
```

I get an error too:

```
error: expected: space
infixl 5 Test.<< 

```
I think that it would be nice to be able to override the fixities of operators, in order to be able to choose the fixity of a new operators with the same name.

**Original post**
The following code shouldn't compile as no fixity declaration is made for the declared operator

` (<<) : Nat -> Nat -> Nat `
` (<<) x y = x + y `
` `
` example: Nat `
` example = 3 << 2 `

But it compiles, and yields the expected result.

I think that the reason is either:
- there is another (<<) operator elsewhere, and there is a fixity declaration for that other operator, that is used as fixity declaration for the new operator
- ` << ` plays an special role to the language. If that's the case, the above definition shouldn't work

**Comment by ahmadsalim** [comment]
The reason is indeed that `(<<)` is defined in `Prelude.Interfaces` with `infixl 7` as fixity.

**Comment by SantiagoBautista** [comment]
But there is a problem: as it takes the fixity declaration of old operator, it is impossible to define a different fixity for the new operator

If I try
```
infixl 5 <<

(<<) : Nat -> Nat -> Nat
(<<) x y = x + y
```
I get the error
```
error: Illegal
    redeclaration of fixity: "infixl
    5 <<" overrides "infixl 7
    <<"
```

And if I try with a fully qualified name
```
module Test

infixl 5 Test.<<

(<<) : Nat -> Nat -> Nat
(<<) x y = x + y
```
I get an error too:
```
error: expected: space
infixl 5 Test.<< 
```

I'm not sure that it is expected behaviour.
I think that either 
+ it should be possible to declare a different fixity for a new operator that has the same name of an existing operator
+ it shouldn't be possible to declare a new operator that has the same name of an existing operator

What do you think?

**Comment by ahmadsalim** [comment]
@SantiagoBautista Ah, I missed that you wanted to have some other behaviour.
I guess it would be nice if there was a way to override existing fixities, but I do not know a good design for it. Suggestions are welcome.

I think excluding new operators with the same name is bad.

**Comment by SantiagoBautista** [comment]
I edited my original post to make more clear.
I agree with you.
For now I'm totally new to Idris and don't have any suggestion :( . When I have time I will look at how are fixities managed in Idris to see if I could think of some suggestions.

**Comment by ahmadsalim** [comment]
@SantiagoBautista No worries, I meant suggestions in general, not just from you :).

**Comment by SantiagoBautista** [comment]
@ahmadsalim Ah, ok :)

**Comment by david-christiansen** [comment]
Given that we have type-directed disambiguation, changing the fixity for an operator seems likely to be confusing to me, as well as difficult to implement.

If we had two fixities for `>>`, then the parser would have to produce two separate syntax trees, and the problem of deciding which was meant would involve a lot of slow backtracking. Because defining a fixity really does change the _grammar_ of Idris, this would result in parsing being type-directed, which I think is a confusing circularity.

**Comment by SantiagoBautista** [comment]
@david-christiansen 
I understand what you mean.

But I think that when people define a new operator with the same name than an existing one they might be surprised/confused by not being able to change the fixity (I was). So I think that it would make sense to add a warning in the doc explaining that it is not possible. What do you think?

**Comment by ahmadsalim** [comment]
I will close the issue since discussion seems to have halted with no good suggestion 😄
