### ISSUE TITLE
Ubuntu installation seemingly never completes on Xubuntu 16.04

### ISSUE THREAD

**Issue by edemond** [idris-lang/Idris-dev#3892]
Following the instructions on https://github.com/idris-lang/Idris-dev/wiki/Idris-on-Ubuntu, on Xubuntu 16.04, with GHC 7.10.3, I'm not able to get the `cabal install idris` step to actually complete (with or without `--with-ld=ld.gold`); it just seems to run forever. This is a bit of an older machine with an i5-750 and 4GB RAM.

```
$ cabal install idris --with-ld=ld.gold
```
This will get through the dependencies, and then it gets stuck at:
```
Building idris-1.0...
```
This seems to run forever. I would assume it's making progress, but I let it run  #longer than an hour last night, and no end was in sight (what's the ballpark for how long this should take?) Happy to try and investigate, but I'm new to Idris and Haskell, so I'm not sure where to look. Anything I could try, or other information I could provide?

While it's churning I took a look at `ghc` with `strace`. It seems to be constantly handling SIGVTALRM (no clue if this is normal for GHC or what):

```
rt_sigreturn({mask=[]})                 = 140691008343522
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=0, ptr=0}} ---
```
This is occasionally punctuated by chunks of calls like the following:
```
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {420, 885370549}) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM], [], 8) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {420, 886983205}) = 0
getrusage(RUSAGE_SELF, {ru_utime={378, 664000}, ru_stime={42, 220000}, ...}) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {420, 888217415}) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM], [], 8) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {420, 890187653}) = 0
getrusage(RUSAGE_SELF, {ru_utime={378, 664000}, ru_stime={42, 224000}, ...}) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {420, 891140631}) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM], [], 8) = 0
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=0, ptr=0}} ---
rt_sigreturn({mask=[HUP INT QUIT TERM]}) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {420, 892410070}) = 0
getrusage(RUSAGE_SELF, {ru_utime={378, 664000}, ru_stime={42, 228000}, ...}) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {420, 893062555}) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM], [], 8) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {420, 893818694}) = 0
getrusage(RUSAGE_SELF, {ru_utime={378, 664000}, ru_stime={42, 228000}, ...}) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {420, 894450510}) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM], [], 8) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {420, 895476532}) = 0
getrusage(RUSAGE_SELF, {ru_utime={378, 664000}, ru_stime={42, 228000}, ...}) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {420, 895981629}) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM], [], 8) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {420, 897196601}) = 0
getrusage(RUSAGE_SELF, {ru_utime={378, 668000}, ru_stime={42, 228000}, ...}) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {420, 897830355}) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM], [], 8) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {420, 898577846}) = 0
getrusage(RUSAGE_SELF, {ru_utime={378, 668000}, ru_stime={42, 228000}, ...}) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {420, 899375768}) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
```

**Comment by NobbZ** [comment]
I'm not sure about the signaling, but at least I can tell you this:

It takes roughly an hour on my machine which is a fourth generation core i5 with 8 GiB of RAM using ``--jobs=5``. You can try to run `cabal install --verbose idris`. That may take even longer, but at least you can see things happening.

**Comment by NobbZ** [comment]
Oh, to actually see the real action going on, you also need to specify `--jobs=1`

**Comment by jfdm** [comment]
@edemond Thanks for reporting the issue. Apologies for it taking so long...I don't know of any expected installation/build times for older machines, on mine it takes around ten minutes for a fresh install.

When installing Idris using cabal it will default to parallel installation of the dependencies. This makes reporting harder for cabal to report to STDOUt, it nonetheless logs to a file. I cannot remember where in the `.cabal` directory the log file is, but you can examine it to determine progress. Alternativly you can specify that number of jobs to one.
