### ISSUE TITLE
show : Show a => a -> String

### ISSUE THREAD

**Issue by zaoqi** [idris-lang/Idris-dev#3907]
```
     ____    __     _                                          
    /  _/___/ /____(_)____                                     
    / // __  / ___/ / ___/     Version 1.0
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/      
 /___/\__,_/_/  /_/____/       Type :? for help               

Idris is free software with ABSOLUTELY NO WARRANTY.            
For details type :warranty.
Idris> show
Can't find implementation for Show ty
```
?
[http://docs.idris-lang.org/en/latest/tutorial/interfaces.html](url)
```idris
show : Show a => a -> String
```

**Comment by clayrat** [comment]
If you want to see the type, do this:
```
Idris> :t show                  
show : Show ty => ty -> String  
```

**Comment by zaoqi** [comment]
@clayrat 
     ____    __     _                                          
    /  _/___/ /____(_)____                                     
    / // __  / ___/ / ___/     Version 1.0
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/      
 /___/\__,_/_/  /_/____/       Type :? for help               

Idris is free software with ABSOLUTELY NO WARRANTY.            
For details type :warranty.
Idris> :t show
show : Show ty => ty -> String
Idris> :t let f=show in f
Can't find implementation for Show ty

**Comment by ahmadsalim** [comment]
@zaoqi You have to provide the type for `f` here, I do not think that Idris can infer the type here.

**Comment by zaoqi** [comment]
It's like MonomorphismRestriction.

**Comment by ahmadsalim** [comment]
@zaoqi Yeah, exactly. Except, that Idris will not fill in a default type like `()` does in Haskell.

**Comment by zaoqi** [comment]
@ahmadsalim Is there NoMonomorphismRestriction?

**Comment by ahmadsalim** [comment]
@zaoqi No, it is simply a type error, if you don't explicitly put the type. 
While Idris looks like Haskell it behaves differently and is type-driven; that is it expects that at least your top-level declarations have type signatures, althought it will try to do local inference to help you out other places if it can.
