### ISSUE TITLE
A combination of total functions doesn't reduce

### ISSUE THREAD

**Issue by clayrat** [idris-lang/Idris-dev#3908]
Let's define 

```
%access public export
%default total

twice : (x -> x) -> x -> x
twice f = f . f

plus1 : Nat -> Nat
plus1 = plus 1
```

These reduce individually
```
testPlus1 : plus1 1 = 2
testPlus1 = Refl

testTwice : twice (plus 1) 0 = 2
testTwice = Refl
```

But not at the same time
```
testBad : twice plus1 0 = 2
testBad = Refl
```

```
        Type mismatch between
                2
        and
                plus1 (plus1 0)
```

it works in REPL via `the` though
```
> the (twice plus1 0 = 2) Refl
Refl : 2 = 2
```

It seems there's nothing you can do to help it: I've tried `{x=Nat}`, `the Nat 2`, `Z` + `S (S Z)`. Even this definition fails with the same error:

```
testBad' : twice plus1 Z = S (S Z)
testBad' = let y = the (twice plus1 Z = S (S Z)) Refl in y
```
(it works if you leave a hole instead of the final `y`, meaning the type is correct)

**Comment by clayrat** [comment]
Ok, I've figured it out - in the `testBad` case `plus1` is considered an implicit - you have to prefix it with the module name. Still would be nice if there was a more helpful error message here.

**Comment by clayrat** [comment]
Hopefully https://github.com/idris-lang/Idris-dev/pull/3910/ fixes this! Though it's still a weird why `plus1` gets considered an implicit when passed to another function, but not on its own.

**Comment by jfdm** [comment]
I suspect that when it applied there is enough information to distinguish it from an implicit. When used as part of a HOF then their is not enough to distinguish it from jack.

Also remember that implicits will have a different colour to functions. I keep on forgetting that.

The warning has always been there, just its reporting has not been consistent, see #3909. If you are happy that your issue is fixed, can we close this?

**Comment by clayrat** [comment]
Haven't tried it out yet, actually (gotta wait for the new release), but I guess I can reopen if it's not fixed.

**Comment by ehamberg** [comment]
With Idris 1.1:

```
Type checking ./test.idr
test.idr:18:17-22:plus1 is bound as an implicit
	Did you mean to refer to Test.plus1?
test.idr:19:9:When checking right hand side of testBad with expected type
        twice plus1 0 = 2

Type mismatch between
        2 = 2 (Type of Refl)
and
        plus1 (plus1 0) = 2 (Expected type)

Specifically:
        Type mismatch between
                2
        and
                plus1 (plus1 0)
```

**Comment by clayrat** [comment]
Confirmed, closing.
