### ISSUE TITLE
Variables introduced in the Elab shell are invisible

### ISSUE THREAD

**Issue by clayrat** [idris-lang/Idris-dev#3913]
If you enter `:elab` mode in REPL and start introducing variables, e.g., with `gensym`, the command succeeds, and the variable can be used further on, but you can't see it in `:state` or `:term`.

**Comment by david-christiansen** [comment]
What do you precisely mean by this? `gensym` should not modify the term, only create a fresh name.

**Comment by clayrat** [comment]
Just saying it would be nice to have a list of these unbound names somewhere on screen.

**Comment by david-christiansen** [comment]
How should the system distinguish the values that you want to display from the values that you don't? A name is a value like any other, after all.

**Comment by clayrat** [comment]
Ok, disregard this, if you do `foo <- gensym "foo"` it actually does list them under "Meta-values". I didn't expect the do-notation to work directly in the elab shell, should probably do a PR to the docs mentioning it.

**Comment by david-christiansen** [comment]
Ah, now I get what you were meaning :-) Thanks!
