### ISSUE TITLE
unsafePerformIO executed at runtime when applied with $

### ISSUE THREAD

**Issue by Ralith** [idris-lang/Idris-dev#392]
The program:

```haskell
module Main

trace' : String -> a -> IO a
trace' x val = do putStrLn x; return val

trace : String -> a -> a
trace x val = unsafePerformIO $ trace' x val

main : IO ()
main = print (trace "hello" "world")
```
executes the implementation-generated unsafePerformIO stub, resulting in the message `Impossible declaration unsafePerformIO` and an abort.

Replacing the definition of trace with
```haskell
trace : String -> a -> a
trace x val = unsafePerformIO (trace' x val)
```
avoids the error.

**Comment by edwinb** [comment]
This does what I'd expect now, probably as a result of IO changes about a year ago but never retested... I've added a regression test to make sure it keeps working.
