### ISSUE TITLE
A proof of False = True -> Void in Prelude?

### ISSUE THREAD

**Issue by clayrat** [idris-lang/Idris-dev#3924]
I know adding things to Prelude is frowned upon, so wanted to discuss first. 

There is already such a proof in `Data.Heap`@contrib (https://github.com/idris-lang/Idris-dev/blob/master/libs/contrib/Data/Heap.idr#L135-L137), but it's not really used there.

However it might be useful for some naive proofs if moved to `Prelude.Bool`.  For example, `Prelude.Nat` already has both 
 - `Uninhabited (Z = S n)` (https://github.com/idris-lang/Idris-dev/blob/master/libs/prelude/Prelude/Nat.idr#L26-L27) 
and 
- `SIsNotZ : (S x = Z) -> Void` (https://github.com/idris-lang/Idris-dev/blob/master/libs/prelude/Prelude/Nat.idr#L321-L322).

**Comment by david-christiansen** [comment]
It's not so much that adding things to the Prelude is frowned upon in general, it's just that it implies a commitment to maintain the things that are there for the foreseeable future. So we want to make sure that the things that are added aren't getting in the way of users's choices of names and that they are actually useful in a variety of Idris programs.

Things like `SIsNotZ` have been around for a long time, before we started getting more selective.

I think that an `Uninhabited (True = False)` implementation makes sense in Prelude. There's only one sensible implementation, and it doesn't clutter the global namespace. Perhaps:
```
Uninhabited (True = False) where
  uninhabited Refl impossible

Uninhabited (False = True) where
  uninhabited Refl impossible
```
does the trick?

**Comment by clayrat** [comment]
I see! The duplication in the interface approach seems a bit unfortunate, with a function you could use `sym`, on the other hand, as you say, it might interfere with somebody's function name. Btw, which style (`x->Void` vs `Uninhabited x`) is recommended nowadays? Seems that `absurd` is pretty much the only use for `Void` anyway.

**Comment by david-christiansen** [comment]
The `Uninhabited` interface is a canonical place to put proofs that certain things can't happen, because then we can just say `absurd` when we want to refer to one rather than remembering its name. It hasn't been around as long as the whole Prelude, though - I think I stuck it in there a couple years ago.

Usually, `absurd` will do what you want, but it might be inconvenient depending on your local context, in which case explicit proofs of `A -> Void` might be needed.

**Comment by ahmadsalim** [comment]
@clayrat Maybe the following could work (or maybe it goes into an infinite loop)?

```idris
implementation Uninhabited (y = x) => Uninhabited (x = y) where
   uninhabited x = uninhabited (sym x)
```

**Comment by david-christiansen** [comment]
@ahmadsalim this seems likely to be problematic, as it will overlap with many other implementations.

**Comment by ahmadsalim** [comment]
@david-christiansen Hmm, yeah, I guess you are right. One could probably make it a named implementation instead.

I think it would be cool if it would be possible to have overlapping instances with prioritization, but I think this required a lot of thought about proper design, etc.

**Comment by ziman** [comment]
Can you give an example where this is needed? I'd expect to be able to deal with most (all?) such cases with `impossible`.

Ideally, we would have disjointness and injectivity of constructors via reflection but I'm not sure what the API would look like.
https://pdfs.semanticscholar.org/1320/0e737e8607d9cf25d28d339e125e9293e3a4.pdf

**Comment by david-christiansen** [comment]
`pruviloj` includes disjointness and injectivity :-)

**Comment by ahmadsalim** [comment]
I will close the issue since it is merged in #3925

**Comment by clayrat** [comment]
@ziman Yes, I guess is this more of stylistic choice. With `SIsNotZ` instances mentioned in the root comment I got the feeling that stdlib doesn't force the choice of matching over `absurd`.

**Comment by clayrat** [comment]
@ziman Ok, here's an example from SF :
(`a<->b` is `(a->b,b->a)`)
```
restricted_excluded_middle : (p <-> b = True) -> p `Either` Not p
restricted_excluded_middle {b = True} (_, bp) = Left $ bp Refl
restricted_excluded_middle {b = False} (pb, _) = Right $ uninhabited . pb
```
Looks to me like the `False` case is a good use of this, so you don't have to introduce intermediate helpers.

**Comment by ziman** [comment]
In the snippet, you can replace `uninhabited` with `(\Refl impossible)`.

But I agree it's just a matter of style.
