### ISSUE TITLE
Fix for once all the syntax wars!

### ISSUE THREAD

**Issue by nuncanada** [idris-lang/Idris-dev#3940]
Please, very please.
As IDRIS seems to be a revolutionary language, fix all syntax wars.

Simply arrange an Full AST (Instead of the usual AST compilers create without comments and other irrelevant syntatic elements) as being the default input to the compiler. 
Simply provide tools for developers for reconstructing code from the Full AST file and for parsing code to create the Full AST file.

Later on encourage projects in the language to only keep the AST files, not the source code files.

**Comment by ahmadsalim** [comment]
@nuncanada Thanks for the ideas.
I however think that this discussion belongs more on the mailing list (see https://github.com/idris-lang/Idris-dev#more-information) than in the issue tracker, so I would kindly ask you to take it there and I will close the issue here.
