### ISSUE TITLE
Memory leak with GHC 8.0.1?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3947]
On a fresh installation of IdrisLibs (https://gitlab.pik-potsdam.de/botta/IdrisLibs) and with Idris 0.12.2-git:PRE, you shoudl be able to do
```
$ cd SequentialDecisionProblems/applications
$ make env
$ time make emissionsgame0
$ time make emissionsgame1
$ time make emissionsgame2
```
With GHC 8.0.1 you should observe that `make emissionsgame0` and `make emissionsgame1` terminate in about one minute.

However, `make emissionsgame2` starts eating up all the available memory and eventually has to be killed. With GHC 7.6.3,  `make emissionsgame2` terminated in about the same time as `make emissionsgame0` and `make emissionsgame1`.

I have come across this issue when upgrading Debian jessie to stretch. Any idea how to avoid the problem?

**Comment by ahmadsalim** [comment]
@nicolabotta Is there any reason you are not using 1.0? 
It seems that 0.12 is a very very old version.

**Comment by nicolabotta** [comment]
@ahmadsalim The only reason why I cannot move to 1.0 is #3727. I have a number of definitions like for instance
```
> ||| Non negative double precision floating point numbers as sigma types
> NonNegDouble : Type
> NonNegDouble = Subset Double (\ x => 0.0 `LTE` x)
```
that cannot be made instances of `Num`, `Show`, `Eq`, etc. because of #3727.

**Comment by ahmadsalim** [comment]
@nicolabotta Yeah, I can see it is inconvenient.
There are workarounds for this particular problem, if you are interested.
The easiest would be to convert aliases to actual records (a bit like `newtype`) in Haskell:

```idris
data NonNegDouble : Type where
  MkNonNegDouble : (value : Double) -> .(isNonNeg : 0.0 `LTE` value) -> NonNegDouble
```

**Comment by nicolabotta** [comment]
@ahmadsalim Yes, I could of course replace all type aliases with data declarations. This would imply rewriting a lot of code but that is not the main reason for rejecting your suggestion. I do not think that throwing away aliases to Sigma types only to circumvent a language deficiency would be a good decision. There are a number of obvious reasons to prefer
```
> NonNegDouble : Type
> NonNegDouble = Subset Double NonNegative
```
to a full fledged data declaration. Thus if #3727 can be fixed in a reasonable time and with moderate efforts, I prefer to stay with 0.12 until the issue is fixed. 

On the other hand, if #3727 is not going to be fixed soon, I would be grateful if there was some clear statement on the questions raised by #3727. If programs like
```
> implementation Uninhabited (DPair Nat (\ n  => LT n Z)) where
>   uninhabited (MkDPair n prf) = absurd prf
```
are not meant to type check in 1.0 and future Idris releases, it would be probably meaningful to close #3727 and clearly state, somewhere in the Idris documentation, that starting from Idris 1.0, Sigma types cannot be instances of type classes.

**Comment by ahmadsalim** [comment]
@nicolabotta I unfortunately do not have much say in how #3727 should be solved.
I personally think it makes sesnse to still allow alias-like declarations to have implementations, but I unfortunately do not have much time these days to try and fix the problem myself.

Maybe @david-christiansen or @edwinb has some ideas of other alternatives that could be used in the meanwhile, and what the status of #3727 should be.

**Comment by nicolabotta** [comment]
@ahmadsalim Thanks Ahmad, perhaps @david-christiansen or @edwinb will chime in on the #3727 issue. For the current issue, however, the problem seems to be GHC 8.0.1. As reported in my original post, `make emissionsgame2` was terminating in one to two minutes under GHC 7.6.3. After upgrading to 8.0.1 I cannot anymore compile the application.

**Comment by nicolabotta** [comment]
I have run another test on another machine: GHC 10.7.3 exhibits the same problme as 8.01. 

I have an old `.cabal/share/x86_64-linux-ghc-7.6.3/idris-0.12.2` directory in my home. Is it possible to reinstall 0.12.2 using these files?

**Comment by melted** [comment]
@nicolabotta you would still have to build the executable with GHC 7.6.3, so it's probably easier to download 7.6.3 for linux from https://downloads.haskell.org/~ghc/7.6.3/ and put it in `/opt` or somewhere, and put that first in `PATH`.

**Comment by nicolabotta** [comment]
@melted Thanks, you mean the GHC binaries, right? The problem is that one needs `libgmp.so.3` in order to build GHC 7.6.3 from the sources and I do not seem to be able to find `libgmp.so.3` for Debian stretch!

**Comment by nicolabotta** [comment]
I have not managed to install GHC 7.6.3. under Debian 9. The `libgmp` problem can be circumvented with `ln -s /usr/lib/x86_64-linux-gnu/libgmp.so /usr/lib/libgmp.so.3`. But the installed 7.6.3 binaries would generate tons of `relocation R_X86_64_32S against ...` error messages when trying to build Idris or, indeed, GHC itself. 

Any idea how to proceed? I need to be able to execute `make emissionsgame2` in a reasonable time for production.

**Comment by melted** [comment]
Maybe you can go the other way and try the newly released GHC 8.2.1?

**Comment by melted** [comment]
I have all idris versions for windows archived so I tested it, looks like my 0.12.3 will build emissionsgame2 just fine.

**Comment by nicolabotta** [comment]
@melted  

> Maybe you can go the other way and try the newly released GHC 8.2.1?

 Good point! How did you manage to build 0.12.3 with GHC 8.2.1? When I try to build 0.12.2 I get lots of dependency errors:
```
nicola@cirrus:~/src/Idris-dev-ff776da0e40aa9e809878d4c01b8eb24e048e77f$ make
cabal install --enable-tests
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: base-4.10.0.0/installed-4.1... (dependency of idris-0.12.2)
next goal: vector (dependency of idris-0.12.2)
rejecting: vector-0.12.0.1, vector-0.12.0.0 (conflict: idris => vector<0.12)
rejecting: vector-0.11.0.0 (conflict: base==4.10.0.0/installed-4.1..., vector
=> base>=4.3 && <4.10)
trying: vector-0.10.12.3
next goal: primitive (dependency of vector-0.10.12.3)
rejecting: primitive-0.6.2.0 (conflict: vector => primitive>=0.5.0.1 &&
<0.6.2)
rejecting: primitive-0.6.1.0 (conflict: base==4.10.0.0/installed-4.1...,
primitive => base>=4.3 && <4.10)
rejecting: primitive-0.5.4.0 (conflict: base==4.10.0.0/installed-4.1...,
primitive => base>=4.3 && <4.9)
rejecting: primitive-0.5.3.0, primitive-0.5.2.1 (conflict:
base==4.10.0.0/installed-4.1..., primitive => base>=4.3 && <4.8)
rejecting: primitive-0.5.1.0 (conflict: base==4.10.0.0/installed-4.1...,
primitive => base>=4 && <4.8)
rejecting: primitive-0.5.0.1 (conflict: base==4.10.0.0/installed-4.1...,
primitive => base>=4 && <4.7)
rejecting: primitive-0.5, primitive-0.4.1, primitive-0.4.0.1, primitive-0.4,
primitive-0.3.1, primitive-0.3, primitive-0.2.1, primitive-0.2, primitive-0.1
(conflict: vector => primitive>=0.5.0.1 && <0.6.2)
rejecting: primitive-0.6 (conflict: base==4.10.0.0/installed-4.1..., primitive
=> base>=4.3 && <4.9)
Dependency tree exhaustively searched.
Makefile:18: recipe for target 'install' failed
make: *** [install] Error 1
nicola@cirrus:~/src/Idris-dev-ff776da0e40aa9e809878d4c01b8eb24e048e77f$
```

**Comment by nicolabotta** [comment]
@ahmadsalim 

> Is there any reason you are not using 1.0? It seems that 0.12 is a very very old version.

I have now realized that #3727 only forces me to use Idris < 1.0. The actual reason for sticking to 0.12.2 is #3405.

**Comment by melted** [comment]
> Good point! How did you manage to build 0.12.3 with GHC 8.2.1? When I try to build 0.12.2 I get lots of dependency errors:

I didn't, I used the old 0.12.3 I had archived, but I'm building it now. I had to add `--allow-newer=base` to cabal install.

**Comment by ahmadsalim** [comment]
@nicolabotta As far as I can see #3405 has been silently resolved somehow. At least it works on `0.99-git:81c8db70`.

**Comment by melted** [comment]
Then I guess this little fix needs to be put in too https://github.com/idris-lang/Idris-dev/pull/3939

**Comment by ahmadsalim** [comment]
@nicolabotta By work, I mean it type checked in around 20s on my computer.
I had to fix a small issue where in `PNat.idr` I had to use `import public NatPositive` instead of just `import`.

**Comment by melted** [comment]
Hmmm, 0.12.3 built with 8.2.1 probably needs a more general --allow-newer for it to work. I think I'll try to reproduce this by building it with 8.0.2 instead.

**Comment by nicolabotta** [comment]
With 0.99.2 and GHC 8.0.1 `make emissionsgame2` compiles in about 3 minutes (on my very old laptop) and without any memory problems. Thus, it seems that the problem was specific of erlier Idris versions, not of GHC. Thus, I am closing this issue. Thanks to everybody!
