### ISSUE TITLE
Lifted holes do not always typecheck

### ISSUE THREAD

**Issue by zenntenn** [idris-lang/Idris-dev#3951]
In a number of different programs I've been writing when I have a .idr file with holes that properly typechecks, and then I lift the hole (on my system in idris-vim using \l on the hole) the file no longer typechecks.

For an example with the attached file (rename test.txt to test.idr, and run idris with -p contrib) when I lift the holes ?executeCommand or ?interpretExpression it produces a type signature which does not typecheck.
[error.txt](https://github.com/idris-lang/Idris-dev/files/1180770/error.txt)

**Comment by eraserhd** [comment]
@zenntenn It looks like you've attached the wrong file?

**Comment by zenntenn** [comment]
You're right, and I didn't save a copy. I'll open a new issue if this comes up again and double check the right file is uploaded.
