### ISSUE TITLE
Are datatype return kinds allowed to depend on argument kinds?

### ISSUE THREAD

**Issue by RyanGlScott** [idris-lang/Idris-dev#3954]
I ask because I've observed odd behavior with this data type:

```idris
module Bug                                                                                
                                                                                          
%default total                                                                            
                                                                                          
MkFun : Nat -> Type                                                                       
MkFun Z     = Type                                                                        
MkFun (S n) = Type -> MkFun n                                                             
                                                                                          
data Foo : (numArgs : Nat) -> MkFun args                                                  
                                                                                          
f : Foo 0 -> Int                                                                          
f _ = 5
```

This errors thusly:

```
$ idris --check Bug.idr                                                                   
Bug.idr:11:3:When checking type of Bug.f:                                                 
Type mismatch between                                                                     
        MkFun args (Type of Foo args 0)                                                   
and                                                                                       
        Type (Expected type)
```

That's odd—`Foo 0` should be of kind `MkFun 0`, which reduces to `Type`.

Moreover, you observe different behavior if you add a `where` at the end of the data declaration:

```idris
data Foo : (numArgs : Nat) -> MkFun args where
```

```
$ idris --check Bug.idr                                                                   
Bug.idr:9:6:When checking type constructor Bug.Foo:                                       
Not a valid type constructor                                                              
Bug.idr:11:3:When checking type of Bug.f:                                                 
No such variable Foo
```

The `Not a valid type constructor` makes me wonder: is what I'm trying to do (by having the datatype's return kind depend on one of the argument kinds) even legal? It appears [not to be in Agda](https://github.com/agda/agda/blob/3e7d93707c65ae6065b5aabefbf6afd10468078b/test/Fail/SortDependingOnIndex.err), but maybe Idris is different.

**Comment by jfdm** [comment]
Shouldn't the type of `Foo` be:

```idris
data Foo : (numArgs : Nat) -> MkFun numArgs
```

Doing this, and everything typechecks are expected.

Otherwise, `args` would be seen as an implicit.

**Comment by clayrat** [comment]
I think the problem with the `where` variant is simply that it can't have zero constructors, you need to change it to something like:
```
data Foo : (numArgs : Nat) -> Type where
  MkFoo : MkFun numArgs -> Foo numArgs     
```

**Comment by RyanGlScott** [comment]
@jfdm, @clayrat, good catches. Let me revise my example, then, to make it clearer what I think the problem is. If we have something like this:

```idris
module Bug

%default total

MkFun : Nat -> Type
MkFun Z     = Type
MkFun (S n) = Type -> MkFun n

data Foo : (numArgs : Nat) -> MkFun numArgs where
  MkFoo0 : Foo 0
  MkFoo1 : a -> Foo 1 a
```

Then this is summarily rejected:

```
$ idris --check Bug.idr
Bug.idr:9:6:When checking type constructor Bug.Foo:
Not a valid type constructor
```

This is the crux of the issue. Is a dependency like this allowable, where the return kind depends on an argument kind like this? If so, this is a proper bug. If not, it would be nice to update the error message to make it explicit what the source of the error is, as in Agda.

**Comment by ahmadsalim** [comment]
@RyanGlScott I think it is not supported to have pattern matching definitions, but you can have things that are syntactically not `Type`, e.g. see the Effect library.

**Comment by RyanGlScott** [comment]
Perhaps I'm missing something, but why does this need to be checked at datatype definition time? Just defer the check to each constructor! `MkFoo0` and `MkFoo1` both bring in evidence that causes `MkFun` to reduce to something that ends in `... Type`, so everything's groovy.

Obviously, this would be a problem if you tried a constructor like `MkFoo3 : Foo n`. But I'm not asking for that ability.

**Comment by ahmadsalim** [comment]
@RyanGlScott Currently the type constructor is elaborated before the data constructor.
Your idea might work, but then elaboration must change I guess.
Maybe @edwinb can budge in here, but I would guess PRs are welcome?

**Comment by ahmadsalim** [comment]
Another issue might be how parameter vs. indices are inferred now (where they are static now).

**Comment by david-christiansen** [comment]
I think that doing it one constructor at a time is not necessarily incorrect, but I have not seen a system of inductive types that validates definitions of that form. These things are tricky to get right!

I wouldn't want to merge a PR that just made this work without a pointer to a theoretical development if this style of type definition, and I suspect that it would have problems if the function in question only sometimes reduced to `Type`.

In any case, it would indeed be good to have a more specific message.

**Comment by melted** [comment]
The immediate reason why this doesn't work is that data declarations must return a type (TType or UType in TT), and that MkFun is a binder, (see Elab/Data.hs, line 85 and thereabouts).
