### ISSUE TITLE
idris-1.1.0 fails to install: "gcc failed in phase `Linker'"

### ISSUE THREAD

**Issue by gallais** [idris-lang/Idris-dev#3958]
I ran
```
TMDIRP=~/tmpdir/ cabal install -f FFI -f LLVM -f GMP idris -v3 &> idris-install.log.txt
```
and got:
```
(...)
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
/usr/bin/ghc returned ExitFailure 1
cabal: Leaving directory '/tmp/cabal-tmp-9240/idris-1.1.0'
Failed to install idris-1.1.0
World file is already up to date.
cabal: Error: some packages failed to install:
idris-1.1.0 failed during the building phase. The exception was:
ExitFailure 1
```
In case that matters, I have:
```
> ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
> cabal --version
cabal-install version 1.24.0.1
compiled using version 1.24.1.0 of the Cabal library
 ```

Full log: [idris-install.log.txt](https://github.com/idris-lang/Idris-dev/files/1190938/idris-install.log.txt)

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue.

@gallais Do you get the same error with stack?

**Comment by gallais** [comment]
AFAII the latest version of Idris available in a resolver compatible with ghc 8.0.1 is 0.12.3 ([resolver 7.24](https://www.stackage.org/lts-7.24/package/idris-0.12.3))

**Comment by ahmadsalim** [comment]
I get this error somewhere, which I do not know if a symptom or a cause:
```
upsweep (partially) failed OR
   Main.main not exported; not linking.
```

**Comment by ahmadsalim** [comment]
I would guess this might be related to #3960 .

**Comment by gallais** [comment]
The log indicates that the version of `cheapsake` picked is `0.1.0.5` which is below the `0.1.1` causing problem in #3960. Plus idris does build all the way, it only chokes on the final phase when it tries to link the executable together.

**Comment by ahmadsalim** [comment]
That is weird indeed. What version of GCC are you using, and was this a clean install of Idris?

**Comment by gallais** [comment]
I already had Idris 1.0 installed (via `cabal install`, using the same set of flags `-f FFI -f LLVM -f GMP`)

```
> gcc --version
gcc (Debian 6.3.0-14) 6.3.0 20170415

> idris --version
1.0
```

**Comment by ahmadsalim** [comment]
Please try:

```idris
cabal clean
cabal new-build -f FFI -f LLVM -f GMP
```

I have tried it on my Mac and it seems to work.

**Comment by melted** [comment]
It's strange that there is no output from the linker, normally you'd get some error message.

The llvm flag doesn't do anything anymore, but that can't be the problem.

**Comment by gallais** [comment]
Ok, I did:

```
git clone https://github.com/idris-lang/Idris-dev -b v1.1.0 --single-branch --depth=1
cd Idris-dev/
cabal clean
cabal new-build -f FFI -f LLVM -f GMP
```
And that succeeded. However this does not install any executable AFAICT. Running

```
cabal install
```
recompiles the 114 modules and then proceeds to install idris in `~/.cabal/bin`. I now have:

```
> idris --version
1.1.0-git:70f172c
```

**Comment by ahmadsalim** [comment]
@gallais Yeah, I misunderstood a small detail regarding `cabal new-build`, which was that it does not directly install the executable (they are working on it). 
I am glad you got it working, I will close the issue then!
