### ISSUE TITLE
Build failure with Haskell Plattform 8.0.2

### ISSUE THREAD

**Issue by m-schmidt** [idris-lang/Idris-dev#3980]
I get build failures with a clean Haskell Plattform 8.0.2 on macOS Sierra when trying to install Idris:

    src/Text/Trifecta/Instances.hs:18:10: error:
        Duplicate instance declarations:
          instance Data.Semigroup Doc
            -- Defined at src/Text/Trifecta/Instances.hs:18:10
          instance [safe] Data.Semigroup Doc
            -- Defined in ‘Text.PrettyPrint.ANSI.Leijen.Internal’
    ...
    idris-1.1.0 depends on trifecta-1.6.2.1 which failed to install.
    trifecta-1.6.2.1 failed during the building phase. The exception was:
    ExitFailure 1

The problem seems to be that the package `ansi-wl-pprint-0.6.8` (recently updated from `0.6.7.3`) is incompatible with `trifecta-1.6.2.1`.  The Idris package on [Hackage](https://hackage.haskell.org/package/idrisl)
specifies these dependencies: `ansi-wl-pprint (<0.7)` and `trifecta (==1.6.*)`.

Possible solution: update the dependencies on Hackage to `ansi-wl-pprint (<0.6.8)`

Regards

**Comment by ahmadsalim** [comment]
@m-schmidt Thanks for reporting the issue.
There will be a .1 release very soon that will fix it, in the mean time feel free to use the binaries.

I will close the issue now, but feel free to reopen if it still persists after 1.1.1 is released.

**Comment by m-schmidt** [comment]
OK. Thanks.
