### ISSUE TITLE
Installation of idris 1.1.1 via brew is broken

### ISSUE THREAD

**Issue by justjoheinz** [idris-lang/Idris-dev#3987]
Please attach complete source files that exhibit the issue in addition
to quoting from them here.

# Steps to Reproduce

install idris via brew
`brew install idris`

# Expected Behavior

I can typecheck files in the idris REPL

# Observed Behavior

```
idris Eff.idr
/usr/local/Cellar/idris/1.1.1/share/x86_64-osx-ghc-8.0.2/idris-1.1.1/libs/prelude/Prelude.idr: openFile: does not exist (No such file or directory)
     ____    __     _                                          
    /  _/___/ /____(_)____                                     
    / // __  / ___/ / ___/     Version 1.1.1
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/      
 /___/\__,_/_/  /_/____/       Type :? for help               

Idris is free software with ABSOLUTELY NO WARRANTY.            
For details type :warranty.
Must be an ibc

```

Please not the two error messages: 
  *  openFile: does not exist (No such file or directory)
  *  Must be an ibc

It is not possible to typecheck any idris idr files.

**Comment by justjoheinz** [comment]
Additional information:
```
/usr/local/Cellar/idris/1.1.1/share/x86_64-osx-ghc-8.0.2/idris-1.1.1/libs/prelude$ ll
total 256
-rw-r--r--   1 markusklink  admin    504  5 Aug 19:51 00prelude-idx.ibc
-rw-r--r--   1 markusklink  admin  21503  5 Aug 19:51 Builtins.ibc
drwxr-xr-x   3 markusklink  admin    102  5 Aug 19:51 Decidable
-rw-r--r--   1 markusklink  admin  36603  5 Aug 19:51 IO.ibc
drwxr-xr-x   4 markusklink  admin    136  5 Aug 19:51 Language
drwxr-xr-x  28 markusklink  admin    952  5 Aug 19:51 Prelude
-rw-r--r--   1 markusklink  admin  64355  5 Aug 19:51 Prelude.ibc
```
the directory only contains the ibc files. Previously installations with homebrew had been working flawlessly (up to idris 1.1.0)

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue.
@ilovezfs Do you have an idea why this issue appears, and how we could potentially fix it?

**Comment by ilovezfs** [comment]
@ahmadsalim I'm not sure, but it should be reproducible in any cabal sandbox.

I don't think I understand the point about the prelude directory:
```
bash-4.4$ ls -1 /usr/local/Cellar/idris/1.0/share/x86_64-osx-ghc-8.0.2/idris-1.0/libs/prelude/
00prelude-idx.ibc
Builtins.ibc
Decidable
IO.ibc
Language
Prelude
Prelude.ibc
bash-4.4$ ls -1 /usr/local/Cellar/idris/1.1.0/share/x86_64-osx-ghc-8.0.2/idris-1.1.0/libs/prelude/
00prelude-idx.ibc
Builtins.ibc
Decidable
IO.ibc
Language
Prelude
Prelude.ibc
bash-4.4$ ls -1 /usr/local/Cellar/idris/1.1.1/share/x86_64-osx-ghc-8.0.2/idris-1.1.1/libs/prelude/
00prelude-idx.ibc
Builtins.ibc
Decidable
IO.ibc
Language
Prelude
Prelude.ibc
bash-4.4$ 
```
It doesn't seem to have changed.

**Comment by ilovezfs** [comment]
It seems to work, no?
```
iMac-TMP:idris joe$ idris reg034.idr 
     ____    __     _                                          
    /  _/___/ /____(_)____                                     
    / // __  / ___/ / ___/     Version 1.1.1
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/      
 /___/\__,_/_/  /_/____/       Type :? for help               

Idris is free software with ABSOLUTELY NO WARRANTY.            
For details type :warranty.
Type checking ./reg034.idr
reg034.idr:6:5:When checking left hand side of bar:
Can't match on bar xs xs Refl
reg034.idr:9:5:When checking left hand side of foo:
Can't match on foo f x x Refl
Holes: main.foo, main.bar
*reg034> 
```

What are the exact steps to reproduce the issue?

**Comment by ahmadsalim** [comment]
@justjoheinz Have you tried running `brew doctor` and is there anything that it warns you about.

**Comment by justjoheinz** [comment]
I did, and nothing suspicious was discovered.

However, recently I managed for the first to to get a source install
running via stack build. I will check if there are not conflicts with
something lurking in some directory. i also tried uninstalling idris to no
avail. So it seems, that there must be something on my side, and no
principal error with the brew idris installer. I will report here if I find
anything.



2017-08-12 13:41 GMT+02:00 Ahmad Salim Al-Sibahi <notifications@github.com>:

**Comment by justjoheinz** [comment]
I investigated a bit further and found the bug, which is really strange. It has nothing to do with the brew installation which is working fine. Sorry for the noise.

The bug was caused because next to my file `Eff.idr` I had a file `IO.idr` with the following contents:

```
module Some

foo: Int -> Int
foo x = x
```

This will freak out the idris REPL and causes the problem I described above. Maybe someone could look into this bug, or I can file a new issue.

**Comment by ahmadsalim** [comment]
@justjoheinz Thanks for clearing this up! Please fine a new issue.

**Comment by ahmadsalim** [comment]
@ilovezfs Thanks for debugging potential issues!

**Comment by ilovezfs** [comment]
@ahmadsalim You're welcome!
