### ISSUE TITLE
File with name `IO.idr` confuses idris REPL

### ISSUE THREAD

**Issue by justjoheinz** [idris-lang/Idris-dev#3994]
# Steps to Reproduce

* Create an empty directory
* add two idris files, Foo.idr and IO.idr
* the module names in the files do not matter, assume `module Foo` and `module Foo2`
* invoke `idris Foo.idr`

# Expected Behavior
* The `prelude` is loaded normally.

# Observed Behavior

```
$ idris Foo.idr
/usr/local/Cellar/idris/1.1.1/share/x86_64-osx-ghc-8.0.2/idris-1.1.1/libs/prelude/Prelude.idr: openFile: does not exist (No such file or directory)
     ____    __     _                                          
    /  _/___/ /____(_)____                                     
    / // __  / ___/ / ___/     Version 1.1.1
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/      
 /___/\__,_/_/  /_/____/       Type :? for help               

Idris is free software with ABSOLUTELY NO WARRANTY.            
For details type :warranty.
Must be an ibc
*Foo> 
```

As a result functions in Foo.idr cannot be accessed. The error also seems to be specific to a filename `IO.idr` - I tried with other filenames which can be found in the prelude, such as `Buildins.idr` but could not reproduce the error.

**Comment by melted** [comment]
It goes awry when trying to find the imports, I suspect Builtins works because it has been loaded before the Prelude ibc, so idris doesn't have to go looking for it when it sees the import.

**Comment by melted** [comment]
I will investigate that theory, in that case there is a simple band-aid fix. But probably a package looking for imports should look in its own directory first.

**Comment by melted** [comment]
`findImports` behavior is almost entirely wrong for `processImports`, it looks in the current directory first, and it just terminates if it happens on a source file with the same name (though loading the wrong ibc is probably worse if one is present).

It's remarkable that it has worked as well as it has. Probably it's thanks to most libs having subdirs and non-generic names for the top level files.

**Comment by justjoheinz** [comment]
I haven't included files, I just wanted to let you know is that it is not
required to import `IO` from anywhere. The mere existence of a file with
that name (it can even define a different module, aka `IO.idr` defines
`module Whatever`) is enough to confuse idris.


2017-08-14 19:29 GMT+02:00 Niklas Larsson <notifications@github.com>:

**Comment by melted** [comment]
The problem is when the prelude is loaded. 

In fact you don't have to try to load a file, just starting idris in a directory with a file named 'IO.idr' is enough.

**Comment by ahmadsalim** [comment]
@justjoheinz There is no expected behaviour?

**Comment by justjoheinz** [comment]
I think the expected behaviour depends on idris not on me: 
 * Is it forbidden to have certain filenames lurking around?
 * should there be a meaningful error message?
 * are programmers allowed to redefine packages of the Prelude?
 * why does idris choke on IO.idr despite the fact that I am not using it at all? 
 * are there other special filenames?

**Comment by ahmadsalim** [comment]
@justjoheinz I used "The prelude is loaded normally."

**Comment by melted** [comment]
I tested a fix and it works. 

But I want to make a more principled fix, namely that any import directory that is a prefix of the path the current IBC is in will be prioritized for imports.
