### ISSUE TITLE
Shorten Travis Jobs

### ISSUE THREAD

**Issue by superfunc** [idris-lang/Idris-dev#3997]
Travis Checks seem to be failing intermittently, running out of the allotted time(for example #3993). These should be trimmed down in some fashion so they can run reliably.

**Comment by david-christiansen** [comment]
I agree! Are you interested in taking a stab at it?

Here's some things that might work, so far as I can see:
1. Figure out which tests predict the success of others, and prune the test suite that way
2. Find a way to cache more intermediate build products (is Nix an answer here?)
3. Run some sample of the tests each time, if test execution time dominates

These are all pretty time-intensive to figure out, unfortunately.

**Comment by melted** [comment]
The jobs used to take about half an hour until a few weeks ago. Hopefully this will be solved on Travis side.

**Comment by superfunc** [comment]
Even 30 minutes feels like something we should try to trim down for better iteration capability.

**Comment by david-christiansen** [comment]
If you can make the tests run faster without decreasing the quality of the feedback we get from them, then that would sure be nice.

**Comment by superfunc** [comment]
Yeah for sure, I'll do some exploring and report back.

**Comment by ahmadsalim** [comment]
@superfunc It may be worth taking a look at changing the test scripts from bash scripts to internal Haskell functions.

**Comment by superfunc** [comment]
It seems like a lot of time is being spent in this [bit](https://github.com/idris-lang/Idris-dev/blob/master/.travis.yml#L84) (roughly 20min in the aforementioned run):

```
$ if diff -u installplan.txt $HOME/.cabsnap/installplan.txt; then echo "cabal build-cache HIT"; rm -rfv .ghc; cp -a $HOME/.cabsnap/ghc $HOME/.ghc; cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/; else echo "cabal build-cache MISS"; rm -rf $HOME/.cabsnap; mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin; cabal install -f FFI --only-dependencies --enable-tests; fi
```

Do you think there is anything smarter we could do here?

**Comment by eraserhd** [comment]
@superfunc I assume it's doing the `cabal install` branch.  If so, perhaps the tests could be run without installing, just building?

I personally like the idea of adding support for HUnit tests (or something equivalent) and perhaps later, QuickCheck tests, and converting a lot of test cases to it.  When looking at issues here, I've often wanted to make a simple case and running the tests is pretty painful.

**Comment by superfunc** [comment]
@eraserhd I agree, a better test infra would be good, but if cleaning up that install bit works, I'd like to split that off into another bug.

**Comment by david-christiansen** [comment]
I think that making many issues to talk about slow CI execution is not likely to make it easier for anyone to see what's going on. Why not stick with this one?

**Comment by superfunc** [comment]
My thought was that converting the tests to hunit tests was outside of the scope of just CI time, and more towards better general infrastructure for the project.

**Comment by david-christiansen** [comment]
I seem to have misunderstood :-) though I think a pull request makes more sense than a bug report there.

**Comment by superfunc** [comment]
Yeah that sounds good to me

**Comment by melted** [comment]
One improvement https://github.com/idris-lang/Idris-dev/pull/4014

As the only thing we're interested in is new dependencies and how it works with them, we can save a lot of time by doing install with --upgrade-dependencies instead wiping the cached stuff.

Actually, I wonder if the comparison serves a purpose, wiping cabsnap and putting in the new stuff takes just seconds.

**Comment by melted** [comment]
Travis is back to normal, and anyone can work on improving the CI situation without an issue. Let's close.
