### ISSUE TITLE
Will the garbage collector be optional some day?

### ISSUE THREAD

**Issue by antoyo** [idris-lang/Idris-dev#4000]
Hello.
The [FAQ](http://docs.idris-lang.org/en/latest/faq/faq.html#why-does-idris-use-eager-evaluation-rather-than-lazy) says that one (future) goal of Idris is to write low-level code.
So, I was wondering if the garbage collector will be optional some day.
Thanks.

**Comment by david-christiansen** [comment]
This is not a bug or issue in Idris.

We try to keep general questions out of the issue tracker, because it's hard enough as is to follow along with as-is! Please ask this kind of question on [the mailing list](http://groups.google.com/group/idris-lang) or in the IRC channel (`#idris` on Freenode).

**Comment by ahmadsalim** [comment]
@antoyo I do not think there are explicit plans for that now, but it may of course happen.
There was some work on `LinearTypes` and `UniqueTypes` that was meant to allow some subroutines to be written without GC, but as far as I can see there is no active development on them and the implementation is fairly immature.

Anyway, I agree with @david-christiansen, please use the mailing list next time.
