### ISSUE TITLE
No such variable Control.ST.st_precondition when building

### ISSUE THREAD

**Issue by shmish111** [idris-lang/Idris-dev#4003]
Please attach complete source files that exhibit the issue in addition
to quoting from them here.

# Steps to Reproduce
I created a project using https://github.com/idris-lang/Idris-dev/tree/master/samples/ST/Net and the following package file:

```
package idrishttp

sourcedir = src

modules = Network.TCP, Network.Http, Network.EchoSimple

opts = "-p contrib -p lightyear"

main = Main

executable = server
```

I ran `idris --build idrishttp.ipkg`

# Expected Behavior
Successfull build

# Observed Behavior
```
Entering directory `./src'
Type checking ./Main.idr
When attempting to perform error reflection, the following internal error occurred:
        No such variable Control.ST.st_precondition Type error while constructing reflected error This is probably a bug. Please consider reporting it at https://github.com/idris-lang/Idris-dev/issues
```

Also I discovered that ipkg names cannot have `-` in them, which is annoying

**Comment by shmish111** [comment]
If I don't have the Main file everything builds sucessfully, main is simply
```idris
module Main

import Network.EchoSimple

public export
main : IO ()
main = run startServer
```

**Comment by rbarreiro** [comment]
I had the same problem, rebuilding idris,  packages and the project after
erasing all ibc solved it for me.


Em 18/08/2017 14:33, "David Smith" <notifications@github.com> escreveu:

**Comment by shmish111** [comment]
A upgraded from idris 1.0 to 1.1.1 and now it works, thanks
