### ISSUE TITLE
Network.Socket `connect` swallows output

### ISSUE THREAD

**Issue by artagnon** [idris-lang/Idris-dev#4011]
# Steps to Reproduce
```
makeRequest : IO ()
makeRequest = do
    case !(socket AF_INET Stream 0) of
      Left err   => putStrLn "Error"
      Right sock =>
        do
          putStrLn "Foom"
          connect sock (Hostname "host") 80
          putStrLn "Bar"
```

# Expected Behavior
```
Foom
Bar
```

# Observed Behavior
```
Foom
```

What codepath could Idris possibly take to not print "Bar"? Ofcourse "host" doesn't resolve to a valid host, but that's besides the point.

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue.

**Comment by melted** [comment]
I'll take a look at it, it's been a while since I last built idris on my freebsd machine (the sockets stuff doesn't work with windows), so it'll take some time to get started.

**Comment by melted** [comment]
It's a segfault.
