### ISSUE TITLE
Idris exits when parsing malformed code file

### ISSUE THREAD

**Issue by justjoheinz** [idris-lang/Idris-dev#4013]
# Steps to Reproduce

Place this into a file `ops.idr`

    {-
    {-
    -}

# Expected Behavior

idris should hint that there is a parse error, but it should not quit. Especially in ide-mode as this kills the process without the application being potentially aware of it. In ide-mode it should also send parseable error information.

# Observed Behavior

```
~/Projects/idris/idris-sandbox/issue$ idris ops.idr
     ____    __     _                                          
    /  _/___/ /____(_)____                                     
    / // __  / ___/ / ___/     Version 1.1.1
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/      
 /___/\__,_/_/  /_/____/       Type :? for help               

Idris is free software with ABSOLUTELY NO WARRANTY.            
For details type :warranty.
idris: user error (./ops.idr:4:1: error: unexpected
    EOF, expected: end of comment
<EOF> 
^     )
~/Projects/idris/idris-sandbox/issue$
```

Idris simply quits.

**Comment by jfdm** [comment]
Hi @justjoheinz thanks for the issue report. I've fixed the typo in the title. Nested comments are one of those tricky things, however, I think it is more important if Idris' behaviour across the different modes is made more expected. If I find time, I'll try to have a look at it.

**Comment by melted** [comment]
The file can be simplified to `{-` :-)

Try to put it under some code and Idris doesn't quit.

The reason for the behavior is in the import parsing code (parseImports in Idris/Parser.hs:1563), where it call `fail` if the parsing doesn't succeed. The fix would be to handle a parse failure like it is in the `parseProg` function. The main problem would be to handle failure in the callers of parseImports that now  assumes it succeeds.
