### ISSUE TITLE
Docs are missing for e.g.  contrib.Text.* 

### ISSUE THREAD

**Issue by hejfelix** [idris-lang/Idris-dev#4047]
While searching the [contrib docs](https://www.idris-lang.org/docs/current/contrib_doc/) for the Text.PrettyPrint module, I realized that it's missing.

Does the module not follow the docs syntax or is it simply missing from the build?

**Comment by jfdm** [comment]
Missing from the build, or the docs are for a version of contrib prior to the inclusion of the `Pretty.Print` module. Those docs are published by hand. With installed version's of Idris the docs are stored locally in `idris --libdocdir` (I think that is the correct flag).

**Comment by melted** [comment]
It could be this bug https://github.com/idris-lang/Idris-dev/issues/2161

I have a diagnosis, but my solution needs a bit of work.

**Comment by jfdm** [comment]
@melted those docs are for Idris contrib v1.0. PrettyPrint wasn't included until v1.1 or newer.

**Comment by melted** [comment]
I mean that it could be an effect of the same bug.

**Comment by jfdm** [comment]
I am going to close this issue, as the pointed to idris docs were for a version of idris prior to inclusion of the pretty printer.
