### ISSUE TITLE
'nicest' function in contrib/Text/PrettyPrint/Core.idr is not lazy

### ISSUE THREAD

**Issue by hejfelix** [idris-lang/Idris-dev#4048]
@jfdm 

I'm trying to understand sources of complexity in the `PrettyPrint` module, and reading [Wadler's article](https://homepages.inf.ed.ac.uk/wadler/papers/prettier/prettier.pdf). On page 10 he states that lazy evaluation of `best`s "inner computation" is essential for efficiency.

I am unsure whether this can cause performance problems here:
https://github.com/idris-lang/Idris-dev/blob/ec294a15690ead749f7ac77b2fc62adb366b6b84/libs/contrib/Text/PrettyPrint/WL/Core.idr#L162-L169

In my playing around with the library, I do see big performance dips on larger expressions that I cannot explain otherwise. 

As an example, this expression doesn't terminate within any tolerable time:

```idris
:exec toString 0 15 $ fold (|//|) $ map text $ words "this is a long sentence with a lot of words that I can use for testing the performance of the prettier printer implementation. I need a few more words to prove my point, though."
```

The resulting doc from the fold is listed here: https://pastebin.com/4AJWcGnD

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue

**Comment by david-christiansen** [comment]
Ken Friis Larsen has a strict version of the algorithm in SML at https://github.com/kfl/wpp .

**Comment by hejfelix** [comment]
Now we're talking. Thanks! While I want this to be fixed, right now I need something that works 😀

**Comment by hejfelix** [comment]
Oh, I thought it was in idris :/

**Comment by david-christiansen** [comment]
We have a Haskell library that looks astonishingly similar to Ken's that could potentially be ported to Idris: http://davidchristiansen.dk/drafts/final-pretty-printer-draft.pdf

No idea how to make it pass the totality checker, though. Perhaps it just will...

/David

**Comment by jfdm** [comment]
Sorry, for delayed response. My port of Wadler-Leijens pretty print was a port of Shayam's version, and is not a strict version. It is total though... The lazy nice could be address through use of the Lazy annotation, or changing the core algorithm to be strict. I don't have time to really address this, but PRs are welcome.

**Comment by jfdm** [comment]
oh, i've fixed this, awaiting tests to finish running

**Comment by hejfelix** [comment]
Man, so cool, thanks -- how would I understand which version of Idris would include this fix?

**Comment by jfdm** [comment]
@hejfelix Currently the 'fix' is in the development version of Idris. Once a new release has been made, then you can get the library with the fix. Alternatively, you can check out the development version of idris and install contents of `libs/`using the version of idris you have installed.
