### ISSUE TITLE
Confusing message on syntax error in ctor declaration

### ISSUE THREAD

**Issue by Heimdell** [idris-lang/Idris-dev#405]
Version 0.9.8

When I write:

```
data Labelled : Type -> Type -> Type where
    (:::) : {Mark Payload : Type} -> Mark -> Payload -> Labelled Mark Payload
```

it fails with message:

```
(line N, column 15): unexpected ':' expecting <lot-of-variants>
```

in line with

```
data Labelled : Type -> ... where
```

the 15 symbol is the ':' between "Labelled" and its type.

But when I added a semicolon in the next line, like this:

```
data Labelled : Type -> Type -> Type where
    (:::) : {Mark, Payload : Type} -> Mark -> Payload -> Labelled Mark Payload
```

It does typecheck.

Seems like the parser rolls back too far in case when list of implicit parameters isn't separated with commas.

I think, it should not roll back but say "expected ',' or '}'" at the place of Payload in my case.

**Comment by ahmadsalim** [comment]
The parser error is now precise after #4170: 

```idris
./test.idr:2:19:
  |
2 |     (:::) : {Mark Payload : Type} -> Mark -> Payload -> Labelled Mark Payload
  |                   ^
unexpected 'P'
expecting '%' or type signature
```
