### ISSUE TITLE
Provide ELF binary

### ISSUE THREAD

**Issue by charles-cooper** [idris-lang/Idris-dev#4050]
Not sure if this is already being worked on but I think it would be helpful to have pre-built binaries for Linux. This would solve https://github.com/idris-lang/Idris-dev/issues/3811.

If no one else is working on this I would be happy to contribute as my time permits.

**Comment by charles-cooper** [comment]
I think this can be done via travis, as in https://github.com/chrisdone/jl/blob/7824e34edbc3f921397b3bcab024954de7557c60/.travis.yml#L89

**Comment by ahmadsalim** [comment]
@charles-cooper Thanks for the feature request! You are very welcome to make a PR if you are interested.
I will close the issue, since I think just having the relevant PR is better if possible, and we already have instructions for Linux users on building.
