### ISSUE TITLE
Feature request: Row polymorphism.

### ISSUE THREAD

**Issue by Josef-Vonasek** [idris-lang/Idris-dev#4066]
I am willing to implement row polymorphism for Idris, unless there is some reason for Idris not to have it.

Illustration:

```haskell
person : {name : String, age : Int}
person = {name = "Alan", age = 27}
```

Row polymoprhism in action

```haskell
> mapAge : (a -> b) -> {x | age : a} -> {x | age : b}
> mapAge fun {x | age} = {x | age = fun age} 
> mapAge (+1) person
{name = "Alan", age = 28}
```

Getters are generated at compile time.

```haskell
> :type .age
.age : {x | age : a} -> a
> .age person
27
> person.age
27
```

I am not yet decided and therefore open to discussion whether to

* automatically generate `map` syntax
* allow field addition and deletion
* *feel free to add your idea*

**Comment by ahmadsalim** [comment]
@Josef-Vonasek Thank you for the feature request.

It is already possible using dependent types to encode record polymorphic-like types, e.g. see:
https://github.com/jmars/Records or http://docs.idris-lang.org/en/latest/st/state.html .

Another note is that it is unlikely that major changes to language design are going to be accepted by @edwinb after 1.0 . Of course if there is a very good reason to include a change, e.g. something is fundamentally flawed or will fundamentally enable making the rest of the programs easier, you are welcome to discuss it on the mailing list on IRC.
