### ISSUE TITLE
Make the optparse-applicative bounds loose for the test suite regression-and-feature-tests

### ISSUE THREAD

**Issue by psibi** [idris-lang/Idris-dev#4069]
While this is fixed in the source repository here, it is still incorrect in the Hackage revision: https://hackage.haskell.org/package/idris-1.1.1/revision/0.cabal

So either a new minor version hackage release needs to be made or it's metadata again needs to be edited (Personally, I would favor just releasing a new release as the editing metadata made things difficult to track for me.)

This is currently keeping it out of stackage: https://github.com/fpco/stackage/pull/2856

**Comment by ahmadsalim** [comment]
@psibi Thanks for reporting the issue. if you are interested, you are welcome to make a PR loosening the bounds.

For a release, I think @edwinb is needed.

**Comment by psibi** [comment]
@ahmadsalim There is no PR required since the bound is already fixed in the master version of the source. It requires either of these two option:

* Releasing a new version of Idris
* Edit cabal metadata in Hackage in the form of revision
