### ISSUE TITLE
Idris calls C compiler with arguments in wrong order

### ISSUE THREAD

**Issue by asandroq** [idris-lang/Idris-dev#4078]
After parsing `%flag` directives the Idris backend calls the C compiler with the flags in the opposite order, which breaks some order-dependent flags. For instance, the following directive:

```
%flag C "-L/usr/local/IUP/lib -Wl,-Bstatic -Wl,-liup -Wl,-Bdynamic"
```
will result in the following arguments to the C compiler:

```
"-Wl,-Bdynamic","-Wl,-liup","-Wl,-Bstatic","-L/usr/local/IUP/lib"
```
which obviously has the opposite effect.

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue. We do welcome PRs!
