### ISSUE TITLE
add IORef to javascript backend

### ISSUE THREAD

**Issue by rbarreiro** [idris-lang/Idris-dev#4082]
I think that it might be good to have some basic stuff to work with idris javascript backend on the idris distribution, because otherwise every one will probably roll-out their own version.
I would like to start with IORef, because it exists for the C backend and I actually have already rolled my own version.

What would be a good place to put it? A new package? contribjs?

**Comment by melted** [comment]
Hmmm, I'd love to have that Just Work for both javascript and C with the same import.

**Comment by rbarreiro** [comment]
Same function name? Overloaded for IO and JS_IO in separated namespaces?

Em 21/09/2017 8:31 da manhã, "Niklas Larsson" <notifications@github.com>
escreveu:

**Comment by melted** [comment]
Yeah, I see no reason why js support should be second-class in the standard lib.

**Comment by ahmadsalim** [comment]
@rbarreiro You could also consider using an interface.

**Comment by ahmadsalim** [comment]
You could even have the `ffi` as a phantom argument in the IORef.

**Comment by rbarreiro** [comment]
Ok, I will work on the pr.

Em 21/09/2017 2:12 da tarde, "Ahmad Salim Al-Sibahi" <
notifications@github.com> escreveu:

**Comment by ahmadsalim** [comment]
@rbarreiro Thanks!

**Comment by rbarreiro** [comment]
I have a first try here https://github.com/rbarreiro/Idris-dev/blob/js_ioref/libs/base/Data/IORef.idr
But test basic021 gives this error
`basic021.idr:4:7:When checking right hand side of count with expected type
        IO ()

Can't find implementation for Show a

Possible cause:
        basic021.idr:5:25:When checking an application of function Data.IORef.readIORef:
                Type mismatch between
                        IORef Integer (Type of ref)
                and
                        IORef a (Expected type)
`
Since the readIORef function has exactly the same signature, this might be an issue on the typechecker, no? I will try to check this myself, but any hints are welcome.

**Comment by ahmadsalim** [comment]
@rbarreiro I think it fails because of injectivity requirements so it can not infer that IORef is injective and so it can not infer that `a` is `Integer`.
@edwinb Any ideas here?

**Comment by ahmadsalim** [comment]
@rbarreiro Yeah, especially since you only have `export` on IORef.
Consider instead using a wrapper as type constructor, e.g.

```idris
data IORef : Type -> Type where
         MkIORef : Raw -> IORef a
```

**Comment by rbarreiro** [comment]
@ahmadsalim That makes sense, I will change the code. Thanks

**Comment by rbarreiro** [comment]
Via #4101
