### ISSUE TITLE
Error putting Type as argument in Show instance.

### ISSUE THREAD

**Issue by jackolantern** [idris-lang/Idris-dev#4087]
# Steps to Reproduce

Compile and run the following code:
```idris
module Main

data Foo = Bar
         | Bin

Show Foo where
  show Foo = "Foo"
  show Bar = "Bar"
  show Bin = "Bin"

main : IO ()
main = putStrLn $ show [Bar, Bin]
```

# Expected Behavior
I would expect the code not to compile, due to the presence of `show Foo`

# Observed Behavior
The code compiles and `show Bar` and `show Bin` evaluate to `"Foo"`.

**Comment by melted** [comment]
Idris doesn't require that variables starts with lower case. So it doesn't see `Foo` as the type but as a variable, which is a pattern match that succeeds. You can put anything there except the constructors and the outcome will be the same.

**Comment by msmorgan** [comment]
Perhaps Idris should issue a warning when an existing capitalized name is used in a pattern that would fail to type-check if matched.

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue, but this is indeed expected behaviour.
@msmorgan 
A PR is welcome for warning on capitalized names, but such should include an activation flag like `--warn-capitalized`.

**Comment by eraserhd** [comment]
@jackolantern Oh man, this didn't occur to me last night :/

I think something like GHC's `-Woverlapping-patterns` would catch most of the cases.
