### ISSUE TITLE
Error running ":exec" in my Mac terminal

### ISSUE THREAD

**Issue by RedDevilArmy** [idris-lang/Idris-dev#4105]
When trying to use ":exec" in my Mac terminal, I got error message below. I installed Idris using package file, and I wanted to uninstall Idris and try reinstalling it using Homebrew because one of my friends used Homebrew to install idris with no problem running ":exec" command. Anyone knows know to completely uninstall Idris or how to fix error below? I would be appreciate your help. Thanks.
**Error Message:**
```idris
ld: file too small (length=0) file '/var/folders/4n/n52w41kj0k58cm5qplpwybcm0000gq/T/idris1622650073984943658' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
FAILURE: "gcc" ["-O2","-fwrapv","-fno-strict-overflow","-DHAS_PTHREAD","-DIDRIS_ENABLE_STATS","-I.","/var/folders/4n/n52w41kj0k58cm5qplpwybcm0000gq/T/idris1144108930470211272.c","-L/usr/local/share/x86_64-osx-ghc-7.10.3/idris-1.1.1/rts","-lidris_rts","-lpthread","-I/usr/local/share/x86_64-osx-ghc-7.10.3/idris-1.1.1/rts","-lm","-I.","-I/Users/edwin/.cabal/share/x86_64-osx-ghc-7.10.3/idris-1.1.1/libs/prelude","-I/Users/edwin/.cabal/share/x86_64-osx-ghc-7.10.3/idris-1.1.1/libs/base","-I.","-I/usr/local/share/x86_64-osx-ghc-7.10.3/idris-1.1.1/libs/prelude","-I/usr/local/share/x86_64-osx-ghc-7.10.3/idris-1.1.1/libs/base","-I","-o","/var/folders/4n/n52w41kj0k58cm5qplpwybcm0000gq/T/idris1622650073984943658"]
/var/folders/4n/n52w41kj0k58cm5qplpwybcm0000gq/T/idris1622650073984943658: rawSystem: runInteractiveProcess: exec: permission denied (Permission denied)
```

**Comment by ahmadsalim** [comment]
Thanks for the issue report.

I would however recommend using the mailing list or IRC for matters regarding installation and set-up since this regards individual machines and not the language itself.

It seems to me that the files you have compiled are compiled to the wrong architecture somehow, but I think people on the mailing list might be to more help.
