### ISSUE TITLE
`stack-shell.nix` doesn't work with NixOS 17.09

### ISSUE THREAD

**Issue by vaibhavsagar** [idris-lang/Idris-dev#4107]
# Steps to Reproduce
```bash
$ stack --nix build
```

# Expected Behavior
A working executable.

# Observed Behavior
`error: attribute ‘lts-9_0’ missing`

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue.

I am unfortunately not familiar with the platforms, so I can not provide a workaround but hopefully someone will come here who is part of maintaining the Nix package or stack package.
