### ISSUE TITLE
typeclass constraints and named parameters don't work on the rhs of top-level declarations

### ISSUE THREAD

**Issue by startling** [idris-lang/Idris-dev#411]
The following code parses and typechecks:
````
Traversal : Type -> Type -> Type -> Type -> Type
Traversal s t a b = (f : Type -> Type)
  -> Applicative f -> (a -> f b) -> s -> f t
````

but if I try to make the `f : Type -> Type` implicit, I get an error:

````
Traversal : Type -> Type -> Type -> Type -> Type
Traversal s t a b = {f : Type -> Type}
  -> Applicative f -> (a -> f b) -> s -> f t
````
````
"./bug.idr" (line 2, column 11):
unexpected "s"
expecting ":" or operator
````

and if I try to use typeclass constraint syntax, I get a similar one.
````
Traversal : Type -> Type -> Type -> Type -> Type
Traversal s t a b = Applicative f => (a -> f b) -> s -> f t
````
````
"./bug.idr" (line 2, column 11):
unexpected "s"
expecting ":" or operator
````

I have a feeling this is a parser error (different rules for signatures and declarations?) but I don't know enough about how implicit parameters or typeclasses work in Idris to say for sure whether the code I gave is workable in the first place.

**Comment by edwinb** [comment]
This syntax has worked for a while now, so this should be closed.

**Comment by startling** [comment]
Thanks!
