### ISSUE TITLE
Why (`add` 1) is not supported?

### ISSUE THREAD

**Issue by luochen1990** [idris-lang/Idris-dev#4123]
```idris
Idris> :let add = (+)
Idris> 1 `add` 2
3 : Integer
Idris> :let inc = (+ 1)
Idris> :let inc' = (`add` 1)
(input):1:14: error: expected: ")",
    dependent type signature,
    expression, name
:let inc' = (`add` 1)<EOF>
             ^
```

`(+ 1)`  is supported
```1 `add` 2``` is supported
but ``` `add` ``` is not same as `+` since ```(`add` 1)``` is not supported

Is it a bug or not?

**Comment by iamrecursion** [comment]
I believe a fix for this was just merged in #4119. Are you on the latest build?

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue but as @iamrecursion mentioned we have just had the #4119 issue merged.

**Comment by luochen1990** [comment]
This problem is solved, checked on the following version:

```
$ /c/Users/Luo/Github/Idris-dev/.stack-work/dist/5c8418a7/build/Idris/idris.exe --version
1.2.0-git:395e8a07
```
