### ISSUE TITLE
Effect

### ISSUE THREAD

**Issue by zaoqi-unsafe** [idris-lang/Idris-dev#4124]
Paper
http://www.cs.st-andrews.ac.uk/~eb/drafts/effects.pdf
User homepage not found

**Comment by clayrat** [comment]
It's at https://eb.host.cs.st-andrews.ac.uk/drafts/effects.pdf

**Comment by ahmadsalim** [comment]
Thanks, but this is for @edwinb to fix on his website so I will close the issue.
