### ISSUE TITLE
Symmetrical Uninhabited instances for equalities

### ISSUE THREAD

**Issue by anton-trunov** [idris-lang/Idris-dev#4136]
# Steps to Reproduce

```
[SymUninhabitedEq] Uninhabited (x = y) => Uninhabited (y = x) where
    uninhabited = absurd . sym

lemma : S n = Z -> Void
lemma = absurd
```

# Expected Behavior
Everything typechecks.

# Observed Behavior
Fails with with the following error message :

> When checking right hand side of lemma with expected type
>              (S n = 0) -> Void
>      
>      Can't find implementation for Uninhabited (S n = 0)

# Motivation

Avoiding code duplication when describing disjointness of constructors, e.g. now we have to create instances such as `Uninhabited (True = False)` and `Uninhabited (False = True)`, and the same thing for `Nat` and so on.

Observe that the following typechecks:

```
lemma : S n = Z -> Void
lemma = absurd @{SymUninhabitedEq}
```

but it's not really a workaround. This just says that the instance we need exists, and this is in contradiction with the error message.

**Comment by david-christiansen** [comment]
This is Idris functioning as expected. Named implementations don't participate in implementation search, and this particular one would also make the search space huge.

To avoid the code duplication, I think it would be better to automate the production of these implementations, either with a special-purpose deriving feature or using elaborator reflection. Most of the work is already done in https://github.com/idris-lang/Idris-dev/blob/master/libs/pruviloj/Pruviloj/Disjoint.idr .

**Comment by anton-trunov** [comment]
Thanks for the explanation!

**Comment by david-christiansen** [comment]
No prob! If you want to finish up that metaprogram, let me know :-)
