### ISSUE TITLE
Names from Language.Reflection leak into scope 

### ISSUE THREAD

**Issue by mpickering** [idris-lang/Idris-dev#4144]
Even when `Language.Reflection` is not imported, it seems its names are in scope. 

```
module Bug

foo : Binder a -> Int
foo x = 5
```

When launching the repl and then typing `:l bug.idr` then the program is accepted. It should be rejected as `Binder` is not in scope.

**Comment by melted** [comment]
For some reason it’s part of the prelude so it’s works as expected.

**Comment by jfdm** [comment]
The reflection utilities are used in the Prelude. Specifically:

https://github.com/idris-lang/Idris-dev/blob/master/libs/prelude/Prelude.idr#L45

The prelude is implicitly imported in all modules.

**Comment by mpickering** [comment]
That makes sense I will close this ticket then but it seems strange to me to export internal compiler names in the prelude.
