### ISSUE TITLE
Wrong type error message when number of elements in vector does not match

### ISSUE THREAD

**Issue by hardvain** [idris-lang/Idris-dev#4153]
The compiler reports a misleading error message on the actual and expected types when working with Vect. 
# Steps to Reproduce
In the below code snippet,
```
twelveInts : Vect 12 Int
twelveInts = [0, 1, 2, 3, 4, 5, 6, 7]
```
# Expected Behavior
The error message should be something like Expected 12 element vector but got 8 element vector.
# Observed Behavior
```
When checking right hand side of fourInts with expected type
        Vect 12 Int

When checking argument xs to constructor Data.Vect.:::
        Type mismatch between
                Vect 0 elem (Type of [])
        and
                Vect 4 Int (Expected type)

        Specifically:
                Type mismatch between
                        0
                and
                        4
```

I believe that the compiler is trying to tell that 4 more items are required, but the actual error message states otherwise.

If this is a valid bug, I would like to fix it. Kindly give me some pointers to fix it. I know some haskel but new to idris.

**Comment by melted** [comment]
The size is part of the type so it’s a type mismatch.

**Comment by hardvain** [comment]
@melted Yes. Its a type mismatch. But should the message be something like 
```
When checking right hand side of fourInts with expected type
        Vect 12 Int

When checking argument xs to constructor Data.Vect.:::
        Type mismatch between
                Vect 8 elem (Type of [])
        and
                Vect 12 Int (Expected type)

        Specifically:
                Type mismatch between
                        8
                and
                        12
```

**Comment by ahmadsalim** [comment]
@hardvain This is expected behaviour.
The notation `[a,b,c]` is syntactic sugar for `a :: b :: c :: []` and the type error here is that instead of an empty list `[]` you should provide it a list of 4 elements.

I am not sure there is a way to generically give a better error message, which does not involve hardcoding the case for `Vect`.

**Comment by hardvain** [comment]
@ahmadsalim Thank you for the explanation.
