### ISSUE TITLE
Data.List.isElem extremely slow for large Lists (k>10)

### ISSUE THREAD

**Issue by janschultecom** [idris-lang/Idris-dev#4161]
The function ```Data.List.isElem``` is getting extremely slow with an increasing number of elements in the list. The 
reason for this is the inlining of the ```mkNo``` function. Extracting ```mkNo``` to a top-level function solves the problem.
For ```Data.Vect.isElem```, this is actually already implemented like this (see function ```neitherHereNorThere``` ) and makes ```Data.Vect.isElem``` much faster than ```Data.List.isElem``` (see Expected Behavior).

# Steps to Reproduce
It can be reproduced easily in the repl following these steps:
```idris
-- fast
isElem 'A' ['a'..'c'] 

-- starting to get slow
isElem 'A' ['a'..'k'] 

-- not usable any more
isElem 'A' ['a'..'z'] 
```
# Expected Behavior
Data.List.isElem should be as fast as Data.Vect.isElem.
```idris
:module Data.Vect
-- fast
Data.Vect.isElem 'A' (Data.Vect.fromList ['a'..'c'])

-- fast
Data.Vect.isElem 'A' (Data.Vect.fromList ['a'..'k'])

-- still fast
Data.Vect.isElem 'A' (Data.Vect.fromList ['a'..'z'])
```
# Observed Behavior
Data.List.isElem starting to get slow for lists > 10 elements.

**Comment by ahmadsalim** [comment]
@janschultecom Have you tried compiling the program?

The REPL uses compile-time evaluation which is not very fast.

**Comment by ahmadsalim** [comment]
@janschultecom We would appreciate a PR that lifted it to global namespace and gave it a proper name, if you are interested 😄 .

**Comment by janschultecom** [comment]
Yep, compiling is the same.

Ok great, will see what I can do :-)
