### ISSUE TITLE
Node backend errors when generating function

### ISSUE THREAD

**Issue by asandroq** [idris-lang/Idris-dev#4172]
# Steps to Reproduce

Compile the following file with `idris --codegen node -o testcase testcase.idr`:

```idris
module Main

main : IO ()
main = do args <- getArgs
          case args of
            (_ :: input :: _) => do st <- readFile input
                                    case st of
                                      Right contents => putStrLn $ "Contents: " ++ contents
                                      Left err => printLn err
            _ => putStrLn "No input file was given"
```
# Expected Behavior

The compiler should finish successfully.

# Observed Behavior

The compiler aborts with:

```
idris-codegen-node: Foreign arg type FCon C_Ptr not supported. While generating function "Prelude__Strings__addToStringBuffer"
CallStack (from HasCallStack):
  error, called at src/IRTS/JavaScript/Codegen.hs:584:5 in idris-1.1.1-HysTDlWIxEf67Pphf1dD8O:IRTS.JavaScript.Codegen
FAILURE: "idris-codegen-node" ["./testcase.ibc","-o","testcase"]
```

**Comment by jfdm** [comment]
This is correct behaviour. The `IO` context, is actually specialised for the C codegen, for any IO operations you will need to use the JS IO context. This context, I am not familiar with,

**Comment by rbarreiro** [comment]
This is happening because some of the functions are using C_FFI. When I
intend to generate code for Node I use JS_IO instead. Maybe something
should be done about this, I am not sure what.

Em 02/11/2017 4:08 da tarde, "Alex Queiroz" <notifications@github.com>
escreveu:
