### ISSUE TITLE
totality checker lets diverging non-inductive function through.

### ISSUE THREAD

**Issue by sellout** [idris-lang/Idris-dev#4192]
**NB**: This was done on Idris 1.0. I’m not certain the issue exists on more recent versions.

# Steps to Reproduce
Compiling the following will work, despite `ana` not being inductive.
```idris
%default total

ana : (a -> Maybe a) -> a -> Nat
ana f = go . f
  where go Nothing  = Z
        go (Just a) = S $ ana f a

-- this diverges
infinity : Nat
infinity = ana Just ()
```
if instead I define
```idris
ana f = (\m => case m of
            Nothing => Z
            Just a  => S $ ana f a)
        . f
```
the checker catches it: “Main.ana is possibly not total due to recursive path Main.ana --> Main.ana”

# Expected Behavior

I should get the same error compiling the `go` implementation as I do with the inlined one.

# Observed Behavior

The first version passes the totality checker successfully (which it shouldn’t).

**Comment by ahmadsalim** [comment]
Interestingly Idris finds the error if I do eta-expansion:
```idris
ana : (a -> Maybe a) -> a -> Nat
ana f = (\a => go (f a))
  where go Nothing  = Z
        go (Just a) = S $ ana f a
```

**Comment by ahmadsalim** [comment]
Interestingly Idris finds the error if I do eta-expansion:
```idris
ana : (a -> Maybe a) -> a -> Nat
ana f = (\a => go (f a))
  where go Nothing  = Z
        go (Just a) = S $ ana f a
```

Also, it fails to find the error if I manually lift it to a `mutual` block:

```idris
mutual
  go : (a -> Maybe a) -> Maybe a -> Nat
  go f Nothing  = Z
  go f (Just x) = S $ ana f x

  ana : (a -> Maybe a) -> a -> Nat
  ana f = go f . f
```

**Comment by ahmadsalim** [comment]
I have debugged the issue and it seems that it is because Idris currently performs a simplistic expansion of arguments which assumes that non-provided arguments do not change in size.
Unfortunately, this is not sound as witnessed by the example given, and we must do eta-expansion instead to check termination correctly.

See https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/Termination.hs#L432
