### ISSUE TITLE
Implementing Permutations of a List.

### ISSUE THREAD

**Issue by Average-user** [idris-lang/Idris-dev#4230]
I couldn't find any built-in implementation of permutations, like the one from [Haskell Data.List](http://hackage.haskell.org/package/base-4.10.0.0/docs/src/Data.OldList.html#local-6989586621679156146). If you are interested I could translate that one and make a PR.

**Comment by ahmadsalim** [comment]
@Average-user Contributions are more than welcome. You can add one to the `contrib` library and we will take a look.

PS: Please us the mailing list or IRC for discussing contributions next time, since we reserve the issue tracker for tracking bugs and similar.

**Comment by Average-user** [comment]
@ahmadsalim Got it.
