### ISSUE TITLE
Feature request: custom annotations on top-level bindings

### ISSUE THREAD

**Issue by mrkgnao** [idris-lang/Idris-dev#4234]
@owickstrom (with whom I'm collaborating on https://github.com/owickstrom/idris-vimscript) suggested trying to export functions that could then be called from external scripts. Is there an existing way to do so?

If not, I think something like

```idris
%no_mangle
foo : Int -> Int
foo x = x
```

or even "anonymous switches" like 

```idris
%attr(no_mangle)
```

(sort of like `{- ANN hlint -}` but integrated into the compiler like Haskell's `{-# foo #-}`) might be worth looking at.

If I'm estimating the scope of this correctly, I'd say this is something I'm comfortable implementing if it doesn't exist.

**Comment by melted** [comment]
It might be interesting to have a way to add custom annotations. But you don't need to have it to export functions as there already exists such a system (used in the C backend). Look at tests/ffi006 for an example.

**Comment by david-christiansen** [comment]
Lean has these, and it's incredibly handy for them.

**Comment by jfdm** [comment]
It might be good to double check our documentation to see if the 'exporting' is well documented.

**Comment by ahmadsalim** [comment]
I think I have suggested a similar idea before, but I never got around to implement something similar 😄

**Comment by ahmadsalim** [comment]
@mrkgnao Yeah, https://github.com/idris-lang/Idris-dev/issues/3145 .
Could you kindly add your request to that issue? To make things more collected.

I will close this one
