### ISSUE TITLE
macOS: can't load file in inside REPL unless it was started from home directory

### ISSUE THREAD

**Issue by rednum** [idris-lang/Idris-dev#4241]
# Steps to Reproduce

```
marcinf:~$ cd
marcinf:~$ cd idris/
marcinf:idris$ cat hello.idr
module Main

main : IO ()
main = putStrLn "Hello world"
marcinf:idris$ idris
/usr/local/share/x86_64-osx-ghc-7.10.3/idris-1.1.1/libs/prelude/Prelude.idr: openFile: does not exist (No such file or directory)
     ____    __     _
    /  _/___/ /____(_)____
    / // __  / ___/ / ___/     Version 1.1.1-git:5e0301c
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/
 /___/\__,_/_/  /_/____/       Type :? for help

Idris is free software with ABSOLUTELY NO WARRANTY.
For details type :warranty.
Idris> :l hello
Module needs reloading:
	SRC : "./IO.idr"
	Modified at: 2017-10-28 16:02:00 UTC
	IBC : "/usr/local/share/x86_64-osx-ghc-7.10.3/idris-1.1.1/libs/prelude/IO.ibc"
	Modified at: 2017-08-05 17:22:43 UTC

*hello> :exec main
No such variable run__IO
```

# Expected Behavior

I should be able to load the module.

# Observed Behavior

Module doesn't work. 

However, when I start Idris from my home directory and do `:cd idris/` inside repl, I can load the files.

As far as I remember I installed Idris from officially provided binaries. `idris --version` returns `1.1.1-git:5e0301c`. Also I'm on macOS, version: 10.12.6

**Comment by rednum** [comment]
Just found another workaround: use Idris binary compiled on my machine.

**Comment by ahmadsalim** [comment]
@rednum Please note that this seems to be an issue specific to your set-up, and I would therefore kindly ask you to discuss this on the mailing list or IRC.

If you can not get it working on the mailing list and find a more specific bug, please open an issue here.
