### ISSUE TITLE
Idris silently accepts invalid option strings in .ipkg files

### ISSUE THREAD

**Issue by gallais** [idris-lang/Idris-dev#4255]
I had the option `opts = "-total -p contrib"` (notice the single hyphen in `-total`) in
an .ipkg file and instead of being warned that it was an invalid option string, Idris
silently kept going, ignoring the rest of the options.

Instead I got a confusing error: `idris --build` reported not being unable to find a
module defined in contrib.

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue.

**Comment by gallais** [comment]
Comments on the tentative patch are welcome!

When I try to generate the `expected` file for the new test case I have added
with `cabal test --test-options="--pattern pkg009 --accept"`, I get the following
error:

```
Running 1 test suites...
Test suite regression-and-feature-tests: RUNNING...
For running the test suite against Node, node must be installed.
Test suite regression-and-feature-tests: FAIL
Test suite logged to: dist/test/idris-1.1.1-regression-and-feature-tests.log
0 of 1 test suites (0 of 1 test cases) passed.
```

Do you I really need to install node.js to generate that one file?

**Comment by ahmadsalim** [comment]
@gallais You are welcome to open a PR without installing `node.js` and let Travis handle the testing. It seems that for some reason running our tests locally require installing `node`.

**Comment by gallais** [comment]
How should I generate the `expected` file though? The README adivses me to use `cabal test`.

**Comment by ahmadsalim** [comment]
@gallais It should not be generated. It should be constructed explicitly with the output you expect and added to the version control (unline `output`).
For the first time you can just write whatever output the command you call gives you.
