### ISSUE TITLE
Recursive type incorrectly complains about too many arguments

### ISSUE THREAD

**Issue by JadenGeller** [idris-lang/Idris-dev#4256]
# Steps to Reproduce
Compile the following code:
```idris
Next : Type -> Type
Next a = a -> (b : Type ** Next b)

foo : Next Bool
foo isNull = ?bar
```

# Expected Behavior
It works.

# Observed Behavior
Error: `Too many arguments for Main.foo`

**Comment by ahmadsalim** [comment]
@JadenGeller
This is correct, since you have a recursive type equation here, which is partial and so would not reduce.
You may be able to get this working by using a `record` or `data` value, but not an explicit equation.
