### ISSUE TITLE
Better type error on left hand side checking

### ISSUE THREAD

**Issue by k-bx** [idris-lang/Idris-dev#4268]
# Steps to Reproduce

I was working through the excellent Type-Driven Development with Idris book, and got to this piece of code:

```idris
module Main

import Data.Vect

data DataStore : Type where
  MkData : (size : Nat) ->
           (items : Vect size String) ->
           DataStore

size : DataStore -> Nat
size (MkData size items) = size

items : (store : DataStore) -> Vect (size store) String
items (MkData size items) = items

addToStore : DataStore -> String -> DataStore
addToStore (MkData size items) newitem = MkData _ (addToData items)
  where
    addToData : Vect old String -> Vect (S old) String
    addToData [] = [newitem]
    addToData (item :: items) = item :: addToData items

main : IO ()
main = ?main_rhs
```

Trying to load in REPL would show this error:

```
- + Errors (1)
 `-- DataStore.idr line 21 col 14:
     When checking left hand side of Main.addToStore, addToData:
     Can't match on Main.addToStore, addToData (S size)
                                               size
                                               items
                                               newitem
                                               (item :: items)
```

# Expected Behavior

To be honest, I'd expect it to type-check (and don't clearly see why wouldn't it). But as an alternative – if you rename arguments of `addToData` to `item'` and `items'`, for example, it would type-check.

What I don't like even more is the fact that the error did not suggest enough help to me, I fixed this type-error intuitively and I feel like it could be somehow improved.

I have Idris version 1.1.1 installed via HomeBrew. Thanks!

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue. I believe this is expected behaviour, since Idris captures variable names in patterns, since it allows dependent (non-linear) refinement and does not overshadow variable names.
