### ISSUE TITLE
Cannot find out if currently running in interpreter

### ISSUE THREAD

**Issue by 6A** [idris-lang/Idris-dev#4269]
Is there a way to determine if the code being executed is actually being interpreted (as opposed to executed by the C backend, for instance)? If so, how?

I thought the `System.Info.backend` function would return "interactive" or something of the sort if interpreted, but it actually forces a recomputation of the executing function in a compiled context.

**Comment by ahmadsalim** [comment]
@6A 
Thank you for the issue report.

Could you kindly rephrase your issue to use the template, and provide an example? I do not seem to understand what your target result is and why you want to avoid executing an expression twice.

**Comment by 6A** [comment]
@ahmadsalim It's not a bug per-say, which is why I did not follow the provided template. It's just a general question that none of the docs answered.

I'll update my original post.

**Comment by ahmadsalim** [comment]
@6A There is no way to determine whether the code is currently running in interactive mode or using the C backend. Note that the interactive mode of Idris is pure per default, so there are no side-effects that can be executed.

PS: Please use the mailing list next time for questions. The issue tracker is primarily for tracking bugs.
