### ISSUE TITLE
Wrong type inference of nested tuples

### ISSUE THREAD

**Issue by hardvain** [idris-lang/Idris-dev#4287]
# Steps to Reproduce
* Open idris REPL 
* Type `(1,(2,3))` and press enter

# Expected Behavior
The expected output is `(1, (2, 3)) : (Integer, (Integer, Integer))`

# Observed Behavior
The actual output is `(1, 2, 3) : (Integer, Integer, Integer)`

This happens not only in the REPL. The following code compiles as well:
```
test : (Integer, Integer, Integer)
test = (1, (2,3))
```
If this is a trivial bug to fix, please give me some pointers and I will try to fix it.

**Comment by ahmadsalim** [comment]
This is expected behaviour. In Idris `(A, B, C)` is the same as `(A, (B, C))`.

**Comment by LeifW** [comment]
That's just how Idris represents tuples (as that recursive structure). Both
are equivalent.
