### ISSUE TITLE
Totality checking says obviously not total function is total

### ISSUE THREAD

**Issue by 2426021684** [idris-lang/Idris-dev#4299]
# Steps to Reproduce
Write this in a file:
```idris
module Main
import Data.Vect
%default total

p : Elem (Maybe x) (map Maybe xs) -> Elem x xs
p Here impossible
p (There l) impossible
```
Load it in the Idris REPL

# Expected Behavior

It says that p is not total.

# Observed Behavior

Idris accepts it as total. Even `:total` thinks that `p` is total.

**Comment by luochen1990** [comment]
@2426021684 Do you mean to use `Just` instead of `Maybe`?

When you use `Maybe`, you means that `x` is a type, and the unification of them is obviously impossible.
If you use `Just`, then the type checking result is as you expected.

**Comment by 2426021684** [comment]
@luochen1990 I have no idea what you are saying. There is a valid total definition of p. I did not mean to use `Just`.

```
p : Elem (Maybe x) (map Maybe xs) -> Elem x xs
p {xs = _ :: _} Here = Here
p {xs = _ :: _} (There l) = There (p l)
```

**Comment by luochen1990** [comment]
@2426021684 sorry, I think you are right, this is indeed something weird.

**Comment by luochen1990** [comment]
And I also find that the following will throw an error as expected:

```
p : Elem (Maybe x) (map Maybe xs) -> Elem x xs
p {xs = _ :: _} Here impossible
p {xs = _ :: _} (There l) impossible
```

**Comment by yanok** [comment]
Related to #4282 (in fact, it's the same problem).
