### ISSUE TITLE
Name of file influences whether invalid program compiles

### ISSUE THREAD

**Issue by turnage** [idris-lang/Idris-dev#4322]
The same code compiles or doesn't compile based on its filename.

# Steps to Reproduce
````idris
module Main

data Foo = Bar | Haz

f : Foo -> String
f Bar = "aye"

main : IO ()
main = putStrLn $ f Haz
````
# Expected Behavior

A compiler error regardless of filename.

# Observed Behavior

1. If you name this file `Main.idr` or `test.idr`, it will compile silently and then segfault at runtime.
2. If you name this file `Haz.idr`, the compiler with rightfully reject it because main is not total.

Further context: https://groups.google.com/forum/#!topic/idris-lang/159h0ou1-cE

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue.

**Comment by edwinb** [comment]
I can't reproduce this in master... which version are you using?

It might be related to a problem with pattern variable names which I recently fixed.

**Comment by melted** [comment]
Can't reproduce the naming difference. Anyway, the crash is expected as Idris by default accepts partial functions, add total or `%default total` to only accept total functions.
