### ISSUE TITLE
Type as Data Type

### ISSUE THREAD

**Issue by zaoqi** [idris-lang/Idris-dev#4329]
Please attach complete source files that exhibit the issue in addition
to quoting from them here.

# Steps to Reproduce
```idris
typeOfList : Type -> Type
typeOfList (List a) = a
```
# Expected Behavior
``
# Observed Behavior
```
   |
32 | typeOfList (List a) = a
   | ~~~~~~~~~~~~~~~~~~~
When checking left hand side of typeOfList:
No explicit types on left hand side: List a
```

**Comment by LeifW** [comment]
This is expected behaviour - you're not allowed to pattern-match on types. Perhaps the error could say "No explicit types allowed on left hand side" to make that clearer?

There's a related stackoverflow: https://stackoverflow.com/questions/45439486/pattern-matching-on-type-in-idris
