### ISSUE TITLE
Syntax Extensions

### ISSUE THREAD

**Issue by zaoqi** [idris-lang/Idris-dev#4330]
Please attach complete source files that exhibit the issue in addition
to quoting from them here.

# Steps to Reproduce
```idris
syntax [x] "：" [t] = x : t
```
# Expected Behavior
`
`
# Observed Behavior
```
   |
19 | syntax [x] "：" [t] = x : t
   |                        ^
not a terminator

```

**Comment by joom** [comment]
`x : t` is not an expression, so I think this is expected behavior.

Are you trying to do type ascription? Try `syntax [x] "：" [t] = the t x`

**Comment by ahmadsalim** [comment]
I agree with @joom. This is expected behaviour.

**Comment by zaoqi** [comment]
@ahmadsalim So I will writing a Lisp that translate to Idris.
