### ISSUE TITLE
Should an identity Cast be provided?

### ISSUE THREAD

**Issue by jacereda** [idris-lang/Idris-dev#4349]
As a newbie, I find it quite surprising that I can't cast from `Double` to `Double`. I asked on IRC and the response was that you shouldn't need it, so I tried to figure out an example where it would be useful.

What about this? 

```idris
import Data.HVect

interface AsDoubles (ts : Vect k Type) where
  asDoubles : HVect ts -> Vect k Double

AsDoubles [] where
  asDoubles [] = []

(Cast t Double, AsDoubles ts) => AsDoubles (t::ts) where
  asDoubles (x::xs) = cast x :: asDoubles xs

stupid1 : Vect 3 Double
stupid1 = asDoubles [the Int 1, the Integer 2, "3"]

-- Uncomment to make it type check 
-- Cast x x where
--  cast = id

stupid2 : Vect 4 Double
stupid2 = asDoubles [the Int 1, the Integer 2, "3", the Double 4]
```

**Comment by ahmadsalim** [comment]
@jacereda We have discussed this before, like in #3833 .

Please note, that you can just as well use `map cast` instead of `asDoubles` in case you need something which is not `Double` already.

**Comment by jacereda** [comment]
Is HVect a functor?

**Comment by ahmadsalim** [comment]
@jacereda I will refer to the answer of the rejection here: https://github.com/idris-lang/Idris-dev/issues/3479#issuecomment-254211975 .

I will show you a possible `map` implementation.

**Comment by ahmadsalim** [comment]
Here is a possible way to do the mapping:

```idris
module Test

import Data.HVect

mapH : {C, P : Type -> Type} -> ({a : Type} -> C a -> a -> P a) -> HVect (map C ts) -> HVect ts -> HVect (map P ts)
mapH f [] [] = []
mapH f (c :: cs) (x :: xs) = f c x :: mapH f cs xs

asDouble : {a : Type} -> Either (Cast a Double) (a = Double) -> a -> Double
asDouble (Left cstr) x = cast x
asDouble (Right p) x = replace p x

asDoubles : HVect (map (\t => Either (Cast t Double) (t = Double)) ts) -> HVect ts -> HVect (map (const Double) ts)
asDoubles cs xs = mapH asDouble cs xs
```

**Comment by jacereda** [comment]
Nice!

In any case, I get the rationale, but from a practical point of view (and given that there're like 4 tickets asking the same thing) I'd consider adding it just to prevent another N tickets being raised ;)

**Comment by ahmadsalim** [comment]
@jacereda You are welcome to add it to the Unofficial FAQ 😄

**Comment by jacereda** [comment]
https://github.com/idris-lang/Idris-dev/wiki/Unofficial-FAQ#why-isnt-there-a-default-cast-ty-ty-implementation

**Comment by ahmadsalim** [comment]
@jacereda Thanks!
