### ISSUE TITLE
Not a valid name for a pattern variable

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#4359]
The program
```
> %default total
> %access public export
> %auto_implicits off


> Unique : Type -> Type
> Unique t = (p : t) -> (q : t) -> p = q

> Unique1 : {A : Type} -> (A -> Type) -> Type
> Unique1 {A} P = (a : A) -> Unique (P a)
```
does not type check with 1.2.0-git:507a7312. The error message is
```
- + Errors (1)
 `-- ./issues/not_a_valid_name.lidr line 10 col 2:
     When checking left hand side of Unique1:
     When checking argument A to Main.Unique1:
             A is not a valid name for a pattern variable
```
There are hundreds of lines of code in https://gitlab.pik-potsdam.de/botta/IdrisLibs/tree/towards1.1.1 that do not type check anymore with similar error messages. Until a few weeks ago and under 1.2.0, they typed checked fine. Perhaps a regression?

**Comment by clayrat** [comment]
AFAIK, since 1.2.0 patterns starting with a capital letter are disallowed

**Comment by nicolabotta** [comment]
@clayrat Thanks, that would be very sad since I have hundreds such patterns in IdrisLibs. Do you know what's the point of not allowing patterns starting with a capital letter? Are we slowly moving towards Fortran77?

**Comment by ahmadsalim** [comment]
@nicolabotta I will take a look at adding a switch for this 😄 . It was meant to prevent common errors, but of course we can't have it break large libraries like yours.

**Comment by nicolabotta** [comment]
@ahmadsalim Thanks Ahmad! Apart from the practical probelem of breaking legacy code: I cannot make any sense of this new rule. In mathematical specifications, it is standard to write expressions like `x \in X`, `Even = {2 * n | n \in N}`, `f : A -> B`. If one wants to argue in favour of dependent types and dependently typed specifications, it is crucial that sets can be represented as types and that the language allows types to be represented by upper-cased names. In short, for me it does not make any sense to force users to write `x : x` or `f : a -> b`
instead of `x : X`and `f : A -> B`. I understand that expressions like `x :: x` and `f :: a -> b` are standard in Haskell. But this does not imply that they are good or suitable for dependently typed languages.  We should rather ask ourselves why Haskell is so unpopular, even among mathematicians. Just my two cents, of course!

**Comment by ahmadsalim** [comment]
@nicolabotta I have opened PR #4366 . I will merge it if there is no serious issues with tests.

I understand the usability of having capitalized pattern names, which e.g. Agda also allows. However, this is a design decision and depends on common practices inside a particular community. I believe a large part of our community comes from Haskell, and @edwinb thought it would be a good idea to disallow them to make common mistakes (e.g. misspelling a constructor name) by disallowing capitalized pattern variables.

**Comment by ahmadsalim** [comment]
@edwinb I did make a switch for this issue in #4366 😄

**Comment by edwinb** [comment]
I just wonder if that's the right solution even if it works for now...

**Comment by ahmadsalim** [comment]
@edwinb I will hold off merging until you OK it then.

I don't know what the right solution is. Another solution would possibly be to warn on unused pattern variables, instead of disallowing capitalized ones.

**Comment by edwinb** [comment]
I think it's fine to merge because it'll help legacy code run again, just that it feels a bit like a "go back to the old bug" option rather than a real solution.

Warning on unused pattern variables could help.

**Comment by nicolabotta** [comment]
Thanks for looking into this Edwin and Ahmad! As I mentioned, I am not so much concerned about legacy code (I can easily rewrite the offending functions) but rather about the impact of the rule on readability and on the usability of Idris as a specification language. Also, it seems to me that allowing
```
Finite1 : {A : Type} -> (P : A -> Type) -> Type
```
but disallowing
```
Finite1 {A} P = (a : A) -> Finite0 (P a) 
```
is not consistent. If `A` in `Finite1 {A} P = (a : A) -> Finite0 (P a) ` cannot be a valid name, then `Finite1 : {A : Type} -> (P : A -> Type) -> Type` should be disallowed as well. Otherwise it is too easy to unconsciously put forward specifications that are not implementable because of a syntax rule!
