### ISSUE TITLE
C backend fails to process large tail recursion instance

### ISSUE THREAD

**Issue by JanBessai** [idris-lang/Idris-dev#443]
See [reg022](https://github.com/JanBessai/Idris-dev/tree/TailRecursive/test/reg022) for an example.
While the other back ends yield the correct answer (500000500000), I'm getting 120762779878 from C.

**Comment by melted** [comment]
The seg fault and memory allocation issues were likely fixed with https://github.com/idris-lang/Idris-dev/pull/2138/
