### ISSUE TITLE
0xc000007b When opening the compiled program

### ISSUE THREAD

**Issue by pe200012** [idris-lang/Idris-dev#4435]
# Environment
Win10 x64  Idris 1.2.0
# Steps to Reproduce
<pre>
main : IO ()
main = return ()
</pre><pre>idris main.idr  -o main.exe</pre>
# Expected Behavior
Executed without any message.
# Observed Behavior
 "The application was unable to start correctly 0xc000007b"

**Comment by melted** [comment]
I'm pretty sure this fails because pthreads are missing. Programs built with idris requires `libwinpthread-1.dll`. It exists in mingw64/bin (or mingw32). To fix, put that in the PATH or copy the dll to the directory where the exe is. 

The experience would be better if we statically linked that.

**Comment by pe200012** [comment]
well, it did not help.

**Comment by melted** [comment]
Interesting.
