### ISSUE TITLE
Distribution + build improvements

### ISSUE THREAD

**Issue by ejconlon** [idris-lang/Idris-dev#4440]
A few months ago I had time to play with Idris and tried to work through some operational blockers from using it in a standard BigTechCo environment.  To understand how things worked, I tried to write a [simple build + package system](https://github.com/ejconlon/idream), [container defs](https://github.com/ejconlon/idr-distribution) and [package defs](https://github.com/ejconlon/idr-package-set).  Maybe the world has changed since I tried, but here are the issues I remember:

1. CI for Idris-based projects is difficult because there are no build or runtime Docker containers published. (It might be fine to just ship build containers and use them at runtime.)
2. Building Docker containers is difficult because there are no binary distributions published. (Yes, I know this is messy business, but the rest of the world seems ok doing it, and it simplifies operations.)
3. Building binary distributions is difficult because (at the time, 1.2.0) the source distribution shipped without frozen package versions. (Stackage or Nix help but I think they are overkill for this.)
4. Package installation is global by default. This makes it very difficult to work on independent projects with conflicting versions or colliding package namespaces.
5. The custom ipkg format makes it difficult to interoperate with external build tools like Bazel (or the one I wrote). Package metadata should be in a standard data format like JSON/YAML/TOML/INI/XML (pick your poison)!
6. The compiler is very sensitive to the library paths you pass and even then it still writes some files to cwd that you need to clean up. (I remember having a lot of trouble with this and had to invoke the compiler carefully.) Also, IIRC, I don't think you can separate library and install path or provide multiple library paths (necessary for using shared compiled versions).
7. Package installation does not take version into account.  (Idris seems to only allow one compiled version of a package at a time.)

I believe that solving these issues will help the community develop a robust ecosystem of libraries and applications, and that in turn will lead to increased attention, use, and contribution. Thanks for reading!

EDIT: I am happy to help solve some of these problems as I have time. I created this issue with the intention of just getting the conversation going.

**Comment by david-christiansen** [comment]
We use the Idris bug tracker to track actual bugs in Idris, rather than as a general-purpose discussion and tech support medium. Otherwise, the bug list tends to drown in other things. There aren't enough people putting enough hours into Idris right now to stay on top of a mixed bug database/discussion forum.

Would you mind taking this to the mailing list instead?
