### ISSUE TITLE
fail to run test function in `.ipkg`

### ISSUE THREAD

**Issue by xieyuheng** [idris-lang/Idris-dev#4441]
# Steps to Reproduce
https://github.com/xieyuheng/oplss-notes/blob/master/2014--ulf-norell--agda/in-idris/Day1/WithVar.idr#L85
https://github.com/xieyuheng/oplss-notes/blob/master/2014--ulf-norell--agda/in-idris/oplss--2014--ulf-norell.ipkg#L14
https://github.com/xieyuheng/oplss-notes/blob/master/2014--ulf-norell--agda/in-idris/dev#L14

# Expected Behavior
run the test

# Observed Behavior

idris version 1.2.0

```
  /home/xyh/note/oplss-notes/2014--ulf-norell--agda/in-idris (master)
./dev test
Type checking ./Preface.idr
Type checking ./Day2/Lambda.idr
Type checking ./Day1/WithVar.idr
Type checking ./Day1/WithoutVar.idr
Type checking ./Main.idr
Type checking /tmp/idris13153-0.idr
/tmp/idris13153-0.idr:9:10-11:29:
  |
9 |   main = do Main.test
  |          ~~~~~~~~~~~~ ...
When checking right hand side of Test_______.Main.main with expected type
        IO ()

When checking an application of function Prelude.Monad.>>=:
        No such variable Day1.WithVar.test
```

**Comment by MarcelineVQ** [comment]
does changing ```module WithVar```  in WithVar.idr    to ```module Day1.WithVar``` help anything?

**Comment by xieyuheng** [comment]
Thank you @MarcelineVQ  !
I am stupid!
You are my saviour!
