### ISSUE TITLE
Can't use fully qualified name?

### ISSUE THREAD

**Issue by SamuraiJack** [idris-lang/Idris-dev#4445]
For some reason, the fully qualified name `Language.WhereCondition` is not found and typecheck fails: https://gist.github.com/SamuraiJack/03ce6fcd63ef1827a2396201df56251d

It works when name is used w/o the module prefix.

Expected: Both forms expected to produce the same result.

**Comment by jacereda** [comment]
Isn't the fully qualified name `Language.SomeRec.WhereCondition`?

**Comment by SamuraiJack** [comment]
Oh, right, that works. Thanks for looking!
