### ISSUE TITLE
stack install doesn't install libraries

### ISSUE THREAD

**Issue by bonds** [idris-lang/Idris-dev#4446]
Installing idris via stack doesn't install its libraries, it just installs the binary.

# Steps to Reproduce

1. ````# mkdir /usr/local/tmp````
1. ````# echo "resolver: lts-11.5\nflags: {}\nextra-package-dbs: []\npackages: []\nextra-deps:\n- ansi-terminal-0.7.1.1\n" > /usr/local/tmp/stack-idris.yml````
1. ````# export TMPDIR=/usr/local/tmp````
1. ````# export STACK_ROOT=/usr/local/tmp````
1. ````# export STACK_YAML=/usr/local/tmp/stack-idris.yml````
1. ````# stack install --system-ghc --local-bin-path=/usr/local/bin idris````
1. ````$ rm -rf $TMPDIR````
1. ````$ idris --listlibs````

# Expected Behavior

Idris works properly after its been installed via ````stack install````, having installed its libraries in /usr/local/lib/idris.

# Observed Behavior

Installing Idris via ````stack install```` results in the libraries being left under the $SOURCE/.stack_work directory. If you remove that directory, Idris no longer has its libraries:

````
scott@server ~ ❯❯❯ idris --listlibs                       Fri 2018-05-18 09:06:00 -0700
Uncaught error: /usr/local/tmp/.stack-work/install/x86_64-openbsd/lts-11.5/8.2.2/share/x86_64-openbsd-ghc-8.2.2/idris-1.2.0/libs/: getDirectoryContents:openDirStream: does not exist (No such file or directory)
````

**Comment by jfdm** [comment]
It is not clear if you are building Idris from HEAD or calling stack as part of a global project. For the former, the behaviour you have experienced is entirely expected.

Stack install is actually an alias [1] for:

```
stack build --copy-bins
```

This only copies the executables across, and not anything else.
 
[1] https://docs.haskellstack.org/en/stable/build_command/

I cannot quite remember the expected behaviour when invoking stack to install idris as part of a global project.

**Comment by bonds** [comment]
I'm building from HEAD. Since stack install only copies the binaries but 
not the libraries...would a PR updating the docs help? I'm thinking 
something like: "stack install copies the idris binary to ~/.local/bin 
and leaves the libraries under <idris src>/.stack_work/..., which is to 
say, you need to keep your idris source directory around if you install 
it this way!"

**Comment by jfdm** [comment]
> would a PR updating the docs help? 

Indeed it would. When improving the docs we should make it clear that this is an issue affecting building from source. There might be space in our sphinx docs in the `docs` folder, but also the `INSTALL` file in the project's root folder would also need updating.

My gut tells me that when installing from source using stack there might be options for setting prefix's as seen with Cabal but I am not to sure. If you (or anyone else for that matter) can confirm/deny this ability, that would be most appreciated.

Thanks

**Comment by bonds** [comment]
How about this?

https://github.com/idris-lang/Idris-dev/pull/4449
