### ISSUE TITLE
Confining the type parameter in generic data types

### ISSUE THREAD

**Issue by nzer0** [idris-lang/Idris-dev#4453]
Hi! I am very new to this community so please correct me if this isn't the right place to ask.

I would like to define a generic data type that is parameterized by a confined group of types.
For example, I could define a generic type as follows.

```idris
data Ty1 = DefTy1
data Ty2 = DefTy2
data Ty3 = DefTy3

data GenTy : (ty:Type) -> Type where
  DefGenTy : ty -> GenTy ty
```

GenTy is currently parameterized by a `Type`, which I would like to be, let's say, only `Ty1` and `Ty2` but not `Ty3`. 

As far as I understand, "grouping" the types in idris can be only done using `interface`.
So, I could add and modify some lines as follows.
```idris
interface My ty where
  dummy : ty -> String

My Ty1 where
  dummy DefTy1 = "Ty1"

My Ty2 where
  dummy DefTy2 = "Ty2"

data GenTy : (ty:Type) -> Type where
  DefGenTy : My ty => ty -> GenTy ty
```

Then, REPL gives
```idris
> :t DefGenTy DefTy2
DefGenTy DefTy2 : GenTy Ty2
> :t DefGenTy DefTy3
Can't find implementation for My Ty3
```

So it seems to be successful. But is this the proper way? Is there any better, cleaner way?

**Comment by SamuraiJack** [comment]
Hi,

Probably better to ask this on the mailing list: https://groups.google.com/forum/#!forum/idris-lang

But what you are looking for is probably a predicate (which is how "My" interface used in your example).

```idris
data TheInputTypeIsAppropriate : Type -> Type where
    BecauseItIsType1  : TheInputTypeIsAppropriate Ty1
    BecauseItIsType2  : TheInputTypeIsAppropriate Ty2

and then
data GenTy : (ty:Type) -> Type where
  DefGenTy : ty -> {auto prf : TheInputTypeIsappropriate ty} -> GenTy ty
```

**Comment by nzer0** [comment]
Thank you so much!
Very elegant way.

I will ask it to the forum next time.
