### ISSUE TITLE
Idris uses mini-gmp despite being compiled with gmp flag set

### ISSUE THREAD

**Issue by jinbijin** [idris-lang/Idris-dev#4470]
# Additional data

OS: OSX 10.13.4 (High Sierra)
Using Idris 1.3.0 compiled with `gmp` and `ffi` flags set, installed via cabal.

# Steps to Reproduce

Compile the following file (`Main.idr`) using a version of Idris with `gmp` flag set
```idris
module Main

%include C "/usr/local/include/gmp.h"

main : IO ()
main = putStrLn "This won't compile!"
```
with `idris -o Main.o Main.idr`.

# Expected Behavior

Compiles without problems if Idris is compiled with `gmp` flag set.

# Observed Behavior

Errors during compilation, indicating some name clashes with `mini-gmp.h`, despite Idris being compiled with `gmp` flag set.

**Comment by jinbijin** [comment]
# Workaround

If in `rts/idris_gmp.h` (in the Idris folder)
```c
#ifdef IDRIS_GMP
#include <gmp.h>
#else
#include "minigmp.h"
#endif
```
is changed to
```c
#include <gmp.h>
```
then the file does compile succesfully and work, so `IDRIS_GMP` may have failed to be set during installation.

**Comment by melted** [comment]
Thanks for the report!

**Comment by melted** [comment]
Looks like it doesn't pass IDRIS_GMP when it's compiling the program. Hmm, wonder why nothing excludes minigmp from the rts build either when that is set.
