### ISSUE TITLE
Misaligned Literate Idris highlightling in `idris-mode`

### ISSUE THREAD

**Issue by fabianhjr** [idris-lang/Idris-dev#4478]
```
> data Day = Monday
>          | Tuesday
>          | Wednesday
>          | Thursday
>          | Friday
>          | Saturday
>          | Sunday
>
> next_weekday : Day -> Day
> next_weekday d = case d of
>                      Monday    => Tuesday
>                      Tuesday   => Wednesday
>                      Wednesday => Thursday
>                      Thursday  => Friday
>                      Friday    => Saturday
>                      Saturday  => Sunday
>                      Sunday    => Monday
```

# Steps to Reproduce

1. Save code as Literate.lidr
2. `idris-load-file` in Emacs with `idris-mode`

# Expected Behavior

Correct highlighting

# Observed Behavior

Highlighting shifts 2 places to the left. (Corresponding to the `> ` in the editor)

![screenshot from 2018-06-14 23-39-20](https://user-images.githubusercontent.com/303897/41450392-f4967a28-702c-11e8-8a94-84492ace79cb.png)

# Software Info

`idris --version`: 1.3.0-git:PRE
`emacs --version`: GNU Emacs 26.1

Related: #1736

Crosspost from idris-hackers/idris-mode#480

**Comment by nicolabotta** [comment]
As far as I can see, this issue is still unresolved in Idris 1.3.2, see https://github.com/idris-lang/Idris-dev/issues/4799#issue-543469766.
