### ISSUE TITLE
Sockets type mismatch

### ISSUE THREAD

**Issue by sciadopitys** [idris-lang/Idris-dev#4490]
I am trying to use https://github.com/idris-lang/Idris-dev/blob/master/libs/contrib/Network/Socket.idr.  I attempted to write a function to create and bind a given amount of sockets, but the following code does not type check due to

"When checking right hand side of initSockets with expected type
        Vect (S len) (Maybe Socket, SocketAddress)

When checking an application of function Prelude.Monad.>>=:
        Type mismatch between
                IO (Either SocketError Socket) (Type of socket fam ty pnum)
        and
                Vect (S len) a (Expected type)
        
        Specifically:
                Type mismatch between
                        IO (Either Int Socket)
                and
                        Vect (S len) a"

initSockets : Vect n Int -> Vect n ((Maybe Socket), SocketAddress)
initSockets [] = []
initSockets (x :: xs) = let curAddr = IPv4Addr 127 0 0 1
                        in do curSocket <- socket AF_INET Datagram 0
                              ?rhs8

**Comment by melted** [comment]
Doesn't look like an Idris bug.
