### ISSUE TITLE
PID of a process

### ISSUE THREAD

**Issue by sciadopitys** [idris-lang/Idris-dev#4492]
Is there a way to get the PID of a process?

**Comment by zenntenn** [comment]
If you use spawn in System.Concurrency.Channels the PID gets returned.

**Comment by sciadopitys** [comment]
What about that of the parent process?

**Comment by melted** [comment]
You can bind getpid and getppid via the ffi. 

It would be a nice inclusion in idris-posix.

**Comment by sciadopitys** [comment]
Sorry, I'm really not sure what you mean by that.

**Comment by zenntenn** [comment]
You could make the calls to the relevant C functions using this method:
http://docs.idris-lang.org/en/latest/reference/ffi.html

The bit about idris-postfix that it should be added here eventually:
https://github.com/idris-hackers/idris-posix

**Comment by melted** [comment]
Not an issue. So will close.
