### ISSUE TITLE
support aeson-1.3 to allow building with current Stackage Nightly

### ISSUE THREAD

**Issue by juhp** [idris-lang/Idris-dev#4493]
Currently idris is not in Stackage Nightly for some time due to deps version issues.
I think idris could be added to Stackage LTS 11 already.

# Steps to Reproduce
`stack --resolver nightly build idris`

# Observed Behavior
```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for idris-1.3.0:
    aeson-1.3.1.1 from stack configuration does not match >=0.6 && <1.3  (latest matching version is 1.2.4.0)
needed since idris is a build target.
```

**Comment by melted** [comment]
Thanks, I have made a PR.
