### ISSUE TITLE
IO Bool

### ISSUE THREAD

**Issue by sciadopitys** [idris-lang/Idris-dev#4503]
I would like to use a value of type IO Bool in a non-IO function.  Is this impossible?

**Comment by jfdm** [comment]
Hi @sciadopitys, we don't use the issue tracker for asking questions about Idris. If we did, we would not be able to track issues with the compiler/language effectively. I am closing this issue as a result.

We have some friendly people at #idris on the IRC channel, and our mailing list has friendly consumers as well.

Questions about language usage should be direct there. 

Thanks
