### ISSUE TITLE
Documentation : Bind to abstract types when working with FFI

### ISSUE THREAD

**Issue by doofin** [idris-lang/Idris-dev#4510]
I can't find out how do sth like 

```
data TF_Status
tfNewStatus : IO TF_Status
tfNewStatus = foreign FFI_C "TF_NewStatus" (IO TF_Status)

```

for c code : `typedef struct TF_Status TF_Status `

it complains that `When checking argument fty to function foreign: Can't find a value of type FTy FFI_C [] (IO TF_Status)`
I have checked the following but find no answer:

http://docs.idris-lang.org/en/latest/reference/ffi.html

http://docs.idris-lang.org/en/latest/tutorial/miscellany.html

when working on this project : https://github.com/doofin/tensorflow-idris

I would like to add that to documentation once I find out how to do that,thanks!

**Comment by jfdm** [comment]
Hi @doofin,

It depends on what the `C` method call `TF_NewStatus` is returning.

More likely than not, if you are not returning a supported data primitive, you will be working with a pointer that can then be registered with the C RTS.

Jan

**Comment by doofin** [comment]
the c function is 

`extern TF_Status* TF_NewStatus()`

Currently what i do is 
```
TF_Status : Type
TF_Status = Ptr 

tfNewStatus : IO TF_Status
tfNewStatus = foreign FFI_C "TF_NewStatus" (IO TF_Status) 
```
Thanks

**Comment by jfdm** [comment]
You would be better off creating a data structure to contain the returned Ptr. This will allow you to keep track, and distinguish, between different pointers.

Given that this is not really an issue with idris, nor with the documentation, I am closing this issue. If you have any further questions on how to use Idris, I would suggest going to the IRC channel, or ask the mailing list.

Thanks

jan
