### ISSUE TITLE
Windows10: GNU Multiple Precision Arithmetic Library (GMP)

### ISSUE THREAD

**Issue by pdavidow** [idris-lang/Idris-dev#4569]
For Windows10 installation, do I still need to install the GNU Multiple Precision Arithmetic Library (GMP) (as mandated at http://docs.idris-lang.org/en/latest/tutorial/starting.html?  If so, how do I get the library for Windows10?

**Comment by melted** [comment]
No, it’s not needed (on any platform). Idris can use a minimal version bundled with the idris runtime.

**Comment by melted** [comment]
As for idris on Windows, there are prebuilt binaries here: https://github.com/idris-lang/Idris-dev/wiki/Windows-Binaries

And installation instructions if you want to build it yourself: https://github.com/idris-lang/Idris-dev/wiki/Idris-on-Windows

**Comment by pdavidow** [comment]
So please update doc at http://docs.idris-lang.org/en/latest/tutorial/starting.html about mandated installation of GMP.
