### ISSUE TITLE
Does not build with cabal 2.4.0.0, breaks ghc-boot-8.6.2

### ISSUE THREAD

**Issue by testexplode** [idris-lang/Idris-dev#4596]
Idris does not build on my system.
<strike>It does also not build on an Ubuntu-system with older ghc, but the same latest cabal.</strike>
Edit: In a sandbox , it does build on ubuntu.

Perhaps the conflicts of packages happen because of the dynamic linking of haskell in Arch Linux and in Manjaro-Linux. 

# Steps to Reproduce
On Manjaro-Linux:

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.2

$ cabal --version
cabal-install version 2.4.0.0
compiled using version 2.4.0.1 of the Cabal library 
$ cabal sandbox init
...
Writing a default package environment file to
/home/user/programming/haskell/idris_sandbox/cabal.sandbox.config
Creating a new sandbox at
/home/user/programming/haskell/idris_sandbox/.cabal-sandbox

$ cabal install idris
...
cabal: The following packages are likely to be broken by the reinstalls:
Cabal-2.4.0.1
libiserv-8.6.1
ghci-8.6.2
ghc-8.6.2
ghc-boot-8.6.2
Use --force-reinstalls if you want to install anyway

# Expected Behavior
The installation shall not break ghc
idris shall be installed

# Observed Behavior
see steps to reproduce

**Comment by felixonmars** [comment]
You may want to install the idris package in the repositories instead.

**Comment by testexplode** [comment]
On Arch the package depends on numerous haskell packages. I fear they conflict with the self-compiled ones.
It should be just a hint for improvements.
