### ISSUE TITLE
Support megaparsec 7?

### ISSUE THREAD

**Issue by felixonmars** [idris-lang/Idris-dev#4602]
Would like to know if there is a plan to support megaparsec 7 soon :)

**Comment by melted** [comment]
Anybody who wants to fix it is very welcome to!

**Comment by melted** [comment]
Didn't mean to close the issue :-)

**Comment by jmorag** [comment]
I'd be interested in taking a look at this. Is it something that could be done by someone totally new to hacking on Idris?

**Comment by felixonmars** [comment]
Should be easier than someone totally new to Haskell (looking at myself).

I actually took a look before opening this issue given it's not so trivial (than the usual naming collision/change or simple argument change).

**Comment by jmorag** [comment]
I just bumped to megaparsec 7 in my [toy MicroC compiler](https://github.com/jmorag/mcc/commit/a4e57edc7dfb4d556f3a5fe7ac9ddfcbcf4f3f7e) and the diff for that was pretty trivial, but that project wasn't using any of megaparsec's source location annotation features, which is what will make this a non-trivial issue. I guess I'll take a stab at it in the next couple days and report progress here.

**Comment by melted** [comment]
@jmorag That would be great! It shouldn't be so bad, the parser is pretty straightforward, if big, this doesn't touch any of the tricky core bits of Idris.
