### ISSUE TITLE
Strange behaviour with the number 100?

### ISSUE THREAD

**Issue by timmyjose** [idris-lang/Idris-dev#4642]
**Background**: I am a beginner in Idris, and currently working through the book, "Type-driven Development in Idris" by Edwin Brady. I was just trying out some very basic operations, and saw some behaviour which I found bizarre, and quite possibly a bug.

**Version**:  
```
$ idris --version
1.3.1
```

**Note**: After discovering this strange behaviour initially with the number 100, I found out that in general, it seems to show up for numbers greater than 99, but with varying combinations, so instead of an explanation, I would like to share a small transcript of code snippets on the REPL along with notes on what I would have expected vs what the output really is:

```
Idris> 100 - 99
1 : Nat       **[ OK]**

Idris> 99 - 100
(input):1:4:When checking argument smaller to function Prelude.Nat.-:
        Can't find a value of type
                LTE 100 99    **[ OK]**

Idris> 100 - 100
(input):1:5:When checking argument smaller to function Prelude.Nat.-:
        Can't find a value of type
                LTE 100 100     **[EXPECTED: 0: Nat]**

Idris> 20 - 20
0 : Nat  **[OK]**

Idris> 99 - 99
0 : Nat   **[OK]**

Idris> 99 - 98
1 : Nat    **[OK]**

Idris> 101 - 101
(input):1:5:When checking argument smaller to function Prelude.Nat.-:
        Can't find a value of type
                LTE 101 101     **[EXPECTED: 0: Nat]**

Idris> 101 - 100
(input):1:5:When checking argument smaller to function Prelude.Nat.-:
        Can't find a value of type
                LTE 100 101   **[EXPECTED: 1: Nat]**

Idris> 101 - 99
2 : Nat  **[OK]**

Idris> 199 - 199
(input):1:5:When checking argument smaller to function Prelude.Nat.-:
        Can't find a value of type
                LTE 199 199  **[EXPECTED: 0: Nat]**

Idris> 199 - 100
(input):1:5:When checking argument smaller to function Prelude.Nat.-:
        Can't find a value of type
                LTE 100 199   **[EXPECTED: 99: Nat]**

Idris> 199 - 99
100 : Nat   **[OK]**

Idris> 987 - 112
(input):1:5:When checking argument smaller to function Prelude.Nat.-:
        Can't find a value of type
                LTE 112 987     **[EXPECTED: 875: Nat]**

Idris> 987 - 99
888 : Nat   **[OK]**
```

Can anyone please explain what's going on here, or am I missing something fundamental? Also, I tried looking at the type for `-`, and saw this:

```
Idris> :t (-)
Prelude.Interfaces.(-) : Neg ty => ty -> ty -> ty
Prelude.Nat.(-) : (m : Nat) -> (n : Nat) -> {auto smaller : LTE n m} -> Nat
```
So it looks like if I specify `100 - 100`, it automatically gets cast into `Nat`. I remember that it was **not** this behaviour before (not sure of the version).

**Comment by clayrat** [comment]
`-` requires an automatically constructed `smaller` proof which is essentially defined in the way that decrements both numbers one at a time until the left one hits zero. The default search depth for such proofs is 100.

**Comment by timmyjose** [comment]
> `-` requires an automatically constructed `smaller` proof which is essentially defined in a way that requires simultaneously decrementing both numbers by one until the left one hits zero. The default search depth for such proofs is 100.

**Comment by timmyjose** [comment]
@clayrat I'm sorry, but I don't think I fully understand. 

Two things - previously, I remember the default type while doing something like `200 - 100` or `100 - 200` to have been `Integer`. And that used to work fine. Now, it seems to default to `Nat` due to the type of `-`. is this correct? (Of course, the examples still work if I use `the` to explicitly use them as `Integer`S, but that's besides the point).

Secondly, does that mean that I cannot now have either number passed in to `-` be greater than `99`? (As in `987 - 112` as in the penultimate example of the original bug description)? 

In practical terms, what does this mean? If I want to use normal arithmetic examples on the REPL, I cannot? 

Sorry, new to Idris, so just trying to figure out if there is something fundamental I'm missing, if the behaviour change was indeed planned, or if this is a bug!
