### ISSUE TITLE
Well Typed Interpreter example does not typecheck

### ISSUE THREAD

**Issue by justjoheinz** [idris-lang/Idris-dev#4651]
# Steps to Reproduce

Following the steps at
http://docs.idris-lang.org/en/latest/tutorial/interp.html
the example does not typecheck.

The first error seems to be obvious. In:

    interpTy : Ty -> Type
    interpTy TyInt       = Integer
    interpTy TyBool      = Bool
    interpTy (TyFun A T) = interpTy A -> interpTy T

`A` and `T` are capital pattern match values which are not allowed anymore.
New problems arise at:

    lookup : HasType i G t -> Env G -> interpTy t
    lookup Stop    (x :: xs) = x
    lookup (Pop k) (x :: xs) = lookup k xs

which raises the error 

    When checking right hand side of Lambda.Term.lookup with expected type
            interpTy t
    
    Type mismatch between
            interpTy a (Type of x)
    and
            interpTy t (Expected type)

for the line `lookup Stop    (x :: xs) = x`
Please also note that idris is not able to case split on `x` at 

     lookup : HasType i G t -> Env G -> interpTy t
     lookup x y = ?hole

This has been confirmed with Atom and emacs idris mode.

I created a gist with the source as far as I got it at https://gist.github.com/justjoheinz/de294fb184c75cb305eb00c91bfa96dc

# Expected Behavior

The example should typecheck and be free of errors

# Observed Behavior

see above

**Comment by clayrat** [comment]
Strange, the whole example (after fixing the capitals in patterns) compiles for me on 1.3.1

**Comment by justjoheinz** [comment]
Can you provide a gist, so that I can try it? Or did you try with my gist?
I am also on 1.3.1, BTW


Am Mi., 30. Jan. 2019 um 12:12 Uhr schrieb Alex Gryzlov <
notifications@github.com>:

**Comment by clayrat** [comment]
Here's the gist: https://gist.github.com/clayrat/0cc5d6f942515df526e414740f93d961 but I think it's more or less identical to yours..

**Comment by justjoheinz** [comment]
Stupid me - I had 

```
    data HasType : (i : Fin n) -> Vect n Ty -> Ty -> Type where
    Stop : HasType FZ (t :: G) t
    Pop  : HasType k G t -> HasType (FS k) (u :: G) t
```

instead of

```
    data HasType : (i : Fin n) -> Vect n Ty -> Ty -> Type where
       Stop : HasType FZ (t :: G) t
       Pop  : HasType k G t -> HasType (FS k) (u :: G) t
```

With these changes the case split works as well again.
