### ISSUE TITLE
Function arguments to foreign functions are only given foreign type FFunction if the FTy is a literal

### ISSUE THREAD

**Issue by imeckler** [idris-lang/Idris-dev#468]
If I define a function

    wrap : (a -> b) -> IO (a -> b)

as

    wrap {a} {b} f =
      mkForeign (FFun "theForeignIdentityFunction" [FFunction (FAny a) (FAny b)] (FFunction (FAny a) (FAny b))) f

then the Idris compiler (`mkIty'` in particular) gives the argument the foreign type FFunction and the code generators will (hopefully) wrap the argument `f` to be callable from the foreign language. However, if the FTy is any non-immediate, then the function argument will not be wrapped in FFunction and the code generators can't wrap it. E.g.,

    wrap {a} {b} f = let funTy = FFunction (FAny a) (FAny b) in
      mkForeign (FFun "theForeignIdentityFunction" [funTy] (funTy)) f

fails.

**Comment by jfdm** [comment]
Given the new FFI is this still an issue, or are parts of this Issue still relevant?

**Comment by edwinb** [comment]
The new FFI has %inline tags which ensure normalisation, so this is no longer relevant. I'll close it.
