### ISSUE TITLE
IDE Protocol should show access modifier when using :doc

### ISSUE THREAD

**Issue by justjoheinz** [idris-lang/Idris-dev#4702]
Please attach complete source files that exhibit the issue in addition
to quoting from them here.

# Steps to Reproduce

In the repl or with any editor do the following

```
Idris> :module Data.SortedMap
*Data/SortedMap> :doc SortedMap
Data type Data.SortedMap.SortedMap : Type -> Type -> Type
    
    
Constructors:
    Empty : Ord k => SortedMap k v
        
        
    M : Ord k => (n : Nat) -> Tree n k v o -> SortedMap k v
```

# Expected Behavior

SortedMap (from contrib) has the export modifier. This is not visible in the doc string and leads to the expectation that the constructors can be used outside the SortedMap module.

# Observed Behavior

the access modifier is not shown.

**Comment by jfdm** [comment]
I might have something brewing that is related to this. I have an uncompiled patch that adds visibility information for functions. Once I get round to it, i shall see if this helps.

**Comment by jfdm** [comment]
I've finally gotten around to pushing my brewed something to #4708. Would this be sufficient for your needs?

**Comment by justjoheinz** [comment]
Yes, this sounds awesome.

Am Mi., 15. Mai 2019 um 10:22 Uhr schrieb Jan de Muijnck-Hughes <
notifications@github.com>:
