### ISSUE TITLE
Dependent Pairs can't be created with the MkSigma Constructor

### ISSUE THREAD

**Issue by Phiroc** [idris-lang/Idris-dev#4714]
Language : Idris 1.31
OS : MacOSX 10.14.4

# Steps to Reproduce

```
v0 : Sigma Nat (\n => Vect n Int)
v0 = MkSigma 2 [3,4]
```
# Expected Behavior

```
(2 ** [3,4]) : (n : Nat ** Vect n Int)
```

# Observed Behavior

```
35 | v1 : Sigma Nat (\n => Vect n Int)
   |    ^
When checking type of Main.v1:
No such variable Sigma
```

cf. _Idris Tutorial_

**Comment by LeifW** [comment]
Sorry, apparently we need to update the tutorial. `Sigma` has since been renamed in the code to `DPair`, as in "dependent pair". Its constructor is `MkDPair`

**Comment by LeifW** [comment]
Where in the tutorial did you find it calling this type `Sigma`? The older PDF version, perhaps? This should be the current tutorial afaik: http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#dependent-pairs
