### ISSUE TITLE
Publish 1.3.2 for Windows

### ISSUE THREAD

**Issue by nightscape** [idris-lang/Idris-dev#4744]
# Steps to Reproduce
1. Go to https://github.com/idris-lang/Idris-dev/wiki/Windows-Binaries
2. Look for Idris 1.3.2
# Expected Behavior
Find a downloadable Windows version for Idris 1.3.2
# Observed Behavior
Find a downloadable Windows version for Idris 1.3.1

Hey @melted!
I'd like to try compiling Idris2 on Windows, but the Windows binary version of Idris is still at 1.3.1.
Is there something I can help with to release 1.3.2 binaries for Windows?

**Comment by melted** [comment]
It's just a matter of running the release build script and updating the wiki. I'll start it now.

**Comment by melted** [comment]
Done!
