### ISSUE TITLE
Windows10: mingw/gcc required in $PATH for build to succeed

### ISSUE THREAD

**Issue by lsedlacek** [idris-lang/Idris-dev#4748]
# Steps to Reproduce
https://neon.se/idris/idris-1.3.2-win64.7z extracted to c:/bin/idris
idris foo.idr -o foo.exe
# Expected Behavior
Build succeeds by using gcc in c:/bin/idris/mingw/bin/gcc
# Observed Behavior
`gcc: rawSystem: does not exist (No such file or directory)`
Adding c:/bin/idris/mingw/bin to my path causes the build to succeed.

**Comment by melted** [comment]
Yes, this should work without PATH. I'll check it out.

**Comment by AlexIljin** [comment]
I wanted to report the same issue. This problem is not happening if I switch to the previous release v1.3.1-win64.

**Comment by melted** [comment]
Turns out I had a stray Tools_idris.hs in src after testing the tarball or something that got picked up instead of the generated one.

I have updated the binaries.

Thanks for the bug report!
