### ISSUE TITLE
Add chocolatey as a windows installation alternative into guide

### ISSUE THREAD

**Issue by KarlMae** [idris-lang/Idris-dev#4813]
I was trying to install idris on my windows and the 2 alternatives given didn't work. After meddling with error messages I remembered that I have chocolatey installed. Using chocolatey, it was a matter of searching for https://chocolatey.org/packages/idris and typing 'choco install idris' into powershell.

**Comment by nightscape** [comment]
Same for [scoop](https://scoop.sh/):
```bash
scoop install idris
```
