### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by szabi** [idris-lang/Idris-dev#4815]
This is an improvement suggestion. I understand that the error messages are formally correct. However, given the example is prominent (second listing in TDD), and they can easily pop up in the "onboarding" experiece, the error messages should guide the user right to the typo. I for one needed quite some time to find the (now blatantly obvious) source of error.

[Average.txt](https://github.com/idris-lang/Idris-dev/files/4184575/Average.txt) (Rename to .idr)

# Steps to Reproduce
(Two different routes with slightly different "observed behaviours"):

Interactively:

    idris Average.idr
    *Average> :exec

Compiling:

    idris Average.idr -o Average.exe

# Expected Behavior

An error message which is easily identified and points to the type in the `module` declaration (`main` instead of expected `Main`).

# Observed Behavior

For interactive use:

    When checking argument value to function Prelude.Basics.the:
            No such variable Main.main

For compiler use

    When checking an application of function run__IO:
            No such variable Main.main

# User experience description

The "When checking" part confused me, because neither `the`, nor `run_IO` was explicitly used in my code. Then I stared long at my lines defining `main : IO ()` telling myself "the variable *is* there".

Only a diff with the TDD example from the repo showed me the issue, but even there (using a visual diff) I first overlooked the (in this diff app: less prominently coloured) spelling difference.

**Comment by imrnk** [comment]
I am still not getting what is the issue with my handwritten code and the TDD repo's code. Can you please elaborate?

**Comment by szabi** [comment]
It's been a long time, but I think the problem is I wrote

```
module main
```

instead of 

```
module Main
```

and the error message was not helpful finding this mistake.

**Comment by gallais** [comment]
I think we can close this then because `module main` simply won't parse anymore.
