### ISSUE TITLE
Error installing Idris on Ubuntu 18.04

### ISSUE THREAD

**Issue by Jamster7777** [idris-lang/Idris-dev#4819]
# Steps to Reproduce
Fresh Ubuntu 18.04 install, following instructions from here:
https://github.com/idris-lang/Idris-dev/wiki/Idris-on-Ubuntu

# Expected Behavior
Successful install

# Observed Behavior
Everything works until the final step:

`$ cabal install idris
Resolving dependencies...
Configuring idris-1.3.2...
Failed to install idris-1.3.2
Build log ( /home/jamie/.cabal/logs/idris-1.3.2.log ):
cabal: Entering directory '/tmp/cabal-tmp-3180/idris-1.3.2'
[1 of 1] Compiling Main             ( /tmp/cabal-tmp-3180/idris-1.3.2/dist/setup/setup.hs, /tmp/cabal-tmp-3180/idris-1.3.2/dist/setup/Main.o )
Linking /tmp/cabal-tmp-3180/idris-1.3.2/dist/setup/setup ...
Configuring idris-1.3.2...
make: rawSystem: runInteractiveProcess: exec: does not exist (No such file or
directory)
cabal: Leaving directory '/tmp/cabal-tmp-3180/idris-1.3.2'
cabal: Error: some packages failed to install:
idris-1.3.2 failed during the configure step. The exception was:
ExitFailure 1
`

**Comment by melted** [comment]
Looks like it can't find `make`, so install that if you haven't.

**Comment by Jamster7777** [comment]
Thanks @melted, that did the trick! :)

**Comment by melted** [comment]
Thanks for the report, I added make to the wiki page.
