### ISSUE TITLE
Can't build 1.3.2 on windows

### ISSUE THREAD

**Issue by NickSeagull** [idris-lang/Idris-dev#4821]
Please attach complete source files that exhibit the issue in addition
to quoting from them here.

# Steps to Reproduce

## 1. Clone any codegen repo, i.e.:

* https://github.com/melted/idris-lua
* https://github.com/idris-lang/idris-emptycg
* https://github.com/edwinb/idris-php

## 2. Build it

I've tried running `cabal build` using Cabal v3 and `stack build`

# Expected Behavior

The project builds successfully

# Observed Behavior

The project doesn't compile, resulting in this error:

```text
In order, the following will be built (use -v for more details):
 - idris-1.3.2 (lib:idris) (requires build)
 - idris-emptycg-0.0.0.1 (exe:idris-emptycg) (first run)
Starting     idris-1.3.2 (all, legacy fallback)

Failed to build idris-1.3.2. The failure occurred during the configure step.
Build log (
C:\Users\nikit\AppData\Roaming\cabal\logs\ghc-8.6.5\idris-1.3.2-c670fb2fe2a8bd54dbd77a8567e4c46aaba577ae.log
):
[1 of 1] Compiling Main             ( C:\Users\nikit\dev\idris-ahk\dist-newstyle\tmp\src-9904\idris-1.3.2\dist\setup\setup.hs, C:\Users\nikit\dev\idris-ahk\dist-newstyle\tmp\src-9904\idris-1.3.2\dist\setup\Main.o )
Linking C:\Users\nikit\dev\idris-ahk\dist-newstyle\tmp\src-9904\idris-1.3.2\dist\setup\setup.exe ...
Configuring idris-1.3.2...
make: rawSystem: does not exist (No such file or directory)
cabal.exe: Failed to build idris-1.3.2 (which is required by exe:idris-emptycg
from idris-emptycg-0.0.0.1). See the build log above for details.
```

**Comment by melted** [comment]
There are build instructions at https://github.com/idris-lang/Idris-dev/wiki/Idris-on-Windows

What is needed is a bash and make, the instructions use MSYS2 to provide those. There is a powershell script to automate it too. 

Note about the prebuilt binaries: If you want to build a backend as wrote about on slack, you can't use the binary distribution as you need idris available as a library.

**Comment by NickSeagull** [comment]
I see, thanks! Will reopen if the issue persists.
