### ISSUE TITLE
Megaparsec 8 support

### ISSUE THREAD

**Issue by felixonmars** [idris-lang/Idris-dev#4826]
Idris currently doesn't build with megaparsec 8:

```
[ 59 of 115] Compiling Idris.Parser.Stack ( src/Idris/Parser/Stack.hs, dist/build/Idris/Parser/Stack.dyn_o )

src/Idris/Parser/Stack.hs:95:24: error:
    • Expecting one more argument to ‘Mark’
      Expected a type, but ‘Mark’ has kind ‘* -> *’
    • In the first argument of ‘m’, namely ‘Mark’
      In the type signature: mark :: Parsing m => m Mark
   |
95 | mark :: Parsing m => m Mark
   |                        ^^^^

src/Idris/Parser/Stack.hs:98:25: error:
    • Expecting one more argument to ‘Mark’
      Expected a type, but ‘Mark’ has kind ‘* -> *’
    • In the type signature: restore :: Parsing m => Mark -> m ()
   |
98 | restore :: Parsing m => Mark -> m ()
   |                         ^^^^
```

Would be nice to have support for the new version.

**Comment by jfdm** [comment]
For a while now, [we have set Idris' dependencies to exclude versions of Megaparsec greater than 8](https://github.com/idris-lang/Idris-dev/blob/master/idris.cabal#L324).

I do not think there are any immediate plans to support versions greater than 8 at the moment as development of Idris 1 is beginning to wind down, and not many people have the time to do large maintaince tasks. That being said, if people are willing to contribute the requisite changes then please feel free to do so.

I will close this issue as it is not really an issue per se, more of a request.
