### ISSUE TITLE
8.8 compatible release on hackage?

### ISSUE THREAD

**Issue by locallycompact** [idris-lang/Idris-dev#4838]
Hi, is it possible to release a hackage version compatible with the latest ghc? idris in nixpkgs is still marked as broken because of this.

**Comment by melted** [comment]
It might be time to do a release. But it's only @edwinb who can do those, so let's ping him.

**Comment by jfdm** [comment]
it might be opportune to think about having cabal independent releases (as well as cabal) in the near-ish future. We can use travis/ci and upload tagged releases as binaries directly to github. This is partly the reason I am looking at deb packages to compliment the macOS ipkgs; although it was motivated more by making a work thing easier. 

Alternatively there is also looking at ppa, snaps, flatpacks, chocolatly, and other package managers. However this just adds to the maintenance burden, and it would be beneficial to keep things easier for ourselves.

**Comment by melted** [comment]
The bad news is that @edwinb will not make a new release. The good news is that I have the keys and can make a new release without adult supervision.

**Comment by melted** [comment]
Released 1.3.3
