### ISSUE TITLE
"cabal install idris" fails with dependency conflict errors

### ISSUE THREAD

**Issue by dgellow** [idris-lang/Idris-dev#4845]
Hello there,

I'm trying to install the latest idris version, but get a list of dependencies conflict errors when doing the `cabal install idris`.

# Steps to Reproduce

Here you will find a Dockerfile that can be used to reproduce the issue:

```dockerfile
FROM haskell:8 as base

RUN apt-get update && apt-get -y install build-essential &&\
    cabal update && cabal install idris &&\
    apt-get remove -y build-essential &&\
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["idris"]
CMD ["--help"]
```

It can be used via:
```
$ docker build -t idris .
```

# Expected Behavior

Idris is installed sucessfully from cabal.

# Observed Behavior

Instead cabal fails with an obscure error regarding depndencies:

![image](https://user-images.githubusercontent.com/2451004/79228267-75b5d600-7e61-11ea-9d4a-f1cc02f5e277.png)

**Comment by melted** [comment]
Idris 1.3.2 doesn't work with GHC 8.8, because that requires Cabal 3.0. Try to switch the first line to `FROM haskell:8.6 as base` or use idris from git.

**Comment by dgellow** [comment]
@melted Thanks, that seems to work. It's now building :)
