### ISSUE TITLE
in interfaces.rst, replace "brackets" by "parentheses"

### ISSUE THREAD

**Issue by andreas-roehler** [idris-lang/Idris-dev#4880]
docs/tutorial/interfaces.rst, line 147

mentions brackets, where no brackets are shown. Suggest using "parentheses" instead.

# Now: Multiple constraints are written in brackets in a comma
separated list, for example:

.. code-block:: idris

    sortAndShow : (Ord a, Show a) => List a -> String
    sortAndShow xs = show (sort xs)

# Should read: Multiple constraints are written in parentheses in a comma
separated list, for example:

.. code-block:: idris

    sortAndShow : (Ord a, Show a) => List a -> String
    sortAndShow xs = show (sort xs)

# Observed Behavior

**Comment by zenntenn** [comment]
The ( ) symbols are "brackets".

**Comment by andreas-roehler** [comment]
Hmm, understanding [ ] as brackets, { } as braces and ( ) as parentheses.

**Comment by jfdm** [comment]
Just to say that you are [both correct](https://en.wikipedia.org/wiki/Bracket). It depends on if you are using British English or non-British English.

However, it is good to be clear in what we mean, and it would be good to be clearer in this regard. That is we change it to parentheses or to "round brackets".

I am happy to merge a PR offering better disambiguation here.
