### ISSUE TITLE
Lambda in place of Type

### ISSUE THREAD

**Issue by MilanKral** [idris-lang/Idris-dev#4898]
In the following example

```idris
id : a -> a
id x = x

ex1 : id
ex1 = ?eeex1

ex2 : \x => x
ex2 = ?eeex2
```

why doesn't `ex1` get a Type mismatch error ?

**Comment by joom** [comment]
From FAQ:
> If you use a name in a type which begins with a lower case letter, and which is not applied to any arguments, then Idris will treat it as an implicitly bound argument.

So `ex1 : id` is the same thing as `ex1 : {id : Type} -> id`.
