### ISSUE TITLE
Add a way to suppress setters for records

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#644]
Right now, records with dependent types don't allow generation of setters and then they complain.  Adding an annotation to suppress generation of a setter would allow the user to get rid of the warning while making it obvious in the code.

Example:

```
%no_setter(field)
record R : a -> Type where
  mkR : (field : a) -> R field
```

**Comment by edwinb** [comment]
I'm closing this because: a) we don't generate setters if they won't work now; and b) because feature requests open this long indicate it's probably wishful thinking :).

We should still make dependent record setters better, as suggested in #3664
