### ISSUE TITLE
Import sequence and "Can't disambiguate name" errors

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#659]
The program
````
> import TestC
> import TestD
```
type checks but
````
> import TestD
> import TestC
```
bails out with
````
Type checking ./TestA.lidr
Type checking ./TestC.lidr
Type checking ./TestD.lidr
TestD.lidr:9:12:When elaborating type of TestD.succsSpec1:
Can't disambiguate name: TestB.isIn, TestC.isIn, TestD.isIn
```
TestA.lidr, TestB.lidr, TestC.lidr and TestD.lidr (each of which type checks) are:

TestA.lidr:
````
> module TestA
> X : Nat -> Type
> Y : (t : Nat) -> X t -> Type
> M : Type -> Type
> step : (t : Nat) -> (x : X t) -> Y t x -> M (X (S t))
```

TestB.lidr:
````
> module TestB
> parameters (beta : Type,
>             eqeq : beta -> beta -> Bool,
>             eqeqSpec1 : (b : beta) -> so (b `eqeq` b))
>   isIn : beta -> (n : Nat ** Vect n beta) -> Bool
>   isIn b (Z ** Nil) = False
>   isIn b ((S n) ** (b' :: bs')) = eqeq b b' || isIn b (n ** bs')
```

TestC.lidr:
````
> module TestC
> import TestA
> import TestB
> eqeq : Y t x -> Y t x -> Bool
> eqeqSpec1 : (y : Y t x) -> so (eqeq y y)
> isIn : Y t x -> (n : Nat ** Vect n (Y t x)) -> Bool
> isIn {t} {x} = TestB.isIn (Y t x) eqeq eqeqSpec1
```

TestD.lidr:
````
> module TestD
> import TestA
> import TestB
> succs : X t -> (n : Nat ** Vect n (M (X (S t))))
> eqeq : M (X t) -> M (X t) -> Bool
> eqeqSpec1 : (x : M (X t)) -> so (eqeq x x)
> isIn : M (X t) -> (n : Nat ** Vect n (M (X t))) -> Bool
> isIn {t} = TestB.isIn (M (X t)) eqeq eqeqSpec1
> succsSpec1 : (x : X t) ->
>              (y : Y t x) ->
>              so ((step t x y) `isIn` (succs x))
```
I have not managed to further simplify the example. For instance, replacing TestA.lidr with
````
> module TestA
> X : Type
> Y : Type
> step : X -> Y -> X
```
and modifying TestC.lidr and TestD.lidr consistently, yields the expected behavior that is, both
````
> import TestC
> import TestD
```
and
````
> import TestD
> import TestC
```
type check.

**Comment by edwinb** [comment]
Some time in the past something got done to fix this... probably when I redid the import chasing, where I know there were errors of this form. Anyway, it behaves as I'd expect now.
