### ISSUE TITLE
Type checking complexity and deferred definitions

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#761]
The following code seems to type check in linear time in "maxColumn"
````
> module Test

> %assert_total

> Blt : Nat -> Type
> Blt b = (n : Nat ** so (n < b))
> toNat : Blt b -> Nat
> toNat = getWitness
> toVect : {b : Nat} -> (Blt b -> a) -> Vect b a

> idx : Vect n alpha -> Blt n -> alpha
> X : Nat -> Type
> viable : (n : Nat) -> X t -> Bool
> nX : (t : Nat) -> (n : Nat) -> Nat 
> xedni : (n : Nat) -> Blt (nX t n) -> (x : X t ** so (viable n x))
> maxColumn : Nat
> maxColumn = 16
> X t = Blt (S maxColumn)
> states : (t : Nat) -> Vect (S maxColumn) (X t)
> states t = toVect (\ i => i)
> cxrvs : (t : Nat) -> (n : Nat) -> (i : Nat ** Vect i (X t))
> cxrvs t n = filter (\ x => viable {t = t} n x) (states t)
> nX t n = getWitness (cxrvs t n)
> xrvs : (t : Nat) -> (n : Nat) -> Vect (nX t n) (X t)
> xedni {t} n i = (idx (xrvs t n) i ** believe_me oh)

> toVect {b = Z} _ = Nil
> toVect {b = S b'} {a = a} f = ((f (Z ** oh)) :: toVect f') where
>   f' : Blt b' -> a
>   f' (k ** q) = f (S k ** believe_me q) 
```
for values of "maxColumn" up to about 1000. What would you expect to be the type check complexity if one moves the definition of "toVect" immediately after its declaration point ?  In other words, what do you expect to be the type check complexity of
````
> module Test

> %assert_total

> Blt : Nat -> Type
> Blt b = (n : Nat ** so (n < b))
> toNat : Blt b -> Nat
> toNat = getWitness
> toVect : {b : Nat} -> (Blt b -> a) -> Vect b a
> toVect {b = Z} _ = Nil
> toVect {b = S b'} {a = a} f = ((f (Z ** oh)) :: toVect f') where
>   f' : Blt b' -> a
>   f' (k ** q) = f (S k ** believe_me q) 

> idx : Vect n alpha -> Blt n -> alpha
> X : Nat -> Type
> viable : (n : Nat) -> X t -> Bool
> nX : (t : Nat) -> (n : Nat) -> Nat 
> xedni : (n : Nat) -> Blt (nX t n) -> (x : X t ** so (viable n x))
> maxColumn : Nat
> maxColumn = 16
> X t = Blt (S maxColumn)
> states : (t : Nat) -> Vect (S maxColumn) (X t)
> states t = toVect (\ i => i)
> cxrvs : (t : Nat) -> (n : Nat) -> (i : Nat ** Vect i (X t))
> cxrvs t n = filter (\ x => viable {t = t} n x) (states t)
> nX t n = getWitness (cxrvs t n)
> xrvs : (t : Nat) -> (n : Nat) -> Vect (nX t n) (X t)
> xedni {t} n i = (idx (xrvs t n) i ** believe_me oh)
```
in "maxColumn" ? 

I'm asking the question because, on my laptop, I cannot type check the second example for "maxColumn = 32". The type checker eats up the whole memory, starts swapping and type checking stalls. 

Is this the expected behavior ? Does this imply that, in general, function definitions should be deferred as much as possible ?

**Comment by ahmadsalim** [comment]
I will close this since it seems to be closely related to #172.
