### ISSUE TITLE
Parser: commit to string literal after reading the opening quote

### ISSUE THREAD

**Issue by ziman** [idris-lang/Idris-dev#800]
Today I spent quite a while hunting a parse error that was caused by an incorrect string literal:
```Haskell
f : String
f = ...long expression...
    ...such multiline... ++ "\u" ++ ...stuff...
    ...stuff...
```
The error was reported at the beginning of the second line with a message saying that "a function definition was expected", which is very confusing, given the actual mistake.

Whenever we encounter a double quote at a point where a string literal may occur, it cannot be anything else but a string literal and we ought to commit to this choice so that potential errors arising from the literal are more informative.

**Comment by melted** [comment]
I get a
```
C:/Niklas/idris/issues/i800.idr:7:7: error: expected: "&",
    escape code, space
    "\u" ++
      ^
```
So it's fixed.
