### ISSUE TITLE
Allow overlapping instances

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#824]
The overlap check for instances should be possible to disable.

Possibilities:
1. Module-level: something like `%instance_overlap allow` at the top
2. Instance-level: an option to a particular instance to turn off the check, for example an option like `%allow_overlapping`
3. Both

I prefer 2 to 1, because it allows an overlap check in some cases, kind of like the `partial` keyword.

**Comment by Melvar** [comment]
The referenced issue was closed.

**Comment by edwinb** [comment]
I think if nobody has been enthusiastic enough to work on this for a couple of years, we should close this issue.

I'm not really convinced that there's situations which require overlapping instances that wouldn't be better dealt with in other ways, but if someone can come up with a convincing use case perhaps we should revisit this later.
