### ISSUE TITLE
Comparing strings using JavaScript backend.

### ISSUE THREAD

**Issue by ak3n** [idris-lang/Idris-dev#825]
I have a function:

``` haskell
getAttr : Element -> String -> IO (Maybe String)
getAttr (MkElem p) s = do
  status <- mkForeign (FFun "%0[%1] === undefined" [FPtr, FString] FString) p s
  if status == "false"
    then do
      e <- mkForeign (FFun "%0[%1]" [FPtr, FString] FString) p s
      return $ Just e
    else return Nothing
```

The problem is with this line:
`status == "false"`

It compiles into something like this:
`return __IDR__ClassesPreludenuintToBool(__IDRRT__EVALTC(ustatus) == "false")`
where `__IDRRT__EVALTC(ustatus)` is `false`.

**Comment by rbarreiro** [comment]
@ak3n  Bool are not primitive types in idris, hence there is no support for them in the ffi. You have to use Int and something like `(status == 0) + 0` to coerce the value.
