### ISSUE TITLE
Replacing gmp with bsdnt

### ISSUE THREAD

**Issue by nimish** [idris-lang/Idris-dev#853]
https://github.com/wbhart/bsdnt/tree/v1.0

BSDNT is a cool new bignum library with a nicer license for static linking.

GMP is a hefty dependency with LGPL issues.

It would be nice to not depend on any particular bignum implementation.

**Comment by edwinb** [comment]
If someone wants to provide a compiler flag that builds an alternative library (like we currently do with minigmp) then that's great. But also anyone who is sufficiently bothered about this will have to do it themselves, I'm afraid...
