### ISSUE TITLE
Pattern Matching against constants fails

### ISSUE THREAD

**Issue by SimonJF** [idris-lang/Idris-dev#904]
If we declare a constant, and try to pattern match, this fails. For example:

``` haskell
CONST1 : Int
CONST1 = 1

CONST2 : Int
CONST2 = 2

testFn : Int -> String
testFn CONST1 = "Const 1"
testFn CONST2 = "Const 2"
testFn _ = "Not a const"


testFn2 : Int -> String
testFn2 1 = "One"
testFn2 2 = "Two"
testFn2 _ = "Other"
```

If we attempt to evaluate

``` haskell
testFn CONST2
```

This results in "Const 1". Conversely, evaluating 

``` haskell
testFn2 CONST2
```

which doesn't have a constant on the LHS, this works as expected, returning "Two".

(warnings are also generated to this effect:)

```
Type checking ./patmatch.idr
patmatch.idr:9:1:warning - Unreachable case: testFn CONST2
patmatch.idr:9:1:warning - Unreachable case: testFn __pi_arg
```

**Comment by yfcai** [comment]
[parity]: http://docs.idris-lang.org/en/latest/tutorial/provisional.html

Is there any way to use constants in patterns without their names being rebound? In Agda, it is possible inside a dot pattern. A legitimate use case is a parity view different from the one in [Idris tutorial][parity], closer to the version in Norell and Chapman (Dependently typed programming in Agda).

```Agda
CONST1 : ℕ
CONST1 = suc zero

CONST2 : ℕ
CONST2 = suc (suc zero)

data Parity : ℕ → Set where
  even : (k : ℕ) → Parity (CONST2 * k)
  odd  : (k : ℕ) → Parity (CONST1 + CONST2 * k)


parity : (n : ℕ) → Parity n
parity zero = even 0
parity (suc n) with parity n
parity (suc .(CONST2 * k)) | even k = odd k
parity (suc .(CONST1 + CONST2 * k)) | odd k =
  subst Parity (sym $ (distrib 2 1 k)) (even (suc k))
```

This typechecks under Agda 2.4.2.3 with suitable imports. Note that when `CONST1` and `CONST2` appear inside a dot pattern, they are interpreted according to the environment and are not rebound.

**Comment by edwinb** [comment]
This should work in Idris too (without the dot) but currently doesn't for an annoying reason, which I will fix.

Idris adds dots implicitly - essentially anything which can't be matched on is considered 'Hidden' meaning that it must be solved by unification, and the result must unify with what the programmer gave. Except I seem to have implemented that in a strange way, which I'll have to investigate.
