### ISSUE TITLE
Instances on lambdas have a name capture problem

### ISSUE THREAD

**Issue by Melvar** [idris-lang/Idris-dev#968]
```idris
module Melvar.TestCase

data Foo m a = foo a

instance Functor (Foo m) where
  map = ?theMap
```
works fine. If I eta-expand `(Foo m)` to `(\a => Foo m a)`, it yields
```
./Prelude/Functor.idr:9:29:When elaborating type of Prelude.Functor.\a => Foo m a instance of Prelude.Functor.Functor, method map:
Can't convert
        a -> b
with
        Type
```
In which it seems to be trying to unify the `m` in `(\a => Foo m a)` with the named argument `m` of `map` in `Prelude/Functor.idr`, where the error message also points. (Varying the type of `m` in the definition of `Foo` produces results consistent with this hypothesis.) Changing `m` in `(\a => Foo m a)` to `μ` instead produces
```
testcase5.idr:5:29:When elaborating type of Prelude.Functor.\a => Foo μ a instance of Prelude.Functor.Functor, method map:
No such variable μ
```
where using `(Foo μ)` works fine as expected.

Observed in `Version 0.9.11.2-git:992acb4`.

**Comment by david-christiansen** [comment]
This works fine in the latest master.
