### ISSUE TITLE
Compiler behaving oddly with where clause

### ISSUE THREAD

**Issue by jedesah** [idris-lang/Idris-dev#982]
I hope this isn't something I misunderstood. But it seems to me fairly likely this is some kind of bug with the compiler.

This compiles:

    generateDraw : Vect n String -> Match
    generateDraw _ = CompositeMatch (subMatch1) (subMatch2)
        where
            subMatch1 = generateDraw ["Gen"]
            subMatch2 = generateDraw ["JR"]

However, this does not:

    generateDraw : Vect n String -> Match
    generateDraw _ = CompositeMatch (generateDraw firstHalf) (generateDraw secondHalf)
        where
            firstHalf = ["Gen"]
            secondHalf = ["JR"]

with a `No such variable n` error message

**Comment by jfdm** [comment]
Is this still an issue? or should this be closed now?
