### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by viclib** [idris-lang/Idris-dev#994]
Hello, I believe most of you will agree with me that benchmarks are really important when judging wether to use a language or not for a determinate problem. By design, I see Idris as one of the most well done languages around, but I wouldn't use it for a serious project as I have absolute no idea on how it performs - AFAIK, it could range from faster than C to slower than interpreted Python. There's just no information available. Moreover, having a set of benchmarks would be really nice to keep a track of the maturity of the implementation as well as attracting people to work on improving it.

So I leave this as a request, if you guys have some free time it would be really great to have a set of benchmarks available. (Including the JS port)

Thanks.

**Comment by jfdm** [comment]
For a while Idris has had a benchmark folder? Does this satisfy the issue? Should this issue be left open?

**Comment by edwinb** [comment]
Closing this because it's open-ended. Better to have a list of such projects on the wiki than leave them lurking as issues which are hard to discover...
